### ISSUE TITLE
子应用切换时能否保存状态

### ISSUE THREAD

**Issue by YDJSZY** [jd-opensource/micro-app#10]
如题。现在切换子应用时应用会被卸载

**Comment by bailicangdu** [comment]
默认不会保留状态，因为已经卸载了，只会保留静态资源，你可以通过display: none的形式隐藏，这样就不会触发卸载。不过卸载后保存状态理论上可以做的到，以后会加上这个功能。

**Comment by GOGOGOSIR** [comment]
> ，因为已经卸载了，只会保留静态资源，你可以通过display: none的形式隐藏，这样就不会触发卸载。不过卸载后保存状态理论上可以做的到

我有一个疑问，如果通过display：none的形式隐藏，去实现应用之间切换时的状态的保留。如果一个应用里渲染了3000个dom节点，此时我已经开启了6个应用，按照这个方案，只有一个应用是显示的，其他5个应用是隐藏的（display:none）,那会不会使得body下的DOM节点过多导致页面卡顿呢

**Comment by bailicangdu** [comment]
这是必然的，display: none是最简单直接的解决方案，如果担心多应用共存导致页面卡顿，可以在子应用卸载时将需要的数据状态上传到基座应用，再次渲染时从基座获取缓存的数据进行渲染

**Comment by GOGOGOSIR** [comment]
> 次渲染时从基座获取缓存的数据进行渲染

这个场景只限于某个应用最后离开的页面的数据缓存。如果场景如下：我先开启应用 A 的 home 和 about 页， 然后我此时从 about 页转至应用 B 的 home 页，那此时，我只缓存了应用A 的 about 页的数据，如果，我这时去切换 tab 跳转至应用 A 的 home 页，那它依然要重新获取数据，重新渲染，然而这个对于切换页面的tab来说，代价有点高

**Comment by GOGOGOSIR** [comment]
如果是 vue 2.x 接入的话，我之前的参考别人的方案是，第二次 render 的时候，直接 new Vue({ render: () => cacheInstance._vnode }), 在离开应用时，在 unmount 钩子 执行

**Comment by WWQ-CODE** [comment]
后面有规划处理子应用切换缓存问题吗？

**Comment by bailicangdu** [comment]
以后会增加这个功能，现在的重心在处理问题

**Comment by a124779683** [comment]
还是很关心这个切换缓存出来的大致时间。3Q

**Comment by bailicangdu** [comment]
> 还是很关心这个切换缓存出来的大致时间。3Q

目前还没进入排期，keep-alive 微应用有一个很致命的问题，微应用再次显示和在离开时url地址可能会不一致，导致url和页面展示不统一。在这个问题没有很好的解决方案出来之前，单纯的实现keep-alive功能是没有意义的。

**Comment by bailicangdu** [comment]
已在0.6.0版本中支持，详情请查看：https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/keep-alive
