### ISSUE TITLE
点击基座菜单 改变基座路由  无法加载子应用对应的页面

### ISSUE THREAD

**Issue by zhen-one** [jd-opensource/micro-app#100]
基座应用：react Antdesign Pro v5
micro-app 版本: 0.3.3
子应用：react 

通过点击菜单无效
浏览器中的后退按钮可以加载页面

**Comment by bailicangdu** [comment]
可以提供一个demo仓库吗

**Comment by zhen-one** [comment]
> 可以提供一个demo仓库吗
我试着从公司项目中提出来一个可以复现的版本吧

**Comment by zhen-one** [comment]
> 可以提供一个demo仓库吗
您好
demo仓库已提供 麻烦帮忙看一下
[https://github.com/q350241636/micro-apps-demo](https://github.com/q350241636/micro-apps-demo)

**Comment by bailicangdu** [comment]
好的

**Comment by bailicangdu** [comment]
每个应用的路由都是独立的，理论上无法影响其它应用，这种情况可以通过基座下发通知给子应用，子应用内部进行跳转

**Comment by zhen-one** [comment]
已解决 感谢

**Comment by HenryZhu-1988** [comment]
> 已解决 感谢

怎么解决的，可以说一下思路 ，贴个 code 嘛？

**Comment by q350241636** [comment]
> > 已解决 感谢
> 
> 怎么解决的，可以说一下思路 ，贴个 code 嘛？

我的基座应用是react17

**Comment by zhen-one** [comment]
> > 已解决 感谢
> 
> 怎么解决的，可以说一下思路 ，贴个 code 嘛？

我的是react17，就是在基座应用的页面组件加载时，派发下事件
```
  useEffect(() => {
    window.dispatchEvent(new PopStateEvent('popstate', { state: null }));
  }, [location.pathname]);
```

**Comment by jinjinwa** [comment]
> 
具体加载哪个文件呢？用的umi4.x

**Comment by jinjinwa** [comment]
具体加载哪个文件呢？用到了umi4.x
