### ISSUE TITLE
是否可支持页面内多组件引入方式（静态模块）

### ISSUE THREAD

**Issue by adntian** [jd-opensource/micro-app#1008]
## 背景
> 描述您希望改进的问题。
在有些业务场景中，可能是对某些页面进行拆解，这些页面里面有部分内容是由微前端实现的，目前可以通过引入多个micro-app来实现多块内容的展示，但如果同一个子应用在同一个页面就无法直接实现，虚拟路由会在url加参数，禁用虚拟路由是需要读取当前url，在有些业务场景下，只是一个单独页面的展示，不做跳转，使用default-page属性就可以固定当前组件显示哪个页面
这种组件级别的引入是否可以考虑一下呢

## 期望的效果

1. 组件级别引入子应用页面
2. 对url无依赖，子应用固定url地址

**Comment by bailicangdu** [comment]
你说的这种效果类似于iframe，完全独立于浏览器的一套路由。我们也在计划增加这个功能，子应用作为单个页面嵌入的场景还是挺常见的

**Comment by adntian** [comment]
这个现在如果单独引入一个也可以通过默认页面实现，但会在浏览器记录添加一个history，这个改动可能涉及比较大。。

**Comment by bailicangdu** [comment]
> 这个现在如果单独引入一个也可以通过默认页面实现，但会在浏览器记录添加一个history，这个改动可能涉及比较大。。

嗯，将子应用完全组件化嵌入，剔除路由的影响

**Comment by rhea-guoxs** [comment]
很期待这个功能，大概什么时候能发布

**Comment by bailicangdu** [comment]
新版本1.0.0-rc.4已支持，pure路由模式，使用方式：

设置单个子应用：
```html
<micro-app name='xx' url='xx' router-mode='pure'></micro-app>
```
全局设置：
```js
import microApp from '@micro-zoe/micro-app'

microApp.start({
  'router-mode': 'pure',
})
```

pure模式下子应用独立于浏览器进行渲染，即不会修改浏览器地址，也不会受其影响，其表现和iframe类似，详情参考：https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/router
