### ISSUE TITLE
目前micro-app是否支持SSR 

### ISSUE THREAD

**Issue by hzfvictory** [jd-opensource/micro-app#101]

**Comment by bailicangdu** [comment]
支持的，如果你不急的话我们会在十一之后推出ssr的案例以供参考

**Comment by youngjunning** [comment]
@bailicangdu ssr 的 Demo 有更新吗

**Comment by bailicangdu** [comment]
近期会进行补充

**Comment by youngjunning** [comment]
https://github.com/micro-zoe/micro-app-demo/tree/master/main_apps/nextjs11 这里的我有个疑问。

**Comment by youngjunning** [comment]
![image](https://user-images.githubusercontent.com/13204332/138418123-8f0873dc-a5dc-45f5-a04f-70cb8aa439c4.png)

这个是你本地的文件夹吗？

**Comment by bailicangdu** [comment]
嗯，案例还在本地调试，写完会去掉

**Comment by bailicangdu** [comment]
参考 https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/framework/nextjs
