### ISSUE TITLE
vite+.react 作为子应用，引入antd Tooltip，出现Tooltip 动态计算的style丢失

### ISSUE THREAD

**Issue by loycoder** [jd-opensource/micro-app#1012]
## 问题描述
> 问题的具体描述

## 复现步骤
1. 主应用(webpack+ react) 接入子应用(vite+ react)
2. 在页面中操作 antd 下拉菜单，

## 上传截图
单独访问子应用效果：
<img width="1252" alt="image" src="https://github.com/micro-zoe/micro-app/assets/33513180/f3e13a6a-7593-4cb5-bc98-d45d750a0094">

子应用被嵌入后效果：
![image](https://github.com/micro-zoe/micro-app/assets/33513180/2255f11e-e3cf-4cef-a7ef-4f01f123f215)

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。
https://stackblitz.com/edit/stackblitz-starters-ihwh2g?file=src%2FApp.tsx

## 环境信息
- micro-app版本：1.0.0-rc.3
- 主应用前端框架&版本：webpack:5.65.0、 react: 16.14.0
- 子应用前端框架&版本： vite: 5.0.8 、antd：4.21.7
- 构建工具&版本：主应用 webpack , 子应用: vite，版本同上描述。

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。
https://stackblitz.com/edit/stackblitz-starters-ihwh2g?file=src%2FApp.tsx

## 环境信息
- micro-app版本：1.0.0-rc.3
- 主应用前端框架&版本：webpack:5.65.0、 react: 16.14.0
- 子应用前端框架&版本： vite: 5.0.8 、antd：4.21.7
- 构建工具&版本：主应用 webpack , 子应用: vite，版本同上描述。

**Comment by bartlian** [comment]
主应用 webpack , 子应用: vite、antd 5.x，antd 日期组件也有问题

**Comment by bailicangdu** [comment]
问题已修复，升级到1.0.0-rc.4即可
