### ISSUE TITLE
子应用使用document.createElementNS()插入dom，实际插入到主应用<body>里，而非子应用<micro-app-body>里，导致子应用获取不到该dom

### ISSUE THREAD

**Issue by ssllee** [jd-opensource/micro-app#1014]
## 问题描述
> 子应用依赖包tiny-svg.js里使用document.createElementNS()插入dom，实际插入到主应用body里，没有插入到子应用<micro-app-body>里，导致子应用依赖包获取不到该dom

## 上传截图
>使用 document.createElementNS()插入如下：
![image](https://github.com/micro-zoe/micro-app/assets/10845176/a15d0a9e-fd43-48c3-a564-1e475fedd5ac)

> 使用document.createElement()插入正确如下：
![image](https://github.com/micro-zoe/micro-app/assets/10845176/cc5a920f-376b-4e51-8f54-e80b462b5131)

## 复现仓库
> 1.在https://github.com/micro-zoe/micro-app-demo demo里 child-vite子应用里写了段代码可复现该问题
> 2.代码如下home.vue：
```js
<template>
  <div>
    <button @click="handleClick">获取Dom对象</button>
  </div>
</template>

<script lang="ts" setup>
import {onMounted } from 'vue'

onMounted(() => {
  testCreateElement()
})

/**
 * 下面 createElement() 与 createElementNS() 生成对象插入 body ownerDocument 顶层对象不同  
 */
function testCreateElement() {
  const idStr = 'test-div'
  if(!document.getElementById(idStr)) {
    // const d = document.createElement('div') // 这样创建的对象会被add到子应用<micro-app-body></micro-app-body>里
    const d = document.createElementNS("http://www.w3.org/1999/xhtml","div") // 这样创建的对象会被add到主应用body里
    d.setAttribute('id', idStr)
    document.body.appendChild(d)
  }
}

const handleClick = ()=> {
   // createElement() 插入时这里可获取，createElementNS() 插入时这里 null
  const testDiv = document.getElementById('test-div')
  console.log(testDiv)
  console.log(testDiv?.ownerDocument)
}
</script>
```

## 环境信息
- micro-app版本：1.0.0-rc.0
- 主应用前端框架&版本：vite+vue3
- 子应用前端框架&版本：vite+vue3
- 构建工具&版本：

**Comment by tinymins** [comment]
![image](https://github.com/micro-zoe/micro-app/assets/1808990/9d1c4156-0fd7-49bd-8951-2881fec9a251)

实测无法复现，元素可以正常获取，需要提供复现仓库

**Comment by ssllee** [comment]
更新版本1.0.0-rc.3后该问题不存在了，感谢
