### ISSUE TITLE
子应用使用vite 切换沙盒模式报错

### ISSUE THREAD

**Issue by zhangxinGithub** [jd-opensource/micro-app#1028]
## 问题描述
> 子,父级应用为vite 版本相同 父应用为vue 子应用为react 在开发模式下无法打开子应用

## 上传截图
> <img width="1198" alt="image" src="https://github.com/micro-zoe/micro-app/assets/16219343/1541d533-3b40-47e8-a12a-92d3391f0321">
父应用
![image](https://github.com/micro-zoe/micro-app/assets/16219343/b6d4ac9f-fc65-4cc2-8854-8f00369ad4f7)
![image](https://github.com/micro-zoe/micro-app/assets/16219343/32393e70-eb35-44c7-b8ae-f18c5e6ba8e1)

**Comment by zhangxinGithub** [comment]
![image](https://github.com/micro-zoe/micro-app/assets/16219343/8b194b2f-1cb7-41f9-a81d-a973c1360939)
子项目中window.mount 也不执行

**Comment by bailicangdu** [comment]
能提供demo看一下吗
