### ISSUE TITLE
官方例子，切换到多层嵌套loading一直在

### ISSUE THREAD

**Issue by LingRen** [jd-opensource/micro-app#103]
## 问题描述
> 问题的具体描述

## 复现步骤
1. 点击multiple菜单，点击inline, 点击page2
2. 点击angular11菜单， 点击multiple菜单，点击inline

## 上传截图
> ![1632968011(1)](https://user-images.githubusercontent.com/15982348/135374424-4edf8839-1540-40b7-b98e-8da4bd53779d.png)

**Comment by bailicangdu** [comment]
已修复，稍后发版会带上
