### ISSUE TITLE
子应用可以使用哪些富文本

### ISSUE THREAD

**Issue by houliang999** [jd-opensource/micro-app#1031]
主子应用都是vite+vue3 目前我使用wangeditor for vue和tinymce都不行，请问有什么富文本编辑器可以用吗

**Comment by houliang999** [comment]
micro-app 版本是1.0.0-beta.5

**Comment by guangmang** [comment]
跟富文本编辑器没啥关系啊，我用的是tinymce

**Comment by houliang999** [comment]
> 跟富文本编辑器没啥关系啊，我用的是tinymce

我子应用iframe + keep-aliv后，在主应用切回子应用的时候，富文本编辑器原本显示的东西没了，内容也无法输入了

**Comment by houliang999** [comment]
@bailicangdu 麻烦看下这个bug，很容易复现，子应用vite+vue3,配置iframe + keepalive ，富文本tinymce，主子应用切换下，富文本的内容就消失了

**Comment by whiteMu** [comment]
> 跟富文本编辑器没啥关系啊，我用的是tinymce

请问在子应用中是如何使用tinymce？我在自己的子应用中独立运行编辑器是正常的，但是一嵌入到基座里就报Uncaught SyntaxError: Unexpected token '<' at runCode2InlineScript错误

**Comment by ahlzq** [comment]
> > 跟富文本编辑器没啥关系啊，我用的是tinymce
> 
> 请问在子应用中是如何使用tinymce？我在自己的子应用中独立运行编辑器是正常的，但是一嵌入到基座里就报Uncaught SyntaxError: Unexpected token '<' at runCode2InlineScript错误


mircro-app里面使用路径不对，加上
const baseUrl = window.__MICRO_APP_PUBLIC_PATH__.replace(/\/$/, '');
![image](https://github.com/user-attachments/assets/901abdfa-7ae7-438f-985f-dd93e3ebed67)
