### ISSUE TITLE
Vue 3.4.0 出现子应用build后micro-app组件无法渲染的问题

### ISSUE THREAD

**Issue by GGBeng1** [jd-opensource/micro-app#1032]
## 问题描述
> 问题的具体描述
子应用采用vite构建出现无法渲染的问题

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。
<img width="1163" alt="image" src="https://github.com/micro-zoe/micro-app/assets/40552498/1f03a52d-d227-4871-8a40-1e32324592d2">

## 环境信息
- micro-app版本：最新版本
- 主应用前端框架&版本：vue3.4.0&vite5.0.10
- 子应用前端框架&版本：vue3.4.0&vite5.0.10
- 构建工具&版本：vite5.0.10

**Comment by bailicangdu** [comment]
这个有设置吗 https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/framework/vue?id=_1%e3%80%81%e4%b8%bb%e5%ba%94%e7%94%a8%e4%b8%ad%e6%8a%9b%e5%87%ba%e8%ad%a6%e5%91%8a%ef%bc%8cmicro-app%e6%9c%aa%e5%ae%9a%e4%b9%89

**Comment by GGBeng1** [comment]
> 这个有设置吗 https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/framework/vue?id=_1%e3%80%81%e4%b8%bb%e5%ba%94%e7%94%a8%e4%b8%ad%e6%8a%9b%e5%87%ba%e8%ad%a6%e5%91%8a%ef%bc%8cmicro-app%e6%9c%aa%e5%ae%9a%e4%b9%89

有设置的，vue@3.3.13是没有问题的

**Comment by bailicangdu** [comment]
能提供个复现的demo吗

**Comment by GGBeng1** [comment]
> 能提供个复现的demo吗

感谢回复，没有渲染的原因找到了，是因为在这个页面下引入了microApp与micro-app冲突了，但是升级到3.4.0后，vite配置isCustomElement失效了，我去vue3的issue去看一下
