### ISSUE TITLE
We're sorry but 项目名称 doesn't work properly without JavaScript enabled. Please enable it to continue

### ISSUE THREAD

**Issue by Jason-Sunlihao** [jd-opensource/micro-app#1038]
引入子应用后报错 We're sorry but 项目名称 doesn't work properly without JavaScript enabled. Please enable it to continue

**Comment by Lionad-Morotar** [comment]
+1，我也出现了

---

和子应用的 publicPath 有关系

**Comment by zhengllingling** [comment]
我也遇到了这个问题 请问解决了吗
