### ISSUE TITLE
vite React 主应用 无法开启 vite vue3 with沙箱 以及__webpack_public_path__ is not defined

### ISSUE THREAD

**Issue by yoke0104x** [jd-opensource/micro-app#1044]
## 问题描述
> 问题的具体描述

## 复现步骤
1.  使用pnpm + monorepo + microapp + vite 实现主应用以及子应用
2.  无法使用with沙箱

## 上传截图
> 
<img width="1512" alt="image" src="https://github.com/micro-zoe/micro-app/assets/44898730/c872207d-0755-4ed8-a62e-67b84822080c">
<img width="1512" alt="image" src="https://github.com/micro-zoe/micro-app/assets/44898730/6f298be8-f8a7-4d66-b50c-c3bc5a17a263">

## 复现仓库
https://github.com/yoke0104x/micro-app-demo
## 环境信息
- micro-app版本：1.0.0-rc.3
- 主应用前端框架&版本："react": "^18.2.0",
- 子应用前端框架&版本："vue": "^3.3.11"
- 构建工具&版本："vite": "^5.0.8",

**Comment by yoke0104x** [comment]
<img width="1512" alt="image" src="https://github.com/micro-zoe/micro-app/assets/44898730/2eee299f-a7b5-482b-a9bb-921ff1a3f1f7">
<img width="1512" alt="image" src="https://github.com/micro-zoe/micro-app/assets/44898730/7283bf53-b2c8-441b-a35c-4c7b74d6eafc">
无法使用with沙箱

**Comment by shunia** [comment]
文档里好像写了vite就没法用with沙箱？不知道是不是指的你这种情况

**Comment by yoke0104x** [comment]
> 文档里好像写了vite就没法用with沙箱？不知道是不是指的你这种情况

好像是，使用iframe沙箱可以

**Comment by li1037** [comment]
子应用是vite+本地开发？是因为vite本地开发时 script标签用的是 type="module"， 而micro-app不支持esm导致的吧

**Comment by bailicangdu** [comment]
vite必须开启iframe沙箱，参考 https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/framework/vite
