### ISSUE TITLE
子应用配置UMD模式，在主应用中访问时，没有触发mount方法

### ISSUE THREAD

**Issue by silencelilili** [jd-opensource/micro-app#1047]
## 问题描述
> 问题的具体描述

## 复现步骤
1. 子应用配置UMD模式
2. 

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。
![图片](https://github.com/micro-zoe/micro-app/assets/16401197/b8425eab-44b6-4224-872f-060ce28a17ba)

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。

## 环境信息
- micro-app版本：1.0.0-beta.5
- 主应用前端框架&版本：vue3+vite
- 子应用前端框架&版本：vue3+vite
- 构建工具&版本：

**Comment by bailicangdu** [comment]
能提供一份代码吗

**Comment by silencelilili** [comment]
> 能提供一份代码吗

代码片段可以么？
![demo](https://github.com/micro-zoe/micro-app/assets/16401197/d022e784-8651-4d81-a332-0eb2229a3c17)

**Comment by bailicangdu** [comment]
看代码没有问题，可能不是这里的问题

**Comment by HLzhongxiao** [comment]
兄弟，解决了没，我也遇到同样的问题了

**Comment by silencelilili** [comment]
> 看代码没有问题，可能不是这里的问题

按照demo中的进行配置的，官方的在线demo在访问vite子应用时会有报错, 未表现出umd模式的正确运行结果。

**Comment by HLzhongxiao** [comment]
demo地址：
链接: https://pan.baidu.com/s/1ThiOQz4GQJMc8FuTH8QUmQ 
提取码: xxge

**Comment by trry-hub** [comment]
同样的问题，我也遇到了
