### ISSUE TITLE
子应用使用vue2+elementUI项目时，elementUI移除元素异常

### ISSUE THREAD

**Issue by happy-wsj** [jd-opensource/micro-app#1048]
## 问题描述
> 问题的具体描述
子应用使用vue2+elementUI项目时，elementUI移除元素异常
## 复现步骤
1.在子应用当中打开elementUI的el-dialog组件
2.审查元素，控制台报错，点击关闭时class为v-modal v-modal-leave的div模态框未能正确移除
3.同样的问题也在下拉选项，以及nprogress.js当中出现报错,导致下拉选项选项内容不能展示出来

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。
<img width="798" alt="1704702732230" src="https://github.com/micro-zoe/micro-app/assets/81739633/037d8bcf-34d7-4cbb-987d-833bccc973c6">
<img width="1021" alt="1704703016079" src="https://github.com/micro-zoe/micro-app/assets/81739633/d3c56303-337d-414e-ae4c-c12b6ad2380e">

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。

## 环境信息
- micro-app版本："@micro-zoe/micro-app": "^1.0.0-rc.3",
- 主应用前端框架&版本："vue": "^2.6.11",
- 子应用前端框架&版本："vue": "2.6.14","element-ui": "^2.15.10",
- 构建工具&版本："webpack": "^4.41.2"

**Comment by bailicangdu** [comment]
测试正常，需要提供复现案例
