### ISSUE TITLE
子应用内window.open进程卡死

### ISSUE THREAD

**Issue by LvZhenXiang** [jd-opensource/micro-app#1053]
子应用内window.open的时候_blank可以正常工作 _self时任务管理器cpu会飙升至100+ 页面卡死 没有任何报错log
现在只能让基座应用来open 期望子应用也可以使用_self 最起码不要让页面卡死

**Comment by bailicangdu** [comment]
测了一下`window.open('https://www.jd.com/', '_self')`正常执行
