### ISSUE TITLE
下一个版本希望能够给出 location、history 被代理的解决方案，通过配置参数可以向下兼容，下边的 Issue 提了快三个月了，拜托了！

### ISSUE THREAD

**Issue by jiaozhiye** [jd-opensource/micro-app#1059]
## 问题描述
> https://github.com/micro-zoe/micro-app/issues/937 

![Dingtalk_20240115163217](https://github.com/micro-zoe/micro-app/assets/22720488/0a81f10e-e370-4142-925a-77de3f1ae9e1)

**Comment by bailicangdu** [comment]
问题已修复，升级到1.0.0-rc.4版本即可
