### ISSUE TITLE
vite 使用iframe沙箱，加载微前端时会重复加载主应用

### ISSUE THREAD

**Issue by 2330450218** [jd-opensource/micro-app#1060]
## 问题描述
> vite 使用iframe沙箱，加载子应用时会重复加载主应用
## 复现步骤
获取一个Id，判断id存在加载子应用，获取到后刷新主应用，导致id丢失，子应用又重新渲染

## 上传截图
> 
![image](https://github.com/micro-zoe/micro-app/assets/70495409/e4b02865-6660-4b42-9526-bf66719b4164)
![image](https://github.com/micro-zoe/micro-app/assets/70495409/18f03916-8e4e-4eb9-828d-1c767400da18)
![image](https://github.com/micro-zoe/micro-app/assets/70495409/1b909fd2-125a-4057-8c56-ae6362c4e705)
![image](https://github.com/micro-zoe/micro-app/assets/70495409/fb6b9664-ba50-48c2-a48f-99c75b2eae26)

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。

## 环境信息
- micro-app版本：1.0.0-rc.3
- 主应用前端框架&版本：vue3.3.4
- 子应用前端框架&版本：：vue3.2.37
- 构建工具&版本：vite 4.3.9

**Comment by bailicangdu** [comment]
死循环吗
