### ISSUE TITLE
safrai 12.2 EventTarget 报错

### ISSUE THREAD

**Issue by zhoudc1995** [jd-opensource/micro-app#1064]
Promise Rejection: TypeError: function is not a constructor (evaluating 'new EventTarget()')

**Comment by tinymins** [comment]
请提供一份问题复现仓库

**Comment by zhoudc1995** [comment]
直接在ios13以下版本尝试 new EventTarget就会报错

---- 回复的原邮件 ----
| 发件人 | Emil ***@***.***> |
| 发送日期 | 2024年01月17日 15:56 |
| 收件人 | micro-zoe/micro-app ***@***.***> |
| 抄送人 | 周东晨 ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [micro-zoe/micro-app] safrai 12.2 EventTarget 报错 (Issue #1064) |

请提供一份问题复现仓库

**Comment by zhoudc1995** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/EventTarget#specifications
<img width="835" alt="image" src="https://github.com/micro-zoe/micro-app/assets/26180122/190d1934-1e36-4ed8-8e08-042fda8c4631">

**Comment by bailicangdu** [comment]
问题已修复，升级到1.0.0-rc.4版本即可
