### ISSUE TITLE
子应用无法直接获取内部的 dom 元素

### ISSUE THREAD

**Issue by lijialiang** [jd-opensource/micro-app#107]
例如，子应用原本逻辑涉及到获取页面的某个元素，但集成到微前端 ShadowDom 下，无法成功获取，请问类似的场景有什么适合解决的方案？

```js
document.getElementById('app')
```

**Comment by bailicangdu** [comment]
拿不到自身的元素？

**Comment by bailicangdu** [comment]
有可以复现的案例吗

**Comment by lijialiang** [comment]
> 拿不到自身的元素？

从原理上看子应用调用 `document` 获取是整个基座的 html，而子应用其实希望拿到的是自己本身的 html（子应用不清楚自身被 ShadowDom 集成了）

**Comment by bailicangdu** [comment]
子应用默认只能在自己内部获取元素，无法获取外部基座的元素，子应用也可以知道自己被微前端集成了

**Comment by lijialiang** [comment]
例如，子应用的 dom 结构是

```html
<div id="app"></div>
```

子应用未集成微前端时，通过 `document.getElementById('app')` 能获取到正确的 dom 元素。

集成到微前端后，dom 结构会变成

```html
#document
<html>
  <custom-element>
    #shadow-root
      <div id="app">
  </custom-element>  
</html> 
```

子应用还是通过 `document.getElementById('app')`  无法直接获取 app 元素，这样就需要通过 shadow-root 去获取 app 元素，也就是需要改动到 业务逻辑 里面的获取方式

**Comment by bailicangdu** [comment]
你说的是在使用micro-app时出现的问题吗

**Comment by lijialiang** [comment]
抱歉，发现是修改自定义元素创建 ShadowDom 引起的问题，与 micro-app 框架无关，十分感谢你的回复！
