### ISSUE TITLE
子应用样式顺序问题

### ISSUE THREAD

**Issue by QJvic** [jd-opensource/micro-app#1071]
## 问题描述
react项目独立部署时，head中，`<link href="xxx.css">`在最后，react动态生成的style如`<style data-rc-order="prependQueue" data-css-hash="1p1iyo1" data-token-hash="19gb5py">xxxxx</style>`在其上方。

在微前端micro-app-head中，这个link生成的style在最前面，导致有样式错乱问题。在chrome里手动把这个link生成的style拖动在最下面后，错误问题消失

## 复现步骤
1.独立部署时
![image](https://github.com/micro-zoe/micro-app/assets/17841191/f51cc24a-00ce-4bc5-bbfc-d2ebbd3f5f82)

2.在微前端中
![image](https://github.com/micro-zoe/micro-app/assets/17841191/710c6239-cb52-4adb-a9ee-8649c5610339)

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。

## 环境信息
- micro-app版本：1.0.0-rc.2
- 主应用前端框架&版本：react
- 子应用前端框架&版本：react
- 构建工具&版本：主应用vite，子应用craco

**Comment by bailicangdu** [comment]
看样子是走到兜底逻辑，style元素通过append插入到head最后，能提供一个demo吗

**Comment by QJvic** [comment]
@bailicangdu https://github.com/QJvic/micro-app-issue-1071.git demo链接。具体情况demo的README中有写。

**Comment by QJvic** [comment]
是否和https://github.com/micro-zoe/micro-app/issues/158 是同一问题

**Comment by QJvic** [comment]
怀疑和antd的css-in-js有关，上述那些动态插入的style标签应该是css-in-js插入的。antd版本降到4，即没有用css-in-js的版本，就没有上述动态插入的style标签，也没有样式错乱问题。

**Comment by QJvic** [comment]
antd的cssinjs插入`style`时，取`head`标签的第一个子元素在其之后追加插入。`microApp`的`invokePrototypeMethod`方法中，有

```js
/**
     * 1. If passiveChild exists, it must be insertBefore or replaceChild
     * 2. When removeChild, targetChild may not be in microAppHead or head
     */
if (passiveChild && !hijackParent.contains(passiveChild)) {
   return globalEnv.rawAppendChild.call(hijackParent, targetChild)
}
```
来进行兜底，因为主应用里`head`标签的第一个子元素不在子应用的`micro-app-head`中，所以导致插入位置错误。

**Comment by bailicangdu** [comment]
问题已修复，升级到1.0.0-rc.4即可
