### ISSUE TITLE
在同一个子应用中路由（url）切换，能否非必要触发当前应用卸载？

### ISSUE THREAD

**Issue by top319VIP** [jd-opensource/micro-app#108]
我想实现 keep-alive 功能
我看文档中写的，只要 name、url 发生变化时就会触发卸载。
但是在同一个子应用中切换路由时会触发卸载，没有什么方法阻止卸载？

**Comment by bailicangdu** [comment]
同一个子应用切换路由可以直接跳转，不需要修改url

**Comment by top319VIP** [comment]
你说的是子应用内部的跳转吧，内部跳转是没有问题的。
我的一级菜单就是一个子应用，一级菜单下面有多个二级菜单，每个二级菜单对应的就是同一个子应用的不同路由页面。
----------------------------------
|
|--- 子应用1   demo
|        |--- 菜单1（路由1）     /demo/page1
|        |--- 菜单2（路由2）    /demo/page2
|        |___菜单n（路由n）    /demo/page3
|--- 子应用2
|        |--- 菜单1（路由1）
|        |--- 菜单2（路由2）
|        |___菜单n（路由n）
-----------------------------------
基座路由：http://localhost:4320/
<micro-app name="demo" baseroute="/demo/"  url="http://localhost:4321/demo/page1"  ……>  
我在基座点击左菜单的时候不是直接修改 url 吗？

**Comment by top319VIP** [comment]
> 同一个子应用切换路由可以直接跳转，不需要修改url

@bailicangdu 你说的是子应用内部的跳转吧，内部跳转是没有问题的。
我的一级菜单就是一个子应用，一级菜单下面有多个二级菜单，每个二级菜单对应的就是同一个子应用的不同路由页面。

|
|--- 子应用1   demo
|        |--- 菜单1（路由1）     /demo/page1
|        |--- 菜单2（路由2）    /demo/page2
|        |___菜单n（路由n）    /demo/page3
|--- 子应用2
|        |--- 菜单1（路由1）
|        |--- 菜单2（路由2）
|        |___菜单n（路由n）


基座路由：http://localhost:4320/
<micro-app name="demo" baseroute="/demo/"  url="http://localhost:4321/demo/page1"  ……>  
我在基座点击左菜单的时候不是直接修改 url 吗？

**Comment by bailicangdu** [comment]
这种情况一般是通过基座下发通知，子应用内部进行跳转

**Comment by mursumomo** [comment]
我也是类似的问题，通过router-link 的to属性，直接跳转，但是发现，并没有作用。难道同一个子应用里就不能用router-link了？只能由基座下发通知，子应用内部跳转？这怕不好吧！期望能解决下这个问题。而不是每一个跳转都想着让事件通知子应用自己跳转，这得写多少兼容逻辑。期望的是子应用能最少成本的改造，而不是处处都得做兼容。这成本有点高了

**Comment by bailicangdu** [comment]
@ice-musru 同一个子应用当然可以使用router-link，这里说的是跨应用跳转，每个应用的路由都是独立的，无法相互影响

**Comment by mursumomo** [comment]
> @ice-musru同一个子应用当然可以使用router-link，这里是跨应用跳转，每个应用的都是路由独立的，无法相互影响

难道是我姿势有问题。。。emmmm,基座里面，用router-link跳转同一个子应用的不同页面，第一个打开的页面没问题，跳别的页面就不行了。。。。

**Comment by bailicangdu** [comment]
唉，基座应用和子应用是两个应用，所以是跨应用

**Comment by bailicangdu** [comment]
https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/route?id=%e5%ba%94%e7%94%a8%e4%b9%8b%e9%97%b4%e5%a6%82%e4%bd%95%e8%b7%b3%e8%bd%ac

**Comment by mursumomo** [comment]
> > @ice-musru同一个子应用当然可以使用router-link，这里是跨应用跳转，每个应用的都是路由独立的，无法相互影响
> 
> 难道是我姿势有问题。。。emmmm,基座里面，用router-link跳转同一个子应用的不同页面，第一个打开的页面没问题，跳别的页面就不行了。。。。

可能的原因：我所有的基座分配的路由，公用的是一个micro.vue的组件。因为需要动态下发每个子应用的信息，动态注册子应用。如果按照官方demo，每新增一个子应用，需要新增一个对应的路由承载组件。。。不太好实现这个动态注册的需求

**Comment by mursumomo** [comment]
> https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/route?id=%e5%ba%94%e7%94%a8%e4%b9%8b%e9%97%b4%e5%a6%82%e4%bd%95%e8%b7%b3%e8%bd%ac

谢谢大佬，应该和我想到的原因有关系，尝试给router-view加key的方式解决。会发现页面很卡，甚至会奔溃。关于服务发现，动态注册的问题，我再想想办法
