### ISSUE TITLE
angular子应用报错:xxx is not defined

### ISSUE THREAD

**Issue by stanwu-1** [jd-opensource/micro-app#1080]
基座应用是vue3,子应用是angular7.0版本，父应用点击按钮跳转至子应用报错如图：<img width="772" alt="image" src="https://github.com/micro-zoe/micro-app/assets/40417829/8ae22a99-e034-4c97-9e4c-b38ebacea7b2"> 
请问像这种类似的依赖报错要怎么解决呢

**Comment by bailicangdu** [comment]
这个报错看不出问题，有案例看一下吗
