### ISSUE TITLE
官网咋打不开了

### ISSUE THREAD

**Issue by houliang999** [jd-opensource/micro-app#1085]

**Comment by bailicangdu** [comment]
哪个官网？

**Comment by houliang999** [comment]
> 哪个官网？

https://micro-zoe.github.io/micro-app/#/ 官方文档，我之前收藏的。。

**Comment by bailicangdu** [comment]
可以正常打开

**Comment by houliang999** [comment]
> 可以正常打开

奇了怪了。。现在可以打开了。我之前一直打不开

**Comment by liuqiyu** [comment]
![image](https://github.com/micro-zoe/micro-app/assets/19789062/8d615c94-bd59-4051-a5ff-3c0b95bcf789)
的确打不开 @bailicangdu

**Comment by bailicangdu** [comment]
> ![image](https://private-user-images.githubusercontent.com/19789062/306482467-8d615c94-bd59-4051-a5ff-3c0b95bcf789.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2NjkwNDMsIm5iZiI6MTcwODY2ODc0MywicGF0aCI6Ii8xOTc4OTA2Mi8zMDY0ODI0NjctOGQ2MTVjOTQtYmQ1OS00MDUxLWE1ZmYtM2MwYjk1YmNmNzg5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIzVDA2MTIyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdjZDY4ZTVmNzEwYmQ3MzA2NzBjODQ2ZGY2OWMwNTVhODk0MmNmMjcxYTMxZWFhYjM4Mjc0YjdiNzA1ZTU2MzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5i8RA32bElfuLynRn7KduCvlzHqHKUSYQcRWLjrVJG4) 的确打不开 @bailicangdu

micro-app的官网是部署在github上的，如果打不开一般是网络问题
