### ISSUE TITLE
FireFox 浏览器下，子应用的 el-dropdown 不触发

### ISSUE THREAD

**Issue by BrignLau** [jd-opensource/micro-app#1089]
## 问题描述
子应用使用iframe模式接入的情况下，firefox 浏览器中 dropdown 不触发。chrome 正常。

## 复现步骤
1.运行demo
2.点击切换到子应用

## 上传截图
![issue1](https://github.com/micro-zoe/micro-app/assets/84120919/7386b127-c790-4924-a500-c23556f499f7)
![issue2](https://github.com/micro-zoe/micro-app/assets/84120919/4cc727c7-58a0-4c9e-a572-cd4d7ebc026d)

## 复现仓库
[复现仓库](https://github.com/BrignLau/micro-demo)

## 环境信息
- micro-app版本：1.0.0-rc.4
- 主应用前端框架&版本：vite vue3
- 子应用前端框架&版本：vite vue3
- 构建工具&版本：vite

**Comment by keuby** [comment]
[micro-zoe-micro-app-v1.0.0-rc.4.tgz](https://github.com/micro-zoe/micro-app/files/14321418/micro-zoe-micro-app-v1.0.0-rc.4.tgz)

用这个包替换 node_modules 下面的对应文件尝试一下，记得需要删除 node_modules/.vite 文件夹清除缓存。

**Comment by keuby** [comment]
理论上，https://github.com/micro-zoe/micro-app/pull/985 这个 PR 可以解决这个问题

**Comment by Lzy328** [comment]
同样的问题，火狐浏览器element Plus 的el-tooltip 和 el-popover也是不触发的。

**Comment by BrignLau** [comment]
> 理论上，#985 这个 PR 可以解决这个问题

感谢回复，不过这个 bug 在我这个项目里影响不算太大，还是等官方版本发布吧

**Comment by JieleeJie** [comment]
> [micro-zoe-micro-app-v1.0.0-rc.4.tgz](https://github.com/micro-zoe/micro-app/files/14321418/micro-zoe-micro-app-v1.0.0-rc.4.tgz)
> 
> 用这个包替换 node_modules 下面的对应文件尝试一下，记得需要删除 node_modules/.vite 文件夹清除缓存。

 线上该怎么处理呢

**Comment by JieleeJie** [comment]
https://github.com/Tencent/wujie/issues/419
https://github.com/Tencent/wujie/issues/380

可以参考下无界类似问题的解决方案，代理instanceof方法测试了一下可以解决

**Comment by marsshen77** [comment]
类似的问题，主应用子应用都使用Vite+React+Ant Design的方案，在火狐里面，子应用中的Select，DatePicker等类似的有下拉框的组件都无法渲染，报错如下。
![image](https://github.com/micro-zoe/micro-app/assets/16367144/40848209-2c8f-4291-96f2-08ef99bb7e2c)

**Comment by JieleeJie** [comment]
> [Tencent/wujie#419](https://github.com/Tencent/wujie/issues/419) [Tencent/wujie#380](https://github.com/Tencent/wujie/issues/380)
> 
> 可以参考下无界类似问题的解决方案，代理instanceof方法测试了一下可以解决

在子应用入口文件(如main.js)添加如下代码可解决。
`/**
 * 解决火狐（版本大于107）兼容性问题
 * 代理 instanceof Element 方法， 手动监测 element 是否是 dom 元素
 * */
if (
    navigator.userAgent.indexOf('Firefox') > -1 &&
    +navigator.userAgent.match(/Firefox\/([\d.]+)/)![1] > 107
) {
    Object.defineProperty(Element, Symbol.hasInstance, {
        value: function (node: any) {
            if (typeof node !== 'object' || !node) return false;
            node = node.__proto__;
            while (node) {
                // 重写 instanceof 判断逻辑
                if (
                    Object.prototype.toString.call(node) ===
                    this.prototype.toString()
                )
                    return true;
                node = node.__proto__;
            }
            return false;
        },
    });
}`

**Comment by JieleeJie** [comment]
> [Tencent/wujie#419](https://github.com/Tencent/wujie/issues/419) [Tencent/wujie#380](https://github.com/Tencent/wujie/issues/380)
> 
> 可以参考下无界类似问题的解决方案，代理instanceof方法测试了一下可以解决

在子应用入口文件(main.js)添加如下代码可解决
```
/**
 * 解决火狐（版本大于107）兼容性问题
 * 代理 instanceof Element 方法， 手动监测 element 是否是 dom 元素
 * */
if (
    navigator.userAgent.indexOf('Firefox') > -1 &&
    +navigator.userAgent.match(/Firefox\/([\d.]+)/)![1] > 107
) {
    Object.defineProperty(Element, Symbol.hasInstance, {
        value: function (node: any) {
            if (typeof node !== 'object' || !node) return false;
            node = node.__proto__;
            while (node) {
                // 重写 instanceof 判断逻辑
                if (
                    Object.prototype.toString.call(node) ===
                    this.prototype.toString()
                )
                    return true;
                node = node.__proto__;
            }
            return false;
        },
    });
}
```

**Comment by marsshen77** [comment]
> [micro-zoe-micro-app-v1.0.0-rc.4.tgz](https://github.com/micro-zoe/micro-app/files/14321418/micro-zoe-micro-app-v1.0.0-rc.4.tgz)
> 
> 用这个包替换 node_modules 下面的对应文件尝试一下，记得需要删除 node_modules/.vite 文件夹清除缓存。

测试暂无问题

**Comment by AmorDiamond** [comment]
> > [Tencent/wujie#419](https://github.com/Tencent/wujie/issues/419) [Tencent/wujie#380](https://github.com/Tencent/wujie/issues/380)
> > 可以参考下无界类似问题的解决方案，代理instanceof方法测试了一下可以解决
> 
> 在子应用入口文件(main.js)添加如下代码可解决
> 
> ```
> /**
>  * 解决火狐（版本大于107）兼容性问题
>  * 代理 instanceof Element 方法， 手动监测 element 是否是 dom 元素
>  * */
> if (
>     navigator.userAgent.indexOf('Firefox') > -1 &&
>     +navigator.userAgent.match(/Firefox\/([\d.]+)/)![1] > 107
> ) {
>     Object.defineProperty(Element, Symbol.hasInstance, {
>         value: function (node: any) {
>             if (typeof node !== 'object' || !node) return false;
>             node = node.__proto__;
>             while (node) {
>                 // 重写 instanceof 判断逻辑
>                 if (
>                     Object.prototype.toString.call(node) ===
>                     this.prototype.toString()
>                 )
>                     return true;
>                 node = node.__proto__;
>             }
>             return false;
>         },
>     });
> }
> ```

但是这个方式弹出层是直接添加在主应用的body下的，会导致子应用设置的css样式不生效，有办法将其添加到micro-app-body下吗？

![image](https://github.com/micro-zoe/micro-app/assets/22789550/1c833b04-19e5-483c-b356-1828aaaada7d)

如下图是chrome下正确的添加位置

![image](https://github.com/micro-zoe/micro-app/assets/22789550/729861b6-85ce-425d-adc0-c0458884386f)

**Comment by AmorDiamond** [comment]
> > > [Tencent/wujie#419](https://github.com/Tencent/wujie/issues/419) [Tencent/wujie#380](https://github.com/Tencent/wujie/issues/380)
> > > 可以参考下无界类似问题的解决方案，代理instanceof方法测试了一下可以解决
> > 
> > 
> > 在子应用入口文件(main.js)添加如下代码可解决
> > ```
> > /**
> >  * 解决火狐（版本大于107）兼容性问题
> >  * 代理 instanceof Element 方法， 手动监测 element 是否是 dom 元素
> >  * */
> > if (
> >     navigator.userAgent.indexOf('Firefox') > -1 &&
> >     +navigator.userAgent.match(/Firefox\/([\d.]+)/)![1] > 107
> > ) {
> >     Object.defineProperty(Element, Symbol.hasInstance, {
> >         value: function (node: any) {
> >             if (typeof node !== 'object' || !node) return false;
> >             node = node.__proto__;
> >             while (node) {
> >                 // 重写 instanceof 判断逻辑
> >                 if (
> >                     Object.prototype.toString.call(node) ===
> >                     this.prototype.toString()
> >                 )
> >                     return true;
> >                 node = node.__proto__;
> >             }
> >             return false;
> >         },
> >     });
> > }
> > ```
> 
> 但是这个方式弹出层是直接添加在主应用的body下的，会导致子应用设置的css样式不生效，有办法将其添加到micro-app-body下吗？
> 
> ![image](https://private-user-images.githubusercontent.com/22789550/329748657-1c833b04-19e5-483c-b356-1828aaaada7d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0MDg5MjEsIm5iZiI6MTcxNTQwODYyMSwicGF0aCI6Ii8yMjc4OTU1MC8zMjk3NDg2NTctMWM4MzNiMDQtMTllNS00ODNjLWIzNTYtMTgyOGFhYWFkYTdkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTExVDA2MjM0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM0MWRjMjZlOTczYjYyYTU1MWZmYjdmMDdlZTc2YmEyNzA0MWU2Yzg1MDJmNWVmZThmYmFlYjEyMTQ0OTA3ZmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Y3keXLMCcYH-17UCo27I_nN2zqcwS8gBtR35NIVc-jc)
> 
> 如下图是chrome下正确的添加位置
> 
> ![image](https://private-user-images.githubusercontent.com/22789550/329748565-729861b6-85ce-425d-adc0-c0458884386f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0MDg5MjEsIm5iZiI6MTcxNTQwODYyMSwicGF0aCI6Ii8yMjc4OTU1MC8zMjk3NDg1NjUtNzI5ODYxYjYtODVjZS00MjVkLWFkYzAtYzA0NTg4ODQzODZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTExVDA2MjM0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2MGExOThmYTg3NDllZmY2YzM1ZWY1N2JlMzYwZTdlZjE1MTNlMTIwNWY1MTdlOWQ1MmQ4NGI2NGI5NzI1N2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9QefAubLs4bb3cVeuP5M6_horYhZh4QHmny6ns4CqQM)

目前判断是微前端框架内的火狐环境时，通过设置ConfigProvider getPopupContainer配置，强制设置为micro-app-body标签。

`
<ConfigProvider
          locale={zh_CN}
          getPopupContainer={(node) => {
            if (FIX_FIREFOX_ANT_POPUP) {
              return document.querySelector('micro-app-body') || document.body
            }
            return document.body
          }}
        >
    <App />
</ConfigProvider>
`
