### ISSUE TITLE
子应用里有弹窗时,弹窗不能覆盖整个屏幕

### ISSUE THREAD

**Issue by wangxm87** [jd-opensource/micro-app#109]
如附件所示,子应用单独跑起来的时候弹窗可以覆盖整个浏览器窗口,但是如果嵌到主应用中,弹窗只能在外层容器的宽高范围内显示,请问下这个怎么解决呢?
![子应用](https://user-images.githubusercontent.com/24665567/136876698-c2adb163-3b98-4094-b500-8dc3279bb34d.jpg)
![子应用嵌到主应用](https://user-images.githubusercontent.com/24665567/136876709-079e681f-f232-4a1e-b067-e5346bcd7c40.jpg)

**Comment by inier** [comment]
这是个问题，虽然，结构整合到了一个页面，但布局还是会受限制，这跟iframe的表现还是一样的

**Comment by SupremeZJw** [comment]
@wangxm87 我目前也有这个问题，请问您是如何修复的？
