### ISSUE TITLE
主应用可以劫持子应用的网络请求吗

### ISSUE THREAD

**Issue by dl9528** [jd-opensource/micro-app#1090]
我想主应用劫持子应用的请求，也就是页面是一个服务器的，后端服务在另外一台服务器上，有这个功能吗
我看到可以通过fetch来劫持静态资源，网络请求有没有办法

**Comment by lizesheng0313** [comment]
这个是不是用Nginx来处理更好一些

**Comment by dl9528** [comment]
> 这个是不是用Nginx来处理更好一些

这个子应用被好几个主应用引用 所以用nginx不太合适

**Comment by bailicangdu** [comment]
目前是不可以的
