### ISSUE TITLE
重复调用vite client，调用前端资源后 取消问题

### ISSUE THREAD

**Issue by cyj19897** [jd-opensource/micro-app#1091]
## 问题描述
> 问题的具体描述
基座及子应用同为 vite，加载子应用时会在启动一次基座vite，然后取消

## 复现步骤
1.启动基座应用
2.启动子应用，点击菜单访问

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。
![image](https://github.com/micro-zoe/micro-app/assets/159004892/1b216b49-3cb3-46fa-807e-8c7fff173fe8)

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。
https://github.com/cyj19897/vue-demo.git
## 环境信息
- micro-app版本：1.0.0-rc.4
- 主应用前端框架&版本：vite-vue3
- 子应用前端框架&版本：vite-vue3/vite-vue2
- 构建工具&版本：vite 4 vue router4

**Comment by cyj19897** [comment]
进入后 分别 run i  run dev 启动后点击菜单 testvite 可复现

**Comment by bailicangdu** [comment]
参考 https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/sandbox?id=iframe-source
