### ISSUE TITLE
加载子应用奇怪的跨域问题

### ISSUE THREAD

**Issue by 826327700** [jd-opensource/micro-app#110]
子应用打包后的js文件是放在腾讯云cos存储，出现了一下奇怪的现象：![image](https://user-images.githubusercontent.com/23014381/136903275-ec721ed0-e5ca-415a-8f5b-fa47948f941e.png)有些js文件加载成功，有些js文件加载报跨域问题。奇怪，同一个桶，同一个目录下的文件，为什么会这样？

![image](https://user-images.githubusercontent.com/23014381/136903035-8c55e23c-4acd-49c6-bcf4-9339693c533c.png)

**Comment by bailicangdu** [comment]
这种情况一般是服务器配置问题

**Comment by yichonglai** [comment]
> “这种情况一般是服务器配置问题” 能具体描述下吗？  
这边也遇到了个类似的问题（现象：在启用缓存的情况下，单独访问过子应用（访问微前端环境前或后），再在微前端环境访问应用会遇到静态资源跨域问题；但在不启用缓存或启用缓存访问微前端之前（或之后）没单独访问过子应用的情况下能正常访问）。

**Comment by yichonglai** [comment]
> 这种情况一般是服务器配置问题

“这种情况一般是服务器配置问题” 能具体描述下吗？
这边也遇到了个类似的问题（现象：在启用缓存的情况下，单独访问过子应用（访问微前端环境前或后），再在微前端环境访问应用会遇到静态资源跨域问题；但在不启用缓存或启用缓存访问微前端之前（或之后）没单独访问过子应用的情况下能正常访问）。

**Comment by small-wolf-dog** [comment]
这个问题解决了吗

**Comment by small-wolf-dog** [comment]
> 这种情况一般是服务器配置问题

这个问题解决了吗
