### ISSUE TITLE
unhandledrejection失效的问题

### ISSUE THREAD

**Issue by philipxiaoxi** [jd-opensource/micro-app#1102]
## 问题表现
子应用中发起的请求，取消后会在控制台输出`Uncaught(in promise)`
然后我会使用`window.addEventListener('unhandledrejection', callback)`对错误信息进行屏蔽，发现失效。

在主应用、子应用都尝试写 `window.addEventListener('unhandledrejection', callback)` 也是不生效，还是会打印。

经过测试是相关错误抛出时，不会走进这个方法函数。

**Comment by bailicangdu** [comment]
问题已修复，发布下个版本时会带上

**Comment by bailicangdu** [comment]
更新到[1.0.0-rc.5](https://github.com/micro-zoe/micro-app/releases/tag/v1.0.0-rc.5)版本即可
