### ISSUE TITLE
跨域问题

### ISSUE THREAD

**Issue by small-wolf-dog** [jd-opensource/micro-app#1107]
## 问题描述
> 问题的具体描述

## 复现步骤
1.
2.

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。
![7DE1D4E2B6D5F3D0AA5D89DC03F3C2BE](https://github.com/micro-zoe/micro-app/assets/37438780/05ba02dd-4393-4cdc-9127-43a08a53e123)

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。

## 环境信息
- micro-app版本：
- 主应用前端框架&版本：
- 子应用前端框架&版本：
- 构建工具&版本：

**Comment by small-wolf-dog** [comment]
请问这个问题怎么解决的

**Comment by tinymins** [comment]
截图显示是本地调试时候获取腾讯云上的js文件跨域了，需要看看腾讯云那边是否可以支持将本地调试地址加入跨域白名单

**Comment by trry-hub** [comment]
解决了么

**Comment by bailicangdu** [comment]
服务器问题，检查一下服务器是否配置跨域、如果有多台服务器检查是否都设置了跨域

**Comment by trry-hub** [comment]
> 服务器问题，检查一下服务器是否配置跨域、如果有多台服务器检查是否都设置了跨域

我的主、子应用都是本地环境，有其他的可能么

**Comment by bailicangdu** [comment]
> > 服务器问题，检查一下服务器是否配置跨域、如果有多台服务器检查是否都设置了跨域
> 
> 我的主、子应用都是本地环境，有其他的可能么

报错截图发一下看看

**Comment by trry-hub** [comment]
> > > 服务器问题，检查一下服务器是否配置跨域、如果有多台服务器检查是否都设置了跨域
> > 
> > 
> > 我的主、子应用都是本地环境，有其他的可能么
> 
> 报错截图发一下看看

![image](https://github.com/micro-zoe/micro-app/assets/67309192/a7c62936-23c0-433f-b9ca-142c133dba65)

**Comment by bailicangdu** [comment]
@trry-github 如果跨域请求带cookie，那么Access-Control-Allow-Origin不能设置为*，必须指定域名，同时设置Access-Control-Allow-Credentials: true 
比如：
```js
"Access-Control-Allow-Credentials": true,
"Access-Control-Allow-Origin": req.headers.origin
```

**Comment by trry-hub** [comment]
@bailicangdu 我在主应用中的设置如下
![image](https://github.com/micro-zoe/micro-app/assets/67309192/4a0bca92-0753-4f53-9982-21df2b0ce4af)


主应用vue2 + webpack，子应用 vue3 + vite，还是报错

**Comment by bailicangdu** [comment]
在子应用设置，origin为主应用域名
