### ISSUE TITLE
请问基座 document 上挂载的 querySelector 方法也被重写是出于什么考虑呢？

### ISSUE THREAD

**Issue by lkiarest** [jd-opensource/micro-app#1108]
你好，

因为在项目中遇到 mobx 共享store 的时候， reaction 副作用导致基座中的 querySelector 被子应用影响了~~

可以了解下基座中的 document 这个方法如果不重写会出现什么问题吗？

**Comment by lkiarest** [comment]
![image](https://github.com/micro-zoe/micro-app/assets/2672975/7c09b4b3-2113-4ac0-b8ab-3c869b3a97c1)
主要是想了解下这个地方的实现，是否是因为考虑子应用里可能意外引用到基座的 document 才加了一个保护呢？

**Comment by gaojiangtao-git** [comment]
你可以加下群  更方便咨询

**Comment by bailicangdu** [comment]
元素作用域绑定，确保元素不会逃逸
