### ISSUE TITLE
micro-app组件循环渲染

### ISSUE THREAD

**Issue by wdzhao3** [jd-opensource/micro-app#111]
## 问题描述
>vue3下 通过vue addroute添加了一条路由，跳转过去，在没有使用micro-app的情况下正常，一旦使用<micro-app>就是一直循环

## 复现步骤
1.
2.

## 上传截图
>  
[https://s3.bmp.ovh/imgs/2021/10/7b53fa850b91749b.png](url)
[https://s3.bmp.ovh/imgs/2021/10/abae5fb547eb5127.png](url)

## 环境信息
- micro-app版本：0.3.3
- 基座应用的前端框架和版本：vue3.2
- 子应用的前端框架和版本：vue2
- 构建工具&版本：

**Comment by bailicangdu** [comment]
在vue2、3，vue-router3、4下都尝试过，没有问题，可以提供一个可复现的demo吗？

**Comment by wdzhao3** [comment]
抱歉，代码应该是没问题的，好像是我同一个文件夹下多个文件的命名，microApp、microApp_xx，这样，我将microApp重命名microApp_bb这样
