### ISSUE TITLE
@1.0.0-rc.4中vue项目router-view 设置了 :key="$router.fullpath"然后应用来回加载子应用，无限循环

### ISSUE THREAD

**Issue by qinxiaozhu** [jd-opensource/micro-app#1114]
主应用中配置了两个菜单，对应两个不同地址：菜单A：子应用Sub的路由a(path: /sub-app-a?sub-app=/a) 菜单B：子应用Sub的路由b(path: /sub-app-b?sub-app=/b) 当点击A菜单可以正常访问，此时切换到菜单B时，浏览器地址栏中就会出现/sub-app-b和/sub-app-b?sub-app=/a之间不停闪烁

**Comment by bailicangdu** [comment]
闪烁问题就是循环刷新问题，在初始化渲染时可能存在，是因为router-view的key设置问题。但切换路由导致的循环刷新问题没有遇到过，能提供一个复现的demo吗

**Comment by qinxiaozhu** [comment]
![screenshot-20240314-152115](https://github.com/micro-zoe/micro-app/assets/17525624/fe4f92df-18ea-4cf1-9d23-ff8bbaef2b17)
现在貌似就是这个问题导致一直在卸载加载，我需要怎么处理~

**Comment by qinxiaozhu** [comment]
router-view的key为this.$route.fullPath所以一直在刷新，换成this.$route.path就好了O(∩_∩)O~

**Comment by qinxiaozhu** [comment]
router-view 的key从"$route.fullpath"改成"$route.path"好像就好了

**Comment by duriann** [comment]
为什么我写成了route.path还是不行。。

**Comment by bailicangdu** [comment]
> 为什么我写成了route.path还是不行。。

改成route.name试试
