### ISSUE TITLE
基座react，接入vue2项目和react项目，同一个应用不同页面的跳转问题

### ISSUE THREAD

**Issue by YuriPLSk** [jd-opensource/micro-app#1117]
我的主服务（react）配了3个link
```
<Link to="/A#/page1" ></Link>
<Link to="/B#/page2" ></Link>
<Link to="/B#/page3" ></Link>
```
主服务路由配置大概如下
```
<Routes>
  <Route path="/A" element={comA}/>
  <Route path="/B" element={comB}/>
</Routes>
```
大致如上，三个link分别指向A服务（react）page1，B服务（vue2）page2，B服务page3，现在遇到问题是12，13间页面切换没问题，但是23间页面切换除了url变话，页面内容无变化，控制台无报错。会是什么原因导致的呢

**Comment by gaojiangtao-git** [comment]
建议提供复现demo出来  方便作者排查问题

**Comment by tinymins** [comment]
主应用是否有通知子应用？子应用没有跨应用时切换路由，主应用需要通知子应用，示例代码：

https://github.com/micro-zoe/micro-app-demo/blob/0cbd0abcc2165b14041aa0d5101f88999bd02f08/main_apps/vue2/src/components/sidebar.vue#L143-L150

**Comment by bailicangdu** [comment]
主应用控制子应用内部跳转要使用micro-app提供的方法，参考 https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/router?id=%e5%af%bc%e8%88%aa
