### ISSUE TITLE
主应用嵌入子应用，子应用又嵌入主应用的独立页面，控制台会报错 Unkown custom element <micro-app>

### ISSUE THREAD

**Issue by philipxiaoxi** [jd-opensource/micro-app#1119]
## 问题描述
主应用嵌入子应用，
该子应用有一个弹窗只需要嵌入主应用的一个独立页面。
此时，子应用控制台会报错 Unkown custom element <micro-app>。
但实际上子应用嵌入主应用是正常加载完毕的。

**Comment by philipxiaoxi** [comment]
配置忽略可以解决问题，但理论上我是new Vue 之前start的

**Comment by bailicangdu** [comment]
https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/framework/vue?id=_1%e3%80%81%e4%b8%bb%e5%ba%94%e7%94%a8%e4%b8%ad%e6%8a%9b%e5%87%ba%e8%ad%a6%e5%91%8a%ef%bc%8cmicro-app%e6%9c%aa%e5%ae%9a%e4%b9%89
