### ISSUE TITLE
Invalid event arguments: event validation failed for event "click".

### ISSUE THREAD

**Issue by 2840365628** [jd-opensource/micro-app#1120]
## 问题描述
> 问题的具体描述
Invalid event arguments: event validation failed for event "click".
## 复现步骤
1. <el-button @click="back">回到著应用</el-button>
2.

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。

## 环境信息
- micro-app版本：1.0.0-rc.4
- 主应用前端框架&版本：3.4.3
- 子应用前端框架&版本：3.4.3
- 构建工具&版本：vite 5.0

**Comment by tinymins** [comment]
请提供一份可复现的精简的代码仓库地址

**Comment by 2840365628** [comment]
> Hello @lcyhyl. In order to facilitate location and troubleshooting, we need you to provide a realistic GitHub repository. 您好 @lcyhyl, 为了方便定位和排查问题，我们需要您提供一个重现实例，请提供一个尽可能精简的 GitHub 仓库地址。

和已关闭的#756 问题一样，是否有其它方法

**Comment by 2840365628** [comment]
> 请提供一份可复现的精简的代码仓库地址

和已关闭的#756 问题一样，是否有其它方法
