### ISSUE TITLE
接入的子应用向后端发送的数据仍然是父应用的url

### ISSUE THREAD

**Issue by sundael** [jd-opensource/micro-app#1121]
现在子应用能独立运行，前后端完备，但是接入微前端之后，向后端发送的的路由是父路径的请求，请问要在哪里配置呢？

**Comment by bailicangdu** [comment]
子应用使用绝对地址请求即可

**Comment by sundael** [comment]
我在使用一个页面多应用激活的时候，点击接入的子应用登陆按钮，重定向到了新的url，子应用占整个页面，能实现像iframe还在原来的页面，只有这个子应用内容变化的功能吗？
