### ISSUE TITLE
子应用（vite子应用）的入口文件添加了<script>const global = globalThis</script>,在主应用中加载这个子应用的时候，会报referenceerror global is not defined，如何解决。

### ISSUE THREAD

**Issue by jzm-123** [jd-opensource/micro-app#1122]
## 问题描述
> 问题的具体描述

## 复现步骤
1.
2.

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。

## 环境信息
- micro-app版本：
- 主应用前端框架&版本：
- 子应用前端框架&版本：
- 构建工具&版本：

**Comment by bailicangdu** [comment]
使用`window.global = globalThis`定义
