### ISSUE TITLE
主应用改变 url，子应用感知不到变化，无法渲染对应的页面

### ISSUE THREAD

**Issue by createYourFirst** [jd-opensource/micro-app#1128]
尝试在不同的  父路由下，只使用一个 micro-app 标签，但是micro-app 无法感知 父应用 url 的变化，去渲染对应的 子应用页面；

**Comment by tinymins** [comment]
父应用有通知子应用吗？
https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/router?id=%e5%af%bc%e8%88%aa

**Comment by bailicangdu** [comment]
参考 https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/router?id=%e5%af%bc%e8%88%aa

**Comment by createYourFirst** [comment]
目前的解决方案是，父应用router.path 改变时，去同步改变子应用的路由
