### ISSUE TITLE
偶现子应用内容变成了主应用

### ISSUE THREAD

**Issue by xjmforweb** [jd-opensource/micro-app#1129]
## 问题描述
> 问题的具体描述

## 复现步骤
1. 一个如下结构的页面
![image](https://github.com/micro-zoe/micro-app/assets/23021279/889d742c-702b-47fa-a552-f99a0cec9793)
2.点击下一页的时候，偶尔会出现micro-app加载的子应用内容变成了主应用的内容，但是接收到了参数（microData）。看了下dom树上iframe节点上绑定的src值是对的。
3.麻烦大佬排查一下这块的代码逻辑是否有问题，会导致上述情况

## 环境信息
- micro-app版本：1.0.0-rc.4
- 主应用前端框架&版本：vue2：2.7.16，webpack
- 子应用前端框架&版本：react18.2+vite
- 构建工具&版本：

**Comment by xjmforweb** [comment]
上一页下一页只是把pageKey++，然后改变了microData的数据，store里的url一直没变

**Comment by xun1224** [comment]
@xjmforweb出现了同样问题，不知道可解决了呢？
