### ISSUE TITLE
1.0.0-rc.4版本，不使用虚拟路由的情况下，子应用跳转，路由变化，页面内容没变

### ISSUE THREAD

**Issue by Yulingsong** [jd-opensource/micro-app#1132]
## 问题描述
> 问题的具体描述
主应用内嵌子应用，使用的版本是rc.4 版本，不使用虚拟路由的情况下，子应用跳转，路由发生变化，子应用内容未变。
## 复现步骤
1.
2.

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。
<img width="2084" alt="image" src="https://github.com/micro-zoe/micro-app/assets/13497831/89b2ce6b-7804-4ff8-a46f-e6644bf5b63c">

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。
本地随意期两个代码库就能复现出来

## 环境信息
- micro-app版本：1.0.0-rc.4
- 主应用前端框架&版本：vue3+vite
- 子应用前端框架&版本：react+vite+react router v6
- 构建工具&版本：vite

**Comment by bailicangdu** [comment]
子应用怎么跳转的？

**Comment by Yulingsong** [comment]
> 子应用怎么跳转的？

```
import { Card, Button } from 'antd'
import { useNavigate } from 'react-router-dom'

const Home: React.FC = () => {
  const navigate = useNavigate()

  return (
    <div>
      页面1
      <Button onClick={()=>{
        navigate('/home2')
      }}>跳转到页面2</Button>
    </div>
  )
}
export default Home

```

**Comment by bailicangdu** [comment]
demo能提供一下吗

**Comment by Yulingsong** [comment]
> home2

react 是子应用，vue的是基座。试一下看看呢


[template-react-ts.zip](https://github.com/micro-zoe/micro-app/files/14635234/template-react-ts.zip)
[template-vue-ts.zip](https://github.com/micro-zoe/micro-app/files/14635235/template-vue-ts.zip)

**Comment by Yulingsong** [comment]
> demo能提供一下吗

此外还发现一个问题，就是子应用路由变化的时候，
```
microApp.router.beforeEach((to, from, appName) => {

})
```
没触发，这个在rc3里是没问题的。rc4就不行

**Comment by MrWeilian** [comment]
你好，同 react+vite+react router v6 子应用通过 navigate 跳转无变化问题。如果子应用单独运行是正常切换的~~

**Comment by bailicangdu** [comment]
问题已修复，近期会更新，感谢反馈

**Comment by bailicangdu** [comment]
临时解决方案：将`:disable-memory-router="true"` 改为 `router-mode='native-scope'`

**Comment by Yulingsong** [comment]
> 临时解决方案：将`:disable-memory-router="true"` 改为 `router-mode='native-scope'`

大致什么时候能发一版呢？我这重度依赖microapp。业务场景导致不能使用虚拟路由。

**Comment by Lie8466** [comment]
> 临时解决方案：将`:disable-memory-router="true"` 改为 `router-mode='native-scope'`

您好，请问什么时候发版呢？我也遇到这个问题了

**Comment by jzm-123** [comment]
请问已经发布了吗？还是存在这样的问题

**Comment by bailicangdu** [comment]
已修复，更新到[1.0.0-rc.5](https://github.com/micro-zoe/micro-app/releases/tag/v1.0.0-rc.5)版本即可
