### ISSUE TITLE
移动端应用micro，使用虚拟路由，基座跳转子应用异常

### ISSUE THREAD

**Issue by inlineHz** [jd-opensource/micro-app#1133]
基座使用虚拟路由跳转子应用
microApp.router.push({ name: 'house', path: '/test' })，
会报子应用不存在或处于非活跃状态
“navigation failed, app does not exist or is inactive”
![image](https://github.com/micro-zoe/micro-app/assets/83279197/44ccb47f-adb2-48ee-936e-d51982c14ca5)
我对此存有一点疑惑，可以告诉我应该怎么配置可以避免这个错误吗。

**Comment by bailicangdu** [comment]
确保子应用已经渲染后再调用这个api

**Comment by inlineHz** [comment]
> 确保子应用已经渲染后再调用这个api

怎么配置可以确保子应用在跳转前就完成渲染，使用预加载吗，可预加载会产生不必要的性能损耗。
在路由跳转前 不清楚要访问哪个子应用。

**Comment by YuriPLSk** [comment]
你好，请问解决了吗？我也遇到了同样的问题，我经过尝试发现，通过预加载只是加载了子应用的资源，然而并没有实际激活/渲染。然后看到官网API中提供了手动渲染的方法-renderApp，通过传参配置来手动渲染出子应用，这时就可以实现跳转。
但是会牵扯到另外一个问题，菜单层切换没问题，在应用层切换时，因为不同的应用挂在同一个dom节点内，所以每次要把dome清空，再判断点击的子应用是否渲染，若渲染则直接跳转，否则renderApp。
我不认为这是一个好方法，因为对内存和性能存在着一定的影响，但我目前没有想到好的方法。

**Comment by bailicangdu** [comment]
<img width="832" alt="image" src="https://github.com/micro-zoe/micro-app/assets/20297227/76ff7566-e0ba-42ab-9c63-339b6758a2b9">，参考 https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/life-cycles

**Comment by bailicangdu** [comment]
也可以通过getActiveApps判断子应用是否处于活跃状态，参考[getActiveApps](https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/api?id=getactiveapps)
