### ISSUE TITLE
虚拟路由使用 pure 模式，子应用内 location 变更/方法调用直接同步到主应用 window.location 导致页面跳转

### ISSUE THREAD

**Issue by youngBrain1893** [jd-opensource/micro-app#1135]
### 依赖版本信息
- @micro-zoe/micro-app@1.0.0-rc.4
- history@4.10.1

### 问题现象
- 虚拟路由使用 **pure** 模式
- 沙箱使用 **iframe** 模式
主应用地址：https://hostname/
子应用地址：https://hostname/subSystemId

子应用内部使用 history.createHashHistory 创建 React 路由系统，encode hash("/") 和原始 hash 值("")不一样做一次修正需要调用window.location.replace
- encode 值和原值不一样
  <img width="425" alt="image" src="https://github.com/micro-zoe/micro-app/assets/16771528/5660a7f6-2ba1-4849-a8eb-d1008bc23e85">

  [history 代码](https://github.com/remix-run/history/blob/v4.10.1/modules/PathUtils.js#L1)

- 比较判断逻辑
  <img width="1877" alt="image" src="https://github.com/micro-zoe/micro-app/assets/16771528/027843aa-8bbc-4828-9d7c-bfa00d4b92fc">

  [createHashHistory 比较修正逻辑](https://github.com/remix-run/history/blob/v4.10.1/modules/createHashHistory.js#L176)

预期结果：**仅影响子系统** window.location 属性访问，**主系统路由不受影响**
实际结果：**整体页面（主系统/基座）** 跳转到 https://hostname/subSystemId/#/

### 尝试的解法：
1. 创建 micro-app 标签时携带 hash 后的信息（期望规避 createHashHistory 的问题）
❌ 不可用，iframe 沙箱默认加载主系统同 hostname 的 index.html 文件，且不传递 hash 信息
相关代码：
<img width="1956" alt="image" src="https://github.com/micro-zoe/micro-app/assets/16771528/9d2e9cde-40c4-4b25-b42a-d5dddf555e3b">
https://github.com/micro-zoe/micro-app/blob/dev/src/sandbox/iframe/index.ts#L90

### 问题排查
访问链：this.patchIframe -> this.proxyLocation -> patchRouter -> createMicroLocation -> createLocationMethod -> commonHandler 内部仅判断了 router-mode 为 search 的情况，是否也需要考虑 router-mode 为 pure 情况的处理
对于 router-mode 为 pure 的场景的处理在 history 的代理里面是有处理的 [history 代理处理 pure 模式](https://github.com/micro-zoe/micro-app/blob/dev/src/sandbox/router/history.ts#L47)

## 复现仓库
暂无，本地 demo 仓库调用未完成 pathIframe 行为，这也是个需要排查的问题
<img width="1114" alt="image" src="https://github.com/micro-zoe/micro-app/assets/16771528/b70bb167-1ba2-40ab-9824-9e15d54f1b0c">
> 后续本地仓库，复现环境补齐

## 环境信息
- micro-app版本：1.0.0-rc.4
- 主应用前端框架&版本：react@16.14.34     history@4.10.1
- 子应用前端框架&版本：react@16.14.34    history@4.10.1
- 构建工具&版本：本地开发 vite 2.9.15

**Comment by youngBrain1893** [comment]
## 复现方式
仓库：https://github.com/youngBrain1893/micro-app-issue-report
步骤：
1. 基础依赖安装 yarn （node >= 18）

2. 使用 vite 启动本地服务 yarn dev 访问默认 http://localhost:5173/assets/ 页面，系统渲染正常 ✅
3. 使用 webpack 启动本地服务 yarn dev:webpack 访问默认 http://localhost:8080/assets/ 页面，子系统内的路由变更影响主系统，页面跳转 ❌

**Comment by bailicangdu** [comment]
可以尝试通过设置默认页面解决 https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/router?id=%e8%ae%be%e7%bd%ae%e9%bb%98%e8%ae%a4%e9%a1%b5%e9%9d%a2

**Comment by bailicangdu** [comment]
location在pure模式的运行逻辑后续会进一步优化

**Comment by youngBrain1893** [comment]
> 可以尝试通过设置默认页面解决 https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/router?id=%e8%ae%be%e7%bd%ae%e9%bb%98%e8%ae%a4%e9%a1%b5%e9%9d%a2

临时解决方案看起来是可行的，在页面逻辑执行前修复 location 类似尝试 url 上+ hash 的解法
本质是避免 createHashHistory 因为差异导致的 replace 调用，还有有其他场景触发 replace 也会被代理到 rawWindow.location.replace 上

这边想的一个临时解法是替换掉子系统 iframe `contentWindow.__MICRO_APP_SANDBOX__` 上的 proxyLocation 为 contextWindow.location（iframe 原始 location）

location 的 pure 模式后续的优化方式预计是咋样的呢，是在 patch 里面的 commonHandler 内识别 pure 模式吗？

**Comment by bailicangdu** [comment]
已修复，更新到[1.0.0-rc.5](https://github.com/micro-zoe/micro-app/releases/tag/v1.0.0-rc.5)版本即可
