### ISSUE TITLE
子应用url会在pathname后追加一个‘/’, 导致后端路由匹配不上

### ISSUE THREAD

**Issue by matrix-neox** [jd-opensource/micro-app#1147]
## 问题描述
> 问题的具体描述
子应用url会在pathname后追加一个‘/’, 导致后端路由匹配不上
## 复现步骤
> 假设子应用地址为 https://www.example.com/pathname
1. 查看控制台中实际加载子应用的fetch请求是: https://www.example.com/pathname/
2. 查看源码中的formatAppURL方法

```ts
export function formatAppURL (url: string | null, appName: string | null = null): string {
  if (!isString(url) || !url) return ''

  try {
    const { origin, pathname, search } = createURL(addProtocol(url), (window.rawWindow || window).location.href)
    // If it ends with .html/.node/.php/.net/.etc, don’t need to add /
    if (/\.(\w+)$/.test(pathname)) {
      return `${origin}${pathname}${search}`
    }
    const fullPath = `${origin}${pathname}/`.replace(/\/\/$/, '/')
    return /^https?:\/\//.test(fullPath) ? `${fullPath}${search}` : ''
  } catch (e) {
    logError(e, appName)
    return ''
  }
}
```
3. 希望可以移除这个逻辑或者增加配置项允许不追加‘/’

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。

## 环境信息
- micro-app版本：1.0.0-rc.2
- 主应用前端框架&版本：react 18.2.0
- 子应用前端框架&版本：react 18.2.0
- 构建工具&版本：vite 4.5.0

**Comment by bailicangdu** [comment]
好的，感谢反馈

**Comment by bailicangdu** [comment]
已修复，更新到[1.0.0-rc.5](https://github.com/micro-zoe/micro-app/releases/tag/v1.0.0-rc.5)版本即可
