### ISSUE TITLE
主应用、子应用都使用vite+vue3，点击浏览器后退路由跳转错误。

### ISSUE THREAD

**Issue by orochitian** [jd-opensource/micro-app#1148]
## 问题描述
> 子应用中有自己的路由系统，在子应用中来回切换几个路由后，直接点击导航切换到主应用路由，这时点击浏览器后退键，跳转路由失败。

## 复现步骤
主应用、子应用都基于vite+vue3。路由模式使用：native-scope。子应用基础路径为：/micro/01
1. 进入子应用路由/micro/01/form
2. 点击系统左侧菜单跳转主应用首页/home
3. 点击浏览器后退按钮，期望返回/micro/01/form
4. 实际返回地址/form

## 上传截图
主应用main.js仅启动微应用：
![image](https://github.com/micro-zoe/micro-app/assets/28913785/bd25b814-5366-45ea-b5a5-d87bb95b7278)
主应用路由配置：
![image](https://github.com/micro-zoe/micro-app/assets/28913785/1e1b5aea-4e46-4278-bc72-e707e03214f0)
主应用调用微服务组件：
![image](https://github.com/micro-zoe/micro-app/assets/28913785/09eca7e1-8a92-448e-8dc1-8cbae6aef489)
子应用路由配置：
![image](https://github.com/micro-zoe/micro-app/assets/28913785/e5a561bf-d465-4316-bc8b-5fbc68ab9414)

## 环境信息
- micro-app版本：^1.0.0-rc.4
- 主应用前端框架&版本：vue ^3.4.21
- 子应用前端框架&版本：vue ^3.4.21
- 主应用、自用用路由：vue-router：^4.3.0
- 构建工具&版本：vite ^5.1.6

**Comment by youngBrain1893** [comment]
@bailicangdu 看打标为 `Working on it`，可以说下当前问题的原因吗
目前使用 pure 模式 + iframe 沙箱，相同的问题（排查看起来是 iframe 内的页面跳转也会影响到浏览器的 history 栈）感觉有点无解了（尝试设置 iframe sandbox 没有效果）

**Comment by bailicangdu** [comment]
使用默认路由模式呢？

**Comment by youngBrain1893** [comment]
> 使用默认路由模式呢？

使用默认路由模式子应用内的 history 操作页面响应正常，主应用上的 hash 变化（前进/后退）子应用不响应了
原因是因为 hashchange 时子应用 createHashHistory 时监听的，实际 window.addEventListener 在沙箱内按照事件类型添加到了 iframe 内的 window 上（所以不会触发）With 沙箱也会有一样的问题，可能需要按文档要求子页面切换为 BrowserHistory（此时 base-router 无法支持多个规则命中同一子应用，不太适用）

- [iframe 沙箱代码](https://github.com/micro-zoe/micro-app/blob/dev/src/sandbox/iframe/window.ts#L202)
- [with 沙箱代码](https://github.com/micro-zoe/micro-app/blob/dev/src/sandbox/with/window.ts#L260)

**Comment by bailicangdu** [comment]
@youngBrain1893 你描述的和我们修复的似乎不是同一个问题，能提供一个复现demo吗

**Comment by orochitian** [comment]
@bailicangdu 使用默认路由模式依然存在问题，与scope模式类似，但不完全一样。问题都出在，当路由从子应用路由跳转至主应用路由后，用户手动点击浏览器后退键，无法返回正确的子应用路由。随便使用一个基本的示例，应该都可以复现这个问题。

**Comment by bailicangdu** [comment]
> @bailicangdu 使用默认路由模式依然存在问题，与scope模式类似，但不完全一样。问题都出在，当路由从子应用路由跳转至主应用路由后，用户手动点击浏览器后退键，无法返回正确的子应用路由。随便使用一个基本的示例，应该都可以复现这个问题。

无法复现问题，需要提供demo

**Comment by youngBrain1893** [comment]
> @youngBrain1893 你描述的和我们修复的似乎不是同一个问题，能提供一个复现demo吗

https://github.com/micro-zoe/micro-app/issues/1151 更新了描述和复现DEMO

**Comment by happy760690** [comment]
我也遇到了这个问题，点击浏览器回退按钮，浏览器地址栏的url错了。。。。

**Comment by happy760690** [comment]
我也遇到了这个问题，点击浏览器回退按钮，浏览器地址栏的url错了。。。。

怎么解决的呀？

**Comment by orochitian** [comment]
@bailicangdu 请问这个问题是否和 #1151 一起修复了？

**Comment by bailicangdu** [comment]
已修复，更新到[1.0.0-rc.5](https://github.com/micro-zoe/micro-app/releases/tag/v1.0.0-rc.5)版本即可

**Comment by lixioo** [comment]
有人遇到过吗,父应用vue3子应用vue3,子应用有base,router push以后,浏览器返回有问题,base 又套了一层
