### ISSUE TITLE
angular 作为子应用运行报错

### ISSUE THREAD

**Issue by tirelyl** [jd-opensource/micro-app#115]
## 问题描述
> angular 12.x 版本 项目作为子项目，报错：[micro-app from runScript] RangeError: Maximum call stack size exceeded

## 复现步骤
1. 创建 react 基座应用
2. 创建 react 子应用（路由成功）
3. 创建 angular 子应用（路由失败）

## 上传截图
> 
![image](https://user-images.githubusercontent.com/20921324/138025709-26294f47-e495-4d5f-ab1f-cd9c1920fb6f.png)

## 复现仓库
>   https://github.com/tirelyl/micro-demo 
app1 目录下是 angular 应用

## 环境信息
- micro-app版本：0.4.0
- 主应用前端框架&版本：react17.x
- 子应用前端框架&版本：angular12.x
- 构建工具&版本：react-app-rewired&2.x

**Comment by tirelyl** [comment]
已解决，用 angular 作为子应用，两个坑：
1. 需要在基座应用的路由页面中 `import zone.js` (具体原因不知道为啥，期望能有解答) 
![image](https://user-images.githubusercontent.com/20921324/138038559-04bbd690-d684-4cc9-908a-dc7b6d5dec7b.png)
2. 本地调试时，angular 子应用的启动命令 `ng serve` 需要改为 `ng serve --live-reload false`，原因是因为在本地启动时，`webpack-dev-server` 会启动 socket 用来监听在文件修改后重启项目，从基座项目地址发起 socket 请求会 404 报错。可以用`--live-reload false` 禁用。感觉设置 proxy 应该也可以解决此问题。

**Comment by bailicangdu** [comment]
抱歉文档中没有说明，我们最近几天会补充相关文档

**Comment by tirelyl** [comment]
> 抱歉文档中没有说明，我们最近几天会补充相关文档

**Comment by tirelyl** [comment]
> 抱歉文档中没有说明，我们最近几天会补充相关文档

感谢回复。想多问一句，后续会补充 angular 作为基座应用的例子吗

**Comment by bailicangdu** [comment]
是的，包括angular、nextjs、nuxtjs都会进行补充

**Comment by meimosor** [comment]
遇到相同的报错，还没解决。
主应用：vue3+vite4
子应用：angular15
已添加zone.js引用，并尝试iframe沙箱，控制台直接卡死，一直输出Maximum call stack size exceeded
