### ISSUE TITLE
iframe 沙箱模式 hashchange 未代理到子系统上触发

### ISSUE THREAD

**Issue by youngBrain1893** [jd-opensource/micro-app#1151]
@youngBrain1893 你描述的和我们修复的似乎不是同一个问题，能提供一个复现demo吗

_Originally posted by @bailicangdu in https://github.com/micro-zoe/micro-app/issues/1148#issuecomment-2033908826_

复现仓库：https://github.com/youngBrain1893/micro-app-issue-report/tree/event-isolation
分支：event-isolation
其他信息：
1. @micro-zoe/micro-app@^1.0.0-rc.4
    - iframe 沙箱
    - route-mode "native"
3. 构建环境 vite，仓库下通过 yarn dev 启动
4. 代码逻辑
  主系统内可通过 `location.hash = \`/now/${Date.now()}\`` 触发 hash 变化
  子系统内通过 `window.addEventListener('hashchange')` 添加 hash 变化监听

复现操作：
1. 访问页面，默认打开 localhost:5173/assets/
2. 点击 `触发 Hash 变化`
3. 预期结果：子系统 hash 变化，hashchange 事件响应展示弹窗
4. 实际结果：主系统内 hash 变化响应，子系统内 hashchange 未触发

**Comment by youngBrain1893** [comment]
初步分析 iframeSandbox.start 阶段有进行 `addHistoryListener` 的操作，确实也有响应
但当前为 native 模式，子系统内 location 与 主系统 location 一致，事件响应时通过 `proxyWindow.location.hash` 拿到的结果已经是更新后的值，因此计算无变化，未触发 hashchange

相关代码：https://github.com/micro-zoe/micro-app/blob/dev/src/sandbox/router/event.ts#L76-L90

**Comment by bailicangdu** [comment]
问题已修复，下个版本发布

**Comment by wangzhenlalala** [comment]
请问下个版本是什么时候呀

**Comment by bailicangdu** [comment]
已发布，更新到1.0.0-rc.5即可
