### ISSUE TITLE
浏览器返回时 报错 Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.

### ISSUE THREAD

**Issue by Xy-Zipper** [jd-opensource/micro-app#1154]
## 问题描述
> 问题的具体描述

## 复现步骤
1. 主应用跳转到子应用
2.子应用使用baseRouter控制跳转到主应用的某个页面
3. 最后，主应用中浏览器返回报错

## 上传截图
> 
![1](https://github.com/micro-zoe/micro-app/assets/54532461/4b38bb9e-3693-499d-ba48-f8b22ab98f12)
![2](https://github.com/micro-zoe/micro-app/assets/54532461/7c785eba-92f3-44f8-bb67-187f0b0661e6)

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。

## 环境信息
- micro-app版本：1.0.0-rc.4
- 主应用前端框架&版本：vite + vue3 + vue-router4 
- 子应用前端框架&版本：vite + vue3 + vue-router4

**Comment by Xy-Zipper** [comment]
![3](https://github.com/micro-zoe/micro-app/assets/54532461/90210544-fbb0-48c8-ba09-7993ec460b7a)

**Comment by gaojiangtao-git** [comment]
提供复现demo方便作者复现问题，这样会提高效率

**Comment by Xy-Zipper** [comment]
> 提供复现demo方便作者复现问题，这样会提高效率

我的demo复现不了。。。

**Comment by Xy-Zipper** [comment]
> Hello @1054959069. In order to facilitate location and troubleshooting, we need you to provide a realistic GitHub repository. 您好 @1054959069, 为了方便定位和排查问题，我们需要您提供一个重现实例，请提供一个尽可能精简的 GitHub 仓库地址。

已经解决，由于vue3的teleport组件导致的，去掉之后就解决了
