### ISSUE TITLE
生产环境，主子应用共享window上的依赖失败

### ISSUE THREAD

**Issue by ByronYan01** [jd-opensource/micro-app#1157]
## 问题描述
主子应用都是 vite+vue3+element-plus，主应用通过加载cdn上的依赖正常渲染，再加载子应用时，将rawWindow上的依赖都赋值给子应用中的window上，子应用加载失败

## 复现步骤
1.主应用渲染成功，触发子应用加载
2.子应用加载先执行script赋值再执行加载其他文件

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。
主应用打印的子应用的html
![image](https://github.com/micro-zoe/micro-app/assets/60208330/2a838300-f35d-407f-8850-7e476e74e827)
window相关属性存在
![image](https://github.com/micro-zoe/micro-app/assets/60208330/71c990be-678d-4c98-957b-c0313360277f)
子应用报错信息
![image](https://github.com/micro-zoe/micro-app/assets/60208330/2e7e313b-82b4-4515-8d9a-2be15f6d8329)

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。

## 环境信息
- micro-app版本：1.0.0-rc.3
- 主应用前端框架&版本：vue3+element-plus
- 子应用前端框架&版本：vue3+element-plus
- 构建工具&版本：vite5

**Comment by ByronYan01** [comment]
https://github.com/ByronYan01/demo0408

**Comment by ByronYan01** [comment]
打包产物使用yarn preview可访问

**Comment by youngBrain1893** [comment]
看 child 构建产物相关资源是 module 类型，with沙箱是否支持这种类型呢？
印象中 iframe 沙箱是为了支持 vite 这种 esmodule 的，但需要注意 iframe 运行 module 代码实际直接用的 iframe 的 contentWindow

**Comment by ByronYan01** [comment]
> 看 child 构建产物相关资源是 module 类型，with沙箱是否支持这种类型呢？ 印象中 iframe 沙箱是为了支持 vite 这种 esmodule 的，但需要注意 iframe 运行 module 代码实际直接用的 iframe 的 contentWindow

谢谢回复，是改成这样嘛

**Comment by ByronYan01** [comment]
> 看 child 构建产物相关资源是 module 类型，with沙箱是否支持这种类型呢？ 印象中 iframe 沙箱是为了支持 vite 这种 esmodule 的，但需要注意 iframe 运行 module 代码实际直接用的 iframe 的 contentWindow

谢谢回复，是改成这样嘛
window.frameElement.contentWindow.Vue = window.rawWindow.Vue;
我试了一下还是一样的报错

**Comment by bailicangdu** [comment]
看了一下demo，问题出在CDN打包会将所有js降级为非esm，所以主应用的js是非esm，而子应用是esm，导致不兼容
<img width="868" alt="image" src="https://github.com/micro-zoe/micro-app/assets/20297227/f524d567-2428-4118-b6dc-5688a3fdb560">
<img width="998" alt="image" src="https://github.com/micro-zoe/micro-app/assets/20297227/4b6720dc-a192-4d2f-aa6f-a28bf5faff6d">

**Comment by bailicangdu** [comment]
这是vite打包模式的问题，和微前端关系不大。这里提供一种方式，仅供参考：1、子应用vite.config.js引入vite-plugin-cdn-import，配置方式和主应用一样 2、主应用修改如下：
<img width="926" alt="image" src="https://github.com/micro-zoe/micro-app/assets/20297227/48ef08bb-ecbb-4a9d-9a9e-07c4450b2593">

经过上述修改，可以正常渲染
<img width="579" alt="image" src="https://github.com/micro-zoe/micro-app/assets/20297227/5e81b0eb-7c11-46de-ba47-7925c04b979c">
