### ISSUE TITLE
iframe 沙箱下子系统的错误无法捕获 unhandledrejction, error 等均不响应

### ISSUE THREAD

**Issue by youngBrain1893** [jd-opensource/micro-app#1159]
## 复现步骤
1. 主系统内添加
```
window.addEventListener('unhandledrejection', (error) => {
    console.error(' === main unhandledrejection ====');
})
setTimeout(() => {
    Promise.reject('main error')
}, 1000)
```

2. 子系统添加
```
window.addEventListener('unhandledrejection', (error) => {
    console.error(' === sub unhandledrejection ====');
})
setTimeout(() => {
    Promise.reject('sub error')
}, 1000)
```

预期结果：主子系统都能捕获到错误
实际结果：主系统捕获到 Promise.reject('main error') 的错误，子系统错误未捕获

## 环境信息
- micro-app版本：1.0.0-rc.4

## 问题排查
子系统 window.addEventListener 被代理到 rawWindow 上，子系统的错误未添加捕获
除了以下事件其他事件都代理到 rawWindow 了：
```
 'popstate',  'hashchange',  'load',  'beforeunload',  'unload',  'unmount',  'appstate-change',  'statechange',  'mounted'
```

子系统的事件可以在内部处理吗，想了解下代理到外部的原因是什么？

**Comment by youngBrain1893** [comment]
最新 dev 分支上 `unhandledrejection` 已添加到 `SCOPE_WINDOW_ON_EVENT_OF_IFRAME` 绑定到子系统沙箱内

**Comment by bailicangdu** [comment]
问题已修复，更新到[1.0.0-rc.5](https://github.com/micro-zoe/micro-app/releases/tag/v1.0.0-rc.5)版本即可
