### ISSUE TITLE
有部署相关得文档吗？

### ISSUE THREAD

**Issue by qianqian05723** [jd-opensource/micro-app#116]

**Comment by M69W** [comment]
可以参考一下 issues/125 [nginx配置 ](https://github.com/micro-zoe/micro-app/issues/125#issuecomment-949443415)

**Comment by qianqian05723** [comment]
> 可以参考一下 issues/125 [nginx配置 ](https://github.com/micro-zoe/micro-app/issues/125#issuecomment-949443415)

就是你们会遇到用代理部署时，同一个页面路由跳转和fetch请求都会触发代理匹配，导致micro-app重复创建的问题码？
