### ISSUE TITLE
子应用内部路由跳转层级大于2层时，子应用调用router.back()会导致主应用挂载子应用的路由页面重新渲染。但不会进入到子页面的生命周期中

### ISSUE THREAD

**Issue by qvqzhm** [jd-opensource/micro-app#1161]
## 问题描述
> 问题的具体描述
子应用内部路由跳转层级大于2层时，子应用调用router.back()会导致主应用挂载子应用的路由页面重新渲染。但不会进入到子页面的生命周期中。
## 复现步骤
1.完成挂载子应用，子应用内部跳转大于两层路由（router.push()）
2.子应用内部使用路由回退(包括back()、go(-1)、window的回退方法)，

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。
![image](https://github.com/micro-zoe/micro-app/assets/102576766/fa0e4b3b-8dec-4e00-96cf-ce6f4eee88b8)

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。

## 环境信息
- micro-app版本：1.0.0-rc.4
- 主应用前端框架&版本：vite+vue3+router4
- 子应用前端框架&版本：webpack+vue2+router3
- 构建工具&版本：

**Comment by qvqzhm** [comment]
感谢您的回复！目前已找到到上述问题的原因。 但又发现一个问题，通过window.open打开的子应用会触发两次mounted生命周期。
地址： https://github.com/qvqzhm/micro-app-base
复现步骤： 
 1、主应用通过window.open新开标签页跳转到分配给子应用所在的路由
 2、子应用渲染会触发两次mounted。

期望： 
1、通过打开新标签页也只触发一次mounted。

疑问： 
1、子应用开启了umd模式，但umd模式只有在单标签页中有效果，新打开的标签页会重新挂载新的子应用实例，那么针对新打开的标签页能不能使用旧的标签页中已经挂载的子应用实例，从而实现跨标签页实现umd模式？

**Comment by bailicangdu** [comment]
感谢反馈，问题已复现，会在近期修复

**Comment by bailicangdu** [comment]
新的标签就是新的窗口，不能实现子应用复用

**Comment by zhiyouai** [comment]
> 感谢您的回复！目前已找到到上述问题的原因。 但又发现一个问题，通过window.open打开的子应用会触发两次mounted生命周期。 地址： https://github.com/qvqzhm/micro-app-base 复现步骤： 1、主应用通过window.open新开标签页跳转到分配给子应用所在的路由 2、子应用渲染会触发两次mounted。
> 
> 期望： 1、通过打开新标签页也只触发一次mounted。
> 
> 疑问： 1、子应用开启了umd模式，但umd模式只有在单标签页中有效果，新打开的标签页会重新挂载新的子应用实例，那么针对新打开的标签页能不能使用旧的标签页中已经挂载的子应用实例，从而实现跨标签页实现umd模式？

“子应用内部路由跳转层级大于2层时，子应用调用router.back()会导致主应用挂载子应用的路由页面重新渲染” 请问这个问题如何解决的？

**Comment by qvqzhm** [comment]
> > 感谢您的回复！目前已找到到上述问题的原因。 但又发现一个问题，通过window.open打开的子应用会触发两次mounted生命周期。 地址： https://github.com/qvqzhm/micro-app-base 复现步骤： 1、主应用通过window.open新开标签页跳转到分配给子应用所在的路由 2、子应用渲染会触发两次mounted。
> > 期望： 1、通过打开新标签页也只触发一次mounted。
> > 疑问： 1、子应用开启了umd模式，但umd模式只有在单标签页中有效果，新打开的标签页会重新挂载新的子应用实例，那么针对新打开的标签页能不能使用旧的标签页中已经挂载的子应用实例，从而实现跨标签页实现umd模式？
> 
> “子应用内部路由跳转层级大于2层时，子应用调用router.back()会导致主应用挂载子应用的路由页面重新渲染” 请问这个问题如何解决的？

我的项目出现这个问题的是因为将静态路由拉平了。保留路由结构就可以了。

**Comment by zhiyouai** [comment]
> 静态路由拉平

请问静态路由拉平，具体是指？

**Comment by qvqzhm** [comment]
正常的路由结构应该是：
{ 
   path: parentPath,
  children: [
    { path: childPath }
  ]
};

拉平后的路由结构就成了：
{
  path: parentPath
},
{
 path: childPath ,
}

**Comment by bailicangdu** [comment]
已修复，更新到[1.0.0-rc.5](https://github.com/micro-zoe/micro-app/releases/tag/v1.0.0-rc.5)版本即可
