### ISSUE TITLE
vue3 + vite 做子应用报错

### ISSUE THREAD

**Issue by trry-hub** [jd-opensource/micro-app#1163]
## 问题描述
> [micro-app from runScript] app my-app:  SyntaxError: Cannot use import statement outside a module

## 复现步骤
1.vue2 + webpack 做主应用，创建成功后，打开控制台报错

## 上传截图
![image](https://github.com/micro-zoe/micro-app/assets/67309192/3597cb74-e088-47ed-b119-deef7d54a17b)

![image](https://github.com/micro-zoe/micro-app/assets/67309192/44057127-6de4-4ff7-9af0-f077ab97eab6)

![image](https://github.com/micro-zoe/micro-app/assets/67309192/c19b56ba-4824-47fc-807c-d5a0da6399a2)

## 环境信息
- micro-app版本：1.0.0-rc.4
- 主应用前端框架&版本：vue@2.6.11 + vue-cli
- 子应用前端框架&版本：vue@3.4.21 + vite@5.2.8
- 构建工具&版本：

**Comment by xiyueW** [comment]
![image](https://github.com/micro-zoe/micro-app/assets/18444525/6f5c59dd-ce1b-4db0-8a86-97cd96e30af9)

**Comment by trry-hub** [comment]
应该是文档误导了我，我看的是vue做为子应用
