### ISSUE TITLE
子应用回退到上一级bug

### ISSUE THREAD

**Issue by liangyuan1** [jd-opensource/micro-app#1166]
主应用加载方案：
![image](https://github.com/micro-zoe/micro-app/assets/25976027/f6f0d28b-5e85-4755-ad1c-75d449da455f)
主应用路由配置：
![image](https://github.com/micro-zoe/micro-app/assets/25976027/a4ee9ddc-b8e8-4b38-834e-720d6e9886e4)
![image](https://github.com/micro-zoe/micro-app/assets/25976027/1eba542c-6fad-4a29-9b39-cd10a68fec6c)
子应用新增页面返回表格页面代码逻辑
![image](https://github.com/micro-zoe/micro-app/assets/25976027/9e0f5a53-f10c-414a-81c2-05518e985563)

页面路由重复加载
![image](https://github.com/micro-zoe/micro-app/assets/25976027/6a6286be-d466-427b-8ef5-3aeab89f57ee)
正确路由地址
![image](https://github.com/micro-zoe/micro-app/assets/25976027/21e9ea57-8b66-4ca5-bce0-7587fc3f77f9)

**Comment by isting** [comment]
我也遇到了这个问题，    go(-2)才达到预期效果

**Comment by bailicangdu** [comment]
问题已修复，更新到最新版本即可
