### ISSUE TITLE
域名中包含.js导致子应用渲染失败

### ISSUE THREAD

**Issue by SepVeneto** [jd-opensource/micro-app#1172]
## 问题描述
假设子应用部署在地址`demo.jstest.com`这个域名上，在加载的时候会由于能匹配到`.js`，导致给html内容包装成micro的结构
https://github.com/micro-zoe/micro-app/blob/976047205521e63b642491f21e7bb3dda8c8277d/src/source/loader/html.ts#L27

进而导致将子应用的访问地址作为`src`进行代理，最终渲染的内容就变成

```js
;(function(proxyWindow){with(proxyWindow.__MICRO_APP_WINDOW__){(function(window,self,globalThis,document,Document,Array,Object,String,Boolean,Math,Number,Symbol,Date,Function,Proxy,WeakMap,WeakSet,Set,Map,Reflect,Element,Node,RegExp,Error,TypeError,JSON,isNaN,parseFloat,parseInt,performance,console,decodeURI,encodeURI,decodeURIComponent,encodeURIComponent,navigator,undefined,location,history){
    ;<!doctype html><html>...</html>
}).call(...)
```

结果就是在控制台上抛出报错
```
/:1 
 Uncaught SyntaxError: Unexpected token '<'
```
## 复现步骤
1. 随便起一个项目，然后修改本地hosts，加一行192.168.1.9 demo.jstest.com
2. 主应用的url改为`192.168.1.9:8080`，能正常渲染子应用
3. 主应用的url改为`demo.jstest.com`，控制台报错

## 上传截图
![image](https://github.com/micro-zoe/micro-app/assets/20925980/0296ca92-2e93-42cd-955e-c9e570289073)

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。

## 环境信息
- micro-app版本：1.0.0-rc.4
- 主应用前端框架&版本：vue 3.2.13
- 子应用前端框架&版本：vue 3.3.4
- 构建工具&版本：webpack 5.74.0

**Comment by bailicangdu** [comment]
已修复，更新到[1.0.0-rc.5](https://github.com/micro-zoe/micro-app/releases/tag/v1.0.0-rc.5)版本即可
