### ISSUE TITLE
子应用返回上一页跳转错误问题

### ISSUE THREAD

**Issue by hjn1028** [jd-opensource/micro-app#1175]
## 问题描述
> 主、子应用都是vite+vue3，都是history路由，虚拟路由模式为native，在子应用内点击浏览器返回地址会错乱

## 复现步骤
1.跳转子应用的默认页面是/redirect
2.在子应用/system/menuList页面点击进入/system/menuEdit
3.在/system/menuEdit页面点击浏览器返回按钮  或者 用router.back()
4.浏览器直接返回到了/redirect页面，而非/system/menuList
5.我查看了history api的历史堆栈，只要不刷新页面，window.history.state.current一直都是进入子应用的第一个页面

## 上传截图
> 主应用
![image](https://github.com/micro-zoe/micro-app/assets/33085961/e55eb1d1-359a-4fe3-9cd2-9b1b65e70c34)
![image](https://github.com/micro-zoe/micro-app/assets/33085961/dde7659e-9f9a-41b2-80cb-32988125ba4e)
![image](https://github.com/micro-zoe/micro-app/assets/33085961/de677dec-148b-4813-859e-959dde6b1383)
> 主应用跳转
![image](https://github.com/micro-zoe/micro-app/assets/33085961/dd6d3373-db5e-4ef6-9de6-83e3b32267d4)
> 子应用
main.ts（看到了demo里这样写的）
![image](https://github.com/micro-zoe/micro-app/assets/33085961/e9b86948-aad1-46c5-bc8b-9ce81959bb02)
router.ts
![image](https://github.com/micro-zoe/micro-app/assets/33085961/d9a0b96b-b942-46d6-95e4-fc0bb2859af7)
vite.config.ts
![image](https://github.com/micro-zoe/micro-app/assets/33085961/26a215a6-9f46-4150-abd3-7eec30916f84)

## 环境信息
- micro-app版本：1.0.0-rc.4
- 主应用前端框架&版本：vue3 vite vue-router4.3
- 子应用前端框架&版本：vue3 vite vue-router4.3
- 构建工具&版本：vite5.1.5

**Comment by LlanHao** [comment]
请问问题修复了，同样的的问题，router.back、history.go(-1) 均跳转异常
