### ISSUE TITLE
子应用配置UMD模式，在主应用中访问时，没有触发mount方法

### ISSUE THREAD

**Issue by trry-hub** [jd-opensource/micro-app#1179]
## 问题描述
> 子应用配置UMD模式，在主应用中访问时，没有触发mount方法

## 复现步骤
1.
![image](https://github.com/micro-zoe/micro-app/assets/67309192/239817a0-9a69-4b82-8d54-7627526a5bdf)

2.
![image](https://github.com/micro-zoe/micro-app/assets/67309192/2e56f522-6c63-4548-ad81-acdd01c872d4)

## 上传截图
> ![image](https://github.com/micro-zoe/micro-app/assets/67309192/bf53d54c-e2e3-49dd-ad88-c692670861f3)

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。

## 环境信息
- micro-app版本：1.0.0-rc.4
- 主应用前端框架&版本：vue2.6.11 + cli
- 子应用前端框架&版本：vue3.4.21 + vite
- 构建工具&版本：

**Comment by bailicangdu** [comment]
这里要加上子应用域名
<img width="422" alt="image" src="https://github.com/micro-zoe/micro-app/assets/20297227/48a5c67d-1baf-4bd6-93ed-c2b83a7b8a34">

**Comment by trry-hub** [comment]
> 这里要加上子应用域名 <img alt="image" width="422" src="https://private-user-images.githubusercontent.com/20297227/323596110-48a5c67d-1baf-4bd6-93ed-c2b83a7b8a34.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0ODgwNjksIm5iZiI6MTcxMzQ4Nzc2OSwicGF0aCI6Ii8yMDI5NzIyNy8zMjM1OTYxMTAtNDhhNWM2N2QtMWJhZi00YmQ2LTkzZWQtYzJiODNhN2I4YTM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE5VDAwNDkyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk0YTVjNDExYjdjYWU3OTk1NGJkN2NmYmE1MWQxNTU0M2U5ZTU1MDJlNGZhMjA0MmQxMThhNzg5YjIxZTZiYTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.R3JA2zm6ALGwxxpxTTdiuzCEQFPOAc1mnHu-9uQocBQ">

不是这个问题，加上也不行的。

**Comment by trry-hub** [comment]
我找到原因了，是因为我使用了 unocss，但我没有时间去了解为什么会导致这个问题， 希望大佬 @bailicangdu 空了帮我看下，我这边需要使用 unocss，但我也需要使用 umd模式，复现地址，https://github.com/trry-hub/issues.git

**Comment by icemirror** [comment]
我也遇到类似的问题，代码都已经进到了vue3的入口文件了，但是就是没有调用mount方法，本地开发时是正常的，发布到线上就发现子应用并没有被渲染。也没有出现任何错误
micro-app版本：1.0.0-rc.4
主应用前端框架&版本：vue2.6.11 + webpack5
子应用前端框架&版本：vue3.4.21 + webpack5
**base:**
```js
<micro-app
    :data="microAppData"
    name="admin-vue3"
    baseroute="/admin-vue3"
    url="{domain}/vue3/"
    router-mode="native"
  ></micro-app>

microApp.start({
    'disable-patch-request': true,
    /**
     * @param url
     * @param options fetch settings
     * @param appName micro app name
     * @returns Promise<string>
     */
    fetch(url, options) {
      return fetch(
        url,
        Object.assign(options, {
          credentials: 'include'
        })
      ).then(res => {
        return res.text()
      })
    }
  })
}

```
**micro:**

```js
if (isMicroApp) {
  window[`micro-app-${window.__MICRO_APP_NAME__}`] = { mount, unmount }
} else {
  mount()
}
```
这种问题大概应该从哪里着手排查呢，控制台没有任何错误。麻烦大佬指点一下，谢谢
@bailicangdu

**Comment by trry-hub** [comment]
> 我也遇到类似的问题，代码都已经进到了vue3的入口文件了，但是就是没有调用mount方法，本地开发时是正常的，发布到线上就发现子应用并没有被渲染。也没有出现任何错误 micro-app版本：1.0.0-rc.4 主应用前端框架&版本：vue2.6.11 + webpack5 子应用前端框架&版本：vue3.4.21 + webpack5 **base:**
> 
> ```js
> <micro-app
>     :data="microAppData"
>     name="admin-vue3"
>     baseroute="/admin-vue3"
>     url="{domain}/vue3/"
>     router-mode="native"
>   ></micro-app>
> 
> microApp.start({
>     'disable-patch-request': true,
>     /**
>      * @param url
>      * @param options fetch settings
>      * @param appName micro app name
>      * @returns Promise<string>
>      */
>     fetch(url, options) {
>       return fetch(
>         url,
>         Object.assign(options, {
>           credentials: 'include'
>         })
>       ).then(res => {
>         return res.text()
>       })
>     }
>   })
> }
> ```
> 
> **micro:**
> 
> ```js
> if (isMicroApp) {
>   window[`micro-app-${window.__MICRO_APP_NAME__}`] = { mount, unmount }
> } else {
>   mount()
> }
> ```
> 
> 这种问题大概应该从哪里着手排查呢，控制台没有任何错误。麻烦大佬指点一下，谢谢 @bailicangdu

我的建议可以先尝试用最小demo 复现，这个过程你可能会找到问题

**Comment by icemirror** [comment]
你的问题是开发环境的吗？还是线上环境呢
@trry-hub

**Comment by trry-hub** [comment]
> 你的问题是开发环境的吗？还是线上环境呢 @trry-hub

我是在开发环境遇到的，加v: trry-wechat 尽量帮你排查下

**Comment by icemirror** [comment]
> > 你的问题是开发环境的吗？还是线上环境呢 @trry-hub
> 
> 我是在开发环境遇到的，加v: trry-wechat 尽量帮你排查下

我是线上的问题，而且没有报错 T.T

**Comment by icemirror** [comment]
<img width="673" alt="image" src="https://github.com/micro-zoe/micro-app/assets/14882452/b1ebdd06-24e0-4840-8f9d-1eb9f827da3e">
而且有个很奇怪的问题，我这边看到header里面的文件被注视掉了。不知道是不是prefetch的问题

**Comment by icemirror** [comment]
我尝试改了一下代码，我开启了iframe沙箱，然后把umd模式改成了默认的方式，就可以正常挂载了。但是这样的话，切换菜单就没有那么丝滑了。。还有没有别的方式啊 T.T @bailicangdu 大佬可以帮忙分析一下吗,谢谢

**Comment by zcx992132258** [comment]
> 我发现原因是因为我使用了unocss，但我没有时间去了解为什么会导致这个问题，希望大佬@bailicangdu空了找来看，我这边需要使用unocss，但我也需要使用umd模式，复现地址，https://github.com/trry-hub/issues.git

请问怎么去解决这个问题啊 使用了unocss 无法触发umd模式

**Comment by trry-hub** [comment]
> > 我发现原因是因为我使用了unocss，但我没有时间去了解为什么会导致这个问题，希望大佬@bailicangdu空了找来看，我这边需要使用unocss，但我也需要使用umd模式，复现地址，https://github.com/trry-hub/issues.git
> 
> 请问怎么去解决这个问题啊 使用了unocss 无法触发umd模式

使用vue-scoped 模式可以解决

**Comment by trry-hub** [comment]
> > > 你的问题是开发环境的吗？还是线上环境呢 @trry-hub
> > 
> > 
> > 我是在开发环境遇到的，加v: trry-wechat 尽量帮你排查下
> 
> 我是线上的问题，而且没有报错 T.T

你的问题解决了么

**Comment by zcx992132258** [comment]
> > > 我发现因为我使用了unocss，但我没有时间去了解为什么会导致这个问题，希望大佬@bailicangdu空了找来看，我这边需要使用unocss，但我也需要使用umd模式，复现地址，https://github.com/trry-hub/issues.git
> > 
> > 
> > 请问怎么去这个框架啊使用了unocss无法触发umd模式
> 
> 使用vue-scoped 模式可以解决
 
可以给一个文档连接吗  我在文档上面没有找到 vue-scoped 模式

**Comment by trry-hub** [comment]
unocss 的能力

![image](https://github.com/micro-zoe/micro-app/assets/67309192/268ba6bf-9569-4a14-b35f-3c964c42ef6a)


main.ts 中 的引入可以删除
