### ISSUE TITLE
哪位大哥救救!! 我的子项目是由webpack3 cli2 构建的vue项目，集成到主应用中一直报跨域错误

### ISSUE THREAD

**Issue by fengweb** [jd-opensource/micro-app#1181]
我的子项目是由webpack3 cli2 构建的vue项目，集成到主应用中一直报跨域错误！按照官网配置 headers: {
    'Access-Control-Allow-Origin': '*',
  },
  都无效！

**Comment by fengweb** [comment]
webpack3是不是都没有devServer 这个配置项啊

**Comment by bailicangdu** [comment]
webpack3 devServer的配置应该和4差不多吧

**Comment by fkc-alt** [comment]
用主应用的origin进行请求。在主应用编写请求代理

**Comment by Yulingsong** [comment]
本地和部署是不是有区别啊，部署之后得配置nginx之类的吧

**Comment by JieleeJie** [comment]
试试 [disable-patch-request](https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/configure?id=disable-patch-request)
https://github.com/micro-zoe/micro-app/issues/1280#issuecomment-2222448311
