### ISSUE TITLE
给<micro-app></micro-app> 或是  父级div  添加 position: relative，会导致el-popper被遮住

### ISSUE THREAD

**Issue by Ripperrrrrr** [jd-opensource/micro-app#1184]
给 micro-app 或是 父级div 添加 position: relative，会导致el-popper被遮住
![image](https://github.com/micro-zoe/micro-app/assets/91586254/6f9eaaec-d271-49d7-a9da-99ae3fd26f2b)
![image](https://github.com/micro-zoe/micro-app/assets/91586254/47efcf99-6af8-43b3-80ba-09af89565105)

**Comment by bailicangdu** [comment]
这种样式冲突框架是解决不了的，只能自行处理了
