### ISSUE TITLE
点击回退按钮到子应用bug

### ISSUE THREAD

**Issue by Sumandle** [jd-opensource/micro-app#1190]
## 问题描述
项目的router-mode使用的native，在微应用的页面时点击侧边栏，跳转到主应用，然后点击左上的回退按钮，出现微应用前缀丢失

## 复现步骤
1.在微应用的页面时点击侧边栏，跳转到主应用
2.点击左上的回退按钮，微应用前缀丢失，再点击就正常了

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。

## 环境信息
- micro-app版本：1.0.0-rc.4
- 主应用前端框架&版本：vite ^4.4.0  vue ^3.4.1
- 子应用前端框架&版本：vuecli 5.0 vue3.3
- 构建工具&版本：

**Comment by bailicangdu** [comment]
更新到1.0.0-rc.5版本可以解决
