### ISSUE TITLE
加载子应用，主应用相关css、js会重新再次加载；以及生产环境主子应用共享依赖相关问题

### ISSUE THREAD

**Issue by ByronYan01** [jd-opensource/micro-app#1191]
## 问题描述
[1157](https://github.com/micro-zoe/micro-app/issues/1157) 提供的解决方案，现在有些问题想请教一下
1. 由于所有依赖是主应用加载运行，挂载到window，所以子应用通过window.frameElement.contentWindow.Vue = window.rawWindow.Vue共享依赖后，沙箱是主应用的
   - 导致子应用的弹框popper都挂在到主应用的body下（期望共享的依赖也能和不共享情况一样，各自属于各自应用）
   - 路由不能正常跳转（只能不共享vue-router，期望能共享）
2. 每次加载子应用，主应用的所有css、js都会重新加载（期望不在加载主应用资源）
## 复现步骤
1. 主应用渲染成功，
2. 点击按钮，触发子应用加载

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。

共享依赖，所属沙箱都是主应用
![image](https://github.com/micro-zoe/micro-app/assets/60208330/34ae64af-ddd0-4e22-b296-728a4dd9d237)

加载子应用，主应用css、js 重新加载并canceled
![image](https://github.com/micro-zoe/micro-app/assets/60208330/fd9efd6d-8e1f-4f21-9e24-37b1bc8bb90a)

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。

https://github.com/ByronYan01/demo0408

## 环境信息
- micro-app版本：1.0.0-rc.3
- 主应用前端框架&版本：vue3+element-plus
- 子应用前端框架&版本：vue3+element-plus
- 构建工具&版本：vite5

**Comment by bailicangdu** [comment]
主应用资源重复加载的问题参考 https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/framework/vite?id=_2%e3%80%81iframe%e6%b2%99%e7%ae%b1%e5%8a%a0%e8%bd%bd%e4%ba%86%e4%b8%bb%e5%ba%94%e7%94%a8%e7%9a%84%e8%b5%84%e6%ba%90
<img width="579" alt="image" src="https://github.com/micro-zoe/micro-app/assets/20297227/3d9cd8d8-8081-4638-8eb9-c76f3e7aabd2">

**Comment by bailicangdu** [comment]
共享依赖的问题目前没有很好的解决方案

**Comment by ByronYan01** [comment]
> 共享依赖的问题目前没有很好的解决方案

好的谢谢，期待官方能尽快提供较好的解决方案

**Comment by hdy1023** [comment]
> > 共享依赖的问题目前没有很好的解决方案
> 
> 好的谢谢，期待官方能尽快提供较好的解决方案

框架应该不会处理这种问题的， “window.Vue = window.rawWindow.Vue”这种写法本质上是和沙箱理念相冲突的。

不知道你们为什么需要这种代码设计。
如果是想减少公共资源请求可以用资源共享。
如果是主应用想为子应用提供些工具方法可以用采取主子应用数据通信。

上面那种写法，一是难以兼容市面上所有第三方依赖；二是边界不清晰，出现问题难以定位。

**Comment by ByronYan01** [comment]
> > > 共享依赖的问题目前没有很好的解决方案
> > 
> > 
> > 好的谢谢，期待官方能尽快提供较好的解决方案
> 
> 框架应该不会处理这种问题的， “window.Vue = window.rawWindow.Vue”这种写法本质上是和沙箱理念相冲突的。
> 
> 不知道你们为什么需要这种代码设计。 如果是想减少公共资源请求可以用资源共享。 如果是主应用想为子应用提供些工具方法可以用采取主子应用数据通信。
> 
> 上面那种写法，一是难以兼容市面上所有第三方依赖；二是边界不清晰，出现问题难以定位。

谢谢回复；因为现在有的子引用加载速度有些慢，所以想一些依赖共享，减少一些加载时间
你说的资源共享，主子应用都访问相同路径的文件，使用globalAssets 或 global 属性达到访问一次，下次都走缓存，是这个意思嘛，回头我试一下

**Comment by UltramanWeiLai** [comment]
子应用的弹框popper都挂在到主应用的body下，这个请问一下解决了吗？

**Comment by ByronYan01** [comment]
> 子应用的弹框popper都挂在到主应用的body下，这个请问一下解决了吗？
子应用不共享主应用的element-ui，自己应用安装不会有这个问题

**Comment by ByronYan01** [comment]
> 子应用的弹框popper都挂在到主应用的body下，这个请问一下解决了吗？

子应用不共享主应用的element-ui，自己应用安装不会有这个问题

**Comment by UltramanWeiLai** [comment]
> > 子应用的弹框popper都挂在到主应用的body下，这个请问一下解决了吗？
> 
> 子应用不共享主应用的element-ui，自己应用安装不会有这个问题

就是想共享，优化加载速度。

**Comment by ByronYan01** [comment]
> > > 子应用的弹框popper都挂在到主应用的body下，这个请问一下解决了吗？
> > 
> > 
> > 子应用不共享主应用的element-ui，自己应用安装不会有这个问题
> 
> 就是想共享，优化加载速度。

那你试试所有子工程都访问同一路径的element-ui文件，使用globalAssets 或 global 属性达到访问一次，下次都走缓存（这个我还没试，应该可行）

**Comment by ByronYan01** [comment]
> 主应用资源重复加载的问题参考 https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/framework/vite?id=_2%e3%80%81iframe%e6%b2%99%e7%ae%b1%e5%8a%a0%e8%bd%bd%e4%ba%86%e4%b8%bb%e5%ba%94%e7%94%a8%e7%9a%84%e8%b5%84%e6%ba%90 <img alt="image" width="579" src="https://private-user-images.githubusercontent.com/20297227/326401185-3d9cd8d8-8081-4638-8eb9-c76f3e7aabd2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1MjgxMDcsIm5iZiI6MTcyMDUyNzgwNywicGF0aCI6Ii8yMDI5NzIyNy8zMjY0MDExODUtM2Q5Y2Q4ZDgtODA4MS00NjM4LThlYjktYzc2ZjNlN2FhYmQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA5VDEyMjMyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmMmNkZTEzMWQzY2MyNzg1ZGNmZDk4Y2Q5OGUwMWYwYTMxYjVlOGU4YzA5YzE5ZjdiODBlNzRiZWY0NWYyYzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WiM2FEDkvpGKGvB89yimJUXtBh6xzJEvy7ThV7bUfac">

目前按照文档说法增加上，加载子应用时还是会加载主应用资源
![image](https://github.com/micro-zoe/micro-app/assets/60208330/153e9e60-1b44-4a97-a190-e4df5581cde5)
![image](https://github.com/micro-zoe/micro-app/assets/60208330/988aa512-95e8-4d4e-b45b-1b6e5072169c)
![image](https://github.com/micro-zoe/micro-app/assets/60208330/48329552-cee1-454e-a909-7f575e864ad3)

https://github.com/ByronYan01/demo0408

**Comment by bailicangdu** [comment]
@ByronYan01  解决方式参考：
<img width="1206" alt="image" src="https://github.com/micro-zoe/micro-app/assets/20297227/c02ebad8-62e2-4509-a7f9-a1dd5940c74b">

**Comment by xubinglove** [comment]
方案一好像无效

**Comment by bailicangdu** [comment]
> 方案一好像无效

应该是设置的不对

**Comment by ByronYan01** [comment]
> > > 子应用的弹框popper都挂在到主应用的body下，这个请问一下解决了吗？
> > 
> > 
> > 子应用不共享主应用的element-ui，自己应用安装不会有这个问题
> 
> 就是想共享，优化加载速度。

共享成功了嘛
