### ISSUE TITLE
在PC端子应用加载正常，但是用手机浏览器打开，子应用无法加载

### ISSUE THREAD

**Issue by chssummer** [jd-opensource/micro-app#1193]
## 问题描述
> 问题的具体描述

## 复现步骤
1.
2.

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。

## 环境信息
- micro-app版本：
- 主应用前端框架&版本：
- 子应用前端框架&版本：
- 构建工具&版本：

**Comment by chssummer** [comment]
micro-app版本：1.0.0-rc.4
主应用前端框架&版本：React  18.2.0
子应用前端框架&版本：React  18.2.0
构建工具&版本：vite 5.0.10

**Comment by bailicangdu** [comment]
手机系统是多少？

**Comment by chssummer** [comment]
苹果11 和 Android  HarmnonyOS  P20 Pro

**Comment by chssummer** [comment]
> 苹果11 和 Android HarmnonyOS P20 Pro



> 手机系统是多少？

@bailicangdu 
苹果11 和 Android HarmnonyOS P20 Pro

**Comment by chssummer** [comment]
> Hello @chssummer. In order to facilitate location and troubleshooting, we need you to provide a realistic GitHub repository. 您好 @chssummer, 为了方便定位和排查问题，我们需要您提供一个重现实例，请提供一个尽可能精简的 GitHub 仓库地址。

内部项目 不好提供项目地址，就是用手机浏览器打开子应用无法打开 但是PC 可以16:25:12.027 flutter        I  LogUtils-D-consoleMessage ====来自于js的打印==== 
                                {message: [micro-app] app feedback: Failed to fetch data from http://localhost:4200/, micro-app stop rendering TypeError: Failed to fetch, messageLevel: 3}

**Comment by bailicangdu** [comment]
> > Hello @chssummer. In order to facilitate location and troubleshooting, we need you to provide a realistic GitHub repository. 您好 @chssummer, 为了方便定位和排查问题，我们需要您提供一个重现实例，请提供一个尽可能精简的 GitHub 仓库地址。
> 
> 内部项目 不好提供项目地址，就是用手机浏览器打开子应用无法打开 但是PC 可以16:25:12.027 flutter I LogUtils-D-consoleMessage ====来自于js的打印==== {message: [micro-app] app feedback: Failed to fetch data from http://localhost:4200/, micro-app stop rendering TypeError: Failed to fetch, messageLevel: 3}

看报错应该是跨域了或者404，建议先确认是哪种报错
