### ISSUE TITLE
microApp多页签缓存应用。microApp采用native路由方式，基座应用有多个页签显示一个子应用。如何实现缓存共功能？

### ISSUE THREAD

**Issue by arrayListTwo** [jd-opensource/micro-app#1195]
- 线上提供了一个最小demo。GitHub仓库：https://github.com/arrayListTwo/micro-demo
- 基座应用中路由： path: '/approve/*'
- ApproveView组件中：beforeRouteUpdate钩子调用reload()

- 如何实现切换顶部页签时，子应用缓存并路由页面正常？

**Comment by bailicangdu** [comment]
你说的是这个吧，https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/keep-alive

**Comment by arrayListTwo** [comment]
> 你说的是这个吧，https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/keep-alive

用了，和我的场景不一样。

主应用有两个页签，页签一和页签二，两个页签对应的主路由都是：/approver，路由组件下有一个子路由，我想在切换页签的时候，子应用随页签切换，并且也保持缓存。  

有时间的话，可以跑一下，我提供的GitHub。

**Comment by arrayListTwo** [comment]
使用：
1、基座应用vue2栈，
```
<keep-alive>
  <router-view>
  </router-view>
</keep-alive>
```
2、基座使用 
```
// microApp版本： 1.0.0-rc.5
<micro-app keep-alive router-mode="native">。 
```
3、子应用使用vue2栈
```
<keep-alive>
  <router-view>
  </router-view>
</keep-alive>
```

## 现象：
- 浏览器地址栏： http://localhost:2028/approve/#/home   变更为 http://localhost:2028/approve/#/about，子应用渲染的页面不发生改变。
- 
![image](https://github.com/micro-zoe/micro-app/assets/14231989/91c96fb2-402b-41f6-b78c-995a403fc4d1)

![image](https://github.com/micro-zoe/micro-app/assets/14231989/80dd2339-a228-49eb-a161-ad5fab51d986)

## 需求

浏览器地址栏发生变更时，子应用根据地址栏进行正常渲染。

请问需要如何操作？

**Comment by bailicangdu** [comment]
这里有2点：第1是子应用频繁卸载，也就是无法缓存的原因是给router-view设置了key，第2是通过主应用控制子应用跳转，相关文档参考 https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/router, 根据所提供的demo，这里提供一种实现方式仅供参考 
<img width="1482" alt="image" src="https://github.com/micro-zoe/micro-app/assets/20297227/1a62ba6e-feb3-4ec0-9b7e-f2e40b79b355">

**Comment by arrayListTwo** [comment]
en  使用主应用再一次控制子应用跳转，感谢指点

**Comment by EmbersEra** [comment]
请问  在主应用哪个周期中控制 子应用再次跳转 我试了  都不行 还是控制不了子应用跳转 @arrayListTwo
