### ISSUE TITLE
1.0.0-alpha.10在IOS手机软件13.7和14等低版本报错runScript错误， r.name.indexOf()

### ISSUE THREAD

**Issue by wpq-ytb** [jd-opensource/micro-app#1198]
## 问题描述
> 问题的具体描述
t.name.index("bound ")报错，正确是t.name为字符串。在低版本的IOS的safari浏览器中t.name是undefind。为一个HTML类型对象。

## 复现步骤
1.主应用是3.2.37用vite打包，子应用vue2.6.11。在低版本的IOS浏览器中运行，IOS手机软件版本13.7和14等。
2.打开子应用

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。
![WechatIMG529](https://github.com/micro-zoe/micro-app/assets/32693903/a8bc5d7e-c048-4c5c-9e11-fea1c57c5b28)
![WechatIMG16](https://github.com/micro-zoe/micro-app/assets/32693903/9b726914-5f18-46db-b779-15dd91634237)
![WechatIMG17](https://github.com/micro-zoe/micro-app/assets/32693903/7a33980a-6fec-4af8-9fa8-f8a622ed403e)

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。

## 环境信息
- micro-app版本："@micro-zoe/micro-app": "1.0.0-alpha.10"
- 主应用前端框架&版本：vue 3.2.37 
- 子应用前端框架&版本：vue2.6.11 
- 构建工具&版本：主应用："vite": "^2.9.9",  子应用 webpack4

**Comment by bailicangdu** [comment]
与 https://github.com/micro-zoe/micro-app/issues/1064 问题相同，升级到最新版本即可

**Comment by wpq-ytb** [comment]
升级到最新的版本还是有这个问题，之前是所有页面都有这个问题， 现在是子应用的页面有使用canvas就有这个问题
