### ISSUE TITLE
使用 native 路由模式，线上部署后子应用状态默认被保活，设置 keep-alive 无效

### ISSUE THREAD

**Issue by jhxxs** [jd-opensource/micro-app#1199]
## 问题描述
> 问题的具体描述

使用 native 路由模式，线上部署后子应用默认被保活，设置 keep-alive 无效。
这样很让人困扰，页面的状态默认被保活了，子应用第二次加载时不会触发自身的 mounted，

## 复现步骤
1. 刷新页面，切换到子应用
2. 子应用内部路由切换
3. 切换到主应用其他页面
4. 返回子应用，发现页面状态还是上次操作后的

## 上传截图

https://github.com/micro-zoe/micro-app/assets/7448223/2b2a968d-4405-4714-a76e-cee21972f0ee

## 环境信息
- micro-app版本：1.0.0-rc.5
- 主应用前端框架&版本：vue@2.7 + element-ui@element-ui
- 子应用前端框架&版本：同上
- 构建工具&版本：vite@5.2.11

**Comment by jhxxs** [comment]
[umd](https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/framework/vue?id=_1%e3%80%81%e5%bc%80%e5%90%afumd%e6%a8%a1%e5%bc%8f%ef%bc%8c%e4%bc%98%e5%8c%96%e5%86%85%e5%ad%98%e5%92%8c%e6%80%a7%e8%83%bd)
把 umd 模式去掉后每次加载子应用都会重新加载资源

**Comment by bailicangdu** [comment]
很明显的keep-alive状态，确定keep-alive的配置都去掉了吗，microApp.start的配置检查一下

**Comment by jhxxs** [comment]
> 很明显的keep-alive状态，确定keep-alive的配置都去掉了吗，microApp.start的配置检查一下

我没有使用 keep-alive 属性，稍等我提供一个最小实现

https://github.com/micro-zoe/micro-app/issues/1179
