### ISSUE TITLE
提问：这个框架浏览器兼容怎么样？感觉不错,希望能把文档搞的详细些，这样肯定会大火

### ISSUE THREAD

**Issue by woshihuxiangbo** [jd-opensource/micro-app#12]

**Comment by bailicangdu** [comment]
参考这里：https://zeroing.jd.com/micro-app/docs.html#/zh-cn/questions?id=_3%e3%80%81%e5%85%bc%e5%ae%b9%e6%80%a7%e5%a6%82%e4%bd%95
