### ISSUE TITLE
加载vue3子应用报错

### ISSUE THREAD

**Issue by JimmingSong** [jd-opensource/micro-app#120]
## 问题描述
> vue3+webpack 加载打包后的子应用报错 [micro-app from runScript] TypeError: Cannot read Property 'call' of undefined.
加载开发环境

## 复现步骤
1.用vue-ci@4.5创建一个vue3+webpack项目
2.打包完部署到nginx中通过基座访问

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。

## 环境信息
- micro-app版本：0.4.0
- 主应用前端框架&版本：vue2.6
- 子应用前端框架&版本：vue3.0
- 构建工具&版本：vue-cli@4.5

**Comment by bailicangdu** [comment]
这个问题和这个类似 https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/questions?id=_13%e3%80%81%e9%94%99%e8%af%af%e4%bf%a1%e6%81%af-referenceerror-xxx-is-not-defined-%e6%88%96-xxx-is-not-a-function-%e7%ad%89%e7%ad%89

**Comment by JimmingSong** [comment]
这个并不是我声明的 开发模式下启动是OK的 打包发布后 就不行了

**Comment by JimmingSong** [comment]
@bailicangdu 好像是web worker导致的

**Comment by bailicangdu** [comment]
可以具体说一下现象吗
