### ISSUE TITLE
"element-plus": "^2.3.4"下， ElMessageBox，el-date-picker样式异常。子应用中富文本wangeditor，复制粘贴有问题

### ISSUE THREAD

**Issue by ZhangYC193** [jd-opensource/micro-app#1203]
样式异常图如下
![微信图片_20240510103519](https://github.com/micro-zoe/micro-app/assets/38649449/b9caaa2f-c283-490b-9b9b-340fa4417d40)
![微信图片_20240510103525](https://github.com/micro-zoe/micro-app/assets/38649449/b540b68e-f7d4-49b7-8b62-d191bc7927b9)

富文本复制粘贴问题

https://github.com/micro-zoe/micro-app/assets/38649449/d6d5c8f7-f6d8-4698-bc0d-f9d9e4ac4ea3

**Comment by ZhangYC193** [comment]
@bailicangdu 大佬看一下吧，用的keep-alive,iframe模式，子应用用的vite + v3

**Comment by gaojiangtao-git** [comment]
最好提供下复现demo 方便作者排查

**Comment by ZhangYC193** [comment]
> 最好提供下复现demo 方便作者排查

  @bailicangdu 仓库地址如下
https://github.com/loser-or-no/vue3-child 子应用
https://github.com/loser-or-no/vue2-main 主应用

**Comment by ByronYan01** [comment]
> > 最好提供下复现demo 方便作者排查
> 
> @bailicangdu 仓库地址如下 https://github.com/loser-or-no/vue3-child 子应用 https://github.com/loser-or-no/vue2-main 主应用

你好，子应用中富文本wangeditor，复制粘贴问题解决了嘛

**Comment by ZhangYC193** [comment]
> > > 最好提供下复现demo 方便作者排查
> > 
> > 
> > @bailicangdu 仓库地址如下 https://github.com/loser-or-no/vue3-child 子应用 https://github.com/loser-or-no/vue2-main 主应用
> 
> 你好，子应用中富文本wangeditor，复制粘贴问题解决了嘛

https://github.com/wangeditor-team/wangEditor/pull/5518

**Comment by ByronYan01** [comment]
> > > > 最好提供下复现demo 方便作者排查
> > > 
> > > 
> > > @bailicangdu 仓库地址如下 https://github.com/loser-or-no/vue3-child 子应用 https://github.com/loser-or-no/vue2-main 主应用
> > 
> > 
> > 你好，子应用中富文本wangeditor，复制粘贴问题解决了嘛
> 
> [wangeditor-team/wangEditor#5518](https://github.com/wangeditor-team/wangEditor/pull/5518)

请问怎么具体使用，我看wangEditor那边的pull request没有合并，是需要自己下载修改并打包嘛

**Comment by ZhangYC193** [comment]
> > > > > 最好提供下复现demo 方便作者排查
> > > > 
> > > > 
> > > > @bailicangdu 仓库地址如下 https://github.com/loser-or-no/vue3-child 子应用 https://github.com/loser-or-no/vue2-main 主应用
> > > 
> > > 
> > > 你好，子应用中富文本wangeditor，复制粘贴问题解决了嘛
> > 
> > 
> > [wangeditor-team/wangEditor#5518](https://github.com/wangeditor-team/wangEditor/pull/5518)
> 
> 请问怎么具体使用，我看wangEditor那边的pull request没有合并，是需要自己下载修改并打包嘛

目前是拉下来自己发的私包
