### ISSUE TITLE
相对路径咨询

### ISSUE THREAD

**Issue by hehanli101** [jd-opensource/micro-app#1206]
子应用的接口请求发出的时候，请求的地址是‘/api/platform/file?keyword=&pageNo=5&pageSize=10’,

但是基座渲染子应用，这个接口在请求时会自动被浏览器补全为fetch(子应用域名 + '/api/platform/file?keyword=&pageNo=5&pageSize=10')，也会存在跨域问题
`
axios({
        method: 'get',
        url: '/api/platform/file?keyword=&pageNo=5&pageSize=10',
        headers:{
          Authorization:'Bearer 954071fbcd084f2bb5707bbf193a67d4'
        }
      })
`
我看文档常见问题写的是
2、请求的接口为相对地址，会以基座域名进行补全，导致报错。
如：fetch('/api/data')，在请求时会自动被浏览器补全为fetch(基座域名 + '/api/data')

不知道是不是我使用的问题

我希望的是子应用按照基座域名进行补全，我想通过nginx代理转发，不想进行跨域的配置

![image](https://github.com/micro-zoe/micro-app/assets/39009226/3448d312-7f83-40bf-bd2d-77e062b989dd)

**Comment by bailicangdu** [comment]
配置disable-patch-request即可 https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/configure?id=disable-patch-request
