### ISSUE TITLE
子应用使用element-plus 导致部分样式失效

### ISSUE THREAD

**Issue by xiangxinji** [jd-opensource/micro-app#121]
比如一些使用到了 var 进行 css 变量提取的值, 没有成功转换  , 这样导致大量的样式需要整改.

.el-dialog__footer {
    padding: var(--el-dialog-padding-primary);
}

---> 

micro-app[name=setup] .el-dialog__footer {
    padding-right: ;
    padding-bottom: ;
    padding-left: ;
}

**Comment by bailicangdu** [comment]
关闭样式隔离试一下呢 https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/configure?id=disablescopecss

**Comment by xiangxinji** [comment]
> 关闭样式隔离试一下呢 https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/configure?id=disablescopecss

关闭可以了,这个原因具体是怎么出现的呢? 不太理解 😄   而且这样也怕会有问题

**Comment by bailicangdu** [comment]
因为浏览器会将style样式转换为CSSRules，样式隔离就是利用转换后的CSSRules实现的，但是浏览器在转换部分var()样式为CSSRules时规则异常，这对浏览器没有影响，但是会导致样式隔离失败。 相似情况还有：
```css
border: 1px solid var(--color-a);
border-top-color: var(--color-b);
```

**Comment by xiangxinji** [comment]
> 因为浏览器会将style样式转换为CSSRules，样式隔离就是利用转换后的CSSRules实现的，但是浏览器在转换部分var()样式为CSSRules时规则异常，这对浏览器没有影响，但是会导致样式隔离失败。 相似情况还有：
> 
> ```css
> border: 1px solid var(--color-a);
> border-top-color: var(--color-b);
> ```

好的 . 非常感谢

**Comment by HenryZhu-1988** [comment]
> > 关闭样式隔离试一下呢 https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/configure?id=disablescopecss
> 
> 关闭可以了,这个原因具体是怎么出现的呢? 不太理解 😄 而且这样也怕会有问题

react 项目中并没有遇到这个问题，而是遇到了其他css 样式问题，我加上了disableScopecss ，关闭了样式隔离，出现了样式css 优先级问题，把 var(...) 给覆盖了
