### ISSUE TITLE
native 路由模式下，点击用例跳转没问题，当浏览器刷新时，加载的子应用页面和地址栏路由对应不上，1.0.0-rc.4 没有这个问题

### ISSUE THREAD

**Issue by jiaozhiye** [jd-opensource/micro-app#1210]
## 问题描述
native 路由模式下，点击用例跳转没问题，当浏览器刷新时，加载的子应用页面和地址栏路由对应不上，1.0.0-rc.4 没有这个问题，1.0.0-rc.5 发现的这个问题，是不是新版本路由这里实现机制有变化啊

## 环境信息
- micro-app版本：1.0.0-rc.5
- 主应用前端框架&版本：React
- 子应用前端框架&版本：React
- 构建工具&版本：Webpack5.88.2

**Comment by bailicangdu** [comment]
能具体描述一下吗，子应用是如何跳转的，url地址、页面最终渲染的地址截图看一下，有没有涉及到浏览器前进后退？

**Comment by jiaozhiye** [comment]
> 能具体描述一下吗，子应用是如何跳转的，url地址、页面最终渲染的地址截图看一下，有没有涉及到浏览器前进后退？

![image](https://github.com/micro-zoe/micro-app/assets/22720488/49d39b20-a59b-4123-a7e7-2966b0217124)
多页签的业务系统，每个页签对应一个微前端容器，正常切换时没问题（偶尔快速切换用例也会出现加载页面错乱），但是比方说停留在`用户管理`用例时，刷新浏览器，加载的子应用页面大概率会出问题，比方说加载的是别的页面。在 1.0.0-rc.4 没有这个问题，最近升级才发现的，后来回退了 rc4 版本。

**Comment by bailicangdu** [comment]
也就是说问题的出现是概率性的，可以提供个demo看一下吗或者远程调试？

**Comment by jiaozhiye** [comment]
> 也就是说问题的出现是概率性的，可以提供个demo看一下吗或者远程调试？

可以远程呀，我在咱们的交流群里加您微信可以吗？

**Comment by bailicangdu** [comment]
> > 也就是说问题的出现是概率性的，可以提供个demo看一下吗或者远程调试？
> 
> 可以远程呀，我在咱们的交流群里加您微信可以吗？

好的

**Comment by refinist** [comment]
Hi，any update?

**Comment by refinist** [comment]
https://github.com/micro-zoe/micro-app/blob/bbf6dba2f5ef7b2285b392b06473fdc334ebd9e2/src/sandbox/router/core.ts#L132-L138

@bailicangdu  hello，我这里测试了下，这里解开注释（L133-L137）然后注释（L138）应该可以解决这个问题。
目前我的业务都是采用 replace 的跳转方式，所以没有深入测试其他。
有空帮忙看看呢

**Comment by Wlisfes** [comment]
@jiaozhiye   微信(UT77243)麻烦拉下微信群

**Comment by sunui** [comment]
到底咋修复啊哥

**Comment by LlanHao** [comment]
> > 也就是说问题的出现是概率性的，可以提供个demo看一下吗或者远程调试？
> 
> 可以远程呀，我在咱们的交流群里加您微信可以吗？
能辛苦拉下进群吗？（微信：a947404912）
