### ISSUE TITLE
主应用引入子应用，子应用js资源被注释禁用，提示extract by micro-app

### ISSUE THREAD

**Issue by lizhenxue0408** [jd-opensource/micro-app#1215]
## 问题描述
> 问题的具体描述
主应用引入子应用，子应用js资源被注释禁用
## 复现步骤
1.  在vue2.6.14项目中，引入vue3.3.4项目
2.两个项目分别部署于不同的ip和端口

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。
![image](https://github.com/micro-zoe/micro-app/assets/54237078/fffce442-f2af-4d5f-b7dc-099e9410b955)
![image](https://github.com/micro-zoe/micro-app/assets/54237078/d3a86be4-de4e-498f-b464-50bd1eb67937)

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。
暂时无法提供
## 环境信息
- micro-app版本："@micro-zoe/micro-app": "^0.8.5",
- 主应用前端框架&版本："vue": "2.6.14",  "@vue/cli-service": "~4.5.0",
- 子应用前端框架&版本："vue": "^3.3.4".     "vite": "^4.4.9"
- 构建工具&版本：

**Comment by bailicangdu** [comment]
没有被禁用，只是提取到后台运行，如果想要显示出来可以设置inline模式，参考 https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/configure?id=inline
