### ISSUE TITLE
子应用配置跨域后 子应用内的请求还是跨域

### ISSUE THREAD

**Issue by wangfpp** [jd-opensource/micro-app#1216]
![image](https://github.com/micro-zoe/micro-app/assets/35289556/002b17e1-f81e-460e-ac3f-6bead9cfae09)

**Comment by bailicangdu** [comment]
根据报错信息所述，allow-header少了authorization字段
<img width="1424" alt="image" src="https://github.com/micro-zoe/micro-app/assets/20297227/c7f2063d-73f1-4859-aa07-2fcfe5676856">

**Comment by wangfpp** [comment]
好像也不行  我在子应用中设置了Access-Control-Allow-Headers 但是还是请求跨域 如下图  难道和我网络有关系？
![image](https://github.com/micro-zoe/micro-app/assets/35289556/e1592f10-fea0-42f1-bcce-3db83af7ca4e)
![image](https://github.com/micro-zoe/micro-app/assets/35289556/0ff20db1-8475-4e0f-a3eb-bb53fc1de481)

**Comment by bailicangdu** [comment]
报错变了，allow-header少了blade-auth字段，根据报错信息少什么加什么就行
<img width="1520" alt="image" src="https://github.com/micro-zoe/micro-app/assets/20297227/0f47fa06-45a8-47a6-a4ac-1492871d7333">

**Comment by JieleeJie** [comment]
试试 [disable-patch-request](https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/configure?id=disable-patch-request)
https://github.com/micro-zoe/micro-app/issues/1280#issuecomment-2222448311
