### ISSUE TITLE
子应用是外部链接时，未正常显示

### ISSUE THREAD

**Issue by oneofakindi** [jd-opensource/micro-app#1220]
## 问题描述
子应用是外部链接时，未正常显示

## 复现步骤
1. 创建子应用如下
`<micro-app name="test" url="http://testapp.com"></micro-app>`
2. http://testapp.com 服务器的nginx配置支持跨域。
3. http://testapp.com网址的内容未正常显示，控制台未报错。

## 上传截图
![image](https://github.com/micro-zoe/micro-app/assets/39716384/7a841a64-326f-4d6e-926e-ee2f7ad39908)

## 环境信息
- micro-app版本：^1.0.0-rc.5
- 主应用前端框架&版本：vue3.4.19
- 子应用前端框架&版本：angular10
- 构建工具&版本：vite5.1.4

**Comment by bailicangdu** [comment]
vite应用参考 https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/framework/vite

**Comment by oneofakindi** [comment]
![image](https://github.com/micro-zoe/micro-app/assets/39716384/0f3b5d33-2988-4869-b581-786d9a769fbf)
microApp.start()这里有做ifram的处理。
尝试使用angular17新建子应用可以正常显示。angular10项目还是不能正常显示

**Comment by oneofakindi** [comment]
感谢，已经解决了，是项目内增加了`DOMContentLoaded`时渲染页面导致的。
