### ISSUE TITLE
svg中图片路径问题

### ISSUE THREAD

**Issue by hehanli101** [jd-opensource/micro-app#1222]
测试过程中发现如果svg里面的图片路径是相对的话，会自动补全基座的域名，不像模板里面那样直接补全子应用的url

![image](https://github.com/micro-zoe/micro-app/assets/39009226/950b981d-2cb5-437c-b6b9-e4b3e25f7f3f)

页面的效果就是svg里面的图片展示不出来
![image](https://github.com/micro-zoe/micro-app/assets/39009226/bb84f243-09b4-4015-ab10-8a39036ebb5e)

除了把svg里面的路径写死，有什么其他的办法处理吗？

**Comment by bailicangdu** [comment]
webpack项目可以设置publicPath  https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/framework/vue?id=_3%e3%80%81%e8%ae%be%e7%bd%ae-publicpath

**Comment by hehanli101** [comment]
> webpack项目可以设置publicPath https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/framework/vue?id=_3%e3%80%81%e8%ae%be%e7%bd%ae-publicpath

我使用的是官网的例子，我看到/dev/children/vue2  vue.config.js配置了publicPath

我也main.js里面引入了public-path.js  也是不行的

**Comment by marsshen77** [comment]
同样的问题，不同的是我这边在Chrome浏览器中能正常补全地址，在firefox中子应用的svg文件就变成了相对路径。环境为vite+react

**Comment by muyuqingqiu** [comment]
我也遇到了这个问题，svg用相对路径会补全基座的域名。配置了publishPath也不行。
