### ISSUE TITLE
v1.0.0-rc.5版本下addEventListener事件挂载失效问题

### ISSUE THREAD

**Issue by WahahaWu** [jd-opensource/micro-app#1233]
## 问题描述
v1.0.0-rc.5版本下addEventListene   beforeunload 事件挂载失效

## 复现步骤
1. 子应用页面 mounted 时
window.addEventListener('beforeunload', (event) => {
  event.preventDefault();
  event.returnValue = '';
});
2. 关闭浏览器未出现阻止弹窗

## 环境信息
- micro-app版本：v1.0.0-rc.5
- 主应用前端框架&版本：vue3.2.13
- 子应用前端框架&版本：
vite、webpack vue2.7、vue3.2.13

## 问题代码
<img width="1031" alt="image" src="https://github.com/micro-zoe/micro-app/assets/31653758/b170f172-9f5b-494b-a451-ab2b75fcc26c">
<img width="935" alt="image" src="https://github.com/micro-zoe/micro-app/assets/31653758/d420cfb4-3446-43b6-84fa-852b676fd35e">
应该是判断反了

**Comment by kelvin-lemon** [comment]
遇到同样的问题 1.0.0-rc5 版本，子应用内监听 beforeunload 事件无效，事件被挂到了 micro-container 的 dom 节点上
![企业微信截图_409158dd-8759-4fca-8ce5-303b747f7d9a](https://github.com/micro-zoe/micro-app/assets/49432472/bfadefd1-fdce-45ef-87e1-889b5a367900)

@bailicangdu

**Comment by bailicangdu** [comment]
问题已收到，会在近期修复

**Comment by kelvin-lemon** [comment]
@bailicangdu 这个问题修复了吗？

**Comment by hailinlu** [comment]
同问，自封装的库，通过dispatchEvent传递的数据，子应用接收不到，单独启动可以获取，和这个是一样的问题 @bailicangdu
