### ISSUE TITLE
浏览器点击返回时地址出现错误

### ISSUE THREAD

**Issue by lilu0826** [jd-opensource/micro-app#1234]
## 问题描述
> 路由模式用的native，子应用跳转到某个地址后，点击浏览器刷新后，再跳转到其他页面，再点击浏览器返回后浏览器地址栏出现错误

## 复现步骤
1. demo地址： https://github.com/lilu0826/micro-app-bug
2.下载demo，都是vite+vue3项目，同时运行main-app和sub-app
3.打开http://localhost:3000/sub-app/about
![image](https://github.com/micro-zoe/micro-app/assets/38303643/ec8fc24f-2166-4f9c-a968-e1a3cd8fba8d)

3.点击【子应用主页】
![image](https://github.com/micro-zoe/micro-app/assets/38303643/dbff54f7-2e3e-4a72-8d07-2ae88c19c048)

4.再点击浏览器返回按钮，浏览器地址会变成：http://localhost:3000/sub-app/sub-app/about
![image](https://github.com/micro-zoe/micro-app/assets/38303643/42543ac6-96fc-40ca-8950-6f26a50e8fc4)
5.子应用渲染错误

## 上传截图
1.主应用的配置：
![image](https://github.com/micro-zoe/micro-app/assets/38303643/7469197f-e4d9-4c30-9078-352a41e67475)
![image](https://github.com/micro-zoe/micro-app/assets/38303643/d81922c0-45b6-48e4-836d-79630f49e9f2)
2.子应用就是正常的一个子应用，router接收了window.__MICRO_APP_BASE_ROUTE__
![image](https://github.com/micro-zoe/micro-app/assets/38303643/2aed326d-fe50-47d5-89fb-3e26fad07c80)

## 复现仓库
> https://github.com/lilu0826/micro-app-bug

## 环境信息
- micro-app版本：^1.0.0-rc.5
- 主应用前端框架&版本：vite+vue3+vue-router4
- 子应用前端框架&版本：vite+vue3+vue-router4
- 构建工具&版本：vite@5.2.8

**Comment by lilu0826** [comment]
![image](https://github.com/micro-zoe/micro-app/assets/38303643/e066efec-b216-40bc-8c22-91069b5696a0)

研究看了下，应该是子应用的history.state.current 被错误的拼接上了baseroute前缀，和主应用__MICRO_APP_STATE__["my-app"].state.current记录的不一致导致的，主应用记录的是对的，不带前缀。希望官网可以解决这个问题吧。

**Comment by lilu0826** [comment]
现在临时的解决方法，在子应用router.beforeEach钩子替换一下history.state.current中的baseroute前缀
`router.beforeEach(async (to, from) => {
    if (from === START_LOCATION && window.__MICRO_APP_ENVIRONMENT__) {
        window.history.state.current = window.history.state.current.replace(window.__MICRO_APP_BASE_ROUTE__, '/')
     }
})`

**Comment by bailicangdu** [comment]
问题会在近期修复，感谢反馈
