### ISSUE TITLE
关于Modal组件挂载位置问题

### ISSUE THREAD

**Issue by vampireXia** [jd-opensource/micro-app#1241]
## 问题描述
> 主应用使用三方UI库 naiveui antdvue的modal组件时，如果有微应用的场景下， 会出现样式丢失或挂载到micro-app-body的情况，实际需要的是正确显示modal组件或挂载到父应用的body下

## 复现步骤
1. 父应用创建一个modal组件
2. 让modal组件显示

## 上传截图
> 样式丢失的情况，但切换到非微应用页面可以正确显示modal组件
> ![image](https://github.com/micro-zoe/micro-app/assets/17586390/c725a1b6-71b5-4ede-b902-3a943ae75839)
> 弹窗正确显示，但是挂载到了子应用micro-app-body下的情况，导致在非微应用页面无法正确显示modal组件
> ![image](https://github.com/micro-zoe/micro-app/assets/17586390/03b2ad5d-e5ba-43ce-88f1-f426a899118f)

## 环境信息
- micro-app版本：1.0.0-rc.5
- 主应用前端框架&版本：vue@3.4.21 + naive-ui@2.38.2
- 子应用前端框架&版本：vue@3.4.21 + naive-ui@2.38.2
- 构建工具&版本：vite@5.1.5

**Comment by bailicangdu** [comment]
是iframe沙箱吗，能提供一个复现的demo吗

**Comment by vampireXia** [comment]
> Hello @vampireXia. In order to facilitate location and troubleshooting, we need you to provide a realistic GitHub repository. 您好 @vampireXia, 为了方便定位和排查问题，我们需要您提供一个重现实例，请提供一个尽可能精简的 GitHub 仓库地址。

你好今天写demo发现可能是项目的某些配置导致的 虽然我还没发现具体导致这个错误的原因，如果我找到了我再补充出完整的可复现demo

**Comment by vampireXia** [comment]
> 是iframe沙箱吗，能提供一个复现的demo吗

你好今天写demo发现可能是项目的某些配置导致的 虽然我还没发现具体导致这个错误的原因，如果我找到了我再补充出完整的可复现demo

**Comment by vampireXia** [comment]
[https://github.com/vampireXia/micro-app-bug-demo](url)

场景说明：通过子应用的触发事件回调打开父应用弹窗
复现步骤：如果通过父应用去改变子应用表格中的`loading`状态，则会将`modal`挂载到子应用下，如果不去改变`loading`则不会
demo: 
```
// 打开子应用5173
pnpm run dev:sub
// 打开父应用端口5174
pnpm run dev
```
点击`点击弹父` 打开弹窗, 发现挂载在了`micro-app-body`下，如果这时去非嵌微应用页面，会导致弹窗打不开

**Comment by vampireXia** [comment]
> 是iframe沙箱吗，能提供一个复现的demo吗

@bailicangdu 

[https://github.com/vampireXia/micro-app-bug-demo](url)

场景说明：通过子应用的触发事件回调打开父应用弹窗
复现步骤：如果通过父应用去改变子应用表格中的`loading`状态，则会将`modal`挂载到子应用下，如果不去改变`loading`则不会
demo: 
```
// 打开子应用5173
pnpm run dev:sub
// 打开父应用端口5174
pnpm run dev
```
点击`点击弹父` 打开弹窗, 发现挂载在了`micro-app-body`下，如果这时去非嵌微应用页面，会导致弹窗打不开
