### ISSUE TITLE
子应用资源加载跨域，按照文档配置了子应用nginx允许跨域没起作用

### ISSUE THREAD

**Issue by yanduhantan1991** [jd-opensource/micro-app#125]
**子应用中的vite.config**
`export default defineConfig({
    plugins: [
        // legacy({
        //   targets: ['Chrome >= 59']
        // }),
        vue(),
        (function() {
            let basePath = ''
            return {
                name: "childAppA",
                apply: 'build',
                configResolved(config) {
                    basePath = `${config.base}${config.build.assetsDir}/`
                },
                renderChunk(code, chunk) {
                    if (chunk.fileName.endsWith('.js') && /(from|import)(\s*['"])(\.\.?\/)/g.test(code)) {
                        code = code.replace(/(from|import)(\s*['"])(\.\.?\/)/g, (all, $1, $2, $3) => {
                            return all.replace($3, new URL($3, basePath))
                        })
                    }
                    return code
                }
            }
        })(),
    ],
    server: {
        port: 3000,
        host: '0.0.0.0'
    },
    build: {
        outDir: 'dist',
    },
    clearScreen: false,
    base: `${process.env.NODE_ENV === 'production' ? 'http://10.0.93.103:3000' : ''}/childAppA/`,
})`

**基座应用中的main.ts**
`  /**
   * 自定义fetch
   * @param url 静态资源地址
   * @param options fetch请求配置项
   * @returns Promise<string>
   */
   fetch(url: string, options: any, appName: string) {
    let config = null
    if (url === 'http://10.0.93.103:3000/childAppA/') {
      config = {
        headers: {
          'custom-head': 'custom-head',
        }
      }
    }
    return fetch(url, Object.assign(options, config)).then((res) => {
      return res.text()
    })
  }`

**子应用nginx配置**
`    server {
        listen       3000;
        server_name  10.0.93.103;

        #charset koi8-r;

        #access_log  logs/host.access.log  main;

        location / {
            add_header Access-Control-Allow-Origin *;
            add_header Access-Control-Allow-Methods 'GET, POST, OPTIONS';
            add_header Access-Control-Allow-Headers 'DNT,X-Mx-ReqToken,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization';

            if ($request_method = 'OPTIONS') {
                return 204;
            }

            root   html/dist;
            index  index.html index.htm;
        }`

基座应用和子应用都是用的vite，本地其服务在基座应用中可以打开子应用，放到本地的nginx上就不行了，也尝试更改这些相关配置，但是依旧都是提示跨域。并且单独打开子应用地址的时候，加载资源文件404，就是因为加载路径中多了childAppA这一层。

**Comment by bailicangdu** [comment]
将 location 修改为  location /childAppA {}, 然后通过http://10.0.93.103:3000/childAppA/ 访问子应用

**Comment by yanduhantan1991** [comment]
> 将 location 修改为 location /childAppA {}，然后通过http://10.0.93.103:3000/childAppA/访问子应用
还是不行，直接访问子应用是404，通过基座应用访问还是提示跨域，还有可能是哪李配置的不对么？

**Comment by bailicangdu** [comment]
肯定是配置的问题，贴上我们使用的nginx配置以供参考：
```
server {
        listen       80;
        server_name  _;
        # root         /usr/share/nginx/html;
        root          /app/app;

        # Load configuration files for the default server block.
        include /etc/nginx/default.d/*.conf;

        location / {
           add_header Access-Control-Allow-Origin *;
           add_header Cache-Control no-cache;
            alias /app/app/micro-app/docs/;
            index index.php index.html index.htm;
        }

        location /micro-app {
            alias /app/app/micro-app/docs/;
            index index.php index.html index.htm;
        }

        location /micro-app/demo {
            add_header Access-Control-Allow-Origin *;
            if ( $request_uri ~* ^.+.(js|css|jpg|png|gif|tif|dpg|jpeg|eot|svg|ttf|woff|json|mp4|rmvb|rm|wmv|avi|3gp)$ ){
                add_header Cache-Control max-age=7776000;
                add_header Access-Control-Allow-Origin *;
            }
            try_files $uri $uri/ /micro-app/demo/index.html;
        }

        location /micro-app/react16 {
            add_header Access-Control-Allow-Origin *;
            if ( $request_uri ~* ^.+.(js|css|jpg|png|gif|tif|dpg|jpeg|eot|svg|ttf|woff|json|mp4|rmvb|rm|wmv|avi|3gp)$ ){
                add_header Cache-Control max-age=7776000;
                add_header Access-Control-Allow-Origin *;
            }
            try_files $uri $uri/ /micro-app/react16/index.html;
        }

        location /micro-app/react17 {
            add_header Access-Control-Allow-Origin *;
            if ( $request_uri ~* ^.+.(js|css|jpg|png|gif|tif|dpg|jpeg|eot|svg|ttf|woff|json|mp4|rmvb|rm|wmv|avi|3gp)$ ){
                add_header Cache-Control max-age=7776000;
                add_header Access-Control-Allow-Origin *;
            }
            try_files $uri $uri/ /micro-app/react17/index.html;
        }

        location /micro-app/vue2 {
            add_header Access-Control-Allow-Origin *;
            if ( $request_uri ~* ^.+.(js|css|jpg|png|gif|tif|dpg|jpeg|eot|svg|ttf|woff|json|mp4|rmvb|rm|wmv|avi|3gp)$ ){
                add_header Cache-Control max-age=7776000;
                add_header Access-Control-Allow-Origin *;
            }
            try_files $uri $uri/ /micro-app/vue2/index.html;
        }

        location /micro-app/vue3 {
            add_header Access-Control-Allow-Origin *;
            if ( $request_uri ~* ^.+.(js|css|jpg|png|gif|tif|dpg|jpeg|eot|svg|ttf|woff|json|mp4|rmvb|rm|wmv|avi|3gp)$ ){
                add_header Cache-Control max-age=7776000;
                add_header Access-Control-Allow-Origin *;
            }
            try_files $uri $uri/ /micro-app/vue3/index.html;
        }

        location /micro-app/vite {
            add_header Access-Control-Allow-Origin *;
            if ( $request_uri ~* ^.+.(js|css|jpg|png|gif|tif|dpg|jpeg|eot|svg|ttf|woff|json|mp4|rmvb|rm|wmv|avi|3gp)$ ){
                add_header Cache-Control max-age=7776000;
                add_header Access-Control-Allow-Origin *;
            }
            try_files $uri $uri/ /micro-app/vite/index.html;
        }

        location /micro-app/angular11 {
            add_header Access-Control-Allow-Origin *;
            if ( $request_uri ~* ^.+.(js|css|jpg|png|gif|tif|dpg|jpeg|eot|svg|ttf|woff|json|mp4|rmvb|rm|wmv|avi|3gp)$ ){
                add_header Cache-Control max-age=7776000;
                add_header Access-Control-Allow-Origin *;
            }
            try_files $uri $uri/ /micro-app/angular11/index.html;
        }

        location ~* \.(eot|otf|ttf|woff|woff2|svg)$ {
           add_header Access-Control-Allow-Origin *;
           add_header Cache-Control max-age=7776000;
        }

        error_page 404 /404.html;
            location = /40x.html {
        }

        error_page 500 502 503 504 /50x.html;
            location = /50x.html {
        }
    }
```

**Comment by i-artist** [comment]
@yanduhantan1991 根据你上面的例子，如果你在主应用的自定义 fetch 方法中，自定义配置了 header 请求头，那么在子应用的 nginx 配置项  Access-Control-Allow-Headers 这里也要把自定义配置的请求头添加上去。

**Comment by yanduhantan1991** [comment]
感谢各位，问题解决了，还是nginx配置的不对
`        location /childAppA {

            add_header Access-Control-Allow-Origin '*';
            add_header Access-Control-Allow-Methods 'GET, POST, OPTIONS';
            add_header Access-Control-Allow-Headers 'DNT,X-Mx-ReqToken,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization';

            if ($request_method = 'OPTIONS') {
                return 204;
            }

            #root   html/dist;
            alias  html/dist;
            index  index.html;
        }`

**Comment by chenmingli** [comment]
我也遇到一样的问题，能帮我看看吗
子应用部署出现跨域

本地运行没问题，部署到线上就出现跨域了

![Untitled](https://user-images.githubusercontent.com/33892254/184563719-f7b5b969-8951-4e64-981c-96da05d20159.png)


基座应用配置子应用

![image](https://user-images.githubusercontent.com/33892254/184563734-77def1c2-6b10-4287-9306-acf279ea9205.png)


子应用的nginx

```jsx
location / {
    add_header 'Access-Control-Allow-Origin' '*';
    add_header 'Access-Control-Allow-Credentials' 'true';
    add_header 'Access-Control-Allow-Headers' 'Authorization,Content-Type,Accept,Origin,User-Agent,DNT,Cache-Control,X-Mx-ReqToken,X-Requested-With';
    add_header 'Access-Control-Allow-Methods' 'GET,POST,OPTIONS';
    root /usr/share/nginx/html;
    index index.html index.htm;
    try_files $uri $uri/ /index.html;
  }
```

**Comment by bailicangdu** [comment]
http://localhost:9081是本地的，部署到服务器要换成服务器地址

**Comment by 1140537179** [comment]
我也是父应用访问子应用有时候会跨域(比如父应用第一次访问子应用)，大佬能看看我的吗，不知道怎么解决
![1](https://github.com/micro-zoe/micro-app/assets/53072146/7fe39333-e788-44b6-9cba-29314cadb2f7)
![2](https://github.com/micro-zoe/micro-app/assets/53072146/f2f2753e-94b8-4c1e-b4cd-02c9fcc54095)
