### ISSUE TITLE
内存泄露问题

### ISSUE THREAD

**Issue by jatyPeng** [jd-opensource/micro-app#1250]
为了实现多tab，打开了很多 micro-app标签，打开一个子应用就大概50M，unmount了不会减。非常容易就上1G内存了。用了umd模式的。
现在很多报内存问题的，什么时候micro-app能彻底解决下？

刚花2周时间把开发了多年的项目从qiankun转过来，觉得调用方式更简单，没想到遇到性能问题了。。。。。。。

**Comment by jatyPeng** [comment]
没人看看吗？chrome提示标签页已经用了1.8G了。

**Comment by xiangxinji** [comment]
解决了嘛？ 哥们

**Comment by shaojiankui** [comment]
同上

**Comment by brightmoonxx** [comment]
同上

**Comment by bailicangdu** [comment]
参考 https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/sandbox?id=memory
