### ISSUE TITLE
当前停留在子应用页面，点击浏览器回退路由返回错误

### ISSUE THREAD

**Issue by 260178** [jd-opensource/micro-app#1251]
环境：
   主应用： VUE2  vue-router3.x
   子应用 ： VUE3  vue-router4 
   虚拟路由开启
场景：
   进入主应用后，点击左侧菜单进入子应用页面a，即/main/a?alert-app=/a,
   在点击左侧菜单进入同一个子应用页面B，即/main/b?alert-app=/b,
   点击浏览器回退按钮正常进入/main/a?alert-app=/a页面，但是浏览器地址变成了/main/a?alert-app=/,页面没有改变

**Comment by flycj** [comment]
遇到同样的问题，请问你解决了吗？ @260178
