### ISSUE TITLE
求紧急修复：1.0.0-rc.4版本后，子应用为vite时无法获取到子应用自身的localtion

### ISSUE THREAD

**Issue by boogie-ben** [jd-opensource/micro-app#1253]
## 问题描述
下图中的 `window.microApp.location` 读取的信息是父应用的

如现在`window.microApp.location.origin`和`window.location.origin`的值都是一致为父应用的origin，无法读取子应用自身的origin

![image](https://github.com/micro-zoe/micro-app/assets/29250685/b6993ad6-55ee-448a-87e5-a9c042302267)

估计和 #937 的修复有关

**Comment by bailicangdu** [comment]
这和路由模式有关，如果想要指向子应用origin，切换到native-scope模式即可
<img width="1133" alt="image" src="https://github.com/micro-zoe/micro-app/assets/20297227/b6227c8b-3601-4eec-ae1b-ddf02ddfe8bb">

**Comment by wellenzhong** [comment]
设置为无论设置为native还是native-scope，window.microApp.location对象都为空，是怎么回事？

**Comment by bailicangdu** [comment]
> 设置为无论设置为native还是native-scope，window.microApp.location对象都为空，是怎么回事？

vite应用吗

**Comment by wellenzhong** [comment]
> > 设置为无论设置为native还是native-scope，window.microApp.location对象都为空，是怎么回事？
> 
> vite应用吗

是的，现在设置路由模式为state，页面又空白了

**Comment by bailicangdu** [comment]
正常情况不会有问题，有案例看一下吗 @wellenzhong

**Comment by wellenzhong** [comment]
定位到了，路由没匹配上~ 明天再研究下这几个路由模式

**Comment by boogie-ben** [comment]
@bailicangdu 
明白了，原来是默认的路由模式改了本来用的是disable-memory-router
