### ISSUE TITLE
两个子应用都是vue-router4.x，初始化及某个子应用内部返回跳转的时候，另外一个子应用也会触发路由守卫，导致返回异常

### ISSUE THREAD

**Issue by zhanyoulin456** [jd-opensource/micro-app#1254]
## 问题描述
> 两个子应用都是vue-router4.x，初始化及某个子应用内部返回跳转的时候，另外一个子应用也会触发路由守卫，导致返回异常

## 复现步骤
1.加载两个子应用的时候，会触发两个子应用的路由守卫
2.某一个子应用内部正常跳转，然后再返回（router.back()或者浏览器返回），此时另外一个子应用也会触发路由守卫，导致跳转异常

## 上传截图
> 无

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。

## 环境信息
- micro-app版本：1.0.0-rc.5
- 主应用前端框架&版本：vue3.3x & vue-router4.2x
- 子应用前端框架&版本：vue3.3x & vue-router4.2x
- 构建工具&版本：均为webpack5

**Comment by bailicangdu** [comment]
返回触发路由守卫是正常的，导致异常大概率是代码问题，最好能提供一个demo看一下
