### ISSUE TITLE
子应用<script type="importmap">不生效导致无法使用esm模式导入第三方依赖

### ISSUE THREAD

**Issue by LAMMUpro** [jd-opensource/micro-app#1255]
## 问题描述
vite应用通过`external: ['vue', 'vue-router', 'element-plus', '@micro-zoe/micro-app', 'test'],`排除第三方依赖, 然后通过<script type="importmap">指定对应依赖的esm.js位置
经测试, 主应用可以正常运行, 子应用单独运行正常, 当子应用套在主应用下时, <script type="importmap">不生效!!! 导致控制台报错TypeError: Failed to resolve module specifier "vue". Relative references must start with either "/", "./", or "../".

期望效果: 将常用的第三方依赖以类cdn的方式引入, 父子应用的资源一致可以有效利用浏览器缓存

## 最小复现仓库
主应用: https://gitee.com/LAMMUpro/microapp-vite-admin.git
子应用A: https://gitee.com/LAMMUpro/microapp-vite-app-a.git

## 复现步骤
1. yarn 安装依赖
2. yarn vite启动应用
3. 访问http://localhost:2666/admin/appA?appA=%2FmicroappA%2Fb
    控制台报错: TypeError: Failed to resolve module specifier "test". Relative references must start with either "/", "./", or "../".
4. 单独访问子应用http://localhost:2333/microappA/b
    控制台正常(通过对比3、4可以证明在父应用下, 子应用的 `import { a } from 'test'` 并没有走importmap)
5. 关掉子应用端口
6. 子应用目录下执行以下命令
   `yarn build`
   `yarn preview --port 2333`    (运行子应用打包产物, 模拟线上环境)
7. 重新访问父应用: http://localhost:2666/admin/appA?appA=%2FmicroappA%2Fb
    控制台报错`TypeError: Failed to resolve module specifier "vue". Relative references must start with either "/", "./", or "../".`

## 上传截图
<img width="1118" alt="image" src="https://github.com/micro-zoe/micro-app/assets/38106851/274a7bfc-a08c-4395-9531-2295518c2503">

## 环境信息
- micro-app版本：1.0.0.rc5
- 主应用前端框架&版本：vue3
- 子应用前端框架&版本：vue3
- 构建工具&版本：vite

**Comment by LAMMUpro** [comment]
已解决，不使用importmap的方案
可以使用external + output.paths的方案加载指定esm资源

**Comment by ollieLiu1988** [comment]
遇到了同样的问题，我想问就算是paths变量打包变量替换成cdn,那比如vue-router 里面import xx from vue 这里的vue是找不到的，如果不用importmap的话，如何解决呢？

**Comment by hkaikai** [comment]
> 遇到了同样的问题，我想问就算是paths变量打包变量替换成cdn,那比如vue-router 里面import xx from vue 这里的vue是找不到的，如果不用importmap的话，如何解决呢？

我是这样处理的：把vue、vue-router等都编译一份，vite会处理好内部引用，编译好后，再paths到编译好的文件
```
import { defineConfig } from "vite";
import { fileURLToPath } from "url";
import { readFileSync } from "fs";
import { dirname, join, resolve } from "path";

export default (externalDeps: string[]) => {
    return defineConfig({
        publicDir: false,
        define: {
            "process.env.NODE_ENV": "'production'",
        },
        build: {
            outDir: "dist/libs",
            lib: {
                entry: externalDeps.reduce((pre, dep) => {
                    if (dep === "lodash") return pre;
                    let depRoot;
                    try {
                        depRoot = dirname(
                            fileURLToPath(import.meta.resolve(`${dep}/package.json`))
                        );
                    } catch {
                        depRoot = dirname(
                            join(
                                fileURLToPath(new URL(".", import.meta.url)),
                                `../../node_modules/${dep}/package.json`
                            )
                        );
                    }
                    const packageJsonPath = resolve(depRoot, "package.json");
                    const pkg = JSON.parse(readFileSync(packageJsonPath, "utf-8"));
                    const moduleEntry = resolve(
                        depRoot,
                        pkg.module ||
                            pkg.exports?.["."]?.browser?.default ||
                            pkg.browser ||
                            pkg.main
                    );
                    return { ...pre, [dep]: moduleEntry };
                }, {}),
                formats: ["es"],
            },
        },
    });
};

```
