### ISSUE TITLE
关闭虚拟路由后，主应用跳转子应用，history会多出来一个__MICRO_APP_STATE__对象，导致浏览器回退时，都会先进history的current地址，然后在点回退才进__MICRO_APP_STATE__对象中的back地址，这是为什么

### ISSUE THREAD

**Issue by revilhui** [jd-opensource/micro-app#1256]
## 问题描述
> 问题的具体描述
主应用关闭虚拟路由后，主应用跳转子应用，history会多出来一个__MICRO_APP_STATE__对象，导致浏览器回退时，都会先进history的current地址，然后在点回退才进__MICRO_APP_STATE__对象中的back地址，这是为什么？
## 复现步骤
1.
2.

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。
![image](https://github.com/micro-zoe/micro-app/assets/23650485/f1ae6aff-6ead-47fd-8631-fa7526c7d9b4)

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。

## 环境信息
- micro-app版本：v1.0.0
- 主应用前端框架&版本：vite3
- 子应用前端框架&版本：vue2
- 构建工具&版本：

**Comment by revilhui** [comment]
1.0.0-rc.4版本就没有这个问题，大于这个版本的，就有

**Comment by revilhui** [comment]
![image](https://github.com/micro-zoe/micro-app/assets/23650485/ff2dce87-4090-4056-8221-6edb035e0b1c)
1.0.0-rc.4版本的history，就没有__MICRO_APP_STATE__对象，并且state中的back，current，forward都有正确的值

**Comment by revilhui** [comment]
我是单页模式，microApp.start({'disable-memory-router': true, ）}// 关闭虚拟路由系统，每次页面跳转的时候，我是主应用vue-router中的router.push去跳转路由，并且通过microApp.setData给子应用发一个消息，子应用接收到后，会用子应用的vue-router去replace跳转对应的页面。（这样history也不会因为两次路由跳转新增history记录）

再1.0.0-rc.4版本的history是正常的，页面能正常跳转和回退。再1.0.0-rc.4后版本的history就会多出来__MICRO_APP_STATE__。每次回退后，都会先进histroy的current地址，再点回退，才进__MICRO_APP_STATE__的back地址，

**Comment by bailicangdu** [comment]
先使用1.0.0-rc.4版本吧，下个版本中rc.5的一些路由问题被修复，不确定是否有你所说的问题
