### ISSUE TITLE
希望可以给一个参数控制 fetch 是否携带 cookie

### ISSUE THREAD

**Issue by WestarkMFF** [jd-opensource/micro-app#126]
## 背景
> 当前部分页面需要携带 cookie 才能正常运行，希望可以用一个参数控制特定的 micro-app 携带 cookie

**Comment by bailicangdu** [comment]
带cookie的场景不多，我们提供了一种解决方式：https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/advanced?id=_1%e3%80%81%e8%87%aa%e5%ae%9a%e4%b9%89fetch

**Comment by WestarkMFF** [comment]
赞
