### ISSUE TITLE
父子应用交互的场景下，modal组件挂载问题

### ISSUE THREAD

**Issue by vampireXia** [jd-opensource/micro-app#1260]
## 问题描述
> 主应用使用三方UI库 naiveui antdvue的modal组件时，如果有微应用的场景下， 会出现样式丢失或挂载到micro-app-body的情况，实际需要的是正确显示modal组件或挂载到父应用的body下

## 复现步骤
1. 父应用创建一个modal组件
2. 让modal组件显示
3. 如果通过父应用去改变子应用表格中的`loading`状态，则会将`modal`挂载到子应用下，如果不去改变`loading`则不会

## 上传截图
> 样式丢失的情况，但切换到非微应用页面可以正确显示modal组件
> ![image](https://github.com/micro-zoe/micro-app/assets/17586390/c725a1b6-71b5-4ede-b902-3a943ae75839)
> 弹窗正确显示，但是挂载到了子应用micro-app-body下的情况，导致在非微应用页面无法正确显示modal组件
> ![image](https://github.com/micro-zoe/micro-app/assets/17586390/03b2ad5d-e5ba-43ce-88f1-f426a899118f)

## 环境信息
- micro-app版本：1.0.0-rc.5
- 主应用前端框架&版本：vue@3.4.21 + naive-ui@2.38.2
- 子应用前端框架&版本：vue@3.4.21 + naive-ui@2.38.2
- 构建工具&版本：vite@5.1.5

[https://github.com/vampireXia/micro-app-bug-demo](url)

场景说明：通过子应用的触发事件回调打开父应用弹窗
demo: 
```
// 打开子应用5173
pnpm run dev:sub
// 打开父应用端口5174
pnpm run dev
```
点击`点击弹父` 打开弹窗, 发现挂载在了`micro-app-body`下，如果这时去非嵌微应用页面，会导致弹窗打不开

**Comment by bailicangdu** [comment]
这个之前提过issue吧

**Comment by lilu0826** [comment]
我之前也遇到过类似的问题，就是主应用提供一个方法让子应用调用，虽然代码在主应用但是是由子应用调用的，此时代码是在子应用的沙箱环境中运行的。
后面改成用事件的方式处理就正常了
window.microApp.dispatch({type: '子应用发送给主应用的数据'})

**Comment by bailicangdu** [comment]
问题出在主应用直接调用了子应用传递的函数创建元素，导致作用域绑定异常，正常情况下应该是主应用下发通知，让子应用自行处理元素操作。
解决方式：在主应用调用子应用函数后执行removeDomScope(true)清除元素作用域
<img width="1312" alt="image" src="https://github.com/micro-zoe/micro-app/assets/20297227/9bb124cb-0e15-4002-8b0c-192810791b61">
