### ISSUE TITLE
在火狐浏览器下，子应用加载后favicon.ico会把主应用的图标给替换掉。

### ISSUE THREAD

**Issue by Yulingsong** [jd-opensource/micro-app#1262]
## 问题描述
> 问题的具体描述

## 复现步骤
1.火狐浏览器下，刷新，能肉眼看到favicon.ico变化。并且控制台-网络中-可以看到请求。谷歌没问题

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。
<img width="239" alt="image" src="https://github.com/micro-zoe/micro-app/assets/13497831/49368de1-5793-4b40-bb3e-4aa6f6a9e945">

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。

## 环境信息
- micro-app版本：1.0.0-rc.5版本（rc.3 和rc.4也都存在）
- 主应用前端框架&版本：vue3+vite
- 子应用前端框架&版本：react+vite+react router v6
- 构建工具&版本：vite

**Comment by bailicangdu** [comment]
临时解决方案：给子应用link图标元素加上exclude属性，如`<link rel="icon" href="/favicon.ico" exclude />`，问题会在后续版本中修复，感谢反馈
