### ISSUE TITLE
子应用报SyntaxError: Unexpected token 'export'

### ISSUE THREAD

**Issue by Lucklj521** [jd-opensource/micro-app#1266]
## 问题描述
> 将主应用和子应用都打包发布到线上测试的环境，就报这个SyntaxError: Unexpected token 'export' 错误了，本地开发没有出现这个bug

## 复现步骤
1.
2.

## 上传截图
> 
![image](https://github.com/micro-zoe/micro-app/assets/93632042/06120295-75a1-4cf3-bfe6-aa1fba6e9193)

![image](https://github.com/micro-zoe/micro-app/assets/93632042/632b36f8-595f-4000-85ff-325bac3def4f)

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。

## 环境信息
- micro-app版本：1.0.0-rc.5
- 主应用前端框架&版本：vue3&3.4.21
- 子应用前端框架&版本：vue2&2.7.0
- 构建工具&版本：主应用vite&5.1.6，子应用vue/cli

**Comment by Lucklj521** [comment]
问题已经解决，是我在主应用里没有访问到子应用，我在nginx里的访问子应用公共路径里配置了/，但在主应用的源码访问子应用的公共路径后没有添加/，我发现是版本rc.4和rc.5的对子应用的公共路径的有无斜杠做了不同的规则处理，rc.4是默认如果没有/会自带一个/

**Comment by dengjunxx** [comment]
我在尝试预加载子应用时也出现同样问题了，本地没事，线上环境不行，但是我没有在源码里配置publicPath，用的时vite+vue3，请问要如何解决呀？
