### ISSUE TITLE
父应用将元素插入到子应用里【必现】

### ISSUE THREAD

**Issue by Fov6363** [jd-opensource/micro-app#1269]
## 问题描述
> 父应用将元素插入到子应用里，影响功能的使用

## 复现步骤
1. 父应用在 createElement 之前发出一个 blur 事件，子应用监听 blue 事件，此时父应用就会把元素插入到子应用之中

#### 父应用
```
"use client";
import React from "react";
import styles from "./page.module.css";
import microApp from "@micro-zoe/micro-app";
microApp.start();


export default function Home() {
  const ref = React.useRef();
  const [isShow, setIsShow] = React.useState(false);
  const onClick = () => {
    setIsShow(!isShow);
    ref.current.blur();
  };
  if (isShow) {
    let dd = document.createElement("div");
    dd.innerHTML = "hello" + Date.now();
    document.body.appendChild(dd);
  }
  return (
    <main className={styles.main}>
      <micro-app name="test" url="http://test.local.com/stt2/index.html"></micro-app>

      <button onClick={onClick} ref={ref}>
        Click Me!
      </button>
    </main>
  );
}
```

子应用
```<html>

<head>
    <script type="text/javascript">
        addEventListener('blur', function () {
            console.log('parent', document.visibilityState);
        }, true)

    </script>
</head>

<body>
    <hi>Hi hi hi</hi>
</body>

</html>
```

## 上传截图
> 
![image](https://github.com/micro-zoe/micro-app/assets/16603080/d3e079fb-4a23-4050-a499-091ee6dde80c)

## 复现仓库
> https://github.com/Fov6363/micro-app-test

## 环境信息
- micro-app版本：1.0.0-rc.5
- 主应用前端框架&版本：react@18
- 子应用前端框架&版本：react@18
- 构建工具&版本：next 脚手架

产生这个原因，我的分析是子应用通过 addEventListener 监听了 blur 事件，然后因为 throttleDeferForSetAppName 的原因，defer 才会设置为 null，在这个空隙中，父应用 createElement 绑定到了错误了 currentMicroAppName ，导致元素被创建到子应用里了

想咨询一下这个问题如何解决？

还想咨询两个问题？
1、对于基座应用的 document 也被劫持了，这个目的是什么？-> 如果把这个放开，这个 bug 也可以解决
2、对于子应用中的 throttleDeferForSetAppName 为什么要使用 defer 释放，而不是在取到值之后直接释放？-> 如果改一下这个，也能解决这个 bug

非常感谢 micro-app 的开源团队，期待回复～

**Comment by bailicangdu** [comment]
参考 https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/dom-scope?id=%e8%a7%a3%e9%99%a4%e5%85%83%e7%b4%a0%e7%bb%91%e5%ae%9a

**Comment by bailicangdu** [comment]
解决方式有两种：1、使用removeDomScope清除绑定 
<img width="864" alt="image" src="https://github.com/micro-zoe/micro-app/assets/20297227/b40c6ead-b7e9-4553-8fe7-3ca5554cf7da"> 2、切换到iframe沙箱

**Comment by Fov6363** [comment]
@bailicangdu  感谢，对于我们业务场景来看，removeDomScope 不太适用，因为它的发出 blur 的组件与监听 blur 事件同时会在基座应用与子应用中运行。我们会尝试一下 iframe 沙箱的方式。

对于以下两个问题还比较困惑，辛苦有空可以解答一下～

1、对于基座应用的 document 也被劫持了，这个目的是什么？
2、对于子应用中的 throttleDeferForSetAppName 为什么要使用 defer 释放，而不是在取到值之后直接释放？

**Comment by bailicangdu** [comment]
同步的元素绑定只能覆盖子应用部分场景，异步可以覆盖更多场景，但这也导致部分场景下元素绑定污染到主应用，这是with沙箱实现机制导致的，iframe沙箱在这方便表现更好
