### ISSUE TITLE
路由跳转 携带二级路径

### ISSUE THREAD

**Issue by hzfvictory** [jd-opensource/micro-app#127]
## 问题描述
2. 反馈1
假如当前路由  ’/mic-react/list‘
使用下面这种路由跳转方式后：
```
history.pushState(null, null, "/mic-vue2/about");
window.dispatchEvent(new PopStateEvent("popstate", { state: null }));
```
此时页面的路由 path 为 ’/mic-react/mic-vue2/about‘

2. 反馈2
都在 history 路由， 当子应用跳转到一个空路由，此时用基座路由跳转回来，路由的path 已变，但页面没反应，用子应用的路由跳转就ok。  是要子应用做路由为空的校验吗

## 环境信息
- micro-app版本：0.4.0
- 主应用前端框架&版本：vue2
- 子应用前端框架&版本：vue2
- 构建工具&版本：webpack

**Comment by bailicangdu** [comment]
第一个问题在vue-router4中会出现，此时不建议使用pushState，第二个问题没看懂，是rewrite了吗

**Comment by hzfvictory** [comment]
> 第一个问题在vue-router4中会出现，此时不建议使用pushState，第二个问题没看懂，是rewrite了吗

第二个问题  就是目前在空的路由页面，用基座跳转页面是没反应的（假如跳转到 /mic-react/list ），子应用跳转是正常的假如跳转到 /mic-react/list ），他俩目的路由是一致的就是基座跳转页面是没反应。

**Comment by bailicangdu** [comment]
子应用初始化后，基座无法控制子应用的路由，你可以通过基座下发通知，让子应用进行跳转

**Comment by hzfvictory** [comment]
> 子应用初始化后，基座无法控制子应用的路由，你可以通过基座下发通知，让子应用进行跳转

这个很不现实，我写中后台，列表页跳转到详情页，然后我的菜单在基座，点击菜单的中的列表页回不来，这可是大问题啊

**Comment by bailicangdu** [comment]
基座和子应用的路由无法相互影响，路由只能控制自身
