### ISSUE TITLE
保活状态下，切换子应用，子应用中的某个iframe页面，会重新加载

### ISSUE THREAD

**Issue by Gordoncs** [jd-opensource/micro-app#1275]
## 问题描述
> 问题的具体描述
micro下有多个子应用，使用了"keep-alive": true。 但《子应用A》里有iframe嵌入页面，这时候打开该页面，然后切换到《子应用B》，再切回子应用A，会导致iframe嵌入页面重新加载（该子应用下，其他页面保活正常。并且该子应用下，iframe与其他页面切换，缓存正常，使用v-show进行控制）
## 复现步骤
1.《子应用A》里有iframe嵌入页面，这时候打开该页面
2.切换到《子应用B》
3.切回子应用A
4.子应用A里打开的iframe，会重新刷新

## 上传截图
> 。

## 复现仓库
> 。

## 环境信息
- micro-app版本：1.0.0-rc.4
- 主应用前端框架&版本："vue": "2.6.11",
- 子应用前端框架&版本："vue": "2.6.11",
- 构建工具&版本：

**Comment by bailicangdu** [comment]
keep-alive存在脱离文档的操作，导致iframe重新加载。这是keep-alive实现机制和iframe原理冲突导致的

**Comment by Gordoncs** [comment]
感谢解答，那对于这种情况，有什么好的解决方法和建议吗？

**Comment by bailicangdu** [comment]
除非iframe始终在文档中保留，否则没其它方式了

**Comment by Mutter45** [comment]
目前好像要缓存含有iframe的子应用，只能就是类似用dispaly的显示隐藏来避免ifrmae刷新，
类似于把含有iframe的子应用一直不灭活，只是样式隐藏
![image](https://github.com/micro-zoe/micro-app/assets/93197952/db795e32-b6fc-4938-b398-b70e8b7d18de)

**Comment by Gordoncs** [comment]
> 目前好像要缓存含有iframe的子应用，只能就是类似用dispaly的显示隐藏来避免ifrmae刷新， 类似于把含有iframe的子应用一直不灭活，只是样式隐藏 ![image](https://private-user-images.githubusercontent.com/93197952/344896780-db795e32-b6fc-4938-b398-b70e8b7d18de.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5MDEyMTQsIm5iZiI6MTcxOTkwMDkxNCwicGF0aCI6Ii85MzE5Nzk1Mi8zNDQ4OTY3ODAtZGI3OTVlMzItYjZmYy00OTM4LWIzOTgtYjcwZThiN2QxOGRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAyVDA2MTUxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ4ZGRlY2EyNjMxNjlmNzAwMzQxNzQxZmMzMjlmYzIwZWRlOWI0NzY3ODY3N2RjM2VlMDk2ZmNhZjc3NjkxYzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0CH6fGKtc5vmq-DQeg81Y739HgFy7rOyCOSQJ-IzYRM)

看来目前只有这个办法了，谢谢

**Comment by Gordoncs** [comment]
> 除非iframe始终在文档中保留，否则没其它方式了

收到

**Comment by Gordoncs** [comment]
done
