### ISSUE TITLE
子应用可以作为一个组件使用，不更新浏览器 URL 吗

### ISSUE THREAD

**Issue by qyjs** [jd-opensource/micro-app#1277]
基座 vue3
子应用 vue3
子应用可以作为一个组件使用，不更新浏览器 URL 吗

**Comment by bailicangdu** [comment]
切换为pure路由模式即可
<img width="1223" alt="image" src="https://github.com/micro-zoe/micro-app/assets/20297227/28d3f861-8623-4846-b76a-9bf053f5adad">
