### ISSUE TITLE
样式污染问题

### ISSUE THREAD

**Issue by hjn1028** [jd-opensource/micro-app#1279]
## 问题描述
主应用是Vue3 +Element Plus 子应用是Vue2 + Element UI

## 复现步骤
1.![image](https://github.com/micro-zoe/micro-app/assets/33085961/0c86af59-eda5-43d6-a65e-e8addda97bf8)
子应用直接访问了主应用的css文件导致样式改变。
2.![image](https://github.com/micro-zoe/micro-app/assets/33085961/4e1b14ee-d567-4d30-94b5-bd45adc97be5)
去掉height后样式恢复正常~还有很多类似的样式问题，包括不限于按钮、弹框等等问题

![image](https://github.com/micro-zoe/micro-app/assets/33085961/d918c60b-c2d1-4895-93fe-a9ef585d384e)
此处为主应用的资源

麻烦请问大佬们，有什么好的解决方案吗？

## 环境信息
- micro-app版本：1.0.0-rc.5
- 主应用前端框架&版本：Vue@3.x+vite@5.x+Element Plus
- 子应用前端框架&版本：Vue@2.x+webpack+Element UI

**Comment by bailicangdu** [comment]
问题出在主、子都是用了elementui，但版本却不一样，有大量相同的class名称冲突了，导致主应用的样式对子应用产生影响。elementui提供了一个方法修改class前缀，可以解决这个问题[自定义命名空间](https://element-plus.org/zh-CN/guide/namespace.html)

**Comment by hjn1028** [comment]
好的，谢谢大佬，我去试试！

**Comment by wellenzhong** [comment]
刚好也遇到这个问题，及时雨啊！
