### ISSUE TITLE
子应用是angularjs老项目，打包后html是每个模块分别的html模板，基座应用获取不到

### ISSUE THREAD

**Issue by xiaoxiangmuyi** [jd-opensource/micro-app#129]
基座应用是vue3，history模式，本地启动访问地址是http://localhost:8083/myapp/#/abc
子应用https://localhost:8080/#/abc
这样基座应用无法访问到子应用的abc模块的html文件

**Comment by qiutianxu** [comment]
> 基座应用是vue3，history模式，本地启动访问地址是http://localhost:8083/myapp/#/abc 子应用https://localhost:8080/#/abc 这样基座应用无法访问到子应用的abc模块的html文件

请问angularjs（1.X版本）最后集成成功了吗。这个问题解决了吗
