### ISSUE TITLE
子应用使用docx-preview插件无法预览docx文档，单独访问正常显示

### ISSUE THREAD

**Issue by ByronYan01** [jd-opensource/micro-app#1292]
## 问题描述
> 问题的具体描述

子应用使用docx-preview插件无法预览docx文档，单独访问正常显示

## 复现步骤
1.访问主应用，点击加载子应用预览word页，点击预览，无反应
2.直接访问子应用，点击预览，正常显示

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。

![image](https://github.com/micro-zoe/micro-app/assets/60208330/2162d834-594a-4397-ac72-6bbc1a62f5c9)
![image](https://github.com/micro-zoe/micro-app/assets/60208330/f986f3a7-2b6e-4717-9b50-16e0ce6357fb)

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。

https://github.com/ByronYan01/demo0408.git

## 环境信息
- micro-app版本：1.0.0-rc.3
- 主应用前端框架&版本：vue3
- 子应用前端框架&版本：vue3
- 构建工具&版本：vite

**Comment by ByronYan01** [comment]
目前暂时只能主应用依赖此插件，提供给子应用使用；请问还有其他优雅得解决方法嘛

**Comment by bailicangdu** [comment]
> 目前暂时只能主应用依赖此插件，提供给子应用使用；请问还有其他优雅得解决方法嘛

问题已经定位并修复，发布后会通知，感谢反馈

**Comment by ByronYan01** [comment]
> > 目前暂时只能主应用依赖此插件，提供给子应用使用；请问还有其他优雅得解决方法嘛
> 
> 问题已经定位并修复，发布后会通知，感谢反馈

好的，多谢，期待新版本
