### ISSUE TITLE
是否支持SSR应用 如 next.js或nuxt.js框架？

### ISSUE THREAD

**Issue by byoungd** [jd-opensource/micro-app#13]
目前给出的examples都是客户端渲染的，micro-app是否支持SSR应用 如 next.js或nuxt.js框架，如果支持的话，希望可以给出基本的示例，非常感谢！

**Comment by bailicangdu** [comment]
可以使用，我在文档里补充一下吧

**Comment by zhangjing007** [comment]
这个就非常棒了啊

**Comment by byoungd** [comment]
> 可以使用，我在文档里补充一下吧

期待能尽快看到官方的例子！

**Comment by zhangyuang** [comment]
@byoungd http://doc.ssr-fc.com/docs/features$faq#%E4%B8%8E%20micro-app%20%E7%BB%93%E5%90%88%E4%BD%BF%E7%94%A8
我们的服务端渲染框架已经跟 micro-app整合了。这里夸一下micro-app，这种无侵入性的接入方式我非常喜欢

**Comment by byoungd** [comment]
> @byoungd http://doc.ssr-fc.com/docs/features$faq#%E4%B8%8E%20micro-app%20%E7%BB%93%E5%90%88%E4%BD%BF%E7%94%A8
> 我们的服务端渲染框架已经跟 micro-app整合了。这里夸一下micro-app，这种无侵入性的接入方式我非常喜欢

赞 我这就去试试

**Comment by bailicangdu** [comment]
参考文档：https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/framework/nextjs
