### ISSUE TITLE
把老的 react 项目嵌入 新开的微前端 基座应用中 报了个资源获取不到

### ISSUE THREAD

**Issue by HenryZhu-1988** [jd-opensource/micro-app#130]
![image](https://user-images.githubusercontent.com/43346131/139000700-cd3ede6e-7d24-4e3c-b3de-0d06c70a17d9.png)

**Comment by bailicangdu** [comment]
这是webpack dll文件的报错，参考 
https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/questions?id=_13%e3%80%81%e9%94%99%e8%af%af%e4%bf%a1%e6%81%af%ef%bc%9axxx-%e6%9c%aa%e5%ae%9a%e4%b9%89

**Comment by HenryZhu-1988** [comment]
> 这是webpack dll文件的报错，参考 https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/questions?id=_13%e3%80%81%e9%94%99%e8%af%af%e4%bf%a1%e6%81%af%ef%bc%9axxx-%e6%9c%aa%e5%ae%9a%e4%b9%89

good job!
