### ISSUE TITLE
主应用跟子应用部署在同一域名和端口下报name冲突

### ISSUE THREAD

**Issue by XiaoDan12202** [jd-opensource/micro-app#1307]
## 问题描述
> 问题的具体描述

## 复现步骤
1.主应用为localhost/mtvx，子应用为localhost/mtvx/report_app

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。
micro-app配置如下：
![image](https://github.com/user-attachments/assets/6ed01018-cdc7-4901-9743-5752470a4bab)
nginx配置：
![image](https://github.com/user-attachments/assets/a9c06df1-f45e-48c7-9423-6748c57afa7b)

报错如下：
![image](https://github.com/user-attachments/assets/2af1d930-e606-42b1-b61e-328e255d344c)

## 环境信息
- micro-app版本：v1.0.0-rc.5
- 主应用前端框架&版本：vue3.3.4
- 子应用前端框架&版本：vue3.3.4
- 构建工具&版本：vite4.4.5

**Comment by bailicangdu** [comment]
死循环了
<img width="773" alt="image" src="https://github.com/user-attachments/assets/374ce41c-b795-4abc-b585-acec89355927">

**Comment by XiaoDan12202** [comment]
换了位置还是一样的

**Comment by bailicangdu** [comment]
单独打开子应用正常吗

**Comment by XiaoDan12202** [comment]
已解决，谢谢
