### ISSUE TITLE
[rawWindow] 子应用中使用的第三方库中，使用了 window.location.href = xxx 会导致错误

### ISSUE THREAD

**Issue by baijunjie** [jd-opensource/micro-app#1309]
由于前端是 vite 编译，所以我开启了 iframe 沙箱，这就导致在使用 window.location.href = xxx 时，收到了以下错误:
```
Refused to display 'https://example.com/' in a frame because it set 'X-Frame-Options' to 'sameorigin'.
```
由于是第三方库中的实现，我无法将其修改为 rawWindow。请问是否有其他方式可以让 iframe 沙箱中的 window.location.href 使用主应用的 window？

**Comment by bailicangdu** [comment]
将第三方库放入基座中，传递给子应用使用
