### ISSUE TITLE
v1.0.0-rc.6 首次进入子应用获取到的路由错误

### ISSUE THREAD

**Issue by Lzy328** [jd-opensource/micro-app#1317]
## 问题描述
> v1.0.0-rc.6  首次进入子应用获取到的路由错误

## 复现步骤
1.v1.0.0-rc.6 
2.主应用defaultPath 为/test，子应用获取到的路由path 为 / 导致跳转错误

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。

## 环境信息
- micro-app版本：v1.0.0-rc.6
- 主应用前端框架&版本：vue3.2.47
- 子应用前端框架&版本：vue3.2.47
- 构建工具&版本：

**Comment by Lzy328** [comment]
在v1.0.0-rc.5的版本子应用获取到路由是正确的。

**Comment by sakoojiang** [comment]
相同的问题
在native 路由模式下
v1.0.0-rc.5 正常
v1.0.0-rc.6   No match found for location with path "/"

**Comment by bailicangdu** [comment]
无法复现所述问题，可以提供一个demo吗
