### ISSUE TITLE
拼写错误：destory => destroy

### ISSUE THREAD

**Issue by zhaowei-plus** [jd-opensource/micro-app#132]
## 拼写错误

> 这哪位哥们写到代码，没有review就提交了呢 destory => destroy

class MicroApp extends EventCenterForBaseApp implements MicroAppConfigType {
  tagName = 'micro-app'
  shadowDOM?: boolean
  destory?: boolean - 写错了。。
  inline?: boolean

   disconnectedCallback (): void {
      this.hasConnected = false
      elementInstanceMap.delete(this)
      this.handleUnmount(this.getDisposeResult('destory')) - 还是拼写错误
      if (elementInstanceMap.size === 0) {
        releasePatches()
      }
    }

强迫症表示很难受

## 期望的效果

期望可以有所优化

**Comment by bailicangdu** [comment]
好的，谢谢提醒，我们会进行修改

**Comment by bailicangdu** [comment]
已修复，[release v0.4.2](https://github.com/micro-zoe/micro-app/releases/tag/v0.4.2)
