### ISSUE TITLE
富文本编辑器问题

### ISSUE THREAD

**Issue by hjn1028** [jd-opensource/micro-app#1321]
## 问题描述
> 升级到1.0.0-rc.6版本后子应用使用wangeditor富文本编辑器报错Maximum call stack size exceeded，从而影响到工具栏加载失败

## 复现步骤
![image](https://github.com/user-attachments/assets/9a565d05-7f44-4dc0-bb41-b5c807968e09)

## 环境信息
- micro-app版本：1.0.0-rc.6
- 主应用前端框架&版本：vite@5.x vue@3.x
- 子应用前端框架&版本：vite@5.x vue@3.x
- 构建工具&版本：vite@5.x

**Comment by 754442658** [comment]
同样的问题

**Comment by L-Z-Y** [comment]
请问解决了吗？

**Comment by timhub66** [comment]
升级到 v1.0.0-rc.11 试试
