### ISSUE TITLE
初次加载时，子应用内部路由跳转后回退会报错[micro-app] app xxxx: app name conflict, an app named xxxx is running

### ISSUE THREAD

**Issue by swing-t** [jd-opensource/micro-app#1330]
## 问题描述
初次加载时，子应用内部路由跳转后点浏览器回退或者router会报错[micro-app] app xxxx: app name conflict, an app named xxxx is running,刷新之后就不会出现这个问题

## 环境信息
- micro-app版本：0.8.10
- 主应用前端框架&版本：vue2
- 子应用前端框架&版本：vue2

**Comment by bailicangdu** [comment]
更新到最新版本看看

**Comment by swing-t** [comment]
> 更新到最新版本看看

> 更新到^1.0.0-rc.6且按照文档做出以下调整：
1、在start中添加配置microApp.start({
  'disable-memory-router': true, // 关闭虚拟路由系统
  'disable-patch-request': true, // 关闭对子应用请求的拦截
})；
2、 :key="$route.fullPath"修改为 :key="$route.name"
加载子应用时一直频繁刷新

**Comment by swing-t** [comment]
> > 更新到最新版本看看
> 
> 更新到^1.0.0-rc.6且按照文档做出以下调整： 1、在start中添加配置microApp.start({ 'disable-memory-router': true, // 关闭虚拟路由系统 'disable-patch-request': true, // 关闭对子应用请求的拦截 })； 2、修改为 加载子应用时一直频繁刷新

控制台报：element micro-app is already defined
