### ISSUE TITLE
虚拟路由跳转页面，子应用的缓存不能保持

### ISSUE THREAD

**Issue by xiaozhao8** [jd-opensource/micro-app#1333]
![image](https://github.com/user-attachments/assets/5a000ef2-c134-48cd-9d0b-d15efa4daa3e)

**Comment by xiaozhao8** [comment]
这个是子应用里边加的缓存，用虚拟路由跳转后做不到，路由缓存保持

**Comment by xiaozhao8** [comment]
子应用中的keepalive路由缓存
子应用单独跑缓存没问题
就是在基座中，用虚拟路由，操作子应用跳转
他页面每次会重新渲染

**Comment by bailicangdu** [comment]
顶部tab属于子应用的吗，检查一下点击tab是否触发了子应用卸载

**Comment by xiaozhao8** [comment]
已解决，感谢大佬
