### ISSUE TITLE
vite vue3 升级到 1.0.0-rc.6 路由跳转异常

### ISSUE THREAD

**Issue by Xy-Zipper** [jd-opensource/micro-app#1335]
## 问题描述
> 路由跳转异常，直接跳转到 / 页面

## 复现步骤

主应用：
```
<micro-app
      name="thirdApp"
      iframe
      url="http://localhost:3003/smart-school/class-list"
    ></micro-app>
```

子应用路由：
```
{
    path: "/",
    component: () => import("@/layout/home.vue")
  },
  {
    path: "/smart-school",
    name: "smart-school",
    children:  [
  {
    path: "class-list",
    name: "class-list",
    component: () => import("@/views/smart-school/class-list/index.vue"),
    meta: {
      customNavBar: true
    }
  }
];
  }
```

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。

## 复现仓库
> https://github.com/Xy-Zipper/mic-test

## 环境信息
- micro-app版本：1.0.0-rc.6
- 主应用前端框架&版本："vue": "^3.3.6",
- 子应用前端框架&版本： "vue": "^3.3.6",
- 构建工具&版本："vite": "^4.5.0",

**Comment by Xy-Zipper** [comment]
1.0.0-rc.5 可以正常跳转路由地址

**Comment by Xy-Zipper** [comment]
https://github.com/Xy-Zipper/mic-test

**Comment by timhub66** [comment]
> https://github.com/Xy-Zipper/mic-test

@Xy-Zipper ,我试了一下能 基座能正常打开子应用，子应用也能正常返回基座，具体你那边路由跳转异常是怎么样的？
![2024-08-19 14 27 45](https://github.com/user-attachments/assets/bbf1dfa8-bdda-45a7-aa0e-ff4e71d67e09)

**Comment by bailicangdu** [comment]
当初始化路由的createWebHistory()参数为空时，vue-router会兜底到base元素上获取基础路径，在micro-app 1.0.0-rc.6版本中对于base的获取条件做了修改，导致出现问题，我们会在下个版本进行修复，感谢反馈。

临时解决方式：子应用createWebHistory()传入参数`import.meta.env.BASE_URL`
<img width="611" alt="image" src="https://github.com/user-attachments/assets/0a4c0b9d-1622-44e0-9c1f-0e9c05b4c56c">
