### ISSUE TITLE
对于不支持 CustomElements 的浏览器，还会提示 ShadowDom 这个类不存在

### ISSUE THREAD

**Issue by LinFeng1997** [jd-opensource/micro-app#134]
## 背景
> 描述您希望改进的问题。
对于不支持 CustomElements 的浏览器，无论有没有使用 shadow dom，都会提示 ShadowDom 这个类不存在

看源码是 `xxx instanceof ShadowRoot` 的时候没有判断 ShadowDom 是否存在

## 期望的效果
1. 源码里在使用 ShadowDom 时进行判断
2. 文档里提示用户如果在 CustomElements 不支持的浏览器里想使用 ShadowDom 的话，还需要引入 ShadowDom 的 polyfill

**Comment by bailicangdu** [comment]
shadowDom并不是必须的，这里只是做了一层判断，我们下个版本会进行优化，对于不支持的浏览器不可以开启shadowDom

**Comment by bailicangdu** [comment]
谢谢提醒

**Comment by bailicangdu** [comment]
问题已修复，https://github.com/micro-zoe/micro-app/releases/tag/v0.4.3
