### ISSUE TITLE
子应用中使用 dom7 报错

### ISSUE THREAD

**Issue by wayingCode** [jd-opensource/micro-app#1343]
## 问题描述
> 子应用中使用 dom7 操作 dom 属性时报错

## 复现步骤
1. 运行复现仓库中的主应用（main）、子应用（vue-dom7-child）
2. 访问http://localhost:5173/micro-app-dom7?micro-app-dom7=%2F
3. 页面挂载后等待一秒即可在控制台查看报错信息

## 上传截图
> 
![image](https://github.com/user-attachments/assets/af30fad8-ee11-4ebb-b5a0-c4a38964a347)
>
![image](https://github.com/user-attachments/assets/5d49803e-7902-41ef-b609-c89cf4fc26e8)

## 复现仓库
> https://github.com/wayingCode/micro-app-bug-demo

## 环境信息
- micro-app版本：1.0.0-rc.8
- 主应用前端框架&版本：vue@3.4.37
- 子应用前端框架&版本：vue@3.4.37、dom7@4.0.6
- 构建工具&版本：vite@5.4.1

## 说明
**经测试 ,1.0.0-rc.5之后的版本出现该问题**

**Comment by timhub66** [comment]
@wayingCode ，语法有点问题，removeElAttr 接受的是一个jq对象

**Comment by timhub66** [comment]
@wayingCode ，老铁语法有点问题，removeElAttr 接受的是一个jq对象，removeElAttr 改成如下试试
```js
const removeElAttr = (collection: any) => {
  console.log(collection)
  collection.removeAttr('style')
  const children = collection.children()
  if (children && children.length){
    children.forEach(childEl => removeElAttr($(childEl)))
  }
}

```
