### ISSUE TITLE
跨域问题

### ISSUE THREAD

**Issue by futugyou** [jd-opensource/micro-app#1347]
1. 非dev，dev没问题
2. 原本的没有跨域问题，主应用可以正常访问子应用
3. 主应用中添加的可观测性组件，会发送相应的tracing到数据收集服务器。
4. 由于可观测性组件的添加，所有主应用发出的fetch请求的request head中被加入了一条'traceparent: ******'
5. 这时主应用访问子应用时报出跨域错误了。

主应用 react+vite
子应用 vue3+vite
任意版本都行

主应用使用的可观测性组件是 [honeycomb](https://docs.honeycomb.io/get-started/start-building/web/#send-data-to-honeycomb)

**Comment by raoenhui** [comment]
可以通过自定义fetch替换框架自带的fetch，https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/advanced?id=custom-fetch

**Comment by futugyou** [comment]
试了自定义fetch，不行。

```ts
microApp.start({
  'keep-alive': true,
  fetch(url, options, appName) {
    const config = {
      mode: 'cors',
    }

    return window.fetch(url, Object.assign(config, options)).then((res) => {
      return res.text()
    })
  }
})
```

这样写的也不知道对不对。

而且令我不解的是同样的线上子应用，我从主应用开发环境可以访问，从主应用线上环境就不行

**Comment by timhub66** [comment]
@futugyou ，可能是 请求头 traceparent 引起的跨域，服务器将 Access-Control-Allow-Headers 的值设为通配符“*” 试试；或者你在自定义fetch中按需 删了这个 traceparent
