### ISSUE TITLE
主应用切换相同子路由页面不刷新

### ISSUE THREAD

**Issue by huyanhai** [jd-opensource/micro-app#135]
## 问题描述
在主应用切换相同子路由页面不刷新

## 复现步骤
1.从vue2路由切换到vue3路由正常显示
2.从vue3路由切换到vue3/about页面不刷新

## 上传截图
第一步
![image](https://user-images.githubusercontent.com/28421572/139414882-6d081a9e-0ddd-49b0-90bf-20b70f08334a.png)
第二步
![image](https://user-images.githubusercontent.com/28421572/139414934-06333ede-4752-4c92-baa2-cf60190dbb71.png)

## 复现仓库
仓库地址：https://github.com/huyanhai/microApp-demo.git

## 环境信息
- micro-app版本：0.4.2
- 主应用前端框架&版本：vue:3.0.0
- 子应用前端框架&版本：vue:3.0.0
- 构建工具&版本：@vue/cli-service:4.5.0

**Comment by bailicangdu** [comment]
麻烦提供完整的包括基座和子应用的代码

**Comment by bailicangdu** [comment]
侧边栏是属于基座应用的吗

**Comment by bailicangdu** [comment]
参考 https://github.com/micro-zoe/micro-app/issues/100
