### ISSUE TITLE
iframe 沙箱嵌套，当在子路由下刷新时，孙子应用调用 getGlobalData 会获取到父应用设置的 globalData

### ISSUE THREAD

**Issue by kiyass** [jd-opensource/micro-app#1350]
如上，当 A -> B -> C 嵌套加载时，如果直接使用路由的方式加载到 C 应用（http://localhost:3000/appB/appC），在 C 应用打印 window.microApp.getGlobalData() 获取到了 A 应用设置的 globalData。如果是一层一层点击加载，先进入 B 应用，再访问 C 应用，此时 C 应用获取到的 globalData 符合预期，是 B 应用设置的 globalData。

前提：
- A，B，C 三个应用都使用 umd 模式
- 虽然在文档中提到多层嵌套时，需要设置 tagName 为 micro-app-xxx，但是发现在使用 iframe 沙箱时，如果设置 tagName 使用子路由直接加载时不会渲染 C 应用，所以目前 tagName 使用的是默认的 micro-app
- 当前使用的 micro app 版本：1.0.0-rc.6

**Comment by kiyass** [comment]
仓库地址：https://github.com/kiyass/micro-app-demo

场景一：
- 进入http://localhost:8000
- 依次进入 app-1，app-1-1
- 点击 app-1-1 中的按钮获取 globalData

场景二：
- 直接进入 http://localhost:8000/app-1/app-1-1
- 点击 app-1-1 中的按钮获取 globalData

可以看到，场景一获取到的 globalData 来自 app-1，场景二获取到的 globalData 来自 host-app。

**Comment by kiyass** [comment]
似乎只要是在子路由下刷新（场景二），父子间的 API 调用都会有问题，路由跳转也有报错，如果从子应用跳转到孙子应用，会有下面的提示信息。
<img width="386" alt="image" src="https://github.com/user-attachments/assets/5db53eb2-5b60-49a9-8807-a9f253645113">

<img width="576" alt="image" src="https://github.com/user-attachments/assets/709f13d8-7bc0-409d-883c-eef7c840f8de">

**Comment by timhub66** [comment]
@kiyass ，app-1 和 app-1-1 挂载和卸载的钩子写的不对，分别是 onmount 和 onunmount，另外 host-app 的 Link 加上 reloadDocument 属性

**Comment by kiyass** [comment]
@timhub66 我改用 onmount 和 onunmount 确实可以，但是这是否意味着就不是 umd 模式了，我发现如果我同时定义了 mount，unmount，onmount 和 onunmount，定义的 onmount 和 onunmount 就不会被执行到。

https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/life-cycles?id=%e5%85%a8%e5%b1%80%e4%ba%8b%e4%bb%b6
官网这里提到的 onmount 和 onunmount 是由主应用定义的监听？有点没理解为什么这里 onmount 和 onunmount 用来做挂载和卸载？可以展开说说吗，感谢
