### ISSUE TITLE
vite 项目里加载 webpack/vite 工程的cesium子应用 均无任何报错,但是也无法渲染出地球,也不加载瓦片.

### ISSUE THREAD

**Issue by SuGod** [jd-opensource/micro-app#1351]
vite 项目里加载 webpack/vite 工程的cesium子应用 均无任何报错,但是也无法加渲染出地球,也不加载瓦片,天空盒等其他工具组件都正常显示,功能也正常.只是没有地球..不知道是什么原因.
而且以下配置除了`inline`,其他都需要配置,否则会报错.
```vue
 <micro-app
    name="cesium-map"
    url="http://localhost:8080/"
    inline
    iframe
    disable-scopecss
    disable-memory-router
  />
```

**Comment by SuGod** [comment]
```json
"@micro-zoe/micro-app": "1.0.0-rc.8"
```
之前有一个项目使用的是`0.8`版本的,子应用是webpack的 ,当时也没有iframe这些配置,地图模型什么都是正常的..不知道为什么新项目用新版本反而出不来了.

**Comment by SuGod** [comment]
> Hello @SuGod. In order to facilitate location and troubleshooting, we need you to provide a realistic GitHub repository. 您好 @SuGod, 为了方便定位和排查问题，我们需要您提供一个重现实例，请提供一个尽可能精简的 GitHub 仓库地址。

https://github.com/SuGod/micro-app-map-demo

**Comment by SuGod** [comment]
@timhub66 [Demo](https://github.com/SuGod/micro-app-map-demo)项目已提交. 
单独打开或者直接使用iframe加载地图子应用都是正常的.但是mcrio-app中却不加载地图瓦片.

**Comment by timhub66** [comment]
@SuGod ，mars3d 和 mars3d-cesium 这两个库代码没有sourceMap，无法定位问题

**Comment by SuGod** [comment]
> @SuGod ，mars3d 和 mars3d-cesium 这两个库代码没有sourceMap，无法定位问题

您好,更新了项目使用cesium+vuecli(webpack)的工程,麻烦您再看一下.

**Comment by SuGod** [comment]
@timhub66 今天测试了一下.发现vue-cli4/webpack4的工程可以正常加载.vite/webpack5工程都无法加载出地图.

**Comment by timhub66** [comment]
@SuGod ,cesium 这个已以feature形式 在 1.0.0-rc.9 版本支持；详细可参考  https://github.com/micro-zoe/awesome-samples/tree/issue-1351
