### ISSUE TITLE
父应用嵌套子应用，长时间页面停留后，切换子应用的菜单（路由）页面无反应，当前页面上的元素点击也无效，整个页面出于卡死状态

### ISSUE THREAD

**Issue by frenkiss-bobo** [jd-opensource/micro-app#1352]
## 问题描述
> 问题的具体描述

## 环境信息
- micro-app版本：v1.0.0-rc.2
- 主应用前端框架&版本：vue3.4.29
- 子应用前端框架&版本：vue3.4.29
- 构建工具&版本：vite

**Comment by Jennylx** [comment]
我也有遇到这个问题，控制台的Sources里面会有多个子应用
