### ISSUE TITLE
升级到v1.0.0-rc.6后的版本，wangEditor-next 富文本插件报错

### ISSUE THREAD

**Issue by liyangyangi** [jd-opensource/micro-app#1354]
可以用这个仓库的 基座项目和子应用项目复现
https://github.com/liyangyangi/micro-test1

**Comment by timhub66** [comment]
我这边跑起来正常，@liyangyangi  你那具体包什么错？报错浏览器及其版本也贴一下

**Comment by timhub66** [comment]
@liyangyangi ,今天刚发布 1.0.0-rc.9，升级一下试试

**Comment by hjn1028** [comment]
> @liyangyangi，今天刚发布 1.0.0-rc.9，升级一下试试

rc.9我更新了 还是会有报错，工具栏无法正常使用
![image](https://github.com/user-attachments/assets/4f317e45-39ad-4498-9979-bf3aca643458)

**Comment by timhub66** [comment]
> > @liyangyangi，今天刚发布 1.0.0-rc.9，升级一下试试
> 
> rc.9我更新了 还是会有报错，工具栏无法正常使用 ![image](https://private-user-images.githubusercontent.com/33085961/366277468-4f317e45-39ad-4498-9979-bf3aca643458.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwMzYxMDgsIm5iZiI6MTcyNjAzNTgwOCwicGF0aCI6Ii8zMzA4NTk2MS8zNjYyNzc0NjgtNGYzMTdlNDUtMzlhZC00NDk4LTk5NzktYmYzYWNhNjQzNDU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTExVDA2MjMyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQzODNjMzM3NGVmYmZjOWE3NDEyNTIzZmFmMjFjZDkzMjNmNmU1NjI4MTQ3YTM5MzQ4ODk3YTAxNWQwNzQ4ZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Tud8feuSSqgBmE2kQyHfGmdG8iDpmd7K2ilxcjMSRoI)

给一个demo，上面那个demo跑起来正常

**Comment by timhub66** [comment]
> > @liyangyangi，今天刚发布 1.0.0-rc.9，升级一下试试
> 
> rc.9我更新了 还是会有报错，工具栏无法正常使用 ![image](https://private-user-images.githubusercontent.com/33085961/366277468-4f317e45-39ad-4498-9979-bf3aca643458.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwMzYxMDgsIm5iZiI6MTcyNjAzNTgwOCwicGF0aCI6Ii8zMzA4NTk2MS8zNjYyNzc0NjgtNGYzMTdlNDUtMzlhZC00NDk4LTk5NzktYmYzYWNhNjQzNDU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTExVDA2MjMyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQzODNjMzM3NGVmYmZjOWE3NDEyNTIzZmFmMjFjZDkzMjNmNmU1NjI4MTQ3YTM5MzQ4ODk3YTAxNWQwNzQ4ZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Tud8feuSSqgBmE2kQyHfGmdG8iDpmd7K2ilxcjMSRoI)

@hjn1028 ，复现demo给一下

**Comment by liyangyangi** [comment]
> 我这边跑起来正常，@liyangyangi 你那具体包什么错？报错浏览器及其版本也贴一下

![1726197403706](https://github.com/user-attachments/assets/2168d858-026f-4352-894f-de3a4bb1e5e2)
升级后还是这样 浏览器chrome 128.0.6613.120 版本

**Comment by liyangyangi** [comment]
> 我这边跑起来正常，@liyangyangi 你那具体包什么错？报错浏览器及其版本也贴一下

跑起来后 基座访问这个地址  http://localhost:5273/a/demo1/home

**Comment by liyangyangi** [comment]
降到 v1.0.0-rc.5 版本是没问题的

**Comment by timhub66** [comment]
v1.0.0-rc.11 已修复
