### ISSUE TITLE
microApp.setData多次只会拿到一个type数据，为什么旧数据还合并过来啊

### ISSUE THREAD

**Issue by xian107** [jd-opensource/micro-app#1356]
hooks1：useEffect(() => { microApp.setData(name, {path:xxx} }, [location.pathname]);
hooks2：useEffect(() => { microApp.setData(name, {tabArrs:xxx} }, [tabArrs]);
hooks1执行后，hooks2执行了后倒置监听到的数据包含hooks1的path，把数据合并了，我在子应用无法知道哪些数据有更新。

改成：
hooks1：useEffect(() => { microApp.setData(name, {type:'path',payload:xxx} }, [location.pathname]);
hooks2：useEffect(() => { microApp.setData(name, {type:'tabArrs',,payload:xxx} }, [tabArrs]);
两个一起变化的时候，我在子应用只能拿到后面执行的type

请问我在子应用要怎么才能addDataListener到最新变化的值？不要之前的旧值

下面这种方法也不行，因为不确定hooks1和hooks2哪个先。都是用useEffect监听的，不在同一个组件里
microApp.setData('my-app', {city: 'HK'}, (res: any[]) => {
        microApp.setData('my-app')
})

**Comment by wiskewu** [comment]
在[官方文档](https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/data)中有提到，micro-app会遍历新旧值中的每个key判断值是否有变化，如果所有数据都相同则不会发送（注意：只会遍历第一层key），如果数据有变化则将**新旧值进行合并**后发送。
![image](https://github.com/user-attachments/assets/65d159bf-418b-4f5e-86fe-f44688354f3f)
