### ISSUE TITLE
micro-app 使用多层嵌套如下:  A 嵌套 B  B嵌套(C 或者 D 或者E)  由于官网通过指定tagName的形式指定子应用  由于全局只能start一次这样导致tagName只能指定一个,那么我想嵌套其他的应用怎么办

### ISSUE THREAD

**Issue by luomuniangniang** [jd-opensource/micro-app#1357]
micro-app 使用多层嵌套如下:  A 嵌套 B  B嵌套(C 或者 D 或者E)  
B的代码如下 
microApp.start({
  tagName: 'micro-app-C' 
})
microApp.setData('C', { msg:"我是B应用,我给C或者D或者E的孙子传的值5555555555555" }) 

<micro-app-C name='C' :url='url' iframe></micro-app-C> 
这时候我动态切换其他子应用是D  由于全局只能一次start  那么我怎么才能修改tageName为micro-app-D
然后像这样 <micro-app-D name='D' :url='url' iframe></micro-app-D> 使用

上述问题是由于  如果只改变name 和 url 而不改变标签  导致被嵌入的 由C 变为 D应用,导致在D应用内通过
 window.microApp.getData();获取B给D传的数据获取时候是{} 获取不到值 想问下microapp 团队能否回答下谢谢

**Comment by loyliu** [comment]
我们也遇到了问题，能帮我们看一下吗

**Comment by luomuniangniang** [comment]
我们暂时的解决方式是, B应用声明 microApp.start({ tagName: "micro-app-C"})  使用时<micro-app-C:name="name" :url="url"></micro-app-C>  切换的时候动态修改 name 和url, 相当于标签一直是<micro-app-C>只换name 和url,   但是使用micro-app的样式还是存在污染的问题,看了官网说是默认开启样式隔离,但是还是会污染,不知谁能给说下这个情况

**Comment by luomuniangniang** [comment]
我们暂时的解决方式是, B应用声明 microApp.start({ tagName: "micro-app-C"})  使用时<micro-app-C:name="name" :url="url"></micro-app-C>  切换的时候动态修改 name 和url, 相当于标签一直是<micro-app-C>只换name 和url,   但是使用micro-app的样式还是存在污染的问题,看了官网说是默认开启样式隔离,但是还是会污染,不知谁能给说下这个情况
