### ISSUE TITLE
RC.9子应用a标签href属性丢失

### ISSUE THREAD

**Issue by garrettzxd** [jd-opensource/micro-app#1358]
![image](https://github.com/user-attachments/assets/dbc7b7d6-39cb-4d9a-b98a-b5fa21d54a63)

在更新到RC.9版本后，子应用所有的a标签href属性都丢失了

**Comment by timhub66** [comment]
能提供一个demo吗？

**Comment by lilu0826** [comment]
RC.9版本子应用a标签功能异常DEOM：https://github.com/lilu0826/micro-app-bug

测试demo文件：https://github.com/lilu0826/micro-app-bug/blob/main/sub-app/src/App.vue

启动主子应用打开即可

**Comment by timhub66** [comment]
@garrettzxd @lilu0826   rc.10 已修复
