### ISSUE TITLE
Vite子应用开启 iframe 沙箱，本地dev报 DOMException：Blocked a frame with origin "xxx" from accessing a cross-origin frame 等一些错误

### ISSUE THREAD

**Issue by LJiangA** [jd-opensource/micro-app#1360]
### 问题描述
Vite子应用开启了 `iframe` 沙箱，且在主应用head的第一个元素插入了`<script>if(window.parent !== window) {window.stop()}</script>`

### 复现步骤

1. Vite子应用开启了 iframe 属性：`<micro-app name="vite-sub-app" url="http://localhost:5173/" iframe></micro-app>`
2. 在主应用haed的第一个元素插入了：`<script>if(window.parent !== window) {window.stop()}</script>`
3. 打开子应用所在页面
4. micro-app元素下没有head和body元素（图2），并报如下图1的错误

### 上传截图

- 图1：
![image](https://github.com/user-attachments/assets/c53df607-5df9-41a7-9fe1-75f46b062d19)
- 图2：
![image](https://github.com/user-attachments/assets/2da7567e-c407-44fc-8ac5-0699f17810c9)

### 环境信息

- micro-app 版本："@micro-zoe/micro-app": "^1.0.0-rc.9"
- 主应用：Vue2+webpack
- 子应用：Vue3+Vite

**Comment by LJiangA** [comment]
发现问题原因了，是主应用设置了 document.domain 导致的，但参考 #736 中的评论说是在1.0.0-beta.1已经解决了。有点疑惑这里还出现了类似的问题...

**Comment by UltramanWeiLai** [comment]
我这边也出现了，而且是偶现，rc.5 的版本，也没发现主应用中有 document.domian 头疼
