### ISSUE TITLE
子应用采用cdn加载库文件，报错，库文件全局未定义，

### ISSUE THREAD

**Issue by shuixiaobin** [jd-opensource/micro-app#1362]
**Is your feature request related to a problem? Please describe.**
主应用: vue3+vite
子应用: vue3+vite

**Describe the solution you'd like**
![5dcc97fc5e394caddf5a25022cc66c1](https://github.com/user-attachments/assets/a5ea3306-b012-4118-9d6a-c5455e41dc19)
![86df91f02d4f8eca91cd3dbbaf13afb](https://github.com/user-attachments/assets/72398776-e9b6-4ea1-8c21-7cf39786027d)
![e48cf28ba0396b377f7fdc7cc77218b](https://github.com/user-attachments/assets/2523f40d-24d6-4617-986e-f6341d93757f)

**Describe alternatives you've considered**

**Additional context**
请问怎么解决呢，子应用要改成npm包的形式引用是可以的，如果不改子应用主应用要怎么改下可以适配这种场景？多谢

**Comment by timhub66** [comment]
@shuixiaobin ， 参照  https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/sandbox?id=%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98

**Comment by shuixiaobin** [comment]
https://gitee.com/shuixiaobin/micro-app-demo.git 

> Hello @shuixiaobin. In order to facilitate location and troubleshooting, we need you to provide a realistic GitHub repository. 您好 @shuixiaobin, 为了方便定位和排查问题，我们需要您提供一个重现实例，请提供一个尽可能精简的 GitHub 仓库地址。

**Comment by shuixiaobin** [comment]
> Hello @shuixiaobin. In order to facilitate location and troubleshooting, we need you to provide a realistic GitHub repository. 您好 @shuixiaobin, 为了方便定位和排查问题，我们需要您提供一个重现实例，请提供一个尽可能精简的 GitHub 仓库地址。

仓库地址已补充，主应用子应用都在一个里面，多谢；https://gitee.com/shuixiaobin/micro-app-demo.git

**Comment by timhub66** [comment]
> > Hello @shuixiaobin. In order to facilitate location and troubleshooting, we need you to provide a realistic GitHub repository. 您好 @shuixiaobin, 为了方便定位和排查问题，我们需要您提供一个重现实例，请提供一个尽可能精简的 GitHub 仓库地址。
> 
> 仓库地址已补充，主应用子应用都在一个里面，多谢；https://gitee.com/shuixiaobin/micro-app-demo.git

@shuixiaobin  基座启动的时候，加一下 几个未定义变量的替换就行了
```js
microApp.start({
    plugins: {
        modules: {
            "my-app": [{
                loader(code, url) {
                    // 按实际情况 加js文件判断
                    // VUE 
                    code = code.replace('var Vue', 'window.Vue')
                    // VUE-ROUTER
                    code = code.replace('var VueRouter', 'window.VueRouter')
                    // ElementPlusIconsVue
                    code = code.replace('var ElementPlusIconsVue', 'window.ElementPlusIconsVue')
                    return code
                }
            }]
        }
    }
})
```
