### ISSUE TITLE
Vue2主应用接入 Vite子应用后，正常加载了，但刷新出现 TypeError: Cannot read properties of null (reading 'instanceMap') 报错

### ISSUE THREAD

**Issue by LJiangA** [jd-opensource/micro-app#1365]
### 问题描述

> 问题的具体描述

### 复现步骤

1. 新建一个 vue2 项目，当作主应用
2. 新建一个 vue3 + vite 项目，当作子应用
3. 在 vue2 中引入 vite 子应用，添加 viteView 页面

views/viteView.vue 文件代码
```vue
<template>
  <div>
    <h1>vite-sub-app</h1>
    <micro-app name="vite-sub-app" url="http://localhost:5173/" iframe></micro-app>
  </div>
</template>
```
App.vue 文件代码
```vue
<template>
  <div id="app">
    <nav>
      <router-link to="/">Home</router-link> |
      <router-link to="/about">About</router-link> |
      <router-link to="/vite">Vite</router-link>
    </nav>
    <router-view/>
  </div>
</template>
```
4. 点击Vite，正常加载了vite子应用，再点击vite子应用内的 About 按钮，也正常显示了（图1）
5. 刷新页面，就出现了下方截图的报错信息（图2），此时页面也显示正常

### 上传截图

> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。

- 图1

![image](https://github.com/user-attachments/assets/79de86c4-b696-4682-9ba9-950a288fe987)

- 图2

![image](https://github.com/user-attachments/assets/ce82b430-60ee-47d4-b921-8cd23efffd9c)

### 复现仓库

> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。

### 环境信息

- micro-app 版本："@micro-zoe/micro-app": "^1.0.0-rc.9"
- 主应用前端框架&版本：Vue2+webpack
```json
{
  "name": "vue2-sub-app",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build"
  },
  "dependencies": {
    "@micro-zoe/micro-app": "^1.0.0-rc.9",
    "core-js": "^3.8.3",
    "vue": "^2.6.14",
    "vue-router": "^3.5.1",
    "vuex": "^3.6.2"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "~5.0.0",
    "@vue/cli-plugin-router": "~5.0.0",
    "@vue/cli-plugin-vuex": "~5.0.0",
    "@vue/cli-service": "~5.0.0",
    "vue-template-compiler": "^2.6.14"
  }
}
```
- 子应用前端框架&版本：Vue3+Vite
```json
{
  "name": "vite-sub-app",
  "version": "0.0.0",
  "private": true,
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview"
  },
  "dependencies": {
    "vue": "^3.4.29",
    "vue-router": "^4.3.3"
  },
  "devDependencies": {
    "@vitejs/plugin-vue": "^5.0.5",
    "vite": "^5.3.1"
  }
}

```

**Comment by lmd3385** [comment]
这个问题，坑我2天才排查出来，是因为升级到1.0.0-rc.9导致，使用1.0.0-rc.8版本没问题。

**Comment by LJiangA** [comment]
感谢大佬 @lmd3385 解惑，这个是因为升级到 1.0.0-rc.9 导致的，使用 1.0.0-rc.8 版本没这个问题。
@bailicangdu  大佬看看这个问题呢？

**Comment by timhub66** [comment]
@LJiangA , 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。

**Comment by LJiangA** [comment]
> @LJiangA , 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。

@timhub66  不是必现的，在1.0.0-rc.8 也碰到过，就是子应用内路由跳转后刷新页面，有时出现一堆这个报错，报错文件是hooks.ts。我后续弄个代码仓库上来。

**Comment by LJiangA** [comment]
最近没碰到过，不是必现的，先关了这个issue
