### ISSUE TITLE
vue3.5中自定义元素defineCustomElement在子应用中报错

### ISSUE THREAD

**Issue by an501920078** [jd-opensource/micro-app#1367]
## 问题描述
> 子应用中的自定义元素由vue的defineCustomElement构建，在升级vue版本到3.5后子应用无法加载自定义元素，报错Uncaught TypeError: Illegal invocation
排查后发现是由于vue3.5+中_applyStyles这个方法重构了，将原先的this.shadowRoot.appendChild更换为了this.shadowRoot.prepend导致micro-app劫持报错。
后续发现复现是需要在自定义元素中引入子组件编写style标签稳定复现，在复现仓库地址中已经给出复现。

## 复现步骤
1.在子应用中使用vue3.5+版本构建的自定义元素
2.自定义元素再引用.ce.vue结尾组件，子组件内包含style样式
3.出现报错

## 上传截图
> 报错位置
![A3DA74D2-A913-406c-B688-DEA5B483E7B5](https://github.com/user-attachments/assets/59e08826-9e8e-49da-9bac-98cf2558664e)
报错说明
![AB962408-1864-4f4b-BCF9-3AFD8C23B988](https://github.com/user-attachments/assets/d6fbe90e-cdb5-4e6d-8cc5-af6bc0a65c6b)
vue3.5+版本与之前的对比
![EBFE55CC-D496-458a-9F2A-D6A0AB22C211](https://github.com/user-attachments/assets/c6f68f45-b1e7-43e7-a4c7-6185f343a843)
![29617E8D-45B7-4f6f-B724-0EE6898E5B09](https://github.com/user-attachments/assets/48b444c9-a7df-4742-9d5a-148a5f19eb7b)

## 复现仓库
> https://github.com/an501920078/microapp-test-demo

## 环境信息
- micro-app版本："1.0.0-rc.8"
- 主应用前端框架&版本："vite:"^5.4.4"
- 子应用前端框架&版本：vite:"^5.4.4"
- 构建工具&版本：vite:"^5.4.4"

**Comment by an501920078** [comment]
@timhub66 已添加复现仓库

**Comment by timhub66** [comment]
> @timhub66 已添加复现仓库

v1.0.0-rc.11 已修复

**Comment by jiaoguanwen** [comment]
请问问题解决了吗

**Comment by jiaoguanwen** [comment]
> > [@timhub66](https://github.com/timhub66) 已添加复现仓库
> 
> v1.0.0-rc.11 已修复

你好，我遇到同样的问题，升级到10，12，22仍存在问题

**Comment by zhanzekun** [comment]
> > [@timhub66](https://github.com/timhub66) 已添加复现仓库
> 
> v1.0.0-rc.11 已修复

大佬，这里相关修复commit是哪个？ 好像没看到贴出来
