### ISSUE TITLE
最新版RC.10中，new Worker 不传第二个参数报错

### ISSUE THREAD

**Issue by lilu0826** [jd-opensource/micro-app#1368]
## 问题描述
> 最新版RC.10中，new Worker 不传第二个参数报错

## 复现步骤
1.用new Worker 创建webworker
2.控制台报错

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。
![image](https://github.com/user-attachments/assets/99511f34-b228-4261-8dab-cf1bde7f9ff7)
![image](https://github.com/user-attachments/assets/b459fd07-70bd-4a94-b574-7920d6797309)

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。

## 环境信息
- micro-app版本：1.0.0-rc.10
- 主应用前端框架&版本：
- 子应用前端框架&版本：
- 构建工具&版本：

**Comment by duangs** [comment]
就因为这个proxy，导致其他包调Worker报错
回退到1.0.0-rc.8就不会有这个问题

**Comment by timhub66** [comment]
> 就因为这个proxy，导致其他包调Worker报错 回退到1.0.0-rc.8就不会有这个问题

好，下一个版本修复

**Comment by timhub66** [comment]
v1.0.0-rc.11 已修复
