### ISSUE TITLE
在子应用中css -webkit-background-clip 的私有前缀 -webkit 被移除了 导致在chrome中对应的样式失效

### ISSUE THREAD

**Issue by HenryZhu-1988** [jd-opensource/micro-app#137]
## 问题描述
> 
在子应用中css -webkit-background-clip 的私有前缀 -webkit 被移除了 导致在chrome中对应的样式失效

## 作为子应用
![image](https://user-images.githubusercontent.com/43346131/139796675-2b32f44a-7799-4600-b374-6d059677bf58.png)

## 作为独立应用
![image](https://user-images.githubusercontent.com/43346131/139796840-a1462f29-9ade-4013-9379-d5503bb07533.png)

## 环境信息
- micro-app版本："@micro-zoe/micro-app": "^0.4.0",
- 主应用前端框架&版本：react "umi": "^3.5.20"
- 子应用前端框架&版本：react v15
- 构建工具&版本：    "webpack": "3.12.0"

**Comment by bailicangdu** [comment]
建议先通过style设置规避这个问题

**Comment by HenryZhu-1988** [comment]
> 建议先通过style设置规避这个问题
这里说的style 设置是禁用样式隔离的嘛？

**Comment by bailicangdu** [comment]
元素的style属性，<div style='-webkit-background-clip: text;'></div>

**Comment by bailicangdu** [comment]
```html
<div style='-webkit-background-clip: text;'>3333</div>
```

**Comment by HenryZhu-1988** [comment]
> ```
> <div style='-webkit-background-clip: text;'>3333</div>
> ```

这个也是一个解决的方法，谢谢！
但是就是需要对子应用做修改
