### ISSUE TITLE
子应用控制台报错：Cannot read properties of null (reading 'emitsOptions')

### ISSUE THREAD

**Issue by dengjunxx** [jd-opensource/micro-app#1372]
**问题描述**
点击主应用菜单，第一次跳转到子应用时，偶尔控制台会报这个错误，感觉还是子应用资源加载异常的问题，请问需要如何解决呢？

**报错信息**
![image](https://github.com/user-attachments/assets/e31d0c05-e858-4ed0-9574-cbcf6239b9f5)

**Comment by dengjunxx** [comment]
我现在配置了子应用预加载，本地启动主应用和子应用都没事，但是部署到线上之后，控制台就会反复报这个错误，请问是怎么回事？
代码仓库：
主应用：https://gitee.com/dengjunxx/micro-app_main_demo
子应用：https://gitee.com/dengjunxx/micro-app_child_vite-vue3_demo
@timhub66

**Comment by dengjunxx** [comment]
![image](https://github.com/user-attachments/assets/73f12dc0-091c-4ec5-8257-76f56a93d7a7)
在login页，还没进入系统之前，控制台会反复报这个错误，感觉是不是资源加载的问题，如果把预加载去掉就不会报这些错误，请问要如何解决呢？
@timhub66

**Comment by taomas** [comment]
同样首次进入子应用会报这个错误，这个问题有什么办法解决吗。
