### ISSUE TITLE
最新版本v1.0.0-rc.9，子应用无法通过location.search，获取micro-app标签url的查询参数

### ISSUE THREAD

**Issue by tmxjiayou** [jd-opensource/micro-app#1377]
## 问题描述
> 最新版本v1.0.0-rc.9，子应用无法通过location.search，获取micro-app标签url的查询参数

## 复现步骤
1. 在父应用中通过micro-app接入子应用， 并配置router-mode="pure"，在子应用里通过$router.push路由跳转并带上query参数
2.在子应用中无法通过子应用无法通过location.search，获取query参数，子应用里拿到的location好像是外层主应用

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。

## 环境信息
- micro-app版本：v1.0.0-rc.9
- 主应用前端框架&版本：vue2.6
- 子应用前端框架&版本：vue2.6
- 构建工具&版本：webpack5

**Comment by tmxjiayou** [comment]
v1.0.0-rc.5版本是正常的，后面的版本在子应用里获取的location都是父应用的

**Comment by htfire** [comment]
> v1.0.0-rc.5版本是正常的，后面的版本在子应用里获取的location都是父应用的

我 v1.0.0-rc.5版本怎么获取的也是父应用的

**Comment by raoenhui** [comment]
window.rawWindow试试
