### ISSUE TITLE
页面离开然后再次进入有离开前的动作

### ISSUE THREAD

**Issue by hzfvictory** [jd-opensource/micro-app#138]
## 问题描述

> 用的是 0.4.1 新提供的 内存优化，在入口处
```
let app = null;

function mount() {
  app = new Vue({
    router,
    store,
    render: h => h(App)
  }).$mount("#app");
}

function unmount() {
  app.$destroy();
  app = null;
}

// 微前端环境下，注册mount和unmount方法
if (window.__MICRO_APP_ENVIRONMENT__) {
  window[`micro-app-${window.__MICRO_APP_NAME__}`] = { mount, unmount };
} else {
  // 非微前端环境直接渲染
  mount();
}
```
导致页面离开 再次返回 离开前的动作还有保留,不使用内存优化是没事的

## 上传截图

![](https://tva1.sinaimg.cn/large/008i3skNly1gw0vv8i7cbg30xi0m2avh.gif)

## 环境信息
- micro-app版本：0.4.1
- 主应用前端框架&版本：vue2
- 子应用前端框架&版本：vue2
- 构建工具&版本：webpack

**Comment by bailicangdu** [comment]
可以在umount函数中增加删除元素的操作
```js
function unmount() {
  app.$destroy();
  app.$el.innerHTML = '';
  app = null;
}
```

**Comment by hzfvictory** [comment]
> 可以在umount函数中增加删除元素的操作
> 
> ```js
> function unmount() {
>   app.$destroy();
>   app.$el.innerHTML = '';
>   app = null;
> }
> ```

这个试过了 无济于事，还是那样的

**Comment by bailicangdu** [comment]
那就只能在unmount函数中手动使用组件的 close方法关闭了

**Comment by hzfvictory** [comment]
> 那就只能在unmount函数中手动使用组件的 close方法关闭了

这个bug不仅仅是弹框 所有加在子应用body上的都会出现这个问题，很多都没有 close 方法;  出现这个问题的原因是内部做了缓存处理吗

**Comment by bailicangdu** [comment]
缓存是必须的，否则二次渲染一些库无法正常运行

**Comment by hzfvictory** [comment]
> 缓存是必须的，否则二次渲染一些库无法正常运行
```
window[`micro-app-${window.__MICRO_APP_NAME__}`] = { mount, unmount };
```
我不使用这种是正常的，我看页面也是有缓存的，但是不会出现上面说的那个问题，这俩内部实现有什么区别啊。

**Comment by bailicangdu** [comment]
正常情况下二次渲染会重新执行所有js，流程和第一次一致。设置mount unmount后，二次渲染只会重新执行这两个方法

**Comment by lijiweigh** [comment]
这个问题解决了吗
