### ISSUE TITLE
[micro-app from runScript] app sub-app:  TypeError: Cannot set properties of undefined (setting 'type')

### ISSUE THREAD

**Issue by xian107** [jd-opensource/micro-app#1385]
## 问题描述
TypeError: Cannot set properties of undefined (setting 'type')

使用这些方法不起作用
![image](https://github.com/user-attachments/assets/1dc5075d-befa-43a0-a5b0-3a1a706f8a52)

## 上传截图
![image](https://github.com/user-attachments/assets/c858b1fd-30e0-4469-9820-74934df0bce8)

## 复现仓库
> [请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。](https://github.com/xian107/dome)

## 环境信息
- micro-app版本：^1.0.0-rc.10
- 主应用前端框架&版本： react  ^18.3.1
- 子应用前端框架&版本：react  ^18.3.1
- 构建工具&版本：webpack

**Comment by Ortonzhang** [comment]
woker没有传递第二个参数的问题 回退到rc.8就好了
参见https://github.com/micro-zoe/micro-app/issues/1368

**Comment by timhub66** [comment]
v1.0.0-rc.11 已修复
