### ISSUE TITLE
Vite+vue3 百度地图动态script加载模式，使用了 #1009 提供的插件后，地图能加载出来，但是图片跨域

### ISSUE THREAD

**Issue by WangEbo** [jd-opensource/micro-app#1388]
## 问题描述
> Vite+vue3 百度地图动态script加载模式，使用了 #1009 提供的插件后，地图能加载出来，但是图片跨域

## 复现步骤
1. 使用动态引入script的方式加载地图，在主应用中配置了 
    ` microApp.start({
          plugins: {
            modules: {
              'appName': [microPluginMap],
            }
          }
    })
2. 主应用能加载js/css，但无法正常加载动态创建dom里的 img，我尝试了使用 excludeAssetFilter 这个api，但似乎只能拦截到 script / link 资源，图片资源不被拦截

## 上传截图
> 
![image](https://github.com/user-attachments/assets/6fe628f2-f5af-4c39-83a7-4388e585eb26)

子应用加载地图正常，两个均为线上环境
![image](https://github.com/user-attachments/assets/691b2772-fbde-4a31-ab95-6e5e0056be35)

## 复现仓库
> 暂时无法提供

## 环境信息
- micro-app版本：1.0.0-rc.6
- 主应用前端框架&版本：vite 4.5 vue3
- 子应用前端框架&版本：vite 4.5 vue3
- 构建工具&版本：vite 4.5 vue3

**Comment by WangEbo** [comment]
> Hello @WangEbo. In order to facilitate location and troubleshooting, we need you to provide a realistic GitHub repository. 您好 @WangEbo, 为了方便定位和排查问题，我们需要您提供一个重现实例，请提供一个尽可能精简的 GitHub 仓库地址。

非常抱歉，我现在没有办法提供最小化的仓库，但是我发现，主应用中无法加载的地图图片被加上了  crossorigin="anonymous" 这个熟悉，子应用中正常的是没有这个属性的，我手动删除这个属性后图片也能正常加载

**Comment by VincientBlue** [comment]
@WangEbo 我最近也碰到了同样的问题，子应用使用了img标签去引用外部图片资源，但是微前端环境中图片被加上crossorigin="anonymous"属性 就会因为跨域没办法加载，想知道这个问题您解决了吗

**Comment by timhub66** [comment]
> @WangEbo 我最近也碰到了同样的问题，子应用使用了img标签去引用外部图片资源，但是微前端环境中图片被加上crossorigin="anonymous"属性 就会因为跨域没办法加载，想知道这个问题您解决了吗

你那有demo吗？

**Comment by VincientBlue** [comment]
> > @WangEbo 我最近也碰到了同样的问题，子应用使用了img标签去引用外部图片资源，但是微前端环境中图片被加上crossorigin="anonymous"属性 就会因为跨域没办法加载，想知道这个问题您解决了吗
> 
> 你那有demo吗？

#1391 没有demo诶，和这个是一样的
