### ISSUE TITLE
跨应用路由切换，报错

### ISSUE THREAD

**Issue by HenryZhu-1988** [jd-opensource/micro-app#139]
## 问题描述
> 子应用App1要跳转到另外一个子应用App2，App1 跳转 App2 没有问题，但是再点击左侧菜单跳转到 App1 时，就报错了

## 复现步骤
1.基座应用
![image](https://user-images.githubusercontent.com/43346131/140035708-d9441d41-06c7-4f14-be1d-dd8fb7653b45.png)

2.子应用 App1
![image](https://user-images.githubusercontent.com/43346131/140035969-f809775b-7b58-43e8-b5c2-fed25c5cdc10.png)
3. App1 跳转 App2 没有问题，但是再点击左侧菜单跳转到 App1 时，就报错了
![image](https://user-images.githubusercontent.com/43346131/140036620-b3325eb2-6d6b-4172-92b8-c0879d923270.png)

## 环境信息
- micro-app版本："@micro-zoe/micro-app": "^0.4.0",
- 主应用前端框架&版本：react "umi": "^3.5.20"
- 子应用前端框架&版本：react v15
- 构建工具&版本： "webpack": "3.12.0"

**Comment by HenryZhu-1988** [comment]
![image](https://user-images.githubusercontent.com/43346131/140039201-06eed44e-2e37-40fe-abe7-3677011eb39f.png)

**Comment by HenryZhu-1988** [comment]
使用 https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/route?id=%e5%ba%94%e7%94%a8%e4%b9%8b%e9%97%b4%e8%b7%b3%e8%bd%ac 上提供的方案 同样报错

**Comment by bailicangdu** [comment]
更新到最新版试一下？

**Comment by HenryZhu-1988** [comment]
> 更新到最新版试一下？

已经更新到 0.4.2 了
还是不行

但是 根据以往的经验添加了 setTimeout 暂时解决了这个问题
![image](https://user-images.githubusercontent.com/43346131/140045719-dd4d2f3f-6823-41e4-88f5-75ded588ce58.png)

**Comment by HenryZhu-1988** [comment]
再过几天 ，看一下micro-app 的源码，我也该做点贡献了
