### ISSUE TITLE
子应用图片加载不出来，img标签src是外部图片，作为子应用的时候img标签被添加了crossorigin="anonymous"属性

### ISSUE THREAD

**Issue by L-Z-Y** [jd-opensource/micro-app#1391]
## 问题描述
> 问题的具体描述
    CDN地址并没有设置跨域设置，单独运行的时候没问题，作为子应用的时候img标签会被添加crossorigin="anonymous"，造成加载的外部图片资源失败。
    看了一下沙箱的代码这块是特意处理的，为什么要这么弄，可否去掉
## 复现步骤
1.
2.

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。
<img width="641" alt="iShot_2024-09-26_18 12 59" src="https://github.com/user-attachments/assets/00f176b5-ea1a-4fe0-833d-fc79f3921dd8">
![iShot_2024-09-26_18 19 52](https://github.com/user-attachments/assets/b73b8181-c1aa-491c-ad59-1a2459531244)

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。

## 环境信息
- micro-app版本：1.0.0-rc.10
- 主应用前端框架&版本：vite+ vue3
- 子应用前端框架&版本：vite+vue3
- 构建工具&版本：vite

**Comment by L-Z-Y** [comment]
![iShot_2024-09-26_18 19 52](https://github.com/user-attachments/assets/e2e9d842-a37b-45a7-83b0-be9ac8ffeb5f)

**Comment by lilu0826** [comment]
同样的问题，在rc.9版本里面将img、audio、video元素统一设置了crossorigin=”[anonymous](https://developer.mozilla.org/zh-CN/docs/Web/HTML/Attributes/crossorigin#anonymous)“

不知是出于什么考虑，要写死这个属性

**Comment by L-Z-Y** [comment]
> 同样的问题，在rc.9版本里面将img、audio、video元素统一设置了crossorigin=”[anonymous](https://developer.mozilla.org/zh-CN/docs/Web/HTML/Attributes/crossorigin#anonymous)“
> 
> 不知是出于什么考虑，要写死这个属性

确实，我没注意版本，rc.9添加的，我先回退到rc.8，要不进行不下去了，感谢

**Comment by timhub66** [comment]
@L-Z-Y @lilu0826 ，提供一个demo，便于快速修复

**Comment by timhub66** [comment]
@L-Z-Y @lilu0826 ，升级到 v1.0.0-rc.11 试试

**Comment by L-Z-Y** [comment]
> @L-Z-Y @lilu0826 ，升级到 v1.0.0-rc.11 试试

我升级了还是不行
https://github.com/L-Z-Y/micro-app-issue-demo
这是demo地址
with 模式下我的项目加载不出来，改用了iframe模式加载子应用，图片加载不出来，子应用的home下我添加了图片地址
/children/vite4/src/pages/home.vue

**Comment by timhub66** [comment]
> > @L-Z-Y @lilu0826 ，升级到 v1.0.0-rc.11 试试
> 
> 我升级了还是不行 https://github.com/L-Z-Y/micro-app-issue-demo 这是demo地址 with 模式下我的项目加载不出来，改用了iframe模式加载子应用，图片加载不出来，子应用的home下我添加了图片地址 /children/vite4/src/pages/home.vue

升级到 v1.0.0-rc.12，另外你这个demo需要调整一下主应用的端口，别和子应用共用5181，最后调整一下 url 即可 ，vite 改成 vite4 （`<micro-app name="vite" url="http://localhost:5181/micro-app/vite4/" iframe>`）

**Comment by timhub66** [comment]
> > @L-Z-Y @lilu0826 ，升级到 v1.0.0-rc.11 试试
> 
> 我升级了还是不行 https://github.com/L-Z-Y/micro-app-issue-demo 这是demo地址 with 模式下我的项目加载不出来，改用了iframe模式加载子应用，图片加载不出来，子应用的home下我添加了图片地址 /children/vite4/src/pages/home.vue

@L-Z-Y 升级到 v1.0.0-rc.12，另外你这个demo需要调整一下主应用的端口，别和子应用共用5181，最后调整一下 url 即可 （vite 改成 vite4 ，`<micro-app name="vite" url="http://localhost:5181/micro-app/vite4/" iframe>`）

**Comment by L-Z-Y** [comment]
> > > @L-Z-Y @lilu0826 ，升级到 v1.0.0-rc.11 试试
> > 
> > 
> > 我升级了还是不行 https://github.com/L-Z-Y/micro-app-issue-demo 这是demo地址 with 模式下我的项目加载不出来，改用了iframe模式加载子应用，图片加载不出来，子应用的home下我添加了图片地址 /children/vite4/src/pages/home.vue
> 
> @L-Z-Y 升级到 v1.0.0-rc.12，另外你这个demo需要调整一下主应用的端口，别和子应用共用5181，最后调整一下 url 即可 （vite 改成 vite4 ，`<micro-app name="vite" url="http://localhost:5181/micro-app/vite4/" iframe>`）

升级到v1.0.0-rc.12可以了，另外我想问一下，vite只能用iframe模式吗？
