### ISSUE TITLE
业务使用场景

### ISSUE THREAD

**Issue by BinZhiZhu** [jd-opensource/micro-app#14]
我是一名后端开发，也略知一些前端技术，看到这个觉得挺有趣的，但是我想请教一下各位大佬，微前端的概念或者说咋们当前这个micro-app的设计，在业务上有什么使用场景，或者说能否更好的帮助业务实现？如果能有一些通俗易懂或者比较具象的例子就更好了。

**Comment by bailicangdu** [comment]
微前端的概念类似于后端的微服务，将多个应用合并成一个大应用，每个应用可以独立开发、部署和运行，也可以理解为将一个庞大的应用进行拆分成小应用，每个负责的团队独立开发互相不影响，最终聚合为一个应用。

**Comment by loo41** [comment]
这个除了一般的大型前端项目，好像没有啥用的到的地方，大公司用的比较多一些。
- 优点
  - 拆分代码，避免形成巨石代码
  - 拆分项目，可以多团队同时开发
  - 抹平技术栈
  - 接入方便
  - ...
- 缺点
  - 部署麻烦
  - 有沟通，维护成本（项目和项目之间）
  - ...

**Comment by rxliuli** [comment]
> 这个除了一般的大型前端项目，好像没有啥用的到的地方，大公司用的比较多一些。
> 
> * 优点
>   
>   * 拆分代码，避免形成巨石代码
>   * 拆分项目，可以多团队同时开发
>   * 抹平技术栈
>   * 接入方便
>   * ...
> * 缺点
>   
>   * 部署麻烦
>   * 有沟通，维护成本（项目和项目之间）
>   * ...

补充一些缺点

- 兼容性和易用性无法媲美 iframe，主要是无法仅仅通过 url 加载子应用，而且隔离之类的也容易出错（吾辈在今天尝试 micro-app 时就出现了 `<micro-app>` 标签上没有添加 name 属性进而导致 css 失效）
- 目前微前端的生态很糟，或者说，由于前端生态的快速发展，几乎没有什么新技术栈能与所有工具链兼容（例如 vite 就是一个例子，官网上说兼容很麻烦，会损失很多功能）
- 某些场景无法解决，例如传统的前后端不分离的项目，无法从构建工具层面解决，所以还是不得不使用 iframe

吾辈的使用场景是在 Web 上构建一个简单的主应用作为“操作系统”，支持使用一些“子应用”，有点类似于飞书的那些子应用，但不太清楚他们的技术栈。

下面是一些个人感想

令人厌恶的为了解决问题而引入了更多复杂性，前端各种配置的繁杂让我想到了之前曾经看过一本科幻小说的一段话：“平心而论，我也不太喜欢这种多少显得有些自欺欺人的数学方式，甚至比你更甚。我越加思考这种该死的加加减减的数学技巧在物理方面的意义就越加的觉得厌恶。不过在经过重整化后的精度高到令人瞠目结舌，这让人完全没有办法回避它的存在。我们都不知道为什么，在进一步完成物理统合前，现有的物理告诉我们自然就是这种奇怪的东西。也许弦理论有希望吧，不过那个就不在我们谈论的范围里了。而且我不得不劝你一句，就算是以后，除非实在没有办法，不要随便去接触弦论，那东西就连你的老师也看了头大……”。
