### ISSUE TITLE
公司内部比较旧的 next.js 作为子应用产生的问题

### ISSUE THREAD

**Issue by chenxtdo** [jd-opensource/micro-app#140]
## 问题描述
> 问题的具体描述

公司内部比较旧的 next.js 作为子应用产生问题，发现 micro-app 对子应用的 getElementById 做了处理，使用 querySelector ，兼容性没做好，id 中带 / 也是不行的。
参照下面截图

## 上传截图

<img width="953" alt="image" src="https://user-images.githubusercontent.com/9393714/140053039-056dfd53-17f3-4d0d-8cc4-88f15762e2f4.png">

<img width="755" alt="image" src="https://user-images.githubusercontent.com/9393714/140052798-00752dbb-9cea-4e2f-9a65-c3eb14f6e0cf.png">

micro-app src/source/pathc.ts 里的代码
<img width="505" alt="image" src="https://user-images.githubusercontent.com/9393714/140052884-6fb689bc-6a2a-47e1-9055-abd6ae96a5ab.png">

## 环境信息
- micro-app版本：0.4.1
- 主应用前端框架&版本：react
- 子应用前端框架&版本：旧版 next.js
- 构建工具&版本：webpack

**Comment by bailicangdu** [comment]
此时建议通过  (0, eval)('window.document').getElementById 查询元素

**Comment by bailicangdu** [comment]
下个版本会进行修复

**Comment by bailicangdu** [comment]
问题已修复，https://github.com/micro-zoe/micro-app/releases/tag/v0.4.3
