### ISSUE TITLE
沙箱模式下第三方依赖（echarts）需要用到主应用挂载在window上的方法出现问题。目前发现的是instanceof Array无法正确判定

### ISSUE THREAD

**Issue by qianfeii** [jd-opensource/micro-app#1400]
## 问题描述
使用echarts时无法正确判断series导致无法渲染报错。
主要问题出在沙箱模式下进行instanceof Array 无法判定到true的结果。导致报错。
需要想办法让 instanceof 比较到全局的array，或者覆盖instanceof  有什么办法。或者给覆盖的方法结果 加上个 Array.is()
当然 也不排除依赖内有没有其他需要用到主项目window内方法的 
```js
// 执行setOption后报错
chartInstance = echarts.init(chartRef.value);
chartInstance.setOption(props.options);
```
报错
![image](https://github.com/user-attachments/assets/f5d3d02f-f2d6-4142-a2c7-3328c77b40a5)

尝试过覆盖子项目  window.array。但是创建对象不能保证不使用 [] 都使用 new Array。没有成功
```
window.Array = window.rawWindow.Array;
```
## 复现步骤
创建子项目 简单实例化echarts。
主项目使用vue3 + vite，沙箱模式加载子项目。

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。
![image](https://github.com/user-attachments/assets/16a80b26-e167-4807-9e01-67f59e770a59)

会执行到micro-app 沙箱内的方法
![image](https://github.com/user-attachments/assets/8864d13f-2697-4e2f-befb-681fdf21c925)

## 环境信息
- micro-app版本：^1.0.0-rc.12
- 主应用前端框架&版本：vue 2.6.11 @vue/cli-service 4.5.19 webpack 4.47.0
- 子应用前端框架&版本：vue 3.4.29  echarts 5.5.1
- 构建工具&版本：vite 5.3.1

**Comment by qianfeii** [comment]
node_modules\@micro-zoe\micro-app\lib\index.esm.js  5700行修改如下可以解决问题
![image](https://github.com/user-attachments/assets/c7989fd0-44d1-40fc-ab72-4d7d60503f10)

**Comment by Agarics** [comment]
同样的问题+1

**Comment by 1169938246** [comment]
同样的问题 +1

**Comment by c-guozi** [comment]
上面 node_modules@micro-zoe\micro-app\lib\index.esm.js 5700行修改后 仍然没有解决问题 @qianfeii ，可以详细看一下全部修改后的样子吗

**Comment by 1169938246** [comment]
> 上面node_modules@micro-zoe\micro-app\lib\index.esm.js 5700行修改后仍然没有解决问题@qianfeii修改一下，可以详细看一下全部后面的样子吗

想暂时解决问题就把  微应用版本：1.0.0-rc.10  改成12以下的固定版本 先暂时使用吧，后续人家修复了再更新

**Comment by an501920078** [comment]
我也是，在rc.12版本中子系统使用obj[key] instanceof Array 始终返回为false,这个BUG很严重

**Comment by XiaoDan12202** [comment]
+1

**Comment by timhub66** [comment]
1.0.0-rc.13 已修复
