### ISSUE TITLE
频繁切换子应用，dom 数量持续增加，导致持续内存增长

### ISSUE THREAD

**Issue by 1742020289** [jd-opensource/micro-app#1406]
## 问题描述
> 问题的具体描述
频繁切换子应用的时候，dom 数量持续增加，内存持续增长
## 复现步骤
1.打开官方demo,使用vue3主应用
2.以vue 3 子应用 和 vue 2 子应用作为示例，为了让演示效果更加明显，分别在home.vue 中添加10000 个 dom,和5000个点击事件
![image](https://github.com/user-attachments/assets/02d1f067-9d1b-4a54-b8d1-b77c81dd6bbb)
3.反复在vue2子应用的home和vue3子应用的home 之间切换
![image](https://github.com/user-attachments/assets/02e051bb-dae0-4ac2-813b-827ad139e310)
4.结果：dom 和事件监听器没有被回收，内存占用很高
![image](https://github.com/user-attachments/assets/03474d2c-c288-4c43-a3ac-97e64afa5a5e)
![image](https://github.com/user-attachments/assets/a996f83a-88b6-4f51-b76d-a03c9e6dd9c0)

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。
1.初始dom数量和内存占用
![image](https://github.com/user-attachments/assets/85ee594c-5fb8-4c5d-9a8a-30d417a6bfa5)
![image](https://github.com/user-attachments/assets/17045120-ed99-424f-8571-01036ed9503d)

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。
复现仓库地址：https://github.com/1742020289/micro-app-demo.git

## 环境信息
与官方demo 一致

**Comment by czAlexZhan** [comment]
出现一样的问题，是否已经修复，版本rc6
