### ISSUE TITLE
vue3+vite 子应用微前端模式，百度地图加载不出来

### ISSUE THREAD

**Issue by txlwelling** [jd-opensource/micro-app#1408]
主应用和子应用都是，
子应用 index.html引入百度地图sdk
<script type="text/javascript" src="https://api.map.baidu.com/api?v=3.0&type=world&ak=xxx"></script>

const initMap = ()=> {
  map.value = new BMap.Map("map"); // 创建Map实例
  let point = new BMap.Point(116.404, 39.915); // 创建点坐标
  mapSearchService.value = new BMap.LocalSearch(map.value, {
    renderOptions: { map: map.value }
  });
  // map.enableScrollWheelZoom(true)
  map.value.centerAndZoom(point, 15); // 初始化地图,设置中心点坐标和地图级别
  // 添加缩放控件
  map.value.addControl(new BMap.NavigationControl());

}
![微信截图_20241015174348](https://github.com/user-attachments/assets/ca77a0a4-cd5b-4742-bb35-cce01028561b)

**Comment by txlwelling** [comment]
主应用和子应用都是vue3+vite

**Comment by woaini521** [comment]
子应用和主应用的widow不一致
