### ISSUE TITLE
microApp.addDataListener 不触发

### ISSUE THREAD

**Issue by mathYang1224** [jd-opensource/micro-app#1409]
## Describe the bug
> A clear and concise description of what the bug is.
microApp.addDataListener 不触发偶现, name 想同情况下 列表页跳详情页再跳回列表页不触发
## To Reproduce
// 主应用
// name 为变量
microApp.setData(name, data)
// 子应用
// 监听基座下发的数据变化
window.microApp.addDataListener((data) => {
  // 当基座下发跳转指令时进行跳转
  if (data.path) {
    router.push(data.path)
  }
})

## Environment
- micro-app version:  "@micro-zoe/micro-app": "v1.0.0-rc.5",
- framework of base app & version:
- framework of sub app & version:
- Build tools & version:

**Comment by mathYang1224** [comment]
有没有什么补偿方案，长期使用这个版本的微前端框架，最好不升级

**Comment by mathYang1224** [comment]
子应用跳转详情页，再在主应用点击到列表页就不触发

**Comment by mathYang1224** [comment]
子应用跳转详情页，再在主应用点击到列表页就不会跳转

**Comment by wiskewu** [comment]
#1356
