### ISSUE TITLE
加载子应用后运行报错 Module scripts don't support importScripts().

### ISSUE THREAD

**Issue by YaoJianqun** [jd-opensource/micro-app#1410]
## 问题描述
加载子应用后执行报错，实测1.0.0-rc.9及之后的版本都有这个问题,1.0.0-rc.8 正常运行，

## 上传截图
<img width="623" alt="image" src="https://github.com/user-attachments/assets/ca6ca7cb-25f5-4628-9d01-3f234bf3ffc7">

## 环境信息
- micro-app版本：1.0.0-rc.12
- 主应用前端框架&版本：Vue3 3.4.21
- 子应用前端框架&版本：Vue3 3.4.21
- 构建工具&版本：vite 5.1.5

**Comment by YaoJianqun** [comment]
您的来信已收到！

**Comment by YaoJianqun** [comment]
https://github.com/YaoJianqun/micro-app-bug-repository

**Comment by timhub66** [comment]
> https://github.com/YaoJianqun/micro-app-bug-repository

@YaoJianqun , 换成module的导入导出就可以了

**Comment by timhub66** [comment]
> https://github.com/YaoJianqun/micro-app-bug-repository

@YaoJianqun ，换成module的导入导出方式就可以了，详细可参考如下

utils.js   
```js
function performComplexCalculation() {
  return "calculation";
}

export default performComplexCalculation
```   
    
worker.js
```js
import performComplexCalculation from 'http://localhost:6616/utils.js'

onmessage = function (event) {
  console.log(`主线程接收: ${event.data}`)

  const result = performComplexCalculation()

  postMessage(result)
}
```
