### ISSUE TITLE
不修改子应用的场景下怎么在主应用控制路由跳转；大佬们求个demo，感谢

### ISSUE THREAD

**Issue by shuixiaobin** [jd-opensource/micro-app#1411]
求个demo，由于子应用不可控（可能是跨部门的子应用），不考虑修改子应用监听路由跳转的那种方式；
子应用路由跳转完全由主应用控制，这种场景的demo；找了一圈没找到，求赐教；

我目前用的思路是用的路由的search模式，在主应用菜单切换时去赋值default-page；子应用内部的路由跳转这块目前用的监听路由的search，发现search的跳转路径赋值了就调用microApp.router.push去跳转。这种方式开发环境没问题，部署到线上后发现search混乱了，子应用内部跳转路径一直在叠加，/a跳到/b，线上的search参数会变成/a/b，求赐教思路，或者有没有类似场景的demo参考的.

**Comment by shuixiaobin** [comment]
![Uploading sdsd.png…]()

**Comment by shuixiaobin** [comment]
![sdsd](https://github.com/user-attachments/assets/7efc43e4-d4bb-43e3-b5d7-28b2b234da79)

**Comment by ghost** [comment]
<img width="1166" alt="image" src="https://github.com/user-attachments/assets/e975bad2-ed48-4a23-9706-bd04993990df">

在主应用里试试导航守卫呢

**Comment by sunnynudt** [comment]
> 求个demo，由于子应用不可控（可能是跨部门的子应用），不考虑修改子应用监听路由跳转的那种方式； 子应用路由跳转完全由主应用控制，这种场景的demo；找了一圈没找到，求赐教；
> 
> 我目前用的思路是用的路由的search模式，在主应用菜单切换时去赋值default-page；子应用内部的路由跳转这块目前用的监听路由的search，发现search的跳转路径赋值了就调用microApp.router.push去跳转。这种方式开发环境没问题，部署到线上后发现search混乱了，子应用内部跳转路径一直在叠加，/a跳到/b，线上的search参数会变成/a/b，求赐教思路，或者有没有类似场景的demo参考的.



@shuixiaobin 现在怎么解决的呢？

**Comment by shuixiaobin** [comment]
> > 求个demo，由于子应用不可控（可能是跨部门的子应用），不考虑修改子应用监听路由跳转的那种方式； 子应用路由跳转完全由主应用控制，这种场景的demo；找了一圈没找到，求赐教；
> > 我目前用的思路是用的路由的search模式，在主应用菜单切换时去赋值default-page；子应用内部的路由跳转这块目前用的监听路由的search，发现search的跳转路径赋值了就调用microApp.router.push去跳转。这种方式开发环境没问题，部署到线上后发现search混乱了，子应用内部跳转路径一直在叠加，/a跳到/b，线上的search参数会变成/a/b，求赐教思路，或者有没有类似场景的demo参考的.
> 
> @shuixiaobin 现在怎么解决的呢？

没解决呢，求个demo参考下，我目前就是开发环境好的，部署到线上有问题，官方都半个月了也不回复，着急啊

**Comment by shuixiaobin** [comment]
> <img alt="image" width="1166" src="https://private-user-images.githubusercontent.com/103547464/379696204-e975bad2-ed48-4a23-9706-bd04993990df.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzNzk4NjQsIm5iZiI6MTczMDM3OTU2NCwicGF0aCI6Ii8xMDM1NDc0NjQvMzc5Njk2MjA0LWU5NzViYWQyLWVkNDgtNGEyMy05NzA2LWJkMDQ5OTM5OTBkZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAzMVQxMjU5MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01Y2MxNmE0N2E0YzAwOGEwNGMzNDExNzU1ZThiMWE5MTA3YTQ0MGNlZGMzMTczMmY5YWI5NjAwYmNkMWJkYTczJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.oqjC9uib1e2-IB9EfTvbNPNiCdICH8IvMrJVPcMLKK0">
> 在主应用里试试导航守卫呢

试过了不行啊，你那有类似的demo吗，求参考

**Comment by nicoleWong007** [comment]
> > <img alt="image" width="1166" src="https://private-user-images.githubusercontent.com/103547464/379696204-e975bad2-ed48-4a23-9706-bd04993990df.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzNzk4NjQsIm5iZiI6MTczMDM3OTU2NCwicGF0aCI6Ii8xMDM1NDc0NjQvMzc5Njk2MjA0LWU5NzViYWQyLWVkNDgtNGEyMy05NzA2LWJkMDQ5OTM5OTBkZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAzMVQxMjU5MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01Y2MxNmE0N2E0YzAwOGEwNGMzNDExNzU1ZThiMWE5MTA3YTQ0MGNlZGMzMTczMmY5YWI5NjAwYmNkMWJkYTczJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.oqjC9uib1e2-IB9EfTvbNPNiCdICH8IvMrJVPcMLKK0">
> > 在主应用里试试导航守卫呢
> 
> 试过了不行啊，你那有类似的demo吗，求参考

基座项目改变路由的时候，向子应用推送一个action对象数据。子应用监听数据，改变当前路由

**Comment by Jennylx** [comment]
请问下这个解决了么，可以说下方法不 @shuixiaobin
