### ISSUE TITLE
nextjs 14+ app router 刷新页面 报错 ReferenceError: window is not defined

### ISSUE THREAD

**Issue by aurora-lch** [jd-opensource/micro-app#1416]
## 问题描述
> 问题的具体描述
主应用、子应用页面正常，但是服务端响应的html没有dom结构。控制台报错
ReferenceError: window is not defined

nextjs 最新版本官网中提到
[Full page load](https://nextjs.org/docs/app/building-your-application/rendering/client-components#full-page-load)
To optimize the initial page load, Next.js will use React's APIs to render a static HTML preview on the server for both Client and Server Components. This means, when the user first visits your application, they will see the content of the page immediately, without having to wait for the client to download, parse, and execute the Client Component JavaScript bundle.

## 复现步骤
1.
2.

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。

## 环境信息
- micro-app版本：1.0.0-rc.12
- 主应用前端框架&版本：14.2.15
- 子应用前端框架&版本：nginx:latest
- 构建工具&版本：14.2.15

**Comment by aurora-lch** [comment]
在客户端组件中使用useEffect 动态导入micro-app 来避免在服务端执行客户端代码，完美解决此问题。
`'use client';

import { useEffect } from "react";

export default function Index() {

  useEffect(() => {
    import('@micro-zoe/micro-app').then(res => {
      res.default.start();
    });
  }, []);

  return (
    <div>
      <micro-app name='my-app' url='http://10.211.55.3:3000' />
    </div>
  )
}
`
仅参考，还有一些useEffect的问题需要优化

**Comment by wuyuedefeng** [comment]
确定是完美解决了吗, 为什么我的随机报`Application error: a client-side exception has occurred (see the browser console for more information).`但是控制台却没有任何信息。

**Comment by yakutsuki** [comment]
nextjs  14版本作为子应用可以接入吗，总是报createTreeWalker错误
