### ISSUE TITLE
同一个页面两个子应用，在子应用中是用vue-router频繁切换页面，会出现： NotFoundError: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.

### ISSUE THREAD

**Issue by xiaogang12131** [jd-opensource/micro-app#1423]
## 问题描述
> 问题的具体描述
NotFoundError: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
## 复现步骤
1. 同一个页面两个子应用
2. 其中一个子应用 被设置 keep-alive：true，在其中是用vue-router，频繁跳转页面

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。
<img width="1035" alt="6f0c9f18643b1413c37e7e2c06962457" src="https://github.com/user-attachments/assets/e9a424f7-698c-4676-9605-8cafb27c0c56">
<img width="1051" alt="4734d9a48e03769f9fa74232d27709f0" src="https://github.com/user-attachments/assets/cb3d3d2c-4e67-4d6e-839e-6815d4b4c4f2">
发现是 insertbefore ，将元素插入到另一个子应用中，导致找不掉 parentNode，报错，帮忙看下这是什么问题

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。

## 环境信息
- micro-app版本：0.8.11
- 主应用前端框架&版本：react
- 子应用前端框架&版本：vue3
- 构建工具&版本：vue-cli@5.08

**Comment by ramseyfeng** [comment]
@xiaogang12131 请问你这问题后来解决了吗？
