### ISSUE TITLE
a标签路径补全bug

### ISSUE THREAD

**Issue by hellomooning** [jd-opensource/micro-app#1424]
## 问题描述
子应用a标签配置了click事件，未配置href，路径自动补全后引起bug，href被补全为href="http://xxx/undefined"，结果导致点击后页面不正常跳转

## 上传截图
![image](https://github.com/user-attachments/assets/6cef3b19-7d00-49e7-b2e2-00053fbc23e8)

## 环境信息
- micro-app版本：1.0.0-rc.10
- 主应用前端框架&版本：element plus 2.8.5
- 子应用前端框架&版本：element plus 2.8.5
- 构建工具&版本：vite

**Comment by hellomooning** [comment]
最新版貌似解决了，我更新试试

**Comment by timhub66** [comment]
@hellomooning ,用最新版还有问题吗？

**Comment by hellomooning** [comment]
没有问题了
