### ISSUE TITLE
v1.0.0-rc.6 版本 iframe 问题，

### ISSUE THREAD

**Issue by zyf540860996** [jd-opensource/micro-app#1429]
## 问题描述
> 问题的具体描述

在版本更新中看到了这条信息（修复 iframe沙箱下message事件无法被触发的问题）
未升级到 v1.0.0-rc.6 及后面的版本时，我子应用内的iframe都能postMessage，
升级到v1.0.0-rc.6+ 后，iframe直接没办法用了，感觉反向修复了

为了解决其他bug，我又不得不升级，真是好难

## 复现步骤
1.
2.

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。

## 环境信息
- micro-app版本：v1.0.0-rc.6+
- 主应用前端框架&版本：vue2
- 子应用前端框架&版本：vue3
- 构建工具&版本：vite

**Comment by gn131131** [comment]
我也有同样问题，父应用嵌套子应用，子应用使用iframe，iframe内部使用window.parent.postMessage(message, '*')，子应用window.addEventListener('message', messageListener)接受不到

**Comment by czAlexZhan** [comment]
> 我也有同样问题，父应用嵌套子应用，子应用使用iframe，iframe内部使用window.parent.postMessage(message, '*')，子应用window.addEventListener('message', messageListener)接受不到

请问这个解决了吗，遇到同样的问题
