### ISSUE TITLE
基座应用通过menu加载子应用的不同页面

### ISSUE THREAD

**Issue by HenryZhu-1988** [jd-opensource/micro-app#143]
![image](https://user-images.githubusercontent.com/43346131/141274101-4edb4d73-9651-430f-8944-1d67e263a60f.png)

根据micro-app 对 已有的老项目（App1）进行了改造，先建一个基座应用（Master），把老项目（App1） 的左侧菜单迁移到基座应用
(Master)中，按照这样的思路去改造的话，就是 每一个 menuItem 都会对应一个<macro-app ... /> ,对应的 <macro-app .../> 可能是同一个子应用，这样造成了重复加载

想问一下有没有比较优雅的方案来替换上述方案

**Comment by eric1202** [comment]
同老项目改造，想通过侧边栏menu sub item 切换同一个子项目页面，页面并没有改动，只有浏览器地址栏改动了
不知道怎么解决。。

**Comment by bailicangdu** [comment]
@eric1202 参考 https://github.com/micro-zoe/micro-app/issues/100

**Comment by bailicangdu** [comment]
@eric1202 应用之间跳转方式：https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/jump

**Comment by bailicangdu** [comment]
@JoMartinezZhu 侧边栏路由指向同一个组件就行了

**Comment by eric1202** [comment]
> @eric1202 应用之间跳转方式：https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/jump

已解决
可在router文件，router.beforeEach((to, from, next) => {} 做处理

**Comment by HenryZhu-1988** [comment]
> > @eric1202 应用之间跳转方式：https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/jump
> 
> 已解决 可在router文件，router.beforeEach((to, from, next) => {} 做处理

是在基座应用处理还是子应用做处理呢？

**Comment by eric1202** [comment]
> > > @eric1202 应用之间跳转方式：https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/jump
> > 
> > 
> > 已解决 可在router文件，router.beforeEach((to, from, next) => {} 做处理
> 
> 是在基座应用处理还是子应用做处理呢？

基座

**Comment by HenryZhu-1988** [comment]
> @JoMartinezZhu 侧边栏路由指向同一个组件就行了

我做了左侧菜单中指向同一个组件（接入子应用的组件），但是基座应用的路由是变了，但是子应用中的内容并没有变

**Comment by HenryZhu-1988** [comment]
> > > > @eric1202 应用之间跳转方式：https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/jump
> > > 
> > > 
> > > 已解决 可在router文件，router.beforeEach((to, from, next) => {} 做处理
> > 
> > 
> > 是在基座应用处理还是子应用做处理呢？
> 
> 基座
我目前的点击 基座的menu ,基座的router 会发生变化，而且接入子应用的组件 也会render，就是内容不发生变化

**Comment by bailicangdu** [comment]
> > > > > @eric1202 应用之间跳转方式：https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/jump
> > > > 
> > > > 
> > > > 已解决 可在router文件，router.beforeEach((to, from, next) => {} 做处理
> > > 
> > > 
> > > 是在基座应用处理还是子应用做处理呢？
> > 
> > 
> > 基座
> > 我目前的点击 基座的menu ,基座的router 会发生变化，而且接入子应用的组件 也会render，就是内容不发生变化

基座路由跳转影响不到子应用，一般通过下发通知，让子应用进行跳转

**Comment by HenryZhu-1988** [comment]
> > > > > > @eric1202 应用之间跳转方式：https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/jump
> > > > > 
> > > > > 
> > > > > 已解决 可在router文件，router.beforeEach((to, from, next) => {} 做处理
> > > > 
> > > > 
> > > > 是在基座应用处理还是子应用做处理呢？
> > > 
> > > 
> > > 基座
> > > 我目前的点击 基座的menu ,基座的router 会发生变化，而且接入子应用的组件 也会render，就是内容不发生变化
> 
> 基座路由跳转影响不到子应用，一般通过下发通知，让子应用进行跳转

对对对，我实现过程中出现了 history 不兼容 react-router的问题，所以一直没有实现。
现在解决了

**Comment by HenryZhu-1988** [comment]
> > > > > > > @eric1202 应用之间跳转方式：https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/jump
> > > > > > 
> > > > > > 
> > > > > > 已解决 可在router文件，router.beforeEach((to, from, next) => {} 做处理
> > > > > 
> > > > > 
> > > > > 是在基座应用处理还是子应用做处理呢？
> > > > 
> > > > 
> > > > 基座
> > > > 我目前的点击 基座的menu ,基座的router 会发生变化，而且接入子应用的组件 也会render，就是内容不发生变化
> > 
> > 
> > 基座路由跳转影响不到子应用，一般通过下发通知，让子应用进行跳转
> 
> 对对对，我实现过程中出现了 history 不兼容 react-router的问题，所以一直没有实现。 现在解决了

现在发现 基座左侧菜单控制调整子应用可以通过基座向子应用发通知，子应用监听到后，去自己跳转。
但是如果子应用自己主动触发了跳转，基座应用左侧菜单需要同步到相应的 menuItem 并改变显示的状态，要实现这样的功能，需要子应用通知基座应用，基座应用自己改变menuItem的状态？

**Comment by bailicangdu** [comment]
> > > > > > > > @eric1202 应用之间跳转方式：https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/jump
> > > > > > > 
> > > > > > > 
> > > > > > > 已解决 可在router文件，router.beforeEach((to, from, next) => {} 做处理
> > > > > > 
> > > > > > 
> > > > > > 是在基座应用处理还是子应用做处理呢？
> > > > > 
> > > > > 
> > > > > 基座
> > > > > 我目前的点击 基座的menu ,基座的router 会发生变化，而且接入子应用的组件 也会render，就是内容不发生变化
> > > 
> > > 
> > > 基座路由跳转影响不到子应用，一般通过下发通知，让子应用进行跳转
> > 
> > 
> > 对对对，我实现过程中出现了 history 不兼容 react-router的问题，所以一直没有实现。 现在解决了
> 
> 现在发现 基座左侧菜单控制调整子应用可以通过基座向子应用发通知，子应用监听到后，去自己跳转。 但是如果子应用自己主动触发了跳转，基座应用左侧菜单需要同步到相应的 menuItem 并改变显示的状态，要实现这样的功能，需要子应用通知基座应用，基座应用自己改变menuItem的状态？

简单来说是需要这样做

**Comment by Kryzeno** [comment]
如果是keep-alive 子应用页面跳转了  再切回去 状态还能保持吗?

**Comment by Kryzeno** [comment]
> @eric1202应用跳转方式：https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/jump
我这里指向同一个组件 会出现重复加载的提示
[micro-app] app app1: app name conflict, an app named app1 is running

**Comment by bailicangdu** [comment]
> 如果是keep-alive 子应用页面跳转了 再切回去 状态还能保持吗?

子应用内部跳转的状态保留由应用自己控制，如vue的keep-alive，vuex、redux之类

**Comment by bailicangdu** [comment]
> > 如果是keep-alive 子应用页面跳转了 再切回去 状态还能保持吗?
> 
> 子应用内部跳转的状态保留由应用自己控制，如vue的keep-alive，vuex、redux之类

micro-app只能控制应用级别的，无法细节到每个页面
