### ISSUE TITLE
引入yudao vue3模版作为子应用 出现 app yudao-ui-admin-vue3:  SyntaxError: Cannot use import statement outside a module 的问题

### ISSUE THREAD

**Issue by pjczz** [jd-opensource/micro-app#1437]
## 问题描述
> 问题的具体描述
引入yudao vue3模版作为子应用 出现 app yudao-ui-admin-vue3:  SyntaxError: Cannot use import statement outside a module 的问题

;import "/node_modules/.pnpm/vite@5.1.4_@types+node@20.12.7_sass@1.75.0_terser@5.30.4/node_modules/vite/dist/client/env.mjs";
显示这个代码有错误
## 复现步骤
1.vue create 一个项目  根据官网方式引入 作为父应用
2.引入一个yudaovue3模板的后台  
3.停留在loaidng界面， 控制台显示报错
这看起来是一个babel错误 但两个项目都有babel 且可以独立运行

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。
![image](https://github.com/user-attachments/assets/34b84685-77c2-4f24-b793-b557cf4be0fe)

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。
https://github.com/pjczz/trymicro
https://github.com/pjczz/yudaoproblem

## 环境信息
- micro-app版本：1.0.0-rc.13
- 主应用前端框架&版本：vue3 3.5.12
- 子应用前端框架&版本：vue3 3.4.21(typescript@5.3.3)
- 构建工具&版本：'@vue/cli-service': 5.0.8

**Comment by pjczz** [comment]
vite 使用 沙箱iframe接入  希望文档能在手把手的时候 写入

**Comment by snowbitx** [comment]
<micro-app iframe name='my-app' url='http://localhost:5174/'></micro-app>   加了iframe可以了。官网做的确实，按照步骤操作是不行的

**Comment by yw738** [comment]
确实 加了iframe 就没问题了 0.0

**Comment by young-tree** [comment]
什么意思？怎么加iframe？

**Comment by young-tree** [comment]
在这个micro-app标签上加个iframe属性就行
