### ISSUE TITLE
样式隔离只通过加micro-app前缀进行吗

### ISSUE THREAD

**Issue by XueMeijing** [jd-opensource/micro-app#144]
## 问题描述
> 问题的具体描述
现在旧项目使用ionic1，新项目使用ionic5，两个子应用同时出现的时候ionic5就会通过shadow dom修改旧项目ionic组件的样式，导致样式隔离失效
## 复现步骤
1.
2.

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。

## 环境信息
- micro-app版本：0.4.3
- 主应用前端框架&版本：react
- 子应用前端框架&版本：react+ionic5 和angular+ionic1
- 构建工具&版本：

**Comment by bailicangdu** [comment]
具体表现是什么呢，子应用之间样式冲突还是主应用和子应用样式冲突？

**Comment by XueMeijing** [comment]
> 具体表现是什么呢，子应用之间样式冲突还是主应用和子应用样式冲突？

主应用引入ionic5或者子应用引入ionic5并且和另一个子应用angular+ionic1同时出现在一个页面上，ionic5就会覆盖ionic1的样式，在ionic那边提了个issue是这么说的 https://github.com/ionic-team/ionic-framework/issues/24180 ，只是我不清楚他那里是怎么突破隔离来修改全局的样式的，抱歉没怎么用过angular没法写复现demo

**Comment by bailicangdu** [comment]
看解释是 `<ion-content>` 被ionic5重写了

**Comment by bailicangdu** [comment]
![image](https://user-images.githubusercontent.com/20297227/141969785-f4972326-5b55-443f-aed0-e0e3ecc82c3e.png)

**Comment by XueMeijing** [comment]
> 看解释是 `<ion-content>` 被ionic5重写了

是的。。但是这两个子应用是平行的，有js沙箱和元素隔离啥的按理说只能修改当前子应用的样式啊，不清楚micro-app有没有这种情况的解决方式?

**Comment by bailicangdu** [comment]
正常情况是隔离的，但显然ionic可以突破这个限制，有空我试一下

**Comment by XueMeijing** [comment]
> 正常情况是隔离的，但显然ionic可以突破这个限制，有空我试一下

嗯嗯好嘞
