### ISSUE TITLE
子应用中instanceOf无法识别继承自Array的类型实例

### ISSUE THREAD

**Issue by AdonLee** [jd-opensource/micro-app#1443]
## 问题描述
> 沙箱里instanceOf无法识别继承自Array的类型

## 复现步骤
在任意子应用中执行此代码
```typescript
class ArrayEx extends Array {
  unique() {}
}
if ([] instanceof ArrayEx) {
  alert('[] should not be instance of ArrayEx');
}
```

## 上传截图
> 无

## 复现仓库
> 无

## 环境信息
- micro-app版本：1.0.0-rc.8
- 主应用前端框架&版本：@angular/core@17.1.3
- 子应用前端框架&版本：@angular/core@17.1.3
- 构建工具&版本：@angular-devkit/build-angular:application

**Comment by AdonLee** [comment]
临时方案可在instanceOf的劫持方法里增加构造器函数名判断
![image](https://github.com/user-attachments/assets/d1890ff6-e430-445c-a278-1ee1baa28548)

**Comment by timhub66** [comment]
@AdonLee ，升级到最新版本试试

**Comment by qyjs** [comment]
> 临时方案可在instanceOf的劫持方法里增加构造器函数名判断 ![image](https://github.com/user-attachments/assets/d1890ff6-e430-445c-a278-1ee1baa28548)

大佬，你用angular17 集成微前端，angular 用的是独立租户么 @AdonLee
