### ISSUE TITLE
使用 blob string url 创建 WebWorker 时报错

### ISSUE THREAD

**Issue by chenhuang444** [jd-opensource/micro-app#1444]
## 问题描述
> 微前端内使用 blob url 创建 WebWorker，报错 `importScripts is undefined`

## 复现步骤
1. 自应用使用 `troika-three-text` 库。
2. 调用 `preloadFont` 创建 web worker

## 问题定位
`troika-three-text` 创建 WebWorker 的代码为、
```javascript
// packages/troika-worker-utils/src/WorkerModules.js
new Worker(URL.createObjectURL(xxx));
```
所以传入 Worker 的参数为 "blob://xxxxxxxx"

Micro App 处理错误:
```typescript
// src/proxies/worker.ts
function isSameOrigin(url: string | URL): boolean {
  if (url instanceof URL && url.protocol === 'blob:') {
    // 如果 url 是 Blob URL，直接返回 true
    return true
  }

  // ...
}
```
上面这部分代码为处理 url 为 string 的情况。导致创建 Worker 时使用了 type='module'。而 `troika-three-text` 使用的是 type='classic' 的语法写的

## 环境信息
- micro-app版本：1.0.0-rc.13
- 主应用前端框架&版本：1.0.0-rc.13
- 子应用前端框架&版本：1.0.0-rc.13
- 构建工具&版本：1.0.0-rc.13

**Comment by chenhuang444** [comment]
已提供 PR，希望可以尽快合并。我这边先本地打包一份 micro-app 先用着
https://github.com/micro-zoe/micro-app/pull/1445

**Comment by timhub66** [comment]
@chenhuang444 ,帮忙整一个复现demo，需要验证一下再和PR

**Comment by chenhuang444** [comment]
> @chenhuang444 ,帮忙整一个复现demo，需要验证一下再和PR

https://github.com/chenhuang444/micro-app-blob-string-example

`pnpm install`
`pnpm dev`
就可以
