### ISSUE TITLE
利用build命令打包失败了

### ISSUE THREAD

**Issue by whenTheMorningDark** [jd-opensource/micro-app#145]
我想请问下，能够进行打包出dist文件的吗？

**Comment by bailicangdu** [comment]
报错信息是什么？

**Comment by whenTheMorningDark** [comment]
> 报错信息是什么？

![image](https://user-images.githubusercontent.com/30688843/142096374-fd2355e2-9d6e-45d9-b98d-1369a0fa994d.png)
帮忙看下是什么原因，公司要上微前端，万分感谢

**Comment by whenTheMorningDark** [comment]
有办法解决吗？我找了好久都没方案

**Comment by bailicangdu** [comment]
看不出问题，不过你可以把后面两个命令删除试一下
![image](https://user-images.githubusercontent.com/20297227/142344851-b0c8b80e-aab6-4f23-a2b4-274d7c40bd1a.png)

**Comment by whenTheMorningDark** [comment]
![image](https://user-images.githubusercontent.com/30688843/143160039-236b90f2-c633-40ab-aee4-964c39837635.png)


> 看不出问题，不过你可以把后面两个命令删除试一下 ![image](https://user-images.githubusercontent.com/20297227/142344851-b0c8b80e-aab6-4f23-a2b4-274d7c40bd1a.png)

![image](https://user-images.githubusercontent.com/30688843/143160042-643ca541-c082-423d-b784-81f53968b18c.png)
打包出来是这样的，这样是正确的？我直接部署index.js?
