### ISSUE TITLE
子应用挂载到父应用中的时候，子应用写的样式全部都丢失了，因为vue语法中的style有一个scoped样式隔离，去掉就正常了，但是不加会影响全局

### ISSUE THREAD

**Issue by PJK15889522750** [jd-opensource/micro-app#1466]
## 问题描述
> 问题的具体描述

## 复现步骤
1.子应用挂载到父应用中的时候，子应用写的样式全部都丢失了，因为vue语法中的style有一个scoped样式隔离，去掉就正常了，但是不加会影响全局

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。

## 环境信息
- micro-app版本：
- 主应用前端框架&版本：
- 子应用前端框架&版本：
- 构建工具&版本：

**Comment by PJK15889522750** [comment]
> Hello @PJK15889522750. In order to facilitate location and troubleshooting, we need you to provide a realistic GitHub repository. 您好 @PJK15889522750, 为了方便定位和排查问题，我们需要您提供一个重现实例，请提供一个尽可能精简的 GitHub 仓库地址。





![企业微信截图_17337346483360](https://github.com/user-attachments/assets/34329b3a-6f79-4b44-8f60-90455b677a81)
比如我在子应用中写了这么一段样式，在主应用加载子应用的时候检查元素可以看到对应的class，但是里面的style是加载不出来的，目前试了一下“1.0.0-rc.15”这个版本是没有这个问题的，但是更新到“1.0.0-rc.16”的时候这个问题就是必现的

**Comment by Cenmingyang** [comment]
我降到了1.0.0-rc.15这个版本，样式还是丢失，大佬能解答一下嘛

**Comment by PJK15889522750** [comment]
> 我降到了1.0.0-rc.15这个版本，样式还是丢失，大佬能解答一下嘛

你的应该是缓存问题吧，打包有没有加hash

**Comment by caohongjie** [comment]
![Uploading 7a8cf448780f3a50c5606746f4dac9d4.png…]()
我看了下子应用的css，发现data-v-hash值被改了，多了个__mock_data-xxxx，导致样式不生效，我也是这两天发现的问题

**Comment by DTZHY** [comment]
我的1.0.0-rc.16版本，也出现了项目中style写scoped，导致样式失效的问题
加scoped不生效
<style lang="scss" scoped>
.main-wrapper {
  padding: 18px 20px 20px 20px;
}
</style>


不加scoped就生效
<style lang="scss">
.main-wrapper {
  padding: 18px 20px 20px 20px;
}
</style>

**Comment by chenzhouli1994** [comment]
看来都有这个问题啊。子应用的css，发现data-v-hash值被改了，多了个__mock_data-xxxx，导致样式不生效，

**Comment by wiscgazf** [comment]
这个库提供的dev demo 代码，子应用都是没有加scoped，如果子应用加上scoped，样式都会失效，因为disable-scopecss禁用后，子应用的样式都会自动加上 [appName=子应用名] 子应用样式{}

**Comment by chenzhouli1994** [comment]
问题的点是串改了原本的css类名注入。浏览器也找不到啊 多了个复制方法 __mock_data-xxxx。应该是css隔离代码有问题

**Comment by timhub66** [comment]
1.0.0-rc.17 已修复
