### ISSUE TITLE
1.0.0-rc.16版本有问题，子项目不会加载css了。降级到1.0.0-rc.15就好了

### ISSUE THREAD

**Issue by a624418020** [jd-opensource/micro-app#1468]
## 问题描述
> 问题的具体描述

## 复现步骤
1.
2.

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。

## 环境信息
- micro-app版本：
- 主应用前端框架&版本：
- 子应用前端框架&版本：
- 构建工具&版本：

**Comment by DTZHY** [comment]
降级到1.0.0-rc.15还是不生效，npm缓存也清理过，包也删除重新下载过，还有其他解决饭方案吗

**Comment by DTZHY** [comment]
正解，主应用降级到1.0.0-rc.15就好了，给楼主点赞

**Comment by Lucklj521** [comment]
我也遇到了同样的问题，降到rc.15就好了

**Comment by YFAnt** [comment]
原因是适配uncoss问题导致的，正则代码在这有点问题，官方人员已经知道了，目前在修复
<img width="888" alt="image" src="https://github.com/user-attachments/assets/9722d2ed-2600-46b0-897c-45acba4febc5" />

遇到问题的先用rc15吧
