### ISSUE TITLE
父子应用开发环境正常运行，部署后子应用访问不到后端

### ISSUE THREAD

**Issue by 122504387** [jd-opensource/micro-app#1474]
子应用独立部署运行，可以正常访问后端，在父应用中不能访问，Nginx的配置都试了，请教怎么解决？

**Comment by shawn2013** [comment]
我也遇到这个问题。基座、子应用都是vite，子应用部署在nginx，基座在dev环境运行，可以正常访问。如果把基座发布到nginx，就访问补了。
1.0.0-rc.17版本
提示跨域拦截，但能配置的都已经配置了

**Comment by 122504387** [comment]
<micro-app
      iframe
      :url="url"
      :data="microAppData"
      disable-patch-request
    ></micro-app>
解决了，加上disable-patch-request就可以了
