### ISSUE TITLE
浏览器回退操作触发子应用404页面

### ISSUE THREAD

**Issue by LoveqLRC** [jd-opensource/micro-app#148]
从基座进入子应用，然后浏览器进行回退操作，会有一瞬间触发子应用的404页面，404页面的匹配路径是“*”，然后页面再回到基座，请问一下如何解决这个问题？

**Comment by bailicangdu** [comment]
建议在微前端环境下，子应用去掉404页面

**Comment by LoveqLRC** [comment]
好的，谢谢大佬
