### ISSUE TITLE
增加 sourceMap ，行号对应不上的问题

### ISSUE THREAD

**Issue by chenxtdo** [jd-opensource/micro-app#150]
## 问题描述
> 主应用跟在子应用开发时，通过 microApp 的 plugins 增加了sourceMap，但发现对应不上的问题。后来自己尝试通过把microApp的 Function 执行，改为 eval 执行，就对应上了。具体效果参考图片。子应用  console 在 第九行

## 上传截图
1. 
<img width="661" alt="image" src="https://user-images.githubusercontent.com/9393714/142590179-8318fce5-8c24-4a5b-8ab3-f7e321d0c351.png">
2. 
<img width="914" alt="image" src="https://user-images.githubusercontent.com/9393714/142590491-412ba609-49c4-4678-bd51-8f6ecd1bce68.png">
3. 
<img width="406" alt="image" src="https://user-images.githubusercontent.com/9393714/142590534-6a4e3729-45d8-47e7-a363-e46635d588c3.png">

4. 
<img width="803" alt="image" src="https://user-images.githubusercontent.com/9393714/142590717-39d13b58-71f4-4f5b-9761-ac3c2673d627.png">
5. 

<img width="910" alt="image" src="https://user-images.githubusercontent.com/9393714/142590975-0c7a5eda-2343-46a2-839e-fc8cbe42b721.png">

**Comment by bailicangdu** [comment]
👍

**Comment by bailicangdu** [comment]
但我们不能将function改成eval

**Comment by chenxtdo** [comment]
@bailicangdu  那帮忙看下，这个问题有什么解法

**Comment by WeirShi** [comment]
这个问题现在是怎么解决的？？？官方不管了么？？？
