### ISSUE TITLE
请问micro-app可以实现子应用之间组件的共享

### ISSUE THREAD

**Issue by yongchaozeng** [jd-opensource/micro-app#151]
请问micro-app有方案可以实现子应用之间组件的共享，或者webpack5 federation

**Comment by bailicangdu** [comment]
目前不好实现

**Comment by yongchaozeng** [comment]
> 目前不好实现

能请教个问题吗，webpack5 federation可以实现子组件的共享，为什么国内各微前端都是single-spa方向的，是webpack5 federation有某些方面的问题吗

**Comment by bailicangdu** [comment]
webpack5 联邦模块主要就是用于共享组件，小到一个按钮，大到一个页面一个应用都可以作为组件共享，共享页面也就实现了微前端，但它有2点要求，1是必须是相同前端框架 2是必须是webpack5。而我们目前遇到的微前端场景大多是对旧项目的改造，这些项目使用不同的技术栈，甚至不同的构建工具，这些问题webpack5无法解决，但我个人认为webpack5的上限更高，前景更好

**Comment by yongchaozeng** [comment]
> webpack5 联邦模块主要就是用于共享组件，小到一个按钮，大到一个页面一个应用都可以作为组件共享，共享页面也就实现了微前端，但它有2点要求，1是必须是相同前端框架 2是必须是webpack5。而我们目前遇到的微前端场景大多是对旧项目的改造，这些项目使用不同的技术栈，甚至不同的构建工具，这些问题webpack5无法解决，但我个人认为webpack5的上限更高，前景更好

感谢大佬的回复，之前看了下基于webpack5 federation的emp，好像有方法兼容不同框架，不过社区还在发展的过程中
