### ISSUE TITLE
浏览器自带的返回导致路由不对

### ISSUE THREAD

**Issue by lvwen76** [jd-opensource/micro-app#155]
## 问题描述
>【路由问题】使用浏览器自带的返回，导致路由不对，页面展示空白

## 复现步骤
1.基座应用是history路由，子应用是history路由，我们要跳转基座应用的【客户】页面，页面中嵌入多个子应用【客户列表】【客户群列表】。
2.当点击子应用【客户列表】时，通过文档中标注的方法（基座路由控制）的方式实现跳转到筛选页
3.此时点击浏览器自带的返回时出现该问题

## 上传截图
>
路径/tabclient/list
![image](![image](https://user-images.githubusercontent.com/52878861/142835734-2da9ce9a-7e0b-45f2-a18c-d55123098663.png)
路径/client/fifter
![image](https://user-images.githubusercontent.com/52878861/142835329-3b66ddba-e2fe-4b02-b89f-db2bdb8e9515.png)

## 环境信息
- micro-app版本：
- 主应用前端框架&版本：vant 3.2.6
- 子应用前端框架&版本：vant 3.2.6
- 构建工具&版本：yarn vue-cli

**Comment by bailicangdu** [comment]
我们在自己的demo中没有复现这个问题，希望可以提供一个demo帮助我们复现、调试。

**Comment by lvwen76** [comment]
这是我写的demo。
git仓库地址`https://github.com/lvwen76/microapp.git`

**Comment by bailicangdu** [comment]
> 这是我写的demo。 git仓库地址`https://github.com/lvwen76/microapp.git`

好的，问题已复现，目前定位是vue-router4冲突导致的，正在查找解决方式

**Comment by bailicangdu** [comment]
解决方式：在site-one，site-two子应用  main.js 中添加下面代码
![image](https://user-images.githubusercontent.com/20297227/143182328-a0418e92-f34f-49bd-b862-8e72c9801154.png)

```js
if (window.__MICRO_APP_ENVIRONMENT__) {
  router.beforeEach(() => {
    if (window.history.state?.current) {
      window.history.state.current = window.history.state.current.replace(new RegExp(window.__MICRO_APP_BASE_ROUTE__, 'g'), '')
    }
  })

  router.afterEach(() => {
    if (typeof window.history.state === 'object') {
      window.history.state.current = window.__MICRO_APP_BASE_ROUTE__ +  (window.history.state.current || '')
    }
  })
}
```

**Comment by bailicangdu** [comment]
```js
if (window.__MICRO_APP_ENVIRONMENT__) {
  router.beforeEach(() => {
    if (window.history.state?.current) {
      window.history.state.current = window.history.state.current.replace(new RegExp(window.__MICRO_APP_BASE_ROUTE__, 'g'), '')
    }
  })

  router.afterEach(() => {
    if (typeof window.history.state === 'object') {
      window.history.state.current = window.__MICRO_APP_BASE_ROUTE__ +  (window.history.state.current || '')
    }
  })
}
```

**Comment by agileago** [comment]
这个问题我之前给提过pr，但他没接受，他认为场景很有限 。。。 https://github.com/vuejs/vue-router-next/issues/1071
我没办法只能fork一下，用自己的版本解决了， 有谁需要可以安装  

```
yarn add @vue3-oop/vue-router
```

**Comment by xiangxinji** [comment]
@bailicangdu 我现在的子应用里面的push 跳转会将子应用本身的 path 给记录进去， 然后主应用那边的历史记录就记录混乱了。 上面的代码我试了， 好像没什么用。  有什么好的方式解决这种问题吗 ？ 
比如子应用里面的一个 push path = /test , 主应用那边自己跳转的记录没问题， 但是点了子应用的跳转之后， 会掺和着刚刚那条 /test 的记录。 
"vue-router": "^4.0.11", 
"@micro-zoe/micro-app": "0.8.1"

**Comment by xiangxinji** [comment]
vue-router 版本是 "vue-router": "^4.0.11",

**Comment by kelvin-lemon** [comment]
> 
这个问题有解决方案吗

**Comment by kelvin-lemon** [comment]
> @bailicangdu 我现在的子应用里面的push 跳转会将子应用本身的 path 给记录进去， 然后主应用那边的历史记录就记录混乱了。 上面的代码我试了， 好像没什么用。 有什么好的方式解决这种问题吗 ？ 比如子应用里面的一个 push path = /test , 主应用那边自己跳转的记录没问题， 但是点了子应用的跳转之后， 会掺和着刚刚那条 /test 的记录。 "vue-router": "^4.0.11", "@micro-zoe/micro-app": "0.8.1"

这个问题有解决方案吗

**Comment by qinpegnsen** [comment]
官方给的不管用啊

**Comment by wow0218** [comment]
原因就是VueRouter会同时操作window.history.
我的解决方式就是让所有的子应用构建自己独有的路由：
VueRouter4: createRouter({ history: createMemoryHistory(basePath)， routes });

/** 测试的时候 VueRouter3好像也会有影响，懒得仔细看了，也同样改掉  */
VueRouter3: new VueRouter({ mode: 'abstract', base: basePath, routes });


子应用Vue3:
![image](https://github.com/micro-zoe/micro-app/assets/8154536/ba40f28e-7b19-4c69-87c0-ef36d8e45c4b)

子应用Vue2:
![image](https://github.com/micro-zoe/micro-app/assets/8154536/fc79411d-d658-4c6b-83dc-6efa9619be5f)

主应用是Vue3：
![image](https://github.com/micro-zoe/micro-app/assets/8154536/d7fc9229-ce17-4e21-8ba1-a1622bfabb9c)
