### ISSUE TITLE
子应用根据相对路径动态加载的静态资源文件，前缀会被补成基座的domain和端口

### ISSUE THREAD

**Issue by FWiner** [jd-opensource/micro-app#156]
子应用根据相对路径动态加载的静态资源文件，前缀会被补成基座的domain和端口。
想问下这个有什么办法解决么。

**Comment by bailicangdu** [comment]
因为它是嵌入到基座进行渲染的，浏览器会自动补全为基座域名，解决方式参考：https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/static-source?id=publicpath

**Comment by FWiner** [comment]
> 因为它是嵌入到基座进行渲染的，浏览器会自动补全为基座域名，解决方式参考：https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/static-source?id=publicpath

你好，我看了下这个是基于webpack的？有没有基于普通项目的。因为现在一般用这个微应用的不单单只是多个项目集成那么简单，好像也有一大部分都是奔着老项目重构，新项目并存的来的。。

**Comment by FWiner** [comment]
然后我还有个问题，关于样式的怎么解决呢。。子应用中 某个class 设置了。background-image: url(../img/icon-3.png); 这个图片页会被自动补全成基座应用的前缀。。

**Comment by bailicangdu** [comment]
其他没有很好的解决方式

**Comment by Kucell** [comment]
按照文档配置了public-path还是不行，还会有其他因素导致地址未正确转换吗

**Comment by bailicangdu** [comment]
> 地址

代码贴一下，否则看不出问题出在哪里

**Comment by bailicangdu** [comment]
> 按照文档配置了public-path还是不行，还会有其他因素导致地址未正确转换吗

代码贴一下，否则看不出问题出在哪里

**Comment by LlanHao** [comment]
> > 文档配置了public-path还是不行，还有其他按照指引的地址未正确转换吗
> 
> 贴代码一下，否则看不出问题在哪里
子应用：.bg_img { background: url('../assets/images/icon-img-1.png') no-repeat; } 子应用独立运行在8081端口是可以的，
子应用嵌入到基座(8080端口)后，url 自动请求为 xx.xx.xx.xx:8080/xxx/xxx/xxx.png

**Comment by ccmtea** [comment]
> > > 文档配置了public-path还是不行，还有其他按照指引的地址未正确转换吗
> > 
> > 
> > 贴代码一下，否则看不出问题在哪里
> > 子应用：.bg_img { background: url('../assets/images/icon-img-1.png') no-repeat; } 子应用独立运行在8081端口是可以的，
> > 子应用嵌入到基座(8080端口)后，url 自动请求为 xx.xx.xx.xx:8080/xxx/xxx/xxx.png

请问这个问题有找到解决方案吗？

**Comment by raoenhui** [comment]
> 图片用绝对地址引入

**Comment by bewhatyouare** [comment]
> 按照文档配置了public-path还是不行，还会有其他因素导致地址未正确转换吗

非动态引入的可以正确转换，但是动态加载的图片展示不出来，请问解决了吗？

**Comment by bewhatyouare** [comment]
> > > > 文档配置了public-path还是不行，还有其他按照指引的地址未正确转换吗
> > > 
> > > 
> > > 贴代码一下，否则看不出问题在哪里
> > > 子应用：.bg_img { background: url('../assets/images/icon-img-1.png') no-repeat; } 子应用独立运行在8081端口是可以的，
> > > 子应用嵌入到基座(8080端口)后，url 自动请求为 xx.xx.xx.xx:8080/xxx/xxx/xxx.png
> 
> 请问这个问题有找到解决方案吗？

非动态引入的可以正确转换，但是动态加载的图片展示不出来，同问，解决了吗？

**Comment by bewhatyouare** [comment]
> > 按照文档配置了public-path还是不行，还会有其他因素导致地址未正确转换吗
> 
> 代码贴一下，否则看不出问题出在哪里

:style="{backgroundImage:'url(static/img/xx.png)'}"   类似这样引入的，都转到基座的URL下了

**Comment by T0205** [comment]
解决了吗?

**Comment by bailicangdu** [comment]
> 解决了吗?

旧的issue基本已经解决，有问题可以新开一个issue
