### ISSUE TITLE
子应用使用最新elemen-plus,变量样式丢失

### ISSUE THREAD

**Issue by mursumomo** [jd-opensource/micro-app#157]
官方样式
![WeChat3a416af6e4d57a2b895705c54a3366b5](https://user-images.githubusercontent.com/43238460/143183742-f77b3595-6664-416f-a1a2-405769605bfe.png)
子应用样式
![image](https://user-images.githubusercontent.com/43238460/143183865-e8369d9f-d855-422a-9045-2ee04d144fb4.png)

**Comment by bailicangdu** [comment]
这个问题同 https://github.com/micro-zoe/micro-app/issues/121 ，暂时只能通过设置disableScopecss关闭样式隔离解决
