### ISSUE TITLE
子应用样式问题

### ISSUE THREAD

**Issue by chenxtdo** [jd-opensource/micro-app#158]
## 问题描述
发现 micro-app 解析子应用的link 样式的时候，会把 style 插在head 的最后，现在我们在使用的子应用框架也会插入 style。
未使用 micro-app 的时候，样式的顺序是 link （子应用style），使用后 micro-app 顺序微 （子应用 style）(link 转换后的 style)
期望， micro-app 加载样式的时候，在当前 link 的位置增加placeholderComment，而不是 head 的最后。
## 复现步骤
1. 
<img width="651" alt="image" src="https://user-images.githubusercontent.com/9393714/143192410-dc6777b9-4747-4fae-bf0e-15c0c3cd4802.png">

<img width="640" alt="image" src="https://user-images.githubusercontent.com/9393714/143192242-e830a397-76b4-40db-b972-735dae0c237b.png">

<img width="974" alt="image" src="https://user-images.githubusercontent.com/9393714/143192461-ff013f36-ddc4-45f6-a0f2-d0bec22c7d6c.png">

**Comment by bailicangdu** [comment]
下个版本0.5.1会进行修复，thanks

**Comment by bailicangdu** [comment]
https://github.com/micro-zoe/micro-app/releases/tag/v0.5.1 已修复
