### ISSUE TITLE
angular框架-主应用-Demo-版本

### ISSUE THREAD

**Issue by ColaLovingCat** [jd-opensource/micro-app#16]
请问有以angular框架为父子应用的demo吗？对于angular的版本有要求吗？谢谢

**Comment by bailicangdu** [comment]
可以用于angular框架，稍后会增加angular的案例

**Comment by renwofei423** [comment]
同样关心 ，期待^^

**Comment by renwofei423** [comment]
等得着急呀

**Comment by Eve-Sama** [comment]
+1

**Comment by Eve-Sama** [comment]
请问有预计时间吗? 非常期待!

**Comment by xabru** [comment]
太好了，我们正在等待，我还想询问是否包含 Svelte 框架

**Comment by Ericxiaoshuang** [comment]
+1, 目前也需要angular9作为主应用,子应用用react17开发项目
希望有示例

**Comment by smile2014** [comment]
同求

**Comment by bailicangdu** [comment]
参考文档 https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/framework/angular, 以及demo 案例 https://github.com/micro-zoe/micro-app-demo
