### ISSUE TITLE
子应用切换再次访问时候，会报__visitId错误

### ISSUE THREAD

**Issue by mursumomo** [jd-opensource/micro-app#160]
![image](https://user-images.githubusercontent.com/43238460/143419222-05f0de37-ac85-4d5b-9260-2ffc7f2bc75b.png)
根据错误看了下，指向的是micro-app的文件

**Comment by bailicangdu** [comment]
有设置这个吗 https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/advanced?id=_3%e3%80%81%e6%80%a7%e8%83%bdamp%e5%86%85%e5%ad%98%e4%bc%98%e5%8c%96

**Comment by zerogu** [comment]
+1 有同样问题, 没切换umd模式

**Comment by bailicangdu** [comment]
@ice-musru @zerogu 希望提供一个demo帮助我们复现这个问题

**Comment by mursumomo** [comment]
> Hello @ice-musru. In order to facilitate location and troubleshooting, we need you to provide a realistic GitHub repository. 您好 @ice-musru, 为了方便定位和排查问题，我们需要您提供一个重现实例，请提供一个尽可能精简的 GitHub 仓库地址。

我再分析下，自己写了简单的demo，却没有复现

**Comment by mursumomo** [comment]
打扰了大佬，这是个乌龙。经排查，是我们自己的问题，动态引入的第三方sdk上的对象，在第二次进入子应用的时候，绑定在window对象上的sdk配置在上一次切出的时候已经销毁，但第二次进入的时候因为有缓存的缘故，并没有重新初始化加载sdk的资源。所以导致了window对象上不存在sdk该有的方法

**Comment by bailicangdu** [comment]
> 打扰了大佬，这是个乌龙。经排查，是我们自己的问题，动态引入的第三方sdk上的对象，在第二次进入子应用的时候，绑定在window对象上的sdk配置在上一次切出的时候已经销毁，但第二次进入的时候因为有缓存的缘故，并没有重新初始化加载sdk的资源。所以导致了window对象上不存在sdk该有的方法

ok
