### ISSUE TITLE
bundle size 太大了

### ISSUE THREAD

**Issue by sep2** [jd-opensource/micro-app#161]
## 背景
`micro-app/lib/index.esm.js` 现在占用了40kb, 但其实很多配置都是可以关掉的 (https://zeroing.jd.com/docs.html#/zh-cn/configure)

## 期望的效果

能否提供按需加载的功能, 比如开启shadowDOM: true的时候, 就把自定义样式隔离相关的代码tree shaking掉, 或者直接提供import effect形式的加载方案, 这样不需要的功能在使用方就不用引入了.

**Comment by sep2** [comment]
Is there any plan to support this?

**Comment by bailicangdu** [comment]
所有功能基本都汇集到customElement  micro-app元素，而元素对于任何按需加载方案都是一个巨大的副作用对象，元素什么时候以什么方式被使用都是不知道的，没办法做很好的优化
