### ISSUE TITLE
子应用内容缓存

### ISSUE THREAD

**Issue by qinaode** [jd-opensource/micro-app#162]
**1.问题描述**
 目前正在使用micro-app微前端框架开发一个多页签后台管理系统，基座应用和子应用使用的都是Vue+VueRouter。

 基座应用提供统一的菜单和页签。点击不同的菜单会打开不同的页签，每个页签可能来自不同的子应用。点击页签后可以进行内容的切换。多页签的初衷是希望用户打开过的页面默认情况下可以进行状态的保留。子应用通过keep-alive配置成功实现了路由页面组件的缓存。

目前标签页在同一子应用的路由间切换时页面状态能够保留。在不同子应用间的路由切换时，发现会因为子应用卸载而导致切换来自不同子应用的功能页签时，页面重新渲染导致页面之前的状态消失和数据重新加载。

**2.期望功能**
期望micro-app可以给开发者提供，在不同子应用间切换时，上一个子应用是否卸载的配置功能，让开发者可以手动控制应用的卸载。以满足上述多页签场景下的页面内容缓存。

![未命名文件](https://user-images.githubusercontent.com/3110595/143666030-00ff76aa-b9f6-4ac8-a6bc-cb22ce910ad0.png)

**Comment by bailicangdu** [comment]
我们会在12月9号左右发布v0.6.0版本，到时候会支持keep-alive功能

**Comment by bailicangdu** [comment]
已在0.6.0版本中支持，详情请查看：https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/keep-alive

**Comment by Kryzeno** [comment]
使用了keep-alive后 切换tab再次打开 会出现这个问题

![image](https://user-images.githubusercontent.com/7607957/146140158-f929bed4-e105-41d3-ac3f-a4699d74bee4.png)

**Comment by bailicangdu** [comment]
可以提供一个可以复现的demo仓库吗

**Comment by Kryzeno** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。

**Comment by Kryzeno** [comment]
@bailicangdu 我知道问题了 主应用这个路由地址也开启了keep-alive  会和主应用的keep-alive冲突  所以主应用的keep-alive关掉就没问题了

**Comment by shaojiankui** [comment]
你这个不会出现tab关闭不释放内存问题么。我是1.0.0beta^1.0.0-beta.4 不释放啊。。人麻了
