### ISSUE TITLE
基座是hash，子系统也是hash，vue-router该如何配置？

### ISSUE THREAD

**Issue by LoveqLRC** [jd-opensource/micro-app#163]
基座是hash，子系统也是hash，vue-router该如何配置？

**Comment by bailicangdu** [comment]
基座设置和文档中描述的一样，子应用参考 
![image](https://user-images.githubusercontent.com/20297227/143982318-9a9faf53-f6aa-4bc6-9fbd-f8d6654894db.png)

**Comment by bailicangdu** [comment]
https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/route?id=%e5%9f%ba%e7%a1%80%e8%b7%af%e7%94%b1

**Comment by LoveqLRC** [comment]
> 基座设置和文档中描述的一样，子应用参考 ![image](https://user-images.githubusercontent.com/20297227/143982318-9a9faf53-f6aa-4bc6-9fbd-f8d6654894db.png)

意思是说子应用添加多一个一级路由吗？ 图中的`home`组件空白文件即可？

**Comment by bailicangdu** [comment]
嗯，放一个router-view即可
```html
<template>
  <router-view />
</template>
```
