### ISSUE TITLE
Nuxt redirect跳转问题

### ISSUE THREAD

**Issue by qianqian05723** [jd-opensource/micro-app#166]
## 问题描述
> 问题的具体描述
Nuxtjs 子应用都配置了baseRoute，在middleware中服务端使用redirect跳转其他子应用时路由问题，因为是服务端所以window对象还不存在，请问有什么别的方法可以在服务端进行跳转吗？
## 复现步骤
1. middleware 登录判断
![image](https://user-images.githubusercontent.com/17306867/144179930-b8c74ebf-8d19-46ef-8c0e-272ef64ef222.png)

2. 实际情况redirect 路由跳转登录
![image](https://user-images.githubusercontent.com/17306867/144180062-decabfb8-7298-415f-8878-b69c6e8202c1.png)

3. 理想情况跳转路由
![image](https://user-images.githubusercontent.com/17306867/144180402-f593d5f0-648c-4e88-9be2-f287f27b2110.png)

## 环境信息
- micro-app版本：0.5.0
- 主应用前端框架&版本：nuxtjs latest
- 子应用前端框架&版本：nuxtjs latest
- 构建工具&版本：

**Comment by bailicangdu** [comment]
重定向的地址是相对地址吗

**Comment by qianqian05723** [comment]
> 重定向的地址是相对地址吗

嗯，是相对地址，这样是不是我要自动补全？

**Comment by bailicangdu** [comment]
要换成绝对地址

**Comment by bailicangdu** [comment]
我不知道你们具体项目和逻辑是什么样，但大体是这个思路

**Comment by qianqian05723** [comment]
> 我不知道你们具体项目和逻辑是什么样，但大体是这个思路

嗯，现在换成绝对路径可以了，感谢大佬！
