### ISSUE TITLE
官网文档无法正常访问

### ISSUE THREAD

**Issue by shiwanmenghuxiahuashan** [jd-opensource/micro-app#167]
官网文档无法正常访问
https://micro-zoe.github.io/micro-app/docs.html

如果我之前提过被删除，这次又发抱歉，但是真的需要看文档啊

**Comment by bailicangdu** [comment]
https://zeroing.jd.com/ 这个地址呢

**Comment by bailicangdu** [comment]
如果还是不行，换成4G网试一下

**Comment by shiwanmenghuxiahuashan** [comment]
> 如果还是不行，换成4G网试一下

电脑连的公司无线，经过提醒，使用手机访问两个地址都可以正常访问到官方文档。神奇呀~

电脑无法访问是因为资源文件加载不到
![image](https://user-images.githubusercontent.com/21036598/144366323-bac79495-1ab4-46b1-ac83-713d3e39b05e.png)

请问这个是我个例嘛？

**Comment by bailicangdu** [comment]
应该是你们公司网络的限制，文档直接使用了unpkg的地址

**Comment by shiwanmenghuxiahuashan** [comment]
https://unpkg.com/  的问题，不开梯子，或者开了梯子，梯子没有开全局代理，只开了黑名单代理，这个域就无法访问。
加载不到所需资源文件。

**Comment by shiwanmenghuxiahuashan** [comment]
> 应该是你们公司网络的限制，文档直接使用了unpkg的地址

感谢，费心了
