### ISSUE TITLE
在子应用中前端修改 window.location.href 改变地址的情况

### ISSUE THREAD

**Issue by CoderMonkie** [jd-opensource/micro-app#170]
存在在子应用中前端修改 `window.location.href`  改变地址的情况，
发现直接跳到目标地址，并不是在子应用中跳的，

文档中没有看到类似问题的相关内容，是否可以避免/控制呢

**Comment by bailicangdu** [comment]
没办法控制，micro-app不是iframe

**Comment by CoderMonkie** [comment]
@bailicangdu 嗯，好的知道了~谢谢

**Comment by sep2** [comment]
能出一个iframe全隔离的版本吗?

**Comment by bailicangdu** [comment]
> 能出一个iframe全隔离的版本吗?

这个很难，只有iframe可以做到全隔离

**Comment by sep2** [comment]
> > 能出一个iframe全隔离的版本吗?
> 
> 这个很难，只有iframe可以做到全隔离

现在都已经全自定义head和body，在加上劫持script和window以及dom操作函数了，再劫持一个iframe也还好了。可以给iframe里面注入劫持代码，达到js全隔离的效果。
