### ISSUE TITLE
rawWindow.__MICRO_APP_PROXY_WINDOW_  的覆盖问题

### ISSUE THREAD

**Issue by asiainfoliwei** [jd-opensource/micro-app#179]
![image](https://user-images.githubusercontent.com/24582028/144856189-e7af4893-cb89-4c50-ba2b-a60f6a78dc39.png)

看bindScope 的代码，子应用的window变量最终都在rawWindow.__MICRO_APP_PROXY_WINDOW__上，但是当多实例存在的情况下，是不是存在对rawWindow.__MICRO_APP_PROXY_WINDOW_的覆盖问题，比如目前同时存在两个子应用A和B，他们依次加载，比如A应用在他的proxyWindow set变量name, 在B应用加载之后，rawWindow.__MICRO_APP_PROXY_WINDOW_就变成了B应用的proxy window，这个时候A应用想取他的proxyWindow上的name是不是就变成undefined了

**Comment by bailicangdu** [comment]
每次执行js前都会重置，不会有问题
