### ISSUE TITLE
micro-app的 URL不能带参数么

### ISSUE THREAD

**Issue by zimo888** [jd-opensource/micro-app#18]
我请求的url 格式是 https://xxx.com?decorator=xxx, 加载的时候url的参数没了。

```
<micro-app name='page1' url="https://www.baidu.com?a=1&b=2" baseurl='/home'></micro-app>
```

**Comment by bailicangdu** [comment]
url只作为html的地址，没有其它作用，参数需要设置在浏览器地址上，详情可以查看 https://zeroing.jd.com/micro-app/docs.html#/zh-cn/route

**Comment by zimo888** [comment]
因为子是一个JSP页面，会请求一个接口返回JSP，需要带参数才能返回正确的 HTML，这种也不行么

**Comment by bailicangdu** [comment]
这种情况比较特殊，可以通过配置fetch，在请求地址上手动添加参数，具体参考这里 https://zeroing.jd.com/micro-app/docs.html#/zh-cn/other?id=_2%e3%80%81%e8%87%aa%e5%ae%9a%e4%b9%89fetch

**Comment by zimo888** [comment]
嗯，这样做应该是可以了，issues我先关了。
