### ISSUE TITLE
scoped_css.ts 里 CSSRule.type 被废弃的修改的建议

### ISSUE THREAD

**Issue by 534591395** [jd-opensource/micro-app#180]
由于 CSSRule.type 被废弃，改用 rule.constructor.name 判断规则类型。https://wiki.csswg.org/spec/cssom-constants。

scopedRule方法里判断方式改成例如：

  for (const rule of rules) {
    if (rule.constructor.name === "CSSStyleRule") {
      result += scopedStyleRule(rule as CSSStyleRule, prefix);
    } else if (rule.constructor.name === "CSSMediaRule") {
      result += scopedPackRule(rule as CSSMediaRule, prefix, "media");
    } else if (rule.constructor.name === "CSSSupportsRule") {
      result += scopedPackRule(rule as CSSSupportsRule, prefix, "supports");
    } else {
      result += rule.cssText;
    }
  }

这种方式是否可行

**Comment by a124779683** [comment]
你的来信我已经收到，稍晚我会阅读。
