### ISSUE TITLE
官方demo,执行start:main-vue3-vite后,无法加载vite和vue子应用

### ISSUE THREAD

**Issue by oblivioussing** [jd-opensource/micro-app#181]
## 问题描述
> 问题的具体描述
官方demo,执行start:main-vue3-vite后,访问vite子应用和vue子应用报错，但是其他子应用可以正常访问

## 复现步骤
1.下载官方demo,安装依赖
2.执行start:main-vue3-vite

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。
<img width="1392" alt="vite" src="https://user-images.githubusercontent.com/15011221/145330111-dd5437fb-dd7c-4291-942d-bb12dd2f9903.png">
<img width="1413" alt="WX20211209-113449@2x" src="https://user-images.githubusercontent.com/15011221/145330127-77e64f4c-f27b-44ad-92e6-6730d39ab7a4.png">

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。

官方demo

## 环境信息
- micro-app版本：
- 主应用前端框架&版本：
- 子应用前端框架&版本：
- 构建工具&版本：

**Comment by bailicangdu** [comment]
已修复，这是版本没有统一导致的，更新代码，重新安装children/vite、vue3的依赖即可
