### ISSUE TITLE
单词拼写错误 destory -> destroy，replaseUnmountOfNestedApp

### ISSUE THREAD

**Issue by XueMeijing** [jd-opensource/micro-app#182]
## 问题描述
> 问题的具体描述

## 复现步骤
1. 这个已经有过issue了，但是文档部分的单词还没有更新 https://github.com/micro-zoe/micro-app/issues/132
![image](https://user-images.githubusercontent.com/35559153/145341591-cbb89f22-5d56-4755-8696-f5eca3f82d77.png)

2.  另外这个单词里的replase是replace吗 replaseUnmountOfNestedApp
![image](https://user-images.githubusercontent.com/35559153/145341969-b5f9b068-9b39-43c8-ab22-ed68c6bed01d.png)

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。

## 环境信息
- micro-app版本：
- 主应用前端框架&版本：
- 子应用前端框架&版本：
- 构建工具&版本：

**Comment by bailicangdu** [comment]
👍

**Comment by bailicangdu** [comment]
已修复
