### ISSUE TITLE
问下怎么重新初始化keep-alive的子应用

### ISSUE THREAD

**Issue by Kryzeno** [jd-opensource/micro-app#185]
问下怎么重新初始化keep-alive的子应用  比如基座应用切换了主体企业信息 那么子应用需要重新初始化渲染  这个要怎么做到

**Comment by Kryzeno** [comment]
就是怎么控制主动销毁keep-alive的子应用

**Comment by Kryzeno** [comment]
还有就是 怎么主动销毁全部keep-alive的子应用

**Comment by bailicangdu** [comment]
目前不支持，我们周五(2021.12.17)会发布0.6.1版本，到时候会支持主动销毁子应用的功能，如果你不急，建议等待一下

**Comment by Kryzeno** [comment]
可以一次销毁所有子应用吗 这样就不用一个一个应用去操作

**Comment by bailicangdu** [comment]
可以

**Comment by bailicangdu** [comment]
新版本已发布，支持手动卸载应用，参考文档： https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/api?id=_8%e3%80%81unmountapp

**Comment by houlang-L** [comment]
vue2  使用keep-alive标签  包microapp子应用   重新进入有问题

**Comment by Kryzeno** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。
