### ISSUE TITLE
通过new Image 创建的dom 元素，调用document.body.appenchild 会出现逃逸

### ISSUE THREAD

**Issue by asiainfoliwei** [jd-opensource/micro-app#186]
## 问题描述
> 问题的具体描述
通过new Image 创建的dom 元素，调用document.body.appenchild()并没有插入到custom-componnets里面

## 复现步骤
```
var myImage = new Image(100, 200);
myImage.src = 'picture.jpg';
document.body.appendChild(myImage);
```

## 上传截图
![image](https://user-images.githubusercontent.com/24582028/146355135-6b6f7fd6-61a4-4eab-996b-4c419c0a0c65.png)

问题原因
![image](https://user-images.githubusercontent.com/24582028/146358541-aef23912-02b5-4dfc-bb78-6f88d5a2863b.png)
 目前看appendChild 并不属于捕获范围之内,通过createElement 方式创建的是ok的
 
 解决建议
 1. sandbox 中添加
```
 const imageProxy = new Proxy(Image, {
  construct: (Target, args): any => {
    Target.prototype.__MICRO_APP_NAME__ = getCurrentAppName();
    return new Target(...args);
  },
});
```

new Proxy中添加
```
get: (target: any, key: PropertyKey): unknown => {
  if (key === 'Image') {
       return imageProxy;
   }
}
```
或者
![image](https://user-images.githubusercontent.com/24582028/146362832-1aa94965-0384-42df-bd7f-4f52ce9d6932.png)
第二个判断添加appendChild

**Comment by asiainfoliwei** [comment]
我提一个mr @bailicangdu

**Comment by bailicangdu** [comment]
> 我提一个mr @bailicangdu

可以👍

**Comment by asiainfoliwei** [comment]
已提

**Comment by bailicangdu** [comment]
好的，我明天看一下
