### ISSUE TITLE
问下有个问题 就是同一个应用的路由跳转问题

### ISSUE THREAD

**Issue by Kryzeno** [jd-opensource/micro-app#188]
就是基座应用 控制一个子应用打开不同的路由页面 会出现这个问题
![image](https://user-images.githubusercontent.com/7607957/146475235-d2107327-934f-4743-831a-af55659d0345.png)
我想实现的是 能同时打开app的不同路由页面 上面的选项卡 也能来回切换这个app的页面 并且状态保持

**Comment by Kryzeno** [comment]
请问这个有实现思路和办法吗

**Comment by 617450941** [comment]
基座这里是不同的路由地址指向的是同一个组件

**Comment by Kryzeno** [comment]
基座这里是不同的路由地址指向的是同一个组件页面

**Comment by Kryzeno** [comment]
还有 如果按文档 https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/jump?id=%e6%96%b9%e5%bc%8f%e4%ba%8c%e3%80%81%e9%80%9a%e8%bf%87%e6%95%b0%e6%8d%ae%e9%80%9a%e4%bf%a1%e6%8e%a7%e5%88%b6%e8%b7%b3%e8%bd%ac 这里说的去实现 如果在子应用里面做了路由切换 那么keep-alive还能保证状态保持吗

**Comment by bailicangdu** [comment]
> 就是基座应用 控制一个子应用打开不同的路由页面 会出现这个问题 ![image](https://user-images.githubusercontent.com/7607957/146475235-d2107327-934f-4743-831a-af55659d0345.png) 我想实现的是 能同时打开app的不同路由页面 上面的选项卡 也能来回切换这个app的页面 并且状态保持

每个micro-app元素的name必须是全局唯一的，这个报错是因为name冲突了，把name值改一下就可以。同时渲染两个应用可以做到，但它们是两个独立的应用，状态不共享。

**Comment by bailicangdu** [comment]
> 还有 如果按文档 https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/jump?id=%e6%96%b9%e5%bc%8f%e4%ba%8c%e3%80%81%e9%80%9a%e8%bf%87%e6%95%b0%e6%8d%ae%e9%80%9a%e4%bf%a1%e6%8e%a7%e5%88%b6%e8%b7%b3%e8%bd%ac 这里说的去实现 如果在子应用里面做了路由切换 那么keep-alive还能保证状态保持吗

micro-app的keep-alive是应用级别的，只有正在活动的页面才会保留状态，应用内部路由切换保留状态由应用自行控制，比如使用vue 的keep-alive组件
