### ISSUE TITLE
微应用监听不到路由变化

### ISSUE THREAD

**Issue by gaokunpen** [jd-opensource/micro-app#189]
子应用无法监听路由变化

**Comment by bailicangdu** [comment]
不同应用之间操控路由，其他应用是无法监听的

**Comment by bailicangdu** [comment]
最常见的场景是通过基座跳转路由，子应用没有变化

**Comment by bailicangdu** [comment]
参考 https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/jump

**Comment by shangwfa** [comment]
子应用路由变化，主应用监听不到，是有什么特殊处理么
