### ISSUE TITLE
@JoMartinezZhu 侧边栏路由指向同一个组件就行了

### ISSUE THREAD

**Issue by Kryzeno** [jd-opensource/micro-app#190]
@JoMartinezZhu 侧边栏路由指向同一个组件就行了

_Originally posted by @bailicangdu in https://github.com/micro-zoe/micro-app/issues/143#issuecomment-966211358_

我这里指向同一个组件会出现重复加载的问题
[micro-app] app app1: app name conflict, an app named app1 is running

**Comment by bailicangdu** [comment]
这是url冲突了，代码贴一下呢

**Comment by Kryzeno** [comment]
![image](https://user-images.githubusercontent.com/7607957/146484633-f9dc8434-6873-442e-aa8e-51d5a845d5b2.png)
![image](https://user-images.githubusercontent.com/7607957/146484655-e90cf508-d08f-49b4-b70c-8903bc9635d2.png)

**Comment by bailicangdu** [comment]
去掉keep-alive还会出现问题吗

**Comment by Kryzeno** [comment]
@bailicangdu 去掉还是会的

**Comment by bailicangdu** [comment]
我们在 vue2.6 + vue-router3.5 环境下试了，但没有复现问题，可以提供一个简易的demo仓库吗

**Comment by Kryzeno** [comment]
@bailicangdu 能否私下发下代码给你调试

**Comment by bailicangdu** [comment]
嗯，可以

**Comment by Kryzeno** [comment]
@bailicangdu 微信可以吗

**Comment by Kryzeno** [comment]
有什么联系方式

**Comment by bailicangdu** [comment]
发我邮箱吧 1264889788@qq.com

**Comment by bailicangdu** [comment]
压缩后的代码应该不大吧

**Comment by Kryzeno** [comment]
@bailicangdu 发你邮箱了

**Comment by Kryzeno** [comment]
@bailicangdu 项目我是用cnpm装的依赖

**Comment by bailicangdu** [comment]
这里每个url应该对应一个不同的name
![image](https://user-images.githubusercontent.com/20297227/147748080-a7b4e783-d42e-4b6e-ba39-1a60961fefd0.png)

**Comment by bailicangdu** [comment]
这个项目和官网demo一样，多个侧边栏地址指向同一个应用，这种情况只能通过基座下发通知，告知子应用进行跳转

**Comment by bailicangdu** [comment]
参考代码 https://github.com/micro-zoe/micro-app-demo ，演示地址 http://www.micro-zoe.com/main-vue2/

**Comment by Kryzeno** [comment]
没其他方便点的办法了吗

**Comment by bailicangdu** [comment]
可以尝试在基座执行window.history.pushState控制子应用跳转  https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/jump?id=%e6%96%b9%e5%bc%8f%e4%b8%80%e3%80%81windowhistory

**Comment by bailicangdu** [comment]
如果子应用是vue3的话 history.pushState就不好用了

**Comment by Kryzeno** [comment]
如果采用通过数据通信控制跳转 像我这种项目 在什么时机去初始化加载这个应用好 因为侧边栏每个菜单总要指定一个页面才行

**Comment by Kryzeno** [comment]
通过子应用通讯的方式能改变子应用的路由 但是怎么解决主应用 不同路由页面重复加载应用的问题 因为这边的主应用系统是一个路由一个页面这样定义的  那么每个页面都会有个micro-app定义 不这样做的话 就算通过下发指令给应用切换路由页面 也无法渲染到主应用的页面上 页面不加micro-app的话

**Comment by bailicangdu** [comment]
你的代码中不是将多个路由指向同一个.vue页面了吗，在这几个路由切换时，页面不会重新卸载渲染，而是保持不变，所以micro-app子应用也保持不变，此时你是可以知道路由变化了的，获取到最新的url地址通知子应用跳转对应的页面就行了。

**Comment by 617450941** [comment]
有没办法做到 主应用多个路由多个页面 指向同一个子应用 的不同路径  而不报重复加载

**Comment by 617450941** [comment]
有没办法做到 主应用多个路由多个页面 指向同一个子应用 的不同路径 而不报重复加载的错误

**Comment by Kryzeno** [comment]
有没办法做到 主应用多个路由多个页面 指向同一个子应用 的不同路径 而不报重复加载的错误  由框架去判断这个应用是否已经加载了

**Comment by bailicangdu** [comment]
如果是同时渲染，无法做到，每个name只能对应一个应用

**Comment by Kryzeno** [comment]
如果通过子应用通讯的方式改变子应用的路由 好像keep-alive就失效了吧？  实测是失效的

**Comment by bailicangdu** [comment]
不会，失效说明你使用的方式错了

**Comment by Kryzeno** [comment]
![image](https://user-images.githubusercontent.com/7607957/147813624-1751c729-467d-4d1b-befc-34c36bacf586.png)
这边是这样跟子应用通讯 切换子应用路由的

**Comment by bailicangdu** [comment]
具体表现是什么？

**Comment by Kryzeno** [comment]
通过setData通知子应用切换路由的时候 上一个页面的状态会丢失 也就是micro-app里的keep-alive属性无效

**Comment by bailicangdu** [comment]
很好的问题，micro-app的keep-alive是应用级别的，它只会保留当前正在活动的页面状态，以保证应用被卸载和重新渲染时的状态保留，如果想要缓存具体的页面或组件，需要使用子应用框架的能力，如：vue的keep-alive

**Comment by Kryzeno** [comment]
那这个keep-alive就是只能适用不同应用切换的状态保持  如果是同一个应用切换不同的路由那么keep-alive还得在应用内实现

**Comment by bailicangdu** [comment]
是的，这本身就是一种取巧的实现，前端框架内部如何卸载组件是否缓存状态是一个黑盒

**Comment by 617450941** [comment]
另外问下 子应用能动态加载初始化吗 而不是在页面内去写死定义一个<micro-app></micro-app>

**Comment by Kryzeno** [comment]
![image](https://user-images.githubusercontent.com/7607957/147815398-63412e56-a0a8-4821-860e-7b80ba9531f3.png)
另外问下 子应用能动态加载初始化吗 而不是在页面内去写死定义一个

**Comment by Kryzeno** [comment]
动态加载 对多应用等比较复杂的情况下 感觉这样会比较灵活

**Comment by bailicangdu** [comment]
可以

**Comment by Kryzeno** [comment]
这个现有的版本可以做到吗
