### ISSUE TITLE
加载子应用，子应用是react  样式库是antd。antd的下拉框 都是 加载到body上，都应该是 micro-app-body里面。但是偶发的情况是，加载到了基座的body了

### ISSUE THREAD

**Issue by stewinged** [jd-opensource/micro-app#191]
## 问题描述
加载子应用，子应用是react 样式库是antd。antd的下拉框 都是 加载到body上，都应该是 micro-app-body里面。但是偶发的情况是，加载到了基座的body了

## 复现步骤
1.偶发的

## 上传截图
![image](https://user-images.githubusercontent.com/20498227/146488790-70e9a933-696b-4002-94f7-b55424b20d1b.png)
![image](https://user-images.githubusercontent.com/20498227/146490652-739a1851-af5c-41e0-b448-6d3f9327886c.png)

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。

## 环境信息
最新版

**Comment by stewinged** [comment]
基座也是用的ant，猜测原因
antd的函数 调用的是基座的antd的函数，所以把样式注到了，基座的body。js沙箱有问题。

**Comment by bailicangdu** [comment]
ok，我们已经了解，你可以关闭样式隔离暂时解决这个问题 https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/configure?id=disablescopecss

**Comment by stewinged** [comment]
> 

刚才可以稳定复现这个问题了，就是同一个应用地址，但是在菜单栏里面配了两个入口，一个入口点击，没问题，样式也没问题，当加载第二个入口，样式就有问题了。distory true也不管用。

**Comment by mursumomo** [comment]
也遇到同样的问题，目前的做法是关闭样式隔离

**Comment by bailicangdu** [comment]
我们会在下个大版本0.7.0中解决这个问题，请耐心等待

**Comment by quhaisi** [comment]
我的基座应用没有用ant，子应用的ant的弹窗都会在基座中插入并且没有样式，关闭样式隔离也没有解决。

**Comment by stewinged** [comment]
> 
0.7.0修复了吗？昨天出现一个分问题。

**Comment by loycoder** [comment]
> 我们会在下个大版本0.7.0中解决这个问题，请耐心等待

现在这个问题修复了吗？最新版： 1.0.0-rc.3 依然会出现

**Comment by bailicangdu** [comment]
> > 我们会在下个大版本0.7.0中解决这个问题，请耐心等待
> 
> 现在这个问题修复了吗？最新版： 1.0.0-rc.3 依然会出现

这个问题已经修复过，不确定是不是同一个原因导致的，可以新提一个iusse，方便我们跟踪解决
