### ISSUE TITLE
主应用和子应用同为vite，模拟部署主应用正常打开，子应用加载不出

### ISSUE THREAD

**Issue by zandko** [jd-opensource/micro-app#193]
## 问题描述
> 问题的具体描述

## 上传截图

![image](https://user-images.githubusercontent.com/37948383/146634879-91ec277c-566a-42e6-aefd-50e3a0b0b094.png)

![image](https://user-images.githubusercontent.com/37948383/146634895-5cde5765-2a4f-4bc5-87fd-d26e4f79c0ec.png)
![Uploading image.png…]()
<img width="1152" alt="image" src="https://user-images.githubusercontent.com/37948383/146634916-64bb3b53-42b2-4a64-8304-62792308203b.png">
![image](https://user-images.githubusercontent.com/37948383/146634915-9b0e4722-37f6-4fca-8794-15b95044827c.png)

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。

## 环境信息
- micro-app版本：0.6
- 主应用前端框架&版本：vue3
- 子应用前端框架&版本: vue3
- 构建工具&版本：vite

**Comment by bailicangdu** [comment]
资源没找到，配置出问题了吧，vite.config.js和nginx配置截图发全一点看一下呢

**Comment by zandko** [comment]
![CleanShot-2021-12-18-16 39 11@2x](https://user-images.githubusercontent.com/37948383/146635130-e02b0fe4-4231-40e3-ad30-f6f78bad5324.png)
![CleanShot-2021-12-18-16 41 29@2x](https://user-images.githubusercontent.com/37948383/146635166-34ae0cc9-3e14-4828-8611-bf7dc03696cc.png)

**Comment by bailicangdu** [comment]
从截图里看不出问题，可以提供一个简易的demo吗

**Comment by zandko** [comment]
> 从截图里看不出问题，可以提供一个简易的demo吗

好的，代码已上传：https://github.com/zandko/micro-issuse-193

**Comment by bailicangdu** [comment]
子应用vite.config.js这里改一下，nginx也要更新一下

**Comment by bailicangdu** [comment]
![image](https://user-images.githubusercontent.com/20297227/146638535-c37902c7-eee8-4463-83b2-78f9d93f9559.png)

**Comment by zandko** [comment]
> ![image](https://user-images.githubusercontent.com/20297227/146638535-c37902c7-eee8-4463-83b2-78f9d93f9559.png)

大佬行不通 还是无法加载子应用
![CleanShot-2021-12-18-19 08 19@2x](https://user-images.githubusercontent.com/37948383/146638825-01170102-20ee-4471-b9ec-777a287e2e42.png)
![CleanShot-2021-12-18-19 08 54@2x](https://user-images.githubusercontent.com/37948383/146638834-8dcc1f83-a2ab-4fd9-af61-b2dbacd48034.png)

**Comment by bailicangdu** [comment]
不会吧，我明天再看一下

**Comment by bailicangdu** [comment]
nginx的配置问题，我在服务器上试了一下，可以了

**Comment by bailicangdu** [comment]
![image](https://user-images.githubusercontent.com/20297227/146669439-54025912-7cc9-4dbe-88ae-05afdcddbeff.png)

**Comment by bailicangdu** [comment]
附上nginx的配置以供参考 @zandko 
```
server {
  listen       80;
  server_name  www.micro-zoe.com micro-zoe.com;

  location / {
    root /root/mygit/micro-zoe;
    index index.php index.html index.htm;
    # add_header Cache-Control no-cache;
    add_header Access-Control-Allow-Origin *;
    if ( $request_uri ~* ^.+.(js|css|jpg|png|gif|tif|dpg|jpeg|eot|svg|ttf|woff|json|mp4|rmvb|rm|wmv|avi|3gp)$ ){
      add_header Cache-Control max-age=7776000;
      add_header Access-Control-Allow-Origin *;
    }
  }

  location /childAppMerchant {
    root /root/mygit/micro-zoe;
    add_header Access-Control-Allow-Origin *;
    if ( $request_uri ~* ^.+.(js|css|jpg|png|gif|tif|dpg|jpeg|eot|svg|ttf|woff|json|mp4|rmvb|rm|wmv|avi|3gp)$ ){
      add_header Cache-Control max-age=7776000;
      add_header Access-Control-Allow-Origin *;
    }
    try_files $uri $uri/ /childAppMerchant/index.html;
  }

  location /main-issue-193 {
    root /root/mygit/micro-zoe;
    add_header Access-Control-Allow-Origin *;
    if ( $request_uri ~* ^.+.(js|css|jpg|png|gif|tif|dpg|jpeg|eot|svg|ttf|woff|json|mp4|rmvb|rm|wmv|avi|3gp)$ ){
      add_header Cache-Control max-age=7776000;
      add_header Access-Control-Allow-Origin *;
    }
    try_files $uri $uri/ /main-issue-193/index.html;
  }
  
  error_page 404 /404.html;
      location = /40x.html {
  }

  error_page 500 502 503 504 /50x.html;
      location = /50x.html {
  }
}
```

**Comment by zandko** [comment]
> 附上nginx的配置以供参考 @zandko
> 
> ```
> server {
>   listen       80;
>   server_name  www.micro-zoe.com micro-zoe.com;
> 
>   location / {
>     root /root/mygit/micro-zoe;
>     index index.php index.html index.htm;
>     # add_header Cache-Control no-cache;
>     add_header Access-Control-Allow-Origin *;
>     if ( $request_uri ~* ^.+.(js|css|jpg|png|gif|tif|dpg|jpeg|eot|svg|ttf|woff|json|mp4|rmvb|rm|wmv|avi|3gp)$ ){
>       add_header Cache-Control max-age=7776000;
>       add_header Access-Control-Allow-Origin *;
>     }
>   }
> 
>   location /childAppMerchant {
>     root /root/mygit/micro-zoe;
>     add_header Access-Control-Allow-Origin *;
>     if ( $request_uri ~* ^.+.(js|css|jpg|png|gif|tif|dpg|jpeg|eot|svg|ttf|woff|json|mp4|rmvb|rm|wmv|avi|3gp)$ ){
>       add_header Cache-Control max-age=7776000;
>       add_header Access-Control-Allow-Origin *;
>     }
>     try_files $uri $uri/ /childAppMerchant/index.html;
>   }
> 
>   location /main-issue-193 {
>     root /root/mygit/micro-zoe;
>     add_header Access-Control-Allow-Origin *;
>     if ( $request_uri ~* ^.+.(js|css|jpg|png|gif|tif|dpg|jpeg|eot|svg|ttf|woff|json|mp4|rmvb|rm|wmv|avi|3gp)$ ){
>       add_header Cache-Control max-age=7776000;
>       add_header Access-Control-Allow-Origin *;
>     }
>     try_files $uri $uri/ /main-issue-193/index.html;
>   }
>   
>   error_page 404 /404.html;
>       location = /40x.html {
>   }
> 
>   error_page 500 502 503 504 /50x.html;
>       location = /50x.html {
>   }
> }
> ```

感谢大佬，已找到原因
