### ISSUE TITLE
能否在菜单多标签下，实现各子应用共用？

### ISSUE THREAD

**Issue by tangdu** [jd-opensource/micro-app#197]
现在有套管理系统是基于Vue2 ElementUI

需求如下：
1、各子应用独立开发时有自己路由【都hash路由】
2、基应用用于合并子应用，业务统一使用基应用【都hash路由】
在实现多标签情况下，是不是每个tab就创建一个micro-app,并且name不一样（动态JS创建component）；类似于iframe嵌入？
现在不太了解基于micro能否实现此功能。

**Comment by bailicangdu** [comment]
功能是肯定可以实现的，每个tab对应一个micro-app要看实际情况，如果是多个tab对应一个子应用，则只需要创建一次，另外基座推荐使用history路由

**Comment by bailicangdu** [comment]
参考案例  https://github.com/micro-zoe/micro-app-demo

**Comment by RedBuil** [comment]
可以的
