### ISSUE TITLE
样式污染

### ISSUE THREAD

**Issue by ycxfun** [jd-opensource/micro-app#199]
基座应用使用了vue3 + element-plus + vite，子应用使用的 element-ui，基座应用的element-plus会影响子应用的element-ui样式，有好的解决方案吗？

**Comment by bailicangdu** [comment]
基座的设定是可以统筹全局，所以样式是可以影响到子应用，如果遇到基座样式影响到子应用，建议手动修改样式，或者开启vue的scoped
