### ISSUE TITLE
vue example 不能正常运行

### ISSUE THREAD

**Issue by Robinsir** [jd-opensource/micro-app#2]
1. clone 代码
2. npm i
3. npm run start 提示
```
* @micro-zoe/micro-app in ./src/main.js, ./node_modules/_cache-loader@4.1.0@cache-loader/dist/cjs.js??ref--12-0!./node_modules/_babel-loader@8.2.2@babel-loader/lib!./node_modules/_cache-loader@4.1.0@cache-loader/dist/cjs.js??ref--0-0!./node_modules/_vue-loader@15.9.7@vue-loader/lib??vue-loader-options!./src/pages/react16.vue?vue&type=script&lang=js&

To install it, you can run: npm install --save @micro-zoe/micro-app
```
4. 运行：npm install --save @micro-zoe/micro-app 还是报3的错误

**Comment by bailicangdu** [comment]
安装依赖使用 npm run bootstrap

**Comment by lileilei** [comment]
> 安装依赖使用 npm run bootstrap

npm run bootstrap安装也不行的，需要删除 children 项目的lock 文件，否则还是会找http://registry.m.jd.com/ 源的。

**Comment by sophiehu36** [comment]
用npm run bootstrap安装依赖还是有问题，反复报错，npm install --save @micro-zoe/micro-app以后还是如此。
`This dependency was not found:`

`* @micro-zoe/micro-app in ./src/main.js, ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/pages/react16.vue?vue&type=script&lang=js&`

`To install it, you can run: npm install --save @micro-zoe/micro-app `

**Comment by bailicangdu** [comment]
开发环境@micro-zoe/micro-app指向的是本地文件lib/index.esm.js，你有运行yarn build 或yarn build:watch 吗
![image](https://user-images.githubusercontent.com/20297227/127293205-d53d9d75-ad9b-406a-af60-921e436d9b4b.png)
@sophiehu36

**Comment by sophiehu36** [comment]
刚刚尝试了一下，yarn build和 yarn build:watch也都会报错：`$ NODE_ENV='development' rollup -c -w
'NODE_ENV' 不是内部或外部命令，也不是可运行的程序
或批处理文件。` @bailicangdu

**Comment by bailicangdu** [comment]
@sophiehu36 我的问题，cross-env没添加，重新拉一下代码试试呢

**Comment by sophiehu36** [comment]
可以运行了，感谢大佬 @bailicangdu

**Comment by bailicangdu** [comment]
应该的，欢迎提问题和PR呀@sophiehu36
