### ISSUE TITLE
使用 emotion 样式问题

### ISSUE THREAD

**Issue by chenxtdo** [jd-opensource/micro-app#200]
## 问题描述

emotion 在生产环境用  insertRule API 来生成样式。micro-app 没做拦截，在样式表没有增加 micro-app[name=] 的前缀 ，所以样式隔离的时候会有问题。

https://github.com/emotion-js/emotion/issues/1248
https://developer.mozilla.org/pl/docs/Web/API/CSSStyleSheet/insertRule

**Comment by bailicangdu** [comment]
ok，我们会在后续版本中进行修复

**Comment by chenxtdo** [comment]
@bailicangdu  预计什么时候修复？

**Comment by qiuzixu** [comment]
现在修复了吗
