### ISSUE TITLE
主应用同一个页面加载不同子应用组件的路由设置问题

### ISSUE THREAD

**Issue by icksky** [jd-opensource/micro-app#201]
主要是子/主应用路由设置的问题.

背景: 主应用有两个页面 `/main/page1` 和 `/main/page2`, 子应用 `A` 有一个组件页面 `/page-a` (**非根路由**), 子应用 `B` 有一个组件页面 `/page-b`.
> 场景1: 同时在 `page1` 渲染子应用 `A` / `B`
> 1. 主应用的 `/main/page1` 是不是要改为 `/main/page1/:sub?`
> 2. `micro-app` 的 baseurl 是不是要设置为 `/main/page1`
> 3. 访问 `/main/page1/page-a` 只能渲染子应用 A , 子应用 B 无法渲染
---
> 场景2: 分别在 `page1` / `page2` 都渲染子应用 `A`
> 1. `page2` 是不是也需要改为 `/main/page2/:sub?` 的形式
> 2. `micro-app` 的 `baseurl` 是不是要设置为 `/main/page2`

使用上感觉子应用跟主应用的路由耦合较大, 无法设置 `url` 为 `http://localhost:8081/page-a` 来直接访问到子应用指定页面.

所以我想知道:
1. 主应用如何同时渲染两个子路由不同的子应用
2. 主应用的路由是否都得配置一个可选参数(`:sub?`)来传递子应用的路由, 从而能渲染指定的子应用页面

可能是我的使用场景偏向于作为组件形式加载, 而不是整个页面的子应用吧

感谢~

**Comment by bailicangdu** [comment]
你理解的都是对的，如果想要在同一个页面渲染两个应用的不同页面，需要修改子应用的路由，让其符合url地址，所有应用都是基于浏览器url地址匹配对应的路由并渲染。/main/page2/:sub 的形式主要为了设置宽泛路由，防止/main/page2/xxx页面404。

**Comment by bailicangdu** [comment]
其实你这样的需求webpack5联邦模块更适合，micro-app更侧重于应用级别的

**Comment by icksky** [comment]
> 其实你这样的需求webpack5联邦模块更适合，micro-app更侧重于应用级别的

了解了, 主要使用场景还是应用级别的 所以暂时没用联邦模块, 想着直接用 micro-app 来实现, 方便主应用跟子应用的通信
