### ISSUE TITLE
文档示例代码错误

### ISSUE THREAD

**Issue by PengBoUESTC** [jd-opensource/micro-app#202]
import microApp from '@micro-zoe/micro-app'

microApp.start({
  inline: true, // 默认值false
  destory: true, // 默认值false
  disableScopecss: true, // 默认值false
  disableSandbox: true, // 默认值false
  macro: true, // 默认值false
  shadowDOM: true, // 默认值false
})

destory ==> destroy

**Comment by bailicangdu** [comment]
ok, thanks
