### ISSUE TITLE
使用angular的版本为13作为子应用匹配的时候页面会一直刷新

### ISSUE THREAD

**Issue by liulovegame** [jd-opensource/micro-app#203]
## 问题描述
> 按照文档使用说明，使用angular的版本13作为子应用的时候，路由匹配到了会一直自己重复刷新页面，主应用不管是13或者12都是呈现会这样的情况，当子应用版本降为12的时候就不会了。

## 复现步骤
1. 启动项目，切换至路由 /my-page，如果是路由/my-micro就会正常加载

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。

## 复现仓库
> https://github.com/liulovegame/micro-angular

## 环境信息
- micro-app版本：^0.6.2
- 主应用前端框架&版本：angular v13.0.0
- 子应用前端框架&版本：angular v13.0.0 and angular v12.1.2
- 构建工具&版本：angular-cli

**Comment by bailicangdu** [comment]
好的，我看一下

**Comment by mewangbin** [comment]
> 好的，我看一下

现在是只有你一个人在维护的吗？

**Comment by bailicangdu** [comment]
> > 好的，我看一下
> 
> 现在是只有你一个人在维护的吗？

是的，我们正在寻找可以一起维护的人员，包括公司内部或外部的

**Comment by liulovegame** [comment]
@bailicangdu 我想问下子应用嵌入主应用后子应用的代码是被隔离的，有什么办法能访问到吗，有些时候想定位下子应用引发的错误都不好定位。

**Comment by bailicangdu** [comment]
> @bailicangdu 我想问下子应用嵌入主应用后子应用的代码是被隔离的，有什么办法能访问到吗，有些时候想定位下子应用引发的错误都不好定位。

可以设置inline模式，方便调试 https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/configure?id=inline

**Comment by liulovegame** [comment]
> > @bailicangdu 我想问下子应用嵌入主应用后子应用的代码是被隔离的，有什么办法能访问到吗，有些时候想定位下子应用引发的错误都不好定位。
> 
> 可以设置inline模式，方便调试 https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/configure?id=inline

内联引入在Sources不能断点，感觉也不是很方便调试哦。

**Comment by sxhieen** [comment]
我试过主应用和子应用都为Angular 13.3.0时，不会出现一直刷新的问题

**Comment by bailicangdu** [comment]
> 我试过主应用和子应用都为Angular 13.3.0时，不会出现一直刷新的问题

angular13使用type module，导致沙箱失效

**Comment by sxhieen** [comment]
> > 我试过主应用和子应用都为Angular 13.3.0时，不会出现一直刷新的问题
> 
> angular13使用type module，导致沙箱失效

有什么好的解决方法吗

**Comment by bailicangdu** [comment]
@sxhieen 目前没有，我们正在尝试一些解决方案

**Comment by m310851010** [comment]
> 

我通过修改angular依赖包解决，使打包后的script非module方式加载

具体修改文件:  `node_modules/@angular-devkit/build-angular/src/utils/index-file.js`

注释掉一行代码  `attrs.push('type="module"');`

希望对你有帮助

**Comment by eclipseHOOT** [comment]
> attrs.push('type="module"');

angular13会一直有刷新问题，就是两个都是ssr渲染的时候
