### ISSUE TITLE
当子应用是angular，并且使用rxjs的时候，组件页面绑定数据不会刷新，且取消订阅报错。

### ISSUE THREAD

**Issue by mewangbin** [jd-opensource/micro-app#204]
1.主应用和子应用都采用angular12，并且在app.component.ts中监听数据：
`ngOnInit(): void {
    window.microApp?.addDataListener((data: Record<string, unknown>) => {
      if (data.type) {
        // 路由
        if (data.type === 'route') {
          if (data.message !== this.router.url) {
            this.router.navigate([data.message]);
          }
        } else {
          // 其他
          this.appService.setData(data);
        }
      }
    }, true);
  }`
其中appService是一个服务，这个服务的作用很简单，就是存储主应用发送过来的数据（除了路由跳转之外）
`import { BehaviorSubject } from 'rxjs';
import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root',
})
export class AppService {
  private data$ = new BehaviorSubject<{}>({});

  constructor() {}

  getData$(): BehaviorSubject<{}> {
    return this.data$;
  }

  setData(data: {}): void {
    this.data$.next({ ...data });
  }
}`
2.子应用中某个组件，订阅：
`import { Component, OnInit, OnDestroy } from '@angular/core';
import { AppService } from '@App_SERVICE';
import { Subscription } from 'rxjs';

@Component({
  selector: 'app-abc',
  templateUrl: './abc.component.html',
  styleUrls: ['./abc.component.less'],
})
export class AbcComponent implements OnInit, OnDestroy {
  message: string = '';

  data$!: Subscription;

  constructor(private appService: AppService) {}

  ngOnDestroy(): void {
    console.log('222');
    this.data$.unsubscribe();
  }

  ngOnInit(): void {
    console.log('111');
    this.data$ = this.appService.getData$().subscribe((data) => {
      this.message = data['message'];
    });
  }

  onClickMe() {
    this.message = 'clickMe';
  }
}`
3.目前发现问题：

- 在切换路由，控制台打印 111，222||222，ngOnInit只执行一次，导致ngOnDestroy 执行时候，this.data$ undefined
- 主应用发送数据后， this.data$ = this.appService.getData$().subscribe能拿到数据，但页面绑定的{{message}}并不能刷新。

是否是我写法有问题，求帮助，感谢！

**Comment by mewangbin** [comment]
好的.
我已经提交了.
项目地址:https://github.com/mewangbin/test-micro-app

**Comment by bailicangdu** [comment]
好的，我们会定位问题并尽快修复

**Comment by mewangbin** [comment]
关于前面提的angular组件的生命周期事件执行问题，是否有些许进展。

**Comment by bailicangdu** [comment]
抱歉，这几天忙着重构的事情，刚有空看，message修改后不更新是因为在angular区域外调用了组件内部的代码(基座、子应用属于不同的angular区域)，这时候需要明确调用更改检测，否则angular不知道状态发生了改变，具体方式如下：
![image](https://user-images.githubusercontent.com/20297227/148034133-dab5ab0f-1e0f-4b5a-9024-bb01dece1c05.png)

**Comment by bailicangdu** [comment]
另外一个问题不属于微前端范围了
