### ISSUE TITLE
子应用引用了百度地图,主应用加载子应用时报跨域问题

### ISSUE THREAD

**Issue by wangxm87** [jd-opensource/micro-app#208]
子应用用的react umi脚手架,在document.ejs文件中引入百度地图的api,主应用加载子应用时fetch百度地图的api报跨域错误,截图如下。请问这种情况该如何解决?
<img width="698" alt="WechatIMG153" src="https://user-images.githubusercontent.com/24665567/147797721-efa17f52-8a85-482e-a6ce-f3759a1c15d4.png">
<img width="264" alt="WechatIMG154" src="https://user-images.githubusercontent.com/24665567/147797724-eb317a01-a1c6-406e-9bd6-8bc7dec9b96e.png">

**Comment by bailicangdu** [comment]
把这个文件放在主应用中引用或者下载到本地

**Comment by whhlulu** [comment]
解决了吗

**Comment by iYogic2** [comment]
按此操作 do like this:  https://github.com/micro-zoe/micro-app/issues/1009
