### ISSUE TITLE
加载子项目时报错 [micro-app from runScript] app app:  TypeError: Cannot redefine property: $router

### ISSUE THREAD

**Issue by baguosiji** [jd-opensource/micro-app#210]
![image](https://user-images.githubusercontent.com/27269213/147845961-64425bec-549c-41bb-85f7-ea5bae23fca4.png)

**Comment by WestarkMFF** [comment]
+1

我会尽快提供一个 精简repo

**Comment by baguosiji** [comment]
@WestarkMFF  vue-router 多次引用 或者vue多次引用 多引用的删了就好了

**Comment by WestarkMFF** [comment]
> @WestarkMFF vue-router 多次引用 或者vue多次引用 多引用的删了就好了

我不是这个场景，我是父子项目共享了一个 dll，不要把 vue 扔到 dll 里面就好了

**Comment by wangjieCode** [comment]
你们的问题解决了么
