### ISSUE TITLE
父应用vite vue3 开启 history 子vite vue3 hash模式应用路由

### ISSUE THREAD

**Issue by zandko** [jd-opensource/micro-app#211]
## 问题描述
> 路由地址无法带参数，带参数找不到路由

## 复现仓库
> 官方demo micro-app-demo

## 环境信息
- micro-app版本：latest
- 主应用前端框架&版本：vue3
- 子应用前端框架&版本：vue3
- 构建工具&版本：vite

**Comment by bailicangdu** [comment]
案例逻辑写的有问题，稍后会进行修改

**Comment by zandko** [comment]
> 案例逻辑写的有问题，稍后会进行修改

大佬可否提供个微信，有些问题想要请教

**Comment by zandko** [comment]
> 案例逻辑写的有问题，稍后会进行修改

大佬修改时，可否加入左侧菜单点击进入同一子应用和keepalive的一些demo

**Comment by moka-erb** [comment]
keepalive+vite 好多问题。 希望出个demo

**Comment by moka-erb** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
