### ISSUE TITLE
在使用 driver.js 库创建元素时候没被拦截到

### ISSUE THREAD

**Issue by chenxtdo** [jd-opensource/micro-app#212]
<img width="803" alt="image" src="https://user-images.githubusercontent.com/9393714/148025902-401647e5-dc60-4a33-a9e8-d52124ac628f.png">

https://github.com/kamranahmedse/driver.js/blob/4a0247ee25ba4f235bbf87434e9217c50619a1b8/src/common/utils.js#L11

查看上图，框架使用firstChild，返回元素对象，此事元素对象上面没有 __MICRO_APP_NAME__， appendChild 的时候创建到外层 body 上，可这时候的样式还在子应用的隔离中。

**Comment by bailicangdu** [comment]
innerHTML目前无法拦截

**Comment by chenxtdo** [comment]
是否尝试可以拦截firstChild，lastChild ？

**Comment by bailicangdu** [comment]
可以做到，但代价太大，每个元素都要拦截

**Comment by chenxtdo** [comment]
```
                          const storeCreateElement =
                            Document.prototype.createElement;
                          Document.prototype.createElement = function (
                            tagName: string,
                            options?: ElementCreationOptions
                          ) {
                            const element = storeCreateElement.call(
                              this,
                              tagName,
                              options
                            );
                            return new Proxy(element, {
                              get: (
                                target: HTMLElement,
                                key: PropertyKey
                              ): unknown => {
                                const r = Reflect.get(target, key);
                                if (r instanceof HTMLElement) {
                                  r.__MICRO_APP_NAME__ =
                                    element.__MICRO_APP_NAME__;
                                }
                                return r;
                              },
                            });
```


可以尝试在 createElement 的时候进行代理，然后把自身挂载 Proxy 下， 在其他地方判断下。

**Comment by chenxtdo** [comment]
可以在 createElement 的时候做个代理，把原对象再挂在 Proxy 对象下， 在使用的时候在判断下。 @bailicangdu 

                          const storeCreateElement =
                            Document.prototype.createElement;
                          Document.prototype.createElement = function (
                            tagName: string,
                            options?: ElementCreationOptions
                          ) {
                            const element = storeCreateElement.call(
                              this,
                              tagName,
                              options
                            );
                            return new Proxy(element, {
                              get: (
                                target: HTMLElement,
                                key: PropertyKey
                              ): unknown => {
                                const r = Reflect.get(target, key);
                                if (r instanceof HTMLElement) {
                                  r.__MICRO_APP_NAME__ =
                                    element.__MICRO_APP_NAME__;
                                }
                                return r;
                              },
                            });
