### ISSUE TITLE
关于 Element-Plus 的 css var 解析样式问题

### ISSUE THREAD

**Issue by xiangxinji** [jd-opensource/micro-app#216]
作者你好, 之前有询问过你关于 Element-Plus 项目嵌入主应用中会导致 Element-Plus中的 css var规则丢失.
之前给我的答复是关闭 css 的样式隔离, 但是我觉得这个不是长久方案,请问作者之后有考虑修复这个问题吗? 
还是说已经修复了,对应版本是什么呢?

**Comment by bailicangdu** [comment]
你问的时间好巧，问题刚好已经解决，我们今天会进行发版

**Comment by xiangxinji** [comment]
好的,非常感谢
