### ISSUE TITLE
子应用高德地图api独立运行没问题，从基座加载的时候失败，子应用是通过script引入的高德地图

### ISSUE THREAD

**Issue by litong001** [jd-opensource/micro-app#217]
基座应用是vue3，子应用是vue2，子应用通过script标签引入高德地图，独立运行是没问题，通过基座加载后地图失效。初始高德地图定位时如图。
独立运行：
![0O{G81EH28RW1LO}NWXZ~I1](https://user-images.githubusercontent.com/42726564/148487325-3405a79b-2003-49fc-8a51-83042d401214.png)

通过基座加载：
![image](https://user-images.githubusercontent.com/42726564/148487407-b7597405-ba50-44c6-900f-d92ef4d58a3b.png)

**Comment by bailicangdu** [comment]
地图js放入基座中引入

**Comment by litong001** [comment]
地图js放入基座中了，依然报这个错误。

**Comment by litong001** [comment]
问题解决了，子应用通过基座加载的时候，地图外层div高度消失了，修改下css样式加上高度就可以了，高德这个报错有点迷。。还有一个问题想问一下，如果vue项目多个子应用或基座使用的依赖相同，有没有提取出来公共依赖，优化打包的方法？

**Comment by bailicangdu** [comment]
可以通过webpack打包成dll文件，在script引入的时候加上global属性 <script src='xx' global></script>，可以实现js文件级别的依赖复用
