### ISSUE TITLE
部署后刷新页面主应用不加载问题

### ISSUE THREAD

**Issue by JackieZhang-Coding** [jd-opensource/micro-app#218]
在base 中 路由 是
```
{
    path: '/',
    redirect: '/vit-home/'
  }
{
   path: `/vit-home/:page*`,
    name: 'vit-home',
    component: () => import('../components/MicroAppTemplate.vue'),
}
```
访问 主应用 / 会跳转 /vit-home/ 加载子应用，但是在 /vit-home/刷新后，主应用的 header 就消失了，也就是 只匹配到了 子应用。

请问 这样 nginx应该怎么配置？ 主应用部署目录在 /index.html   子应用部署目录/vit-home/index.html

谢谢

**Comment by bailicangdu** [comment]
路由名称换一个，不要叫 vit-home，或者子应用文件夹名字换一个，不要和路由名称重复

**Comment by JackieZhang-Coding** [comment]
> 路由名称换一个，不要叫 vit-home，或者子应用文件夹名字换一个，不要和路由名称重复

这是什么原理呢？ 换了就不会有问题吗？我理解是nginx配置的问题。我换成 子应用文件夹换成vitHome 可以吗

**Comment by bailicangdu** [comment]
nginx的优先级，建议google一下，关键词 路由冲突

**Comment by JackieZhang-Coding** [comment]
> nginx的优先级，建议google一下，关键词 路由冲突

不对 子应用部署目录 就是不一样 加了1024  是部署在/vit1024-home/index.html

**Comment by bailicangdu** [comment]
> > 路由名称换一个，不要叫 vit-home，或者子应用文件夹名字换一个，不要和路由名称重复
> 
> 这是什么原理呢？ 换了就不会有问题吗？我理解是nginx配置的问题。我换成 子应用文件夹换成vitHome 可以吗

如果你的文件夹不是放在web container里面，那就单独修改nginx配置

**Comment by JackieZhang-Coding** [comment]
> > > 路由名称换一个，不要叫 vit-home，或者子应用文件夹名字换一个，不要和路由名称重复
> > 
> > 
> > 这是什么原理呢？ 换了就不会有问题吗？我理解是nginx配置的问题。我换成 子应用文件夹换成vitHome 可以吗
> 
> 如果你的文件夹不是放在web container里面，那就单独修改nginx配置

运维 不懂 web container 是啥。我也不懂。我们部署 就是服务器对应 域名/主应用资源   域名/子应用文件夹/子应用资源

**Comment by JackieZhang-Coding** [comment]
> nginx的优先级，建议google一下，关键词 路由冲突

页面刷新，是不是不管是啥路由，都要返回主应用的html? 我们这样配置 / 返回主应用资源，重定向到 /vit-home/ 加载子应用。刷新之后，就只匹配到了 子应用  所以出问题是这样吧

**Comment by longshenzhu** [comment]
> 子应用 所以出问题是

请问问题解决了没，我也碰到了这个问题

**Comment by longshenzhu** [comment]
> 应用文件夹名字换一个

基座是history路由，换个文件夹名字刷新时就报错了

**Comment by longshenzhu** [comment]
> > 子应用 所以出问题是
> 
> 请问问题解决了没，我也碰到了这个问题

我自己解决了，我的方案是双hash路由，基座路由需要全匹配子应用路由。这样才能刷新，不然直接在基座路由就报错了。

**Comment by longshenzhu** [comment]
> > > > 路由名称换一个，不要叫 vit-home，或者子应用文件夹名字换一个，不要和路由名称重复
> > > 
> > > 
> > > 这是什么原理呢？ 换了就不会有问题吗？我理解是nginx配置的问题。我换成 子应用文件夹换成vitHome 可以吗
> > 
> > 
> > 如果你的文件夹不是放在web container里面，那就单独修改nginx配置
> 
> 运维 不懂 web container 是啥。我也不懂。我们部署 就是服务器对应 域名/主应用资源 域名/子应用文件夹/子应用资源

基座history+子应用hash模式解决了的话，回复我一下谢谢

**Comment by raoenhui** [comment]
基座history+子应用hash模式，路由应该是不冲突的，新版本目前还有这个问题吗？
