### ISSUE TITLE
文档-常见问题-14. 子应用接口报错的疑问?

### ISSUE THREAD

**Issue by zephyrljy** [jd-opensource/micro-app#219]
文档中对此问题解决方案是子需求使用完整的地址：fetch('子应用域名/api/data').
但是当我使用axios请求时,依然会遇到同源策略的限制.
基座应用:
vite2
@micro-zoe/micro-app:0.7.1
运行端口:3000
子应用:
vue-cli:3.1.4
运行端口:1888
devServe配置:
![image](https://user-images.githubusercontent.com/39013157/148512783-2e4212fa-7c91-48b8-8c6c-7edad507f60d.png)

请求接口报错
![image](https://user-images.githubusercontent.com/39013157/148512860-257d4418-4fdd-483f-9f67-e6fad6698820.png)

**Comment by bailicangdu** [comment]
能否贴出代码或者上传一个demo帮助复现？

**Comment by bailicangdu** [comment]
一般这种情况都是proxy配置或接口调用方式不对，仔细检查一下呢，贴出案例中代理的代码以供参考：
![image](https://user-images.githubusercontent.com/20297227/148676902-e1ee34b4-630f-4e0f-992a-cbabac7b9061.png)
![image](https://user-images.githubusercontent.com/20297227/148676907-ed3e1e36-d3bb-471e-b263-99c8c526a42d.png)

**Comment by zephyrljy** [comment]
感谢阁下的回复.
我通过将跨域配置在基座应用中可以暂时解决这个问题.但我不知道是否有更好的解决办法.
下面是demo地址
git@github.com:xijiangmoon/micro-demo.git

**Comment by bailicangdu** [comment]
demo没有代码呀

**Comment by zephyrljy** [comment]
抱歉,已重新上传
git@github.com:xijiangmoon/micro-demo.git

**Comment by bailicangdu** [comment]
不是可以的么
![image](https://user-images.githubusercontent.com/20297227/148715645-f3236052-6a9b-426c-8d35-a6fa8c6ad802.png)

**Comment by zephyrljy** [comment]
如果后端的接口没有设置Access-Control-Allow-Origin为"*",会造成影响吗?

**Comment by zephyrljy** [comment]
目前看是上传了身份信息,导致Access-Control-Allow-Origin不能为'*'

**Comment by bailicangdu** [comment]
那要看接口是否设置了基座域名为白名单

**Comment by zephyrljy** [comment]
如果我在本地跑,应该怎么设置白名单
