### ISSUE TITLE
在子应用刷新页面报错与图片资源的基本地址并未被替换成正确的地址

### ISSUE THREAD

**Issue by core-admin** [jd-opensource/micro-app#220]
作者你好，请教一个问题：

项目地址：https://gitee.com/fslfsl/micro-project/tree/issues-1

基座与子应用都是vuecli4与vue3

```javascript
module.exports = {
  publicPath: '/',
  ......
}
```

子应用配置如上，在子应用的页面中引入一个img，发现图片的基本地址路径还是为主应用的，并未被__webpack_public_path__的值替换掉，__webpack_public_path__的值是存在的。

![image](https://user-images.githubusercontent.com/77573477/148643172-afa402fe-e678-4ded-9d75-1a521d4a96bd.png)

将子应用的publicPath在vue.config.js中写成绝对地址，表现符合预期

![image](https://user-images.githubusercontent.com/77573477/148643359-1d92575e-2400-4656-a5fc-25adf44dc25a.png)

![image](https://user-images.githubusercontent.com/77573477/148643364-ecfe70bd-5e9b-4ab3-9aae-feb4d90f643d.png)

想请教作者，图片或者其他这种资源为何修改了__webpack_public_path__，但从实际表现结果来看并未生效。

---

请教第二个问题：
![image](https://user-images.githubusercontent.com/77573477/148643480-1428eee8-aec7-4c95-a22d-cef5495aea83.png)

正常切换主页与子应用没问题，当切换到子应用路由下时，刷新页面报错

排查发现，刷新页面后，这俩文件的地址感觉不对，表现如下：

![image](https://user-images.githubusercontent.com/77573477/148644610-50012f90-967a-4cb7-9dc2-073e2def11dc.png)

![image](https://user-images.githubusercontent.com/77573477/148644618-0b78a518-9336-4481-99bb-b6af4d4ca9c3.png)

--- 

**补充：**

![image](https://user-images.githubusercontent.com/77573477/148650695-07cb95ea-9a79-4963-8361-2881ca6ea586.png)

**图片等资源引入到项目时地址未被正确的补充对的问题，目前发现是引入 public-path 文件的位置不同结果不同，疑惑！**

上面项目在子应用的地址上刷新页面，自己新建了一个非常干净的demo，刷新页面后错误的问题没了，可能是项目中某个地方配置问题，还在排查中

---

**补充：**

刷新后页面异常问题没了，在改动public-path 文件位置后莫名其妙的好了，又遇见的小伙伴看看是否和这个文件有关系

**Comment by bailicangdu** [comment]
将public_path放在最顶部是webpack的要求，参考webpack文档 https://webpack.docschina.org/guides/public-path/#on-the-fly

**Comment by core-admin** [comment]
感谢，文档看的不够仔细
