### ISSUE TITLE
注释的方式进行禁止样式隔离失效，未起作用

### ISSUE THREAD

**Issue by core-admin** [jd-opensource/micro-app#221]
## 问题描述
使用注释的方式进行禁止样式隔离，发现类名依然会被处理

## 复现步骤
1. 添加对应的css，添加禁用隔离的注释代码
2. vue文件中引用此文件进行使用

## 上传截图
![image](https://user-images.githubusercontent.com/77573477/148713578-aa0aa3b5-4b6d-4c72-9939-afc773a3c813.png)

![image](https://user-images.githubusercontent.com/77573477/148713674-92d36f5f-9a91-452e-bbaf-53829b8dd28d.png)

## 复现仓库
https://gitee.com/fslfsl/micro-project/tree/issues-2

## 环境信息
- micro-app版本："@micro-zoe/micro-app": "^0.7.1"
- 主应用前端框架&版本："vue": "^3.2.20",
- 子应用前端框架&版本："vue": "^3.2.20",
- 构建工具&版本：@vue/cli 4.5.15、

**Comment by bailicangdu** [comment]
更新到最新版试一下呢

**Comment by stewinged** [comment]
> 更新到最新版试一下呢

0.8.0 css样式 动态引入的
![image](https://user-images.githubusercontent.com/20498227/148718507-da78d9c1-8dcf-4097-90cd-ed3a932ad871.png)
之前版本没问题 之前是 0.6.2
![image](https://user-images.githubusercontent.com/20498227/148718538-fa572662-c620-4750-94c3-487cd3476b45.png)

**Comment by core-admin** [comment]
> 更新到最新版试一下呢

更新到最新版本，注释取消样式隔离功能可用

**Comment by bailicangdu** [comment]
> > 更新到最新版试一下呢
> 
> 0.8.0 css样式 动态引入的 ![image](https://user-images.githubusercontent.com/20498227/148718507-da78d9c1-8dcf-4097-90cd-ed3a932ad871.png) 之前版本没问题 之前是 0.6.2 ![image](https://user-images.githubusercontent.com/20498227/148718538-fa572662-c620-4750-94c3-487cd3476b45.png)

麻烦提供一个demo，或者css的内容
