### ISSUE TITLE
子应用使用 el-dropdown 或者是 el-popover  组件会导致样式丢失

### ISSUE THREAD

**Issue by xiangxinji** [jd-opensource/micro-app#223]
## 问题描述
> 问题的具体描述
子应用使用 dropdown 和 el-popover 导致组件样式丢失 
## 复现步骤
1. 使用 element-plus@1.0.2-beta.71
2. 子应用使用其中的 dropdown 和 popover 组件
3. 主应用预览

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。
子应用
![image](https://user-images.githubusercontent.com/58387767/148751185-61dbdef5-0e70-44eb-a261-74c37f1bf503.png)

主应用
![image](https://user-images.githubusercontent.com/58387767/148751275-2e8bdf95-aad5-462b-927a-c164fe2a9f78.png)

## 复现仓库
> 暂无

## 环境信息
- micro-app版本：0.8.0
- 主应用前端框架&版本： "naive-ui": "^2.19.1",
- 子应用前端框架&版本： element-plus@1.0.2-beta.71
- 构建工具&版本：主应用   "vite": "^2.5.10",

**Comment by bailicangdu** [comment]
好的，我们会在下个版本修复

**Comment by bailicangdu** [comment]
v0.8.1已修复 https://github.com/micro-zoe/micro-app/releases/tag/v0.8.1

**Comment by xiangxinji** [comment]
@bailicangdu 我已经安装了 0.8.1 , 但好像没什么效果 
在子应用样式
![image](https://user-images.githubusercontent.com/58387767/149119490-9aa97517-640b-4798-bc1c-e19081f3bf67.png)
主应用渲染出来的样式依然不包含 .el-popover 和 .el-popper 的样式
![image](https://user-images.githubusercontent.com/58387767/149119769-d2323534-bd1b-4170-aa3e-46dd54f52993.png)

或者我应该怎么先去解决这个问题, 是再安装element-plus , 然后手动引入他的 popover 的css 吗?

**Comment by bailicangdu** [comment]
更新到最新版element-plus

**Comment by xiangxinji** [comment]
好的 , 非常感谢, 已经解决
