### ISSUE TITLE
子应用vue2项目中，vue-pdf 报错 Failed to construct 'Worker'

### ISSUE THREAD

**Issue by sidifen** [jd-opensource/micro-app#225]
## 问题描述
> 问题的具体描述
micro-app-demo-master 项目
分别启动：
启动 main_apps 目录下的 vue2  项目
启动 child_apps 目录下的 vue2 项目 与 sidebar 项目
启动正常，父应用vue2访问子应用vue2正常

下面是问题复现步骤

## 复现步骤
1. 在child_apps 目录下的 vue2 项目中 cnpm install vue-pdf --save， 并在main.js全局import,并且 Vue.component 全局注册，
2. import pdf from 'vue-pdf';   Vue.component('pdf', pdf);
3. cnpm run dev重启 该子应用，在父应用vue2项目中访问子应用，报错如图
4. micro-app-demo-master 项目里就导入了这个vue-pdf，其他与git上代码一模一样没有变动。

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。
报错信息如下：
![1641868680(1)](https://user-images.githubusercontent.com/18259377/148871719-3f9374c7-5fd7-4374-a9d6-e13e6d351831.png)
改动信息如下：
![1641868836(1)](https://user-images.githubusercontent.com/18259377/148871807-1ee7ee9e-620f-4771-bdf8-3dc6a52138ac.png)

## 复现仓库
> git 上的 micro-app-demo-master

## 环境信息
git 上的 micro-app-demo-master 就在子应用vue2中全局加了一个vue-pdf包，其余没有变动
- micro-app版本："@micro-zoe/micro-app": "latest"
- 主应用前端框架&版本：vue2
- 子应用前端框架&版本：vue2
- 构建工具&版本：node v14.16.0  cnpm@6.2.0

**Comment by sidifen** [comment]
似乎找到答案：https://github.com/FranckFreiburger/vue-pdf/issues/25#issue-272439462；
只要导入noworker的包就好了。

**Comment by bailicangdu** [comment]
worker跨域的问题无解，只能通过其他方式解决，这边给一个参考的方案：从基座进入，下发给子应用。具体方式如下：
1、基座安装vue-pdf
2、基座下发pdf组件给子应用
![image](https://user-images.githubusercontent.com/20297227/148878935-fee3f836-7184-4e3f-adfd-a5759b7c5890.png)
3、子应用根据环境进行初始化，保证嵌入基座和单独运行都能正常执行
![image](https://user-images.githubusercontent.com/20297227/148879116-5d6a09c4-52d8-431c-a9ec-2045f5a22174.png)

**Comment by sidifen** [comment]
@bailicangdu 好的，bailicangdu，十分感谢！
