### ISSUE TITLE
调用unmountAllApps卸载后 怎么再加载回来 现在好像没有重新加载的办法

### ISSUE THREAD

**Issue by Kryzeno** [jd-opensource/micro-app#226]
调用unmountAllApps结束应用后 再次初始化micro-app 页面不会显示任何元素 这是怎么回事

**Comment by Kryzeno** [comment]
![image](https://user-images.githubusercontent.com/7607957/148887662-fe21f7e1-5f75-4d94-9dc9-22287ff56835.png)
这是首次加载的没问题 但是调用unmountAllApps后 再次加载micro-app里面整个元素都没了
![image](https://user-images.githubusercontent.com/7607957/148887777-88d2fb2b-da86-4c4e-8ae1-ebb1a4df25ac.png)

**Comment by Kryzeno** [comment]
代码
![image](https://user-images.githubusercontent.com/7607957/148887826-f83f1d9f-7d28-44ff-877f-f753ed8be6b5.png)

**Comment by bailicangdu** [comment]
是否使用了vue的keep-alive？

**Comment by Kryzeno** [comment]
主应用的micro-app属性里面用了keep-alive

**Comment by Kryzeno** [comment]
子应用的keep-alive都去掉了

**Comment by bailicangdu** [comment]
二次渲染失败是因为micro-app元素没被创建，仔细检查一下逻辑呢

**Comment by Kryzeno** [comment]
micro-app元素我也没做v-if  v-show 怎么会这样的

**Comment by bailicangdu** [comment]
你可以提供一个简易的复现问题的demo

**Comment by Kryzeno** [comment]
我再micro-app元素外面再包一个div 加上v-if重新初始化控制就可以了   直接在micro-app元素绑定v-if重新渲染 是会失败的
