### ISSUE TITLE
子应用vue2项目中，index.html 引入layui，样式文件路径丢失

### ISSUE THREAD

**Issue by sidifen** [jd-opensource/micro-app#227]
## 问题描述
> 问题的具体描述
micro-app-demo-master 项目
分别启动：
启动 main_apps 目录下的 vue2 项目（history模式）
启动 child_apps 目录下的 vue2 项目 （history模式）与 sidebar 项目
启动正常，父应用vue2访问子应用vue2正常

第三方文件包可下载（测试）：
[layui.zip](https://github.com/micro-zoe/micro-app/files/7844349/layui.zip)

## 复现步骤
1.在child_apps 目录下的 vue2 项目中，将上述layui解压至public目录下
2.在index.html中引入如图1
3.浏览器直接访问child_apps 目录下的 vue2 项目没有问题，layer相关的css文件都能加载成功。如图2
4.用父应用加载子应用的方式访问，除了layui样式文件加载正常，其余俩个layer.css 与 laydate样式没有加载成功。如图3
5.原因layer.css与laydate.css是路径缺失, layui.css是正常的。
有没有合适一点的方案解决
6.补充 我父应用嵌套下的子应用中app.vue中调用该库的脚本报错，独立访问子应用并没有问题。如图4

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。
1.
![1641884786(1)](https://user-images.githubusercontent.com/18259377/148896589-c4f9623a-be23-47e3-809f-4d9d976c1b1b.png)
2.
3.
![1641885172(1)](https://user-images.githubusercontent.com/18259377/148897335-3443f50d-4bdb-4010-b94a-57f098e6c94e.png)
![1641885220(1)](https://user-images.githubusercontent.com/18259377/148897421-bc14e675-c9c6-4c55-b475-4a15b6cd734a.png)

4.
![1641886322(1)](https://user-images.githubusercontent.com/18259377/148899769-b4d048ae-7f20-43df-8a90-44457dc5a8f4.png)
![1641886432(1)](https://user-images.githubusercontent.com/18259377/148900028-7fb64933-b0c5-4bc6-9728-fbd882b80560.png)

## 复现仓库
> git 上 micro-app-demo-master 项目 用上述layui包测试，除了引入这个包之外，其余代码与git上一样。

## 环境信息
- micro-app版本："@micro-zoe/micro-app": "latest"
- 主应用前端框架&版本：vue2
- 子应用前端框架&版本：vue2
- 构建工具&版本：node v14.16.0 cnpm@6.2.0

**Comment by bailicangdu** [comment]
layui.js从location取值添加css，暂时没办法解决，只能等到下一个大版本
