### ISSUE TITLE
vite 打包之后的代码，不能被应用

### ISSUE THREAD

**Issue by dcomdjl** [jd-opensource/micro-app#228]
## 问题描述
> 问题的具体描述

使用vue3  + vite 打包之后，抱如下的错误

Failed to resolve module specifier "./vendor.9005415a.js". Invalid relative url or base scheme isn't hierarchical.

## 上传截图
![image](https://user-images.githubusercontent.com/15134783/148922984-8d33c1b3-b05c-4683-81b4-b850fd707c1e.png)

**Comment by dcomdjl** [comment]
发现vite打包之后，对应的html代码为

    <script type="module" crossorigin src="/assets/index.8a7ea51d.js"></script>
    <link rel="modulepreload" href="/assets/vendor.49341405.js">
    <link rel="modulepreload" href="/assets/__federation_expose_Button.js">
    <link rel="stylesheet" href="/assets/__federation_expose_Button.0bc5dddb.css">

不能正确的解析 modulepreload

**Comment by dcomdjl** [comment]
vite打包的代码不能直接使用，需要自己写脚本修改打包代码，已解决

**Comment by ulnae** [comment]
兄弟你是怎么解决的

**Comment by note520** [comment]
> 

大兄弟，能贴解决demo代码吗？

**Comment by dcomdjl** [comment]
> 

不好意思,最终没有使用这个方案了,主要是遇到的问题各种各样,有些没办法解决,原来的代码仓库公司这边都已经丢弃了

**Comment by houqiangxie** [comment]
大佬，我按照官网配置了打包插件，现在是报第三方插件问题
![image](https://user-images.githubusercontent.com/39187588/188537531-e7ecac15-62a6-4e31-a8f1-292a27ee0d5e.png)

**Comment by zch233** [comment]
怎么解决的呢

**Comment by rawbin-** [comment]
这个主应用的更改，异步的组件会走loader的逻辑么，能不能只在主应用加载的时候修改子应用不改？

**Comment by chenzl0723** [comment]
> vite打包的代码不能直接使用，需要自己写脚本修改打包代码，已解决

vite4.x 如何做修改适配
