### ISSUE TITLE
请求 给个部署教程？

### ISSUE THREAD

**Issue by macsapps** [jd-opensource/micro-app#229]
vite - vue3 作为主框架

打包部署后 vue3的的子应用不出来并报有跨域的问题

vue2的子应用 首次可以加载出来 但是刷新就包404

**Comment by bailicangdu** [comment]
参考 https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/deploy

**Comment by macsapps** [comment]
部署后可以实现访问但是浏览器不能刷新 一刷新 就404了
<img width="1342" alt="企业微信20220112-154500@2x" src="https://user-images.githubusercontent.com/53206306/149085632-da817d2f-854c-4df6-ac4f-cdd4ecdfe1d2.png">
<img width="1166" alt="企业微信20220112-154525@2x" src="https://user-images.githubusercontent.com/53206306/149085670-5ce6f6c9-8ebb-4aab-bdda-c5201b70477b.png">
<img width="1136" alt="企业微信20220112-154419@2x" src="https://user-images.githubusercontent.com/53206306/149085684-276df391-f6e2-4b37-b646-e3d7ac05fe61.png">



> 参考https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/deploy

**Comment by bailicangdu** [comment]
这里设置了吗
![image](https://user-images.githubusercontent.com/20297227/149086017-7a0b88fd-35d9-4e67-bcab-957e1d8ab992.png)

**Comment by macsapps** [comment]
![image](https://user-images.githubusercontent.com/53206306/149086369-bdaa96d2-272e-497d-b3e6-556c330b011a.png)

这里的设置是这样吗？

**Comment by hewenxiao** [comment]
> 这里设置了吗 ![image](https://user-images.githubusercontent.com/20297227/149086017-7a0b88fd-35d9-4e67-bcab-957e1d8ab992.png)

**Comment by macsapps** [comment]
应该是和 nginx的端口有关系   listen 80 这里是默认的80
但是我 部署在84端口的  我这改成84
然后配置好 重定向路径 后 现在是访问正常了
