### ISSUE TITLE
父应用的路由好像会受到 vuerouter 的 base 的影响

### ISSUE THREAD

**Issue by wtZZx** [jd-opensource/micro-app#23]
父应用是一个老项目，使用了 directorjs 作为路由（hash）

子应用使用了 VueRouter（hash）

当我进入子应用后，hash 会变成 `#/app-vue-hash/about`

但是当我点击父应用的原有菜单时，hash 会变成 `#/app-vue-hash/[原来的hash]` 

不知道有没有人遇到过这种情况

**Comment by bailicangdu** [comment]
基座和子应用都是基于浏览器地址的，两个都会影响到浏览器地址

**Comment by wtZZx** [comment]
现在的问题是我在父应用更改 `location.hash` 的时候子应用还没有卸载，触发了子应用的路由，导致跳转到了子应用带 `base` 的  hash 上

**Comment by bailicangdu** [comment]
这样的问题就需要修改路由配置来解决了

**Comment by bailicangdu** [comment]
这样的问题就需要修改路由配置来解决了

**Comment by wtZZx** [comment]
:joy:  解决了，我看我能拿到 `appInstanceMap` 所以我就在点菜单的时候先主动卸载掉了 :joy:

**Comment by junsen313** [comment]
> 😂 解决了，我看我能拿到 `appInstanceMap` 所以我就在点菜单的时候先主动卸载掉了 😂

@wtZZx 请问怎么拿到 `appInstanceMap` ?
