### ISSUE TITLE
子应用使用  position: fixed样式，使用element组件的Popover、Tooltip、Drawer (设置了append-to-body)等样式失效问题

### ISSUE THREAD

**Issue by wengfengtong** [jd-opensource/micro-app#230]
## 问题描述
> 问题的具体描述
![image](https://user-images.githubusercontent.com/37279162/148954937-8a6fb9fc-2277-44a1-bf74-c8f0c8219ea7.png)
以上可使用transform: translate(0, 0);修复

![image](https://user-images.githubusercontent.com/37279162/148955042-28f405ed-2a5a-458b-96a2-7af99c427727.png)
![image](https://user-images.githubusercontent.com/37279162/148955101-8c10c842-20b1-455a-9c55-374fccf8aa0a.png)

## 复现步骤
1. 主应用容器使用相对定位
![image](https://user-images.githubusercontent.com/37279162/148954588-48b4f277-d2f1-4144-bebf-e8f213275a27.png)

2.子应用
![image](https://user-images.githubusercontent.com/37279162/148954705-f735fb49-6a9e-4b12-8087-997c7abf12a2.png)

2.

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。
https://github.com/wengfengtong/micro-app-bug-demo.git
管理后台采用element-admin  建议完整版测试

## 环境信息
- micro-app版本：
- 主应用前端框架&版本：vue2
- 子应用前端框架&版本：vue2
- 构建工具&版本：webpack

**Comment by bailicangdu** [comment]
样式冲突，只能你自己调整了

**Comment by wangrx-jerry** [comment]
有没有全局的调整策略，难道是对每个偏移元素特殊处理？

**Comment by tom-hanks** [comment]
请问解决了吗

**Comment by tom-hanks** [comment]
为什么没有完全隔离样式，导致 fixed 会逃逸到父应用里
