### ISSUE TITLE
子项目中在index.html引入高德地图，抛出异常app app1: CSSParser: An error occurred while parsing CSS Error: Declaration missing '}'

### ISSUE THREAD

**Issue by XuRenee** [jd-opensource/micro-app#232]
## 问题描述
子项目中在index.html引入高德地图，抛出异常app app1: CSSParser: An error occurred while parsing CSS Error: Declaration missing '}'

## 复现步骤
1.index.html中引入【<script
            src="https://webapi.amap.com/maps?v=1.4.15&key=xxxxx&&plugin=AMap.Scale,AMap.OverView,AMap.ToolBar,AMap.DistrictSearch">
        </script>】
如图：
![image](https://user-images.githubusercontent.com/49704463/149064569-1d7cf67d-2602-4f8e-843f-2b1643e9c7f6.png)

2.基座应用加载子项目
    <micro-app
      name="app1"
      url="http://localhost:8080/"
      baseroute="/constructionprocedure"
    ></micro-app>

## 上传截图
![1641962439(1)](https://user-images.githubusercontent.com/49704463/149064890-8c30f5c8-f2f6-44f4-ba01-bda12c4da984.jpg)

## 环境信息
- micro-app版本："@micro-zoe/micro-app": "^0.8.0",
- 主应用前端框架&版本："vue": "^2.6.11",
- 子应用前端框架&版本："vue": "^2.6.11",
- 构建工具&版本："@vue/cli-service": "~4.5.0",

**Comment by bailicangdu** [comment]
了解，没想到如今还会掉到ie6、7的坑里。下个版本进行修复

**Comment by XuRenee** [comment]
坐等更新！！！！！芜湖~
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "micro-zoe/micro-app"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月12日(星期三) 下午2:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [micro-zoe/micro-app] 子项目中在index.html引入高德地图，抛出异常app app1: CSSParser: An error occurred while parsing CSS Error: Declaration missing '}' (Issue #232)





 
了解，没想到如今还会掉到ie6、7的坑里。下个版本进行修复
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by bailicangdu** [comment]
v0.8.1已修复, https://github.com/micro-zoe/micro-app/releases/tag/v0.8.1

**Comment by XuRenee** [comment]
> 

我天！！！！效率这么高，牛哇牛哇

**Comment by K-walker** [comment]
> 且 7 天未收到回应。现关闭 issue，若有任何问题，可评论回复。



> v0.8.1已修复, https://github.com/micro-zoe/micro-app/releases/tag/v0.8.1

我安装的最新的 0.8.7 版本还是会出现
![image](https://user-images.githubusercontent.com/10557092/178637871-cb3fafef-8bf2-439d-8758-d48dea4566b7.png)

**Comment by bailicangdu** [comment]
@K-walker css内容发一下呢

**Comment by K-walker** [comment]
> @K-walker css内容发一下呢

我找到问题了，是我打包后的style标签，有的里面没有任何样式的缘故，因而这样的css导致无法解析如下：
![image](https://user-images.githubusercontent.com/10557092/178666027-78224103-764f-4402-a64f-c38a92a30690.png)
这里style标签里，全是注释代码，没有写一行样式，所以就报错了（这块我自己正在处理）。

能否希望大佬在源码里加个容错呢？这样的style标签，就直接忽略。

**Comment by K-walker** [comment]
> @K-walker css内容发一下呢

我找到问题了，是我打包后的style标签，有的里面没有任何样式的缘故，因而这样的css导致无法解析如下：
![image](https://user-images.githubusercontent.com/10557092/178666027-78224103-764f-4402-a64f-c38a92a30690.png)
这里style标签里，全是注释代码，没有写一行样式，所以就报错了（这块我自己正在处理）。

能否希望大佬在源码里加个容错呢？这样的style标签，就直接忽略。

**Comment by bailicangdu** [comment]
这是写法不规范，应该是 @charset "UTF-8";

**Comment by K-walker** [comment]
> 这是写法不规范，应该是 @charset "UTF-8";

我看了下那个scss文件，里面写的确实是  @charset 'utf-8';  冒号是加了的，因为其他文件都有：
![image](https://user-images.githubusercontent.com/10557092/178668515-0aa382d9-5264-4e76-8fcc-5ccfa44dea69.png)

唯独这个上面截图中的冒号在编译之后没了

**Comment by WJYman** [comment]
<img width="1309" alt="image" src="https://user-images.githubusercontent.com/26448051/199386632-02a81a2a-b2b5-4041-aec8-77426decc837.png">
micro-app版本："@micro-zoe/micro-app": "^0.8.10",
主应用前端框架&版本："vue": "^2.6.10",
子应用前端框架&版本："vue": "^2.6.10",
子应用显示出来了，但是报错

**Comment by WJYman** [comment]
主应用和子应用目前都是在本地运行的

**Comment by WJYman** [comment]
主应用和子应用目前都是在本地运行的
