### ISSUE TITLE
使用micro-app后无法使用vueCli的远程组件

### ISSUE THREAD

**Issue by XuRenee** [jd-opensource/micro-app#234]
## 问题描述
> 基座项目的index.html中引入了<script src="https://unpkg.com/vue"></script>，运行报错[micro-app from runScript] app app1:  TypeError: Cannot redefine property: $router

## 复现步骤
1.父项目index.html引入<script src="https://unpkg.com/vue"></script>
2.启动-运行父项目

## 上传截图
>
![1641981069](https://user-images.githubusercontent.com/49704463/149116952-22a48405-8aaa-4608-8beb-6147785be1aa.jpg)
![1641980824(1)](https://user-images.githubusercontent.com/49704463/149116983-549b094d-6b47-4b29-b113-ebd575c98f53.jpg)

## 环境信息
- micro-app版本：0.8.1
- 主应用前端框架&版本：vue2
- 子应用前端框架&版本：vue2
- 构建工具&版本："@vue/cli-service": "~4.5.0"

不知道可不可以兼容vue远程组件，求教大佬！！！

**Comment by bailicangdu** [comment]
你可以使用临时方案：
```js
microApp.start({
  plugins: {
    global: [
      {
        scopeProperties: ['Vue'],
      },
    ],
  },
})
```

**Comment by bailicangdu** [comment]
或者等到下一个版本

**Comment by XuRenee** [comment]
ok，谢谢大佬~
