### ISSUE TITLE
请问支持blazor webassembly框架吗？.net 系的

### ISSUE THREAD

**Issue by bingxueyinlian** [jd-opensource/micro-app#239]
请问一下：
支持blazor webassembly框架吗？.net 系的
还有现有老系统怎么接入，jquery,asp.net,jsp开发的。

**Comment by bailicangdu** [comment]
多页面应用不适合使用

**Comment by bingxueyinlian** [comment]
@bailicangdu
blazor webassembly也是单页面的，只是用C#代替了js

**Comment by bailicangdu** [comment]
> @bailicangdu blazor webassembly也是单页面的，只是用C#代替了js

这个还真没试过，理论上是可以的，有空我们写个demo试一下

**Comment by bingxueyinlian** [comment]
好的，谢谢。
