### ISSUE TITLE
vite vue3 本地开发环境加载本地npm库的时候异常

### ISSUE THREAD

**Issue by palluo** [jd-opensource/micro-app#243]
## 问题描述
> 问题的具体描述

## 复现步骤
1. 链接本地npm库， npm link xxx

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。
![image](https://user-images.githubusercontent.com/24562747/149665566-63213d2b-2e5c-4f53-adf5-39d265935ad4.png)

## 环境信息
- micro-app版本：
- 主应用前端框架&版本：和主应用没关系
- 子应用前端框架&版本：
- 构建工具&版本：vite 2.7.12

**Comment by palluo** [comment]
![image](https://user-images.githubusercontent.com/24562747/149665793-0efeac8a-7b00-4295-bafa-0f6d6b267df3.png)
和这个配置有关系

**Comment by core-admin** [comment]
配错东西了吧，参照下官方案例，之前我也是配错了，也是这个错
