### ISSUE TITLE
微前端这种技术方案是否可应用到electron上？

### ISSUE THREAD

**Issue by core-admin** [jd-opensource/micro-app#244]
请教下作者，像微前端这种技术方案（落地的比如有：qiankun、micro-app），放到electron上是否也通用？因为微前端也是解决多个应用独立开发互不影响，二是减小项目平台的整体代码体积，在electron中也有这个问题，如果放入多个应用（代码全部在一个项目下），就代表着开发人员越多维护起来越复杂，是否可使用微前端技术解决在electron中遇到的问题呢？

**Comment by bailicangdu** [comment]
可以的

**Comment by core-admin** [comment]
OK
