### ISSUE TITLE
应用间样式错乱

### ISSUE THREAD

**Issue by luocongchao** [jd-opensource/micro-app#247]
![image](https://user-images.githubusercontent.com/19605214/149885544-1c03861b-d550-4f95-a710-a13cf33d4a6e.png)
子应用的样式都加载到基座的head标签里面导致的样式相互影响
disableScopecss用的是默认的css隔离 但似乎并没有起作用
从demo里面拉取下来的代码  版本0.8.2

**Comment by bailicangdu** [comment]
因为这是vite应用，沙箱关闭了 https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/framework/vite

**Comment by luocongchao** [comment]
噢，谢谢提醒，那这样的话感觉要适配vite还得做好多额外操作库😂😂
