### ISSUE TITLE
子应用 localStorage 命名冲突，有没有提供什么方法

### ISSUE THREAD

**Issue by hzfvictory** [jd-opensource/micro-app#252]
## 背景
> 子应用 localStorage 命名冲突，导致应用异常

## 期望的效果

每个子应用本地存储的 key 默认带着 name

**Comment by bailicangdu** [comment]
目前不支持，只能自行解决

**Comment by core-admin** [comment]
自己处理就行 每个子项目添加本地缓存时存储的key都添加namespace

**Comment by hzfvictory** [comment]
> 自己处理就行 每个子项目添加本地缓存时存储的key都添加namespace

localStorage  支持重写吗

**Comment by hzfvictory** [comment]
> 自己处理就行 每个子项目添加本地缓存时存储的key都添加namespace

说的真好 以后别说了。 成本太大了

**Comment by CODPHISH** [comment]
> 目前不支持，只能自行解决

请问主应用与子应用之间的所有storage都是共享的吗？文档中没找到

**Comment by Hachiko2018** [comment]
> > 目前不支持，只能自行解决
> 
> 请问主应用与子应用之间的所有storage都是共享的吗？文档中没找到

我试下来是共享的
