### ISSUE TITLE
子应用使用react-monaco-editor时发生异常

### ISSUE THREAD

**Issue by coolRoger** [jd-opensource/micro-app#253]
## Describe the bug
当含有react-monaco-editor的应用单独运行时表现正常，当嵌入了microApp作为子应用运行时，样式丢失且控制台发生报错

## Reproduce repository
可复现的仓库, [micro-app-issue-253](https://github.com/coolRoger/micro-app-issue-253)，**在mainApp安装依赖时，请务必使用yarn, subApp则随意**

## Screenshots
**单独运行时**：
<br/>
![image](https://user-images.githubusercontent.com/33861624/150461428-1b65a51f-570f-469a-a167-cd6bc3a9bc50.png)
<br/>
![image](https://user-images.githubusercontent.com/33861624/150462075-42bea517-5c87-466b-b481-c044cee6e691.png)
<br/>
****嵌入主应用运行时**：**
<br/>
![image](https://user-images.githubusercontent.com/33861624/150462999-6bba4b20-7550-4640-91ac-dc74134f8337.png)
代码提示消失
<br/>
![image](https://user-images.githubusercontent.com/33861624/150462947-06f168de-b0c3-4cf6-8355-3b885a802670.png)
右键菜单显示异常
<br/>
![image](https://user-images.githubusercontent.com/33861624/150462879-60e8c23f-8b2b-45ff-af46-dc2603f7d348.png)
子应用打开时，控制台报错
<br/>
![image](https://user-images.githubusercontent.com/33861624/150462803-36b3568c-770d-441c-ad1e-7c11c21c05c2.png)
关闭子应用时，控制台报错

## Environment
- micro-app version: **0.7.1**
- framework of base app & version: **React^17.0.2**
- framework of sub app & version: **React^17.0.2**
- Build tools & version: **react-scripts^5.0.0** & **@craco/craco^6.4.3**

**Comment by bailicangdu** [comment]
这是一个难以解决的问题，我们正在排查和尝试修复，谢谢反馈

**Comment by coolRoger** [comment]
@bailicangdu 非常感谢您的回复：

我现在用了一个曲线救国的方法：

- 暂时先在react-monaco-editor的子应用将disableScopecss设置为true，
- 至于代码提示方面，主要是monaco-editor-webpack-plugin这个插件来引入语言库然后做代码提示的。所以我只有在主程序修改webpack配置，启用monaco-editor-webpack-plugin这个插件，并且将monaco-eidtor这个库引进主程序

暂时用起来貌似是没有问题的，同时也非常期待您的相关修复

**Comment by coolRoger** [comment]
@bailicangdu 大佬, 请问这个issue的修复进度如何啦?

**Comment by aWestbrookFan** [comment]
控制台发生报错 可能是因为editor.worker.js和ts.worker.js资源没获取到。设置下 https://zeroing.jd.com/docs.html#/zh-cn/static-source?id=publicpath 就可以了

**Comment by pisyell** [comment]
在子应用中，代码编辑器的光标聚焦有很大的问题

**Comment by qyjs** [comment]
![image](https://github.com/micro-zoe/micro-app/assets/22796811/056a2abe-c622-465c-a80a-6e8a0cdcaf93)
大佬，在子应用中，也遇到同样的问题。有什么进展么，或者有什么思路吗，大家一起解决

**Comment by raoenhui** [comment]
用 v1.0.0-beta.7 版本 试下看，是不是好了

**Comment by qyjs** [comment]
> 用 v1.0.0-beta.7 版本 试下看，是不是好了

不行一样的问题

**Comment by raoenhui** [comment]
> > 用 v1.0.0-beta.7 版本 试下看，是不是好了
> 
> 不行一样的问题

我自己安装react-monaco-edito是好的，方便提供下代码仓库吗？方便进微信群加下我微信吗？

**Comment by raoenhui** [comment]
由于react-monaco-editor中生成了shadow，所以导致micro-app加的样式隔离失效，建议开启disableScopecss=‘true’即可解决，详情查看 https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/configure?id=disable-scopecss决，

**Comment by BTBMan** [comment]
@coolRoger 您好，同样遇到了 worker 加载的问题，请问除了上述你提供的解决办法还有其他的解决办法吗？

**Comment by BTBMan** [comment]
@bailicangdu 请问这个问题解决了吗？

子应用单独运行，worker 的加载是正常的。

<img width="858" height="210" alt="Image" src="https://github.com/user-attachments/assets/f40330be-695a-4457-9d25-dcd2481d4f34" />



当在 micro-app 里，worker 就变成 blob 形式了。

<img width="2074" height="206" alt="Image" src="https://github.com/user-attachments/assets/b1af93f8-30f7-4264-9c0f-fba0d273f0cd" />



而这个 blob 在浏览器里打开是这个内容。

<img width="2006" height="190" alt="Image" src="https://github.com/user-attachments/assets/5692a29b-2230-4870-ac52-bb995c01897e" />

**Comment by BTBMan** [comment]
> 控制台发生报错 可能是因为editor.worker.js和ts.worker.js资源没获取到。设置下 [zeroing.jd.com/docs.html#/zh-cn/static-source?id=publicpath](https://zeroing.jd.com/docs.html#/zh-cn/static-source?id=publicpath) 就可以了

通过这种方式配置后，worker 的引用路径确实是对的，不过请求头信息无内容。

<img width="1826" height="812" alt="Image" src="https://github.com/user-attachments/assets/5a894313-034d-4824-bc4b-84079e3d3e52" />

正常的请求头内容是。

<img width="1656" height="1026" alt="Image" src="https://github.com/user-attachments/assets/9448fcc6-2728-431e-bfe0-a92a769a11c3" />

**Comment by BTBMan** [comment]
已解决，就是通过上面的 public 方法解决的，因为打包分包的问题导致 js 加载错误，少运行一个 worker。
