### ISSUE TITLE
升级到0.8版本，首页点输入框超级卡

### ISSUE THREAD

**Issue by wdzhao3** [jd-opensource/micro-app#256]
## 问题描述
> 0.7.1升级到0.8版本，登录输入框点不动，大概20秒，输入框才能正常使用，回退到0.7.1正常，发现是main.js里有预加载才这样
**火狐浏览器出现这种情况**
谷歌浏览器正常，360正常，

## 复现步骤
1.
2.

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。

## 复现仓库
>  https://github.com/wdzhao3/issue-demo.git

## 环境信息
- micro-app版本：0.8
- 主应用前端框架&版本：vue3（vue-cli），element-plus
- 子应用前端框架&版本：vue2
- 构建工具&版本：

**Comment by bailicangdu** [comment]
demo 地址404

**Comment by wdzhao3** [comment]
https://github.com/wdzhao3/issue-demo

**Comment by bailicangdu** [comment]
你是不是设置为私有仓库了

**Comment by wdzhao3** [comment]
是的，修改了

**Comment by bailicangdu** [comment]
已修复，升级到0.8.4即可，谢谢反馈！
