### ISSUE TITLE
关于 js 被 extract 的问题 

### ISSUE THREAD

**Issue by xiangxinji** [jd-opensource/micro-app#257]
因为我现在子项目中有引用 iconfont 生成的js , 但是集成到主应用当中发现这个js 被自动排除了 .
请问什么情况下会做这种排除呢, 然后怎么去解决它呢

![image](https://user-images.githubusercontent.com/58387767/150742093-f8282280-f1d2-46d4-b825-bc27f94888f1.png)

**Comment by bailicangdu** [comment]
参考 https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/configure?id=inline
