### ISSUE TITLE
umi创建的子应用加载后报错

### ISSUE THREAD

**Issue by qinsong77** [jd-opensource/micro-app#26]
复现库：https://github.com/qinsong77/micro-app-demo
报错如图
![image](https://user-images.githubusercontent.com/35391584/128703418-ed6c0a22-e93e-425a-a738-cb8220586b4f.png)

**Comment by qinsong77** [comment]
排查是热更新websocket的问题，umi是dev-server，固定写死解决 [socket_server](https://umijs.org/zh-CN/docs/env-variables#socket_server)
好像也可通过插件解决。

**Comment by bailicangdu** [comment]
👍

**Comment by HenryZhu-1988** [comment]
> 



> 排查是热更新websocket的问题，umi是dev-server，固定写死解决 [socket_server](https://umijs.org/zh-CN/docs/env-variables#socket_server) 好像也可通过插件解决。

`SOCKET_SERVER=https://localhost:8000/  umi dev`

SOCKET_SERVER 这个 server 指向的是 基座的 host 还是 umi 子应用本身的
