### ISSUE TITLE
关于挂载到body上的元素问题

### ISSUE THREAD

**Issue by core-admin** [jd-opensource/micro-app#260]
请教作者一个问题，我在子应用中创建动态的元素并插入到body中，发现插入的操作应该是被拦截了，插入到了`micro-app-body`下，这应该是作者处理过了，如图：
![image](https://user-images.githubusercontent.com/77573477/150956233-6b99044b-e526-4b7e-b756-a898bc2db27b.png)
![image](https://user-images.githubusercontent.com/77573477/150956926-2c8d7f16-ffe3-49c6-9c0b-4a6b70ecf6fb.png)

但是在使用ant-design这一类UI库时，一些弹窗，下拉框一般会把body作为容器，经过测试我发现Modal这个组件显示时插入的位置是`micro-app-body`，而像Popover和选择时间这种下拉框它们都被放到了body下，想问下作者，如果我们已经拦截了body的节点插入操作，像出现以上这种情况大概是什么原因。

![image](https://user-images.githubusercontent.com/77573477/150955464-26bda639-8e6e-40df-a049-645c83b67196.png)
![image](https://user-images.githubusercontent.com/77573477/150957472-2f0b5bb6-e934-4310-b3b1-031a76dc2ea2.png)

这样的话，启用样式隔离的情况下，被插入到body上的元素，样式将不会被应用。

版本："@micro-zoe/micro-app": "^0.8.4",
基座和子应用都是vue3、ant-design-vue-3.0.alpha.9

**Comment by bailicangdu** [comment]
一般是异步操作导致元素无法被沙箱拦截，这是目前沙箱上的设计缺陷，回在后续版本中修复

**Comment by core-admin** [comment]
> 一般是异步操作导致元素无法被沙箱拦截，这是目前沙箱上的设计缺陷，回在后续版本中修复

收到

**Comment by hanxujoy88** [comment]
> 一般是异步操作导致元素无法被沙箱拦截，这是目前沙箱上的设计缺陷，回在后续版本中修复

求问下这个问题会在近期版本中修复吗？

**Comment by fangcao7618** [comment]
解决后，这里会关闭问题么？还是在官网中哪里提一个这个BUG解决么？

**Comment by sunft1996** [comment]
问下作者最新进度咋样啦，modal样式丢失

> 一般是异步操作导致元素无法被沙箱拦截，这是目前沙箱上的设计缺陷，回在后续版本中修复
