### ISSUE TITLE
拼写错误：文档里的第一图 Controller not Controler

### ISSUE THREAD

**Issue by haixiangyan** [jd-opensource/micro-app#262]
## 背景
文档的介绍[这一章](https://zeroing.jd.com/docs.html#/) 里的 "Controler" 应为 "Controller"。

<img width="1005" alt="f135ab0912746bd6" src="https://user-images.githubusercontent.com/17061654/151295687-95a9e598-eeb6-401e-9f6e-bad7d1fecfda.png">

![](https://user-images.githubusercontent.com/17061654/151295481-a44ff8c1-dd12-49a6-8ef4-7d2e3978595d.png)

## 期望的效果

Controller

**Comment by bailicangdu** [comment]
好的，谢谢提醒
