### ISSUE TITLE
已经配置跨域，GET可以请求数据，POST/DELETE失败

### ISSUE THREAD

**Issue by MichaelSign** [jd-opensource/micro-app#263]
> 
![image](https://user-images.githubusercontent.com/14855698/151346460-0b4b4e78-ebdb-43e5-90da-c88044dd76d0.png)

> 
![image](https://user-images.githubusercontent.com/14855698/151346636-6f89f70c-1239-4306-b8aa-f8d641d2fdea.png)

**Comment by ysneo** [comment]
这个是预请求的错误， option devserver 处理不了，你让后端把跨域加上吧，我之前也是这个问题

**Comment by zhen-one** [comment]
Allow-Header
允许下POST/DELETE
