### ISSUE TITLE
能否提供刷新子应用的api 让子应用界面重新渲染

### ISSUE THREAD

**Issue by Kryzeno** [jd-opensource/micro-app#268]
能否提供刷新子应用的api 让子应用界面重新渲染

**Comment by bailicangdu** [comment]
会的，下个大版本会增加相关api

**Comment by Kryzeno** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。

**Comment by qianqian05723** [comment]
这个刷新子应用是当keep-alive为true时，能够手动重新加载子应用吗？@bailicangdu

> 会的，下个大版本会增加相关api

这个刷新子应用是当keep-alive为true时，能够手动重新加载子应用吗？@bailicangdu

**Comment by Kryzeno** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。

**Comment by bailicangdu** [comment]
@qianqian05723 可以，我们会提供强刷新和弱刷新两种不同形式

**Comment by AhhhhhChiu** [comment]
我尝试了手动unmount然后重新start但没有效果，有没有其他方式可以尝试，现在改一点就要手动刷新太痛苦了

**Comment by bailicangdu** [comment]
> 我尝试了手动unmount然后重新start但没有效果，有没有其他方式可以尝试，现在改一点就要手动刷新太痛苦了

删除micro-app元素重新插入

**Comment by keuby** [comment]
@bailicangdu 下个版本大概会在什么时候?

**Comment by Kryzeno** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。

**Comment by shi-gui** [comment]
快更新吧

**Comment by Kryzeno** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。
