### ISSUE TITLE
请问如何解决子应用cookie 的问题

### ISSUE THREAD

**Issue by wtZZx** [jd-opensource/micro-app#27]
发现子应用在加载后，不会发送服务器下发给父应用的 cookie 诶，这样会导致在子应用内部请求出现鉴权失败的问题。

**Comment by bailicangdu** [comment]
怎么请求的，请求什么类型的数据？

**Comment by bailicangdu** [comment]
请求后端接口是应用自行控制的

**Comment by wtZZx** [comment]
:sweat_smile: 解决了，是部署的问题。。。

**Comment by liujszbwx** [comment]
大佬，本地会出现这个问题吗？我这边就是加载子应用的接口或者js之类的文件，不会携带cookie，但是请求子应用入口的时候会携带
