### ISSUE TITLE
子应用加载腾讯地图报错

### ISSUE THREAD

**Issue by involker** [jd-opensource/micro-app#274]
子应用动态加载腾讯地图，设置script.setAttribute("ignore", "true")后js文件加载没问题，但是地图会额外加载一个请求导致跨域
![image](https://user-images.githubusercontent.com/23690689/153330675-ae267fc7-da5b-453e-a31c-d3324e7c1bbe.png)
请问有什么好的处理方案吗？

**Comment by bailicangdu** [comment]
这是因为localhost非授权域名的导致的吧，使用webpack设置代理可以在开发环境避免这个问题

**Comment by Ytime** [comment]
> 这是因为localhost非授权域名的导致的吧，使用webpack设置代理可以在开发环境避免这个问题

请问拉取子应用的时候，fetch跨域的js文件时报错白屏这种情况怎么避免呢？哪里可以catch这些错误

**Comment by bailicangdu** [comment]
最好的方式是让js文件支持跨域，如果不行可以设置ginore属性避免报错白屏，参考 https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/configure?id=ignore%e5%bf%bd%e7%95%a5%e5%85%83%e7%b4%a0 ，更高级的做法是重定义fetch方法，开发者可以自由掌控某些文件的处理 https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/advanced?id=_1%e3%80%81%e8%87%aa%e5%ae%9a%e4%b9%89fetch

**Comment by Ytime** [comment]
嗯，多谢哈

**Comment by involker** [comment]
> 这是因为localhost非授权域名的导致的吧，使用webpack设置代理可以在开发环境避免这个问题

子应用单独启动是没有这个问题的。我把fetch重写了，直接忽略了这个请求暂时没问题了

**Comment by iYogic2** [comment]
按此操作 do like this:  https://github.com/micro-zoe/micro-app/issues/1009
