### ISSUE TITLE
浏览器路径变了，但子应用页面不渲染，要刷新页面或点击其他页面再点击本页面才显示内容

### ISSUE THREAD

**Issue by LadyChatterleyLover** [jd-opensource/micro-app#276]
<img width="1440" alt="截屏2022-02-10 下午8 01 09" src="https://user-images.githubusercontent.com/35223515/153404896-9adf96f4-ce61-4895-a56e-051d07cd6a23.png">
如图显示，第一次点击child-vue2的home，正常显示home组件的内容，但再次点击about，如下图所示，浏览器路径变了，但about页面内容不显示，还是显示的home页面的内容，要刷新页面或者点击首页，再次点击about才正常，vue2子应用和vue3子应用都有此问题
<img width="1290" alt="截屏2022-02-10 下午8 02 49" src="https://user-images.githubusercontent.com/35223515/153405065-628a03bd-c3e0-4458-bcd3-b60d38bc2338.png">
示

**Comment by LadyChatterleyLover** [comment]
侧边栏在基座应用当中，使用的是element-plus的menu组件的路由模式进行跳转

**Comment by bailicangdu** [comment]
通过基座无法控制子应用的跳转

**Comment by bailicangdu** [comment]
参考 https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/jump
