### ISSUE TITLE
请问一下基座应用和子应用之间有没有共享依赖的解决方案？

### ISSUE THREAD

**Issue by LadyChatterleyLover** [jd-opensource/micro-app#278]
比如基座应用和子应用都会使用element-plus，有没有共享依赖的解决方案呢？如果应用都安装依赖，是不是有点浪费资源了。

**Comment by bailicangdu** [comment]
micro-app并没有提供类似的功能，只能由用户自己实现。可行的方案如：1、基座通过data下发实例或方法  2、webpack dll

**Comment by bailicangdu** [comment]
我们也正在考虑从框架角度提供一种组件级别的共享功能

**Comment by hechanghong** [comment]
Looking forward to having this feature soon...

**Comment by NicCraver** [comment]
webpack5（Module Federation）还有这个https://github.com/efoxTeam/emp 项目  感觉在共享依赖、组件的方向是不错的

**Comment by LadyChatterleyLover** [comment]
@bailicangdu  好的，期待新功能

**Comment by LadyChatterleyLover** [comment]
@NicCraver  webpack5的联邦模块是可行，但是我们所有的项目的webpack版本都是3或者4，升级代码改动太大并且风险太高。

**Comment by NicCraver** [comment]
@LadyChatterleyLover 只能再等一年两年了

**Comment by y2hlbg** [comment]
> @NicCraver webpack5的联邦模块是可行，但是我们所有的项目的webpack版本都是3或者4，升级代码改动太大并且风险太高。

我这刚升完5，改动也没有想象中的那么夸张。就算不用mf，你也可以把包挂在window底下的自定义变量，子项目引用的时候，把import的东西指向到window下的那个变量。

**Comment by LadyChatterleyLover** [comment]
@y2hlbg 主要是组件库这种大型资源不好办的，小资源可以是用window解决 。

**Comment by zhen-one** [comment]
monorepo

**Comment by richwxd** [comment]
集成lerna呢，是不是就可以共享依赖了

**Comment by zhen-one** [comment]
> 集成lerna呢，是不是就可以共享依赖了

我们公司的项目就是使用Yarn+ lerna

**Comment by small-dots** [comment]
大家还有什么奇妙的想法呀，很需要这个功能

**Comment by fantasticsoul** [comment]
推荐采用[hel-micro](https://github.com/tnfe/hel), 管理[共享模块](https://www.bilibili.com/video/BV15t4y1u7i5/?vd_source=51bc50bf5f860e0d778c49b00d192cee)

**Comment by fantasticsoul** [comment]
推荐采用[hel-micro](https://github.com/tnfe/hel), 管理[共享模块](https://www.bilibili.com/video/BV15t4y1u7i5/?vd_source=51bc50bf5f860e0d778c49b00d192cee)

**Comment by fantasticsoul** [comment]
[hel-mirco](https://juejin.cn/post/7138792768234586148)，就是你想要的答案哦

**Comment by YangAu2022** [comment]
> 比如基座应用和子应用都会使用element-plus，有没有共享依赖的解决方案呢？如果应用都安装依赖，是不是有点浪费资源了。

请问您找到解决方案了吗，遇到了同样的问题

**Comment by chaorenluo** [comment]
https://github.com/chaorenluo/admin-micro-app 可以参考一下实现这个仓库是基于vue+vite的把公用的库和组件抽离出来实现一个模块联邦的机制

**Comment by chaorenluo** [comment]
https://github.com/chaorenluo/admin-micro-app 可以参考一下实现这个仓库是基于vue+vite的把公用的库和组件抽离出来实现一个模块联邦的机制，如果感觉有用欢迎start
