### ISSUE TITLE
文档完善建议

### ISSUE THREAD

**Issue by fengjianying** [jd-opensource/micro-app#28]
框架使用文档已经很清晰，建议官方出一个关于项目部署的文档，瑞思拜！

**Comment by bailicangdu** [comment]
部署和正常项目一样，只要做好跨域和路由就行了

**Comment by fengjianying** [comment]
您说的正常项目只的是单页面应用是吗？

**Comment by fengjianying** [comment]
> 部署和正常项目一样，只要做好跨域和路由就行了
您说的正常项目指的是单页面应用是吗？

**Comment by bailicangdu** [comment]
你在部署时出了问题吗 @fengjianying

**Comment by fengjianying** [comment]
没有出现问题，我只是发现官方文档没有一点点关于部署的说明 ，我就想建议一下是不是应该写一点关于部署的文档或者说明
