### ISSUE TITLE
子应用window上的__MICRO_APP_ENVIRONMENT__等变量丢失

### ISSUE THREAD

**Issue by mursumomo** [jd-opensource/micro-app#282]
## 问题描述
> 本地启动起来是没有问题的，子应用上各个环境变量正常
> 打包发到线上后，发现子应用的代理window(__MICRO_APP_PROXY_WINDOW__)不存在了
> 子应用本应该注入的micro的环境变量也不复存在

## 复现步骤
1.本地
![image](https://user-images.githubusercontent.com/43238460/153860979-e495ce2e-0795-4610-bc8b-e3c9999bfd30.png)

2.线上
![image](https://user-images.githubusercontent.com/43238460/153861175-cef0f8a4-56dc-4812-9ac7-c001de07dcc7.png)

试了好几次没法本地复现。出现问题的仓库与其余仓库并没有任何区别。

## 环境信息
- micro-app版本：0.8.5
- 主应用前端框架&版本：vue + vite
- 子应用前端框架&版本：vue + webpack
- 构建工具&版本：

**Comment by bailicangdu** [comment]
回退到0.8.4版本试一下呢

**Comment by mursumomo** [comment]
> 

一样的，原来使用的是0.6的版本，猜测以为是版本太低的缘故，升级后，还是老样子

**Comment by luvletterldl** [comment]
@ice-musru 你的是不是基座是history，子应用是hash的情况下？ 我也碰到了这个问题，如果基座和子应用都是history的路由，子应用就能拿得到，@bailicangdu 大佬，有空看下？

**Comment by Qujh97** [comment]
我也遇到了同样的问题，但这不是丢失，而是打包后沙箱失效了，子应用直接访问了主应用的window。
我通过排查，发现是在子应用升级了vue-cli导致
升级前（正常）
```
{
    "@vue/cli-plugin-eslint": "~4.5.0",
    "@vue/cli-plugin-router": "~4.5.0",
    "@vue/cli-plugin-typescript": "~4.5.0",
    "@vue/cli-plugin-unit-jest": "~4.5.0",
    "@vue/cli-service": "~4.5.0",
}
```
升级后（生产环境沙箱失效）
```
{
    "@vue/cli-plugin-eslint": "~5.0.1",
    "@vue/cli-plugin-router": "~5.0.1",
    "@vue/cli-plugin-typescript": "~5.0.1",
    "@vue/cli-plugin-unit-jest": "~5.0.1",
    "@vue/cli-service": "~5.0.1",
}
```

**Comment by bailicangdu** [comment]
vue-cli 5 在打包后使用esm，导致沙箱失效

**Comment by Relaxe111** [comment]
I have same issue with vite 3 react sub app? I there any solution to this?
