### ISSUE TITLE
基座应用和子应用都是vite+react

### ISSUE THREAD

**Issue by Macromer** [jd-opensource/micro-app#283]
Failed to resolve module specifier "/node_modules/vite/dist/client/env.mjs". Invalid relative url or base scheme isn't hierarchical
Uncaught TypeError: Failed to resolve module specifier "/@react-refresh". Invalid relative url or base scheme isn't hierarchical.
Uncaught TypeError: Failed to resolve module specifier "/node_modules/.vite/react.js?v=22bb5dc8". Invalid relative url or base scheme isn't hierarchical.

**Comment by zhen-one** [comment]
这个官网有写
https://cangdu.org/micro-app/docs.html#/zh-cn/framework/vite
<img width="967" alt="image" src="https://user-images.githubusercontent.com/38104555/154662574-b08b5289-5abd-46f6-90f0-699113c7a3ad.png">
按照文档改下基座应用就ok了

**Comment by Macromer** [comment]
我是这样改了   还是会有这个问题

**Comment by zhen-one** [comment]
> 我是这样改了 还是会有这个问题

看了下我的项目
子应用也需要编写插件 补全资源地址

**Comment by Macromer** [comment]
> > 我是这样改了 还是会有这个问题
> 
> 看了下我的项目 子应用也需要编写插件 补全资源地址

主要问题是子应用写了补全资源就成功了一次，这就很气。老兄有代码地址吗，我看看到底差在什么地方

**Comment by zhen-one** [comment]
> > > 我是这样改了 还是会有这个问题
> > 
> > 
> > 看了下我的项目 子应用也需要编写插件 补全资源地址
> 
> 主要问题是子应用写了补全资源就成功了一次，这就很气。老兄有代码地址吗，我看看到底差在什么地方

没什么特殊的 子应用就按照文档编写了一个vite插件

`basepath`就是服务所在的域名

<img width="704" alt="image" src="https://user-images.githubusercontent.com/38104555/154886126-7e44302a-c4b9-4975-b852-6f1cfbce68f4.png">

``` javascript
	return {
		name: "vite:micro-app",
		apply: "build",
		configResolved(config) {
			// 获取资源地址前缀
			basePath = `${basePath}${config.base}${config.build.assetsDir}/`;
		},
		renderChunk(code, chunk) {
			// build后，import会通过相对地址引入模块，需要将其补全
			if (chunk.fileName.endsWith(".js") && /(from|import)(\s*['"])(\.\.?\/)/g.test(code)) {
				code = code.replace(/(from|import)(\s*['"])(\.\.?\/)/g, (all, $1, $2, $3) => {
					return all.replace($3, new URL($3, basePath).href);
				});
			}
			return code;
		},
	};
```

**Comment by bailicangdu** [comment]
基座有进行适配吗
<img width="1183" alt="image" src="https://user-images.githubusercontent.com/20297227/154899208-a3689d72-e408-4723-b6b3-e90689c9e467.png">

**Comment by Macromer** [comment]
> 基座有进行适配吗 <img alt="image" width="1183" src="https://user-images.githubusercontent.com/20297227/154899208-a3689d72-e408-4723-b6b3-e90689c9e467.png">

有的，现在还是报这个错     ===》
![image](https://user-images.githubusercontent.com/36805569/154902243-cc039edc-aa5e-4b10-abdd-c72fa13ea2ae.png)

**Comment by Macromer** [comment]
> > > > 我是这样改了 还是会有这个问题
> > > 
> > > 
> > > 看了下我的项目 子应用也需要编写插件 补全资源地址
> > 
> > 
> > 主要问题是子应用写了补全资源就成功了一次，这就很气。老兄有代码地址吗，我看看到底差在什么地方
> 
> 没什么特殊的 子应用就按照文档编写了一个vite插件
> 
> `basepath`就是服务所在的域名
> 
> <img alt="image" width="704" src="https://user-images.githubusercontent.com/38104555/154886126-7e44302a-c4b9-4975-b852-6f1cfbce68f4.png">
> 
> ```js
> 	return {
> 		name: "vite:micro-app",
> 		apply: "build",
> 		configResolved(config) {
> 			// 获取资源地址前缀
> 			basePath = `${basePath}${config.base}${config.build.assetsDir}/`;
> 		},
> 		renderChunk(code, chunk) {
> 			// build后，import会通过相对地址引入模块，需要将其补全
> 			if (chunk.fileName.endsWith(".js") && /(from|import)(\s*['"])(\.\.?\/)/g.test(code)) {
> 				code = code.replace(/(from|import)(\s*['"])(\.\.?\/)/g, (all, $1, $2, $3) => {
> 					return all.replace($3, new URL($3, basePath).href);
> 				});
> 			}
> 			return code;
> 		},
> 	};
> ```

有完整项目的地址吗   方便给一个吗

**Comment by zhen-one** [comment]
> > > > > 我是这样改了 还是会有这个问题
> > > > 
> > > > 
> > > > 看了下我的项目 子应用也需要编写插件 补全资源地址
> > > 
> > > 
> > > 主要问题是子应用写了补全资源就成功了一次，这就很气。老兄有代码地址吗，我看看到底差在什么地方
> > 
> > 
> > 没什么特殊的 子应用就按照文档编写了一个vite插件
> > `basepath`就是服务所在的域名
> > <img alt="image" width="704" src="https://user-images.githubusercontent.com/38104555/154886126-7e44302a-c4b9-4975-b852-6f1cfbce68f4.png">
> > ```js
> > 	return {
> > 		name: "vite:micro-app",
> > 		apply: "build",
> > 		configResolved(config) {
> > 			// 获取资源地址前缀
> > 			basePath = `${basePath}${config.base}${config.build.assetsDir}/`;
> > 		},
> > 		renderChunk(code, chunk) {
> > 			// build后，import会通过相对地址引入模块，需要将其补全
> > 			if (chunk.fileName.endsWith(".js") && /(from|import)(\s*['"])(\.\.?\/)/g.test(code)) {
> > 				code = code.replace(/(from|import)(\s*['"])(\.\.?\/)/g, (all, $1, $2, $3) => {
> > 					return all.replace($3, new URL($3, basePath).href);
> > 				});
> > 			}
> > 			return code;
> > 		},
> > 	};
> > ```
> 
> 有完整项目的地址吗 方便给一个吗

完整的没办法给，你可以把你的代码开个repo，帮你看一下

**Comment by bailicangdu** [comment]
基座里microApp.start()那部分的代码贴一下看看

**Comment by Macromer** [comment]
> 基座里microApp.start()那部分的代码贴一下看看

![image](https://user-images.githubusercontent.com/36805569/154906498-09a04534-6a01-410c-bd54-c9c2f1de391d.png)

**Comment by bailicangdu** [comment]
就是这里的问题了，这四处要改
<img width="807" alt="image" src="https://user-images.githubusercontent.com/20297227/154906836-186799d7-80aa-43bb-9b8e-2df6f355e916.png">

**Comment by bailicangdu** [comment]
贴一下某个demo的配置，以供参考 
<img width="868" alt="image" src="https://user-images.githubusercontent.com/20297227/154907458-28764f44-485c-45fc-a18c-0bdfd2002135.png">

**Comment by Macromer** [comment]
![image](https://user-images.githubusercontent.com/36805569/154907823-1d3fd8c2-d908-4882-a40a-1cc18a185fc5.png)
大佬 帮看一下呢

**Comment by bailicangdu** [comment]
差不多，你启动看一下

**Comment by Macromer** [comment]
还是一样 的问题

**Comment by bailicangdu** [comment]
`<micro-app>`元素代码和`vite.config.js`的代码发一下

**Comment by Macromer** [comment]
![image](https://user-images.githubusercontent.com/36805569/154910495-3dd016c3-2b90-46c6-9be4-2fc0373ea154.png)
我把代码传上来了   你看能访问到不

**Comment by bailicangdu** [comment]
<img width="1121" alt="image" src="https://user-images.githubusercontent.com/20297227/154911853-15691dae-89e0-4736-99ac-e455fa2bc08e.png">

**Comment by Macromer** [comment]
感谢大佬

**Comment by Macromer** [comment]
![image](https://user-images.githubusercontent.com/36805569/154918487-a4cdc900-dc5f-4349-ba95-73ddc79827d4.png)
子应用里面图片访问不到呢

**Comment by bailicangdu** [comment]
> ![image](https://user-images.githubusercontent.com/36805569/154918487-a4cdc900-dc5f-4349-ba95-73ddc79827d4.png) 子应用里面图片访问不到呢

文档里有写
<img width="1111" alt="image" src="https://user-images.githubusercontent.com/20297227/154932982-fd3f4fe0-f8be-473b-ab9b-3f11af731063.png">

**Comment by Qujh97** [comment]
子应用用vite不太友好，个人实践后有很多小问题，建议还是webpack吧

**Comment by jiangkaifree** [comment]
成功了吗？ 我基座 ，子应用都是vite react

**Comment by jiangkaifree** [comment]
xdm 我的成功了 突然之间开窍了。 所以当你一下子解决不了，那不妨抽根烟 ，或者睡一觉 试试。 修改了一点文档。希望能能讲解的清楚一下。

下面是我的完整配置 (关键是 `name` 参数保持一致)：

基座应用配置
```js
// 入口页面
<micro-app
  name="basename" // name(必传)：应用名称
  url="http://localhost:3001/basename/"
  inline // 使用内联script模式
  disableSandbox // 关闭沙箱
></micro-app>

// 入口 main.js
import microApp from '@micro-zoe/micro-app'

// microApp.start()
microApp.start({
  plugins: {
    modules: {
      // 注意这里 子应用的name值
      "basename": [{
        loader(code) {
          if (process.env.NODE_ENV === 'development') {
            // 这里 basename 需要和子应用vite.config.js中base的配置保持一致
            code = code.replace(/(from|import)(\s*['"])(\/basename\/)/g, all => {
              return all.replace('/basename/', 'http://localhost:3001/basename/')
            })
          }

          return code
        }
      }]
    }
  }
})
```

子应用除了要修改挂载的id外，还需要:
```js
// vite.config.js
import { join } from 'path';
import { writeFileSync } from 'fs';

export default defineConfig({
  base: `${process.env.NODE_ENV === 'production' ? 'http://my-site.com' : ''}/basename/`,
  plugins: [

    (function () {
      let basePath = '';
      return {
        name: 'basename',
        apply: 'build',
        configResolved(config) {
          basePath = `${config.base}${config.build.assetsDir}/`;
        },
        writeBundle(options, bundle) {
          for (const chunkName in bundle) {
            if (Object.prototype.hasOwnProperty.call(bundle, chunkName)) {
              const chunk = bundle[chunkName];
              if (chunk.fileName && chunk.fileName.endsWith('.js')) {
                chunk.code = chunk.code.replace(
                  /(from|import\()(\s*['"])(\.\.?\/)/g,
                  (all, $1, $2, $3) => {
                    return all.replace($3, new URL($3, basePath));
                  },
                );
                const fullPath = join(options.dir, chunk.fileName);
                writeFileSync(fullPath, chunk.code);
              }
            }
          }
        },
      };
    })(),
  ],
})
```

**Comment by wangyuan0108** [comment]
> xdm 我的成功了 突然之间开窍了。 所以当你一下子解决不了，那不妨抽根烟 ，或者睡一觉 试试。 修改了一点文档。希望能能讲解的清楚一下。
> 
> 下面是我的完整配置 (关键是 `name` 参数保持一致)：
> 
> 基座应用配置
> 
> ```js
> // 入口页面
> <micro-app
>   name="basename" // name(必传)：应用名称
>   url="http://localhost:3001/basename/"
>   inline // 使用内联script模式
>   disableSandbox // 关闭沙箱
> ></micro-app>
> 
> // 入口 main.js
> import microApp from '@micro-zoe/micro-app'
> 
> // microApp.start()
> microApp.start({
>   plugins: {
>     modules: {
>       // 注意这里 子应用的name值
>       "basename": [{
>         loader(code) {
>           if (process.env.NODE_ENV === 'development') {
>             // 这里 basename 需要和子应用vite.config.js中base的配置保持一致
>             code = code.replace(/(from|import)(\s*['"])(\/basename\/)/g, all => {
>               return all.replace('/basename/', 'http://localhost:3001/basename/')
>             })
>           }
> 
>           return code
>         }
>       }]
>     }
>   }
> })
> ```
> 
> 子应用除了要修改挂载的id外，还需要:
> 
> ```js
> // vite.config.js
> import { join } from 'path';
> import { writeFileSync } from 'fs';
> 
> export default defineConfig({
>   base: `${process.env.NODE_ENV === 'production' ? 'http://my-site.com' : ''}/basename/`,
>   plugins: [
> 
>     (function () {
>       let basePath = '';
>       return {
>         name: 'basename',
>         apply: 'build',
>         configResolved(config) {
>           basePath = `${config.base}${config.build.assetsDir}/`;
>         },
>         writeBundle(options, bundle) {
>           for (const chunkName in bundle) {
>             if (Object.prototype.hasOwnProperty.call(bundle, chunkName)) {
>               const chunk = bundle[chunkName];
>               if (chunk.fileName && chunk.fileName.endsWith('.js')) {
>                 chunk.code = chunk.code.replace(
>                   /(from|import\()(\s*['"])(\.\.?\/)/g,
>                   (all, $1, $2, $3) => {
>                     return all.replace($3, new URL($3, basePath));
>                   },
>                 );
>                 const fullPath = join(options.dir, chunk.fileName);
>                 writeFileSync(fullPath, chunk.code);
>               }
>             }
>           }
>         },
>       };
>     })(),
>   ],
> })
> ```

## 按照这个接入也没有成功啊（react+webpack主 +  vite+react子）
![image](https://user-images.githubusercontent.com/22407253/191697109-e14fda80-89cc-44ff-a1dd-0d2e2c9b6880.png)

**Comment by X-W-W** [comment]
> > xdm 我的成功了 突然之间开窍了。 所以当你一下子解决不了，那不妨抽根烟 ，或者睡一觉 试试。 修改了一点文档。希望能能讲解的清楚一下。
> > 下面是我的完整配置 (关键是 `name` 参数保持一致)：
> > 基座应用配置
> > ```js
> > // 入口页面
> > <micro-app
> >   name="basename" // name(必传)：应用名称
> >   url="http://localhost:3001/basename/"
> >   inline // 使用内联script模式
> >   disableSandbox // 关闭沙箱
> > ></micro-app>
> > 
> > // 入口 main.js
> > import microApp from '@micro-zoe/micro-app'
> > 
> > // microApp.start()
> > microApp.start({
> >   plugins: {
> >     modules: {
> >       // 注意这里 子应用的name值
> >       "basename": [{
> >         loader(code) {
> >           if (process.env.NODE_ENV === 'development') {
> >             // 这里 basename 需要和子应用vite.config.js中base的配置保持一致
> >             code = code.replace(/(from|import)(\s*['"])(\/basename\/)/g, all => {
> >               return all.replace('/basename/', 'http://localhost:3001/basename/')
> >             })
> >           }
> > 
> >           return code
> >         }
> >       }]
> >     }
> >   }
> > })
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 子应用除了要修改挂载的id外，还需要:
> > ```js
> > // vite.config.js
> > import { join } from 'path';
> > import { writeFileSync } from 'fs';
> > 
> > export default defineConfig({
> >   base: `${process.env.NODE_ENV === 'production' ? 'http://my-site.com' : ''}/basename/`,
> >   plugins: [
> > 
> >     (function () {
> >       let basePath = '';
> >       return {
> >         name: 'basename',
> >         apply: 'build',
> >         configResolved(config) {
> >           basePath = `${config.base}${config.build.assetsDir}/`;
> >         },
> >         writeBundle(options, bundle) {
> >           for (const chunkName in bundle) {
> >             if (Object.prototype.hasOwnProperty.call(bundle, chunkName)) {
> >               const chunk = bundle[chunkName];
> >               if (chunk.fileName && chunk.fileName.endsWith('.js')) {
> >                 chunk.code = chunk.code.replace(
> >                   /(from|import\()(\s*['"])(\.\.?\/)/g,
> >                   (all, $1, $2, $3) => {
> >                     return all.replace($3, new URL($3, basePath));
> >                   },
> >                 );
> >                 const fullPath = join(options.dir, chunk.fileName);
> >                 writeFileSync(fullPath, chunk.code);
> >               }
> >             }
> >           }
> >         },
> >       };
> >     })(),
> >   ],
> > })
> > ```
> 
> ## 按照这个接入也没有成功啊（react+webpack主 + vite+react子）
> ![image](https://user-images.githubusercontent.com/22407253/191697109-e14fda80-89cc-44ff-a1dd-0d2e2c9b6880.png)

demo里面是部署在同一域名下
如果部署的不是同一域名下
修改，base: `${process.env.NODE_ENV === 'production' ? 'http://my-site.com' : ''}/`
或者修改服务器设置，调整入口

**Comment by justrustc** [comment]
我用1.x的版本也遇到这个问题

**Comment by ly75x12** [comment]
版本：1.0.0-beta.4
主应用和子应用都是：vite + react
按照https://micro-zoe.com/docs/1.x/#/zh-cn/framework/vite的示例，子应用使用iframe方式接入遇到了同样的问题
<micro-app name='app1' url='http://localhost:5174/' iframe></micro-app>

报错：
![image](https://user-images.githubusercontent.com/20216981/237019972-ee1349c3-b8b0-475e-bc91-556cba97348d.png)

@bailicangdu

**Comment by levinx7512** [comment]
micro-app版本：1.0.0-beta.4
主应用 / 子应用：都是vite + react

按照1.x的文档 https://micro-zoe.com/docs/1.x/#/zh-cn/framework/vite ，使用iframe方式接入
<micro-app name='xxx' url='xxx' iframe></micro-app>

控制台报错：
Uncaught TypeError: Failed to resolve module specifier "/@react-refresh". 
Invalid relative url or base scheme isn't hierarchical.

@bailicangdu

**Comment by helloworldwk** [comment]
react子应用配置路由basename里，window.__MICRO_APP_BASE_ROUTE__为undefined，我打印了window，里面只有__MICRO_APP_BASE_APPLICATION__为true，有遇到过的吗？
![屏幕截图 2023-07-19 222354](https://github.com/micro-zoe/micro-app/assets/88221609/b012a6d5-dc96-4469-9b1d-980c6357e1db)

**Comment by helloworldwk** [comment]
> react子应用配置路由basename里，window.__MICRO_APP_BASE_ROUTE__为undefined，我打印了window，里面只有__MICRO_APP_BASE_APPLICATION__为true，有遇到过的吗？ ![屏幕截图 2023-07-19 222354](https://user-images.githubusercontent.com/88221609/254605807-b012a6d5-dc96-4469-9b1d-980c6357e1db.png)

__MICRO_APP_ENVIRONMENT__、__MICRO_APP_NAME__、__MICRO_APP_PUBLIC_PATH__这些环境变量window上都没有;__MICRO_APP_BASE_APPLICATION__判断是否为基座应用，竟然在主应用和子应用里都为true;我的主应用是vite+vue3，子应用是vite+react18
