### ISSUE TITLE
如何实现多标签页

### ISSUE THREAD

**Issue by tint** [jd-opensource/micro-app#284]
用作后台开发，需要多标签页功能，不知道怎么实现

**Comment by zandko** [comment]
我目前是通过子应用的路由守卫派发消息通知主应用，由主应用过滤并添加标签页

**Comment by zandko** [comment]
> 用作后台开发，需要多标签页功能，不知道怎么实现

我目前是通过子应用的路由守卫派发消息通知主应用，由主应用过滤并添加标签页
