### ISSUE TITLE
assets中资源路径补全问题

### ISSUE THREAD

**Issue by qianqian05723** [jd-opensource/micro-app#286]
![image](https://user-images.githubusercontent.com/17306867/154207759-246b6d7d-ae46-434b-910c-81215019dee0.png)
页面引用 assets 目录里面的图片时，使用v-show去动态显示时会显示图片404
![image](https://user-images.githubusercontent.com/17306867/154208799-8da5b8ab-0423-4184-a6a2-eb741f3169f8.png)
然后试着补全了路径，刷新后还是404，这个assets中的图片需要怎么处理吗？@bailicangdu

_Originally posted by @qianqian05723 in https://github.com/micro-zoe/micro-app/issues/169#issuecomment-1041153546_

**Comment by bailicangdu** [comment]
ok，我看一下

**Comment by qianqian05723** [comment]
> ok，我看一下
大佬，最近有版本更新吗？感觉会更新不少内容吧...

**Comment by bailicangdu** [comment]
接下来是1.0版本，会有很多更新

**Comment by qianqian05723** [comment]
> 接下来是1.0版本，会有很多更新

那像这种子应用中动态加载的图片路径有解决方案吗？我发现动态加载图片的路径补全了都是有问题...

**Comment by wtZZx** [comment]
升级了之后发现资源补齐有点问题

**Comment by qianqian05723** [comment]
> 升级了之后发现资源补齐有点问题

暂时把资源放到static或者public目录下，只要不打包把路径补全应该可以正常显示吧

**Comment by skyLoveSnap** [comment]
这个问题解决了吗

**Comment by skyLoveSnap** [comment]
![image](https://user-images.githubusercontent.com/40157361/202668293-c596075a-d845-4b90-9049-df0b9efac1c8.png)
