### ISSUE TITLE
移动端引入micro-app后由于改写了window type, 导致fastClick失效

### ISSUE THREAD

**Issue by FANZHETWO** [jd-opensource/micro-app#288]
## 问题描述
>vue^2.6.11  单页面项目，安卓移动端引入micro-app后由打包放在手机上测试，页面点击事件会出现如下错误

## 复现步骤
main.js 里面引入了
```js
import FastClick from 'fastclick'
import microApp from '@micro-zoe/micro-app'
microApp.start()
 FastClick.attach(document.body);
```

## 上传截图

![Uploading image.png…]()

## 错误描述
> Uncaught TypeError: Failed to execute 'initMouseEvent' on 'MouseEvent': parameter 4 is not of type 'Window'.
webpack:///./node_modules/fastclick/lib/fastclick.js?:306:14 TypeError: Failed to execute 'initMouseEvent' on 'MouseEvent': parameter 4 is not of type 'Window'.
at FastClick.sendClick (webpack:///./node_modules/fastclick/lib/fastclick.js?:306:14)
at FastClick.onTouchEnd (webpack:///./node_modules/fastclick/lib/fastclick.js?:606:9)
at HTMLBodyElement.eval (webpack:///./node_modules/fastclick/lib/fastclick.js?:111:38)
at HTMLBodyElement.a.Bugly (<anonymous>:1:156)

## 环境信息
 "fastclick": "^1.0.6",
- micro-app版本：0.8.4
- 主应用前端框架&版本："vue": "^2.6.11",
- 子应用前端框架&版本："vue": "^2.6.11",
- 构建工具&版本：@vue/cli-service@^4.5.0"

**Comment by bailicangdu** [comment]
感谢反馈，我们会尽快对问题进行修复

**Comment by FANZHETWO** [comment]
请问大佬这问题啥时候可以修复呀

**Comment by bailicangdu** [comment]
我们在android12版本上测试，没有复现问题，其它环境信息一致，你的android版本是多少？

**Comment by FANZHETWO** [comment]
子应用不要引入注册 fastclick  就不会有这个问题了，大佬可以关闭缺陷了
