### ISSUE TITLE
Angular 11, 全局数据通信无效

### ISSUE THREAD

**Issue by wincn9000** [jd-opensource/micro-app#289]
## 问题描述
> 问题的具体描述

通过全局方式microApp.setGlobalData({ type: 'data' }); 从基座发给子应用，子应用收不到数据。

## 复现步骤
1.
2.

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。

## 环境信息
- micro-app版本：0.8.5
- 主应用前端框架&版本：angular 11.2.14
- 子应用前端框架&版本：angular 11.2.14
- 构建工具&版本：

**Comment by bailicangdu** [comment]
参考 https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/framework/angular?id=_3%e3%80%81%e9%80%9a%e8%bf%87micro-app%e6%95%b0%e6%8d%ae%e9%80%9a%e4%bf%a1%e4%bf%ae%e6%94%b9angular%e7%bb%84%e4%bb%b6%e6%95%b0%e6%8d%ae%e5%90%8e%e8%a7%86%e5%9b%be%e4%b8%8d%e6%9b%b4%e6%96%b0
