### ISSUE TITLE
子应用怎么监听自己的生命周期

### ISSUE THREAD

**Issue by gk525152097** [jd-opensource/micro-app#29]

**Comment by bailicangdu** [comment]
子应用的js执行则为装载，卸载通过自定义事件监听 https://zeroing.jd.com/micro-app/docs.html#/zh-cn/life-cycles?id=%e5%ad%90%e5%ba%94%e7%94%a8%e5%8d%b8%e8%bd%bd

**Comment by gk525152097** [comment]
> 子应用的js执行则为组件，卸载通过自定义事件监听[https://zeroing.jd.com/micro-app/docs.html#/zh-cn/life-cycles?id=%e5%ad%90 %e5%ba%94%e7%94%a8%e5%8d%b8%e8%bd%bd](https://zeroing.jd.com/micro-app/docs.html#/zh-cn/life-cycles?id=%e5%ad%90%e5%ba%94%e7%94%a8%e5%8d%b8%e8%bd%bd)

不是 是子应用自己 自己不能监听生命周期吗

**Comment by bailicangdu** [comment]
![image](https://user-images.githubusercontent.com/20297227/128815536-2a846eca-39d7-4413-9b2f-6a10c6f44ac6.png)

**Comment by bailicangdu** [comment]
对于子应用只有两个周期，挂载和卸载，js被执行就是挂载，卸载用上面这个事件

**Comment by hjiog** [comment]
子应用必须监听卸载事件吗？
 window.addEventListener('unmount', function () {
  ReactDOM.unmountComponentAtNode(document.getElementById('root'))
})
这个逻辑可以统一在框架层面处理嘛？
