### ISSUE TITLE
有没有原生JS版本的基座Demo啊啊啊啊,谢谢

### ISSUE THREAD

**Issue by yunnuoyang** [jd-opensource/micro-app#290]
LayUI或者Ext.js（主应用）+vue3的子应用Demo

**Comment by bailicangdu** [comment]
不支持esm的环境不太合适

**Comment by wtZZx** [comment]
我们有一个不支持esm的jquery的老项目，是将引入 microapp 的入口文件编写好后使用 rollup 打成 iife 的包，用 <script> 直接导入的 :joy:

**Comment by jackchoumine** [comment]
> 我们有一个不支持esm的jquery的老项目，是将引入 microapp 的入口文件编写好后使用 rollup 打成 iife 的包，用 <script> 直接导入的 😂

可以上一个demo 吗，我也遇到这样的问题

**Comment by putao88** [comment]
> 我们有一个不支持esm的jquery的老项目，是将引入 microapp 的入口文件编写好后使用 rollup 打成 iife 的包，用 <script> 直接导入的 😂

你好,请问入口文件是怎么写的,如何打包成file文件,有代码demo吗,目前我们项目也有这样的场景
