### ISSUE TITLE
vue2项目，基站和子应用都是hash路由模式，子应用路由回退会卸载子应用

### ISSUE THREAD

**Issue by FANZHETWO** [jd-opensource/micro-app#293]
## 问题描述
> vue2项目，基站和子应用都是hash路由模式，子应用路由回退会直接卸载子应用，整个子应用的hash都被清掉了

## 复现仓库
[这是可以复现的demo](https://github.com/FANZHETWO/micro-app-demo)

## 复现步骤 
1. 基站 页面点击  【跳转微页面】 按钮
2. 子应用页面点击 page2 路由跳转
3. 点击 【back 】 按钮返回 

## 环境信息
- micro-app版本：latest
- 主应用前端框架&版本："vue": "^2.6.11",
- 子应用前端框架&版本："vue": "^2.6.11",
- 构建工具&版本：

**Comment by bailicangdu** [comment]
这是路由设置的问题，因为基座和子应用都是hash路由，所以子应用需要设置baseroute，具体方式如下：

<img width="1435" alt="image" src="https://user-images.githubusercontent.com/20297227/155679454-85c0dec9-b556-403c-a398-e1c11bfa387a.png">

<img width="1230" alt="image" src="https://user-images.githubusercontent.com/20297227/155679502-e39f2d97-58d2-404e-b57f-d85c64759ddb.png">

**Comment by bailicangdu** [comment]
文档中有xian相关说明

<img width="1103" alt="image" src="https://user-images.githubusercontent.com/20297227/155679634-0329d152-bb20-4312-adc5-60a4c34fa8c2.png">

**Comment by FANZHETWO** [comment]
我增加 root-app.vue 文件设置了baseroute 路径也是一样哦，您可以从 [这个demo测试效果](https://github.com/FANZHETWO/micro-app-demo)  具体操作步骤如下：
1、基站 页面点击 【跳转微页面】 按钮
2、子应用页面点击 page2 路由跳转
3、点击 【back 】 按钮返回

看 "vue-router": "3.0.1",  源码 对于 this.$router.back()  返回调用的是window.history.go(-1),  请问子应用这样调用是不是就意味调用到基础页面的路由返回了，因此导致了子应用的卸载

**Comment by bailicangdu** [comment]
根据截图提供的信息修改就可以了，已经测试过正常运行

**Comment by FANZHETWO** [comment]
> 



> 根据截图提供的信息修改就可以了，已经测试过正常运行

大佬，我在子应用里面多加了几个页面，从第三个页面返回就会出现子应用卸载问题。 [这是重现代码](https://github.com/FANZHETWO/micro-app-demo)

具体操作步骤如下：
1、基站 页面点击 【跳转微页面】 按钮
2、子应用页面点击 【goPAGE2】
3、点击 【goPAGE3】
4、点击 【back】

**Comment by bailicangdu** [comment]
> > 
> 
> > 根据截图提供的信息修改就可以了，已经测试过正常运行
> 
> 大佬，我在子应用里面多加了几个页面，从第三个页面返回就会出现子应用卸载问题。 [这是重现代码](https://github.com/FANZHETWO/micro-app-demo)
> 
> 具体操作步骤如下： 1、基站 页面点击 【跳转微页面】 按钮 2、子应用页面点击 【goPAGE2】 3、点击 【goPAGE3】 4、点击 【back】

一切正常呀

**Comment by xuya227939** [comment]
@bailicangdu 我试了下，非必现；多试几次就出来了，从 page3 返回 page2 的时候，空白

**Comment by zhiyouai** [comment]
> > 
> 
> > 根据截图提供的信息修改就可以了，已经测试过正常运行
> 
> 大佬，我在子应用里面多加了几个页面，从第三个页面返回就会出现子应用卸载问题。 [这是重现代码](https://github.com/FANZHETWO/micro-app-demo)
> 
> 具体操作步骤如下： 1、基站 页面点击 【跳转微页面】 按钮 2、子应用页面点击 【goPAGE2】 3、点击 【goPAGE3】 4、点击 【back】

我也遇到了同样的问题，请问现在有相应的解决方案嘛@bailicangdu
