### ISSUE TITLE
angular1.X加gulp怎么作为基座应用

### ISSUE THREAD

**Issue by yumeiqiang** [jd-opensource/micro-app#294]
公司有一个老项目是angular1.X➕gulp的，想把他作为基座应用重构下，有相应的示例可以参考嚒

**Comment by bailicangdu** [comment]
angular1没用过，太老了😶 不过你可以参考其它angular版本的接入方式 https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/framework/angular

**Comment by LKCheng** [comment]
vue2为基座，angular1.x 为子应用，路由已经变化了，内容渲染出不来怎么回事。

**Comment by bailicangdu** [comment]
> vue2为基座，angular1.x 为子应用，路由已经变化了，内容渲染出不来怎么回事。

直接在基座修改url地址无法影响到子应用，只能通过子应用内部跳转

**Comment by LKCheng** [comment]
子应用内部已经自动跳转到登录页面了，基座的路由也已经发生变化了。但是就是子应用依然无内容显示，未报错

**Comment by lzbabd** [comment]
> 公司有一个老项目是angular1.X➕gulp的，想把他作为基座应用重构下，有相应的示例可以参考嚒

@yumeiqiang 你好，请问angular1.X作为基座解决了吗？
