### ISSUE TITLE
子应用页面使用回退快捷键，会使基座应用页面回退

### ISSUE THREAD

**Issue by Horoll** [jd-opensource/micro-app#296]
基座与主应用均为vue2.x+vue-router 3.x，且都为hash模式。在子应用页面使用鼠标侧键回退会直接让基座页面回退

**Comment by bailicangdu** [comment]
这是正常的

**Comment by Horoll** [comment]
> 这是正常的

请问有什么可行的方法可以规避这个问题吗？

**Comment by FANZHETWO** [comment]
我也遇到了这个问题，我在子应用里面多加了几个页面，从第三个页面返回就会出现子应用卸载问题。 [这是重现代码](https://github.com/FANZHETWO/micro-app-demo)

具体操作步骤如下：
1、基站 页面点击 【跳转微页面】 按钮
2、子应用页面点击 【goPAGE2】
3、点击 【goPAGE3】
4、点击 【back】

请问有啥解决思路没，新项目就卡这块了。。泪奔。。。

**Comment by bailicangdu** [comment]
> 

没有办法，因为鼠标控制的是浏览器返回，而不是某一个应用

**Comment by caihai123** [comment]
我在使用浏览器回退时会子应用会直接到404页面

**Comment by bailicangdu** [comment]
> 我在使用浏览器回退时会子应用会直接到404页面

vue3吗

**Comment by caihai123** [comment]
> 



> > 我在使用浏览器回退时会子应用会直接到404页面
> 
> vue3吗
vue2的，主应用使用的history，子应用使用的hash，并且带有keep-alive

**Comment by bailicangdu** [comment]
@caihai123 可以提供一个demo吗

**Comment by caihai123** [comment]
> @caihai123 可以提供一个demo吗

可以的 我弄一个

**Comment by caihai123** [comment]
> 

我写了个demo，但是没有这个问题，好像只出现在我的项目中，我明天再检查😁

**Comment by caihai123** [comment]
> @caihai123 可以提供一个demo吗

出现的原因应该是子应用中路由表最后一行我添加了`{ path: "*", redirect: "/404" },`，我做了个demo，可以麻烦你看一下吗。https://github.com/caihai123/icestark-bug-demo

**Comment by bailicangdu** [comment]
@caihai123 keep-alive应用确实有这样的问题，这个问题已经在1.0.0-alpha.1中解决，升级新版本或者将404的路由配置删除

**Comment by wjy18666** [comment]
主应用：vite + vue3，配置了3个路由[
  '/main-vite/platform/user-permission/system-permission/#/system-permission',
  '/main-vite/platform/user-permission/user-group/#/user-group',
  '/main-vite/platform/user-permission/user/#/user'
]，这3个路由都是用的同一个<micro-app />组件，加载的都是同一个子应用，根据url跳转子应用不同的页面而已;

子应用：vue-cli5 + vue3，404路由屏蔽了；

父子应用都是用的vue-router 4.x版本，主应用点击上述3个菜单页面切换跳转后，点击浏览器返回出现404（跳转到主应用的404页面了）；切换时会触发这个子应用的mount和unmount钩子函数，请问这是bug还是使用不对，能提供解决思路吗？非常感谢

**Comment by wjy18666** [comment]
主应用history路由，子应用hash路由，有知道问题的能指导下，非常感谢
