### ISSUE TITLE
vue2作为基座应用，vite作为子项目接入报错

### ISSUE THREAD

**Issue by liulin0524** [jd-opensource/micro-app#297]
![image](https://user-images.githubusercontent.com/32123161/155970428-9cafa923-ce00-4556-b0d2-fab536ea611e.png)

disablesandbox已关闭
![image](https://user-images.githubusercontent.com/32123161/155970619-6e97ec1f-318d-41de-864e-64326cc454da.png)

**Comment by bailicangdu** [comment]
<img width="1211" alt="image" src="https://user-images.githubusercontent.com/20297227/155971719-59a14177-66a4-4208-a9d8-d9b7f6554b8d.png">

**Comment by liulin0524** [comment]
谢谢，已经整好，想关掉提问呢，您这回复够快，点赞
