### ISSUE TITLE
vite react模版的初始化项目报错

### ISSUE THREAD

**Issue by lileilei** [jd-opensource/micro-app#3]
希望添加尽可能多模版来验证micro-app的稳定性，包括nextjs 等比较常用的框架的demo案例

**Comment by bailicangdu** [comment]
vite的处理比较麻烦，可以参考 https://cangdu.org/micro-app/docs.html#/zh-cn/other?id=_3%e3%80%81%e9%80%82%e9%85%8dvite

**Comment by Rabbitzzc** [comment]
vite 作为子应用，不可以放在沙箱里面么...

**Comment by lileilei** [comment]
> vite 作为子应用，不可以放在沙箱里面么...
参考楼上的 修改module加载路径应该可以解决
