### ISSUE TITLE
子应用更新问题

### ISSUE THREAD

**Issue by junsen313** [jd-opensource/micro-app#30]
子应用fetch过一次之后会缓存下来，如果这时子应用版本有更新，在不刷新浏览器的情况下，如何重新fetch新的子应用？

**Comment by bailicangdu** [comment]
可以使用destory强制删除缓存，https://zeroing.jd.com/micro-app/docs.html#/zh-cn/configure?id=destory

**Comment by junsen313** [comment]
> 可以使用destory强制删除缓存，https://zeroing.jd.com/micro-app/docs.html#/zh-cn/configure?id=destory

这需要先切换应用才会触发卸载删除缓存吧？有主动清除缓存方法或重新加载方法吗？

**Comment by wtZZx** [comment]
:eyes: + 1， 希望可以暴露出子应用的生命周期方法，便于手动控制

**Comment by bailicangdu** [comment]
@junsen313 如果子应用已经渲染，无法修改，这和浏览器中打开页面一样

**Comment by bailicangdu** [comment]
@wtZZx 你可以通过数据通信向基座应用暴露方法，控制子应用的渲染和更新，这样做更加灵活，如果从框架层面控制，会影响到所有应用，无论这个应用是否需要暴露方法。

**Comment by junsen313** [comment]
> @junsen313 如果子应用已经渲染，无法修改，这和浏览器中打开页面一样

恩，确实。但是，我的意思已经渲染的子应用可以重新渲染（拉取最新的资源），单单是子应用区域重新加载渲染。

**Comment by bailicangdu** [comment]
> > @junsen313 如果子应用已经渲染，无法修改，这和浏览器中打开页面一样
> 
> 恩，确实。但是，我的意思已经渲染的子应用可以重新渲染（拉取最新的资源），单单是子应用区域重新加载渲染。

删除micro-app元素后重新渲染，或者修改name值，这些都是相当于卸载应用后渲染，但是会有一段时间白屏

**Comment by junsen313** [comment]
> > > @junsen313 如果子应用已经渲染，无法修改，这和浏览器中打开页面一样
> > 
> > 
> > 恩，确实。但是，我的意思已经渲染的子应用可以重新渲染（拉取最新的资源），单单是子应用区域重新加载渲染。
> 
> 删除micro-app元素后重新渲染，或者修改name值，这些都是相当于卸载应用后渲染，但是会有一段时间白屏

恩，明白了。
