### ISSUE TITLE
问下 子应用的定位不准确问题该怎么解决

### ISSUE THREAD

**Issue by Kryzeno** [jd-opensource/micro-app#303]
![image](https://user-images.githubusercontent.com/7607957/156494026-3a85f485-4ae1-41c8-8f09-76fa774264b1.png)

**Comment by Kryzeno** [comment]
![image](https://user-images.githubusercontent.com/7607957/156494408-c2ccd18a-f8ef-4f2f-baaf-066b5d020c86.png)
正常应该是这样的 组件是用的vxe table

**Comment by bailicangdu** [comment]
应该是样式冲突，检查一下css定位

**Comment by Kryzeno** [comment]
![image](https://user-images.githubusercontent.com/7607957/156505033-014846c0-7562-4838-a7d2-47bc33df50fd.png)
我看了下 不是冲突的问题   不知道是什么原因导致的属性值计算出错

**Comment by Kryzeno** [comment]
我看了vxe table这个第三方组件是拿主应用的window去计算出这个top left的距离的 所以导致计算错误  有没办法避免 让他能正确的拿子应用的windows offsetHeight去计算

**Comment by Kryzeno** [comment]
这个window不是隔离的吗 怎么会这样的

**Comment by bailicangdu** [comment]
window窗口的信息是唯一的，这种情况需要你自行调整样式

**Comment by Kryzeno** [comment]
![image](https://user-images.githubusercontent.com/7607957/156547624-28c87252-6dd1-4639-9623-fd052ecf3896.png)
是不是框架对vxe table的这段代码逻辑有影响

**Comment by Kryzeno** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。

**Comment by 273063020** [comment]
你好，请问这个问题目前解决了吗？

**Comment by Kryzeno** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。
