### ISSUE TITLE
关于父子应用都需要登录，在Chrome高版本浏览器的Bug

### ISSUE THREAD

**Issue by scrushy** [jd-opensource/micro-app#305]
micro-app和iframe一样，会触发谷歌SameSite Cookie限制。子应用将不能携带Cookie，会出现一直跳转的情况。不清楚这个是BUG还是设计如此？因为在做乾坤验证的时候，并不会触发该限制。

**Comment by scrushy** [comment]
<img width="1678" alt="image" src="https://user-images.githubusercontent.com/23580390/156713320-dcb9c28b-e574-407d-b283-f6816ee78410.png">

**Comment by bailicangdu** [comment]
micro-app默认是不带cookie的

**Comment by bailicangdu** [comment]
你的chrome版本是多少？可以描述一下复现的步骤吗

**Comment by scrushy** [comment]
据了解90+以上的chrome就禁用了三方cookie，我当前的谷歌版本号是：98.0.4758.80（正式版本） (x86_64)
测试的是前后端分离的项目，前端会请求需要登录的后台接口，跳转去登录，但是我们登录是基于session的方案
以micro-app嵌入，浏览器会识别出子应用是三方cookie，和iframe一样出现类似的效果。
相信大多场景前端都是需要去登录的，不是很好复现
