### ISSUE TITLE
同一个页面能支持的micro-app的个数上限是？

### ISSUE THREAD

**Issue by houyhea** [jd-opensource/micro-app#306]
为micro-app的另辟蹊径的思路点个赞先！

然后请教一下，同一个页面能支持的micro-app的个数上限是多少？在不影响性能的情况下，且打开了webcomponent 和js sandbox。比如，我们考虑一个场景，用micro-app来做一个web的插件架构的B端系统，将一个web页面拆分成若干个micro-app组件。是否可行？

**Comment by bailicangdu** [comment]
理论上没有上限，但micro-app以应用为维度，必须使用html作为入口，所以不适合组件级别的嵌入，组件复用最好使用webpack5模块联邦

**Comment by sunnynudt** [comment]
> 理论上没有上限，但micro-app以应用为维度，必须使用html作为入口，所以不适合组件级别的嵌入，组件复用最好使用webpack5模块联邦

@bailicangdu 请教一下，micro-app是否可以兼容加载webpack 5的模块联邦组件呢？或者需要我们开发一些插件来支持这种能力吗？有什么好的建议或者思路吗？
