### ISSUE TITLE
vue2为基座，vue2的子应用路由跳转的时候出现：Loading chunk 0 failed.

### ISSUE THREAD

**Issue by Barford** [jd-opensource/micro-app#307]
![image](https://user-images.githubusercontent.com/64939605/156999561-94c9eec5-3498-4039-90d1-5016cc738fe5.png)
![image](https://user-images.githubusercontent.com/64939605/156999702-f51d3d5e-d764-44c3-a5d0-1017eca24395.png)
![image](https://user-images.githubusercontent.com/64939605/156999740-8c0ea388-df34-4381-8084-439d6659dd0a.png)

**Comment by wastone** [comment]
我这也出现了，vue2子应用是采用的异步路由，并且是根据数据动态addRoute的

**Comment by wastone** [comment]
试了多次，发现子应用路由改为同步组件，不使用异步组件就可以了，这是为什么

**Comment by wastone** [comment]
找到造成这个问题的地方在哪了：
基座应用和子应用都是vue2应用，vue.config.js都配置了
```
webpack的alias: {
        '@': resolve('src')
      }
```
子应用路由的组件路径写的是@/views/**,
这个路径如果不适用@改为../src/views就不报这个错了，
但是还没有分析为什么出现这个问题

**Comment by xuyingjie** [comment]
复现：通过 vue-cli 创建的 vue2 应用，build后上传到 cdn，做为子应用地址，这个子应用沙箱会失效

**Comment by bailicangdu** [comment]
> 复现：通过 vue-cli 创建的 vue2 应用，build后上传到 cdn，做为子应用地址，这个子应用沙箱会失效

这是vue-cli5出现的问题，临时解决方案有两个 1、降级到vue-cli4，重新build  2、将打包后的index.html中script标签中type='module'的部分去掉

**Comment by bailicangdu** [comment]
我们会在下个版本解决这个问题

**Comment by hupan508** [comment]
哪个版本已经修复。我使用最新版[1.0.0-alpha.10](https://www.npmjs.com/package/@micro-zoe/micro-app/v/1.0.0-alpha.10) 还是无效
