### ISSUE TITLE
这个框架可以嵌入任意网站不，用于做爬虫的

### ISSUE THREAD

**Issue by 372798735** [jd-opensource/micro-app#309]
这个框架可以嵌入任意网站不，用于做爬虫的,类似下面图片的效果的

**Comment by 372798735** [comment]
![image](https://user-images.githubusercontent.com/52733319/157184354-f0ac573b-1186-4e0e-86f0-6c7fc0ab763b.png)

**Comment by bailicangdu** [comment]
可以嵌，但是太麻烦了，不建议使用

**Comment by bailicangdu** [comment]
micro-app适合single-spa

**Comment by 372798735** [comment]
好的，谢谢
