### ISSUE TITLE
嵌套应用的孙应用收不到全局数据

### ISSUE THREAD

**Issue by lonelygoogle** [jd-opensource/micro-app#312]
## 问题描述
有3个应用都是从cra创建的最简单永远没有其他逻辑 ，ABC，A是基座应用，B是A的子应用，C是B的子应用。
当我在主应用A或者B，发出全局数据时候，C收不到，当把C应用放在B的平级的时候，是可以接收到全局数据的

问题，如何实现子应用到孙应用的数据传输？ 谢谢

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。

## 环境信息
- micro-app版本：
- 主应用前端框架&版本：
- 子应用前端框架&版本：
- 构建工具&版本：

**Comment by bailicangdu** [comment]
全局数据通讯只能在父子层级

**Comment by lonelygoogle** [comment]
> 

这个回复速度是光速啊 ，谢谢。那如何实现子应用和孙应用的数据书传输呢？谢谢

**Comment by bailicangdu** [comment]
子应用本身也有数据通信系统，如同父子通讯一样

**Comment by lonelygoogle** [comment]
> 子应用本身也有数据通信系统，如同父子通讯一样

> 
谢谢这么热心回答我，依旧是说B应用也要按照基座应用配置 然后就可以了？ 我昨天是误打误撞 把B应用这么配置：
import microApp from '@micro-zoe/micro-app'

// setGlobalData只接受对象作为参数
microApp.setGlobalData({type: '全局数据'})
此时C应用作为孙应用是可以接收到数据。
