### ISSUE TITLE
子应用中使用第三方得依赖，依赖需要window变量，怎么处理？

### ISSUE THREAD

**Issue by qianqian05723** [jd-opensource/micro-app#313]
## 问题描述
> 子应用使用了第三方依赖，需要window变量，因为沙箱得缘故取不到变量

![image](https://user-images.githubusercontent.com/17306867/157819547-32aaad1f-8823-4b7b-8f76-23aa55cc6894.png)

## 上传截图
![image](https://user-images.githubusercontent.com/17306867/157819939-e901f869-d3f1-4af9-b06d-c05458918e26.png)

想用这种插件方式修改window => window.rawWindow得话应该只适用<script>加进来得资源吧？？?

如果是依赖得话有办法解决吗？

## 环境信息
- micro-app版本：latest
- 主应用前端框架&版本：nuxt@latest
- 子应用前端框架&版本：nuxt@latest
- 构建工具&版本：webpack@4

**Comment by bailicangdu** [comment]
这是ssr吧，在node环境使用了window变量，和微前端没关系

**Comment by qianqian05723** [comment]
> 这是ssr吧，在node环境使用了window变量，和微前端没关系

感谢大佬提醒，发现了组件用client-only包裹跑在了客户端，依赖仍然跑在两边了...依赖也改成client就可以了 = =!
