### ISSUE TITLE
是否考虑采用ShadowRealms替换proxy实现沙箱

### ISSUE THREAD

**Issue by typistZxd** [jd-opensource/micro-app#314]
## 背景
> 描述您希望改进的问题。

通过proxy代理window实现的沙箱，可能存在以下问题：

- with指定作用域导致查找非指定作用域变量变慢
- Function执行js字符串导致集成之后，调试子应用困难
- proxy可能带来的[Vue diff失效](https://github.com/micro-zoe/micro-app/discussions/259)

## 期望的效果

考虑采用ShadowRealms实现沙箱

**Comment by bailicangdu** [comment]
ShadowRealm还不成熟

**Comment by LinFeng1997** [comment]
@typistZxd 
1. 这个通过缓存一些常用的全局变量，如 Math/Object 等可以优化性能瓶颈，其他的场景基本不会因为访问作用域造成性能问题
2. 可以通过 inline 模式调试子应用
