### ISSUE TITLE
有没有在子应用获取全部主应用下发的数据的方法

### ISSUE THREAD

**Issue by Qujh97** [jd-opensource/micro-app#315]
## 背景
目前已有api只能获取改变的数据，需要频繁使用的数据无法通过已有api获取到

## 期望的效果
目前做法是把所有数据挂在子应用的window上。不知道是不是我没有在文档中找到，想要类似`window.microApp.getAllData()`获取全部数据的效果。

**Comment by Qujh97** [comment]
我看文档中`const data = window.microApp.getData()`表达的意思似乎是能获取全部数据，但实际上我获取到的依然只是改变的数据

**Comment by bailicangdu** [comment]
新数据会全量覆盖旧数据，只能应用自己记录数据
