### ISSUE TITLE
子应用script标签引入的js文件，其他文件拿不到文件内容

### ISSUE THREAD

**Issue by tanqin** [jd-opensource/micro-app#316]
## 问题描述
> 通过主应用( Vue 应用)跳转到子应用（Vue 应用），子应用 index.html 中通过 script 标签引入的 js 文件，在子应用的其他 vue 页面中报 undefined。如果单独运行子应用，并不会发生以上问题。

## 上传截图
> 
![error1](https://user-images.githubusercontent.com/63828394/158101359-0e25dd08-70c4-44dc-ae74-e171ef512e82.png)

![error2](https://user-images.githubusercontent.com/63828394/158101314-96dcbd19-3dd6-4329-a2ad-4e2a2dc019a5.png)

## 环境信息
- micro-app版本：0.8.5
- 主应用前端框架&版本：vue: 2.6.11
- 子应用前端框架&版本：vue: 2.6.12

**Comment by bailicangdu** [comment]
参考 https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/questions?id=_12%e3%80%81%e9%94%99%e8%af%af%e4%bf%a1%e6%81%af%ef%bc%9axxx-%e6%9c%aa%e5%ae%9a%e4%b9%89

**Comment by tanqin** [comment]
> 参考 https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/questions?id=_12%e3%80%81%e9%94%99%e8%af%af%e4%bf%a1%e6%81%af%ef%bc%9axxx-%e6%9c%aa%e5%ae%9a%e4%b9%89

已解决

**Comment by haoshaojing** [comment]
楼主怎么解决的呢，急求
