### ISSUE TITLE
子应用使用elementplus版本1.0以上的tabel组件，会出现table组件配置height或者maxheight属性后，进入该页面后，项目直接崩溃的情况。

### ISSUE THREAD

**Issue by eeeeeeeg** [jd-opensource/micro-app#317]
## 问题描述
> micro-app的子应用 项目使用vue3 + elementplus@2.1.1 组件库中的table组件在使用height或maxheight属性时，系统会崩溃

## 复现步骤
1.提供子应用，项目地址为 https://github.com/eeeeeeeg/tomicro
![image](https://user-images.githubusercontent.com/51465940/158108570-777abb0b-cf06-4da0-ae5d-460e4913785f.png)
可通过切换这两行代码发现配置了height或者maxheight，进去页面后 系统会直接崩溃，无控制台报错
2.

## 上传截图
> 
![image](https://user-images.githubusercontent.com/51465940/158108637-9f737bc8-0218-4969-afec-9a42edc4c828.png)

## 复现仓库
> (https://github.com/eeeeeeeg/tomicro)
## 环境信息
- micro-app版本：0.6.0
- 主应用前端框架&版本：@angular~12.1.0,
- 子应用前端框架&版本："vue": "^3.2.13",
- 构建工具&版本："@angular/cli": "~12.1.0", vue-cli@~5.0.0

**Comment by bailicangdu** [comment]
这只有子应用的demo，试了一下，没有问题
