### ISSUE TITLE
keep-alive 功能开启后，同一子应用内跳转不刷新子应用的路由

### ISSUE THREAD

**Issue by xiangxinji** [jd-opensource/micro-app#324]
## 问题描述
主应用 main , 子应用 app 
我在 main 中配置了 keep-alive , 然后通过 vue-router 的push 从 app 的 A 页面跳转到 app 的B  页面 。 

浏览器 url 变了， 但是页面还是 A 页面的内容

## 复现步骤
1. 在main 中使用 keep-alive
2. 使用 vue-router push 同一个子应用 

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。
![image](https://user-images.githubusercontent.com/58387767/158931348-68d11eac-2a49-4e73-b0c2-1408cb2fdc8b.png)
![image](https://user-images.githubusercontent.com/58387767/158931396-509782ef-6064-4e8e-be5c-60974420aa6f.png)

## 环境信息
- micro-app版本：0.8.1
- 主应用前端框架&版本："vue": "^3.2.16" ,"vue-router": "^4.0.11",
- 子应用前端框架&版本："vue": "^3.1.5", "vue-router": "^4.0.11",
- 构建工具&版本：主应用："vite": "^2.5.10", app 应用 "@vue/cli-service": "5.0.0-beta.3",

路由确保没问题，因为之前是正常的， 只要我开启keep-alive 就会出现这种情况

**Comment by bailicangdu** [comment]
代码贴一下呢

**Comment by xiangxinji** [comment]
@bailicangdu 是哪一部分的代码， main 那边就是很简单的 router.push 然后会命中那个 micro-app 组件 ，主应用这边也没有keep-alive ， 子应用也没其他东西，都是很平常的
![image](https://user-images.githubusercontent.com/58387767/158934997-7d39b1f3-c850-4d86-9cb7-309940dfab3c.png)
这是 main 的应用路由跳转

**Comment by xiangxinji** [comment]
但是 micro-app 组件那边可能会有一些逻辑，就是去获取主应用的一些样式或者啥的一些信息
![image](https://user-images.githubusercontent.com/58387767/158935523-ebb23306-6512-4ca7-aa3f-bb244f5b40b5.png)
![image](https://user-images.githubusercontent.com/58387767/158935575-4d3c898d-4290-4265-ab00-776dea25d6ba.png)

不知道这个有没有影响


@bailicangdu

**Comment by xiangxinji** [comment]
就是我在子应用中打印路由相关的信息，还是上一次的。 虽然主应用通过 keep-alive 缓存了这个子应用， 是不是路由这种信息要重新更新，而不是简单的全部缓存。

**Comment by bailicangdu** [comment]
参考 https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/keep-alive?id=_1%e3%80%81%e5%86%8d%e6%ac%a1%e6%b8%b2%e6%9f%93%e6%97%b6url%e5%92%8c%e9%a1%b5%e9%9d%a2%e4%b8%8d%e5%8c%b9%e9%85%8d

**Comment by xiangxinji** [comment]
@bailicangdu  好的 ，刚刚我也看到了这个， 非常感谢, 挺喜欢这个框架的， 希望早日 1.0
