### ISSUE TITLE
执行远程scrtipt报错

### ISSUE THREAD

**Issue by Betula-L** [jd-opensource/micro-app#33]
**如何复现？**

执行远程script，script报错无法执行
![image](https://user-images.githubusercontent.com/6059935/129016172-ec74013e-3634-4360-a872-8d0ea1d2564a.png)

**debug信息：**
控制台打日志发现，执行远程脚本的info.code被替换成了远程地址html，而不是''。

![image](https://user-images.githubusercontent.com/6059935/129016219-a16981dc-2945-4f5b-b04d-c6228b60e490.png)

![image](https://user-images.githubusercontent.com/6059935/129016054-67b88b2d-0817-428e-bf6c-764f64fc71d7.png)

子应用中执行脚本文件有问题，但是执行text code没问题

![image](https://user-images.githubusercontent.com/6059935/129016845-3584404e-e2eb-4c47-9eaa-7b6a5a1d0a1a.png)

**Comment by bailicangdu** [comment]
micro-app的配置麻烦发一下

**Comment by Betula-L** [comment]
@bailicangdu 


嵌入的子应用可以这样启动，子应用页面 http://localhost:16686
项目地址: https://github.com/jaegertracing/jaeger-ui

```
docker run -d -e QUERY_BASE_PATH=/jaeger -e COLLECTOR_ZIPKIN_HTTP_PORT=9411 -p 5775:5775/udp -p 6831:6831/udp -p 6832:6832/udp -p 5778:5778  -p 16686:16686 -p 14268:14268  -p 14269:14269   -p 9411:9411 jaegertracing/all-in-one:latest
```

![image](https://user-images.githubusercontent.com/6059935/129022486-bd921841-2856-4bbe-897a-79b8cafacadc.png)

**Comment by bailicangdu** [comment]
js的地址会根据url地址进行补全，所以会补全为 http://.../dependencies/static/js/xxx.js，这个地址找不到，所以兜底到html上了

**Comment by Betula-L** [comment]
我想把这个开源项目作为子应用改造一下，子应用public path是/jaeger，但是路由配半天也没配明白。感觉还是需要详细说明一下路由怎么配。。

**Comment by bailicangdu** [comment]
micro-app的url只是html地址，推荐看一下文档中的路由部分：https://zeroing.jd.com/micro-app/docs.html#/zh-cn/route

![image](https://user-images.githubusercontent.com/20297227/129025900-5c4825e1-3585-4044-b4d5-91f6ebe9aa92.png)

**Comment by bailicangdu** [comment]
当然还有一些细节上的注意点，我们会在文档中补充的，谢谢提醒

**Comment by loo41** [comment]
@bailicangdu 是不是还存在这样一个问题，子应用请求的 url 并不能以相对地址补全，我的请求（方便统一域名），实际上会自动补全为基座的主域。但是又不能在window下重写 XMLHttpRequest 和 fetch, 是不是可以在沙盒里面重新补全一下，还是通过插件实现，又或者让用户写死代码？

**Comment by wangxm87** [comment]
请问楼主如何解决的?我也碰到了类似的问题.在子应用react的public目录里面添加了一些js,然后集成到主工程之后发现这些js都找不到~~如果楼主解决了的话，麻烦告诉下解决思路，谢谢了～～

**Comment by wangxm87** [comment]
请问楼主如何解决的?我也碰到了类似的问题.在子应用react的public目录里面添加了一些js,然后集成到主工程之后发现这些js都找不到~~如果楼主解决了的话，麻烦告诉下解决思路，谢谢了～～

**Comment by bailicangdu** [comment]
js 默认提取到后台运行，如果想要看到这些js，可以配置inline模式 https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/configure?id=inline
