### ISSUE TITLE
window[`micro-app-${window.__MICRO_APP_NAME__}`] 为undefined 为什么呢

### ISSUE THREAD

**Issue by jiangruifeng** [jd-opensource/micro-app#330]
![image](https://user-images.githubusercontent.com/27045566/159424717-f428b45e-1817-4852-be33-62ee136e7250.png)

**Comment by bailicangdu** [comment]
这是需要用户设置的值

**Comment by jiangruifeng** [comment]
![image](https://user-images.githubusercontent.com/27045566/160111660-d35f62d1-c6f3-497c-b5fe-1194650d5c4c.png)
如果我只写85行，刷新后子应用将不显示，除非是从主应用界面切换到子应用否则子应用不显示 ，但是我看案例刷新却是正常的

**Comment by tiseny** [comment]
window 对象未激活， 切换到 angular 应用的时候， window 对象依然停留在  window.__MICRO_APP_PROXY_WINDOW__  中。
