### ISSUE TITLE
一直报MIME type ("text/html") 

### ISSUE THREAD

**Issue by LengYXin** [jd-opensource/micro-app#331]
一直报 EventSource's response has a MIME type ("text/html") that is not "text/event-stream". Aborting the connection.
虽然没有什么影响吧。
还是循环的，看着很不舒服
![image](https://user-images.githubusercontent.com/19631404/159615120-7564f1e7-d0b5-4056-8bbe-c5576e8a8999.png)
跟 webpakc 的这个东西有关吧。热更新？
__webpack_hmr/client

**Comment by bailicangdu** [comment]
开发环境的问题，一般是socket请求兜底到基座的html导致报错。

**Comment by bailicangdu** [comment]
子应用是用什么脚手架创建的？

**Comment by LengYXin** [comment]
> 



> 子应用是用什么手架搭建的？

子应用是 nuxt 的2.x版本

**Comment by 0vn** [comment]
在根目录的 server.js 中，更改如下：
`
app.all('*', (req, res, next) => {
  let url = req.url;
  if (url.includes('/__webpack_hmr')) return;
  res.header("Access-Control-Allow-Origin", '*')
  next()
})
`
