### ISSUE TITLE
动态添加脚本会被捕获并且注释后塞在micro-app-head里面

### ISSUE THREAD

**Issue by yolkerrr** [jd-opensource/micro-app#332]
## 问题描述
动态添加脚本会被捕获并且注释后塞在micro-app-head里面

## 复现步骤
在子应用中通过getScript函数动态加载脚本，会micro-app环境中会被捕获并且注释后塞在micro-app-head里面

## 上传截图
>
![image](https://user-images.githubusercontent.com/58155364/159645860-02b851ca-df75-40cf-bfa4-5ad6574f0d85.png)
![image](https://user-images.githubusercontent.com/58155364/159645981-4a116601-c17c-41f2-9d57-5f58bea7e196.png)
![image](https://user-images.githubusercontent.com/58155364/159646026-79701e3c-daa4-4c93-aa70-4b6eed31b7b4.png)

我该如何配置或者说有更好的解决方案

**Comment by bailicangdu** [comment]
https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/configure?id=inline

**Comment by yolkerrr** [comment]
> 
这个方案会影响性能吗
![image](https://user-images.githubusercontent.com/58155364/159652211-69f005ac-efc3-4dd4-b0c9-8311eda863b9.png)

**Comment by bailicangdu** [comment]
正常情况下不需要设置inline，默认模式就行
