### ISSUE TITLE
父子应用都是hash路由，一个页面里该怎么嵌入多个子组件

### ISSUE THREAD

**Issue by scrushy** [jd-opensource/micro-app#333]
父子应用都是hash路由，一个页面里该怎么嵌入多个应用呢？

文档中描述如下： 那我有两个micro-app，怎么匹配浏览器呢

子应用是hash路由，我们要渲染子应用的page1页面，那么在micro-app的url属性上设置hash值是无效的，#/page1应该添加到浏览器地址上。

<micro-app url='http://www.xxx.com/#/page1'></micro-app>

<micro-app url='http://www.xxx.com/'></micro-app>
复制代码Error复制成功

**Comment by panyouqing** [comment]
@scrushy 请问你解决了吗？谢谢

**Comment by dongoa** [comment]
双hash解决了嘛

**Comment by TerminatorSd** [comment]
> 父子应用都是hash路由，一个页面里该怎么嵌入多个应用呢？
> 
> 文档中描述如下： 那我有两个micro-app，怎么匹配浏览器呢
> 
> 子应用是hash路由，我们要渲染子应用的page1页面，那么在micro-app的url属性上设置hash值是无效的，#/page1应该添加到浏览器地址上。
> 
> 复制代码Error复制成功

micro-app的url只能是不带路由的域名地址，如果要让子应用跳转到特定路由，两个办法
1、直接最外层主应用的url就跳转到那个路由值
2、主应用给子应用传递一个值，子应用拿到这个值之后使用router.push进行跳转
不过需要注意，子应用路由发生跳转时，也会影响到主应用的路由，所以要注意两者不能出现重复路由
