### ISSUE TITLE
v0.8.5 版本部署上线后 在使用微前端的页面强刷会出现卡死的情况

### ISSUE THREAD

**Issue by hzfvictory** [jd-opensource/micro-app#334]
## 问题描述
> v0.8.5 版本部署上线后 在使用微前端的页面强刷会出现卡死的情况，退到0.8.1恢复正常

## 环境信息
- micro-app版本：0.8.5
- 主应用前端框架&版本：vue 2.6.12
- 子应用前端框架&版本：vue 2.6.12
- 构建工具&版本：webpack

**Comment by hzfvictory** [comment]
貌似跟版本没啥关系 在页面强刷五六次就复现了

**Comment by bailicangdu** [comment]
无法复现 https://www.micro-zoe.com/main-vue2/app-vue2，可以提供一个demo吗

**Comment by hzfvictory** [comment]
晚会吧  我好好排查下 也可能是fetch请求堵塞了，一直是pending状态
