### ISSUE TITLE
基座中，使用<router-link> 打开了一个子应用的页面，然后再使用<router-link> 打开了这个子应用的另外一个页面，页面不刷新。

### ISSUE THREAD

**Issue by weiqi93** [jd-opensource/micro-app#339]
## 问题描述
> 基座中，使用<router-link> 打开了一个子应用的页面，然后再使用<router-link> 打开了这个子应用的另外一个页面，这时候页面不刷新。

## 复现步骤
1. 基座中  <router-link to="/member/about">，可以正常打开about页面。
2. 基座中 <router-link to="/member/home">，页面不会刷新，也不能正常显示home页面。

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。

## 环境信息
- micro-app版本：0.8.5
- 主应用前端框架&版本：vue2
- 子应用前端框架&版本：vue2
- 构建工具&版本：webpack

**Comment by bailicangdu** [comment]
参考 https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/jump

**Comment by jiangruifeng** [comment]
你需要通知子应用
