### ISSUE TITLE
vue keep-alive不能缓存子应用状态吗

### ISSUE THREAD

**Issue by gk525152097** [jd-opensource/micro-app#34]
用路由做子应用切换 给子应用渲染到vuekeepalive里 也会被卸载掉 是不能缓存状态吗

**Comment by bailicangdu** [comment]
你的意思是基座使用vuekeepalive保存子应用的状态吗，这样不行的，micro-app元素从文档中删除就会进行卸载操作，我们无法知道它是不是keepalive的状态

**Comment by gk525152097** [comment]
> 你的英文是你可以使用vuekeepal的状态，这样不能的，微应用元素文档从中删除会进行卸载，操作我们不知道它不是keepalive的状态

所以现在只能通过display：none 来保持子应用状态 吗

**Comment by bailicangdu** [comment]
display：none  的确是一种解决方案
