### ISSUE TITLE
有人遇到刷新后子应用不显示的问题吗，切换一下父应用，子应用就显示了

### ISSUE THREAD

**Issue by jiangruifeng** [jd-opensource/micro-app#341]

**Comment by bailicangdu** [comment]
大概率是路由配置问题

**Comment by jiangruifeng** [comment]
![image](https://user-images.githubusercontent.com/27045566/160331073-c65214bf-31fe-440e-8bda-39388f697501.png)

**Comment by jiangruifeng** [comment]
但是自己写的样式就会丢失。。

**Comment by jiangruifeng** [comment]
大佬刷新后并没有走mount方法 ，跟路由有关系吗这时候路由还没注入呢吧

**Comment by jiangruifeng** [comment]
> 大概率是路由配置问题

大佬刷新后并没有走mount方法 ，跟路由有关系吗这时候路由还没注入呢吧

**Comment by bailicangdu** [comment]
代码贴一下

**Comment by jiangruifeng** [comment]
主应用
![image](https://user-images.githubusercontent.com/27045566/160391433-81024169-6bf0-44f9-afaa-8a18f2188862.png)

子应用
![image](https://user-images.githubusercontent.com/27045566/160391553-76a30aa9-3798-4136-808c-2eb93eabc320.png)

然后第一次进入子应用mount方法没有执行
有两个question
    1.当切换到主应用其他路由再进入子应用时才会正常展示
    2.刷新子应用界面 子应用不展示，想要展示同1

**Comment by bailicangdu** [comment]
信息太少了，能提供一个demo吗

**Comment by gaomingchao** [comment]
@jiangruifeng 我也遇到这个问题，你解决了吗？

**Comment by gaomingchao** [comment]
我也遇到这个问题，问题原因：主应用路由没配好，path 需要匹配子应用下所有路由
**有问题的路由**
`
      path: '/app1',
      name: app1,
      component: MicroAppRouter,
 `
**解决**
` path: '/app1/:path(.*)*',
  name: app1,
  component: MicroAppRouter,`

**Comment by jiangruifeng** [comment]
我加了/* 的呀

**Comment by jiangruifeng** [comment]
> 我也遇到这个问题，问题原因：主应用路由没配好，path 需要匹配子应用下所有路由 **有问题的路由** `path: '/app1', name: app1, component: MicroAppRouter,` **解决** ` path: '/app1/:path(.*)*', name: app1, component: MicroAppRouter,`

我是vue2的项目加了 /* ，你这个/ :path(.*)* 哪里的写法呀

**Comment by longshenzhu** [comment]
问题解决了吗？我也碰到这个问题：我的问题是开发环境没问题，部署后直接加载子路由，基座没加载出来

> > 我也遇到这个问题，问题原因：主应用路由没配好，path 需要匹配子应用下所有路由 **有问题的路由** `path: '/app1', name: app1, component: MicroAppRouter,` **解决** ` path: '/app1/:path(.*)*', name: app1, component: MicroAppRouter,`
> 
> 我是vue2的项目加了 /* ，你这个/ :path(._)_ 哪里的写法呀

**Comment by jiangruifeng** [comment]
> 

没解决 我换成qiankun了 嘎嘎香

**Comment by jiangruifeng** [comment]
> 问题解决了吗？我也碰到这个问题：我的问题是开发环境没问题，部署后直接加载子路由，基座没加载出来
> 
> > > 我也遇到这个问题，问题原因：主应用路由没配好，path 需要匹配子应用下所有路由 **有问题的路由** `path: '/app1', name: app1, component: MicroAppRouter,` **解决** ` path: '/app1/:path(.*)*', name: app1, component: MicroAppRouter,`
> > 
> > 
> > 我是vue2的项目加了 /* ，你这个/ :path(._)_ 哪里的写法呀

没解决 我换别的框架了 这个还是等1.0版本吧
