### ISSUE TITLE
为子应用沙箱添加参数

### ISSUE THREAD

**Issue by tuzhu008** [jd-opensource/micro-app#343]
在实际使用过程中，基座需要向子应用传递一些初始化的数据或者提供一些方法。目前探索到使用当前框架可以实现的方式：

1. 使用事件机制，基座向子应用下发数据。

   该方式只会缓存最后一次下发的数据，可能会导致数据丢失。

2. 在微应用使用 `window[window.__MICRO_APP_NAME__]`

   该方式需要将数据写在基座上，未清理会导致内存泄漏。微应用间数据未做到隔离。

期望：

能够有种方式，优雅地将数据直接初始化到微应用的沙箱中。

**Comment by LinFeng1997** [comment]
提供一个 Inject 方法？

```ts
microApp.inject(injectData: unknown, appName?: string)
```

如果要清除的话：
```ts
microApp.clearInjectData(appName?: string)
```

**Comment by bailicangdu** [comment]
> 

不错的思路

**Comment by tuzhu008** [comment]
> ```ts
> microApp
> ```

我理解的话，这是一种将参数注入到基座容器的一种实现，但与我此处所描述的并不是同等的概念。最重要的是，并不想要把这些数据写入基座。

**Comment by LinFeng1997** [comment]
@tuzhu008 没理解你的回复，这些 inject 的数据写入基座是指什么意思？
