### ISSUE TITLE
angular8当做基座，按照文档的手把手部分配置启动报错

### ISSUE THREAD

**Issue by qinzhihao-conghua** [jd-opensource/micro-app#344]
![1](https://user-images.githubusercontent.com/33079330/160587639-49802043-e13b-43f2-9d55-6c9969f5f30f.png)

**Comment by bailicangdu** [comment]
这是ts类型声明错误，在tsconfig.ts中配置忽略@micro-zoe/micro-app暂时避免这个问题

**Comment by qinzhihao-conghua** [comment]
> 这是ts类型声明错误，在tsconfig.ts中配置忽略@micro-zoe/micro-app暂时避免这个问题

exclude中已经添加忽略了，但是还是一样

**Comment by bailicangdu** [comment]
不是exclude，是path，看一下ts文档

**Comment by xinb-yanh** [comment]
hello  请问angular 做子应用问题多吗 ？

**Comment by qinzhihao-conghua** [comment]
> hello 请问angular 做子应用问题多吗 ？

用不了
