### ISSUE TITLE
Disconnected from the devServer, trying to reconnect...

### ISSUE THREAD

**Issue by sanmuw** [jd-opensource/micro-app#346]
## 问题描述
> 问题的具体描述

## 复现步骤
1.基座react脚手架/子应用 umi搭建的项目
2.正常文档配置
3. 点击进入 子应用  就会出现
4. Disconnected from the devServer, trying to reconnect...

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。
<img width="1411" alt="image" src="https://user-images.githubusercontent.com/22683369/160645280-b01a1628-1cbf-4abe-9afc-3fc5fc98ffa6.png">

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。

## 环境信息
- micro-app版本：0.8.5
- 主应用前端框架&版本：任何一个项目
- 子应用前端框架&版本：umi搭建的任意版本
- 构建工具&版本：任意

讨论组里也有提问：
https://github.com/micro-zoe/micro-app/discussions/342

**Comment by sanmuw** [comment]
@bailicangdu 能帮忙看下吗？

**Comment by bailicangdu** [comment]
这个问题是umi的websocket加载地址兜底到基座上，导致失败，下一个版本会解决

**Comment by sanmuw** [comment]
> 这个问题是umi的websocket加载地址兜底到基座上，导致失败，下一个版本会解决

谢谢提供了思考方向

**Comment by sanmuw** [comment]
> 这个问题是umi的websocket加载地址兜底到基座上，导致失败，下一个版本会解决

对了 大佬 咱们下一个版本 大概什么时间会发布

**Comment by littlewhiteprogrammer** [comment]
解决了吗，有什么方法解决吗

**Comment by SrandL** [comment]
> 这个问题是umi的websocket加载地址兜底到基座上，导致失败，下一个版本会解决

现在以antd-pro作为主应用，umi为子应用时，仍然会出现这个问题
