### ISSUE TITLE
基座应用的url属性值是子应用的域名时，会报跨域错误Access-Control-Allow-Origin

### ISSUE THREAD

**Issue by JC-Guy** [jd-opensource/micro-app#348]
## 问题描述
> 如题
## 说明
url属性值是本地启动的字应用ip就不会报跨域问题， 值是测试环境的子应用域名的时候就会报跨域（测试环境子应用域名只能内网访问）

## 复现步骤
1. 基座应用中：   <micro-app name="micro-app" url="http://xxx.xxx.com/"  keep-alive :data="microAppData"></micro-app>

2.进入子应用前就报错了，进入子应用前！
## 上传截图
> ![image](https://user-images.githubusercontent.com/40263378/160809805-42e44a43-64d9-4bac-b71a-f5e83cb375ca.png)

## 复现仓库
> 不好意思没有仓库，如果大佬们有遇到和我一样的问题可以在下面留言贴图
## 环境信息
- micro-app版本：0.8.5
- 主应用前端框架&版本：vue  2.6.11
- 子应用前端框架&版本：vue 3.2.31
- 构建工具&版本：webpack 4.46.0

**Comment by waylon233** [comment]
我也遇到这个问题，本地环境基座跳子应用不会报跨域，部署之后就会报跨域，而且F5刷新之后又好了

**Comment by KeithLier** [comment]
一模一样的问题，偶尔会出现跨域，刷新之后就正常，定位不到具体问题，现在有解决的嘛

**Comment by raoenhui** [comment]
静态资源也需要支持跨域

**Comment by Hachiko2018** [comment]
我也遇到这个问题了，基座是localhost，引入的子应用的url用的是sat环境的，然后就报跨域了。这个问题有大佬知道如何解决吗？

**Comment by elarbor** [comment]
我也是，子应用的接口报错：

![Image](https://github.com/user-attachments/assets/e6de6440-1e88-4526-a181-96d334b83858)

![Image](https://github.com/user-attachments/assets/2fe8f82c-9556-4346-9200-c2dd3072c610)
