### ISSUE TITLE
谁在用 micro-app？

### ISSUE THREAD

**Issue by bailicangdu** [jd-opensource/micro-app#35]
大家好，
micro-app已经开源，我们将会积极响应开发者的疑问与反馈，持续不断打磨完善 ，帮助更多开发者提升开发效率，改善开发体验。如果您正在使用micro-app，非常感谢您的支持，欢迎留下公司或产品名，我们会在首页重要位置展示，以鼓励更多开发者采用 micro-app。

回复格式：
```
- 产品：xxx
- 公司或组织：（如果可以）
- 链接：（如果可以）
- 截图：（如果可以）
```

**Comment by renwofei423** [comment]
赞！准备调研试一试。如果真用上了，再来回复吧

**Comment by TinChak** [comment]
赞！准备调研试一试。如果真用上了，再来回复吧

**Comment by han8435762** [comment]
赞！准备调研试一试。如果真用上了，再来回复吧

**Comment by Verten** [comment]
赞！准备调研试一试。如果真用上了，再来回复吧

**Comment by raoenhui** [comment]
- 产品：京东营销投放平台
- 公司或组织：京东
- 链接：https://ace.jd.com

**Comment by zhouliangui** [comment]
好东西，赞一个

**Comment by inier** [comment]
赞！准备调研试一试。如果真用上了，再来回复吧

**Comment by inier** [comment]
数据通信方案有考虑果postmessage

**Comment by WWQ-CODE** [comment]
子应用切换能做到缓存就好了，类似vue中的keep-alive的功能

**Comment by wtZZx** [comment]
我们也上线运行 2 个月左右了，内部老系统的迁移改造项目 :grimacing:

**Comment by y2hlbg** [comment]
> 

请问贵司名称是什么，方便透露嘛

**Comment by y2hlbg** [comment]
> 我们也上线运行 2 个月左右了，内部老系统的迁移改造项目 😬

@wtZZx 请问贵司名字是什么，方便透露嘛

**Comment by whenTheMorningDark** [comment]
使用的同学能说下，怎么打包发布的吗？我卡在这里了。

**Comment by biezhi** [comment]
请问各位 我vue为基座接入react子应用白屏怎么回事。反之不会
