### ISSUE TITLE
[micro-app] app xxx: TypeError: Failed to fetch

### ISSUE THREAD

**Issue by LadyChatterleyLover** [jd-opensource/micro-app#350]
![%EB93%VV39$M@MXDUH1Y7HB](https://user-images.githubusercontent.com/35223515/160997702-7251bf56-8c14-433a-9a3d-f5b8a9770deb.png)
加载子应用会报这个错，但是不影响使用，有办法解决这个问题吗？

**Comment by bailicangdu** [comment]
某一个js或css资源有问题，加载失败

**Comment by LadyChatterleyLover** [comment]
这个有办法排除是哪个文件出错吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "micro-zoe/micro-app"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月31日(星期四) 下午3:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [micro-zoe/micro-app] [micro-app] app xxx: TypeError: Failed to fetch (Issue #350)





 
某一个js或css资源有问题，加载失败

**Comment by bailicangdu** [comment]
先确定是哪个文件，然后参考 https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/configure?id=exclude%e8%bf%87%e6%bb%a4%e5%85%83%e7%b4%a0

**Comment by LadyChatterleyLover** [comment]
好的，那我现在有办法自己确认是哪个文件吗？因为这个报错也看不出来是哪错了。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "micro-zoe/micro-app"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月31日(星期四) 下午3:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [micro-zoe/micro-app] [micro-app] app xxx: TypeError: Failed to fetch (Issue #350)





 
先确定是哪个文件，然后参考 https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/configure?id=exclude%e8%bf%87%e6%bb%a4%e5%85%83%e7%b4%a0

**Comment by xiejunping** [comment]
同问，我的起来也是报这个，但是我用了demo里的vue2起的服务就可以跳进去，是不是跨域设置有问题

**Comment by bailicangdu** [comment]
> 同问，我的起来也是报这个，但是我用了demo里的vue2起的服务就可以跳进去，是不是跨域设置有问题

看一下报错信息是加载哪一个文件失败？

**Comment by better-pz** [comment]
@bailicangdu 求助下，export const injectJS = (jsUrl, cb) => {
  const scriptEle = document.createElement('script');
  scriptEle.type = 'text/javascript';
  scriptEle.onload = function () {
    cb?.();
    scriptEle.remove();
  };
  scriptEle.src = jsUrl;
  scriptEle.setAttribute('ignore', 'true');
  document.getElementsByTagName('head')[0].appendChild(scriptEle);
}; 这样写之后还是有报错，jsUrl是第三放库里面自带的请求

**Comment by raoenhui** [comment]
> jsUrl

报错信息是什么？

**Comment by raoenhui** [comment]
> @bailicangdu 求助下，export const injectJS = (jsUrl, cb) => { const scriptEle = document.createElement('script'); scriptEle.type = 'text/javascript'; scriptEle.onload = function () { cb?.(); scriptEle.remove(); }; scriptEle.src = jsUrl; scriptEle.setAttribute('ignore', 'true'); document.getElementsByTagName('head')[0].appendChild(scriptEle); }; 这样写之后还是有报错，jsUrl是第三放库里面自带的请求

报错信息是什么？
