### ISSUE TITLE
有一个业务场景，micro-app无法实现

### ISSUE THREAD

**Issue by weiqi93** [jd-opensource/micro-app#352]
我们的业务场景是：

在基座中的工作台中，有很多待办列表，每一个待办列表点开展示的是每一个子应用的某一个具体页面。

在点开某一个待办时候，如果浏览器的Url不变的情况下，用micro-app如果实现，望解答，谢谢！

**Comment by bailicangdu** [comment]
等下一个版本吧

**Comment by weiqi93** [comment]
用vue-router的abstract模式，是否可以实现。

**Comment by weiqi93** [comment]
> 等下一个版本吧

请问是micro-app的1.0正式版本吗？

预计正式版本发布的时间计划有吗？

**Comment by bailicangdu** [comment]
最近情况特殊，具体时间不确定

**Comment by panyouqing** [comment]
@weiqi93 我和你有一样的业务场景，请问你有解决吗？谢谢
