### ISSUE TITLE
子应用中的__MICRO_APP_ENVIRONMENT__为undefined

### ISSUE THREAD

**Issue by qinzhihao-conghua** [jd-opensource/micro-app#354]
### 描述：
基座应用是ng12，子应用是ng8，也看了官方demo部分进行相关修改，但是这个值仍然是undefined，控制台报路径没有匹配到的error，但是子应用却请求到了，不过页面明显不对了

![1](https://user-images.githubusercontent.com/33079330/161738674-875998f8-a375-437e-adad-8c47ebe67f24.png)

![2](https://user-images.githubusercontent.com/33079330/161740110-d3aa6e54-7f44-46d2-857e-5c201c7e8d30.png)

### 复现demo：

https://github.com/qinzhihao-conghua/zh-micro-app.git

**Comment by sxhieen** [comment]
尝试过主12+子12，主13+子12，主13+子13，主12+子13
只要是Angular13的子应用，都碰到类似的问题

**Comment by m310851010** [comment]
> 尝试过主12+子12，主13+子12，主13+子13，主12+子13 只要是Angular13的子应用，都碰到类似的问题

经调试发现 Angular13的子应用生成的script标签是有module属性的, micro-app处理module脚本时没有绑定Proxy Window对象所导致，希望能解决

**Comment by bailicangdu** [comment]
这个问题是因为module script标签导致沙箱失效，暂时无法解决

**Comment by for-kian** [comment]
基座angular14，子应用angular14 同样，看v1.0.0-alpha.6的更新已经解决，更新包后正常了
[https://github.com/micro-zoe/micro-app/releases/tag/v1.0.0-alpha.6](https://github.com/micro-zoe/micro-app/releases/tag/v1.0.0-alpha.6)
