### ISSUE TITLE
浏览器 history 历史记录不正确 

### ISSUE THREAD

**Issue by xiangxinji** [jd-opensource/micro-app#355]
## 问题描述
浏览器 url 为 /setup/setup/profile-manager/list ， 但是 window.history 注册的确是 
![image](https://user-images.githubusercontent.com/58387767/161888896-6638541f-08d9-4252-b6d0-42ffd16a267f.png)

这是由什么原因导致的这样， 注册进去的 history 没有 basePath 

主应用 
"@micro-zoe/micro-app": "0.8.1",
"vue-router": "^4.0.11",

子应用
"vue-router": "^4.0.11",

**Comment by xiangxinji** [comment]
测试了一下， 感觉好像是有冲突， 子应用的 history 和 主应用的 histrory 是共享的，子应用将自己匹配的路由注册进 history 了， 主应用预览回退就会读取被重置的 window.history 导致就少了 basePath .

**Comment by laoliya** [comment]
解决了吗，我的也是主应用的路由地址没了，只有子应用的

**Comment by bailicangdu** [comment]
参考 https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/framework/vue?id=_2%e3%80%81%e5%bd%93%e5%9f%ba%e5%ba%a7%e5%92%8c%e5%ad%90%e5%ba%94%e7%94%a8%e9%83%bd%e6%98%afvue-router4%ef%bc%8c%e7%82%b9%e5%87%bb%e6%b5%8f%e8%a7%88%e5%99%a8%e8%bf%94%e5%9b%9e%e6%8c%89%e9%92%ae%e9%a1%b5%e9%9d%a2%e4%b8%a2%e5%a4%b1

**Comment by xiangxinji** [comment]
好的 ， 非常感谢

**Comment by xiangxinji** [comment]
@bailicangdu  那段代码我加上并且测试了一下， 但是感觉效果不太理想， 原因是我们的这个 baseRoute 可能是动态生成的， 导致子路由可能会和主应用的baseRoute 相同， 就像上面的情况 /setup/setup/xxxx

**Comment by bailicangdu** [comment]
> @bailicangdu 那段代码我加上并且测试了一下， 但是感觉效果不太理想， 原因是我们的这个 baseRoute 可能是动态生成的， 导致子路由可能会和主应用的baseRoute 相同， 就像上面的情况 /setup/setup/xxxx

这个是临时解决方案，需要开发者调控的东西比较多，1.0版本会对这个问题进行修复，但还需要一段时间

**Comment by xiangxinji** [comment]
好的
