### ISSUE TITLE
列表到详情页多次使用浏览器前进后退，在详情页跳转另一个应用时报错

### ISSUE THREAD

**Issue by NicCraver** [jd-opensource/micro-app#357]
## 问题描述
> 问题的具体描述

## 复现步骤
账号密码随意
登录后
1. 从test1-1 点击跳转详情页再点浏览器返回
2.重复操作几次，从详情页点击test2(另一个子应用)的菜单
3.控制台报错

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。
<img width="594" alt="image" src="https://user-images.githubusercontent.com/36131101/162111935-c7e8da8b-9443-46b5-825a-67cf97d6dffe.png">

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。
https://github.com/NicCraver/microapp-demo

## 环境信息
- micro-app版本：0.8.5
- 主应用前端框架&版本："vue": "^3.2.31"
- 子应用前端框架&版本："vue": "^2.6.11",
- 构建工具&版本：@vue/cli 4.5.15

**Comment by bailicangdu** [comment]
问题不能稳定复现，初步推测是vue-router4的问题，我们会在下一个版本推出路由隔离，可以避免这个问题

**Comment by NicCraver** [comment]
> 问题不能稳定复现，初步推测是vue-router4的问题，我们会在下一个版本推出路由隔离，可以避免这个问题
> 
> The problem is not stable replication, the initial speculation is vue-router4 problem, we will be introduced in the next version of the route isolation, can avoid this problem

有具体时间吗，希望可以在我的项目上线之前解决这个问题，大佬加油

**Comment by NicCraver** [comment]
> 问题不能稳定复现，初步推测是vue-router4的问题，我们会在下一个版本推出路由隔离，可以避免这个问题

有具体时间吗，希望可以在我的项目上线之前解决这个问题，大佬加油

**Comment by bailicangdu** [comment]
> > 问题不能稳定复现，初步推测是vue-router4的问题，我们会在下一个版本推出路由隔离，可以避免这个问题
> 
> 有具体时间吗，希望可以在我的项目上线之前解决这个问题，大佬加油

受上海疫情影响，计划推迟，具体时间不确定

**Comment by NicCraver** [comment]
我能避免这个问题吗，是否是因为我的跳转方法不对，或者路由有问题，大佬能帮忙看一下代码吗

**Comment by NicCraver** [comment]
https://github1s.com/NicCraver/microapp-demo/blob/HEAD/main/src/layouts/BasicLayout.vue#L180
跳转方法 menuGoPage

**Comment by NicCraver** [comment]
主要是我觉得别人好像没提过类似问题，我觉得是我自己的问题/(ㄒoㄒ)/~~

**Comment by NicCraver** [comment]
@bailicangdu

**Comment by bailicangdu** [comment]
> 我能避免这个问题吗，是否是因为我的跳转方法不对，或者路由有问题，大佬能帮忙看一下代码吗

涉及到vue-router4的实现原理，它会在每次push前先执行replace，使用history.state.current替换当前路由信息。因为根据demo只复现了一次，之后再也无法复现，暂时猜测是因为子应用同时修改了history.state导致current为undefined，基座在跳转时拼接地址成 http://localhost:3001undefined, 导致报错。

**Comment by NicCraver** [comment]
```
router.beforeEach((to, from, next) => {
  if (history.state && !history.state.current) {
    Object.assign(history.state, {
      current: from.fullPath,
    })
  }
  const hasToken = sessionStorage.getItem('token')
  // requireAuth: true 表示需要登录
  if (to.meta.requireAuth) {
    if (hasToken) {
      next()
    } else {
      next(`/login?redirect=${to.path}`)
    }
  } else {
    next()
  }
  if (to.fullPath === '/login') {
    if (hasToken) {
      next({
        path: from.fullPath,
      })
    } else {
      next()
    }
  }
})
```
添加了这段代码，解决了问题 
```
if (history.state && !history.state.current) {
    Object.assign(history.state, {
      current: from.fullPath,
    })
  }
```
@bailicangdu
