### ISSUE TITLE
是不是不支持webpack5 好像没在demo找到 打包后子应用无法获取到 window.microApp

### ISSUE THREAD

**Issue by Jansschen** [jd-opensource/micro-app#358]
## 问题描述
> 问题的具体描述

## 复现步骤
1.
2.

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。

## 环境信息
- micro-app版本：
- 主应用前端框架&版本：
- 子应用前端框架&版本：
- 构建工具&版本：

**Comment by bailicangdu** [comment]
哪个脚手架，vue-cli5吗，还是自己搭建的脚手架？

**Comment by Jansschen** [comment]
vue-cli 搭建的webpack5

**Comment by bailicangdu** [comment]
> vue-cli 搭建的webpack5

vue-cli5有这个问题，临时解决方式是在打包后将html中type=module的部分去掉，下个版本会修复这个问题

**Comment by wangjieCode** [comment]
我想问一下webpack如何吧type=module的脚本去掉呀
