### ISSUE TITLE
vue3基座应用向子应用传参，子应用监听没有触发，要把data解构之后再重新处理成对象才能触发监听，不知道这是什么情况？

### ISSUE THREAD

**Issue by adouni1996** [jd-opensource/micro-app#360]
![Snipaste_2022-04-09_17-44-15](https://user-images.githubusercontent.com/57342656/162566519-db1a8520-8dd9-400e-a21d-4d7622db9770.png)

代码如下：
<template>
  
  <micro-app
    :name="name"
    :url="url"
    :baseroute="baseroute"
    :data="{...chilData}"
  />
</template>

<script>
import { useRoute } from 'vue-router'
import { reactive, toRefs, watch } from 'vue'

export default {
  setup() {
    const route = useRoute()
    const state = reactive({
      name: 'shop',
      url: 'http://127.0.0.1:8080/',
      baseroute: '/shop',
      chilData: {
        route: ''
      }
    })

    watch(
      () => route.hash,
      () => {
        setChilDataRoute()
      }
    )

    // 获取当前模块下的路由是多少,如果不是当前模块,不做不做处理
    const setChilDataRoute = () => {
      if (route.path.indexOf(state.baseroute) === -1) {
        return
      }
      state.chilData.route = route.hash.split('#')?.[1] || '/'
    }

    setChilDataRoute()

    return {
      ...toRefs(state)
    }
  }
}
</script>

<style>

</style>

**Comment by adouni1996** [comment]
``

**Comment by bailicangdu** [comment]
只有新的对象才会触发更新

**Comment by msojocs** [comment]
补个例子
![image](https://github.com/micro-zoe/micro-app/assets/20937135/d51965c4-55e5-43ee-aece-6c724fbbbda6)
