### ISSUE TITLE
el-popover、el-tooltip无法卸载

### ISSUE THREAD

**Issue by laozei6401** [jd-opensource/micro-app#364]
## 问题描述
> 问题的具体描述
因为劫持了dom的appendChild方法导致获取parentNode不一致
导致无法进入if判断进行卸载元素操作

## 复现步骤
1.使用el-popover、el-tooltip组件
2.在内部进行路由切换操作

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。
![image](https://user-images.githubusercontent.com/17523519/163355612-13b32f7a-4d24-43eb-856e-9d3b0be0d416.png)

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。

## 环境信息
- micro-app版本：
- 主应用前端框架&版本：
- 子应用前端框架&版本：
- 构建工具&版本：

**Comment by dongongfeiyu** [comment]
请问最终如何解决的？
