### ISSUE TITLE
整个官方群可以不  互帮互助

### ISSUE THREAD

**Issue by potatoes0521** [jd-opensource/micro-app#365]
## 背景
遇到的问题倒不是bug 也找不到类似的文章可以借鉴  
## 期望的效果
整个官方群可以不  互帮互助

**Comment by HenryZhu-1988** [comment]
> ## 背景
> 遇到的问题倒不是bug 也找不到类似的文章可以借鉴
> 
> ## 期望的效果
> 整个官方群可以不 互帮互助

good idea;

飞书、或者钉钉 群都可以

**Comment by Qujh97** [comment]
官网文档右下角有聊天群https://gitter.im/microzoe/micro-app

**Comment by leohai** [comment]
是啊，希望能够活跃一点，好的开源需要社区推广和应用，不能这么低调呀
