### ISSUE TITLE
主应用子应用都需要引入相同css资源时，子应用怎么才能减少一次引入呢

### ISSUE THREAD

**Issue by jiangruifeng** [jd-opensource/micro-app#367]
用globalAssets在主应用预加载了，但是子应用还是加载了一次

**Comment by bailicangdu** [comment]
地址是完全一样的吗

**Comment by bailicangdu** [comment]
截图看一下呢

**Comment by jiangruifeng** [comment]
> 
请问 用globalAssets在主应用预加载之后，子应用直接能用这个资源是吗

**Comment by bailicangdu** [comment]
是的

**Comment by zxb853440735** [comment]
这个大概意思是在基座中配置了globalAssets资源共享，这样子应用就可以直接用这个资源了。那是不是子应用就不需要这个资源了？那我好奇如果子应用单独运行，这个资源是不是就没法获取？

**Comment by jiangruifeng** [comment]
本地开发本来就是要启动主应用的




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月28日(星期五) 中午11:25
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [micro-zoe/micro-app] 主应用子应用都需要引入相同css资源时，子应用怎么才能减少一次引入呢 (Issue #367)





 
这个大概意思是在基座中配置了globalAssets资源共享，这样子应用就可以直接用这个资源了。那是不是子应用就不需要这个资源了？那我好奇如果子应用单独运行，这个资源是不是就没法获取？
