### ISSUE TITLE
基座中怎么跳转到子应用的多页面中？

### ISSUE THREAD

**Issue by ddtsdg** [jd-opensource/micro-app#368]
目前是基座中http://localhost:9999/app-ibi/，点击按钮跳转子应用的新页面，但是点击了http://localhost:9999/app-ibi/ide.html?id=8a74ba5e80314cbe01803c15fef00013&type=unit&terminal=PC，新页面也打开了，但是页面显示的还是app-ibi的首页，有人知道怎么配置嘛？

**Comment by jiangruifeng** [comment]
> 目前是基座中[http://localhost:9999/app-ibi/，点击按钮跳转子应用的新页面，但是点击了http://localhost:9999/app-ibi/ide.html?id=8a74ba5e80314cbe01803c15fef00013&type=unit&terminal=PC，新页面也打开了，但是页面显示的还是app-ibi的首页，有人知道怎么配置嘛？](http://localhost:9999/app-ibi/%EF%BC%8C%E7%82%B9%E5%87%BB%E6%8C%89%E9%92%AE%E8%B7%B3%E8%BD%AC%E5%AD%90%E5%BA%94%E7%94%A8%E7%9A%84%E6%96%B0%E9%A1%B5%E9%9D%A2%EF%BC%8C%E4%BD%86%E6%98%AF%E7%82%B9%E5%87%BB%E4%BA%86http://localhost:9999/app-ibi/ide.html?id=8a74ba5e80314cbe01803c15fef00013&type=unit&terminal=PC%EF%BC%8C%E6%96%B0%E9%A1%B5%E9%9D%A2%E4%B9%9F%E6%89%93%E5%BC%80%E4%BA%86%EF%BC%8C%E4%BD%86%E6%98%AF%E9%A1%B5%E9%9D%A2%E6%98%BE%E7%A4%BA%E7%9A%84%E8%BF%98%E6%98%AFapp-ibi%E7%9A%84%E9%A6%96%E9%A1%B5%EF%BC%8C%E6%9C%89%E4%BA%BA%E7%9F%A5%E9%81%93%E6%80%8E%E4%B9%88%E9%85%8D%E7%BD%AE%E5%98%9B%EF%BC%9F)

你需要通知给基座

> 目前是基座中[http://localhost:9999/app-ibi/，点击按钮跳转子应用的新页面，但是点击了http://localhost:9999/app-ibi/ide.html?id=8a74ba5e80314cbe01803c15fef00013&type=unit&terminal=PC，新页面也打开了，但是页面显示的还是app-ibi的首页，有人知道怎么配置嘛？](http://localhost:9999/app-ibi/%EF%BC%8C%E7%82%B9%E5%87%BB%E6%8C%89%E9%92%AE%E8%B7%B3%E8%BD%AC%E5%AD%90%E5%BA%94%E7%94%A8%E7%9A%84%E6%96%B0%E9%A1%B5%E9%9D%A2%EF%BC%8C%E4%BD%86%E6%98%AF%E7%82%B9%E5%87%BB%E4%BA%86http://localhost:9999/app-ibi/ide.html?id=8a74ba5e80314cbe01803c15fef00013&type=unit&terminal=PC%EF%BC%8C%E6%96%B0%E9%A1%B5%E9%9D%A2%E4%B9%9F%E6%89%93%E5%BC%80%E4%BA%86%EF%BC%8C%E4%BD%86%E6%98%AF%E9%A1%B5%E9%9D%A2%E6%98%BE%E7%A4%BA%E7%9A%84%E8%BF%98%E6%98%AFapp-ibi%E7%9A%84%E9%A6%96%E9%A1%B5%EF%BC%8C%E6%9C%89%E4%BA%BA%E7%9F%A5%E9%81%93%E6%80%8E%E4%B9%88%E9%85%8D%E7%BD%AE%E5%98%9B%EF%BC%9F)



> 目前是基座中[http://localhost:9999/app-ibi/，点击按钮跳转子应用的新页面，但是点击了http://localhost:9999/app-ibi/ide.html?id=8a74ba5e80314cbe01803c15fef00013&type=unit&terminal=PC，新页面也打开了，但是页面显示的还是app-ibi的首页，有人知道怎么配置嘛？](http://localhost:9999/app-ibi/%EF%BC%8C%E7%82%B9%E5%87%BB%E6%8C%89%E9%92%AE%E8%B7%B3%E8%BD%AC%E5%AD%90%E5%BA%94%E7%94%A8%E7%9A%84%E6%96%B0%E9%A1%B5%E9%9D%A2%EF%BC%8C%E4%BD%86%E6%98%AF%E7%82%B9%E5%87%BB%E4%BA%86http://localhost:9999/app-ibi/ide.html?id=8a74ba5e80314cbe01803c15fef00013&type=unit&terminal=PC%EF%BC%8C%E6%96%B0%E9%A1%B5%E9%9D%A2%E4%B9%9F%E6%89%93%E5%BC%80%E4%BA%86%EF%BC%8C%E4%BD%86%E6%98%AF%E9%A1%B5%E9%9D%A2%E6%98%BE%E7%A4%BA%E7%9A%84%E8%BF%98%E6%98%AFapp-ibi%E7%9A%84%E9%A6%96%E9%A1%B5%EF%BC%8C%E6%9C%89%E4%BA%BA%E7%9F%A5%E9%81%93%E6%80%8E%E4%B9%88%E9%85%8D%E7%BD%AE%E5%98%9B%EF%BC%9F)

通知给基座来控制跳转

**Comment by jiangruifeng** [comment]
通知给基座来控制跳转

**Comment by bailicangdu** [comment]
多页面只能通过a标签和href跳转，每次跳转都会刷新，和spa不一样
