### ISSUE TITLE
keepalive下，已经加载过的子系统切换时URL已经改变，页面并未加载，该子系统并未被拉起

### ISSUE THREAD

**Issue by isboyjc** [jd-opensource/micro-app#370]
## 问题描述
> 问题的具体描述
微前端+keepalive多页签
采用的跳转方式为，首次加载子系统使用主系统的router.push，已经加载过的系统由基座向子系统发送跳转事件，由子系统router.push跳转

main-A/xxx
main-B/xxx

假如A/B系统都已经初始化过了（keepalive），目前在B系统，我再次跳转到A系统的时候，该系统应该使用主系统的路由去跳转还是通知子系统去跳转呢？
上述的问题是采用通知子系统跳转，跳转后页面还是B系统页面并未渲染A系统页面，不过URL确实改变了（main-A/xxx），这里有个问题，我在主系统通知子系统跳转某页面，为什么URL中主系统的路由会变呢（main-B/xxx  ->  main-A/xxx），这里是框架做了处理吗？
但是只是URL变了，并没有渲染页面，仿佛子系统并没有被拉起一样

## 复现步骤
1.点击子系统A-1页面，切换子系统A-2页面。此次是系统A首次加载，一切正常。
2.切换点击子系统B-1页面，切换子系统B-2页面。此次是系统B首次加载，一切正常。
3.切换子系统A-1页面。这是系统A已经初始化过了，还未卸载，切换后URL变为A-1，但是页面还是子系统B-2页面并未改变

## 上传截图
> 暂无，请看上面描述，谢谢

## 复现仓库
> 暂无

## 环境信息
- micro-app版本：0.8.5
- 主应用前端框架&版本：vue3+vite
- 子应用前端框架&版本：vue3+VueCLI
- 构建工具&版本：

**Comment by bailicangdu** [comment]
主、子都是基于浏览器url进行渲染，子应用之间的跳转通过主应用控制，页面有没有被选入，要看micro-app标签是否被渲染

**Comment by bailicangdu** [comment]
还有一点，主 A B 三个路由相互独立，无法通过某一个子应用控制另外一个子应用跳转
