### ISSUE TITLE
应用已存在什么意思

### ISSUE THREAD

**Issue by ddtsdg** [jd-opensource/micro-app#372]
index.esm.js?94a1:55 [micro-app] app xxx: app name conflict, an app named ibi is running
有人遇见过这个问题吗？怎么解决呢

**Comment by ddtsdg** [comment]
我没有重复名字的服务

**Comment by bailicangdu** [comment]
micro-app name值重复了，仔细检查一下逻辑

**Comment by rawbin-** [comment]
看起来是SPA取资源取的不对导致的，比如渲染子应用资源的时候，请求发到了主应用，拿到了主应用的index.html，然后主应用又渲染了一遍子应用，然后就 app name conflict了
