### ISSUE TITLE
主项目和子项目共享npm包？

### ISSUE THREAD

**Issue by xinlai3698** [jd-opensource/micro-app#374]
请问下，因为我们把业务组件封装成了一个npm包，然后在各子项目中引入使用； 不知micro-app如何共享npm包

**Comment by Qujh97** [comment]
#278 
可以考虑使用lerna

**Comment by LinFeng1997** [comment]
npm 包支持 umd 模式的话，由子应用或者主应用挂在 window 上就可以吧

**Comment by Perseman** [comment]
模块联邦

**Comment by Lionad-Morotar** [comment]
使用 pnpm workspace 或者 lerna + yarn，npm@^7 也支持 workspace 了。
