### ISSUE TITLE
关于自定义fetch功能的建议

### ISSUE THREAD

**Issue by wojiaoggyy** [jd-opensource/micro-app#376]
## 背景
> 现在的自定义fetch功能，只能用于拦截静态资源。
> 在这种模式下，想要请求后端接口，只能修改子应用（1. 打包模式；2.接口封装时判断运行环境）。
> 但是如果自定义fetch可以拦截动态的接口，那么我可以真正做到对子应用的零修改，直接通过拦截和proxy配置即可（如下）。

```
microApp.start({
  fetch(url, options, appName) {
    if (url.includes("/api")) {
      return window
        .fetch(url.replace("/api", `/${appName}/api`), options)
        .then((res) => {
          return res.text();
        });
    } else {
      return window.fetch(url, options).then((res) => {
        return res.text();
      });
    }
  },
});
```

## 期望的回复
> 1. 我所说背景是否是我自己理解错误？
> 2. 这样设计模式的原因是什么？
> 3. 后期有无意愿实现类似功能？

**Comment by bailicangdu** [comment]
这个fetch只是在框架层面拦截资源，不涉及接口，子应用的接口请求也有可能用到ajax

**Comment by wojiaoggyy** [comment]
所以是基于子应用接口方式的不确定性来考虑，不做接口层面的拦截？
那么后期有这方面的规划吗？
