### ISSUE TITLE
基座下业务应用动态创建script标签资源跨域

### ISSUE THREAD

**Issue by Jedanny** [jd-opensource/micro-app#377]
## 问题描述
> 基座下单个业务用到了腾讯地图，业务应用单独访问正常，基座下访问动态加载远程js跨域 ，怀疑动态创建script 挂载在body 下基座代理fetch执行安全策略拦截掉了

## 复现步骤
1.  使用 qqmap-plus 初始化腾讯地图
```javascript
import qqmapPlus from 'qqmap-plus'
     qqmapPlus.init('api-key', () => {
            const options = {
              center: new qq.maps.LatLng(position.coords.latitude, position.coords.longitude),
              zoom: this.zoom
            }
            this.map = new qq.maps.Map(container, options)
          }, ['geometry'])
```
3.

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。
正常访问类型为script
![image](https://user-images.githubusercontent.com/33054738/164989122-9bb6a288-a5d9-4768-875d-aef7079d3ceb.png)
跨域为fetch
![image](https://user-images.githubusercontent.com/33054738/164989140-1a2bcc76-dccc-4e1d-8843-9d1bcbcb7055.png)

![image](https://user-images.githubusercontent.com/33054738/164989155-a74faf23-6e89-4832-862c-88322f39327e.png)
正常无origin 头
![image](https://user-images.githubusercontent.com/33054738/164989459-9874f0e4-5d8c-4957-89f2-d742bbb3884a.png)
基座下执行带有origin头，跨域
![image](https://user-images.githubusercontent.com/33054738/164989475-7a78277e-84bc-4777-9722-a63bb5d8ab60.png)

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。

## 环境信息
- micro-app版本：@micro-zoe/micro-app@0.8.5 
- 主应用前端框架&版本：vue@2.6.14
- 子应用前端框架&版本：vue@2.6.14
- 构建工具&版本：webpack@5.69.1
- 地图相关工具&版本: qqmap-plus@0.1.0

**Comment by xiangxinji** [comment]
静态文件需要自己做代理

**Comment by bailicangdu** [comment]
可以将地图js放在基座中加载避免这个问题

**Comment by Jedanny** [comment]
放在基座下算是个临时解决方案 不优雅 业务的职能由基座去承载了一部分  官方后续这块有计划调整么

**Comment by bailicangdu** [comment]
地图js属于第三方文件，无法要求第三方设置跨域，所以只能采用降级方案，放入基座或者下载到本地

**Comment by Jedanny** [comment]
妥妥的

**Comment by huchaolin** [comment]
> 25 Apr

请问这位同学你最后找到解决方法了吗， 我这就算作代理， 自定义fetch拦截之后做代理拿到资源之后也没有正常加载script

**Comment by chylhos** [comment]
> 

请问解决了吗，我是第三方js资源，设置mode: 'no-cors'确实能拿到，但是实际上并没有生效

**Comment by chylhos** [comment]
> > 25 Apr
> 
> 请问这位同学你最后找到解决方法了吗， 我这就算作代理， 自定义fetch拦截之后做代理拿到资源之后也没有正常加载script

请问解决了吗，我是第三方js资源，设置mode: 'no-cors'确实能拿到，但是实际上并没有生效

**Comment by xiangxinji** [comment]
> > > 25 Apr
> > 
> > 
> > 请问这位同学你最后找到解决方法了吗， 我这就算作代理， 自定义fetch拦截之后做代理拿到资源之后也没有正常加载script
> 
> 请问解决了吗，我是第三方js资源，设置mode: 'no-cors'确实能拿到，但是实际上并没有生效

no-cors 只是 fetch 不会爆跨域的错误, 但是拿到的内容依然是空的, 可以用个 node 或者什么做个转发比较好

**Comment by xiangxinji** [comment]
> > > 25 Apr
> > 
> > 
> > 请问这位同学你最后找到解决方法了吗， 我这就算作代理， 自定义fetch拦截之后做代理拿到资源之后也没有正常加载script
> 
> 请问解决了吗，我是第三方js资源，设置mode: 'no-cors'确实能拿到，但是实际上并没有生效
然后去用插件去单独处理这个 静态资源文件.

**Comment by raoenhui** [comment]
把地图js下载下来，放入基座或者放在子应用服务器中加载

**Comment by iYogic2** [comment]
按此操作 do like this:  https://github.com/micro-zoe/micro-app/issues/1009
