### ISSUE TITLE
为什么子应用内的documen !== window.rawDocument，但window === window.rawWindow

### ISSUE THREAD

**Issue by kenjiding** [jd-opensource/micro-app#378]
## 问题描述
> 问题的具体描述
**为什么子应用内的documen === window.rawDocument，但window !== window.rawWindow**

## 复现步骤
1.
2.

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。

## 环境信息
- micro-app版本：
- 主应用前端框架&版本：
- 子应用前端框架&版本：
- 构建工具&版本：

**Comment by bailicangdu** [comment]
子应用的window是代理对象，不是rawWindow

**Comment by 719347266** [comment]
> 子应用的窗口是代理对象，而不是rawWindow

这里的代理的对象是指子应用的window还是基座的
