### ISSUE TITLE
ReferenceError: utils_library_dll is not defined

### ISSUE THREAD

**Issue by Buggersldx** [jd-opensource/micro-app#38]
![image](https://user-images.githubusercontent.com/21056737/129328623-af73af54-1e7f-46b0-816c-d7e7eafb8d22.png)

按照流程一步步走，基座是新建的，子项目是历史项目；

![image](https://user-images.githubusercontent.com/21056737/129328754-b18e4881-fe5e-45ec-92b5-f935920e223c.png)
但找不到这个 utils_library_dll

**Comment by bailicangdu** [comment]
webpack打包后的dll是一个单独的js文件，开头就是 var xxx =, 你仔细找找

**Comment by bailicangdu** [comment]
打包后的html中靠前的script元素

**Comment by Buggersldx** [comment]
@bailicangdu 这是要手动去找去改打包后的文件吗？   我目前是开发状态下的，并不是打包之后的；

现在我找到了，但应该要怎么改呢？

**Comment by bailicangdu** [comment]
因为dll文件的内容和js地址正常情况下是固定的，所以可以手动修改，或者通过插件系统修改 var xx_dll = 改为 window.xx_dll = 
```js
microApp.start({
  plugins: {
    modules: {
      应用名称: [{
        loader(code, url) {
          if (url === 'xxx.js') {
            code = code.replace('var xx_dll = ', 'window.xx_dll = ')
          }
          return code
        }
      }]
    }
  }
})
```

**Comment by vellsuan** [comment]
当一个十几个依赖js产生大量的未定义是需要全部代码手动去改吗 那不等于重写编写代码 而且有的第三方的很复杂代码写的一个变量改了就一堆问题

**Comment by vellsuan** [comment]
这个问题挺严重的因为window的劫持导致很多项目加载的js里面有很多不是准确声明的变量和方法全都是未定义
