### ISSUE TITLE
React 17以下在使用shadowDom 的时候所有点击事件都失效

### ISSUE THREAD

**Issue by asiainfoliwei** [jd-opensource/micro-app#380]
## 问题描述
> 问题的具体描述
React 17以下在使用shadowDom 的时候所有点击事件都失效

## 复现步骤
1. 基座地址: https://helper.ilive.qq.com/ilive/test/base/index.html
2. 子应用地址: https://helper.ilive.qq.com/ilive/test/index.html
3. 两个项目各点击按钮即可发现问题

## 关键截图
子应用代码
![image](https://user-images.githubusercontent.com/24582028/165428927-6a5a9684-12e9-40d4-a3ff-be80418ee4b5.png)

## 环境信息
- micro-app版本：0.8.5
- 主应用前端框架&版本：vue2
- 子应用前端框架&版本：16.8
- 构建工具&版本：webpack

**Comment by asiainfoliwei** [comment]
定位了一下react-dom 代码，16.x版本的事件都使用的是事件委托，将相关的click 事件绑定在document上面，通过event.target 去找到触发click 事件的dom 元素，但是加了shadow dom 之后，event target就不是触发事件的元素而是web-componnets，

![image](https://user-images.githubusercontent.com/24582028/165429427-c3f8a5ae-a420-4533-abc4-a2a7eaa126a9.png)
在使用shadow dom的情况下把上图的rawDocuemnt 修改成shadowroot 可以解决这个问题，我提个PR？

**Comment by asiainfoliwei** [comment]
已提PR

**Comment by jinjinwa** [comment]
官方还没解决么？
