### ISSUE TITLE
基座热更新，报错Uncaught Error: Iframe has not been created yet.

### ISSUE THREAD

**Issue by lijiweigh** [jd-opensource/micro-app#382]
## 问题描述
基座是react 17.02，之前出现过热更新时提示 process is not defined，后来根据这个方法修改https://stackoverflow.com/a/70402397
现在保存会出现Uncaught Error: Iframe has not been created yet.

如果不加载子应用，即主应用的microApp.start() 不调用，热更新正常，调用之后会报错

报错代码的对应位置：
https://github.com/facebook/create-react-app/blob/bb64e31a81eb12d688c14713dce812143688750a/packages/react-error-overlay/src/index.js#L163

## 复现步骤
1.
2.

## 上传截图
![image](https://user-images.githubusercontent.com/23213046/165697375-40607997-03a7-4996-bf53-55aef0f5e979.png)

create-react-app 里有类似的issue
https://github.com/facebook/create-react-app/issues/10865

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。

## 环境信息
- micro-app版本：0.8.5
- 主应用前端框架&版本：17.0.1
- 子应用前端框架&版本：17.0.1
- 构建工具&版本：webpack4  create-react-app4

**Comment by lijiweigh** [comment]
这种情况下，子应用的热更新也失效了，但是不会报错

**Comment by bailicangdu** [comment]
这个问题暂时只能关闭热更新

**Comment by lijiweigh** [comment]
有修复计划吗

**Comment by bailicangdu** [comment]
目前没办法解决

**Comment by nieshiming** [comment]
最新版本create-react-app创建的基座和子应用，子应用热更新后<已开启跨域>，基座页面没有重新加载，基座需要重新刷新页面才能显示子应用最新内容。
请问下micro-app是支持  子应用热更新后，基座页面也自动热更新吗
