### ISSUE TITLE
子应用创建元素插入到 body 时，在某些情况下会插入到基座应用的 body 中，Vue3 的 Teleport 必定重现

### ISSUE THREAD

**Issue by keuby** [jd-opensource/micro-app#383]
## 问题描述
子应用中插入元素到 body 上时，会有可能插入到基座应用的 body 上。这个问题在 https://github.com/micro-zoe/micro-app/issues/260 上有提到。
并且经过我调试以及对源代码的理解，我发现是否会插入到 body 与是否使用 Promise 等延时执行的微任务或宏任务中做插入操作并没有直接联系。

这边提供两段在 微任务中执行的代码，都是微任务中执行的，代码 1 能正常插入到 micro-app-body 中，而代码 2 会插入到基座应用的 body 中

```ts
// 代码 1
Promise.resolve().then(() => {
  document.body.appendChild(document.createElement('div'));
});
```

```ts
// 代码 2
const doc = window.document;
Promise.resolve().then(() => {
  doc.body.appendChild(doc.createElement('div'));
});
```

是否会插入到基座应用的 body，和框架无关，和是否在 宏任务或微任务中执行插入操作也没有直接联系，只和写法有关。经过源码的调试，我发现在 代理 window 的Proxy 中有这样一段代码

https://github.com/micro-zoe/micro-app/blob/8ffc792ebd6932d0a05ce3bd9b889196b9ebdb74/src/sandbox/index.ts#L178-L188

在 185 行中，从 proxy window 上直接拿到属性的时候会触发 `throttleDeferForSetAppName` 函数

https://github.com/micro-zoe/micro-app/blob/8ffc792ebd6932d0a05ce3bd9b889196b9ebdb74/src/libs/utils.ts#L289-L296

该函数设置了 currentAppName，然后注册了一个微任务去移除 currentAppName，所以在 `代码 2` 中，执行创建和插入操作的时候，currentAppName 应该是 null。

此时在执行 createElement 创建元素的时候，就 markElement 无法正常在元素上追加 `__MICRO_APP_NAME__` 属性

https://github.com/micro-zoe/micro-app/blob/8ffc792ebd6932d0a05ce3bd9b889196b9ebdb74/src/source/patch.ts?_pjax=%23js-repo-pjax-container#L291-L295

所以在调用 appendChild 插入元素的时候，内部会统一调用的  commonElementHandler 就会走到最后的逻辑，直接调用原生方法执行插入操作，直接插入到 body 上

https://github.com/micro-zoe/micro-app/blob/8ffc792ebd6932d0a05ce3bd9b889196b9ebdb74/src/source/patch.ts?_pjax=%23js-repo-pjax-container#L157-L200

如果要正确插入元素到 body，那么在创建元素的时候，就不能缓存 document，而是必须直接从 window 上取得 document 才能正常插入到 micro-app-body 中，而在 vue3 的 源码中，nodeOps 应该是为了减少作用域链长度，优化变量查询链路，缓存了 document 元素，所以导致所有使用 <teleport to="body"></teleport> 这样挂在的元素都会直接挂在到基座的的 body 中

https://github.com/vuejs/core/blob/4a3237ad9300693e465f82a6be3552565a1c4be3/packages/runtime-dom/src/nodeOps.ts?_pjax=%23js-repo-pjax-container#L4-L31

## 复现步骤

将上述代码中的 代码 1 和代码 2 分别放入子应用中执行即可复现。

## 环境信息
- micro-app版本：0.8.5
- 主应用前端框架&版本：Vue 3.2.33
- 子应用前端框架&版本：Vue 3.2.33
- 构建工具&版本：基座应用 Vite 2.8.6，子应用 @vue/cli 5.0.4

**Comment by keuby** [comment]
@bailicangdu 大佬，关于这个问题有修复的计划吗，或者我可以提供什么帮助？

**Comment by note520** [comment]
同样问题，是否有解决方案？？？

**Comment by keuby** [comment]
> 同样问题，是否有解决方案？？？

我目前临时的方案是，teleport 的 to 参数传入 document.querySelector('micro-app-body')

**Comment by LinFeng1997** [comment]
有一个解决方案就是在对于沙箱内 Window 的对象再代理一次 Document 属性，在 proxy 过的 document 内处理 createElement 方法将特殊属性挂载到元素上去，而不是全局劫持方法。

此方案需要 @bailicangdu review 下，如果可以的话我提个 pr。

**Comment by keuby** [comment]
这个 MR 还有什么问题么？这个 document 的问题导致了很多不可预料的 bug，为了修复这些 bug 我们花费了大量的时间去适配，但是这些工作都是不必要的，而且后期当这个问题修复之后可能还需要移除。

希望可以尽快修复 @bailicangdu

**Comment by LinFeng1997** [comment]
@keuby 经过测试，我们发现 proxyDocument 在一些场景下仍然会被绕过，如 react-dom 的 ownerDocument 和 parentNode 方式访问 document 等，具体解决方案还在设计中。

**Comment by Fov6363** [comment]
想问一下这个问题有解决方案了吗？我遇到类似的问题，是父应用通过 document.createElement 插入到子应用之中，也是因为 throttleDeferForSetAppName 延迟设置 null 的问题。

**Comment by YuJianghao** [comment]
尝试了一个 **哪疼医哪** 的方案可以解决一些 ownerDocument 导致的 React Portal 的问题

```ts
// 子应用内，React 启动前
Object.defineProperty(document.body.ownerDocument, 'createElement', {
  get() {
    return document.createElement.bind(document)
  },
})
```

```ts
import ReactDOM from 'react-dom'
import {Select} from 'antd'

export default () => {
  return ReactDOM.createPortal(
    <Select
      getPopupContainer={() => document.body}
      className="w-72"
      options={[{label: 'label', value: 'value'}]}
    />,
    document.body
  )
}
```

react@18.3.1
react-dom@18.3.1
@micro-zoe/micro-app@1.0.0-rc.5
