### ISSUE TITLE
子应用window相关，有大佬能解答下吗

### ISSUE THREAD

**Issue by xiaozhanghui** [jd-opensource/micro-app#385]
子应用中
window.a= 1;
window.rawWindow.b = 1;
打印window
window = {
 a:1,
 b:1,
 rawWindow: {b:1}
}
为什么window.rawWindow.a是 undefind

**Comment by bailicangdu** [comment]
a是子应用的变量，不属于原生window

**Comment by dream2023** [comment]
> 子应用中 window.a= 1; window.rawWindow.b = 1; 打印window window = { a:1, b:1, rawWindow: {b:1} } 为什么window.rawWindow.a是 undefind

因为被沙箱隔离了呀，微前端的一个重要作用不就是沙箱吗，最后被代理到 `proxyWindow` 也就是 `window.rawWindow.__MICRO_APP_PROXY_WINDOW__` 而不是 `rawWindow` 上，没有泄漏到全局
