### ISSUE TITLE
父子应用同框架情况下, 子应用操作卡顿延迟

### ISSUE THREAD

**Issue by skye-z** [jd-opensource/micro-app#388]
## 问题描述

当基座和子应用都使用 `element-plus` 时, 子应用中的操作会出现延迟和随机卡顿, 

>下图为卡顿情况(操作不跟手,hover明显是在鼠标离开后才渲染)
![QQ20220505-160022-HD](https://user-images.githubusercontent.com/20382734/166883441-b5903066-4615-4134-9da5-6588050bbc2b.gif)
>下图为流畅情况
![流畅](https://user-images.githubusercontent.com/20382734/166882617-a93db1ce-96fb-4cc2-bbec-66b1316017ed.gif)

并伴随基座 **JS堆** 大小的异常增长, 下图为 基座 在不同的子应用引入情况下的堆大小

![image](https://user-images.githubusercontent.com/20382734/166880989-e9f529a3-4b63-4ecf-9a51-3d1a6b3aa621.png)

下图是执行上方GIF图中的操作后, 堆大小异常增长的情况

![WX20220505-160705](https://user-images.githubusercontent.com/20382734/166884565-ead2f37d-ffa3-4228-9849-2874a8aea22b.png)

子应用完整引入后独立访问, 其堆大小只有 33.7MB

### 内存分析报告

> 从下到上
![1](https://user-images.githubusercontent.com/20382734/166885246-496a9245-e428-44cf-8d16-4e975e838776.png)

> 从上到下
![3](https://user-images.githubusercontent.com/20382734/166885259-1a91607b-db1c-48b3-b6b1-65c238cf9b42.png)

## 复现步骤
1. 新建基座, 完整引入 `element-plus`
2. 新建子应用, 引入`element-plus`
3. 创建一个元素, 给予css hover事件

## 环境信息
- micro-app版本：0.8.5
- 主应用前端框架&版本：element-plus 2.1.11
- 子应用前端框架&版本：element-plus 2.1.11
- 构建工具&版本：webpack

## 附件

[性能&内存分析.zip](https://github.com/micro-zoe/micro-app/files/8629649/default.zip)

**Comment by skye-z** [comment]
🤦‍♂️ 实例试了下不好提出来, 当前项目基座里面东西太多了, 而且很多是服务端渲染的.

旧项目直接嵌入是非常流畅的, 那就意味着是新代码导致的, 
我尝试一段段注释代码排查导致卡顿的原因, 发现去掉下面这段代码后就正常了
```vue
// 当前是否处于微前端环境
this.app = Boolean(window.__MICRO_APP_ENVIRONMENT__);
```

> 这段代码是获取当前是否处于基座中, 因为基座上有个顶部导航, 如果是在基座中需要通过 `v-if` 显示导航占位元素

[操作录屏](https://user-images.githubusercontent.com/20382734/166894756-9ae1ae81-b5a0-4919-9a12-63c79ddf9e54.mp4)

**Comment by Huansheng1** [comment]
如果是因为这个window.__MICRO_APP_ENVIRONMENT__导致的卡顿那如何判断是在micro-app里呢
