### ISSUE TITLE
子应用如果配置的有externals，会报错

### ISSUE THREAD

**Issue by lyh0371** [jd-opensource/micro-app#390]
子应用 配置
```js
    config.externals({
      vue: 'Vue',
      'vue-router': 'VueRouter',
      vuex: 'Vuex',
      axios: 'axios',
      echarts: 'echarts',
      'element-ui': 'ELEMENT',

    })
```

主应用报错
<img width="1151" alt="image" src="https://user-images.githubusercontent.com/30796346/167243427-379e88ac-9284-4874-8c04-5faa0bcc7ffa.png">

**Comment by bailicangdu** [comment]
参考 https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/sandbox?id=_2%e3%80%81%e5%ad%90%e5%ba%94%e7%94%a8%e6%8a%9b%e5%87%ba%e9%94%99%e8%af%af%e4%bf%a1%e6%81%af%ef%bc%9axxx-%e6%9c%aa%e5%ae%9a%e4%b9%89

**Comment by jingjingzhao** [comment]
> 

请问你有解决吗？是怎么解决的？我尝试了各种方式都不生效，还是undefined @lyh0371

**Comment by lyh0371** [comment]
@jingjingzhao 没有解决

**Comment by wjy18666** [comment]
> 参考 https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/sandbox?id=_2%e3%80%81%e5%ad%90%e5%ba%94%e7%94%a8%e6%8a%9b%e5%87%ba%e9%94%99%e8%af%af%e4%bf%a1%e6%81%af%ef%bc%9axxx-%e6%9c%aa%e5%ae%9a%e4%b9%89

子应用都是用的vue，有不同的版本，例如v2.x和v3.x，暴露为全局变量不行，除非针对不同的版本暴露的全局变量为不相同，那项目的代码可能得改，而且改动不小
