### ISSUE TITLE
angular里通过loadChildren惰性加载的应用作为子应用会报错

### ISSUE THREAD

**Issue by Huansheng1** [jd-opensource/micro-app#393]
## 问题描述
> 问题的具体描述
angular里可能某种嵌套通过loadChildren惰性加载的应用作为子应用会报错？
不确定根本原因，报错截图里的load.script脚本请求地址不对，4200是基座端口，不是子应用的端口，导致请求不到？我通过插件、配置等方式貌似也改不了该加载地址。
## 复现步骤
> 可能的，我也不确定到底怎么复现
1. 一个模块设置为惰性加载，里面还有惰性加载
2.作为子应用嵌入

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。
```ts
loadChildren: () =>
                    import('./dashboard/dashboard.module').then((m) => m.DashboardModule),
```
![image](https://user-images.githubusercontent.com/33859558/167885937-52e5e25f-f049-424c-a43b-7766205a0651.png)

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。

## 环境信息
- micro-app版本：最新版
- 主应用前端框架&版本：Angular12
- 子应用前端框架&版本：Angular12
- 构建工具&版本：Ng Cli

**Comment by Huansheng1** [comment]
![image](https://user-images.githubusercontent.com/33859558/167889500-2ed45fe8-2998-4b8b-94b5-80d5bc9e2e54.png)
![image](https://user-images.githubusercontent.com/33859558/167890266-f56983f3-42c8-4a11-8af3-4cc0171f8c5c.png)

这里加载的有问题，路径不对，导致加载的是 http://localhost:4200/default~modules-auth-auth-module~pages-layout-module.js
实际子应用的地址是 http://localhost:6677/default~modules-auth-auth-module~pages-layout-module.js
没有按照配置的url走啊：
![image](https://user-images.githubusercontent.com/33859558/167890112-5f824970-c2ff-48de-9834-d8230361e05e.png)

**Comment by bailicangdu** [comment]
将子应用首页改成非懒加载的试一下呢

**Comment by Huansheng1** [comment]
> 将子应用首页改成非懒加载的试一下呢

您好，我强制将js路径都变更为本地子应用的开发路径，那个问题暂时跳过了，结果子应用直接渲染到父级应用的body上了：
![image](https://user-images.githubusercontent.com/33859558/168191113-142db148-aafd-4e2a-a0a2-724a0b031835.png)
本来应该是子应用显示在父应用的一个局部区域，但是现在没有按照指定的区域渲染，在正常的右侧区域一闪而逝变成了全屏上去了，跑到外面来了，渲染到了基座应用的body上；
然后子应用的组件样式变形（按官网设置去除样式隔离参数，貌似没生效，可能和渲染位置错误跑到父亲应用的Body上有关系）
请求跨域报错（我是angular脚手架配置的，貌似还是存在这个问题，然后引入了自定义webpack插件按官网说的加了允许跨域，还是不行）
![image](https://user-images.githubusercontent.com/33859558/168191357-d054e470-dffe-4d00-a290-6dc974a43545.png)

**Comment by Huansheng1** [comment]
> > 将子应用首页改成非懒加载的试一下呢
> 
> 您好，我强制将js路径都变更为本地子应用的开发路径，那个问题暂时跳过了，结果子应用直接渲染到父级应用的body上了： ![image](https://user-images.githubusercontent.com/33859558/168191113-142db148-aafd-4e2a-a0a2-724a0b031835.png) 本来应该是子应用显示在父应用的一个局部区域，但是现在没有按照指定的区域渲染，在正常的右侧区域一闪而逝变成了全屏上去了，跑到外面来了，渲染到了基座应用的body上； 然后子应用的组件样式变形（按官网设置去除样式隔离参数，貌似没生效，可能和渲染位置错误跑到父亲应用的Body上有关系） 请求跨域报错（我是angular脚手架配置的，貌似还是存在这个问题，然后引入了自定义webpack插件按官网说的加了允许跨域，还是不行） ![image](https://user-images.githubusercontent.com/33859558/168191357-d054e470-dffe-4d00-a290-6dc974a43545.png)

渲染问题确定了，子应用选择器不知道为啥选择到了本地的Body，需要修改子应用的挂载点
