### ISSUE TITLE
打开子应用的资源能能否携带自定义请求头

### ISSUE THREAD

**Issue by Kryzeno** [jd-opensource/micro-app#394]
打开子应用的资源能能否携带自定义请求头

**Comment by bailicangdu** [comment]
你说的是这个吗 https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/advanced?id=_1%e3%80%81%e8%87%aa%e5%ae%9a%e4%b9%89fetch

**Comment by Kryzeno** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。
