### ISSUE TITLE
Vue 子应用通过创建 script 标签加载 库打包模式的 Vue 组件时无法正确设置 publicpath

### ISSUE THREAD

**Issue by kelvin-lemon** [jd-opensource/micro-app#395]
![image](https://user-images.githubusercontent.com/49432472/168032447-5a8d6dc2-2a91-478b-8a1f-422733f7d568.png)

问题：
子应用有些资源是通过 Vue 库打包模式构建上传的 cdn 的，vue 的库打包通过 currentScript 动态设置 publicpath，但在 microapp 内失效。

期望：子应用通过创建 script js 包内需要通过 window.document.currentScript 来设置 其内部资源的 publicpath。

参考：
https://cli.vuejs.org/zh/guide/build-targets.html#%E5%BA%93

**Comment by bailicangdu** [comment]
问题已经定位，接下来会进行处理

**Comment by jardenliu** [comment]
如果紧急需要解决这个问题的话，可以尝试patch的方式，通过修复document.currentScript的getter来修正值

**Comment by bailicangdu** [comment]
[v1.0.0-alpha.6](https://github.com/micro-zoe/micro-app/releases/tag/v1.0.0-alpha.6)已修复

**Comment by darknessjs** [comment]
还是不行，主应用用了1.0.0-alpha.10
子应用生成的html文件里包含

    <script
      crossorigin="anonymous"
      src="https://uipaas-assets.com/prod/npm/@alilc/lowcode-engine/1.1.1/dist/js/engine-core.js"
    ></script>
   这里面依然无法获取到正确的currentScript
