### ISSUE TITLE
子应用取100vh超出基座100%高度从而出现滚动条

### ISSUE THREAD

**Issue by shiwanmenghuxiahuashan** [jd-opensource/micro-app#396]
## 问题描述
> 基座应用设置contnet内容区域为 heighet:calc(100vh - 60px) ,子应用设置高度100vh,此时vh高度取可视高度，超出基座区域产生滚动

## 复现步骤
1.
2.

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。

## 环境信息
- micro-app版本：
- 主应用前端框架&版本：
- 子应用前端框架&版本：
- 构建工具&版本：

**Comment by Qujh97** [comment]
这是正常的，vh本身就是基于浏览器高度，而非基座应用高度
