### ISSUE TITLE
关于start配置项的改进建议

### ISSUE THREAD

**Issue by Huansheng1** [jd-opensource/micro-app#397]
## 背景
> 描述您希望改进的问题。
1. 当前文档里涉及angular相关其实是有不少坑的，资源路径、挂载点、跨域、网络请求等都存在问题；希望完善下相关文档
2. 希望配置扩充下，支持修改子应用的网络请求（目前只能修改个fetch，但这个只能处理加载几个js的东西，达不到我下面想要的效果），比如请求api接口返回的一些相对路径图片，目前如果直接用就会报错，但是自己手动处理就要修改n个子项目，如果能在基座应用里通过配置的方式串改请求前、请求后的请求相关数据，就能避免挨个修改子应用达到目的
3. 配置支持修改子应用的html页面数据（因为可能存在静态图片等资源，但是目前我测试好像并没有自动修改），所以希望能给人提供个手动修改的配置，这样即使手动的没生效也能在父亲应用里修改，避免子应用修改太多，单独部署出现其他问题
4. 遇见这种问题，比如 [这个也拦截不到，查看源代码好像是直接创建script脚本完成的，fetch拦截不到倒也正常，我就顺便说下这个情况要是能在基座应用里也能自己通过个函数或者什么的自定义一些处理下更好](https://github.com/micro-zoe/micro-app/issues/393)

**Comment by Huansheng1** [comment]
5. css里的相对路径图片资源问题：[qiankun里有人讨论过，可以考虑下哈](https://github.com/umijs/qiankun/issues/981)、[相关问题](https://github.com/umijs/qiankun/issues/808)、[相关问题2](https://github.com/umijs/qiankun/issues/2014)
6. api请求问题不能通过配置什么的避免修改子应用嘛：[子应用请求接口报错](https://zeroing.jd.com/micro-app/docs.html#/zh-cn/questions?id=_14%e3%80%81%e5%ad%90%e5%ba%94%e7%94%a8%e8%af%b7%e6%b1%82%e6%8e%a5%e5%8f%a3%e6%8a%a5%e9%94%99)

**Comment by emmi2008** [comment]
> 5. css里的相对路径图片资源问题：[qiankun里有人讨论过，可以考虑下哈](https://github.com/umijs/qiankun/issues/981)、[相关问题](https://github.com/umijs/qiankun/issues/808)、[相关问题2](https://github.com/umijs/qiankun/issues/2014)
> 6. api请求问题不能通过配置什么的避免修改子应用嘛：[子应用请求接口报错](https://zeroing.jd.com/micro-app/docs.html#/zh-cn/questions?id=_14%e3%80%81%e5%ad%90%e5%ba%94%e7%94%a8%e8%af%b7%e6%b1%82%e6%8e%a5%e5%8f%a3%e6%8a%a5%e9%94%99)

我们也是主要用angular，同感，相关文档太少了。可否加个好友，互相沟通一下。WX：szxingyu

**Comment by lanmingle** [comment]
我基于这个封装了一个 ng 12 的库，我测试得还是可以，搞成路由模式，不支持 outlet，目前还是这个库还是 0.8.5 版本，ng 13 完全有问题，就算是 12 ，在主应用引入 BrowserAnimationsModule 模块则会导致 micro-app 的 afterhidden 事件不会触发，等等各种各样小问题，不过一般情况下还是够用的。

**Comment by emmi2008** [comment]
> 

<router-outlet></router-outlet> 你指的outlet？github有例子没有，搞个例子看看？

**Comment by lanmingle** [comment]
虽然花了几个星期设计和封装，想了想还是分享出来给大家，稍等我上传代码，还没有经过产品上的验证，多多担待，哈哈哈

**Comment by lanmingle** [comment]
虽然花了几个星期设计和封装，想了想还是分享出来给大家，稍等我上传代码，还没有经过产品上的验证，多多担待，哈哈哈

**Comment by lanmingle** [comment]
项目地址：https://github.com/lanaqi-opensource/aqi-microapp （希望别改改就说是自己的，敬畏开源）

目前发现 12 支持最友好，11 也支持，11的分支没有搞上来，只是有一些微小的变化，13 有问题。

下载下来，安装 npm 包，然后执行

npm run serve:ma-demo-main:dev
npm run serve:ma-demo-app1:dev
npm run serve:ma-demo-app2:dev

通过浏览器访问 localhost:4200 测试

代码说明（自己看吧哈哈哈）

-----

main.ts 无论是主还是子都一样
主应用：MaMainService 服务
子应用：MaSubService 服务

``` ts

// 这里的代码简单说一下，this.mainService.registerFrames 不一定需要在 ngAfterViewInit 事件中处理，在这里处理主要是引用自定错误模板（加载错误时显示），反正代码先自己看吧，这个封装还等框架升级以及尝试弄一些项目后再次调整。

  ngAfterViewInit(): void {

    const frameConfigs: MaFrameConfig[] = [
      {
        appUrl: 'http://localhost:4201',
        appName: 'sub-app1',
        // todo 开启 keepAlive 模式以后，如果加载失败则不会自动恢复，不推荐使用
        keepAlive: false,
        // todo 开启 shadowDom 模式以后 shares 样式则不生效，默认情况下，框架默认不开启 shadowDom 模式
        shadowDom: false,
      },
      {
        appUrl: 'http://localhost:4202',
        appName: 'sub-app2',
        // todo 开启 keepAlive 模式以后，如果加载失败则不会自动恢复，不推荐使用
        keepAlive: true,
        // todo 开启 shadowDom 模式以后 shares 样式则不生效，默认情况下，框架默认不开启 shadowDom 模式
        shadowDom: false,
      },
    ];

    this.mainService.registerFrames(frameConfigs, true, this.customErrorTemplate);

  }

```
