### ISSUE TITLE
页面刷新的问题

### ISSUE THREAD

**Issue by longshenzhu** [jd-opensource/micro-app#399]
基座histroy路由，子应用hash路由，刷新页面时如何保证基座路由先匹配，然后加载子应用

**Comment by longshenzhu** [comment]
![W )0%QH~SU236} _` 5MI06](https://user-images.githubusercontent.com/3724569/168782495-fa28cd27-8240-4b4c-b1fb-ab893cd25416.png)
![7N`PDD`T7%94X%1}}JN{5%7](https://user-images.githubusercontent.com/3724569/168782500-12e6a08a-532f-46af-970a-ae7483cfc5a5.png)

如图，刷新的时候，基座的页头页尾没加载出来，只加载子应用。

**Comment by longshenzhu** [comment]
> Hello @longshenzhu. In order to facilitate location and troubleshooting, we need you to provide a realistic GitHub repository. 您好 @longshenzhu, 为了方便定位和排查问题，我们需要您提供一个重现实例，请提供一个尽可能精简的 GitHub 仓库地址。

> Hello @longshenzhu. In order to facilitate location and troubleshooting, we need you to provide a realistic GitHub repository. 您好 @longshenzhu, 为了方便定位和排查问题，我们需要您提供一个重现实例，请提供一个尽可能精简的 GitHub 仓库地址。

**Comment by wenston** [comment]
请问，这个问题解决了吗
