### ISSUE TITLE
官方示例 start 函数配置 destory true，切换子应用，内存持续增加

### ISSUE THREAD

**Issue by psybor** [jd-opensource/micro-app#400]
问题表现：
配置 `destory: true` 后，连续切换子应用，内存持续增加。

仓库：
https://github.com/micro-zoe/micro-app-demo

重现步骤：
测试1：任务管理器
1. 在 main_apps/react16/src/index.js 配置 start 函数，增加 `destroy: true,` 配置。
2. `yarn dev:main-react16`。
3. 访问首页，不打开控制台，打开浏览器任务管理器。
4. 连续切换 vue2, vue3, vue-vite, nextjs11, nuxtjs2 5个子应用，循环8次，每次循环结束后等待15s GC，然后查看内存。
![image](https://user-images.githubusercontent.com/74579438/169329744-e493f9cc-e704-4208-8113-e3dc67ee3385.png)

测试2：控制台内存查看
1. 打开控制台的内存 tab，点击收集垃圾，选择时间线配置
2. 记录，连续切换 vue2, vue3, vue-vite, nextjs11, nuxtjs2 5个子应用，循环4次。
3. 点击收集垃圾，然后停止记录
![image](https://user-images.githubusercontent.com/74579438/169332006-906efb35-afd3-4551-b08b-8a22023701db.png)

测试3： 配置 `destory: false`
1. 在 main_apps/react16/src/index.js 配置 start 函数，增加 `destroy: false,` 配置。
2. 打开控制台的内存 tab，点击收集垃圾，选择时间线配置
3. 记录，连续切换 vue2, vue3, vue-vite, nextjs11, nuxtjs2 5个子应用，循环4次。
4. 点击收集垃圾，然后停止记录
![image](https://user-images.githubusercontent.com/74579438/169333984-e794d83e-766b-467b-bc37-591168151e8b.png)

另外，在 `destory: true`模式下，第二次进入 react16, react 17 子应用报错，这又是另外的问题了。

## 环境信息
- micro-app版本：0.8

**Comment by bailicangdu** [comment]
好的，感谢反馈

**Comment by nova-qiang** [comment]
> 

在实际项目中，子应用包含了比较大的JS和CSS文件，所以每次加载一个子应用就增加几十兆内存。但是一直得不到释放，导致系统就越用越慢。所以请你能抓紧看一下。

**Comment by bailicangdu** [comment]
@nova-qiang 可以通过umd模式解决这个问题，不要设置destory  https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/advanced?id=_2%e3%80%81%e6%80%a7%e8%83%bdamp%e5%86%85%e5%ad%98%e4%bc%98%e5%8c%96

**Comment by ycxfun** [comment]
@bailicangdu 遇到了类似的我问题，使用了umd模式发现只有在切换路由的情况下，内存才会被释放。如果不切换路由的情况下，子应用有频繁的渲染和卸载行为，该如果解决呢？

**Comment by ycxfun** [comment]
@bailicangdu 遇到了类似的问题，使用了umd模式发现只有在切换路由的情况下，内存才会被释放。如果不切换路由的情况下，子应用有频繁的渲染和卸载行为，该如果解决呢？

**Comment by bailicangdu** [comment]
> @bailicangdu 遇到了类似的问题，使用了umd模式发现只有在切换路由的情况下，内存才会被释放。如果不切换路由的情况下，子应用有频繁的渲染和卸载行为，该如果解决呢？

micro-app版本是多少？

**Comment by ycxfun** [comment]
> > @bailicangdu 遇到了类似的问题，使用了umd模式发现只有在切换路由的情况下，内存才会被释放。如果不切换路由的情况下，子应用有频繁的渲染和卸载行为，该如果解决呢？
> 
> micro-app版本是多少？

0.8.10

**Comment by JerryWu1234** [comment]
> [bailicangdu](/bailicangdu)

为啥不能清除掉这些内存呢？

**Comment by ycxfun** [comment]
@bailicangdu 
![image](https://user-images.githubusercontent.com/25812139/203689062-08c2c47c-3bee-45f8-9569-18babdf5004b.png)
开启umd模式后，每次刷新页面js堆大小都在累加，即使硬性重载也不行

**Comment by bailicangdu** [comment]
设置destroy后每次子应用的渲染都会重新全部加载和执行js，会导致内存的增加，在1.0版本中这个问题得到一定缓解，还是会有，这是实现机制导致的

**Comment by JerryWu1234** [comment]
> 设置destroy后每次子应用的渲染都会重新全部加载和执行js，会导致内存的增加，在1.0版本中这个问题得到一定缓解，还是会有，这是实现机制导致的

因为每次new Function？

**Comment by bailicangdu** [comment]
不全是，主要是执行的部分

**Comment by JerryWu1234** [comment]
> 不全是，主要是执行的部分

![Hhsw6H3A5c](https://user-images.githubusercontent.com/27261522/203932148-f3225864-44dc-4d7f-86f5-d67404046c6c.jpg)
![8F8yawuzOE](https://user-images.githubusercontent.com/27261522/203932171-c077f70c-08ec-4a9e-a587-f1b734b7d44f.jpg)
确认下是这块吗，我是新人，所以想跟你确定下

**Comment by bailicangdu** [comment]
升级到1.0版本可以修复你说的这个问题 @wulinsheng123

**Comment by bailicangdu** [comment]
https://micro-zoe.com/docs/1.x/#/zh-cn/transfer

**Comment by JerryWu1234** [comment]
> 升级到1.0版本可以修复你说的这个问题 @wulinsheng123

导致内存堆积的问题是因为图片里面的代码吗？
我升级到了1.0但是还是有问题....

**Comment by ycxfun** [comment]
@bailicangdu 1.0版本我试了，子应用的unmount方法有触发但内存并没有减少，0.8.10版本倒是会有减少。是不是可以理解这个问题暂时只能缓解，不能根治？像数据标注这类有频繁渲染卸载操作的页面，是不是不太适用微前端的场景？

**Comment by JIJEvoid** [comment]
> 

我目前也遇到这个问题了，升级到1.0也并没有修复这个问题。目前来看只能通过keep-alive属性来规避大量重复生产string类型的render函数。
