### ISSUE TITLE
问下 有没什么辅助手段方案解决子应用首次加载白屏的等待时长长的问题

### ISSUE THREAD

**Issue by Kryzeno** [jd-opensource/micro-app#404]
问下 有没什么辅助手段方案解决子应用首次加载白屏的等待时长长的问题

**Comment by bailicangdu** [comment]
对于非首屏，可以使用预加载

**Comment by Kryzeno** [comment]
我这里用了预加载首屏的渲染时间还是偏慢

**Comment by 617450941** [comment]
希望有种手段可以预热子应用

**Comment by Kryzeno** [comment]
希望有种手段可以更好的预热子应用  实现同主应用级别的加载时间

**Comment by lanmingle** [comment]
这个问题我之前提过，没有单独一个加载事件来处理，我通过事件（不是全局）来控制

Created -> BeforeLoad
Mounted & Error -> AfterLoad

观察网络请求发现，加载 HTML 是还没有触发 Created 的，加载完 index 后才会触发 Created 事件，一般情况下现在的应用 html 页面内容很小，基本可以忽略，通过这个方式可以展示加载子应用进度条等，哈哈纯属自己折腾

**Comment by dream2023** [comment]
> 希望有种手段可以更好的预热子应用 实现同主应用级别的加载时间

首先需要确定究竟是什么导致了加载速度慢？有可能是子应用资源过多、单个资源过大、甚至可能是需要走一些接口后再显示页面，所以如果不确定到底是什么导致的，盲目谈优化不可取。

想要明确到底是什么导致的，可以观察 network 的时间线、performance ，或者使用类似 lighthose 进行评测。

假设通过观察，真的是资源的问题，以下是一些通用的解决方案：

- 如果是单个资源过大（虽然 webpack 建议是单个资源不要超过250k 左右，但是可以放宽到 1MB），要记得通过 webpack [optimization. splitChunks](https://webpack.js.org/plugins/split-chunks-plugin/) 进行拆分，针对于 node_modules 下的包，可以单独打出来，让其不受业务代码的影响；
- 是否使用 webpack [externals](https://webpack.js.org/configuration/externals/#root) 将一些第三方库 umd 化，并且相同依赖，仅需要主应用加载，子应用无需加载，比如一些 UI 库，可以大大减少体积；
- 是否使用过 webpack [module-federation](https://webpack.js.org/concepts/module-federation/#root) 去共享过一些通用代码

总体思路就是在进行实际测试后发现导致慢的核心原因，然后采取措施，一些通用思路就是减少文件大小，减少文件数量、共享代码、预加载等
