### ISSUE TITLE
Angular里micro-app元素无法通过ngFor之类的指令动态创建

### ISSUE THREAD

**Issue by Huansheng1** [jd-opensource/micro-app#408]
## 问题描述
> 问题的具体描述
Angular里micro-app元素无法通过ngFor之类的指令动态创建
如果通过循环指令创建的话，baseroute变量在子应用里将会为空，且在ng里window.microApp貌似是找不到的？
现在代码是手动复制n个元素，在上面写死相关子应用配置，感觉比较丑陋。。
能否支持 手动在js里动态添加某个应用 或者能让在模板支持设置动态的baseroute也行呀（现在设置是会报错的）
后来我想通过data传递baseroute数据，然后子应用通过`window.microApp`拿到传过来的，再修改自己的baseHref，发现拿不到`microApp`
或者主应用里支持修改子应用的`index.html`里的值也行
## 复现步骤
1.
```ts
<micro-app [attr.name]='currentMicroAppConfig?.name' [attr.url]='currentMicroAppConfig?.url + "/"'
            [attr.baseroute]='currentMicroAppConfig?.baseroute' (beforeshow)="sendLoadMicroChildAppEvent($event)"
            (afterhidden)="sendLoadMicroChildAppEvent($event)" (aftershow)="sendLoadMicroChildAppEvent($event)"
            keep-alive>
```
2. 子应用的 `window?.__MICRO_APP_BASE_ROUTE__`为undefined

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。

## 环境信息
- micro-app版本：
- 主应用前端框架&版本：
- 子应用前端框架&版本：
- 构建工具&版本：

**Comment by lanmingle** [comment]
得包装一个一对一的组件，然后再通过 for 来处理，还有 baseroute 在HTML中写在第一个位置上，别问我为什么，因为我都折腾过，哈哈哈

**Comment by Huansheng1** [comment]
> 
牛呀，大佬大佬，给你仓库点了个star

**Comment by zzhimin** [comment]
@lanmingle 牛啊，动态绑定的baseroute原来需要写在第一个位置，这个bug我好几天没有解决。
