### ISSUE TITLE
vue-基座绑定数据向子应用传值时，首次传值失败

### ISSUE THREAD

**Issue by M76chao** [jd-opensource/micro-app#41]
如标题。
此时传值失败

`<!-- 此时子应用主动接收参数时，获取不到 -->`
`<template>`
`  <micro-app :name='name' :url="url" :baseurl='baseurl' :data='microData'></micro-app>`
`</template>`
`<script>`
`export default { `
`  data () {`
`    return {`
`      name: 'customChart',`
`      url: 'http://localhost:1888/custom_chart/#/chartGather/index',`
`      baseurl: '/custom_chart',`
`      microData: {`
`        Authorization: 123,`
`        Token: 456`
`      }`
`    }`
`  },`
`  methods: {},`
`}`
`</script>`

需手动触发micro-app 的监听才可以

`
mounted () {
    console.log(this.microData);
    this.microData = {...this.microData}
  }
`  

期望： 默认绑定的数据能在子应用中主动获取到

**Comment by bailicangdu** [comment]
因为子应用是异步渲染的，所以可能产生数据先发送，子应用之后才监听的情况。这时有两种方式解决：1、设置addDataListener第二个参数为true window.microApp?.addDataListener(dataListener: Function, autoTrigger?: boolean)  2、window.microApp?.getData()
