### ISSUE TITLE
请问基座和子应用都是hash路由，是否支持加载多个子应用，谢谢！

### ISSUE THREAD

**Issue by panyouqing** [jd-opensource/micro-app#412]

**Comment by bailicangdu** [comment]
可以，设置好路由就行

**Comment by dongoa** [comment]
> 可以，设置好路由就行

请问是怎么设置的，react 双hash路由 只能打开子路由#之前的页面，子应用多个页面怎么加载呢 两个#不胜生效

**Comment by bailicangdu** [comment]
> > 可以，设置好路由就行
> 
> 请问是怎么设置的，react 双hash路由 只能打开子路由#之前的页面，子应用多个页面怎么加载呢 两个#不胜生效

升级到[1.0.0-alpha.3](https://www.npmjs.com/package/@micro-zoe/micro-app/v/1.0.0-alpha.3)版本可以解决，但功能还不稳定

**Comment by liuruibin** [comment]
我在官方的demo中没找到基座和子应用都是hash路由的例子，我自己改了一下没有成功，主应用和子应用都是 vite vue，重复点击菜单后浏览器地址栏会变成 只有 / 了

**Comment by bailicangdu** [comment]
> 我在官方的demo中没找到基座和子应用都是hash路由的例子，我自己改了一下没有成功，主应用和子应用都是 vite vue，重复点击菜单后浏览器地址栏会变成 只有 / 了

vite暂时不支持
