### ISSUE TITLE
子应用集成进来以后，主应用报错  TypeError: Cannot read properties of undefined (reading 'call')

### ISSUE THREAD

**Issue by likaiji** [jd-opensource/micro-app#413]
主应用，子应用均为vue3   
<img width="933" alt="image" src="https://user-images.githubusercontent.com/24820280/170929602-52c7e22f-9f0a-4433-bd57-12216799453b.png">

**Comment by bailicangdu** [comment]
应该是这个问题导致的https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/sandbox?id=_2%e3%80%81%e5%ad%90%e5%ba%94%e7%94%a8%e6%8a%9b%e5%87%ba%e9%94%99%e8%af%af%e4%bf%a1%e6%81%af%ef%bc%9axxx-%e6%9c%aa%e5%ae%9a%e4%b9%89

**Comment by Huansheng1** [comment]
你可以刷新一下再试一次，我也遇见过，问题不明；刷新一次可以正常加载
![image](https://user-images.githubusercontent.com/33859558/170971758-35a7178a-4545-4732-95b6-027c84709fe8.png)
![image](https://user-images.githubusercontent.com/33859558/170971922-e10ee1d5-0c8f-4de4-bc74-8575f9468c13.png)

**Comment by likaiji** [comment]
我这边的问题是子应用的package.json的name与基座应用不一致导致的

**Comment by Huansheng1** [comment]
> 

啥，子应用package.json的name还需要和基座应用一致？我蒙蔽了，官网没讲呀

**Comment by NiShuiXingZ** [comment]
> 我这边的问题是子应用的package.json的name与基座应用不一致导致的

你说的应该是name相同而导致的吧。刚才看了你的答复发现我的两个项目就是package.json name重名了，然后就报以上问题了。修改为不同的就好了。
