### ISSUE TITLE
document.write 方法没有被劫持

### ISSUE THREAD

**Issue by LinFeng1997** [jd-opensource/micro-app#415]
## 背景
> 描述您希望改进的问题。
在使用了一些第三方 JS 库的时候，它们会使用 document.write 方法，如：
```
document.write('<script async src="https://s9.cnzz.com/z_stat.php?id=xxx&web_id=yyy"></script>');
```
这个时候基座应用会被破坏。

## 期望的效果
劫持 document.write 方法，只改变子应用内部的 html。

**Comment by jardenliu** [comment]
要劫持这个的话，是不是应该顺便劫持一下document.close

**Comment by Perseman** [comment]
手动劫持，然后修改到对应的appName
