### ISSUE TITLE
基座应用中XMLHttpRequest的原型方法被修改对子应用造成影响

### ISSUE THREAD

**Issue by ztw2010** [jd-opensource/micro-app#417]
基座应用中XMLHttpRequest的原型方法被修改了，对子应用造成影响，要怎么解决？例如基座应用XMLHttpRequest的原型上的send方法被修改，在基座应用中的send方法中增加自己的逻辑，比如把某个请求头给删掉了，而子应用需要用到这个请求头，就会对子应用造成影响

**Comment by bailicangdu** [comment]
XMLHttpRequest是全局唯一的，基座修改会影响子应用
