### ISSUE TITLE
有解决基座应用和子应用共用依赖的特性吗

### ISSUE THREAD

**Issue by airkingZy** [jd-opensource/micro-app#42]
abc项目都有共同的依赖，vue，vuex或者react，react-dom，能让子应用bc去使用基座a上的依赖，做到给子应用减重的操作吗。
现在没有的话，未来有这个功能feature的计划吗。或者说可以在现有基础上自己通过module federation去做

**Comment by loo41** [comment]
那就主应用全局加载，子应用使用呗，我们就是放到基座下，子应用使用，但是打包的时候不打包，使用全局的就好啊。

**Comment by bailicangdu** [comment]
方式一：公共仓库打包成js文件，名称和地址固定，多个应用同时使用，利用浏览器缓存机制可以做到，但这要修改一些配置。第二个方式是通过数据通信将包依赖传递到子应用，例如都是react项目，那么可以通过import * as React from 'react'; import * as reactDom from 'react-dom'，然后将react和reactDom传递给子应用使用

**Comment by airkingZy** [comment]
> 方式一：公共仓库打包成js文件，名称和地址固定，多个应用同时使用，利用浏览器缓存机制可以做到，但这要修改一些配置。第二个方式是通过数据通信将包依赖传递到子应用，例如都是react项目，那么可以通过import * as React from 'react'; import * as reactDom from 'react-dom'，然后将react和reactDom传递给子应用使用

方式2说的数据通讯依赖是指 通过microApp.setData 这种方法，在主应用这样把依赖传递下去吗.在子应用中如何去使用呢，在子应用的入口可以通过window.microApp?.addDataListener 拿到传递过来的react，子应用其他的page页面的import React from "react"; 应该如何去处理呢。

**Comment by bailicangdu** [comment]
如果你既想嵌入微前端运行又想单独运行，方式2显然是不行的
