### ISSUE TITLE
iconfont隔离问题

### ISSUE THREAD

**Issue by xiaozhanghui** [jd-opensource/micro-app#423]
## iconfont隔离问题
> 子应用的iconfont会覆盖主应用的iconfont，当content的值相同的时候。

## 复现步骤
1.
2.

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。

## 环境信息
- micro-app版本：0.8.5
- 主应用前端框架&版本：
- 子应用前端框架&版本：
- 构建工具&版本：

**Comment by bailicangdu** [comment]
font-family 的名称冲突了，改成其它名字

**Comment by xiaozhanghui** [comment]
@bailicangdu 
不是名称一样，比如主项目的iconfont.css文件中
.icon1:before {
  content: "\e642";
}
子项目
.icon2:before {
  content: "\e642";
}
这时候主项目的icon1图标就变成子项目的icon2项目了。
阿里的iconfont在升级，现在还不好弄个重现的项目，不知道我表达的清楚吗？

**Comment by Perseman** [comment]
iconfont都由主应用引入呢？

**Comment by xiaozhanghui** [comment]
> iconfont都由主应用引入呢？

两个应用iconfont文件不一样，子应用也会被多个主应用引用
