### ISSUE TITLE
样式失效

### ISSUE THREAD

**Issue by Kimkow** [jd-opensource/micro-app#424]
## 问题描述
> 问题的具体描述
1、本地开发环境，打包后ngnix部署样式正常，无任何异常
2、子应用二级异步加载的路由页面样式失效。
3、禁用样式隔离后，样式正常了。但是scss变量文件的woff等字体文件路径出错，style标签里assets资源引用路径出错
## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。
1.本地开发环境，打包后ngnix部署截图
![image](https://user-images.githubusercontent.com/22110416/172599173-4ca62e58-8e63-4c3d-b7d6-c701674296df.png)
![image](https://user-images.githubusercontent.com/22110416/172599923-2dda9115-68b9-42e7-b5e2-0848869548bd.png)

2. 子应用二级异步加载的路由页面样式失效截图
![image](https://user-images.githubusercontent.com/22110416/172598796-3998a32d-3936-4fc9-acff-81591c1e0b73.png)
![image](https://user-images.githubusercontent.com/22110416/172599487-a867abd2-bdef-4f07-bcb0-6f21502f7aad.png)

3.禁用样式隔离后，截图
![image](https://user-images.githubusercontent.com/22110416/172599699-3be306b2-7a16-4360-8854-e456ed7f9411.png)
![image](https://user-images.githubusercontent.com/22110416/172599807-274c9bdd-a0a5-4984-bf6e-b6e9d3ca173c.png)

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。

## 环境信息
- micro-app版本：0.8.5
- 主应用前端框架&版本：vue3,vite
- 子应用前端框架&版本：vue2, vue/cli-service 4.4.4
- 构建工具&版本：npm 16.13.1

**Comment by Kimkow** [comment]
![image](https://user-images.githubusercontent.com/22110416/172600336-e31dc133-9940-455a-a317-6689ea15986e.png)
publicPath是有设置的

**Comment by Kimkow** [comment]
目前最头疼的地方就是，设置了disableScopecss，样式正常了，但是部分资源路径错误，直接访问到基应用的地址了。
删掉disableScopecss，资源路径正确无误，但是就是二级router-view 里面的页面样式全部失效了。一级的router-view样式都正常生效

**Comment by alex86w** [comment]
问题后面解决了么？

**Comment by whatthecole** [comment]
我貌似也有类似的问题，我子应用用的next.js，设置了disableScopecss样式正常，删除就不正常。查看dom节点，发现所有样式加了两次前缀
### 环境信息
- micro-app版本：1.0.0-alpha.10

**Comment by bailicangdu** [comment]
> 我貌似也有类似的问题，我子应用用的next.js，设置了disableScopecss样式正常，删除就不正常。查看dom节点，发现所有样式加了两次前缀
> 
> ### 环境信息
> * micro-app版本：1.0.0-alpha.10

可以提供一个复现的demo吗

**Comment by whatthecole** [comment]
打了一下断点，发现scoedCSS会执行两遍。

**第一遍的时候，此时样式内容还未被处理。**
![image-20221027185451288](https://user-images.githubusercontent.com/6036348/198268109-3dfd47d6-8bfa-4cb5-a8ed-6359feaefee0.png)

进入**commonAction**，此时`__MICRO_APP_HAS_SCOPED__`为`undefined`

![image-20221027185728832](https://user-images.githubusercontent.com/6036348/198268413-8f03bc7f-b039-4145-ab97-f0981f262a5b.png)
---

第二遍的时候（此时样式内容已经加上前缀了）

![image-20221027185907334](https://user-images.githubusercontent.com/6036348/198268654-fc4af4ae-6b43-4145-8cd3-f1643a432654.png)
再次进入**commonAction**，此时`__MICRO_APP_HAS_SCOPED__`还是为`undefined`

![image-20221027185957768](https://user-images.githubusercontent.com/6036348/198268837-0966a1ec-b282-4474-9d69-4f64f458046c.png)

---
最终输入的结果为 
![image](https://user-images.githubusercontent.com/6036348/198269739-1b78ddac-61e4-425f-be13-d340f461d3ab.png)

**Comment by bailicangdu** [comment]
nextjs的版本是多少 @chenjunkai-ones

**Comment by whatthecole** [comment]
> nextjs的版本是多少 @chenjunkai-ones

12.3.1

**Comment by humorHan** [comment]
同样的问题，请问最后怎么额解决的

**Comment by clevernight** [comment]
同样问题，请问解决了吗
