### ISSUE TITLE
主应用在集成子应用的时候, fetch 命中强缓存报错

### ISSUE THREAD

**Issue by xiangxinji** [jd-opensource/micro-app#426]
现在我们的公共库全部都放到 cdn 上了,  但是子应用在渲染的时候因为强缓存导致 fetch 报错. 如果使用自定义fetch 加上参数 ({ cache : 'no-cache' }) 就没问题. 请问这个有比较好的解决方案吗?

**Comment by HenryZhu-1988** [comment]
能给个demo 嘛？

**Comment by bailicangdu** [comment]
microApp默认对于html做了no-cache，只要css js文件的后缀hash不一致就没问题，如果静态资源的地址没变，那么命中缓存是理所当然的，比较好的处理方式就像你说的，通过自定义fetch网络 @xiangxinji

**Comment by lolipop99** [comment]
> microApp默认对于html做了no-cache，只要css js文件的后缀hash不一致就没问题，如果静态资源的地址没变，那么命中缓存是理所当然的，比较好的处理方式就像你说的，通过自定义fetch网络 @xiangxinji

microApp version对于html资源做了缓存处理，fetch.no-cache（no-cache — 浏览器在其 HTTP 缓存中寻找匹配的请求。）

no-store — 浏览器直接从远程服务器获取资源，不查看缓存，并且不会使用下载的资源更新缓存。

https://developer.mozilla.org/zh-CN/docs/Web/API/Request/cache
