### ISSUE TITLE
父应用更改子应用Url时，子应用不会重新渲染页面

### ISSUE THREAD

**Issue by raoenhui** [jd-opensource/micro-app#428]
## 问题描述
> 问题的具体描述

## 复现步骤
点击父页面中的不同按钮，更改了子页面url，子页面不会重新渲染。

## 上传截图
http://test1.yx.jd.com/activity-manage/myCreate/daily-activities-operation/managemc/ruleSetAndInvite?entry=0&activityId=10637710&blockId=141003227&from=acore
![9E75D597C181110B39E999840E3A753F](https://user-images.githubusercontent.com/14011130/173533479-10c5a069-c5ad-4b99-b422-8abb853c07f9.jpg)

## 复现仓库
>  https://coding.jd.com/FE/activity-core.git 

## 环境信息
- micro-app版本：0.4.3
- 主应用前端框架&版本：React16.13.1
- 子应用前端框架&版本：React16.13.1
- 构建工具&版本：webpack

**Comment by bailicangdu** [comment]
?

**Comment by jiangshengdev** [comment]
遇到类似的问题

父应用 https://vvbin.cn/doc-next/ 搭建 vue3

子应用 https://gitee.com/liuge1988/kitty-ui 搭建 vue2

父应用中的多tab页面切换的时候，从 vue3切换到vue2正常，但是从vue2切换到vue2则无响应

**Comment by bailicangdu** [comment]
参考 https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/jump

**Comment by jiangshengdev** [comment]
> 参考 https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/jump

感谢，已经参考这个文档解决了

另外还参考文档，将子应用中的“编程式的导航”都采用重新封装的方法，可以在子应用中打开父应用的新tab，用起来就像是同一个应用的感觉

**Comment by BrignLau** [comment]
> > 参考 https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/jump
> 
> 感谢，已经参考这个文档解决了
> 
> 另外还参考文档，将子应用中的“编程式的导航”都采用重新封装的方法，可以在子应用中打开父应用的新tab，用起来就像是同一个应用的感觉

@jiangshengdev 
你好，可以问一下在子应用中打开父应用tab是怎么操作的吗？

**Comment by jiangshengdev** [comment]
> > > 参考 https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/jump
> > 
> > 
> > 感谢，已经参考这个文档解决了
> > 另外还参考文档，将子应用中的“编程式的导航”都采用重新封装的方法，可以在子应用中打开父应用的新tab，用起来就像是同一个应用的感觉
> 
> @jiangshengdev 你好，可以问一下在子应用中打开父应用tab是怎么操作的吗？

就是子应用传递新tab的url等数据给父应用，父应用接受到数据进行新增tab操作

可以参考数据通信文档

https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/data
