### ISSUE TITLE
子应用的容器没有添加 name 属性导致样式失效

### ISSUE THREAD

**Issue by rxliuli** [jd-opensource/micro-app#43]
> 可复现示例：<https://github.com/rxliuli/micro-app-demo/tree/feat_microapp>

![image](https://user-images.githubusercontent.com/24560368/129686912-bb8d6bf1-9e12-474e-a14c-18058d5d49ff.png)

复现步骤

1. yarn 安装依赖
2. `cd apps/main-micro-app/ && yarn dev`
3. `cd apps/vue-cli-app/ && yarn dev`

即可看到这个错误

---

其实在默认情况下也不会自动重写 img 的请求路径，上图中吾辈强制配置了子应用的 `publicPath`

**Comment by bailicangdu** [comment]
将micro-app放在vue创建实例之后运行，暂时先用这种方式解决吧，具体原因还没找到。图片地址失效是因为vue3的静态模版，静态的html直接写到文档中，没有创建过程无法监听和拦截，所以vue3下，使用publicPath来处理吧。
![image](https://user-images.githubusercontent.com/20297227/129694254-ef34850e-f914-4e64-8f21-385ee96a56a0.png)

**Comment by rxliuli** [comment]
> 将 micro-app 放在 vue 创建实例之后运行，暂时先用这种方式解决吧，具体原因还没找到。图片地址失效是因为 vue3 的静态模版，静态的 html 直接写到文档中，没有创建过程无法监听和拦截，所以 vue3 下，使用 publicPath 来处理吧。
> ![image](https://user-images.githubusercontent.com/20297227/129694254-ef34850e-f914-4e64-8f21-385ee96a56a0.png)

对了，支持 vite 能否提供更简单的使用方式？形如 <https://github.com/tengmaoqing/vite-plugin-qiankun> 这种插件

**Comment by bailicangdu** [comment]
> > 将 micro-app 放在 vue 创建实例之后运行，暂时先用这种方式解决吧，具体原因还没找到。图片地址失效是因为 vue3 的静态模版，静态的 html 直接写到文档中，没有创建过程无法监听和拦截，所以 vue3 下，使用 publicPath 来处理吧。
> > ![image](https://user-images.githubusercontent.com/20297227/129694254-ef34850e-f914-4e64-8f21-385ee96a56a0.png)
> 
> 对了，支持 vite 能否提供更简单的使用方式？形如 https://github.com/tengmaoqing/vite-plugin-qiankun 这种插件

目前没有

**Comment by bailicangdu** [comment]
在examples/children/vite/vite.config.js中有一个插件的雏形，我觉得太过简单，没有提取成插件，只在文档中展现了
![image](https://user-images.githubusercontent.com/20297227/129700191-0b02d612-75bf-4cc1-8fae-4c8fba36bdec.png)

**Comment by nieaowei** [comment]
手动注入name，也能解决问题（人麻）
```ts
onMounted(() => {
  let e = document.getElementById('vue2')
  console.log(e.attributes.getNamedItem("name"))
  let a = document.createAttribute("name")
  a.value = 'vue2'
  e.attributes.setNamedItem(a)
})
```

**Comment by bailicangdu** [comment]
问题已修复 https://github.com/micro-zoe/micro-app/releases/tag/v0.2.5
