### ISSUE TITLE
切换到某个子应用页面， 然后刷新浏览器， 页面直接 404 

### ISSUE THREAD

**Issue by zdJOJO** [jd-opensource/micro-app#431]
## 问题描述
> **基座应用** 和 **子应用** 都是用 `BrowserRouter history` 路由， 切换到某个子应用，然后刷新， 页面 404；

> <font color='#ff4d4f'>**注:**</font> 如果子应用使用  `HashRouter history`  ， 并不会出现这个问题。

## 复现步骤
1. 切换到某个应用， 
2. 刷新页面

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。

## 复现仓库
> https://github.com/zdJOJO/micro.git
```
1. git checkout micro-app

2. yarn install

3.  yarn run dev

4. 暂时没有子项目，可以自己配一个，然后切换到子应用，刷新浏览器， 直接404 
```

## 环境信息
- micro-app版本： 
```
"@micro-zoe/micro-app": "^0.8.5"
```
- 主应用前端框架&版本：
```
  "react": "18.0.0",
   "react-dom": "18.0.0",
   "react-router-dom": "6.3.0",
    "vite": "^2.6.4",
```
- 子应用前端框架&版本：

```
 "react-dom": "^16.11.0",
 "react-router-dom": "^5.1.2",
 "webpack": "^4.41.2",
```

- 构建工具&版本：
```
  基座应用： "vite": "^2.6.4",
  子应用："webpack": "^4.41.2",
```

**Comment by bailicangdu** [comment]
路由的问题，baseRoute配置了吗

**Comment by zdJOJO** [comment]
子应用配了

>  `ROUTE_PATH.APP_1` 的 值是 `app1`
```
// 基座应用中配的子应用： 
import { ROUTE_PATH } from '@/route/enum'
import React from 'react'

const App1 = () => {
  return (
    <div>
      <micro-app name={ROUTE_PATH.APP_1} url="http://127.0.0.1:3001/" baseroute={`/${ROUTE_PATH.APP_1}`} />
    </div>
  )
}

export default App1
```

**Comment by bailicangdu** [comment]
子应用的代码贴一下呢，浏览器url截图发一下

**Comment by zdJOJO** [comment]
> 子应用的代码贴一下呢，浏览器url截图发一下

## 子引用代码片段

```
//  App.tsx

import {
  BrowserRouter,
  Route,
  Switch
} from 'react-router-dom'

<BrowserRouter basename={window.__MICRO_APP_BASE_ROUTE__ || '/'}>
  <Layout>
    <Switch>
      <Suspense  fallback={   <>  loading...  </>  } >
        <Route exact key="schedulesList" path={SCHEDULE}>
          <Plans />
        </Route>
      </Suspense>
    </Switch>
  </Layout>
</BrowserRouter >
```


````
//  public-path.js

// __MICRO_APP_ENVIRONMENT__和__MICRO_APP_PUBLIC_PATH__是由micro-app注入的全局变量
if (window.__MICRO_APP_ENVIRONMENT__) {
  // eslint-disable-next-line
  __webpack_public_path__ = window.__MICRO_APP_PUBLIC_PATH__
}

````


```
//  webpack 配置
devServer: {
    host: '127.0.0.1',
    port: port,
    contentBase: path.appDist,
    historyApiFallback: true,
    hot: true,
    inline: true,
    headers: {
      'Access-Control-Allow-Origin': '*'
    }
  },
```

### 项目截图

1.  正常：
![image](https://user-images.githubusercontent.com/25069798/174244920-2c48cbf3-0075-4e28-afbd-6e76d4a6f76d.png)



2.  刷新之后
![image](https://user-images.githubusercontent.com/25069798/174244971-13b151cd-b677-4912-9b5e-e382b64808e4.png)

**Comment by meimosor** [comment]
我也遇到这个问题了，换成hash模式就没问题。history下确实会这样

**Comment by zdJOJO** [comment]
> 我也遇到这个问题了，换成hash模式就没问题。history下确实会这样

老哥， 你 `react-router-dom` 的版本是 V6 还是 V5 ， 我用的是 V6, 没试过V5 ，可能跟版本有关系

**Comment by bailicangdu** [comment]
改成这样就可以了
<img width="437" alt="image" src="https://user-images.githubusercontent.com/20297227/174562246-994d72ce-699c-46d4-8cdc-f6d6fa719abd.png">

react-router6的泛路由设置不太一样，https://reactrouter.com/docs/en/v6/getting-started/overview#descendant-routes

**Comment by zdJOJO** [comment]
> 改成这样就可以了 <img alt="image" width="437" src="https://user-images.githubusercontent.com/20297227/174562246-994d72ce-699c-46d4-8cdc-f6d6fa719abd.png">
> 
> react-router6的泛路由设置不太一样，https://reactrouter.com/docs/en/v6/getting-started/overview#descendant-routes

OK， THX

**Comment by zdJOJO** [comment]
> 改成这样就可以了 <img alt="image" width="437" src="https://user-images.githubusercontent.com/20297227/174562246-994d72ce-699c-46d4-8cdc-f6d6fa719abd.png">
> 
> react-router6的泛路由设置不太一样，https://reactrouter.com/docs/en/v6/getting-started/overview#descendant-routes

大佬，虽然刷新不会出现404，改成这样又出现另外一个问题， 浏览器 url 会出现  `*`

![image](https://user-images.githubusercontent.com/25069798/174696571-c40aff95-bd6a-41d5-829b-4a78f3331d9b.png)

**Comment by bailicangdu** [comment]
传递给子应用时，`/*`要去掉

**Comment by zdJOJO** [comment]
> 传递给子应用时，`/*`要去掉

懂了，懂了。
