### ISSUE TITLE
子系统在调用router.go(-1)时候会概率性报错

### ISSUE THREAD

**Issue by potatoes0521** [jd-opensource/micro-app#437]
报错内容是  Cannot read properties of null (reading 'nextSibling')
<img width="514" alt="image" src="https://user-images.githubusercontent.com/32003360/174581438-4f83eaa3-fd75-4080-a227-d2e8b6886961.png">

主应用是 vue3.2.25 vue-router 4.0.14 vite
子应用是 vue3.2.31 vue-router 4.0.14 webpack
在子应用调用 router.go(-1)时候报错  已经使用了  官网修复报错的函数

想问下  比如说我打开了   A, B, C三个子系统   在C 系统进入了一个页面  然后在页面内跳转到二级页面   在二级页面内点击返回调用 router.go(-1)的时候  A,B两个已经被隐藏的系统router.beforeEach 会被触发  这样是对的吗
![image](https://user-images.githubusercontent.com/32003360/174581155-f464e2a8-3d02-479a-8e67-4a6a7c593b55.png)

**Comment by bailicangdu** [comment]
能提供复现的demo吗

**Comment by potatoes0521** [comment]
稍等  我整理一个

**Comment by potatoes0521** [comment]
> 能提供复现的demo吗

https://github.com/potatoes0521/microapp-demo.git

您好  demo 已经提供了   但是报错这个是概率性的   主要是想咨询一下    
比如说我打开了 A, B, C三个子系统 在C 系统进入了一个页面 然后在页面内跳转到二级页面 在二级页面内点击返回调用 router.go(-1)的时候 A,B两个已经被隐藏的系统router.beforeEach 会被触发 这样是对的吗

如果demo里面有什么需要我解答的  随时到

**Comment by bailicangdu** [comment]
如果子应用是keep-alive是正常的，router.go会发送popState事件，这个事件是全局的，所有正在运行的应用的路由守卫都会被触发

**Comment by potatoes0521** [comment]
> 如果子应用是keep-alive是正常的，router.go会发送popState事件，这个事件是全局的，所有正在运行的应用的路由守卫都会被触发

好的 感谢
