### ISSUE TITLE
shadowDOM开启导致子应用elementUI的字体样式丢失

### ISSUE THREAD

**Issue by oydiligent** [jd-opensource/micro-app#438]
## 问题描述
> 问题的具体描述
开发环境，基座开启shadowDOM，子应用采用的vue2+elementUI，子应用中elementUI的字体图标失效

## 复现步骤
1.基座开启shadowDOM
2.子应用采用的vue2+elementUI，elementUI全局引用，已导入elementUI全局样式；
3.子组件中elementUI组件上自带的icon失效：
4.关闭shadowDOM，icon生效

## 上传截图
> 
![image](https://user-images.githubusercontent.com/19690319/174590252-5cc657bc-fc8f-4a7b-a1b0-58847d450a9a.png)
![image](https://user-images.githubusercontent.com/19690319/174590324-9c80d47e-f276-4b82-acdc-9b84f61631d9.png)
![image](https://user-images.githubusercontent.com/19690319/174590447-cf391812-28b8-4d3f-a0ff-dab5b7906434.png)

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。

## 环境信息
- micro-app版本：^0.8.5
- 主应用前端框架&版本："vite": "^2.9.9", "vue": "^3.2.25",
- 子应用前端框架&版本：@vue/cli 5.0.0，"vue": "^2.6.14","element-ui": "^2.15.8",
- 构建工具&版本："vite": "^2.9.9"

**Comment by JackieZhang-Coding** [comment]
@bailicangdu 请问这个问题估计什么时候修复？

**Comment by cnLiuMing** [comment]
同问

**Comment by cnLiuMing** [comment]
默认会请求基座的端口

**Comment by Caveolaes** [comment]
有解决么？

**Comment by Supermariozmx** [comment]
这个关闭shadowdom后图标可以展示，会出现其他问题吗

**Comment by Mmmy-a** [comment]
这个问题怎么关闭了？解决了吗？
