### ISSUE TITLE
官网示例项目，安装完依赖后，无法启动应用

### ISSUE THREAD

**Issue by tail1231** [jd-opensource/micro-app#439]
clone的该源码：https://github.com/micro-zoe/micro-app/tree/dev/dev
1. yarn bootstrap
2. yarn start:main-vite
![image](https://user-images.githubusercontent.com/47874311/174700043-11182eba-041d-431f-aa61-75b0df0f5280.png)

**Comment by bailicangdu** [comment]
有可能是vite版本导致的
