### ISSUE TITLE
基座和子应用都是vue3+vite，页面加载失败，

### ISSUE THREAD

**Issue by zhoufanglu** [jd-opensource/micro-app#441]
## 问题描述
> 主应用报错 [Vue warn]: Failed to resolve component: micro-app
![I2F@CPWF7$XG%$D3)CLGKXF](https://user-images.githubusercontent.com/24451091/174789574-2e5188b6-30f3-46fe-b5b6-d528adadc941.png)
还有 官方步骤 跟github demo好像有点出入。

### 基座, 感觉有问题
`main.js`
```js
import { createApp } from 'vue'
import microApp from '@micro-zoe/micro-app'
import App from './App.vue'
import router from './router'

// store
import { setupStore } from './store'

// console.log(8, process.env.NODE_ENV)
// 微前端-microApp-注入
// microApp.start()
microApp.start({
  plugins: {
    modules: {
      'appname-vite': [
        {
          loader(code) {
            if (process.env.NODE_ENV === 'development') {
              // 这里 /basename/ 需要和子应用vite.config.js中base的配置保持一致
              // eslint-disable-next-line no-param-reassign
              code = code.replace(/(from|import)(\s*['"])(\/child\/vite\/)/g, all => {
                return all.replace('/vue3-vite/', 'http://localhost:3001/vue3-vite/')
              })
            }

            return code
          }
        }
      ]
    }
  }
})

const app = createApp(App)

setupStore(app)

app.use(router).mount('#app')

```

## 复现仓库
> [github仓库](https://github.com/zhoufanglu/micro-app-study)

## 环境信息
- micro-app版本："@micro-zoe/micro-app": "^0.8.5",
- 主应用前端框架&版本：vue3.2, vite.2.9
- 子应用前端框架&版本：vue3.2, vite.2.9
- 构建工具&版本：vite.2.9

**Comment by bailicangdu** [comment]
<img width="713" alt="image" src="https://user-images.githubusercontent.com/20297227/174790328-cdcdbbe5-1664-48d7-ab12-ae8734f23526.png">

**Comment by zhoufanglu** [comment]
> ```js
> appname
> ```

感谢回答，我修改后还是报一样的错， 想问下，microApp.start是放在组件内， 还是`main.js`内

**Comment by bailicangdu** [comment]
<img width="806" alt="image" src="https://user-images.githubusercontent.com/20297227/174792292-9c85016d-4d1e-4a1f-894b-d0688fe67be1.png">

**Comment by bailicangdu** [comment]
放在main.js中

**Comment by zhoufanglu** [comment]
> 放在main.js中

ok 出来了，sry, 是我看的不仔细，十分感谢， 子应用的图片路径只能填 `绝对路径`吗？我看`相对路径`无法识别
* 绝对路径成功
```js
  <img alt="Vue logo" src="src/assets/logo.png" />
```
* 相对路径失败
```js
  <img alt="Vue logo" src="../src/assets/logo.png" />
```
错误: `GET http://localhost:3000/vue3-vite/src/assets/logo.png 404 (Not Found)`
我看请求地址是用的基座的ip，是否有地方可以配置下？

**Comment by bailicangdu** [comment]
目前只能写死为绝对地址

**Comment by zhoufanglu** [comment]
> 目前只能写死为绝对地址
请问vite中 基座怎么传参， 官方文档写的不是很清楚。
```js
// 基座传参
// 注意：每个子应用根据appName单独分配一个通信对象
window.eventCenterForAppxx = new EventCenterForMicroApp(appName)
```
