### ISSUE TITLE
请问什么时候触发unmount事件?

### ISSUE THREAD

**Issue by zhoufanglu** [jd-opensource/micro-app#445]
## 问题描述
> 请问什么时候触发unmount事件?

## 复现步骤
* 看你demo，看到子路由写了这么一个监听函数，什么时候触发？
```js
// // 监听卸载操作
// window.addEventListener('unmount', function () {
//   app.unmount()
//   // 卸载所有数据监听函数
//   window.eventCenterForAppNameVite?.clearDataListener()
//   console.log('微应用child-vite卸载了')
// })
```

## 环境信息
- micro-app版本：
- 主应用前端框架&版本：vue3 vite2.9
- 子应用前端框架&版本：vue3 vite2.9

**Comment by zhoufanglu** [comment]
子应用目前不知道怎么触发此钩子函数
```js
// 子应用
// 子应用卸载
window.addEventListener('unmount', function () {
  // 执行卸载相关操作
  console.log('子应用卸载钩子函数-------------')
})
```

**Comment by lp0124** [comment]
+1

**Comment by lp0124** [comment]
从 micro-app-demo 中试了下，若配置了 disable-sandbox 则无法触发 window.addEventListener('unmount')

**Comment by zhoufanglu** [comment]
> 从 micro-app-demo 中试了下，若配置了 disable-sandbox 则无法触发 window.addEventListener('unmount')


这个属性我没有配置，请问在哪的？

**Comment by lp0124** [comment]
> > 从 micro-app-demo 中试了下，若配置了 disable-sandbox 则无法触发 window.addEventListener('unmount')
> 
> 这个属性我没有配置，请问在哪的？

基座 micro-app 标签上写的，子应用用vite的话肯定配置了的，我这边也遇到这个问题

**Comment by zhoufanglu** [comment]
> > > 从 micro-app-demo 中试了下，若配置了 disable-sandbox 则无法触发 window.addEventListener('unmount')
> > 
> > 
> > 这个属性我没有配置，请问在哪的？
> 
> 基座 micro-app 标签上写的，子应用用vite的话肯定配置了的，我这边也遇到这个问题

disablesandbox 这个属性我本来就加的😂， 方便留个联系方式吗？

**Comment by lp0124** [comment]
> 

我看[micro-app](https://github.com/micro-zoe/micro-app)代码里做了window.removeEventListener('unmount')的操作，由于没有沙箱，所以把子应用的这个事件监听也给卸载了。我这边暂时是通过自定义别的事件名去规避下这个bug。

<img width="696" alt="image" src="https://user-images.githubusercontent.com/22974194/175491343-3bd0c853-0c51-4001-9b90-8d4a8a7cdca3.png">
<img width="479" alt="image" src="https://user-images.githubusercontent.com/22974194/175491429-a8f43f03-4312-4136-a3e6-88728d927347.png">
<img width="643" alt="image" src="https://user-images.githubusercontent.com/22974194/175491467-5b992885-dac3-410b-b417-546ef3c8c1e7.png">

**Comment by zhoufanglu** [comment]
> > 
> 
> 我看[micro-app](https://github.com/micro-zoe/micro-app)代码里做了window.removeEventListener('unmount')的操作，由于没有沙箱，所以把子应用的这个事件监听也给卸载了。我这边暂时是通过自定义别的事件名去规避下这个bug。
> 
> <img alt="image" width="696" src="https://user-images.githubusercontent.com/22974194/175491343-3bd0c853-0c51-4001-9b90-8d4a8a7cdca3.png">
> 
> <img alt="image" width="479" src="https://user-images.githubusercontent.com/22974194/175491429-a8f43f03-4312-4136-a3e6-88728d927347.png">
> 
> <img alt="image" width="643" src="https://user-images.githubusercontent.com/22974194/175491467-5b992885-dac3-410b-b417-546ef3c8c1e7.png">

谢谢 这样确实可行， 那请问怎么销毁呢

**Comment by zhoufanglu** [comment]
> > > 
> > 
> > 
> > 我看[micro-app](https://github.com/micro-zoe/micro-app)代码里做了window.removeEventListener('unmount')的操作，由于没有沙箱，所以把子应用的这个事件监听也给卸载了。我这边暂时是通过自定义别的事件名去规避下这个bug。
> > <img alt="image" width="696" src="https://user-images.githubusercontent.com/22974194/175491343-3bd0c853-0c51-4001-9b90-8d4a8a7cdca3.png">
> > <img alt="image" width="479" src="https://user-images.githubusercontent.com/22974194/175491429-a8f43f03-4312-4136-a3e6-88728d927347.png">
> > <img alt="image" width="643" src="https://user-images.githubusercontent.com/22974194/175491467-5b992885-dac3-410b-b417-546ef3c8c1e7.png">
> 
> 谢谢 这样确实可行， 那请问怎么销毁呢

`    window.removeEventListener('unmount-bakingVue', null, true)` 这样不行

**Comment by zhoufanglu** [comment]
> 
fn 抽离出去就Ok了
`window.removeEventListener('unmount-bakingVue', unmountFn, false)`
