### ISSUE TITLE
window 被代理导致第三库报错

### ISSUE THREAD

**Issue by Lizhooh** [jd-opensource/micro-app#448]
## 问题描述
如题，使用了 leader-line （https://www.npmjs.com/package/leader-line）这个库，单独打开子应用没问题，集成到主应用后报错

**Comment by bailicangdu** [comment]
放到基座中引入呢

**Comment by Lizhooh** [comment]
这个库会判断当前的 window 是否是真实的 window 对象，感觉这类库都有问题

**Comment by 0o23** [comment]
> 放到基座中引入呢

可以如这个答复所说：
1. 基座(主应用)中 npm 下载库；
2. 在基座的 main.js 中 import 库并挂载到 window 上：
import * as xxx from 'xxx'
window.xxx = xxx
4. 然后子应用就可以直接获取库并使用：
const xxx = window.rawWindow.xxx

参考链接：https://github.com/umijs/qiankun/issues/1358
