### ISSUE TITLE
在基座应用跳转某个应用不同页面不生效

### ISSUE THREAD

**Issue by mursumomo** [jd-opensource/micro-app#45]

**Comment by mursumomo** [comment]
可以采用父应用下发事件通知子应用，子应用去主动触发路由跳转，但这种方式确实有点不太好

**Comment by bailicangdu** [comment]
参考这里：https://zeroing.jd.com/micro-app/docs.html#/zh-cn/route?id=%e5%ba%94%e7%94%a8%e4%b9%8b%e9%97%b4%e5%a6%82%e4%bd%95%e8%b7%b3%e8%bd%ac

**Comment by mursumomo** [comment]
再请教个问题，子应用路由变化后，需要联动父级，或者其他子应用的路由/侧栏变化。需要在子应用中全局监听route的变化，再
主动触发一次popstate事件
window.dispatchEvent(new PopStateEvent('popstate', { state: null }))
可能每个子应用都需要加个路由监听，可能稍微会有些繁琐。

**Comment by bailicangdu** [comment]
这里的PopStateEvent是用于触发框架路由如react-router, vue-router，如果是应用之间的信息交流可以使用数据通信的方式，跨子应用可以使用全局通信
