### ISSUE TITLE
angular11为主应用，angular8为子应用。 路由加载angular8 子应用有死循环，看看是哪出问题了？ 代码如下：https://github.com/emmi2008/micro-angular11-simple

### ISSUE THREAD

**Issue by emmi2008** [jd-opensource/micro-app#450]
## Describe the bug
> A clear and concise description of what the bug is.

## To Reproduce
1.
2.

## Screenshots
> If possible, please upload screenshots of the code, console, terminal, etc. to help us understand your problem.

## Reproduce repository
> Please provide a condensed code repository and upload it to your own github to help us reproduce your problem.

## Environment
- micro-app version:
- framework of base app & version:
- framework of sub app & version:
- Build tools & version:

**Comment by emmi2008** [comment]
![image](https://user-images.githubusercontent.com/24648210/175974908-0f25cd72-df0c-4815-9e7e-3e4266299c8b.png)


我把代码放到git 上了，https://github.com/emmi2008/micro-angular11-simple
主应用11，子应用8时就会出问题。

**Comment by bailicangdu** [comment]
下个版本会进行修复

**Comment by emmi2008** [comment]
> 下个版本会进行修复

看你们发了新版本0.8.8，这个问题是不是已经修复了？
