### ISSUE TITLE
切换到根节点不同的dom中再跳转进来  提示 name 名称冲突

### ISSUE THREAD

**Issue by hzfvictory** [jd-opensource/micro-app#452]
## 问题描述
> 页面只有一个子应用，子应用根据主应用的路由来判断显示隐藏，当子应用所处的兄弟节点和父节点没有变化时，切换页面子应用能正常显示隐藏，当子应用的父级节点被销毁，目前来看是子应用没有完全销毁（执行了unmount方法），导致再次进来的时候提示 name 名称冲突

## 环境信息
- micro-app版本：0.8.1
- 主应用前端框架&版本：vue2
- 子应用前端框架&版本：vue2
- 构建工具&版本：webpack4

**Comment by bailicangdu** [comment]
有设置keep-alive吗

**Comment by rawbin-** [comment]
看起来是SPA取资源取的不对导致的，比如渲染子应用资源的时候，请求发到了主应用，拿到了主应用的index.html，然后主应用又渲染了一遍子应用，然后就 app name conflict了

**Comment by hzfvictory** [comment]
> 有设置keep-alive吗

没有设置

**Comment by hzfvictory** [comment]
> 比如渲染子应用资源的时候，请求

看了下 没有这样的事情发生

**Comment by hzfvictory** [comment]
> Hello @hzfvictory. In order to facilitate location and troubleshooting, we need you to provide a realistic GitHub repository. 您好 @hzfvictory, 为了方便定位和排查问题，我们需要您提供一个重现实例，请提供一个尽可能精简的 GitHub 仓库地址。

这个比较复杂  我看看怎么抽出来吧
