### ISSUE TITLE
micro-app 已经攒了不少更新，请问何时发布下一个版本，有无里程碑？

### ISSUE THREAD

**Issue by dream2023** [jd-opensource/micro-app#453]
如题，目前很需要之前提交的两个 PR，但不知道 micro-app 的发布计划，有里程碑吗

**Comment by bailicangdu** [comment]
大版本还在开发中，如有需要可以在6.30发布一个小版本

**Comment by wangxiaolei5** [comment]
> 大版本还在开发中，如有需要可以在6.30发布一个小版本

特别需要~~~~

**Comment by dream2023** [comment]
> 大版本还在开发中，如有需要可以在6.30发布一个小版本

很需要~~~~~~~

**Comment by bailicangdu** [comment]
已发布小版本0.8.6
