### ISSUE TITLE
vite子应用配置太麻烦了

### ISSUE THREAD

**Issue by huzedong2015** [jd-opensource/micro-app#454]
## 背景
> 如果每个子项目这么配置很麻烦

## 期望的效果
官方推出一个vite的插件 发布到npm

**Comment by lysdyt** [comment]
vite 打包配置指定绝对路径，对产品发布局限太大，每次都需要指定服务器地址，不合理。

**Comment by bailicangdu** [comment]
目前适配vite代价是很大的，我们正在计划为vite打造一个独立的沙箱，以保证vite的接入方式和其他应用一样简单

**Comment by zxsoft** [comment]
> 目前适配vite代价是很大的，我们正在计划为vite打造一个独立的沙箱，以保证vite的接入方式和其他应用一样简单

现在已经12月份了，请问原计划9月份推出的vite沙箱环境进展如何了？
