### ISSUE TITLE
关于基座菜单跳转路径的问题

### ISSUE THREAD

**Issue by zhoufanglu** [jd-opensource/micro-app#455]
## 问题描述
> 基座菜单跳转地址格式应该是怎样的？
> 第一次进来是带hash的#号的，后面菜单跳转就不带了。

## 复现步骤
1. 基座 跳转 子项目的两个地址为 `main-vite/vue3-vite` 和`main-vite/vue3-vite/childRoute`
2. 子路由没有识别到
3. 主应用是`history`, 子应用是`hash`, 两个项目都是`vue3+ vite`
4. 代码
* `main-app` - 基座 注入
```js
// 微前端-microApp-注入
microApp.start({
  plugins: {
    modules: {
      // vue3 + vite的子应用
      'vue3-vite': [
        {
          loader(code) {
            if (process.env.NODE_ENV === 'development') {
              // 这里 /basename/ 需要和子应用vite.config.js中base的配置保持一致
              // eslint-disable-next-line no-param-reassign
              code = code.replace(/(from|import)(\s*['"])(\/vue3-vite\/)/g, all => {
                // 子应用启动地址
                return all.replace('/vue3-vite/', 'http://localhost:4001/vue3-vite/')
              })
            }
            return code
          }
        }
      ]
    }
  }
})
```
*  子应用`vue3-vite`  base配置
```js
  base: `${process.env.NODE_ENV === 'production' ? 'http://www.micro-zoe.com' : ''}/vue3-vite/`,

```

## 上传截图
![1mmIbP15um](https://user-images.githubusercontent.com/24451091/176342277-3dd773b9-1982-4a15-8012-de081a17ddab.gif)

## 复现仓库
[micro-app-study](https://github.com/zhoufanglu/micro-app-study)

## 环境信息
- micro-app版本：0.85
- 主应用前端框架&版本：vue3 vite
- 子应用前端框架&版本：vue3 vite
- 构建工具&版本：vue3 vite

**Comment by bailicangdu** [comment]
参考  https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/jump

**Comment by zhoufanglu** [comment]
> 参考 https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/jump

1、我在基座 菜单点击的时候注册了`microApp`事件
```js
import microApp from '@micro-zoe/micro-app'

function menuClick(path) {
  microApp.setData('app-child', {
      path
    })
}
```
2、 子应用监听， 监听不到 ,window对象下 没有 micro 属性
```js
// main.js
// window对象下 没有 micro 属性
```

**Comment by zhoufanglu** [comment]
> 参考 https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/jump

我看文档推荐的是， 我是vue-router4版本
![image](https://user-images.githubusercontent.com/24451091/176642125-3a303693-1bc6-4041-955a-60db46d1188f.png)
---
但是你demo中跳转用的却是`this.microAppData.pushState(appName, index, hash)`
实际用哪个比较好

**Comment by bailicangdu** [comment]
demo中包含子应用控制基座跳转，和基座控制子应用跳转，你贴的是子应用控制基座跳转的逻辑

**Comment by bailicangdu** [comment]
因为你是vite子应用，没有沙箱，通讯功能受限，处理方式只能和demo中的vite-vue3一样  https://github.com/micro-zoe/micro-app-demo/tree/master/child_apps/vite-vue3

**Comment by zhoufanglu** [comment]
> demo中包含子应用控制基座跳转，和基座控制子应用跳转，你贴的是子应用控制基座跳转的逻辑

我左侧菜单是放在主应用内的， 是主应用控制子应用跳转， 还是需要用到`方式二-数据通信控制跳转`是吗

**Comment by bailicangdu** [comment]
> > demo中包含子应用控制基座跳转，和基座控制子应用跳转，你贴的是子应用控制基座跳转的逻辑
> 
> 我左侧菜单是放在主应用内的， 是主应用控制子应用跳转， 还是需要用到`方式二-数据通信控制跳转`是吗

是的

**Comment by zhoufanglu** [comment]
> > > demo中包含子应用控制基座跳转，和基座控制子应用跳转，你贴的是子应用控制基座跳转的逻辑
> > 
> > 
> > 我左侧菜单是放在主应用内的， 是主应用控制子应用跳转， 还是需要用到`方式二-数据通信控制跳转`是吗
> 
> 是的

目前基本实现了，说说逻辑，不知道对不对
主应用点击菜单事件，传递事件给子应用， 子应用进行路由跳转
环境： 主应用（main-app）`vue3+vite`,  路由`history`， 子应用（child-app-1）: `vue3+vite`, 路由`hash`
* 主应用代码
```js
//  路由数组
const menuList = ref([])
menuList.value = [
  {
    name: '主-app',
    children: [
      {
        name: 'page-A',
        path: '/page-A',
        appForm: 'main'
      },
      {
        name: 'page-B',
        path: '/page-B',
        appForm: 'main'
      }
    ]
  },
  {
    name: '子-child-app-1',
    children: [
      {
        name: 'home',
        path: '/',
        appForm: 'child-app-1'
      },
      {
        name: 'childRoute',
        path: '/childRoute',
        appForm: 'child-app-1'
      }
    ]
  }
]
// 路由点击事件
/** ********************事件********************** */
const menuItemClick = item => {
  // 如果是主应用地址 就正常跳转
  if (item.appForm === 'main') {
    router.push(item.path)
  }
  //  如果是子应用 child-app-1
  else if (item.appForm === 'child-app-1') {
    router.push('child-app-1')
    // 向子应用传递路由 让子路由进行跳转
    microApp.setData('child-app-1', { path: item.path })
  }
}
```
* 子应用响应事件
```js
// 监听基座下发的数据变化
// console.log(6, window)
window.eventCenterForChildApp_1.addDataListener((data) => {
  // 当基座下发跳转指令时进行跳转
  if (data.path) {
    router.push(data.path)
  }
})
```
* 实现效果
![6E8Xllw7Ka](https://user-images.githubusercontent.com/24451091/177074612-19aaeb14-305b-462a-ba5a-802291109333.gif)

* 这边想询问一下这思路是否准确， 或者有无更好的方案
