### ISSUE TITLE
子应用动态加载script，无法成功加载

### ISSUE THREAD

**Issue by halaproliu** [jd-opensource/micro-app#456]
## 问题描述
> vue3子应用动态加载script，出现

## 复现步骤
1. 在vue3子应用动态插入script到head

## 上传截图
<img width="422" alt="image" src="https://user-images.githubusercontent.com/17921304/176578905-329161ea-a8cc-4ed7-b2cd-e3841b083d5f.png">

## 复现仓库
> [microApp](https://github.com/halaproliu/microApp)

## 环境信息
- micro-app版本：@micro-zoe/micro-app@0.8.5
- 主应用前端框架&版本：vue@2.6.11
- 子应用前端框架&版本：vue@3.0.0
- 构建工具&版本：子应用：webpack@5.73.0, 主应用：webpack@4.46.0

**Comment by jiaozhiye** [comment]
请问这个问题有解决方案了吗
