### ISSUE TITLE
使用style-components更改UI框架样式后，由于scope前缀问题导致css权重变化问题

### ISSUE THREAD

**Issue by mework** [jd-opensource/micro-app#457]
## 问题描述
> 问题的具体描述
当子应用使用style-components时，micro-app 排除了为其添加前缀的逻辑，导致渲染时样式权重发生变化，可以解释下为什么专门排除了 style-components 的样式处理吗

## micro-app 内部逻辑
![image](https://user-images.githubusercontent.com/35413629/176589640-c8f0dab5-5a36-40c9-ac16-bc2acc2d7dd8.png)

## 渲染效果
![image](https://user-images.githubusercontent.com/35413629/176590364-ba523993-50fd-418d-8e3c-a8cc360129c0.png)
![image](https://user-images.githubusercontent.com/35413629/176590520-b7ed79de-ea88-435d-8e8b-03dacd31ed77.png)

## 环境信息
- micro-app版本：0.8.5

**Comment by mework** [comment]
有处理与无处理本质上 css 权重值发生了变化，希望大佬不排除 style-components 的处理

**Comment by bailicangdu** [comment]
style-component直接操作cssRule注入样式，目前无法拦截和处理

**Comment by mework** [comment]
那这种场景下大佬有啥好的法子推荐下不？😂@bailicangdu

**Comment by bailicangdu** [comment]
加权重

**Comment by mework** [comment]
谢谢大佬
