### ISSUE TITLE
子应用锚点失效

### ISSUE THREAD

**Issue by huabuyu1993** [jd-opensource/micro-app#459]
子应用使用锚点不生效
disableSandbox 设置为true锚点可以生效但是菜单点击展开功能失效

**Comment by huabuyu1993** [comment]
主应用是vite项目 ，子应用是[Docusaurus](https://docusaurus.io/zh-CN/) 构建的静态站点

**Comment by huabuyu1993** [comment]
我这个是用的公司项目 不太方便

**Comment by bailicangdu** [comment]
你说的锚点是js模拟实现的锚点还是html原生锚点？

**Comment by huabuyu1993** [comment]
html 原生
