### ISSUE TITLE
同一个子应用的入口文件请求了两次

### ISSUE THREAD

**Issue by Yubiao-Li** [jd-opensource/micro-app#46]
![image](https://user-images.githubusercontent.com/39786286/129884710-e891b589-db63-4a79-9553-764fcdc2764c.png)
这里子应用的入口文件为什么被请求了两次呢

**Comment by bailicangdu** [comment]
第一次是preload

**Comment by Yubiao-Li** [comment]
@bailicangdu 这个preload我在文档并没有搜到对应的解释。我这里是在点击进去对应的路由的时候才加载的两次，如果是preload的话是不是应该在没点击路由的时候就开始加载呢

**Comment by bailicangdu** [comment]
这里指的是link标签的preload 
![image](https://user-images.githubusercontent.com/20297227/129898804-c59a008f-f987-496b-ba43-655ada9d889c.png)

**Comment by Yubiao-Li** [comment]
@bailicangdu 这是我做的一个demo，并没有发现有加载两次的问题
![image](https://user-images.githubusercontent.com/39786286/130000972-587d7857-179c-4e3b-b286-bae6ecca82c2.png)
![image](https://user-images.githubusercontent.com/39786286/130001006-e0852240-d92e-43a1-a4fe-b655f87a29e0.png)

**Comment by linlianqiang** [comment]
所以最后是什么原因呢
