### ISSUE TITLE
父子应用都是vite, 子应用图片地址404

### ISSUE THREAD

**Issue by zhoufanglu** [jd-opensource/micro-app#460]
## 问题描述
父子应用都是vite, 子应用图片地址404

## 复现步骤
* 子应用这样写404, 前缀渲染的是主应用的地址
```html
  <img alt="Vue logo" src="src/assets/logo-child.png" />
```
*  一定要这样写才行吗？这样改动太大了
```js
const logoPath = new URL('../src/assets/logo-child.png', import.meta.url).href
<img alt="Vue logo" :src="logoPath" />
```

**Comment by bailicangdu** [comment]
只要是绝对地址就行，其他方式也行

**Comment by zhoufanglu** [comment]
> 只要是绝对地址就行，其他方式也行

`  <img alt="Vue logo" src="src/assets/logo-child.png" /> 
`
这样写无效，前缀解析的还是主应用地址

**Comment by zhoufanglu** [comment]
> 

`src="@/assets/images/directory.png"` 这种地址都无法解析是吧

**Comment by skyLoveSnap** [comment]
解决了吗
vite的子应用 const logoPath = new URL('../src/assets/logo-child.png', import.meta.url).href
<img alt="Vue logo" :src="logoPath" />
 这样用 也是404

**Comment by zhoufanglu** [comment]
用绝对路径代替相对路径即可

**Comment by skyLoveSnap** [comment]
> 

@zhoufanglu   您好， 我这有写 是绝对路径 还是404，写的不对吗？

> 

<img width="1006" alt="image" src="https://user-images.githubusercontent.com/40157361/202990035-fb4873f7-f3d7-435a-8c3e-ba16ccd3b2fd.png">
