### ISSUE TITLE
nuxt子应用中，在asyncData或者fetch钩子函数中获取不到URL的query

### ISSUE THREAD

**Issue by Bisheng940924** [jd-opensource/micro-app#461]
## 问题描述
nuxt子应用中，在asyncData或者fetch钩子函数中获取不到URL的query

## 复现步骤
1.主应用和子应用均为Nuxt2应用
2.输入URL: http://localhost:3000/app-nuxtjs2/?type=123
3.asyncData函数中 query为 {}
4.mounted函数中可以正常获取到query
5.如果单独打开子应用页面如http://localhost:4003/app-nuxtjs2/?type=123 ，可以获取到query

## 上传截图
<img width="408" alt="image" src="https://user-images.githubusercontent.com/34200319/177051071-32328156-808d-4472-8419-60fffba7f6af.png">

## 复现仓库
使用示例代码仓库：https://github.com/micro-zoe/micro-app-demo 

## 环境信息
- micro-app版本：
- 主应用前端框架&版本：
- 子应用前端框架&版本：
- 构建工具&版本：

**Comment by bailicangdu** [comment]
参数要放在micro-app的url属性上

**Comment by bailicangdu** [comment]
下个版本会进行优化
