### ISSUE TITLE
关于子应用静态资源相对路径时，加载问题

### ISSUE THREAD

**Issue by MIRXU** [jd-opensource/micro-app#463]
引入了第三方插件，插件里面许多相对路径的静态资源，加载的时候他直接去基座找资源，，这个问题怎么解决？

**Comment by cnLiuMing** [comment]
不只是vite，迁移到webpack5也是这个问题，子应用elementui的font资源默认找主应用

**Comment by bailicangdu** [comment]
只能修改成绝对地址解决

**Comment by cnLiuMing** [comment]
父子同时用element plus解决，但子应用需要迁移

**Comment by MIRXU** [comment]
> 只能修改成绝对地址解决

我使用的是第三方插件cesium,它里面有很多相对路径，因此我把静态资源暂时放在基座里面，不知道这个解决方案有没有问题

**Comment by ShiChenCong** [comment]
是vite不能动态修改public_path 导致的吗
