### ISSUE TITLE
原生html,js

### ISSUE THREAD

**Issue by MIRXU** [jd-opensource/micro-app#464]
micro-app 可以加入原生的html作为子应用吗，有没有例子

**Comment by heavenwing** [comment]
同问。
如果可以嵌入html，那么类似Blazor WebAssembly这样的WebAssembly就可以无缝的和SPA类应用并存了。

**Comment by bailicangdu** [comment]
> 同问。 如果可以嵌入html，那么类似Blazor WebAssembly这样的WebAssembly就可以无缝的和SPA类应用并存了。

html项目最大的问题是路由，每次跳转都指向一个新的html，这无法被拦截，非spa项目在micro-app下都无法支持
