### ISSUE TITLE
基座vue2 子应用vite + vue3 第二次加载时报错

### ISSUE THREAD

**Issue by suKarXiao** [jd-opensource/micro-app#467]
由于 vite 作为子应用需要关闭沙箱，因此为了不影响主应用，非子应用的路由时，<micro-app />v-if置为false，首次进入子应用路由时一切正常，子应用可以正常加载出来，但是跳到其他非子应用路由 在跳回子应用路由时，出现以下报错，怀疑和vue3 全局实例被二次创建有关系？

![image](https://user-images.githubusercontent.com/52072212/177467388-f37360ee-f682-4ed1-944f-da70a22f5ecc.png)

**Comment by bailicangdu** [comment]
在子应用加一层if判断防止重复初始化

**Comment by suKarXiao** [comment]
> 在子应用加一层if判断防止重复初始化

感谢回复，做过这样的尝试，在子应用main中把createApp出来的app挂载到window上，判断如果window上有挂载就直接读取，但改成这样后，子应用直接就打不开了，报以下错误
![image](https://user-images.githubusercontent.com/52072212/177497392-fc3c4278-7bdb-4900-8546-26447f34a4fc.png)

**Comment by zhoufanglu** [comment]
第二次加载会出现这样的问题， 第一次不报错

```js
TypeError: Cannot destructure property 'Component' of 'undefined' as it is undefined.  
```
