### ISSUE TITLE
MicroApp中keep-alive的实现方式

### ISSUE THREAD

**Issue by isboyjc** [jd-opensource/micro-app#469]
请问下micro-app的keep-alive实现方式是用了display：none吗？还是其他的方案呢？

**Comment by bailicangdu** [comment]
效果类似，但不是display：none

**Comment by isboyjc** [comment]
也就是说，并没有移除真实DOM对吗

**Comment by isboyjc** [comment]
这边目前是在微前端架构下进行了的多页签缓存的实现
但现在有个三方页面是iframe嵌入的，需要做iframe内容的缓存
所以需要确认下MicroApp下的keep-alive模式进行系统切换时，是否移除了真实DOM还是说是隐藏了DOM

**Comment by bailicangdu** [comment]
dom从文档中删除了，缓存在内存中

**Comment by isboyjc** [comment]
好的，谢谢
