### ISSUE TITLE
[Feature request] 完善v1.0.0文档

### ISSUE THREAD

**Issue by bailicangdu** [jd-opensource/micro-app#470]
NOTE: 默认文档仍然为0.x，1.0正式发版后切换为默认文档

**Comment by suKarXiao** [comment]
请问 1.0 版本支持 vite子应用 沙箱吗? 兼容vite快哭了

**Comment by bailicangdu** [comment]
> 请问 1.0 版本支持 vite子应用 沙箱吗? 兼容vite快哭了

不支持，vite沙箱要等一段时间

**Comment by zhoufanglu** [comment]
> 请问 1.0 版本支持 vite子应用 沙箱吗? 兼容vite快哭了

我父子应用都是vite, 兼容的差不多了，还差个router.go(-1), 方便交流下么, 确实快哭了。。

**Comment by Qujh97** [comment]
> > 请问 1.0 版本支持 vite子应用 沙箱吗? 兼容vite快哭了
> 
> 我父子应用都是vite, 兼容的差不多了，还差个router.go(-1), 方便交流下么, 确实快哭了。。

哈哈哈，同最后卡在router问题，最终选择了vue-cli5

**Comment by zhoufanglu** [comment]
> 

你是父子应用都迁移到了vue-cli5了吗？

**Comment by zhoufanglu** [comment]
> > > 请问 1.0 版本支持 vite子应用 沙箱吗? 兼容vite快哭了
> > 
> > 
> > 我父子应用都是vite, 兼容的差不多了，还差个router.go(-1), 方便交流下么, 确实快哭了。。
> 
> 哈哈哈，同最后卡在router问题，最终选择了vue-cli5

你是父子应用都迁移到vue-cli5了吗？ 我目前vite是卡在回退有问题，其它差不多了

**Comment by Qujh97** [comment]
> > > > 请问 1.0 版本支持 vite子应用 沙箱吗? 兼容vite快哭了
> > > 
> > > 
> > > 我父子应用都是vite, 兼容的差不多了，还差个router.go(-1), 方便交流下么, 确实快哭了。。
> > 
> > 
> > 哈哈哈，同最后卡在router问题，最终选择了vue-cli5
> 
> 你是父子应用都迁移到vue-cli5了吗？ 我目前vite是卡在回退有问题，其它差不多了

项目开发前期就放弃vite了，一直用的vue-cli。个人能力有限，以及考虑日常开发体验，还是选择放弃了vite

**Comment by Qujh97** [comment]
> > > > 请问 1.0 版本支持 vite子应用 沙箱吗? 兼容vite快哭了
> > > 
> > > 
> > > 我父子应用都是vite, 兼容的差不多了，还差个router.go(-1), 方便交流下么, 确实快哭了。。
> > 
> > 
> > 哈哈哈，同最后卡在router问题，最终选择了vue-cli5
> 
> 你是父子应用都迁移到vue-cli5了吗？ 我目前vite是卡在回退有问题，其它差不多了

项目开发前期就放弃vite了，一直用的vue-cli。个人能力有限，以及考虑日常开发体验，还是选择放弃了vite

**Comment by Qujh97** [comment]
> > > > 请问 1.0 版本支持 vite子应用 沙箱吗? 兼容vite快哭了
> > > 
> > > 
> > > 我父子应用都是vite, 兼容的差不多了，还差个router.go(-1), 方便交流下么, 确实快哭了。。
> > 
> > 
> > 哈哈哈，同最后卡在router问题，最终选择了vue-cli5
> 
> 你是父子应用都迁移到vue-cli5了吗？ 我目前vite是卡在回退有问题，其它差不多了

父应用还是vite，子应用vue-cli

**Comment by bailicangdu** [comment]
> > 请问 1.0 版本支持 vite子应用 沙箱吗? 兼容vite快哭了
> 
> 我父子应用都是vite, 兼容的差不多了，还差个router.go(-1), 方便交流下么, 确实快哭了。。

router.go是全局的

**Comment by suKarXiao** [comment]
> 

已放弃micro-app方案，转为原始iframe了，因为嵌入页面不多，无沙箱兼容vite成本过高

**Comment by suKarXiao** [comment]
> > 请问 1.0 版本支持 vite子应用 沙箱吗? 兼容vite快哭了
> 
> 我父子应用都是vite, 兼容的差不多了，还差个router.go(-1), 方便交流下么, 确实快哭了。。

已放弃micro-app方案，转为原始iframe了，因为嵌入页面不多，无沙箱兼容vite成本过高

**Comment by LengYXin** [comment]
v1 有增加 当前子应用的全局常量扩展么？扩展 代理后的 Window 实际开发中 需要 这个配置 而不是通过全局 setGlobalData 和 data 去传递 只在子应用初始化的时候使用
我这边的业务场景是不通过路由初始化的时候去加载子路由的某个页面。把这个页面变成初始化的首页。
现在的实现方式是通过配置的url去分析路由匹配更改路由规则
大致是这样的

`
  const basePage = new URL(window.__MICRO_APP_PUBLIC_PATH__)
// 加载微应用组件
if (basePage.pathname) {
    const component = lodash.find(options.routes, ['name', lodash.trim(basePage.pathname, '/')])
    if (component) {
        // 替换现有首页
        lodash.remove(options.routes, ['name', 'index']);
        options.routes.unshift({ ...component, path: '/', name: 'index' })
    }
}

`

**Comment by bailicangdu** [comment]
@LengYXin 已经在规划中了

**Comment by zhoufanglu** [comment]
> 

iframe 体验太差，不够能写ppt

**Comment by lanmingle** [comment]
@bailicangdu angular 13 / 14 有做支持不？

**Comment by SuS7799** [comment]
@bailicangdu 请问大佬，vite沙箱有预计推出时间吗

**Comment by bailicangdu** [comment]
计划是9月 @SuS7799

**Comment by yooki0328** [comment]
> > 请问 1.0 版本支持 vite子应用 沙箱吗? 兼容vite快哭了
> 
> 我父子应用都是vite, 兼容的差不多了，还差个router.go(-1), 方便交流下么, 确实快哭了。。

--- 我的解决方案是禁用回退. 
```javascript
// FIXME: 微前端环境下浏览器回退问题
    router.afterEach(() => {
        history.pushState(null, '', document.URL);
    });
```
