### ISSUE TITLE
子应用主题色污染了基座应用

### ISSUE THREAD

**Issue by zhoufanglu** [jd-opensource/micro-app#471]
## 问题描述
> 子应用主题色污染了基座应用

## 复现步骤
![yXkg0ti9Bo](https://user-images.githubusercontent.com/24451091/177904810-8a856b04-689f-4e2f-90eb-1fed05e20431.gif)

## 环境信息
- micro-app版本：0.8
- 主应用前端框架&版本：vue 3.2
- 子应用前端框架&版本：vue 3.2
- 构建工具&版本：vite 2.9

**Comment by bailicangdu** [comment]
子应用是vite吗

**Comment by zhoufanglu** [comment]
> 

是的 都是vite

**Comment by zhoufanglu** [comment]
> 子应用是vite吗

是的 都是vite

**Comment by bailicangdu** [comment]
vite子应用的样式隔离和沙箱都失效，所以主、子应用的样式会相互影响，只能手动修改css解决

**Comment by zhoufanglu** [comment]
> vite子应用的样式隔离和沙箱都失效，所以主、子应用的样式会相互影响，只能手动修改css解决

有什么好的思路吗？我两个项目都全局引入了一些scss 文件， 这些都会影响？

**Comment by bailicangdu** [comment]
没办法

**Comment by bailicangdu** [comment]
沙箱关闭会导致很多问题，现在不建议接入vite，等到vite沙箱开发完成再接入吧

**Comment by zhoufanglu** [comment]
> 沙箱关闭会导致很多问题，现在不建议接入vite，等到vite沙箱开发完成再接入吧

作者有完成计划吗， 目前很多子应用用了vite,  目前测了 改变组件类名可以解决样式覆盖的问题。。

**Comment by bailicangdu** [comment]
在规划中
