### ISSUE TITLE
生产环境子应用第二次加载报错

### ISSUE THREAD

**Issue by zhoufanglu** [jd-opensource/micro-app#478]
## 问题描述
>生产环境子应用第二次加载报错， 本地开发环境没问题
`layout.e0815752.js:3 Uncaught (in promise) TypeError: Cannot destructure property 'Component' of 'undefined' as it is undefined.`

## 复现步骤
1. 子应用`vite.config.js` 插件
```js
    plugins: [
      vue(),
      // 自定义micro-app插件
      (function () {
        let basePath = "";
        return {
          name: "bdcp",
          apply: "build",
          configResolved(config) {
            basePath = `${config.base}${config.build.assetsDir}/`;
          },
          writeBundle(options, bundle) {
            for (const chunkName in bundle) {
              if (Object.prototype.hasOwnProperty.call(bundle, chunkName)) {
                const chunk = bundle[chunkName];
                if (chunk.fileName && chunk.fileName.endsWith(".js")) {
                  chunk.code = chunk.code.replace(
                    /(from|import\()(\s*['"])(\.\.?\/)/g,
                    (all, $1, $2, $3) => {
                      return all.replace($3, new URL($3, basePath));
                    }
                  );
                  const fullPath = join(options.dir, chunk.fileName);
                  writeFileSync(fullPath, chunk.code);
                }
              }
            }
          },
        };
      })(),
    ],

```

## 上传截图
![h16PK0AgJ8](https://user-images.githubusercontent.com/24451091/178389132-b990f154-3995-40ee-9645-c3d2caf04fcb.gif)

## 复现仓库
> 内部项目。。无法提供。。

## 环境信息
- micro-app版本： 0.8
- 主应用前端框架&版本：vue3+ vite
- 子应用前端框架&版本：vue3+ vite
- 构建工具&版本：vite2.9

**Comment by bailicangdu** [comment]
在子应用加一层判断，防止重复初始化

**Comment by zhoufanglu** [comment]
> 在子应用加一层判断，防止重复初始化

具体怎么判断呢？这样不行
```js
if(!app._container){
  app.mount('#bdcp') 
}
```
还有为什么本地开发是好的， 上了生产就出问题了

**Comment by zhoufanglu** [comment]
> > 在子应用加一层判断，防止重复初始化
> 
> 具体怎么判断呢？这样吗？ 还有为什么本地开发是好的， 上了生产就出问题了
> 
> ```js
> if(!app._container){
>   app.mount('#bdcp') 
> }
> ```



> > 在子应用加一层判断，防止重复初始化
> 
> 具体怎么判断呢？这样不行
> 
> ```js
> if(!app._container){
>   app.mount('#bdcp') 
> }
> ```
> 
> 还有为什么本地开发是好的， 上了生产就出问题了

![image](https://user-images.githubusercontent.com/24451091/178467790-f103fd5e-37b7-4fa8-97bb-c5fecc45bfb4.png)

**Comment by zhoufanglu** [comment]
> 在子应用加一层判断，防止重复初始化

找到为什么报这个错的问题了， 但是不知道怎么解决
我用这种方式渲染就会报上面的错， 本地开发不会出现 上生产就会
难道跟我`element-ui`组件有关系吗？
```js
<router-view v-slot="{ Component }">
        <transition name="el-fade-in" mode="out-in">
          <component :is="Component" />
        </transition>
      </router-view>
```

**Comment by bailicangdu** [comment]
动态组件？

**Comment by zhoufanglu** [comment]
> 动态组件？

只是这个写法
![image](https://user-images.githubusercontent.com/24451091/178739278-23ea2c73-9770-4219-91df-fb5b6eb911b2.png)

**Comment by zhoufanglu** [comment]
> 动态组件？

我又仔细测了下， 好像带路由嵌套的就不行，生产第二次进入到页面就不渲染了
`<router-view>`没有解析出来
![image](https://user-images.githubusercontent.com/24451091/178755342-29358e43-d506-4117-a793-1ff1c418d37f.png)

**Comment by zhoufanglu** [comment]
此问题关闭了， 重新开了个https://github.com/micro-zoe/micro-app/issues/487
