### ISSUE TITLE
基座应用和子应用部署在不同的域名下需要怎么处理

### ISSUE THREAD

**Issue by weedxu** [jd-opensource/micro-app#479]
将基座应用和子应用部署在不同的域名下，需要怎么去配置基座应用和子应用，按照文档步骤配置结果请求子应用的js文件路径会被补全成基座应用的域名，从而导致解析错误，请大大们指教一下。

**Comment by Qeney** [comment]
![image](https://user-images.githubusercontent.com/85222064/178646511-a784eff2-0eba-49e0-89d5-001430edd45f.png)
做个生产环境的映射表
生产模式下，config域名换成对应域名。这里默认取的基座域名

**Comment by weedxu** [comment]
> ![image](https://user-images.githubusercontent.com/85222064/178646511-a784eff2-0eba-49e0-89d5-001430edd45f.png) 做个生产环境的映射表 生产模式下，config域名换成对应域名。这里默认取的基座域名



> ![image](https://user-images.githubusercontent.com/85222064/178646511-a784eff2-0eba-49e0-89d5-001430edd45f.png) 做个生产环境的映射表 生产模式下，config域名换成对应域名。这里默认取的基座域名
