### ISSUE TITLE
这种情况一般是服务器配置问题

### ISSUE THREAD

**Issue by yichonglai** [jd-opensource/micro-app#480]
这种情况一般是服务器配置问题

_Originally posted by @bailicangdu in https://github.com/micro-zoe/micro-app/issues/110#issuecomment-940872336_

**Comment by yichonglai** [comment]
> 这种情况一般是服务器配置问题
> 
> _Originally posted by @bailicangdu in [#110 (comment)](https://github.com/micro-zoe/micro-app/issues/110#issuecomment-940872336)_

“这种情况一般是服务器配置问题” 能具体描述下吗？
这边也遇到了个类似的问题（现象：在启用缓存的情况下，单独访问过子应用（访问微前端环境前或后），再在微前端环境访问应用会遇到静态资源跨域问题；但在不启用缓存或启用缓存访问微前端之前（或之后）没单独访问过子应用的情况下能正常访问）。

**Comment by yichonglai** [comment]
> 这种情况一般是服务器配置问题
> 
> _Originally posted by @bailicangdu in [#110 (comment)](https://github.com/micro-zoe/micro-app/issues/110#issuecomment-940872336)_

“这种情况一般是服务器配置问题” 能具体描述下吗？
这边也遇到了个类似的问题（现象：在启用缓存的情况下，单独访问过子应用（访问微前端环境前或后），再在微前端环境访问应用会遇到静态资源跨域问题；但在不启用缓存或启用缓存访问微前端之前（或之后）没单独访问过子应用的情况下能正常访问）。

**Comment by bailicangdu** [comment]
把你的nginx配置发一下呢
