### ISSUE TITLE
vite子应用生产环境legacy模式不支持

### ISSUE THREAD

**Issue by Qeney** [jd-opensource/micro-app#481]
## 问题描述
> 问题的具体描述

## 复现步骤
子应用vite构建，使用@vitejs/plugin-legacy插件

legacy模式下，会生成script nomodule
但是会被micro-app给ignore掉，导致js资源加载异常

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。
![image](https://user-images.githubusercontent.com/85222064/178643475-deccb39a-a1b6-4d69-9d45-b54b0487af26.png)

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。

## 环境信息
- micro-app版本：0.8.7
- 主应用前端框架&版本：vite2.9
- 子应用前端框架&版本：vite2.9
- 构建工具&版本：vite2.9

**Comment by bailicangdu** [comment]
nomodule 和 module 只会有一个生效

**Comment by colgin** [comment]
> nomodule 和 module 只会有一个生效

话说 vite 应用是不是 只需要讲 输出的 html 全部用 nomodule，不要有 type=‘module’ 的这种引入，就可以被micro-app处理了？
