### ISSUE TITLE
vite生产环境模块路径引用异常，导致js执行多次

### ISSUE THREAD

**Issue by Qeney** [jd-opensource/micro-app#482]
## 问题描述
> 问题的具体描述

## 复现步骤
1. vue3全局使用store或者i18n，例如：app.use(store)
2.路由页面通过异步加载，例如：import('@/views/index.vue')

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。
![image](https://user-images.githubusercontent.com/85222064/178713350-c8cdb5ab-8051-447a-a1ff-c2cc890c5c2a.png)

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。

## 环境信息
- micro-app版本：0.8.7
- 主应用前端框架&版本：vite2.9
- 子应用前端框架&版本：vite2.9
- 构建工具&版本：vite2.9

**Comment by Qeney** [comment]
本地dev环境正常没问题。

由于处理后的js路径（blob:http//domain/xxxx.js）是运行时生成的，所以在微应用app构建时也无法动态改引用路径

不知道目前有什么其他好的办法？

或者考虑在rollup打包，利用代码分割，把这一部分内容打包进vendor.js内部

**Comment by Qeney** [comment]
目前先不用异步路由，临时解决生产环境。牺牲性能，全部页面打包到一个js

**Comment by bailicangdu** [comment]
感谢反馈，已经在安排解决了

**Comment by a1067111756** [comment]
感觉这个问题在vite上很容易复现。是因为在打造vite的沙箱没有修复这个问题？基于vite使用这个微前端框架，几乎让我快放弃，各种问题

**Comment by Valar103769** [comment]
> 感觉这个问题在vite上很容易复现。是因为在打造vite的沙箱没有修复这个问题？基于vite使用这个微前端框架，几乎让我快放弃，各种问题

我的vite主应用, 直接跑不起来😭
