### ISSUE TITLE
基座和子应用共用UI组件这个功能怎么实现？

### ISSUE THREAD

**Issue by X-J-C** [jd-opensource/micro-app#483]
基座和子应用都是用的element-ui，现在想要只有基座下载包，子应用不需要下载。研究了文档的静态资源和插件系统都不成功，请问还有什么其它解决办法吗

**Comment by Lzy49** [comment]
两个方案：
1. 将element-ui单独打包，然后通过浏览器缓存做
2.只在基座引入 ，在子应用通过可以向上访问window的特性来获取

**Comment by frontend-cherry** [comment]
我也看了官网的插件系统和资源共享，没研究明白怎么将基座封装的组件共享给各个子应用

**Comment by elarbor** [comment]
我也看了官网的[插件系统](https://zeroing.jd.com/micro-app/docs.html#/zh-cn/plugins)和[资源共享](https://zeroing.jd.com/micro-app/docs.html#/zh-cn/static-source?id=%e8%b5%84%e6%ba%90%e5%85%b1%e4%ba%ab)，没研究明白怎么将基座封装的组件共享给各个子应用

**Comment by VenomQAQ** [comment]
请问解决了吗
