### ISSUE TITLE
子应用里type="systemjs-module"的script标签的src地址没有自动补全

### ISSUE THREAD

**Issue by chengzhuo5** [jd-opensource/micro-app#484]
## 问题描述
> 子应用里type="systemjs-module"的script标签的src地址没有自动补全，导致基座应用加载时找不到子应用的script路径

## 复现步骤
1.创建一个基于SystemJS的子应用
2.基座应用接入子应用

## 上传截图
子应用
![image](https://user-images.githubusercontent.com/42364602/178977214-2d30aa17-dcb7-44bb-97c2-855a751c28ed.png)
基座应用
![image](https://user-images.githubusercontent.com/42364602/178977324-b6d8c726-8a32-4e88-b137-d92e34d71960.png)

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。

## 环境信息
- micro-app版本：0.8.7
- 主应用前端框架&版本：
- 子应用前端框架&版本：
- 构建工具&版本：

**Comment by chengzhuo5** [comment]
https://github.com/micro-zoe/micro-app/pull/485

**Comment by lianglei777** [comment]
分享一个场景问题：
我的项目 v0.8.7 升级到 v0.8.8 后，micr app 会出错，
v0.8.8 的修改
![Screenshot2023_04_21_183254](https://user-images.githubusercontent.com/18453568/233614847-a2ac3f4a-bbeb-4181-ad8f-899ee8a4c6a9.jpg)

项目集成的子应用利用 systemjs 做了一些打包处理，script标签标签不需要特殊处理，处理了反而出问题的。
为了避免这个问题，给script 加了 ignore 属性。
 
<img width="382" alt="Screen Shot 2023-04-21 at 18 36 43" src="https://user-images.githubusercontent.com/18453568/233615597-b0521119-021b-447b-b99e-2a8e24d1cfc6.png">

建议这部分的设计可以做的灵活一些。
