### ISSUE TITLE
生产路由嵌套第二次访问不识别， element-pls内容失效

### ISSUE THREAD

**Issue by zhoufanglu** [jd-opensource/micro-app#487]
## 问题描述
> 生产环境路由嵌套第二次访问不识别， element-pls内容失效
> 本地开发是完全没有问题的

## 复现步骤
[生产演示地址](http://110.40.136.102:3307/main-app/page-A)
第一次进入子应用是Ok的，切换到主应用，再次进入就不行了, `router-view`没有解析出来。

## 上传截图
![1AQ3HxBPss](https://user-images.githubusercontent.com/24451091/179135828-a1db6560-d9cc-44c0-be2c-11fa8c57e41a.gif)

## 复现仓库
> [github demo](https://github.com/zhoufanglu/micro-app-study-2/tree/dev-ep)

## 环境信息
- micro-app版本：0.87
- 主应用前端框架&版本：vue3+ vite2.9
- 子应用前端框架&版本：vue3+ vite2.9
- 构建工具&版本：vue3+ vite2.9

**Comment by miaozikeji** [comment]
更新日志是不是有点问题

**Comment by zhoufanglu** [comment]
> 更新日志是不是有点问题

什么意思？

**Comment by caisanli** [comment]
看样子是框架的问题
它把入口文件的内容提了出来 转成了blob地址 作为实际的入口文件地址
然后这个入口文件又会 export 一些函数给其它文件用
但是其它文件from的地址是入口文件的真实地址
这样就会导致引用出错
...
不知道是不是这个问题

**Comment by ohion** [comment]
我也遇到了这个问题，第一次加载了子应用，跳转到主应用其他的路由，再回来，子应用就加载不出来了，刷新一下页面才可以

**Comment by ulnae** [comment]
我碰到的问题跟这个类似但又不太一样
我的基座跟子应用采用的也都是vite+vue3
然后我关闭了沙箱
首次进入子应用没有任何问题
然后切换其他子应用后再回来的话
子应用直接无了
我把报错信息放了出来
vue那边有人提过这个问题
![image](https://user-images.githubusercontent.com/68459780/187699304-d553bb68-fe19-47dd-bff6-caa5ff5b8c8d.png)
兄弟，你这个部署没有碰到这个问题吗？
还有个就是切换子应用生成很多blob
![image](https://user-images.githubusercontent.com/68459780/187699809-70698ce4-5a34-4679-9738-12424ea2f744.png)
这个不知道是不是我配置的问题

[demo地址](http://47.93.229.170)

**Comment by w7team** [comment]
vue的嵌套路由遇到了类似的问题，来顶一下。
文档：https://router.vuejs.org/zh/guide/essentials/nested-routes.html
![G0Y)I 90518WPZ4W2Y`{R$6](https://user-images.githubusercontent.com/74588507/196585880-d7597a97-c576-4ae1-b5fd-f756ddf33098.jpg)

**Comment by lx18658730623** [comment]
这个问题有解决吗

**Comment by jiatong859** [comment]
> 

请问问题解决了么
