### ISSUE TITLE
基座中可以弹窗形式加载子应用的某一个页面吗

### ISSUE THREAD

**Issue by baosuyaole1** [jd-opensource/micro-app#489]
## 背景
> 描述您希望改进的问题。

**Comment by bailicangdu** [comment]
可以

**Comment by baosuyaole1** [comment]
> 可以
怎么弄啊 有demo吗  我用micro-app标签加载进来会影响地址栏路由
基座是vue-router4 +createWebHistory模式
子应用有viet 也有webpack的 也都是路由4

**Comment by bailicangdu** [comment]
使用 [1.0.0-alpha.2](https://www.npmjs.com/package/@micro-zoe/micro-app/v/1.0.0-alpha.2) 版本

**Comment by baosuyaole1** [comment]
> 使用 [1.0.0-alpha.2](https://www.npmjs.com/package/@micro-zoe/micro-app/v/1.0.0-alpha.2) 版本
感谢  我升级试试
