### ISSUE TITLE
microAPP子应用动态加载js资源并顺序执行

### ISSUE THREAD

**Issue by limbodan** [jd-opensource/micro-app#491]
## 我在配置子应用的时候，需要在head里动态写入<script><css>资源，
例如：<script src="a.js"/><script src="d.js"/>，在a.js里通过append script标签动态加载b.js,c.js，正常加载执行顺序是，a.js, b.js,c.js,d.js；但是挂在microAPP下作为 子应用后，加载js的顺序变成了，a.js, d.js, b.js,c.js。请问我要怎样才能让js顺序加载并执行

**Comment by bailicangdu** [comment]
子应用单独运行时执行的顺序是什么

**Comment by hdy1023** [comment]
正常情况下也是adbc 吧  append script 代码执行是异步的

**Comment by zyf540860996** [comment]
顺序问题有得到解决么？当子应用嵌入 资源加载顺序存在，导致依赖性的js文件报错
