### ISSUE TITLE
加载性能优化

### ISSUE THREAD

**Issue by dream2023** [jd-opensource/micro-app#498]
## 背景

![222](https://user-images.githubusercontent.com/19297757/180149494-7e199af5-07ed-4629-8143-83c7a5ab2839.png)

如图所示，稍微大一点的子应用，其加载的过程就会很长，这段时间，页面会假死，操作无响应。

## 期望的效果

能够借鉴 React 的理念，将大任务分割成一个一个的小任务进行执行，解决整体初始化时卡顿的问题

**Comment by bailicangdu** [comment]
看你的截图，应该是样式隔离的代码，你的css有多大？

**Comment by bailicangdu** [comment]
思路很好，对于子应用的css和js的处理，确实可以拆分成小单元执行

**Comment by dream2023** [comment]
> 看你的截图，应该是样式隔离的代码，你的css有多大？

我们这有 30 几个子应用，有 JS 执行时间较长的也有 CSS 执行时间较长的

![1-4](https://user-images.githubusercontent.com/19297757/180157511-334c7eb2-e62b-425b-a554-66a511793f7a.png)
![1-3](https://user-images.githubusercontent.com/19297757/180157534-08ee5264-d2b9-4d70-a527-260d32a70898.png)
![1-2](https://user-images.githubusercontent.com/19297757/180157552-7290a09c-275a-459f-aba8-de0846562ada.png)

**Comment by dream2023** [comment]
> 思路很好，对于子应用的css和js的处理，确实可以拆分成小单元执行

简单写了一下代码，首先将 一次性执行所有 JS 链接改为分开分开执行，然后再将 `bindScope` 和 `runCode2InlineScript / runCode2Function` 分开。

效果整体还行，但是由于单个 JS 本身执行时间长，导致还是会有卡顿的问题，确实没发解决。

![优化前](https://user-images.githubusercontent.com/19297757/181698771-eba0a1b4-2ac6-40ec-9dad-c3256b4a7869.png)

![优化后](https://user-images.githubusercontent.com/19297757/181699271-abaa7a64-8e4c-43c1-bfa6-3d1e9e2b8fd1.png)
