### ISSUE TITLE
关于vite3拿不到注入的window.microApp对象

### ISSUE THREAD

**Issue by zhanghan-cdns** [jd-opensource/micro-app#499]
## 问题描述
> 问题的具体描述
主应用和子应用都是vite3+vue3,跳转能正常跳转，但是数据通信方面好像有问题，子应用在window对象中没有发现环境变量和micro-app注入的microApp对象。
## 复现步骤
1.
2.

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。

## 环境信息
- micro-app版本：
- 主应用前端框架&版本：
- 子应用前端框架&版本：
- 构建工具&版本：

**Comment by bailicangdu** [comment]
参考 https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/data?id=%e5%85%b3%e9%97%ad%e6%b2%99%e7%ae%b1%e5%90%8e%e7%9a%84%e9%80%9a%e4%bf%a1%e6%96%b9%e5%bc%8f

**Comment by zhushihao110** [comment]
- micro-app版本："@micro-zoe/micro-app": "latest",
- 主应用前端框架&版本："vue": "^3.0.5",
- 子应用前端框架&版本："vue": "^3.0.5",
- 构建工具&版本："vite": "^2.6.13",

子应用无法获取microApp对象
![image](https://user-images.githubusercontent.com/26850475/182803637-2738e4be-e449-4e13-8f30-4f480baa21cb.png)

**Comment by zhushihao110** [comment]
https://zeroing.jd.com/docs.html#/zh-cn/jump?id=%e6%96%b9%e5%bc%8f%e4%b8%89%e3%80%81%e4%bc%a0%e9%80%92%e8%b7%af%e7%94%b1%e5%ae%9e%e4%be%8b%e6%96%b9%e6%b3%95

**Comment by bailicangdu** [comment]
@zhushihao110 vite关闭了沙箱，拿不到这些数据，vite应用暂时不要接入，后续会更新vite沙箱

**Comment by gaofeng222** [comment]
> @zhushihao110 vite关闭了沙箱，拿不到这些数据，vite应用暂时不要接入，后续会更新vite沙箱

啥时候更新呀，我们现在要做前端的微前端化，用的vite构建的项目

**Comment by shuyuTech** [comment]
> > @zhushihao110 vite关闭了沙箱，拿不到这些数据，vite应用暂时不要接入，后续会更新vite沙箱
> 
> 啥时候更新呀，我们现在要做前端的微前端化，用的vite构建的项目

main 通过消息通信将关键信息发送过去，child中接收，自己维护一个全局变量，我们就是这么解决的
