### ISSUE TITLE
feat: 服务端渲染接入 micro-app

### ISSUE THREAD

**Issue by zhangyuang** [jd-opensource/micro-app#50]
我们公司这边的服务端选渲染框架 https://github.com/ykfe/ssr 目前正在打算整合微前端方案。
调研了一下qiankun和micro-app。看起来micro-app的侵入性是比较小的。但是不确定成熟度如何。
接入过程中出现了一些问题，初步推测是micro-app自身的问题。
不知道是否有精力能够加个微信单独沟通调试下。

**Comment by bailicangdu** [comment]
好的，您的微信可以发我吗，邮箱：1264889788@qq.com，或者在gitter上私聊我 https://gitter.im/bailicangdu

**Comment by zhangyuang** [comment]
gitter 效率略低，已经加你这个qq了
