### ISSUE TITLE
0.8.8 这个版本的更新内容是什么? 

### ISSUE THREAD

**Issue by xiangxinji** [jd-opensource/micro-app#500]
文档上的更新日志好像没有提到这个版本

**Comment by bailicangdu** [comment]
<img width="1246" alt="image" src="https://user-images.githubusercontent.com/20297227/180159879-72a352db-3f1d-4a26-8048-a1a6327e887e.png">

**Comment by xiangxinji** [comment]
哦哦, 好的 那上次说的那个 vue-router4.0 导致 window.history 混乱的问题有在排期里面吗 ? 这个问题遗留挺久了.

**Comment by bailicangdu** [comment]
问题在[v1.0.0-alpha.1](https://github.com/micro-zoe/micro-app/releases/tag/v1.0.0-alpha.1)已修复，但还在测试阶段

**Comment by xiangxinji** [comment]
好的, 非常感谢

**Comment by Qingggggggg** [comment]
> 问题在[v1.0.0-alpha.1](https://github.com/micro-zoe/micro-app/releases/tag/v1.0.0-alpha.1)已修复，但还在测试阶段

要开启什么配置吗？目前更新上去还是有问题

**Comment by bailicangdu** [comment]
> > 问题在[v1.0.0-alpha.1](https://github.com/micro-zoe/micro-app/releases/tag/v1.0.0-alpha.1)已修复，但还在测试阶段
> 
> 要开启什么配置吗？目前更新上去还是有问题

有什么问题，能提供一个demo吗

**Comment by Qingggggggg** [comment]
> 有什么问题，能提供一个demo吗

有点不太好复现

大致流程是这样：
> 都是vite/vue3

主应用：/
子应用1: a
子应用2: b
1. 从 /  ->  /a/apage 正常
2. 从 /a/apage -> /b/bpage 不正常（路由现在为/a/b/bpage）

另外 现在进入子应用路由都会被拼接 `?子应用名=/` 的query

**Comment by bailicangdu** [comment]
vite没办法

**Comment by Qingggggggg** [comment]
> vite没办法

是什么原因限制了，我可以参与开发。

**Comment by bailicangdu** [comment]
vite沙箱关闭了，vue3下路由冲突，只能等到vite沙箱支持后才能彻底解决

**Comment by Qingggggggg** [comment]
> vite沙箱关闭了，vue3下路由冲突，只能等到vite沙箱支持后才能彻底解决

我不设置 `disable-sandbox` 没有遇到错误

**Comment by bailicangdu** [comment]
vite子应用会自动关闭沙箱

**Comment by Qingggggggg** [comment]
> vite子应用会自动关闭沙箱

感谢回复！

看了下源码，是因为 module script 无法使用`with` 导致无法支持 sandbox 的吗

目前有什么方案吗？

---

我自己尝试了下改造了下 code 可以运行，但无法把 `window` 替换为 `proxyWindow`。想到的另一个方案是使用 `vite` 插件替换所有 `window` 为 `proxyWindow`，不知道这种方案是否可行。

**Comment by bailicangdu** [comment]
这个问题比较麻烦，不是vite的问题，而是esm下禁止使用with，而micro-app的沙箱就是强依赖于proxy和with

**Comment by bailicangdu** [comment]
这让我们不得不不寻找其他的沙箱方案

**Comment by Qingggggggg** [comment]
> 这个问题比较麻烦，不是vite的问题，而是esm下禁止使用with，而micro-app的沙箱就是强依赖于proxy和with

理解，proxy应该没问题吧？

> 这让我们不得不不寻找其他的沙箱方案

现在有初步的方案了吗？想参与开发尽早用上😊

**Comment by bailicangdu** [comment]
你有什么建议？

**Comment by Qingggggggg** [comment]
> 你有什么建议？

web worker 执行代码，dom操作 postmessage 让主线程执行。不知道这种方案是否可行。
