### ISSUE TITLE
基座一个页面中集成多个子应用页面

### ISSUE THREAD

**Issue by Chonglin-X** [jd-opensource/micro-app#504]
根据文档提示添加多个micro-app标签保证name不重复，并设置一个baseRoute路由
页面显示结果：集成纯前端页面没有问题，如果包含调用后端接口则报404，地址可以单独访问，集成后不能访问
![image](https://user-images.githubusercontent.com/84110421/180692191-ef639aa3-afe0-4e8f-aebd-c765cbe9d529.png)

望大佬指导

代码配置如下
`    <div>
      <micro-app  name='alert-test2' url='http://192.168.1.6:80/public/information' ></micro-app>
    </div>
    <div>
    <micro-app  class="alert" name='alert-test' url='http://192.168.1.6:80/public/alert' baseRoute="/public/alertxxx" ></micro-app>
    </div>
`

**Comment by bailicangdu** [comment]
路由没有配置好，推荐使用版本 [1.0.0-alpha.3](https://www.npmjs.com/package/@micro-zoe/micro-app/v/1.0.0-alpha.3)

**Comment by Chonglin-X** [comment]
> 路由没有配置好，推荐使用版本 [1.0.0-alpha.3](https://www.npmjs.com/package/@micro-zoe/micro-app/v/1.0.0-alpha.3)

官网最新版本0.8.2，这个1.0.0是什么版本，要用1.0.0这个版本才可以吗

**Comment by bailicangdu** [comment]
0.x版本没有路由隔离，你需要自己设置好路由配置规则，否则容易出现404问题

**Comment by Chonglin-X** [comment]
> 0.x版本没有路由隔离，你需要自己设置好路由配置规则，否则容易出现404问题
好的，我切换版本试一下

**Comment by Chonglin-X** [comment]
> 0.x版本没有路由隔离，你需要自己设置好路由配置规则，否则容易出现404问题

切换版本会把我所有路由的请求都指向microapp里所配置的IP，正常应该只是被调用的页面指向所配置的IP其他不变
![image](https://user-images.githubusercontent.com/84110421/180699400-6b568439-73ec-4eb6-9abd-7c10902213b6.png)

**Comment by Ec2-slj** [comment]
url配置得应该是指向子应用的index.html，可以通过传值的方式把路由传给子应用，子应用通过传过来的进行指定页面渲染，但是要实现一个主应用加载多个子应用对应得组件内容，怎么禁止micro-app这个组件监听路由进行匹配子应用得路由呢，有了解得一块讨论下呗

**Comment by Chonglin-X** [comment]
> url配置得应该是指向子应用的index.html，可以通过传值的方式把路由传给子应用，子应用通过传过来的进行指定页面渲染，但是要实现一个主应用加载多个子应用对应得组件内容，怎么禁止micro-app这个组件监听路由进行匹配子应用得路由呢，有了解得一块讨论下呗
是的，micro-app集成的页面会根据路由进行加载，如果一个页面集成多个子应用，会显示相同的页面。作者说可以用1.0版本试试，我改成1.0版本后原来集成的单个页面也不能用了，所以又退回到0.8版本，暂时集成多个页面使用的是micro-app和iframe配合集成的，这样写比较笨重，最好还是通过micro-app一次性集成多个页面
