### ISSUE TITLE
子应用接入高德地图的问题

### ISSUE THREAD

**Issue by BrignLau** [jd-opensource/micro-app#505]
## 问题描述
> 子应用接入高德地图后，初次渲染正常，卸载APP后再次进入无法渲染。

## 复现步骤
1.点击child-vue2/home，此时地图正常显示
2.点击首页后再次点击child-vue2/home，地图无法现在

## 上传截图
![image](https://user-images.githubusercontent.com/84120919/180737469-06d38779-ba6c-483b-9977-eb010a070d37.png)

## 复现仓库
https://github.com/BrignLau/micro-demo-amap

## 环境信息
用的就是官方的demo，在vue2子应用中集成了高德地图

**Comment by bailicangdu** [comment]
问题会在后续版本中修复

**Comment by bailicangdu** [comment]
临时解决方案，切换到默认模式
![image](https://user-images.githubusercontent.com/20297227/180947488-f113e069-86da-4244-9a1c-6939587297bb.png)

**Comment by BrignLau** [comment]
好的，试了一下暂时可以解决问题，后续再关注版本更新。thx。

**Comment by dongoa** [comment]
这个问题已经修复了吗，有iframe嵌入的地图和微应用地图，先打开iframe嵌入的地图，再打开微应用地图还是会报地图api加载错误。"@micro-zoe/micro-app": "^0.8.8

**Comment by dongoa** [comment]
这个问题已经修复了吗，有iframe嵌入的地图和微应用地图，先打开iframe嵌入的地图，再打开微应用地图还是会报地图api加载错误。"@micro-zoe/micro-app": "^0.8.8
