### ISSUE TITLE
子应用无法获取到自适应高度  子应用子使用高度为0

### ISSUE THREAD

**Issue by dongoa** [jd-opensource/micro-app#506]
## 问题描述
> 问题的具体描述

## 复现步骤
1.
2.

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。

## 环境信息
- micro-app版本：
- 主应用前端框架&版本：
- 子应用前端框架&版本：
- 构建工具&版本：

**Comment by bailicangdu** [comment]
micro-app 和 micro-app-body默认由子应用撑开高度，如果需要占高100%需要手动设置

**Comment by dongoa** [comment]
> micro-app 和 micro-app-body默认由子应用撑开高度，如果需要占高100%需要手动设置

求教怎么手动设置，在基座设置.micro-app, .micro-app-body height:100%!important无法生效。
感谢🙏

另：复现了一个加载iframe的地图api后，切换到微应用地图api加载报错 高德api2.0

**Comment by bailicangdu** [comment]
micro-app, micro-app-body {height:100%;}

**Comment by dongoa** [comment]
忘了是webcomponents nice 高德那个是我自己的bug 👍

**Comment by kongbg** [comment]
> micro-app, micro-app-body {height:100%;}

子应用布局用了绝对定位，导致主应用micro-app, micro-app-body高度为0，
设置micro-app, micro-app-body {height:100%;}无效
设置micro-app, micro-app-body {height:vh;}生效，也可以用clac()减头部高度
