### ISSUE TITLE
昨日 dev 提交的代码导致测试用例报错 

### ISSUE THREAD

**Issue by dream2023** [jd-opensource/micro-app#508]
问题：

昨日 @bailicangdu 大佬提交的代码，并没有跑测试用例，导致报错很多，具体如下：

![微信截图_20220729211307](https://user-images.githubusercontent.com/19297757/181768097-4aee0180-f408-4a5f-9b0d-1e5b68bb9f8e.png)

解决方案：
1、希望能临时修复这个问题
2、是否应该在 DEV 分支、PR 提交等场景，触发 GITHUB CI 跑测试用例

**Comment by bailicangdu** [comment]
1.0的测试用例要重构，目前优先实现功能

**Comment by dream2023** [comment]
> 1.0的测试用例要重构，目前优先实现功能

好的，不过后面还是建议把 PR 和 DEV 的 CI 搞上，还有最后一个参数，必填，不能放到后面。
