### ISSUE TITLE
文档常见问题之子应用请求接口报错提供意见

### ISSUE THREAD

**Issue by tanqin** [jd-opensource/micro-app#510]
大佬您好，我看到到文档常见问题的第 14 项提到子应用请求接口报错的问题，也在 issues 里寻找了解决方案，大佬们给的解决方案与文档一致，就是写死子应用的域名，但是我觉得此方案略显不妥，于是研究了一番。
我注意到在子应用中 window.__MICRO_APP_PUBLIC_PATH__ 是可以获取到子应用域名的，window.origin 在子应用单独运行时可以获取到子应用域名，在微前端环境下可以获取到基座域名，于是我将子应用的请求进行了以下改进：
**改进前：**
```js
// 请求 docx 资源
 fetch('/files/resource.docx').then((res) => {
        res.blob().then((blob) => {
          // get blob
        })
      })
```
**改进后：**
```js
/**
    子应用单独运行时：此时 window.__MICRO_APP_PUBLIC_PATH__ 为 undefined，window.origin 为子应用域名，可以正确请求到资源
    微前端环境运行时：此时 window.__MICRO_APP_PUBLIC_PATH__ 为 子应用域名，window.origin 为基座域名，也可以正确请求到资源
**/
  fetch((window.__MICRO_APP_PUBLIC_PATH__ || window.origin) + '/files/resource.docx').then((res) => {
        res.blob().then((blob) => {
          // get blob
        })
```
我不确定我的建议算不算是该问题的另一种解决方案，它确实解决了我当下遇到的问题，所以打算跟大佬探讨一下。

**Comment by bailicangdu** [comment]
在1.0版本中对这个问题进行了优化，默认使用子应用域名补全 https://micro-zoe.com/docs/1.x/#/zh-cn/configure?id=disable-patch-request

**Comment by tanqin** [comment]
> 在1.0版本中对这个问题进行了优化，默认使用子应用域名补全 https://micro-zoe.com/docs/1.x/#/zh-cn/configure?id=disable-patch-request

原来如此，谢谢大佬！！

**Comment by tanqin** [comment]
官网对该问题已有解决方案
