### ISSUE TITLE
【keepAlice 标签缓存问题】子应用独立运行时页签可缓存，在微前端环境缓存不生效。

### ISSUE THREAD

**Issue by LlanHao** [jd-opensource/micro-app#511]
问题：

子应用独立运行时页签可缓存，在微前端环境缓存不生效。
<img width="615" alt="image" src="https://user-images.githubusercontent.com/56375728/182138632-be554824-be31-46ef-8c42-5d3c0f5340b9.png">

<img width="789" alt="image" src="https://user-images.githubusercontent.com/56375728/182138521-a9a116a6-7077-4883-bc8d-95a3da7292b5.png">

<img width="571" alt="image" src="https://user-images.githubusercontent.com/56375728/182138991-b71e58f5-e1ac-413a-9da6-2b8a8eb3542c.png">

期望：
子应用页签切换保留页面输入状态

**Comment by bailicangdu** [comment]
参考 https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/keep-alive

**Comment by LlanHao** [comment]
> 参考https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/keep-alive

micro-app 标签加上 keep-alive 属性 开启应用级缓存后无法实现缓存效果。
<img width="969" alt="WechatIMG3207" src="https://user-images.githubusercontent.com/56375728/182331190-54b4f10e-3e8d-4bef-adfe-5dba12b4b1f9.png">
具体想实现的效果是，在子应用里，页面 A，页面B 切换时，通过 vue keep-alive 的标签实现缓存。

**Comment by LlanHao** [comment]
> 参考https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/keep-alive

micro-app 标签加上 keep-alive 属性 开启应用级缓存后无法实现缓存效果
<img width="969" alt="WechatIMG3207" src="https://user-images.githubusercontent.com/56375728/182332096-d96e4571-2af2-498a-9f50-25637e7881dd.png">
具体想实现的效果是，在子应用里，页面 A，页面B 切换时，通过 vue keep-alive 的标签实现缓存。

**Comment by bailicangdu** [comment]
你是通过修改url地址卸载子应用的吗

**Comment by LlanHao** [comment]
> 你是通过修改url地址卸载子应用的吗

不是。跳转使用的这个方式
子应用：：
<img width="703" alt="WechatIMG3208" src="https://user-images.githubusercontent.com/56375728/182335002-25339566-514a-4922-ae0c-f9b34ee92b4d.png">

主应用：：
<img width="855" alt="WechatIMG3209" src="https://user-images.githubusercontent.com/56375728/182335255-d6fd96e2-3ed7-47a4-b0b8-036d38d9d736.png">

**Comment by bailicangdu** [comment]
<img width="480" alt="image" src="https://user-images.githubusercontent.com/20297227/182335996-651641e1-d004-4310-96a1-a8e462f705eb.png">
name不变，url变化时，会彻底删除旧项目包括keep-alive状态，因为name和url是唯一匹配的

**Comment by LlanHao** [comment]
> <img alt="image" width="480" src="https://user-images.githubusercontent.com/20297227/182335996-651641e1-d004-4310-96a1-a8e462f705eb.png">
> 
> name不变，url变化时，会彻底删除旧项目包括keep-alive状态，因为name和url是唯一匹配的

没懂。具体怎么操作，大神能帮忙再指导下吗？能在线指导不

**Comment by bailicangdu** [comment]
```html
<micro-app 
  :name='url变化时设置新的值'
  :url='url'
>
```

**Comment by LlanHao** [comment]
> ```
> <micro-app 
>   :name='url变化时设置新的值'
>   :url='url'
> >
> ```
试了，子应用在切换页面的时候 micro-app标签绑定的 URL 并没有发生变化。
<img width="926" alt="image" src="https://user-images.githubusercontent.com/56375728/182341526-8c3195f7-d38a-4e5b-a9cb-38fb8e30c034.png">

**Comment by bailicangdu** [comment]
提供个demo看一下吧

**Comment by LlanHao** [comment]
方便添加下我的联系方式吗，项目是内网项目比较复杂。不好弄demo。我微：a947404912   万分感谢~

**Comment by BoosL** [comment]
@LlanHao 你好 微前端环境下子应用的页面缓存的实现 能提供一个demo参考一下吗？

**Comment by BoosL** [comment]
@LlanHao 你好 微前端环境下子应用的页面缓存的实现 能提供一个demo参考一下吗？
