### ISSUE TITLE
主应用和子应用都是hash下 ，ChunkLoadError: Loading chunk fail failed

### ISSUE THREAD

**Issue by ibandeng** [jd-opensource/micro-app#512]
主应用和子应用都是hash下 ，主应用跳转到子应用，然后子应用返回主应用懒加载并且没有加载过的页面会报ChunkLoadError: Loading chunk fail failed错误。请问怎么解决。
[demo地址](https://github.com/ibandeng/micro-app-demo)

**Comment by bailicangdu** [comment]
原因是popstate事件同时触发了基座和子应用的路由响应，而子应用没有/#/aboult页面，导致出错，解决方式参考 https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/jump?id=%e6%96%b9%e5%bc%8f%e4%b8%89%e3%80%81%e4%bc%a0%e9%80%92%e8%b7%af%e7%94%b1%e5%ae%9e%e4%be%8b%e6%96%b9%e6%b3%95

**Comment by ibandeng** [comment]
> 原因是同时触发了和//micropopstate应用程序的路由和子应用程序的路由，引发异常，解决方式参考[/#https://https://github.com/micro-zoe.github.io/micro-app/docs.html #/zh-cn/jump?id=%e6%96%b9%e5%bc%8f%e4%b8%89%e3%80%81%e4%bc%a0%e9%80%92%e8%b7 %af%e7%94%b1%e5%ae%9e%e4%be%8b%e6%96%b9%e6%b3%95](https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/jump?id=%e6%96%b9%e5%bc%8f%e4%b8%89%e3%80%81%e4%bc%a0%e9%80%92%e8%b7%af%e7%94%b1%e5%ae%9e%e4%be%8b%e6%96%b9%e6%b3%95)

demo 按照方式三改了，还是报错

**Comment by bailicangdu** [comment]
加上这个
![image](https://user-images.githubusercontent.com/20297227/182756415-a4c33bc6-f2ed-4991-a53e-dc828197a1d0.png)

**Comment by ibandeng** [comment]
> 加上这个 ![image](https://user-images.githubusercontent.com/20297227/182756415-a4c33bc6-f2ed-4991-a53e-dc828197a1d0.png)
感谢，问题解决了
