### ISSUE TITLE
url 属性必须是一个完整的 URI 路径吗？

### ISSUE THREAD

**Issue by jawn-ha** [jd-opensource/micro-app#513]
首先感谢您的工作，micro-app确实接入简单，但是目前遇到一个问题，希望作者能帮忙看下

## 问题描述
<micro-app> 的 url 属性必须是一个完整的 URI 路径吗？为什么使用绝对路径会报错

## 复现步骤
1. `<micro-app url="/avue/xxx/index.html">`
2. 报错：Failed to construct 'URL': Invalid URL

## 上传截图

![image](https://user-images.githubusercontent.com/16000122/182509306-5491b434-311b-4ee0-940d-1306b7996e46.png)
![image](https://user-images.githubusercontent.com/16000122/182509327-61213610-b89b-476a-891d-6c0821fb267b.png)

## 复现仓库
暂无

## 环境信息
- micro-app版本：0.8.8
- 主应用前端框架&版本：Vue2.6
- 子应用前端框架&版本：Vue2.6
- 构建工具&版本：vue-cli4.x

**Comment by bailicangdu** [comment]
是的

**Comment by jardenliu** [comment]
用new URL(url, location.herf)处理一下
