### ISSUE TITLE
基座菜单栏 子应用间(携带二级路由路径) 跳转

### ISSUE THREAD

**Issue by UltramanWeiLai** [jd-opensource/micro-app#517]
## 问题
在基座中通过菜单栏进行 子应用 之间的路由跳转(指定路由)
例如：
当前再 app1 的 home 页面，通过 基座 的菜单栏跳转到 app2 的 list 页面
直接控制 基座 做全量的跳转，子应用无法响应
我目前的做法是，先通过基座跳转到对应子应用的基础路由，再通过发送路由跳转信息让子路由进行跳转，但是子路由无法响应这次路由跳转的信息，可能是 子应用 此时还没加载好 ，然后 加载完成后 getData 的信息被 micro-app 标签上的传递覆盖了
![image](https://user-images.githubusercontent.com/23336585/183052436-6fa4b4a9-499d-4c57-8731-04c1a772621b.png)

请问一下这种情况有什么解决方案吗？

**Comment by bailicangdu** [comment]
app1和app2是同时存在的吗

**Comment by bailicangdu** [comment]
如果是同时存在，可以让app1直接发送全局数据，app2监听全局数据，接受到新数据后跳转

**Comment by bailicangdu** [comment]
如果不是同时存在，通过app1控制基座跳转就可以了，app2在渲染时会根据浏览器url渲染对应页面

**Comment by UltramanWeiLai** [comment]
> app1和app2是同时存在的吗

不是同时存在，翻遍了 issue 发现，主应用直接跳转完整路径，子应用会响应初始化的路由路径，建议再文档上面 标注 一下，很容易被 主 子 应用之间路由无关联的给影响到

**Comment by lizesheng0313** [comment]
请问怎么处理的呢最后
