### ISSUE TITLE
子应用使用vite 3报无法连接到websocket错误，但是功能正常 

### ISSUE THREAD

**Issue by bobfw** [jd-opensource/micro-app#519]
## 问题描述
> 问题的具体描述

## 复现步骤
1. 将子应用vite版本升为3即可

## 上传截图
<img width="565" alt="image" src="https://user-images.githubusercontent.com/26560612/183291937-fbf99abe-728b-4e3c-8d5a-534b25b91375.png">

## 环境信息
- micro-app版本：0.8.8
- 主应用前端框架&版本：react 18.2.0，micro-app 0.88
- 子应用前端框架&版本：react 18.2.0，micro-app 0.88
- 构建工具&版本：主子都是vite 3.0.4

**Comment by gaofeng222** [comment]
![image](https://user-images.githubusercontent.com/18065659/183884190-a599e42c-95f4-4928-b6cb-7e8fdaf18314.png)
我的vite2.x也有

**Comment by liyuanjie0225** [comment]
我尝试把vite版本降低为2.9.9后控制台不报错了。
