### ISSUE TITLE
基座中渲染子应用卡顿问题

### ISSUE THREAD

**Issue by Jonathan-Rao** [jd-opensource/micro-app#52]
接入试用了一下，发现在基座中子应用元素渲染非常卡顿，单独运行子应用非常流畅，请问是什么原因导致的？，怎么优化？

**Comment by bailicangdu** [comment]
框架、版本号，ui库发一下呢

**Comment by Jonathan-Rao** [comment]
@bailicangdu  

vue框架：用的这个脚手架，基座和子应用都是这个框架  https://github.com/PanJiaChen/vue-admin-template
UI框架:使用的element ui  2.15.5版本
页面用的el-table 加载数据，100条就很卡了，使用虚拟dom加载几千条数据会更加卡，在单独运行子应用中是很流畅的

**Comment by bailicangdu** [comment]
好的

**Comment by bailicangdu** [comment]
你可以先尝试将沙箱关闭来避免这个问题

**Comment by Jonathan-Rao** [comment]
@bailicangdu 您好，这是我的demo，基座应用中加载子应用明显有卡顿，我担心后面随着功能越来越多，会更加卡顿，您看是否有解决方案？
https://github.com/Jonathan-Rao/my-micro-app-demo

**Comment by bailicangdu** [comment]
好的

**Comment by caojunior** [comment]
我这边使用也存在这个问题，直接访问子应用和在基座内访问子应用请求等都存在大概三分之一的延迟，做地图应用尤为明显，希望这个框架能解决这种问题，还是很支持的

**Comment by Yubiao-Li** [comment]
+1

**Comment by mursumomo** [comment]
是的，好卡！而且建议能想qiankun一样，添加loading钩子。现在等待一个比较庞大的应用，会超卡，而且样式加载也会一部分失败

**Comment by bailicangdu** [comment]
我们正在尝试解决这个问题，请大家耐心等待

**Comment by shiwanmenghuxiahuashan** [comment]
> 你可以先尝试将沙箱关闭来避免这个问题

请问关闭沙箱渲染会带来什么问题？

**Comment by bailicangdu** [comment]
> > 你可以先尝试将沙箱关闭来避免这个问题
> 
> 请问关闭沙箱渲染会带来什么问题？

关闭沙箱会导致micro-app部分功能失效，如样式隔离，因为没有沙箱的隔离，js更容易产生冲突。如果处理得当可以关闭沙箱，比如vite作为子应用时

https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/configure?id=disablesandbox

**Comment by shiwanmenghuxiahuashan** [comment]
> > > 你可以先尝试将沙箱关闭来避免这个问题
> > 
> > 
> > 请问关闭沙箱渲染会带来什么问题？
> 
> 关闭沙箱会导致micro-app部分功能失效，如样式隔离，因为没有沙箱的隔离，js更容易产生冲突。如果处理得当可以关闭沙箱，比如vite作为子应用时
> 
> https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/configure?id=disablesandbox

谢谢，有仔细看文档，你们很棒，谢谢。

**Comment by mursumomo** [comment]
子应用接入后，使用一段时间，页面越来越卡，滚动卡，数据渲染操作也卡。单独打开，操作就很流畅。看内存占用也不高，但就是很卡

**Comment by bailicangdu** [comment]
@ice-musru 可以留个联系方式吗

**Comment by bailicangdu** [comment]
v0.7.0 重构沙箱，性能提升 20% ~ ∞，页面越复杂性能提升越明显，欢迎升级尝试 https://github.com/micro-zoe/micro-app/releases/tag/v0.7.0
