### ISSUE TITLE
父应用使用keep-alive,切换页面子应用未渲染

### ISSUE THREAD

**Issue by lytgexiao** [jd-opensource/micro-app#521]
## 问题描述
> 问题的具体描述
父应用使用keep-alive缓存页面，micro-app 用keep-alive属性缓存子应用，页面切换，子应用无法渲染

## 复现步骤
1.父应用使用keep-alive标签包括router-view
2.在页面嵌入子应用（使用keep-alive属性）<micro-app name='xx' url='xx' **keep-alive**></micro-app>
3.期望切换路由保留父应用状态的同事，子应用keep-alive也可以重新渲染

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。
![image](https://user-images.githubusercontent.com/42412103/183384620-fde29d9c-e08e-40a7-ae44-f3675a78e37d.png)

![e0da7a4f043e846b27f5824a15bde77](https://user-images.githubusercontent.com/42412103/183380967-e3be2cd0-2581-4ba1-b945-97d7e35ab6d2.jpg)

![88f907f58d76265c282ab718d089297](https://user-images.githubusercontent.com/42412103/183384306-40e67205-2d43-4249-a4fc-ec22991febdc.jpg)

![0d663209bbf74eca27789320ec38b4d](https://user-images.githubusercontent.com/42412103/183384087-48cffff7-c34b-47c5-a5a5-e1587615b23d.jpg)

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。

## 环境信息
- micro-app版本：0.8+
- 主应用前端框架&版本：vue2
- 子应用前端框架&版本：vue2
- 构建工具&版本：webpack

**Comment by bailicangdu** [comment]
能提demo看一下吗

**Comment by lytgexiao** [comment]
![image](https://user-images.githubusercontent.com/42412103/183543704-16d54d0c-a2f8-4f41-b32e-84c72b87941a.png)
就很正常的需求，父应用的页面也需要keep-alive，但是父应用切换页面的时候子应用无法渲染出来，既不报错又执行了appstate-change

**Comment by lytgexiao** [comment]
github 示例地址：https://github.com/lytgexiao/public-app

**Comment by lytgexiao** [comment]
> 能提demo看一下吗

https://github.com/lytgexiao/public-app

**Comment by Rain20199** [comment]
这问题解决了吗
