### ISSUE TITLE
keep-alive 问题，提供了demo

### ISSUE THREAD

**Issue by lytgexiao** [jd-opensource/micro-app#524]
## 问题描述
> 问题的具体描述

## 复现步骤
1.https://github.com/micro-zoe/micro-app/issues/521
2.https://github.com/lytgexiao/public-app

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。

## 环境信息
- micro-app版本：
- 主应用前端框架&版本：
- 子应用前端框架&版本：
- 构建工具&版本：

**Comment by bailicangdu** [comment]
路由不对，基座是hash，子应用是history，这是没办法正常运行的，建议都改成history路由

**Comment by bailicangdu** [comment]
vue的`<keep-alive>`会在瞬间渲染和卸载micro-app两次，导致出现问题，我们会在近期进行修复，感谢反馈
