### ISSUE TITLE
基站应用的样式跟子应用的样式冲突

### ISSUE THREAD

**Issue by huang-ju** [jd-opensource/micro-app#528]
基站用 ant-design 组件库，子应用也用了 ant-desigin组件库。基站有一些样式对组件库进行了修改，但不想子应用受到影响，有什么方法让子应用不受基站样式的影响吗？

**Comment by bailicangdu** [comment]
ant-design支持设置prefixCls  class前缀可以解决这个问题 https://ant.design/components/config-provider-cn/#ConfigProvider.config()-4.13.0+
