### ISSUE TITLE
是否可以支持子应用之间弹窗嵌套 展示某一个页面？

### ISSUE THREAD

**Issue by baosuyaole1** [jd-opensource/micro-app#531]
## 背景
> 描述您希望改进的问题。
是否可以支持子应用之间弹窗嵌套 展示某一个页面？ 无哭无泪啊 
## 期望的效果
希望在子应用之间相互嵌套详情页进行展示
如果实在不行 那如果在基座中以弹窗的形式嵌套呢 ？望楼主提供一个demo
或者是告知一下使用哪个api可以解决此类问题。感谢🙏

<micro-app default-page='页面地址'></micro-app>
使用这个标签加载会修改地址栏路由信息 影响返回操作 
是否可以结合虚拟路由守卫判断环境并把路由记录进行删除操作

**Comment by bailicangdu** [comment]
micro-app版本是多少

**Comment by bailicangdu** [comment]
`使用这个标签加载会修改地址栏路由信息 影响返回操作` 
子应用渲染时不会增加路有堆栈，不应该有返回问题

**Comment by baosuyaole1** [comment]
最新的版本 原因是 vite打包子应用 所以关闭沙箱导致的这问题
不知道咱们多久会支持vite沙箱啊 支持后是否可以使用虚拟路由


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "micro-zoe/micro-app"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月12日(星期五) 下午4:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [micro-zoe/micro-app] 是否可以支持子应用之间弹窗嵌套 展示某一个页面？ (Issue #531)





 
micro-app版本是多少
