### ISSUE TITLE
vite 兼容问题

### ISSUE THREAD

**Issue by lufandev** [jd-opensource/micro-app#534]
请问对于基座和自应用都用的vite的项目，大概什么时候可以使用micro-app呢

**Comment by M69W** [comment]
我们首先要关注的 是 vite 兼容遇到了什么问题吧，
目前大概的情况如何。

**Comment by lufandev** [comment]
也许我的题目描述不准确，其实我的问题是：
目前项目在做前期调研，如果基座和子应用都用的vite的话，是否可以成熟使用micro-app了，如果还不是很成熟的话，可以考虑改用webpack的

**Comment by bailicangdu** [comment]
目前排期是9月份

**Comment by iq9891** [comment]
vite3什么时候支持
