### ISSUE TITLE
v1.0.0-alpha.5  虚拟路由系统  default-page 不起作用

### ISSUE THREAD

**Issue by baosuyaole1** [jd-opensource/micro-app#535]
## 问题描述
> 问题的具体描述

## 复现步骤
1. <micro-app
      name="adminSet"
      inline
      disableSandbox
      url="http://localhost:3004/adminSet"
      default-page="/commentTemplateList"
    ></micro-app>
2.
3.webpack构建的子应用没有问腿

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。
子应用路由配置 
<img width="1044" alt="image" src="https://user-images.githubusercontent.com/28467941/184290334-64ece7ee-e517-45bf-98e0-2127f11464d8.png">
加载后无法定位默认路径
![image](https://user-images.githubusercontent.com/28467941/184290510-f2644cef-f181-40ab-a143-fb46ca9ed692.png)

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。

## 环境信息
- micro-app版本：
- 主应用前端框架&版本：v1.0.0-alpha.5  基座"vue": "^3.2.13",  "vue-router": "4.0.11",
- 子应用前端框架&版本：子应用  "vue": "^3.2.31","vue-router": "4",vite构建
- 构建工具&版本：

**Comment by bailicangdu** [comment]
关闭沙箱后虚拟路由系统也会失效，文档缺少这个提示，后续会补充

**Comment by baosuyaole1** [comment]
好的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "micro-zoe/micro-app"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月12日(星期五) 下午4:47
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [micro-zoe/micro-app] v1.0.0-alpha.5  虚拟路由系统  default-page 不起作用 (Issue #535)





 
关闭沙箱后虚拟路由系统也会失效，文档缺少这个提示，后续会补充
