### ISSUE TITLE
子应用样式隔离

### ISSUE THREAD

**Issue by heD0ng** [jd-opensource/micro-app#536]
## 问题描述
> 问题的具体描述
我们的项目主要应用于pc端, 所以基座的body上设置了min-width: 1200px, 但是目前子应用有场景需要适配移动端, 所以需要利用样式隔离设置min-width. 问题是, 采用scss语法在子应用中设置会失败, 但是采用css语法就可以实现效果.
## 上传截图
1. min-width设置失败;
![image](https://user-images.githubusercontent.com/73006116/184319122-2b194bc4-38e1-4476-abe5-4e579da18c0e.png)

2. min-width设置成功;
![image](https://user-images.githubusercontent.com/73006116/184319162-82a0db19-a7c8-44fe-9697-e5115e3354be.png)

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。

## 环境信息
- micro-app版本：0.8.7
- 主应用前端框架&版本：vue 2.6.11
- 子应用前端框架&版本：vue 2.6.11
- 构建工具&版本：lerna: ^4.0.0, webpack: ^4.0.0
- css-loader: ^3.5.3,
- postcss-loader: ^3.0.0
- "vue-style-loader": ^4.1.2
- sass-loader: 8.0.2

**Comment by bailicangdu** [comment]
我自己试了一下，没有问题
<img width="446" alt="image" src="https://user-images.githubusercontent.com/20297227/184326148-162645c7-bba6-41e7-b4d1-47f69cd07e7e.png">

**Comment by bailicangdu** [comment]
<img width="512" alt="image" src="https://user-images.githubusercontent.com/20297227/184326222-49771eae-e760-4b78-86e2-670951b60d22.png">

**Comment by heD0ng** [comment]
其实我也比较疑惑这一点。但是我不确定是否是webpack或者loader这类工具是否会影响micro中的魔法注释，从而导致语法不生效，所以才向您请教一下。
