### ISSUE TITLE
vue3项目env.mjs报错

### ISSUE THREAD

**Issue by zhangyiweb** [jd-opensource/micro-app#539]
![image](https://user-images.githubusercontent.com/71304444/184569829-365440dd-1717-4acf-bba7-10d9317f6b78.png)
vue create xx创建v3项目和vite创建v3项目使用micro-app出现这个错误。是怎么解决。

**Comment by zhangyiweb** [comment]
> Hello @zhangyiweb. In order to facilitate location and troubleshooting, we need you to provide a realistic GitHub repository. 您好 @zhangyiweb, 为了方便定位和排查问题，我们需要您提供一个重现实例，请提供一个尽可能精简的 GitHub 仓库地址。

**Comment by zhangyiweb** [comment]
> Hello @zhangyiweb. In order to facilitate location and troubleshooting, we need you to provide a realistic GitHub repository. 您好 @zhangyiweb, 为了方便定位和排查问题，我们需要您提供一个重现实例，请提供一个尽可能精简的 GitHub 仓库地址。

https://gitee.com/zhangyiweb/basc.git

**Comment by dukeL12** [comment]
请问这个是怎么解决的呢，我也遇到了
