### ISSUE TITLE
angular 13 创建的项目，没办法资源路径自动补全

### ISSUE THREAD

**Issue by wangyunteng** [jd-opensource/micro-app#540]
## 问题描述

angular 13 创建的项目，没办法资源路径自动补全
__MICRO_APP_ENVIRONMENT__，
__MICRO_APP_ENVIRONMENT__ 等环境变量为空

## 复现步骤
1. 启动主项目，打开hash 子项目会发现图片加载不出来
2. 打开子项目public-path 打印__MICRO_APP_ENVIRONMENT__ 为空

## 上传截图
![1660549105723](https://user-images.githubusercontent.com/49503411/184595188-ff60510c-7b62-498d-91c6-6fb69cc88fe5.png)

## 复现仓库
https://github.com/wangyunteng/micro-app.git

## 环境信息
- micro-app版本：0.8.8
- 主应用前端框架&版本：angular 13 hash模式
- 子应用前端框架&版本：angular 13 hash模式
- 构建工具&版本：node 14.17.5

**Comment by bailicangdu** [comment]
问题已经在处理，会在近期修复

**Comment by lanmingle** [comment]
angular 13 我测试发现是无法获取相关变量值。

**Comment by teeom** [comment]
angular 14 发现了同样的问题

**Comment by bailicangdu** [comment]
angular13、14相关问题在 [v1.0.0-alpha.6](https://github.com/micro-zoe/micro-app/releases/tag/v1.0.0-alpha.6)版本中已解决

**Comment by wangyunteng** [comment]
我更新到0.8.10 版本还是不能获取 @bailicangdu

**Comment by bailicangdu** [comment]
> 我更新到0.8.10 版本还是不能获取 @bailicangdu

需要升级到1.0版本 https://micro-zoe.com/docs/1.x/#/zh-cn/transfer

**Comment by wangyunteng** [comment]
可以了，谢谢大佬 @bailicangdu
