### ISSUE TITLE
keep-router-state不生效

### ISSUE THREAD

**Issue by X-J-C** [jd-opensource/micro-app#545]
基座和子应用用的都是vue和hash路由，刷新之后默认回到首页，用keep-router-state不生效，micro-app是最新版本

**Comment by bailicangdu** [comment]
刷新浏览器？

**Comment by X-J-C** [comment]
是的，刷新浏览器就默认回到首页。如果不用新版micro-app，就报错

**Comment by bailicangdu** [comment]
如果关闭了虚拟路由，就是路由没有配置好

**Comment by bailicangdu** [comment]
子应用加载后的浏览器地址发一下呢

**Comment by X-J-C** [comment]
http://localhost:8080/#/workbench/clous?clous=%2F%23%2Forganization
没有关闭虚拟路由

**Comment by bailicangdu** [comment]
可以提供个demo看一下吗

**Comment by X-J-C** [comment]
基座路由是这么配置的
![image](https://user-images.githubusercontent.com/48943037/185324788-89019ff8-b350-4119-9b83-2504fd57fa09.png)
这个是子应用配置
![image](https://user-images.githubusercontent.com/48943037/185325430-61e992e1-c39d-4e38-9e2b-e3afca49eb90.png)

**Comment by X-J-C** [comment]
因为是公司项目，所以不好做demo

**Comment by bailicangdu** [comment]
刷新浏览器micro-app会根据url参数渲染对应的子应用页面，如`?clous=%2F%23%2Forganization`，刷新之后子应用默认跳转到首页只有可能是参数被删除或者修改导致的

**Comment by X-J-C** [comment]
项目刷新之后micro-app元素被重新创建，路由也就跳转到默认路由了。是不是这个影响了

**Comment by bailicangdu** [comment]
<img width="813" alt="image" src="https://user-images.githubusercontent.com/20297227/185335968-afbb6286-ceda-4604-ba37-8953ba4b583b.png">

**Comment by bailicangdu** [comment]
添加unmount事件，看一下刷新时子应用有没有被卸载

**Comment by X-J-C** [comment]
没有被卸载，但是加载后子应用加载两次，第一个路由是刷新前的路由，第二个是默认路由
![image](https://user-images.githubusercontent.com/48943037/185337666-1b278954-3723-46a3-a507-0f6f1ef722fa.png)

**Comment by bailicangdu** [comment]
设置了keep-alive吗

**Comment by bailicangdu** [comment]
<img width="320" alt="image" src="https://user-images.githubusercontent.com/20297227/185339782-2d47bafe-2ce6-428d-8f9a-18071698892c.png">

**Comment by X-J-C** [comment]
子应用设置了，这个有影响吗？

**Comment by bailicangdu** [comment]
> 没有被卸载，但是加载后子应用加载两次，第一个路由是刷新前的路由，第二个是默认路由 ![image](https://user-images.githubusercontent.com/48943037/185337666-1b278954-3723-46a3-a507-0f6f1ef722fa.png)

这种情况像是micro-app的url被改变了，检查一下url是否发生变化

**Comment by X-J-C** [comment]
我找到原因了，是因为我子应用接收基座传回来的数据时做了转换。谢谢大佬了
