### ISSUE TITLE
vite hash子应用打包部署异常Cannot read properties of undefined (reading 'replace')

### ISSUE THREAD

**Issue by hqzh** [jd-opensource/micro-app#547]
## 问题描述
1.本地开发正常
2.打包异常
3.主和子都是hash路由

## 集成子项目地址
https://github.com/sz-star/dolphinscheduler/tree/3.0.0-release/dolphinscheduler-ui
## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。
![image](https://user-images.githubusercontent.com/26128706/185781111-a8b5e240-f606-46a7-bab2-74afd391c3d7.png)
![image](https://user-images.githubusercontent.com/26128706/185781131-1d6a96e7-5318-4067-b345-89103f3225f5.png)

## 环境信息
- micro-app版本：
- 主应用前端框架&版本：vue2.x
- 子应用前端框架&版本：vite _ vue3
- 构建工具&版本：vite 2.9.13   "build:prod": "vue-tsc --noEmit && vite build --mode production"

**Comment by hqzh** [comment]
![image](https://user-images.githubusercontent.com/26128706/185783978-ea0042b0-d0aa-4e6e-bd98-8632a4f11e1b.png)

**Comment by hqzh** [comment]
### chunk打印结果
![image](https://user-images.githubusercontent.com/26128706/185819673-cae4d935-4ad9-4c53-ac4a-93793c6a0a3a.png)

**Comment by hqzh** [comment]
pnpm 和 npm 都报错

**Comment by CodeGod007** [comment]
老哥, 怎么解决的呢, 我和你的情况一样

**Comment by hqzh** [comment]
> 老哥, 怎么解决的呢, 我和你的情况一样

没解决呢

**Comment by CodeGod007** [comment]
@bailicangdu 
能帮忙看一下吗,这个问题比较棘手

**Comment by hqzh** [comment]
他们好像计划在基于iframe搞vite沙箱计划，我改用了wujie微前端

**Comment by hqzh** [comment]
他们好像计划在基于iframe搞vite沙箱计划，我改用了wujie微前端

**Comment by CodeGod007** [comment]
我们现在的需求和你们的差不多, 我们也是要集成海豚, 我怀疑是里面用到的编辑器插件,导致打包报错

**Comment by CodeGod007** [comment]
你好, 我现在也切换成啦wujie微前端, 但是现在有个问题是子应用请求报跨域, 这个问你你有遇到过吗, 怎么解决的呢?
@hqzh

**Comment by hqzh** [comment]
我没遇到这个问题，你可以加wujie微信群，作者回复挺快的

**Comment by CodeGod007** [comment]
老哥你从哪找到的wujie的微信群呢

**Comment by CodeGod007** [comment]
我已经加上啦, 谢谢老哥

**Comment by hqzh** [comment]
> 他们好像计划在基于iframe搞vite沙箱计划，我改用了wujie微前端
