### ISSUE TITLE
Vite + vue的使用体验很差，后期能否有方法解决module script导致的问题

### ISSUE THREAD

**Issue by a1067111756** [jd-opensource/micro-app#548]
## 背景
> 1. 配置过于繁琐，需要改造的地方太多
> 2. 资源加载报错，让人摸不清头脑

## 期望的效果
> 1. 解决module script导致的问题，让配置和其它保持一致

**Comment by bailicangdu** [comment]
vite 沙箱正在开发中，敬请期待

**Comment by jingjingzhao** [comment]
> vite 沙箱正在开发中，敬请期待

这个有预期的时间吗？我们系统也是vite+vue的... @bailicangdu

**Comment by bailicangdu** [comment]
> > vite 沙箱正在开发中，敬请期待
> 
> 这个有预期的时间吗？我们系统也是vite+vue的... @bailicangdu

9月底
