### ISSUE TITLE
高德地图 基座上高德地图模块打开后 打开子应用高德地图加载失败

### ISSUE THREAD

**Issue by dongoa** [jd-opensource/micro-app#549]
## 问题描述
> 问题的具体描述

## 复现步骤
1.
2.

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。

## 环境信息
- micro-app版本：
- 主应用前端框架&版本：
- 子应用前端框架&版本：
- 构建工具&版本：

显示：禁止多种API加载方式混用
失败后 基座的高德地图也会报错 有什么解法么 求救！

**Comment by dongoa** [comment]
版本     "@micro-zoe/micro-app": "^1.0.0-alpha.6

**Comment by dongoa** [comment]
相当于基座的window上挂在了Amap，然后就有问题貌似

**Comment by dongoa** [comment]
基座项目的webpack  externals 里配置了AMap

**Comment by bailicangdu** [comment]
重复加载吗

**Comment by dongoa** [comment]
> 重复加载吗

先打开基座和子应用的高德地图会受影响，大佬求救

**Comment by bailicangdu** [comment]
设置插件的scopeProperties试一下
```js
microApp.start({
  plugins: {
    global: [
      {
        scopeProperties: ['AMap'],
      }
    ],
  },
})
```

**Comment by dongoa** [comment]
我觉得和window上挂载的AMap有关系，我试试 

> 设置插件的scopeProperties试一下
> 
> ```js
> microApp.start({
>   plugins: {
>     global: [
>       {
>         scopeProperties: ['AMap'],
>       }
>     ],
>   },
> })
> ```
我觉得和window上挂载的AMap有关系，我试试

**Comment by dongoa** [comment]
我觉得和window上挂载的AMap有关系，我试试 

> 设置插件的scopeProperties试一下
> 
> ```js
> microApp.start({
>   plugins: {
>     global: [
>       {
>         scopeProperties: ['AMap'],
>       }
>     ],
>   },
> })
> ```
我觉得和window上挂载的AMap有关系，我试试

**Comment by ohion** [comment]
> 我觉得和window上挂载的AMap有关系，我试试
> 
> > 设置插件的scopeProperties试一下
> > ```js
> > microApp.start({
> >   plugins: {
> >     global: [
> >       {
> >         scopeProperties: ['AMap'],
> >       }
> >     ],
> >   },
> > })
> > ```
> 
> 我觉得和window上挂载的AMap有关系，我试试

问题有解决吗？
