### ISSUE TITLE
vite react 的子应用，路由懒加载文件报404？

### ISSUE THREAD

**Issue by hdbaiyu** [jd-opensource/micro-app#55]
![image](https://user-images.githubusercontent.com/10139104/130384824-ce206687-7121-4eca-9868-d684abceec1e.png)

子应用的路由配置：
![image](https://user-images.githubusercontent.com/10139104/130384888-cde0fb16-5eea-42d9-bca1-505c2a59ecd1.png)

**Comment by bailicangdu** [comment]
需要设置 public_path https://zeroing.jd.com/micro-app/docs.html#/zh-cn/static-source?id=%e6%89%8b%e5%8a%a8%e8%a1%a5%e5%85%a8

**Comment by hdbaiyu** [comment]
加了public_path文件也没有用呢！

**Comment by bailicangdu** [comment]
8081的端口号是基座应用还是子应用的？

**Comment by hdbaiyu** [comment]
基座应用8081，子应用8003

**Comment by bailicangdu** [comment]
那就还是public_path的问题，在vite.config.js中配置base，设置全地址，如：http://localhost:8003/micro-app/

**Comment by hdbaiyu** [comment]
并没有效果

**Comment by bailicangdu** [comment]
思路就是这样，根据项目实际情况对静态资源前缀进行补全就行
