### ISSUE TITLE
主应用调用setData后，会覆盖通过data传递的数据吗？

### ISSUE THREAD

**Issue by will961123** [jd-opensource/micro-app#550]
```js
// 主应用代码

<micro-app name="micro-app" :url="microAppUrl" :data="microAppData"></micro-app>

 <el-button @click="setData">主应用调用setData</el-button>

  computed: {
    microAppData (){
      return {
        remoteRouter: this.$router
      }
    }
  }

setData (){
      console.log('主应用调用setData')
      microApp.setData('micro-app', {eventCode: 'router-push', eventData: {path: '/micro-app/page1'}})
    },
```

```js
// 子应用代码

<el-button @click="getData">获取主应用传递的data</el-button>

 getData (){
      console.log('子应用调用getData', window.microApp.getData())
    }

```

![image](https://user-images.githubusercontent.com/45943678/185901668-97afb8ac-905d-42c5-9479-abd5411bafd8.png)

作者你好，今天刚使用micro-app，根据文档 “应用之间跳转” 部分提供的示例方法来做，我这边出现了一些问题。在如图所示，在子应用中直接使用 window.microApp.getData() 获取主应用传递的 data ，主应用调用 microApp.setData() 方法后，再次尝试获取时，原先在data中定义的数据被覆盖了。请问我该怎么做才能不被覆盖呢？

**Comment by will961123** [comment]
版本信息
"@micro-zoe/micro-app": "^0.8.10"
"vue": "^2.6.14"

主、子路由均为hash模式

**Comment by bailicangdu** [comment]
目前方式是在setData手动合并新旧值

**Comment by will961123** [comment]
> 当前方式是在setData手动合并新旧值

microApp.getData('micro-app') 这种方式是不是不能获取通过 data 传递的数据

![image](https://user-images.githubusercontent.com/45943678/185904735-e16d0133-2679-4bb7-ab9d-071598fa89cb.png)

**Comment by bailicangdu** [comment]
> > 当前方式是在setData手动合并新旧值
> 
> microApp.getData('micro-app') 这种方式是不是不能获取通过 data 传递的数据
> 
> ![image](https://user-images.githubusercontent.com/45943678/185904735-e16d0133-2679-4bb7-ab9d-071598fa89cb.png)

这是获取子应用上传给基座的数据
