### ISSUE TITLE
子应用的弹框样式z-index， 影响父级应用

### ISSUE THREAD

**Issue by tangchaoren1** [jd-opensource/micro-app#554]
## 问题描述
> 父级应用: iview2 + vue  子应用: element-ui - vue  当子应用弹框出现时，父级应用左侧导航 z-index 层级出现问题。导致子应用的遮罩层部分失效

## 复现步骤
1.  
2.

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。

## 环境信息
- micro-app版本：0.8
- 主应用前端框架&版本：iview2 + vue
- 子应用前端框架&版本：  element-ui - vue
- 构建工具&版本：webpack

**Comment by bailicangdu** [comment]
由于基座影响子应用的样式问题，目前只能手动调整样式解决
