### ISSUE TITLE
基座应用重定向如何处理

### ISSUE THREAD

**Issue by xuya227939** [jd-opensource/micro-app#557]
在子应用内部进行路由跳转，会被基座应用拦截掉进行重定向，请问如何处理？基座应用重定向代码删除，则不会拦截，子应用正常跳转。但是不能删除基座应用重定向代码

**Comment by bailicangdu** [comment]
子应用的跳转不应该触发重定向，baseroute设置对了就不应该出这样的问题

**Comment by xuya227939** [comment]
@bailicangdu 跟着 demo 配置来的，如何验证是否设置成功？

**Comment by bailicangdu** [comment]
micro-app的版本是多少

**Comment by xuya227939** [comment]
@bailicangdu  0.8.8

**Comment by bailicangdu** [comment]
升级到1.0，用虚拟路由隔离子、主应用试一下 `npm i @micro-zoe/micro-app@alpha --save`

**Comment by bailicangdu** [comment]
https://micro-zoe.com/docs/1.x/#/zh-cn/start

**Comment by xuya227939** [comment]
@bailicangdu 好的，我试试

**Comment by xuya227939** [comment]
@bailicangdu  请问下 0.8.8 版本如何解决这个问题？1.x 版本直接升级，跑不起来；关闭虚拟路由也跑不起来，大概看了下可能是promise 拦截报错了

**Comment by xuya227939** [comment]
@bailicangdu  请问下 0.8.8 版本如何解决这个问题？1.x 版本直接升级，跑不起来；关闭虚拟路由可加载子应用

**Comment by bailicangdu** [comment]
能提供个demo看一下吗

**Comment by xuya227939** [comment]
@bailicangdu 关闭虚拟路由和 开启 disable-patch-request，倒是解决了我的问题，demo 的话，我看看如何提供。。。

**Comment by xuya227939** [comment]
@bailicangdu 本地开发加载子应用没有问题，打包部署之后，micro-app fetch 子应用出错，部署后的页面，单独访问是没问题的，请问这种错误如何排查？
![企业微信截图_e10b23bd-ef46-4f5a-98e0-f78a72beb6ef](https://user-images.githubusercontent.com/16217324/188102040-c11bb2bf-6494-45ca-bf38-251e14e7db08.png)

![企业微信截图_d0f69854-7aab-4ede-80ec-23abd698dafd](https://user-images.githubusercontent.com/16217324/188102049-0d412bb1-c994-4886-ad21-e271b033fa17.png)

**Comment by bailicangdu** [comment]
js地址没找到，404

**Comment by bailicangdu** [comment]
子应用的构建工具是什么，vite？

**Comment by xuya227939** [comment]
Webpack，单独访问子应用，没有看到相关文件 404；看基座应用 network 下，有一个请求是来自子应用的 JS 文件 404

**Comment by bailicangdu** [comment]
public_path设置了吗

**Comment by xuya227939** [comment]
@bailicangdu 大佬，还有个问题想问下，某个子应用使用了 Driver.js 库，在进行渲染的时候，是基于 micro-app 获取到的 document.body，如何不更改库的源码，修复成获取主应用的 document.body ?

**Comment by bailicangdu** [comment]
通过window.rawDocument.body访问，在不该动代码的基础上做不到

**Comment by xuya227939** [comment]
micro-app 本身是否能提供这样的能力？比如文档提到的忽略元素（我试了下，并不行），基于这个思路，针对特定的库，加载在主应用下？，这样能解决UI问题吗？

**Comment by bailicangdu** [comment]
micro-app 只能针对script元素进行配置，对于通过import引入的第三方包无法控制

**Comment by xuya227939** [comment]
好的，感谢
