### ISSUE TITLE
vue 2.x 使用 keep-alive，点击子应用路由时，一直重复卸载创建渲染，无法正常进入子应用

### ISSUE THREAD

**Issue by innocencepj** [jd-opensource/micro-app#558]
## 问题描述
> micro-app 1.x 版本，父应用使用 keep-alive, micro-app 设置 keep-alive，切换的时候，子应用一直重复 卸载-> 创建 -> 渲染。且路由后面添加了一串子应用的路由信息（不太确定）？不跳转到子应用页面。
micro-app 0.8+ 版本，使用 keep-alive，有和 [#521](https://github.com/micro-zoe/micro-app/issues/521) 相同的问题

## 复现步骤
1. 父应用 router-view 使用 keep-alive
2. 父应用分给子应用的路由页面中， micro-app 使用 v-if 控制是否使用子应用。
3. 父应用分给子应用的路由，子应用中也有相同的路由
4. 父应用中，点击子应用页面时，传过去 path，子应用跳转到相应的 path。
5. 从主应用访问过的路径栏，进入缓存的子应用页面，一直重复卸载创建渲染，地址栏一直闪现，不会跳转到子应用页面。如果点击一个新的子应用项，则会显示之前的子应用项的内容。

## 上传截图
> 
micro-app 使用 v-if 控制

![image](https://user-images.githubusercontent.com/29282556/186614081-84261d61-20d5-4f12-abb0-7e0304615004.png)
父应用分配给子应用的路由

![image](https://user-images.githubusercontent.com/29282556/186614708-f63cef51-2aba-4ddb-b985-37f17d11093b.png)
子应用中的路由

![image](https://user-images.githubusercontent.com/29282556/186614907-3dd4aaad-1342-4c0a-a35c-5e2da355f645.png)
父应用点击子应用页面

![image](https://user-images.githubusercontent.com/29282556/186617044-ec0603c6-2ecb-4d9d-85b5-13b05d99d865.png)
子应用中监听数据进行跳转，上图父应用中，点击下面的项以及路径，只要是子应用页面，都会触发下图子应用中的跳转
![image](https://user-images.githubusercontent.com/29282556/186617584-d99b005f-ecf7-4277-86e1-3e91da6e3ffe.png)
重复卸载创建渲染

![image](https://user-images.githubusercontent.com/29282556/186620788-161d2b2e-56e2-40d8-baaa-7a46036a7226.png)
地址栏，&subApp 及后面的内容一直闪现（快速消失出现）

![image](https://user-images.githubusercontent.com/29282556/186618908-f957509e-18f2-4aa1-8d75-9e926ca73e53.png)

## 复现仓库
> 公司项目
## 环境信息
- micro-app版本：1.0.0-alpha.6
- 主应用前端框架&版本：vue 2.6.11
- 子应用前端框架&版本：vue 2.6.11
- 构建工具&版本：vue-cli

**Comment by LengYXin** [comment]
我这也有个类似的问题，明明组件被卸载的时候还会创建渲染一次，就很奇怪了
![image](https://user-images.githubusercontent.com/19631404/186854553-a2f4b4e7-bf48-4c31-9e17-1280dd9602df.png)
micro-app版本：0.8.10
同vue 版本
没有使用  keep-alive

**Comment by sogud** [comment]
同样遇到，升级到1.0版本就好了。

**Comment by Plortinus** [comment]
> 

升级到1.0.0-beta.5也是重复卸载和创建子应用
