### ISSUE TITLE
请问后续会有主应用和子应用依赖共享的解决方案吗？

### ISSUE THREAD

**Issue by LadyChatterleyLover** [jd-opensource/micro-app#559]
如果主应用和子应用都使用了相同的第三方依赖，后续会有依赖共享的解决方案吗？

**Comment by bailicangdu** [comment]
已经在计划中，但还没想好具体怎么做，欢迎提供思路

**Comment by LadyChatterleyLover** [comment]
可以参考这个，https://wujie-micro.github.io/doc/guide/share.html

**Comment by bailicangdu** [comment]
> 可以参考这个，https://wujie-micro.github.io/doc/guide/share.html

如果是这种方式，micro-app本身就是支持的

**Comment by LadyChatterleyLover** [comment]
意思是把依赖挂载在window上面吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "micro-zoe/micro-app"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月26日(星期五) 中午1:42
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [micro-zoe/micro-app] 请问后续会有主应用和子应用依赖共享的解决方案吗？ (Issue #559)





  
可以参考这个，https://wujie-micro.github.io/doc/guide/share.html
  
如果是这种方式，micro-app本身就是支持的

**Comment by wsteth-dev** [comment]
依赖缓存感觉框架层面不好入手，得从打包层面考虑，就类似于module federation那种。公共依赖每加载都缓存到container里。下次打开就不请求不执行。

**Comment by LadyChatterleyLover** [comment]
其实也可以集成模块联邦，不过还是和框架有关系。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "micro-zoe/micro-app"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月26日(星期五) 下午2:33
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [micro-zoe/micro-app] 请问后续会有主应用和子应用依赖共享的解决方案吗？ (Issue #559)





 
依赖缓存感觉框架层面不好入手，得从打包层面考虑，就类似于module federation那种。公共依赖每加载都缓存到container里。下次打开就不请求不执行。

**Comment by zhangshenshenyunin** [comment]
> 本身就是支持的

方便给个microApp的链接吗

**Comment by zhangshenshenyunin** [comment]
> > 可以参考这个，https://wujie-micro.github.io/doc/guide/share.html
> 
> 如果是这种方式，micro-app本身就是支持的

您好，请问micro-app官方文档给出有说明吗

**Comment by fantasticsoul** [comment]
推荐采用[hel-micro](https://github.com/tnfe/hel), 管理[共享模块](https://www.bilibili.com/video/BV15t4y1u7i5/?vd_source=51bc50bf5f860e0d778c49b00d192cee)
