### ISSUE TITLE
新增操控子应用沙箱的API

### ISSUE THREAD

**Issue by bailicangdu** [jd-opensource/micro-app#562]
sandBox在micro-app元素创建之后、代码执行之前获取
```js
microApp.getSandBox(appName).then((sandBox) => {
  sandBox.exec('code') // 在子应用中执行js代码
  sandBox.getWindow() // 返回子应用的window
  sandBox.getDocument() // 返回子应用的document
  sandBox.inject(data: Object) // 注入子应用全局变量
  sandBox.deleteInjectData(key) // 删除指定注入子应用的全局变量
  sandBox.clearInjectData() // 删除所有注入子应用全局变量
})
```

**注意：**
1、预加载也会创建沙箱，但不会触发then，只有在代码执行前才会触发
2、注入的变量在应用卸载时不会被自动清除

**Comment by tuzhu008** [comment]
在什么时机能够拿到 sandBox 呢？

**Comment by bailicangdu** [comment]
> 在什么时机能够拿到 sandBox 呢？

sandBox在micro-app元素创建之后、代码执行之前可以获取
```js
microApp.getSandBox(appName).then((sandBox) => {
  sandBox.exec('code') // 在子应用中执行js代码
  sandBox.getWindow() // 返回子应用的window
  sandBox.getDocument() // 返回子应用的document
  sandBox.inject(data: Object) // 注入子应用全局变量
  sandBox.deleteInjectData(key) // 删除指定注入子应用的全局变量
  sandBox.clearInjectData() // 删除所有注入子应用全局变量
})
```

**Comment by tuzhu008** [comment]
> > 在什么时机能够拿到 sandBox 呢？
> 
> sandBox在micro-app元素创建之后、代码执行之前可以获取
> 
> ```js
> microApp.getSandBox(appName).then((sandBox) => {
>   sandBox.exec('code') // 在子应用中执行js代码
>   sandBox.getWindow() // 返回子应用的window
>   sandBox.getDocument() // 返回子应用的document
>   sandBox.inject(data: Object) // 注入子应用全局变量
>   sandBox.deleteInjectData(key) // 删除指定注入子应用的全局变量
>   sandBox.clearInjectData() // 删除所有注入子应用全局变量
> })
> ```

理解起来有点困难，是说子应用的代码执行之前吗？
