### ISSUE TITLE
react子应用中，React报undefined

### ISSUE THREAD

**Issue by jingjingzhao** [jd-opensource/micro-app#563]
## 问题描述
> 通过主应用( Vue 应用)跳转到子应用（React 应用），子应用 index.html 中通过 script 标签引入的 js 文件，在子应用的页面中报 undefined。如果单独运行子应用，并不会发生以上问题。

## 上传截图
![image](https://user-images.githubusercontent.com/5880014/187174672-4936b633-8e4c-403b-9b61-eb25fcffb25e.png)
![image](https://user-images.githubusercontent.com/5880014/187175428-c40f337f-6d69-452f-b3e2-440836dc2676.png)
![image](https://user-images.githubusercontent.com/5880014/187175660-57328b9f-3c9c-4872-a999-24729668553a.png)
![image](https://user-images.githubusercontent.com/5880014/187175634-5fb8abd1-8488-4d08-ab14-890fdecca30b.png)

## 环境信息
- micro-app版本：^0.8.10
- 主应用前端框架&版本：
     "vue": "3.2.36",
    "vue-router": "4.0.15"
    "vite": "2.9.9",
- 子应用前端框架&版本：（低代码引擎的lowcode-demo）
    "react"："16.14.0"
    "webpack": "4.46.0"

**Comment by bailicangdu** [comment]
lowcode-demo 是哪个项目？

**Comment by jingjingzhao** [comment]
> lowcode-demo 是哪个项目？

https://github.com/alibaba/lowcode-demo

**Comment by jingjingzhao** [comment]
我猜测是这里导致的，window.xxx，但不知道应该怎么修改。求大佬指点 @bailicangdu 
![image](https://user-images.githubusercontent.com/5880014/187345646-165b60d1-ee48-4e7e-a197-e720c4838459.png)
按着官方提供的解决方案，也不晓得这种情况应该如何修改。https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/questions?id=_12%e3%80%81%e9%94%99%e8%af%af%e4%bf%a1%e6%81%af%ef%bc%9axxx-%e6%9c%aa%e5%ae%9a%e4%b9%89

**Comment by jingjingzhao** [comment]
应该如何把子应用window上的属性，挂到最外层基座window上啊？ @bailicangdu 
![image](https://user-images.githubusercontent.com/5880014/187813156-d70a6231-dc10-4977-b861-ff4b7925632b.png)
