### ISSUE TITLE
v1.0.0-alpha.7   使用keep-alive 第一次跳转到其他子应用可以， 再跳转回上一个子应用页面，路由的子应用跳转错误

### ISSUE THREAD

**Issue by Lzy328** [jd-opensource/micro-app#567]
## 问题描述
> 问题的具体描述
v1.0.0-alpha.7   使用keep-alive 第一次跳转到其他子应用可以， 再跳转回上一个子应用页面，路由的子应用跳转错误

## 复现步骤
1.点击其他的子应用如：product 是可以正常进入的，从product子应用跳转到order子应用也是可以的
2.从order子应用点击跳转回product时跳转错误，

## 上传截图
> 子应用
![image](https://user-images.githubusercontent.com/51940708/187403670-a68d7353-bb2a-4ff1-ad0d-3d919add8e08.png)
micro
![image](https://user-images.githubusercontent.com/51940708/187403796-24d7c258-f109-4c3a-86ba-72e20367ba09.png)

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。

## 环境信息
- micro-app版本：v1.0.0-alpha.7
- 主应用前端框架&版本：vue3
- 子应用前端框架&版本：vue3
- 构建工具&版本：

**Comment by bailicangdu** [comment]
子应用是vite？

**Comment by Lzy328** [comment]
是的




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年08月30日 17:47 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [micro-zoe/micro-app] v1.0.0-alpha.7   使用keep-alive 第一次跳转到其他子应用可以， 再跳转回上一个子应用页面，路由的子应用跳转错误 (Issue #567) |

vite应用？

**Comment by bailicangdu** [comment]
vite应用暂时没办法

**Comment by bailicangdu** [comment]
等vite沙箱推出才能解决

**Comment by zandko** [comment]
> 等vite沙箱推出才能解决

vite 沙箱大概在几月份推出

**Comment by bailicangdu** [comment]
9月底
