### ISSUE TITLE
子应用的Message.success()弹窗不显示

### ISSUE THREAD

**Issue by SteveCGC** [jd-opensource/micro-app#568]
## 问题描述
> 问题的具体描述

## 复现步骤
1. 主应用：vite+vue3
2. 子应用：webpack+react,组件库是@alifd/next
3. 子应用中执行Message.success(‘保存成功’),无法弹窗

## 上传截图
> 正常
![image](https://user-images.githubusercontent.com/16144832/187581067-213a5541-b20d-47c5-aee1-9fb3d86220e3.png)

> 嵌套到micro-app，没效果，控制台不报错
![image](https://user-images.githubusercontent.com/16144832/187581155-598493f7-8190-4100-8abb-cc87973d52ee.png)

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。

## 环境信息
- micro-app版本："@micro-zoe/micro-app": "1.0.0-alpha.3",
- 主应用前端框架&版本：vite vue3 
- 子应用前端框架&版本：webpack react16
- 构建工具&版本：

**Comment by bailicangdu** [comment]
我本地试了没问题，我的版本是 1.0.0-alpha.7
<img width="364" alt="image" src="https://user-images.githubusercontent.com/20297227/187588930-66dec23d-0055-44d4-b025-1c7bd7e8db50.png">
