### ISSUE TITLE
子应用表格固定列错行问题

### ISSUE THREAD

**Issue by Lemon0613** [jd-opensource/micro-app#569]
## 问题描述
> 主应用Vue3 + ElementPlus + Vite，子应用Vue2 + ElementUI +  webpack
> vue2子应用表格固定左侧列之后，显示错行
> 请问对于这个问题有没有好的解决方法或者建议

## 复现步骤
1.  开启子应用shadowDom，可以解决错行问题，但是ElementUI内置图标均不显示（系统大量用到了ElementUI内置图标）
2.  关闭子应用shadowDom，表格固定列错行
3.  子应用单独运行，无表格错行问题
4. 试了网上百度的解决表格错行方法，均不生效

## 上传截图

<img width="691" alt="image" src="https://user-images.githubusercontent.com/20120126/187584205-bf108063-be9a-445a-a43e-86e073dabd1b.png">

## 环境信息
- micro-app版本：
- 主应用前端框架&版本：Vue3 + ElementPlus + Vite2
- 子应用前端框架&版本：Vue2 + ElementUI +  webpack4
- 构建工具&版本：

**Comment by bailicangdu** [comment]
应该是基座影响了，解决方式：给子应用elementui添加class前缀
