### ISSUE TITLE
样式问题

### ISSUE THREAD

**Issue by TinChak** [jd-opensource/micro-app#57]
问题1：micro-app[name=vue2], micro-app[name=vue2], micro-app[name=vue2] div, micro-app[name=vue2] span, micro-app[name=vue2] applet,
主应用给样式增加 micro-app[name=vue2] 前缀后，改变了样式原有的优先级，导致样式错乱，请问有没有更好的解法？

问题2：如果关闭沙箱的话，问题1没有了，但是会遇到另一个奇怪的问题，里面内容的宽度会逐渐拉升变宽（在自我膨胀，仿佛特效一般）

**Comment by bailicangdu** [comment]
不建议关闭沙箱，根据实际情况手动调整
