### ISSUE TITLE
jquery 项目怎么做为子应用使用？

### ISSUE THREAD

**Issue by biewenwoshishei** [jd-opensource/micro-app#570]

**Comment by bailicangdu** [comment]
如果只有一个页面，直接嵌入就行
```html
<micro-app name='xx' url='xxx.html'></micro-app>
```

**Comment by bailicangdu** [comment]
如果是多页面，不建议使用，因为需要自行解决跳转的问题

**Comment by biewenwoshishei** [comment]
我也是这么做的 控制台报错  但是单独打开这页面是可以运行的
<img width="652" alt="image" src="https://user-images.githubusercontent.com/64004615/187629723-ee2a3045-111c-4323-90e9-15d76eb0275b.png">

**Comment by bailicangdu** [comment]
这个报错是因为没有找到head标签，子应用有线上地址吗，发一下地址看看

**Comment by bailicangdu** [comment]
这个报错是因为解析html失败没有找到head标签，子应用有线上地址吗，发一下地址看看

**Comment by biewenwoshishei** [comment]
没有，jquery是本地的demo   jquery项目本地正常是能跑的

**Comment by biewenwoshishei** [comment]
https://gitee.com/chenminghui_git/micro-app    demo仓库 大佬帮我看下
<img width="517" alt="image" src="https://user-images.githubusercontent.com/64004615/187808897-7313ad27-b32a-490c-b2c5-2dc02da302c2.png">

**Comment by ghost** [comment]
> 

请问【自行解决跳转问题】是什么意思？我们有一个比较老的Vue的多页面应用

**Comment by raoenhui** [comment]
> > 
> 
> 请问【自行解决跳转问题】是什么意思？我们有一个比较老的Vue的多页面应用

多个html页面，相互跳转 ，如`<a href="./aaaa.html">按钮</a>`，micro-app暂时无法拦截
