### ISSUE TITLE
关于公共模块的管理

### ISSUE THREAD

**Issue by qiliangya** [jd-opensource/micro-app#571]
1. 假设把所有公共模块如 请求方法、配置、常量、工具方法等 全部放在基座应用加载 然后通过父传子 给每个子服务使用
2. 单独创建一个PublicService 将上述内容打包成一个js，加载到基座应用 并且配上global， 子应用通过window对象去读取使用

因为有时候不想改到公共部分的时候 构建所有应用， 请问上面哪种方式好一点

**Comment by bailicangdu** [comment]
看你选择，第二种成本低，类似于将这些功能模块放到基座window上的一个对象上

**Comment by fantasticsoul** [comment]
推荐采用[hel-micro](https://github.com/tnfe/hel), 管理[共享模块](https://www.bilibili.com/video/BV15t4y1u7i5/?vd_source=51bc50bf5f860e0d778c49b00d192cee)
