### ISSUE TITLE
vite + vue  子应用 在基座报错 client.ts:70                  [vite] failed to connect to websocket (SyntaxError: Failed to construct 'WebSocket': The URL 'ws://:/vite3/' is invalid.). 

### ISSUE THREAD

**Issue by beyondOurself** [jd-opensource/micro-app#572]
## 问题描述
> 问题的具体描述

vue2 + webpack 为基座; vue3+vite 为子应用.  子应用启动没报错. 但基座一直报 websock 连接失败

## 复现步骤
1.
2.

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。

## 环境信息
- micro-app版本：
- 主应用前端框架&版本： vue2 + webpack
- 子应用前端框架&版本： vue3 + vite
- 构建工具&版本：
主应用用的是 webpack 构建

**Comment by jyliyue** [comment]
我也遇到了同样的问题，兄弟你解决了吗？

**Comment by matteao03** [comment]
#604  我也提了一个 issue

**Comment by pipinet** [comment]
同样的问题。

**Comment by smallk1002** [comment]
有解决么

ws 一直报错

**Comment by lhm005** [comment]
升级1.0beta这个错误没有了

**Comment by dukeL12** [comment]
Vite 启动 WebSocket 服务器的主要目的是为了支持快速的热重载。打包后就不会有这个错误了。

**Comment by ssx1477651687** [comment]
+1
