### ISSUE TITLE
基座是jq+php项目,子应用是react,可以接入micro-app吗

### ISSUE THREAD

**Issue by putao88** [jd-opensource/micro-app#573]

**Comment by bailicangdu** [comment]
1.0版本可以接入 https://micro-zoe.com/docs/1.x/#/zh-cn/start
在浏览器环境执行microApp.start，理论上只需要设置name和url即可
```html
<micro-app name='my-app' url='http://localhost:3000/'></micro-app>
```

**Comment by putao88** [comment]
> 1.0版本可以接入 https://micro-zoe.com/docs/1.x/#/zh-cn/start 在浏览器环境执行microApp.start，理论上只需要设置name和url即可
> 
> ```
> <micro-app name='my-app' url='http://localhost:3000/'></micro-app>
> ```

基座是非esm项目,直接引入会报错

**Comment by bailicangdu** [comment]
非esm环境无法使用，后续会推出一个umd的兼容版本

**Comment by canbaoSama** [comment]
基座我使用Vue3,子应用是php的yii框架，然后对frontend的SiteController添加了跨域配置如下
'corsFilter' => [
    'class' => Cors::class,
    'cors' => [
        // 设置允许的来源，'*'表示接受所有来源
        'Origin' => [ '*' ],
    ],
],

但是除了引入的index.php文件外，其他的css和js等资源都跨域了，有大佬知道怎么处理吗，我找了很多网上资料都没有解决，不会php，但是想要做调研，项目我是用 https://github.com/yiisoft/yii2-app-advanced  做测试的
