### ISSUE TITLE
基座中反向代理配置疑问

### ISSUE THREAD

**Issue by small-dots** [jd-opensource/micro-app#574]
把反向代理的配置放到

把反向代理的配置放到基座

这个反向代理的配置内容 和基座之前的反向代理配置一样吗 @bailicangdu
举例：接入前子应用的配置
`/dev-api': { 
       target: 'http://xx.xx.xx.xx:8081', 
       changeOrigin: true,
       ws: true, 
       pathRewrite: { '^dev-api': '', },
 },
`

如果配置放到基座呢，有什么变化 ，求指导

**Comment by small-dots** [comment]
配置在基座的问题已经解决了 ，但是后期加子应用都需要在基座加代理配置，如果想在子应用补全的话 ，
![image](https://user-images.githubusercontent.com/52172424/188044105-c772c61e-459b-4403-bc2f-6fd1a3c8d3a2.png)

![image](https://user-images.githubusercontent.com/52172424/188044161-5192b544-05e4-4039-afeb-11223e6a8dc6.png)
报跨域怎么解决

**Comment by bailicangdu** [comment]
子应用请求接口的代码贴一下

**Comment by small-dots** [comment]
> 子应用请求接口的代码贴一下

![image](https://user-images.githubusercontent.com/52172424/188067099-f9ec9804-24ac-4339-9e03-8da3d82b8d5a.png)
这是接口请求地址
下面是baseurl
![image](https://user-images.githubusercontent.com/52172424/188067155-aca4bc31-f782-4486-9181-7f0f8d61b6a0.png)

**Comment by small-dots** [comment]
> > 子应用请求接口的代码贴一下
> 
> ![image](https://user-images.githubusercontent.com/52172424/188067099-f9ec9804-24ac-4339-9e03-8da3d82b8d5a.png) 这是接口请求地址 下面是baseurl ![image](https://user-images.githubusercontent.com/52172424/188067155-aca4bc31-f782-4486-9181-7f0f8d61b6a0.png)
 完整地址就是localhost:4010/dev-api/api/sjzt/xtsj/yh/yzm   api/sjzt/xtsj/yh/yzm是实际接口地址

**Comment by bailicangdu** [comment]
4010是子应用还是基座端口？

**Comment by small-dots** [comment]
> 4010是子应用还是基座端口？

子应用

**Comment by bailicangdu** [comment]
既然请求指向了子应用的端口，反向代理保留在子应用中设置就行了

**Comment by small-dots** [comment]
> 既然请求指向了子应用的端口，反向代理保留在子应用中设置就行了



> 配置在基座的问题已经解决了 ，但是后期加子应用都需要在基座加代理配置，如果想在子应用补全的话 ， ![image](https://user-images.githubusercontent.com/52172424/188044105-c772c61e-459b-4403-bc2f-6fd1a3c8d3a2.png)
> 
> ![image](https://user-images.githubusercontent.com/52172424/188044161-5192b544-05e4-4039-afeb-11223e6a8dc6.png) 报跨域怎么解决

是啊  这个代理就是在子应用中配置的  ，配置以后报跨域啊 

再理一下  

基座  端口是  3000       子应用 4010  ，现在采取的方式是在子应用中接口地址写完整的子应用域名+接口地址  ，也就是http://localhost:4010/dev-api/api/,,,,,,

然后继续在子应用配置代理 ，
![Uploading image.png…]()
结果报跨域

**Comment by bailicangdu** [comment]
能提供个demo看一下吗

**Comment by small-dots** [comment]
没事了 谢谢 ，还是统一将代理配置在基座中吧，
