### ISSUE TITLE
UmiJS v4兼容性

### ISSUE THREAD

**Issue by shamur** [jd-opensource/micro-app#577]
问题：
![image](https://user-images.githubusercontent.com/17883846/188112631-75ddf0c4-ec7c-4817-895f-1cab28c5ff46.png)
![image](https://user-images.githubusercontent.com/17883846/188112782-7d3f5485-b316-48e0-827a-44f8e36e9c18.png)

基座：
"@micro-zoe/micro-app": "^0.8.10",
"umi": "^4.0.17"

子应用：
"umi": "^4.0.17"

是不是跟UmiJS 4.x有兼容性问题？还是说我的配置有问题？ 项目不是很复杂，只想走一个基础的Demo，子应用用UmiJS 3.x可以跑起来。

**Comment by shamur** [comment]
![image](https://user-images.githubusercontent.com/17883846/188113848-7cc28bec-70f0-499b-b3b6-c86d417bec0f.png)
![image](https://user-images.githubusercontent.com/17883846/188114079-8ddf7ec2-06ca-4108-b64d-e75f9571da79.png)
针对最后一点，我在子应用的.umirc.ts中设置了如上图的配置，因为看Umijs 4去掉了devServer配置了。

**Comment by bailicangdu** [comment]
开发环境确实有问题，生产环境正常运行，我们会尝试修复这个问题，感谢反馈。umi自带了qiankun插件，可以用官方的微前端方案接入

**Comment by jinjinwa** [comment]
这个有方案了么
