### ISSUE TITLE
angular-14作为子应用无法加载，Error: NG04002: Cannot match any routes

### ISSUE THREAD

**Issue by punyfish** [jd-opensource/micro-app#579]
## 问题描述
> 问题的具体描述
无法加载angular-14框架的子应用。
fork自官网的demo，也是如此。

## 复现步骤
1.启动main-angular14的主应用
2.启动child-angular14子应用
3.启动angular11子应用
4.启动sidebar子应用
5.点击左侧的child-angular14菜单，或者直接输入/main-angular14/app-angular14
6.报错：Error: NG04002: Cannot match any routes. URL Segment: 'main-angular14/app-angular14'

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。
![image](https://user-images.githubusercontent.com/38232683/188263059-72ad56cd-3433-40a4-9cd2-3fc6025a8cd5.png)

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。
https://github.com/punyfish/micro-app-demo.git

## 环境信息
- micro-app版本：
- 主应用前端框架&版本：angular14 或者其他任意框架
- 子应用前端框架&版本：angular14
- 构建工具&版本：angular-cli@14.2.1（webpack@^5.30.0  webpack-dev-server": "^4.0.0）

**Comment by punyfish** [comment]
main-angular14和child-angular14的均是copy自main-apps和child-apps中的angular11，angular框架升级到了14。

**Comment by bailicangdu** [comment]
安装1.0版本的micro-app试一下呢 npm i @micro-zoe/micro-app@alpha --save

**Comment by punyfish** [comment]
按照您说的：npm i @micro-zoe/micro-app@alpha --save ，问题解决了

**Comment by punyfish** [comment]
初次**通过路由跳转**到angular14的子应用还是会报错，Error: NG04002: Cannot match any routes。错误信息如下
![micro-app-bug](https://user-images.githubusercontent.com/38232683/188350209-62e7968c-da9d-4a5a-951c-b77dff4c9354.png)
刷新浏览器，或者浏览器直接打开/main-angular14/app-angular14子应用的完整地址，也不会报错。

**Comment by punyfish** [comment]
还有一个问题。只加载了一个side-bar子应用，但是报错重复加载了。
![app-conflict](https://user-images.githubusercontent.com/38232683/188351449-3bc06114-1f36-4676-b223-e2f0e3e56b17.png)

**Comment by punyfish** [comment]
再次补充：@micro-zoe/micro-app@alpha 这个版本，angular14作为基座，通过路由跳转（点击左侧sidebar中的菜单）子应用（angular14，angular11）报错，Error: NG04002: Cannot match any routes。
跳转到child-vue3同样问题，报错：vue-router.esm-bundler.js?6c02:72 [Vue Router warn]: No match found for location with path "/main-angular14/app-vue3?appname-sidebar=/child/sidebar/"

**Comment by punyfish** [comment]
通过测试发现：
一、@micro-zoe/micro-app@alpha 版本
1.  vue3作为基座应用，angular-11、angular-14作为子应用是没有问题的。
2.  angular-14作为基座应用，其它子应用（ng14、ng11、vue3）都报错路由的问题。
3. angular-11作为基座应用，其它子应用（ng14、ng11、vue3）都报错路由的问题。

二、@micro-zoe/micro-app@latest
1.angular14作为子应用有问题

**Comment by bailicangdu** [comment]
感谢反馈，我们已经复现了问题，会在后续进行修复
