### ISSUE TITLE
🐞 Bug: micro-app运行不起来

### ISSUE THREAD

**Issue by llbiao** [jd-opensource/micro-app#58]
![image](https://user-images.githubusercontent.com/32304163/130576025-7b8db74a-b6b8-4d15-a47e-c164b19f825d.png)

直接运行examples的main应用也不行

![image](https://user-images.githubusercontent.com/32304163/130577113-861c413c-4ad1-4b14-a072-56863e510417.png)

**Comment by bailicangdu** [comment]
单独进入每个仓库执行yarn安装试一下

**Comment by llbiao** [comment]
所有项目都npm install了，依然没法运行
![image](https://user-images.githubusercontent.com/32304163/130578889-e09f8881-c013-403f-8da3-3c804dd8aa56.png)

**Comment by bailicangdu** [comment]
在根目录执行yarn安装后，运行yarn build:watch

**Comment by bailicangdu** [comment]
然后再进入main-xx运行

**Comment by llbiao** [comment]
> 在根目录执行yarn安装后，运行yarn build:watch

可以了，感谢！请问子应用能支持angular1.x + glup的项目接入吗？

**Comment by bailicangdu** [comment]
> > 在根目录执行yarn安装后，运行yarn build:watch
> 
> 可以了，感谢！请问子应用能支持angular1.x + glup的项目接入吗？

可以的

**Comment by llbiao** [comment]
> > > 在根目录执行yarn安装后，运行yarn build:watch
> > 
> > 
> > 可以了，感谢！请问子应用能支持angular1.x + glup的项目接入吗？
> 
> 可以的

没有angular的接入文档吗？
![image](https://user-images.githubusercontent.com/32304163/130590051-2cc2c2e9-98b0-458e-9510-15ac4c89be69.png)

**Comment by bailicangdu** [comment]
路由前缀和环境判断，参考文档：https://zeroing.jd.com/micro-app/docs.html
