### ISSUE TITLE
globalKeyToBeCached 优化

### ISSUE THREAD

**Issue by lishaobos** [jd-opensource/micro-app#580]
## 背景
> 描述您希望改进的问题。

咱们的 globalKeyToBeCached 没有包含 document，在大量操作 dom 的情况下，加上 document 性能会更好，是有其他的考虑吗？

## 期望的效果

globalKeyToBeCached 包含 document

**Comment by bailicangdu** [comment]
因为document非常特殊，不能进行缓存

**Comment by lishaobos** [comment]
@bailicangdu 你好，可以请教下是因为什么不能进行缓存吗。只是我自己感兴趣，如果太过复杂就不用说了。

**Comment by bailicangdu** [comment]
因为要绑定元素作用域
<img width="851" alt="image" src="https://user-images.githubusercontent.com/20297227/188404991-8adfea76-2e84-40a1-bd92-dbbf79ce763f.png">

**Comment by bailicangdu** [comment]
你点醒我了，[v1.0.0-alpha.2](https://github.com/micro-zoe/micro-app/releases/tag/v1.0.0-alpha.2)版本后增加proxyDocument，document可以放入globalKeyToBeCached缓存中了，thx

**Comment by bailicangdu** [comment]
😂

**Comment by lishaobos** [comment]
哈哈，感谢大佬的回复，这个加与不加，性能差距实在太大了。
