### ISSUE TITLE
Is possible to render multiple components of the same micro app on the same page simultaneously?

### ISSUE THREAD

**Issue by Relaxe111** [jd-opensource/micro-app#581]
Hi, i have a use case when i need to render from the same micro app multiple components on the same page is that possible?
Can I use in-memory route (react,vue) for this? 
<img width="538" alt="image" src="https://user-images.githubusercontent.com/40892030/188419413-faf77f4a-b1ac-4089-9fbf-d5a9ec35e1a9.png">
thank you  in advance.

**Comment by bailicangdu** [comment]
Components of the same micro app can be rendered at the same time, but each app is unique. For example, component1 & component2 belong to micro-app-2, then we have to render micro-app-2  twice

**Comment by Relaxe111** [comment]
Nice. Is there any consideration to take related to the fact that most of micro-apps are vite-react apps and some of the are vite-svelte apps?

**Comment by bailicangdu** [comment]
We are working hard for vite

**Comment by Relaxe111** [comment]
thank-you for quick answers. Closing issue
