### ISSUE TITLE
在主应用中配置子应用页面的路由，点击跳转到对应的子页面，当加载了第一个子应用页面后再去点击主应用中另一个子页面的路由，子应用跳转后子应用页面还停留在上一个子应用页面。

### ISSUE THREAD

**Issue by biewenwoshishei** [jd-opensource/micro-app#583]
目前我的解决办法是主应用给子应用传递路由地址,然后子应用自己跳转; 
主应用的菜单路径已经跟子应用的路径匹配上
想要的是直接在主应用左侧菜单栏中点击对应的菜单跳转到对应子应用的页面,不用传参处理

**Comment by bailicangdu** [comment]
你说的功能在micro-app1.0版本才有，0.x版本不支持

**Comment by biewenwoshishei** [comment]
我不知道我描述的够不够清 
<img width="388" alt="WeChat29158634b4255bf87d1d29566f11bb84" src="https://user-images.githubusercontent.com/64004615/188797751-75632295-455f-4667-b7c5-8faa1637316a.png">

**Comment by bailicangdu** [comment]
https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/jump

**Comment by biewenwoshishei** [comment]
我这个子应用是同一个子应用, 多个菜单对应同一个子应用的多个路由

**Comment by tuzhu008** [comment]
> 我这个子应用是同一个子应用, 多个菜单对应同一个子应用的多个路由

我目前的处理办法是，将每个左侧的菜单都当做一个新的子应用。

**Comment by lkiarest** [comment]
> > 我这个子应用是同一个子应用, 多个菜单对应同一个子应用的多个路由
> 
> 我目前的处理办法是，将每个左侧的菜单都当做一个新的子应用。

好像没有什么更方便的方式了
