### ISSUE TITLE
基座应用嵌子应用页面，打开一直报错，也无法渲染

### ISSUE THREAD

**Issue by bing127** [jd-opensource/micro-app#584]
## 问题描述
> 基座应用嵌子应用页面，打开一直报错，也无法渲染

## 上传截图
> ![image](https://user-images.githubusercontent.com/31166183/189050901-125de7eb-251d-4fb1-bcbb-294a4a827266.png)

**Comment by bailicangdu** [comment]
配置inline模式看一下具体哪行的报错，https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/configure?id=inline

**Comment by bailicangdu** [comment]
或者提供一个可以复现的demo？
