### ISSUE TITLE
刷新孙子页面变成空白

### ISSUE THREAD

**Issue by piczi** [jd-opensource/micro-app#586]
## 问题描述
> 在基座项目下渲染子项目，子项目也渲染一个子项目，正常跳转可以显示，但是刷新页面会变成空白。

## 复现步骤
1.react 项目使用hash路有作为基座项目，代号为A
2.起一个react项目同样用hash路由作为子项目B
3. 再起一个react项目C作为B的子项目，B作为A的子项目进行渲染，正常情况下可以打开，但点击浏览器刷新，页面空白了。

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。

## 环境信息
- micro-app版本：0.8.5
- 主应用前端框架&版本：react17 + umi v3.5.23
- 子应用前端框架&版本：react17 + umi v3.5.23
- 构建工具&版本：umi v3.5.23

**Comment by bailicangdu** [comment]
路由没有匹配，自己检查一下吧
