### ISSUE TITLE
子应用路径与官网例子不符，使用参数形式包含子应用名称，如?app-vue2-micro-app=%2F%23%2Fhome

### ISSUE THREAD

**Issue by Star-live** [jd-opensource/micro-app#587]
## 问题描述
> 问题的具体描述
在跳转到子应用的路径时，url总是会进行自动跳转加上一个后缀。
比如我在前端输入的URL为：http://local.gf.com.cn:7000/vue2/state
回车后URL自动变为：http://local.gf.com.cn:7000/vue2/state?app-vue2-micro-app=%2F%23%2Fhome（该URL中vue2-micro-app是子应用名称，state与home是子应用的路由）
该现象与官网所描述的[路由](https://zeroing.jd.com/micro-app/docs.html#/zh-cn/route)不符合：
![image](https://user-images.githubusercontent.com/52146433/189109037-118b4a55-4f4d-4b20-9ab5-053888284fb7.png)

## 复现步骤
1. 按官网描述进行微前端改造
2. 主应用与子应用都采用history路由
3. 主应用控制子应用显示采用 router-link

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。
![image](https://user-images.githubusercontent.com/52146433/189108585-4e47b1b2-55fe-4c15-89ee-3f5ab0a1408a.png)

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。
https://github.com/Star-live/microApp-demo
## 环境信息
- micro-app版本：1.0.0-alpha.1
- 主应用前端框架&版本：vue 2.5.2
- 子应用前端框架&版本：vue2 (node 10.24.1),  vue3 (node 14.19.3), react16 (node 14.19.3), react17 (node 14.19.3). 
- 构建工具&版本：node 10.24.1

**Comment by bailicangdu** [comment]
你说的文档是0.x版，用的是1.0版本，参考 https://micro-zoe.com/docs/1.x/#/zh-cn/router

**Comment by Star-live** [comment]
非常感谢您的回复，我按照1.0版本的文档 https://micro-zoe.com/docs/1.x/#/zh-cn/transfer 尝试关闭虚拟路由系统，具体如下所示：
```javascript
import microApp from '@micro-zoe/micro-app'

microApp.start({
  'disable-memory-router': true,
  'disable-patch-request': true
})
```
发现遇到了下面一个奇怪的问题，录屏如下所示：
![tt0 top-805408](https://user-images.githubusercontent.com/52146433/189259351-b254cd0d-417e-4f78-b511-e58e2dba0904.gif)

复现路径：
1. 从主应用第一次跳转到子应用，子应用路由路径无误：http://local.gf.com.cn:7000/vue2/home
2. 回到主应用，再次跳转到子应用，子应用路由路径为虚拟路由的路径：http://local.gf.com.cn:7000/vue2/home?vue2-micro-app=%2Fvue2

**Comment by bailicangdu** [comment]
升级到最新版1.0.0-alpha.8试一下

**Comment by Star-live** [comment]
嗯嗯，我已经升级到最新的版本了，但还是会有这个问题，依赖如下所示：
```
  "dependencies": {
    "@micro-zoe/micro-app": "^1.0.0-alpha.8",
    "vue": "^2.5.2",
    "vue-router": "^3.0.1"
  },
```
具体仓库：https://github.com/Star-live/microApp-demo
其他问题：
- 在打开虚拟路由系统时，我给子应用设置keep-alive，可以保留子应用的路由及状态；
- 关闭虚拟路由系统后，即使设置keep-alive，无法保留原有的功能，子应用路由和状态都会消失；

**Comment by bailicangdu** [comment]
感谢反馈，问题已修复，更新到[1.0.0-alpha.9](https://github.com/micro-zoe/micro-app/releases/tag/v1.0.0-alpha.9)即可解决
