### ISSUE TITLE
从0.8.10 升级至 1.0.0-alpha.9，引入第三方库报错

### ISSUE THREAD

**Issue by yuristar12** [jd-opensource/micro-app#588]
## 问题描述
> 从0.8.10 升级至 1.0.0-alpha.9，第三方库报错

## 上传截图
<img width="874" alt="image" src="https://user-images.githubusercontent.com/75759471/189538041-4a62f2d5-2c20-496f-bfe5-47bd8f57e094.png">

## 环境信息
- micro-app版本：1.0.0-alpha.9
- 主应用前端框架&版本：vue ^2.7.0
- 子应用前端框架&版本：vue ^2.7.0
- 构建工具&版本：webpack

**Comment by bailicangdu** [comment]
第三方库是哪个？

**Comment by yuristar12** [comment]
> 第三方库是哪个？

精简的 仓库地址是这个 https://github.com/yuristar12/microAppTest.git 麻烦看下，谢谢！
