### ISSUE TITLE
子应用naive-ui部分样式丢失

### ISSUE THREAD

**Issue by jiakangning** [jd-opensource/micro-app#589]
## 问题描述
> 问题的具体描述 嵌套层级的微前端 （注：vue3的样式隔离已关闭）
基建应用：vue3+naiveui （上层父应用）
父应用1（父应用为：基建应用）：vue2+element-ui （未关闭样式隔离，element弹窗样式暂未出现问题）
子应用（父应用为：父应用1）：vue3+naiveui （已关闭样式隔离）
## 复现步骤
使用prompt或者dialog概率丢失样式级效果 （表现如下：）

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。
![932ECAC9-D368-4cc7-953E-BABA5042E952](https://user-images.githubusercontent.com/34635641/189800097-be9afba2-f2c0-4f48-b990-7ca220514f9c.png)

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。
暂无法提供
## 环境信息
- micro-app版本：0.8.6
- 主应用前端框架&版本：参考上述
- 子应用前端框架&版本：参考上述
- 构建工具&版本：vue-cli 基于webpack5.x

**Comment by jiakangning** [comment]
@bailicangdu   对于插入body类型的组件（dialog，message等） naiveui 不能像 element-ui一样被插入到所在mciro元素下的micro-app-body里（真实情况是堆积在父应用所在的_”body_“（**当父应用也作为子应用时，此时body变为micro-app-body**）里） 而导致切换应用时，元素样式丢失从而无法正确的被关闭（消失），表现为：会堆积在所在父应用的”body“（同上）上，造成整体布局出现问题

**Comment by bailicangdu** [comment]
升级到1.0试一下 https://micro-zoe.com/docs/1.x/#/zh-cn/transfer
