### ISSUE TITLE
从0.8.10 升级至 1.0.0-alpha.9  子应用antd抽屉组件无法渲染

### ISSUE THREAD

**Issue by sogud** [jd-opensource/micro-app#591]
## 问题描述
> 问题的具体描述

## 复现步骤
1. 0.8.10 版本没问题，1.0.0-alpha.9 无法渲染抽屉组件，子应用样式渲染至主应用样式上。

## 复现仓库
vue2 主应用
react17 子应用
https://github.com/sogud/micro-app

## 环境信息
- micro-app版本：1.0.0-alpha.9
- 主应用前端框架&版本：vue2
- 子应用前端框架&版本：react17
- 构建工具&版本：官方仓库

**Comment by bailicangdu** [comment]
试了一下，用的antd最新版本v4.23.1，react16、17都没问题，能提供个demo看一下吗

**Comment by sogud** [comment]
> 试了一下，用的antd最新版本v4.23.1，react16、17都没问题，能提供个demo看一下吗


可以查看此运行示例
vue2 主应用
react17 子应用
https://github.com/sogud/micro-app

**Comment by 1021683053** [comment]
跟我一样，我刚想提供issues

**Comment by hlskysong** [comment]
micro-zoe/micro-app  1.0.0-alpha.7  有同样的问题

**Comment by dandelion-Chen** [comment]
@bailicangdu  请问有预计在哪个版本会fix这个问题嘛

**Comment by bailicangdu** [comment]
问题已经定位到，但是解决这个问题又会导致element-ui出错，我们还在研究更好的方案

**Comment by jiaozhiye** [comment]
这个问题现在有解决方案吗
