### ISSUE TITLE
disable-memory-router 的问题

### ISSUE THREAD

**Issue by xiangxinji** [jd-opensource/micro-app#593]
现在的虚拟路由功能是没弄好吗 ?  我发现一开启这玩意就开始无限循环自动跳转

**Comment by bailicangdu** [comment]
环境信息报一下呢，基座、子应用是什么框架，版本是多少？

**Comment by xiangxinji** [comment]
主应用  vite 
"vite": "^2.5.10", 
"vue-router": "^4.0.11",
"@micro-zoe/micro-app": "^1.0.0-alpha.9",
 "vue": "3.2.16",

子应用 vuecli
"vue": "3.2.16",
"vue-router": "^4.0.11",

**Comment by xiangxinji** [comment]
disable-memory-router = false , 主应用就会在url 上追加一个 app名称=/ , 然后打开一个可用页面之后,就无限进行跳转,并且追加
http://localhost:8001/setup/setup/dashboard-manager/preview?id=ssss&setup=%2Fredirectectectectectectect  这种错乱的参数.  并且无限跳转.

**Comment by xiangxinji** [comment]
然后我子应用的行为包括 , 上次提到的应用缓存的机制, 需要自己手动去跳转的行为. 
```js
  if (!isMicro) return;
  const appName = window.__MICRO_APP_NAME__;
  window.addEventListener("appstate-change", function (e: any) {
    if (e.detail.appState === "aftershow") { 
      const p = window.location.pathname;
      const path = p.substring(appName ? appName.length + 1 : 0);
      const query = convertHrefSearch();
      if (window.$router) window?.$router.replace({ path: `/redirect${path}`, query });
    }
  });
```

**Comment by bailicangdu** [comment]
能提供一个简易的demo帮助复现问题吗

**Comment by xiangxinji** [comment]
这里我大概处理了一下, 好像是  keep-alive 的问题, 如果keep-alive 并且定义了 "appstate-change" 事件, 他会重复触发. 如果我把子应用中的 addEventListener 给删掉, 这个虚拟路由是没有问题的

**Comment by xiangxinji** [comment]
是我这段逻辑有问题, 在其中进行 replace 导致重新进行了 appstate-change , 一直无限循环 . 不过请问一下还有什么比较合适的方式让不执行这段逻辑after-show吗? 当前这个路由一直锁定在这个子应用下, 是不是不应该是 after-show 的流程了?

**Comment by xiangxinji** [comment]
还有就是请问一下,什么情况下虚拟路由会不生效呢? 我使用虚拟路由集成到系统里面, 完全不行, appName=/ 一直都是这样, 子应用路由跳转的url 会和之前一样, 放在虚拟路由参数的前面. 我自定义了一个示例项目却又重现不出来这个问题

**Comment by bailicangdu** [comment]
可以关闭虚拟路由，采用以前的baseroute配置路由

**Comment by bailicangdu** [comment]
> 是我这段逻辑有问题, 在其中进行 replace 导致重新进行了 appstate-change , 一直无限循环 . 不过请问一下还有什么比较合适的方式让不执行这段逻辑after-show吗? 当前这个路由一直锁定在这个子应用下, 是不是不应该是 after-show 的流程了?

应该是之前路由跳转的逻辑是针对浏览器的，放在虚拟路由里被拦截了，两者有差异，导致冲突

**Comment by xiangxinji** [comment]
> 采用

但是关闭虚拟路由依然会存在那个 baseRoute 丢失的问题.

**Comment by xiangxinji** [comment]
> > 采用
> 
> 但是关闭虚拟路由依然会存在那个 baseRoute 丢失的问题.

或者说目前有比较好解决这个的方案吗, 除开就是之前文档提供的那串代码的, 这个问题已经卡很久了

**Comment by bailicangdu** [comment]
猜测是vue3的路由冲突导致的，baseRoute确实无法解决这个冲突，只有虚拟路由系统才可以，但是现在虚拟路由也出问题了，应是代码逻辑冲突了，我现在看不到代码，无法定位

**Comment by xiangxinji** [comment]
> 猜测是vue3的路由冲突导致的，baseRoute确实无法解决这个冲突，只有虚拟路由系统才可以，但是现在虚拟路由也出问题了，应是代码逻辑冲突了，我现在看不到代码，无法定位

我尽可能按照项目中的配置来还原一个实例项目,看能不能复现出项目中的异常结果. 还有就是虚拟路由的这个 after-show 和 before-show 应该是要改的吧 ?

**Comment by bailicangdu** [comment]
replace的作用是什么？

**Comment by bailicangdu** [comment]
原因猜测：replace会让基座的vue页面重新渲染，导致micro-app被重新卸载和挂载，就你看到的`appstate-change`事件被频繁触发，这种情况以前遇到过，原因是根据路由的path设置了key，导致每次路由变化都会导致整个页面被卸载并重新渲染，即便只是修改了浏览器的query参数 `<router-view :key="$route.path"></router-view>`

**Comment by xiangxinji** [comment]
> 原因猜测：replace会让基座的vue页面重新渲染，导致micro-app被重新卸载和挂载，就你看到的`appstate-change`事件被频繁触发，这种情况以前遇到过，原因是根据路由的path设置了key，导致每次路由变化都会导致整个页面被卸载并重新渲染，即便只是修改了浏览器的query参数 `<router-view :key="$route.path"></router-view>`

哦哦， 找到了主应用中确实有这个 vue-router key 的情况， 谢谢
