### ISSUE TITLE
vite子应用打包后发布在测试服务器子应用不生效，本地跑没问题

### ISSUE THREAD

**Issue by biewenwoshishei** [jd-opensource/micro-app#594]
测试服务器显示自应用未加载
<img width="634" alt="image" src="https://user-images.githubusercontent.com/64004615/190844569-a09d3afd-cbec-41e5-a3fc-3887e5c137f7.png">

**Comment by bailicangdu** [comment]
这个问题是请求html出错，跨域设置了吗？

**Comment by biewenwoshishei** [comment]
子应用（9000/child）与主应用(9000/main)是在同一个端口下 路径不同  跨越也设置了    主应用中给子应用的url 是(9000). 现在是子应用未启动

**Comment by biewenwoshishei** [comment]
未报错  子应用主应用都是vite项目

**Comment by bailicangdu** [comment]
可能是url配置错了

**Comment by bailicangdu** [comment]
url设置的是什么

**Comment by biewenwoshishei** [comment]
<img width="1009" alt="image" src="https://user-images.githubusercontent.com/64004615/190961435-3d8cc07c-2b99-4128-965c-a4ee33c35ed6.png">
<img width="614" alt="image" src="https://user-images.githubusercontent.com/64004615/190961479-ea484400-ec2e-42e3-8b1c-1d2b630beaad.png">

**Comment by biewenwoshishei** [comment]
主应用的url 是localhost:9000/main/   子应用的url是localhost:9000/page/ 
<img width="400" alt="image" src="https://user-images.githubusercontent.com/64004615/190961671-5a7a54f5-d1e5-41e5-ae5c-3a467d1a3cf3.png">

**Comment by bailicangdu** [comment]
> <img alt="image" width="1009" src="https://user-images.githubusercontent.com/64004615/190961435-3d8cc07c-2b99-4128-965c-a4ee33c35ed6.png">
> 
> <img alt="image" width="614" src="https://user-images.githubusercontent.com/64004615/190961479-ea484400-ec2e-42e3-8b1c-1d2b630beaad.png">

这个地址有问题吧，如果子应用在child文件夹，应该是9000/child开头，你的nginx配置发一下看看呢

**Comment by biewenwoshishei** [comment]
上面报错问题已经解决了 在vite.config.js 中设置base路径为 htpp:localhost:9000/page 

> > <img alt="image" width="1009" src="https://user-images.githubusercontent.com/64004615/190961435-3d8cc07c-2b99-4128-965c-a4ee33c35ed6.png">
> > <img alt="image" width="614" src="https://user-images.githubusercontent.com/64004615/190961479-ea484400-ec2e-42e3-8b1c-1d2b630beaad.png">
> 
> 这个地址有问题吧，如果子应用在child文件夹，应该是9000/child开头，你的nginx配置发一下看看呢

我们这配置的是子应用是page文件下的路径 所以开头是page 而不是child  child只是表示是子应用

**Comment by biewenwoshishei** [comment]
新的问题 打包后的vite 子应用中 pinia  不识别   代理后的地址为 http：localhost：9000/page  直接访问9000/page是正常的 但是访问微前端的子应用页面 就提示
<img width="951" alt="image" src="https://user-images.githubusercontent.com/64004615/191019356-02ed13ab-947c-47ac-b3b5-ef78a0d8e988.png">

<img width="444" alt="image" src="https://user-images.githubusercontent.com/64004615/191019510-5906cf59-f5bc-4e24-aefc-2fdb66713ff1.png">

**Comment by biewenwoshishei** [comment]
只有在微前端环境才会报这种错误
