### ISSUE TITLE
Vue3+vite 样式隔离没生效

### ISSUE THREAD

**Issue by chinaSoftMobile** [jd-opensource/micro-app#595]
## 问题描述
> 父应应用
```
   <div class="child2">
      我是父亲首页123
    </div>
 <micro-app  inline disablesandbox name='appname-vite'  url='http://localhost:8081/child/vite/'></micro-app>
.child2 {
  color: green;
}
```

>子应用
```
 <div class="child2">
    我是儿子2
  </div>
  <style scoped>
.child2{
  color: red;
}
</style>
```

## 上传截图
> 
![image](https://user-images.githubusercontent.com/81662974/190945286-1a273b85-94d7-468f-b95c-c197934986b1.png)

## 复现仓库
> git@github.com:chinaSoftMobile/vue-vite.git

## 环境信息
- micro-app版本：
- 主应用前端框架&版本：vue3(3.2.25) 
- 子应用前端框架&版本：(0.8.10)
- 构建工具&版本：vite (2.7.2)

**Comment by bailicangdu** [comment]
vite子应用不支持样式隔离
