### ISSUE TITLE
alpha版本的文档在哪呀，我不太确定alpha版本的api有哪些变化，官网没翻到alpha版本的文档和说明

### ISSUE THREAD

**Issue by Huansheng1** [jd-opensource/micro-app#597]
alpha版本的文档在哪呀，我不太确定alpha版本的api有哪些变化，官网没翻到alpha版本的文档和说明

**Comment by Valar103769** [comment]
没发布到npm 吧, 你也下载不了啊 https://www.npmjs.com/package/@micro-app/plugin-deploy-command

**Comment by bailicangdu** [comment]
https://micro-zoe.com/docs/1.x/#/zh-cn/start

**Comment by bailicangdu** [comment]
<img width="1639" alt="image" src="https://user-images.githubusercontent.com/20297227/190969667-7acd27be-5a36-425d-a4a9-d161a26bf46c.png">
