### ISSUE TITLE
vite子应用打包后在微前端环境不生效报错，通过网络请求看到子应用已加载。

### ISSUE THREAD

**Issue by biewenwoshishei** [jd-opensource/micro-app#598]
<img width="732" alt="image" src="https://user-images.githubusercontent.com/64004615/191158349-32726788-c13d-49d6-9990-c142f1e7eee5.png">

**Comment by bailicangdu** [comment]
vite.config.js的配置发一下看看呢

**Comment by biewenwoshishei** [comment]
`import { fileURLToPath, URL } from 'url'
import { writeFileSync } from 'fs'
// mock服务
// import { viteMockServe } from 'vite-plugin-mock'
import { defineConfig, loadEnv, } from 'vite'
import vue from '@vitejs/plugin-vue'
import vueJsx from '@vitejs/plugin-vue-jsx'
import AutoImport from 'unplugin-auto-import/vite'
import Components from 'unplugin-vue-components/vite'
import path, { join } from 'path'
import { ElementPlusResolver } from 'unplugin-vue-components/resolvers'
const envResolve = (mode: string, env: string) => {
  return loadEnv(mode, process.cwd())[env];
}
export default ({ mode }: any) => defineConfig({
  // base: envResolve(mode, 'VITE_PUBLISH_PATH'),
  base: `http://localhost:9000/page`,
  css: {
    preprocessorOptions: {
      scss: {
        // 按需配置自定义的主题色-- 全局配置须在main.ts中一次性导入
        //additionalData: `@use "@/theme/element.scss" as *;`,
      },
    },
  },
  plugins: [
    (function () {
      let basePath = '';
      return {
        name: 'page',
        apply: 'build',
        configResolved(config) {
          basePath = `${config.base}${config.build.assetsDir}/`;
        },
        writeBundle(options, bundle) {
          const filterChunk = ["lodash-unified"]
          for (const chunkName in bundle) {
            if (filterChunk.includes(chunkName)) {
              continue;
            }
            if (Object.prototype.hasOwnProperty.call(bundle, chunkName)) {
              const chunk = bundle[chunkName];
              // console.log(chunk);
              if (chunk.fileName && chunk.fileName.endsWith('.js')) {
                console.log(chunk.code);

                try {
                  chunk.code = chunk.code.replace(
                    /(from|import\()(\s*['"])(\.\.?\/)/g,
                    (all, $1, $2, $3) => {

                      console.log(all, 'all=====================');
                      console.log($1, '1=====================');
                      console.log($2, '2=====================');
                      console.log($3, '3=====================');
                      console.log(all.replace($3, new URL($3, basePath)));

                      return all.replace($3, new URL($3, basePath));
                    },
                  );
                } catch (error) {
                  console.log(error)
                }
                const fullPath = join(options.dir, chunk.fileName);
                writeFileSync(fullPath, chunk.code);
              }
            }
          }
        },
      };
    })(),
    vue(),
    vueJsx()
  ],
  resolve: {
    alias: {
      '@': fileURLToPath(new URL('./src', import.meta.url))
    }
  },
  build: {  // 构建包时使用
    // sourcemap: true,
    // target: 'modules',
    outDir: 'page', //指定输出路径
    assetsDir: 'assets', // 指定生成静态资源的存放路径
    chunkSizeWarningLimit: 1500,   ///块大小警告的限制（以 kbs 为单位）。
    rollupOptions: {  //分解块，将大块分解成更小的块
      output: {
        manualChunks(id) {
          if (id.includes('node_modules')) {
            return id.toString().split('node_modules/')[1].split('/')[0].toString();
          }
        }
      }
    }
  },
  optimizeDeps: {
    include: [
      'vue',
      'element-plus/es',
      'element-plus/es/components/form/style/index',
      'element-plus/es/components/radio-group/style/index',
      'element-plus/es/components/radio/style/index',
      'element-plus/es/components/checkbox/style/index',
      'element-plus/es/components/checkbox-group/style/index',
      'element-plus/es/components/switch/style/index',
      'element-plus/es/components/time-picker/style/index',
      'element-plus/es/components/date-picker/style/index',
      'element-plus/es/components/col/style/index',
      'element-plus/es/components/form-item/style/index',
      'element-plus/es/components/alert/style/index',
      'element-plus/es/components/breadcrumb/style/index',
      'element-plus/es/components/select/style/index',
      'element-plus/es/components/input/style/index',
      'element-plus/es/components/breadcrumb-item/style/index',
      'element-plus/es/components/tag/style/index',
      'element-plus/es/components/pagination/style/index',
      'element-plus/es/components/table/style/index',
      'element-plus/es/components/table-column/style/index',
      'element-plus/es/components/card/style/index',
      'element-plus/es/components/row/style/index',
      'element-plus/es/components/button/style/index',
      'element-plus/es/components/menu/style/index',
      'element-plus/es/components/sub-menu/style/index',
      'element-plus/es/components/menu-item/style/index',
      'element-plus/es/components/option/style/index',
      '@element-plus/icons-vue',
      'pinia',
      'axios',
      'vue-router',
    ],
  },
  server: {
    host: '0.0.0.0',
    port: 8888, // 设置服务启动端口号
    open: true, // 设置服务启动时是否自动打开浏览器
    cors: true, // 允许跨域
    //TODO
    // 设置代理，根据我们项目实际情况配置
    proxy: {
      '/api': {
        target: 'http://121.40.44.91:8120',
        changeOrigin: true,
        secure: false,
        rewrite: (path) => path
      },
      // '/api': {
      //   target: 'http://139.196.18.102:8500',
      //   changeOrigin: true,
      //   secure: false,
      //   rewrite: (path) => path
      // },
      // '^(?!/page)': {
      //   //target: 'http://127.0.0.1:8000/',
      //   target: 'http://139.196.18.102:8020/',
      //   changeOrigin: true,
      //   secure: false,
      //   rewrite: (path) => path
      // },
    }
  }
})
`

**Comment by biewenwoshishei** [comment]
<img width="1093" alt="image" src="https://user-images.githubusercontent.com/64004615/191161516-9f92401c-cecd-4337-a6b6-8c1bb8ab37fb.png">


怀疑有些js 相对路径未替换

**Comment by bailicangdu** [comment]
可以看一下build之后的js文件，确认一下./vue.xx.js文件的地址是不是相对路径，如果是相对路径，需要想办法设置为绝对路径

**Comment by biewenwoshishei** [comment]
很明显 替换规则没生效

**Comment by evle** [comment]
@bailicangdu  9月底啦 vite2支持版本会发布吗？

**Comment by dingshaomiao** [comment]
@bailicangdu 9月底啦 vite2支持版本会发布吗？

**Comment by xiaofanchuan159** [comment]
九月底了，还没发布vite的支持版本，现在对于vite，下不支持2.6，上不支持3.1，就能用2.9.14。返璞归真用iframe的另一个方案了，啥问题都没有。
