### ISSUE TITLE
页面长时间不操作，会出现不能跳转页面的情况，必须要手动刷新页面才恢复

### ISSUE THREAD

**Issue by LadyChatterleyLover** [jd-opensource/micro-app#599]
## 问题描述
> 问题的具体描述

## 复现步骤
1. 停留页面半个小时不操作
2. 点击跳转子应用无反应，必须要手动刷新页面才恢复

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。

## 环境信息
- micro-app版本：0.8.5
- 主应用前端框架&版本： vue3.2.13
- 子应用前端框架&版本：vue3.2.13
- 构建工具&版本：vue-cli5.0.0

**Comment by LadyChatterleyLover** [comment]
![image](https://user-images.githubusercontent.com/35223515/191425145-93f54563-798c-49c1-b9d6-a83ab39e4173.png)
会报这个错

**Comment by bailicangdu** [comment]
基座和子应用都不能跳转吗

**Comment by bailicangdu** [comment]
run build 打包后看一下是否还存在这个问题

**Comment by LadyChatterleyLover** [comment]
就是线上环境哈，如果正常使用，不会出现问题，如果页面长时间不操作，就会出现问题




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "micro-zoe/micro-app"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月21日(星期三) 下午2:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [micro-zoe/micro-app] 页面长时间不操作，会出现不能跳转页面的情况，必须要手动刷新页面才恢复 (Issue #599)





 
run build 打包后看一下否存还存在这个问题

**Comment by bailicangdu** [comment]
试了一下，自己创建的demo没有复现，有没有可以复现的方法，线上地址之类的？

**Comment by LadyChatterleyLover** [comment]
可能没办法复现，这个是在线上运行的。





发自我的iPhone


------------------ 原始邮件 ------------------
发件人: cangdu ***@***.***&gt;
发送时间: 2022年9月21日 18:59
收件人: micro-zoe/micro-app ***@***.***&gt;
抄送: luopei ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [micro-zoe/micro-app] 页面长时间不操作，会出现不能跳转页面的情况，必须要手动刷新页面才恢复 (Issue #599)





 
试了一下，自己创建的demo没有复现，有没有可以复现的方法？

**Comment by LadyChatterleyLover** [comment]
主应用和子应用都不行，相当于页面直接卡死了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "micro-zoe/micro-app"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月21日(星期三) 下午2:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [micro-zoe/micro-app] 页面长时间不操作，会出现不能跳转页面的情况，必须要手动刷新页面才恢复 (Issue #599)





 
run build 打包后看一下否存还存在这个问题

**Comment by LadyChatterleyLover** [comment]
@bailicangdu 请问这个问题有解决方案，最近出现的频率比较高

**Comment by bailicangdu** [comment]
无法复现，没办法定位问题

**Comment by LadyChatterleyLover** [comment]
![image](https://user-images.githubusercontent.com/35223515/196370734-bd4f5c92-112d-4929-ba87-08252bd4d72a.png)
@bailicangdu 又出现了，感觉像是子应用的资源没有加载到，

**Comment by bailicangdu** [comment]
升级到1.0试一下 https://micro-zoe.com/docs/1.x/#/zh-cn/transfer

**Comment by LadyChatterleyLover** [comment]
好的，到时候我试一下




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "micro-zoe/micro-app"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月18日(星期二) 下午4:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [micro-zoe/micro-app] 页面长时间不操作，会出现不能跳转页面的情况，必须要手动刷新页面才恢复 (Issue #599)





 
升级到1.0试一下 https://micro-zoe.com/docs/1.x/#/zh-cn/transfer

**Comment by LadyChatterleyLover** [comment]
@bailicangdu 问题解决了，子应用路由懒加载引起的，取消懒加载就可以了
