### ISSUE TITLE
子应用使用webpack5报错 Cannot redefine property: $router

### ISSUE THREAD

**Issue by wangjieCode** [jd-opensource/micro-app#600]
## 问题描述
> 问题的具体描述
<img width="983" alt="image" src="https://user-images.githubusercontent.com/49115360/191403099-91d3243b-2cf3-46c4-9ac6-c58609bcdbf3.png">
基座使用的是2.6.x的vue 
子应用使用的为2.7.x的vue
都做了externals 开发环境正常，build出来就会报以上的错误

## 环境信息
- micro-app版本 0.8.5：
- 主应用前端框架&版本：vue 2.6.14
- 子应用前端框架&版本：vue 2.7.6
- 构建工具&版本：主应用webpack4 子应用webpack5

**Comment by wangjieCode** [comment]
我搭出来的demo复现不了，但是在公司项目会这样，大佬可以帮我判断一下问题可能出在哪里么

**Comment by bailicangdu** [comment]
参考 https://stackoverflow.com/questions/52209717/vuejs-uncaught-typeerror-cannot-redefine-property-router

**Comment by wangjieCode** [comment]
子应用中访问的vue实例不是基座的实例吧，我们的项目中，我在子应用打印vue版本发现会访问到基座的2.6.14

**Comment by bailicangdu** [comment]
子应用的全局变量如果没查询到会兜底到原生window上查询

**Comment by bailicangdu** [comment]
最直接的原因是$router被定义了两次，比如：
<img width="700" alt="image" src="https://user-images.githubusercontent.com/20297227/191444049-25f0ce2b-de29-445f-b58a-088d25fb64a9.png">
但是我看不到代码，无法定位具体是哪行代码

**Comment by wangjieCode** [comment]
谢谢回复我晚点在研究一下🙏

**Comment by wangjieCode** [comment]
破案了。vue/cli 5.x会默认打包支持esm的产物+不支持esm的产物，通过nomodule属性实现，关闭构建esm的选项即可``vue-cli-service build --no-module`` 添加``--no-module``即可

**Comment by bailicangdu** [comment]
这个吗，最新版vue/cli应该是默认关闭esm，只有设置--modern参数才会开启，你的vue/cli是5.几？
<img width="821" alt="image" src="https://user-images.githubusercontent.com/20297227/191655123-20f761ac-cea0-44b8-a541-7ed39a88877f.png">

**Comment by wangjieCode** [comment]
5.0.8 ，我没开默认给我打esm

**Comment by YFAnt** [comment]
借个楼，我今天也出现了这个问题，一般情况下，子应用中报这个错，一般是由于父应用中的 Vue 挂载到了父应用的 window 对象上了。

所以他们基本上有两个办法：
- 在主应用中不使用 CDN 等 external 的方式来加载 Vue 框架，使用前端打包软件来加载模块
- 在主应用中，将 window.Vue 变量改个名称，例如 window.Vue2 = window.Vue; delete window.Vue


很不幸， 这两个方法对我来说没用， 我打印了`window.Vue`， 发现是`undefined`， 且 我并没有`script`引入`vue` 或者`vue-router`, 最后的解决办法在卸载子应用的时候
```
window.unmount = () => {
  app.$destroy()；
  window.Vue = null 
}
```

这样确实解决了我的问题。
