### ISSUE TITLE
主应用和子应都是 vite 打包，报：failed to connect to websocket

### ISSUE THREAD

**Issue by matteao03** [jd-opensource/micro-app#604]
## 前言
一个主应用 main，两个子应用 app1 , app2 。主应用和子应用都是 vue3 项目， 通过 vite 打包。
## 问题
子应用无法正常切换
## 复现步骤
- 访问主应用： http://127.0.0.1:5173/ ， 页面上有四个路由： app1,  app2, home, about 。 其中 home ,about 为主应用路由；
- 点击 app1 路由, 可以正常切换 app1 子应用，控制台报错： failed to connect to websocket 
-  点击 app2 路由，正常切换 app2 子应用, 控制台报错： failed to connect to websocket
- 点击 home 路由或者 about 路由，可以正常切换；

## 最小复现仓库：
[micro-app-demo-vite](https://github.com/matteao03/micro-app-demo-vite)

## 环境
浏览器： chrome (比较新的版本即可)
@micro-zoe/micro-app: 0.8.10
vue: 3.2.38
@vitejs/plugin-vue:  3.0.3

**Comment by xiaofanchuan159** [comment]
vite应用，用microapp，都不如直接用iframe

**Comment by jiangkaifree** [comment]
我也是这样子（主应用umi， 子应用vite+react）， 接入了， 页面倒是出来了，但是应用通信不行，相关的环境变量都获取不到
![image](https://user-images.githubusercontent.com/50451924/220236313-bdd58530-6453-401c-be47-b62c688dadaa.png)
![image](https://user-images.githubusercontent.com/50451924/220236337-c9475559-f564-434c-97df-b4295f398da7.png)

**Comment by smallk1002** [comment]
有解决么

ws 一直报错

**Comment by easymoneysniperrr** [comment]
<img width="415" alt="image" src="https://user-images.githubusercontent.com/45280905/231726768-296a38d7-8a0e-4d98-90bb-6b3de72e92ed.png">
怎么解决啊

**Comment by easymoneysniperrr** [comment]
> 我也是这样子（主应用umi， 子应用vite+react）， 接入了， 页面倒是出来了，但是应用通信不行，相关的环境变量都获取不到 ![image](https://user-images.githubusercontent.com/50451924/220236313-bdd58530-6453-401c-be47-b62c688dadaa.png) ![image](https://user-images.githubusercontent.com/50451924/220236337-c9475559-f564-434c-97df-b4295f398da7.png)

请问解决了吗

**Comment by noyanse1023** [comment]
有解决吗

**Comment by jiangkaifree** [comment]
没有 弃坑了，转wujie了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "micro-zoe/micro-app"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月20日(星期四) 中午11:12
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [micro-zoe/micro-app] 主应用和子应都是 vite 打包，报：failed to connect to websocket (Issue #604)





 
有解决吗

**Comment by noyanse1023** [comment]
啊，我解决了,用这个通信: `import { EventCenterForMicroApp } from '@micro-zoe/micro-app'``

**Comment by easymoneysniperrr** [comment]
这个是vite版本的问题，用"vite": "^2.6.13"的版本就不会有这个报错
