### ISSUE TITLE
希望将子应用信息映射至地址栏的功能是可配置的

### ISSUE THREAD

**Issue by coolRoger** [jd-opensource/micro-app#605]
## 背景
由0.8.5升级到1.0.0-alpha.9之后，每次打开子应用，地址栏都会出现子应用的相关信息
<img width="1679" alt="image" src="https://user-images.githubusercontent.com/33861624/192084040-c6ea5260-519c-42d4-98f0-04768556a2ea.png">

<img width="1678" alt="image" src="https://user-images.githubusercontent.com/33861624/192084080-c68c89f8-8650-424a-a116-7dd04650aeb6.png">
就会导致其下子应用的热更失效，要每次都要重新刷新基座程序才能看到子应用更新，(之前是把子应用关闭再重新打开就能看到子应用更新了)。

排查了一下，估计是地址栏新增了子应用信息导致，所以希望将子应用信息映射至地址栏的功能是可配置的

## 期望的效果
希望将子应用信息映射至地址栏的功能是可配置的
microApp.start({attachToUrl: boolean})

**Comment by icksky** [comment]
```javascript
microApp.start({
  'disable-memory-router': true, // 关闭虚拟路由
})
```
参考[文档-虚拟路由系统](https://micro-zoe.com/docs/1.x/#/zh-cn/router)

**Comment by coolRoger** [comment]
谢谢解答
