### ISSUE TITLE
如何把基座应用中众多的子应用配置界面的逻辑集中到一个文件中？

### ISSUE THREAD

**Issue by small-dots** [jd-opensource/micro-app#606]
如何把基座应用中众多的子应用配置界面的逻辑集中到一个文件中？

如果后期增加一个活多个子应用，就需要在基座中去添加相应的配置，能否通过接口请求的方式来配置这些内容，有什么好的办法吗？

![image](https://user-images.githubusercontent.com/52172424/192214139-217ea46a-255f-47a5-bddd-b4f946fc2eb9.png)

**Comment by bailicangdu** [comment]
可以直接修改name和url切换不同的子应用，`<micro-app name='x' url='x'>`

**Comment by culm** [comment]
通过<micro-app name='x' url='x'>，路由改变后，里面内容没有改变。刷新下页面就正常了

**Comment by bailicangdu** [comment]
> 通过，路由改变后，里面内容没有改变。刷新下页面就正常了

参考 https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/jump

**Comment by culm** [comment]
> 
在micro-app-demo样例中增加了一个页面，做通用应用，在增加的页面中，可以监听到路由改变，当前微应用不刷新，重新筛选页面没问题。

< template>
  < div v-if="appName && url">
    <micro-app
      :name="appName"
      :url='url'
      :baseroute="baseroute"
      inline
      disablesandbox
      :data='microAppData'
      @created='handleCreate'
      @beforemount='handleBeforeMount'
      @mounted='handleMount'
      @unmount='handleUnmount'
      @error='handleError'
      @datachange='handleDataChange'
    ></micro-app>
  </div>
</template>

const loadApp = (router: any) => {
  // const {path, query} = router;
  const path = router.path.substr(1);
  const index = path.indexOf('/');
  if(index < 0) {
    appName = path;
  } else {
    appName = path.substring(0, index);
  }
  
  const app = AppDatas[appName];
  if(!app) {
    console.log('不存在的引用');
    return;
  }
  baseroute = app.baseroute;
  // debugger
  url = `${app.url}${app.publicPath}`
  // url = `${config.vite}/child/vite/`;
  console.log('url:', url)
  console.log('appName:', appName)
}
const router = useRouter();
watch(
  () => router.currentRoute.value.path,
  (path, _) => {
    loadApp(router.currentRoute.value)
  },
  { immediate: true }
);

**Comment by culm** [comment]
html是这样的：
<div v-if="appName && url">
    <micro-app
      :name="appName"
      :url='url'
      :baseroute="baseroute"
      inline
      disablesandbox
      :data='microAppData'
      @created='handleCreate'
      @beforemount='handleBeforeMount'
      @mounted='handleMount'
      @unmount='handleUnmount'
      @error='handleError'
      @datachange='handleDataChange'
    ></micro-app>
  </div>

**Comment by culm** [comment]
如果像demo中一样，一个应用一个路由去配置，跳转就没问题

**Comment by culm** [comment]
<img width="729" alt="image" src="https://user-images.githubusercontent.com/2657943/192514318-2697945c-0545-4e8a-8457-22c7076b3c7e.png">
路由配置如上

**Comment by culm** [comment]
> > 通过，路由改变后，里面内容没有改变。刷新下页面就正常了
> 
> 参考 https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/jump

方便添加联系方式么

**Comment by bailicangdu** [comment]
可以加微信群 https://github.com/micro-zoe/micro-app/blob/dev/Contact.md

**Comment by culm** [comment]
> 可以加微信群 https://github.com/micro-zoe/micro-app/blob/dev/Contact.md

多谢
