### ISSUE TITLE
[🐞 Bug]：

### ISSUE THREAD

**Issue by Gavinchen92** [jd-opensource/micro-app#61]
## 问题描述
> 问题的具体描述

## 环境信息
- **micro-app版本:** 0.2.5
- **基座&子应用使用的前端框架和版本:**  react 17.0.2
- **构建工具&版本:** webpack 4.44.2

## 复现步骤
1.  当子应用出现unhandledrejection(fetch 请求返回Promise.reject未捕获)错误时，页面直接白屏
2.

## 上传截图
![](https://pt-starimg.didistatic.com/static/starimg/img/msLV68EB5k1629875539382.png)

**Comment by Gavinchen92** [comment]
是react-error-overlay的问题

**Comment by lijiweigh** [comment]
> 

请问这个问题是怎么解决的，我也遇到了
