### ISSUE TITLE
浏览器回退时所有子页面的路由守卫都被触发

### ISSUE THREAD

**Issue by Star-live** [jd-opensource/micro-app#610]
场景：由一个多标签应用场景，会存在多个应用都处于保活的情况，当点击浏览器回退按钮时，多个子应用的路由守卫都会被触发，这种有什么好的解决办法吗？
![image](https://user-images.githubusercontent.com/52146433/192726229-4cc2349d-1dcc-4171-9b7d-5769e545a13b.png)

**Comment by bailicangdu** [comment]
micro-app版本是多少，如果是0.x版本无解

**Comment by Star-live** [comment]
还是0.8，之前用1.x版本，虚拟路由有循环跳转的问题就还是用的0.8... 我回头再试试1.x的虚拟路由
