### ISSUE TITLE
基座angular，接入vite2+vue3的子应用，按照官网改造后不生效

### ISSUE THREAD

**Issue by LHMing01** [jd-opensource/micro-app#611]
## 问题描述
> 问题的具体描述
报错：Uncaught SyntaxError: Cannot use import statement outside a module.
network查看子应用的资源加载成功了，但是会一直报上面错
## 复现步骤
1.
2.

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。

## 环境信息
- micro-app版本：
- 主应用前端框架&版本：angular
- 子应用前端框架&版本： vue：3.2.25
- 构建工具&版本：vite：2.7.2

**Comment by bailicangdu** [comment]
vite子应用暂时不建议使用

**Comment by thezj** [comment]
内部api项目，就别指望社区化的解决问题了，跑。。。

**Comment by lhm005** [comment]
升级1.0beta这个错误没有了
