### ISSUE TITLE
如何加载子应用指定路由

### ISSUE THREAD

**Issue by wangchaochuan** [jd-opensource/micro-app#614]
## 背景
按照官方示例只实现了将整个子应用加载进主页用，包括了子应用的所有路由，如何才能只加载子应用的指定路由

## 期望的效果
子应用的展示效果是只加载子应用指定的路由

**Comment by raoenhui** [comment]
可查看设置默认页面文档： https://micro-zoe.com/docs/1.x/#/zh-cn/router?id=%e8%ae%be%e7%bd%ae%e9%bb%98%e8%ae%a4%e9%a1%b5%e9%9d%a2
