### ISSUE TITLE
虚拟路由,子应用使用router-link 会直接更改url,而不是更改url 中的那个参数值

### ISSUE THREAD

**Issue by xiangxinji** [jd-opensource/micro-app#615]
我这边虚拟路由还有两个问题, 我这边测试了一下, 如果子应用使用 vue-router 的 router-link好像和router.push 的行为不一样. 
1. router-link 会直接更改浏览器的url 部分,导致虚拟路由的逻辑有问题.
2. 使用 router.push, 会直接动态匹配到 url 的 appName 参数之后, 这个是没有问题的. 

解决方法,我这边可以通过自定义组件组强制更改成统一行为, 不知道这种解决方案是否标准. 然后我还想问的一个问题是,这个url 上的虚拟路由参数, key 可以自定义吗? 

另外最近是否有计划发布1.0 的正式版呢?

**Comment by xiangxinji** [comment]
还有就是 子应用如果指定跳转其他子应用, name 字段是不是和 vue-router 的name 字段冲突了 ?

**Comment by bailicangdu** [comment]
正常情况下router-link跳转是没问题的，能提供个demo看一下吗

**Comment by jiefancis** [comment]
> 我这边虚拟路由还有两个问题, 我这边测试了一下, 如果子应用使用 vue-router 的 router-link好像和router.push 的行

1、提供一个最小复现仓库
2、可以到codepen 或者codesanbox上创建一个demo
以上两种方式方便作者定位问题。

**Comment by niceduang** [comment]
子应用中的 router-link 没有问题，但是控制台会有个警告
```
vue-router.mjs:35 [Vue Router warn]: history.state seems to have been manually replaced without preserving the necessary values. Make sure to preserve existing history state if you are manually calling history.replaceState:

history.replaceState(history.state, '', url)

You can find more information at https://next.router.vuejs.org/guide/migration/#usage-of-history-state.
```
