### ISSUE TITLE
micro-app跟vconsole库冲突，开启vconsole页面会报错，关闭vconsole页面正常

### ISSUE THREAD

**Issue by fengdu555** [jd-opensource/micro-app#618]
## 问题描述
> 问题的具体描述

## 复现步骤
1.开启vconsole,出现报错
2.

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。
<img width="701" alt="image" src="https://user-images.githubusercontent.com/15420634/194987202-88641ab3-1e79-4491-ac1c-ef7067ecb8ac.png">

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。

## 环境信息
- micro-app版本：
- ^0.8.10
- 主应用前端框架&版本：
- 子应用前端框架&版本：
- 构建工具&版本：

**Comment by bailicangdu** [comment]
好的，感谢反馈

**Comment by caoweiju** [comment]
这个问题有进展吗？试了在基座工程和子工程引用vconsole都会报错，也会继续看看源码查一下具体的原因。

**Comment by utj110** [comment]
升级到最新的1.0.0-rc.8版本还是会报错

**Comment by utj110** [comment]
![Uploading 企业微信截图_17255028813469.png…]()
