### ISSUE TITLE
[🐞 Bug]：路由跳转报错

### ISSUE THREAD

**Issue by junsen313** [jd-opensource/micro-app#62]
## 问题描述
应用间路由跳转报错，报错信息如下：
vue-router.min.js:11 ChunkLoadError: Loading chunk loginError404Chunk failed.
(missing: http://localhost:5000/js/loginError404Chunk.js)
    at Function.requireEnsure [as e] (eval at runScript (index.esm.js?fd83:1), <anonymous>:896:26)
    at Function.fn.e (eval at runScript (index.esm.js?fd83:1), <anonymous>:177:40)
    at component (index.js?a18c:2)
    at vue-router.min.js:11
    at vue-router.min.js:11
    at Array.map (<anonymous>)
    at vue-router.min.js:11
    at Array.map (<anonymous>)
    at Et (vue-router.min.js:11)
    at vue-router.min.js:11

## 环境信息
见demo

## 复现步骤
1. git clone https://github.com/junsen313/micro-app-demo.git
2. yarn
3. yarn serve
4. 打开 http://localhost:5000/login/
5. 点击页面的直接跳转按钮
6. 点击浏览器返回按钮
7. 点击左侧菜单切换

## 上传截图
![image](https://user-images.githubusercontent.com/1218085/130767821-826fef4e-cab3-4af4-adf1-5ca7ca2f15af.png)

## 复现仓库
[demo](https://github.com/junsen313/micro-app-demo.git)

**Comment by bailicangdu** [comment]
这个问题是因为popstate事件影响到所有应用，login子应用接收到事件判断 /goods/路由为非法路由则会兜底加载login的404页面，但此时应用已经被卸载了，导致出错，建议子应用的404在微前端环境去掉吧，统一使用基座应用的
![image](https://user-images.githubusercontent.com/20297227/130779249-bdf6bf26-4df4-4116-b0e9-1ca594c5716b.png)

**Comment by junsen313** [comment]
@bailicangdu 子应用已去掉404，暂不处理404情况；问题还是存在，基座左侧菜单来回切换，点浏览器返回，多切几次，还是会报类似错误，暂时没发现规律。demo已更新。

**Comment by junsen313** [comment]
自己debug了下，发现基座的MicroApp.vue组件销毁了，没有触发子应用的 vue实例销毁的生命周期（不知道是不是bug），自然子应用的路由影响还在。所以需要手动的销毁子应用的vue实例：
``` javascript
const subApp = new Vue({
    router,
    store,
    render: (h) => h(App),
}).$mount('#app');

// 子应用中监听卸载事件
window.addEventListener('unmount', function () {
    console.log('我被卸载了');
    subApp.$destroy();
});
```
这样修改后，暂时没发现报错了

**Comment by bailicangdu** [comment]
👍
