### ISSUE TITLE
无法正常获取window.__MICRO_APP_BASE_ROUTE__ 与 window.location.href

### ISSUE THREAD

**Issue by Niefee** [jd-opensource/micro-app#620]
新建一个基座主应用，使用[micro-app-demo](https://github.com/micro-zoe/micro-app-demo)作为子应用。
## 问题描述
> 问题的具体描述
1. 基座已经添加`baseroute="/main-app/sub-app-vue3"`参数，子应用无法获取`window.__MICRO_APP_BASE_ROUTE__`，返回结果为`undefined。
2. 子应用中打印`window.location.href`，返回地址是子应用单独打开的地址`http:xxx/child/vue3/`，正确应该是`"http://xxxxxx/main-vite/app-vue3/"`

## 复现步骤
1.
2.

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。

## 环境信息
- micro-app版本：@micro-zoe/micro-app": "^1.0.0-alpha.1",
- 主应用前端框架&版本："vue": "^3.2.25",
- 子应用前端框架&版本：
  - "vue": "^3.0.5",
   - "vue-router": "^4.0.11"
- 构建工具&版本：
  - "vite": "^2.9.2",
    "vite-plugin-compression": "^0.5.1",
    "vite-plugin-eslint": "^1.6.0",
    "vite-plugin-vue-setup-extend": "^0.4.0",
    "vue-tsc": "^0.40.13"

**Comment by bailicangdu** [comment]
vite子应用是拿不到这些数据的，因为沙箱关闭了

**Comment by Niefee** [comment]
已解决，升级到最新，关闭虚拟路由即可
