### ISSUE TITLE
angular13项目，子应用之间切换，未触发当前页面ngOnDestroy生命周期

### ISSUE THREAD

**Issue by w2819** [jd-opensource/micro-app#621]
## 问题描述
> 如题，子应用之间切换未触发生命周期，导致点开未关闭的popover等组件和订阅事件无法正常卸载，切换回页面后页面出现混乱。
注：子应用卸载的时候 unmount 生命周期里app.destroy()会报错，屏蔽掉了

## 复现步骤
1.在子应用页面ngOnDestroy生命周期内添加log，跳转到其他子应用
2.观察log未打印
3.多次切换不同页面是否会内存溢出还未测试

## 复现仓库
> 官方demo也可以复现

## 环境信息
```bash
Angular CLI: 13.2.6
Node: 16.14.2
Package Manager: npm 8.5.0
OS: darwin arm64

Angular: 13.2.7
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1302.6
@angular-devkit/build-angular   13.2.6
@angular-devkit/core            13.2.6
@angular-devkit/schematics      13.2.6
@angular/cdk                    13.2.6
@angular/cli                    13.2.6
@schematics/angular             13.2.6
rxjs                            7.5.6
typescript                      4.5.5
@micro-zoe/micro-app  ^1.0.0-alpha.10
```

**Comment by bailicangdu** [comment]
因为没有执行app.destroy()，angular不知道组件被卸载，所以还是需要执行app.destroy

**Comment by bailicangdu** [comment]
执行app.destroy()报错的截图发一下呢

**Comment by w2819** [comment]
![image](https://user-images.githubusercontent.com/8953012/196362693-b6beac99-ef3c-4f21-b242-40a42dd80532.png)
调用后可以正常卸载并切换应用，再次进入这个应用会报这个错

**Comment by bailicangdu** [comment]
这个问题是因为执行destroy后根元素也被删除了，再次渲染时需要手动创建一个根元素，就是报错信息中的 seui-product-root 元素

**Comment by w2819** [comment]
请问如何创建呢，在什么时机插入进入，谢谢哦

**Comment by bailicangdu** [comment]
mount方法最前面，document.createElement('seui-product-root')

**Comment by w2819** [comment]
好的，多谢，马上试试

**Comment by w2819** [comment]
<img width="675" alt="image" src="https://user-images.githubusercontent.com/8953012/196379842-7a5ac9cd-19da-491b-a93e-6cbf151e530f.png">
修改后，组件库会报这个错，功能基本正常了

**Comment by w2819** [comment]
<img width="825" alt="image" src="https://user-images.githubusercontent.com/8953012/196380406-292c168e-a6ae-4f17-b0d3-3baee81dde8e.png">
