### ISSUE TITLE
__MICRO_APP_BASE_APPLICATION__返回结果有误

### ISSUE THREAD

**Issue by Niefee** [jd-opensource/micro-app#622]
## 问题描述
> 问题的具体描述

在基座正常返回，
```js
console.log('__MICRO_APP_BASE_APPLICATION__:', window.__MICRO_APP_BASE_APPLICATION__);
// __MICRO_APP_BASE_APPLICATION__: true
```
在vue3子应用也正常返回
```js
console.log('__MICRO_APP_BASE_APPLICATION__:', window.__MICRO_APP_BASE_APPLICATION__);
// __MICRO_APP_BASE_APPLICATION__: undefined
```

但在vite&vue3子应用中，却又问题，返回true
```js
console.log('__MICRO_APP_BASE_APPLICATION__:', window.__MICRO_APP_BASE_APPLICATION__);
// __MICRO_APP_BASE_APPLICATION__: true
```
根据问题文档[__MICRO_APP_BASE_APPLICATION__](https://micro-zoe.com/docs/1.x/#/zh-cn/env?id=__micro_app_base_application__)，在执行microApp.start()后此值才会生效。这里不是应该返回`undefined`吗

## 复现步骤
1.
2.

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。

## 环境信息
- micro-app版本："@micro-zoe/micro-app": "1.0.0-alpha.10",
- 主应用前端框架&版本：
  -  "vite": "^2.9.2",
    "vite-plugin-compression": "^0.5.1",
    "vite-plugin-eslint": "^1.6.0",
    "vite-plugin-vue-setup-extend": "^0.4.0",
    "vue-tsc": "^0.40.13"
- 子应用前端框架&版本：
  - "vite": "^2.9.2",
    "vite-plugin-compression": "^0.5.1",
    "vite-plugin-eslint": "^1.6.0",
    "vite-plugin-vue-setup-extend": "^0.4.0",
    "vue-eslint-parser": "^9.1.0",
    "vue-tsc": "^0.29.8"
- 构建工具&版本：

**Comment by bailicangdu** [comment]
因为vite子应用的沙箱关闭了，以后会修复这个问题

**Comment by Niefee** [comment]
开启或者关闭虚拟路由`disable-memory-router`，子应用返回的 window.location.href结果不一致。
 @bailicangdu 这个是否bug。
关闭虚拟路由，返回基座URL，默认不关闭返回子应用单独打开的URL

**Comment by bailicangdu** [comment]
正常

**Comment by Niefee** [comment]
> 正常

@bailicangdu  那开启虚拟路由，子应用就无法获取基座的完整`href`了。有什么办法解决？

**Comment by bailicangdu** [comment]
window.rawWindow.location.href

**Comment by chenxiaofie** [comment]
> 因为vite子应用的沙箱关闭了，以后会修复这个问题

大佬，这个bug还没修吗，现在使用还是会出现这种情况，基座vite+子应用vite 在子应用中__MICRO_APP_BASE_APPLICATION__还是为true。没办法判断环境变量了
