### ISSUE TITLE
对于1.0版本的一些想法

### ISSUE THREAD

**Issue by mursumomo** [jd-opensource/micro-app#623]
## 背景
> 子应用请求的自动补全是个非常好的功能，之前是自己手动去用拦截实现的。看了micro的源码，很佩服，也学到了。但在使用1.0版本的同时，也想继续使用ajax-hook，对子应用的一些请求进行一些特定的拦截。发现开启了子应用请求的自动补全功能的话，ajax-hook的拦截就失效了。

## 期望的效果

1：开启了子应用请求自动补全的功能，对xhr的拦截还能继续生效
2：是否可以开放一个功能函数，仅仅使用micro-app就可以对子应用的请求进行拦截，实现类似ajax-hook的能力
3：如果前两条都不可以，是否可以把micro-app内部的一些工具函数提供出来，如creatURL这些。现在发现这些工具函数并没有直接export出来。如果可以，想使用这些工具函数，方便的自己去实现功能

**Comment by bailicangdu** [comment]
请求的补全功能是可以关闭的，参考  https://micro-zoe.com/docs/1.x/#/zh-cn/configure?id=disable-patch-request

**Comment by bailicangdu** [comment]
以后会拓展一些请求相关的功能

**Comment by mursumomo** [comment]
> https://micro-zoe.com/docs/1.x/#/zh-cn/configure?id=disable-patch-request

是的，是可以关闭的。哈哈，主要是挺好用的，想继续用。然后又有需求需要去用ajax-hook去拦截。因为补全功能重写了xhr，导致ajax-hook失效了。
