### ISSUE TITLE
vue3 vite3 ts 编译后作为micro-app的子应用报错

### ISSUE THREAD

**Issue by zp342519261** [jd-opensource/micro-app#626]
## 问题描述
> vue3 vite3 ts 编译后作为micro-app的子应用报错
[micro-app from runScript] app template-compile:  SyntaxError: Unexpected token 'export' (at index.032e5d31.js:63:26815)

## 复现步骤
1.按照官网给的vite适配方式去做
2.

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。
<img width="1007" alt="image" src="https://user-images.githubusercontent.com/45960308/197158495-26305c0a-1a3d-4988-9dfb-f55bd61c3627.png">
<img width="964" alt="image" src="https://user-images.githubusercontent.com/45960308/197158646-99bb57b7-8130-4de3-b870-5cc7a89b96fb.png">
<img width="557" alt="image" src="https://user-images.githubusercontent.com/45960308/197159436-c05b31f5-e586-445a-bd32-4ad760e6e2a6.png">

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。

## 环境信息
- micro-app版本：1.0.0-alpha.9
- 主应用前端框架&版本：vue@2.6.14
- 子应用前端框架&版本：vue@3.2.28 
- 构建工具&版本：vite@3.0.9

**Comment by liuwei1025** [comment]
同样的问题

**Comment by jackiealex** [comment]
使用 iframe 沙箱，不会有这个问题

**Comment by bingowujihuan** [comment]
Uncaught TypeError: Failed to resolve module specifier "/node_modules/.vite/deps/vue.js?v=34bfca84". Invalid relative url or base scheme isn't hierarchical.

**Comment by bingowujihuan** [comment]
这个问题很像
![image](https://user-images.githubusercontent.com/107112193/219340123-5cc38f76-9a6c-4550-a853-276a3b640243.png)

**Comment by changEveryDay** [comment]
我也遇到相同的问题，请问您问题解决了吗，怎么解决的

**Comment by wangling404** [comment]
<img width="1496" alt="image" src="https://github.com/micro-zoe/micro-app/assets/25219906/dae4921c-3b0d-4a46-be9a-f86df6ae5d05">我也是一直报着个错，基座和微应用，全部都是vite4 + vue3，怎么解决

**Comment by raoenhui** [comment]
https://micro-zoe.com/docs/1.x/#/zh-cn/configure?id=iframe ，用的是iframe这个吗？

**Comment by scottMan1001** [comment]
> <img alt="image" width="1496" src="https://user-images.githubusercontent.com/25219906/258967641-dae4921c-3b0d-4a46-be9a-f86df6ae5d05.png">我也是一直报着个错，基座和微应用，全部都是vite4 + vue3，怎么解决

子应用不能是开发模式，我之前也遇到这个问题，你把子应用打包，然后npm run preview再看看

**Comment by DoubleXm** [comment]
> > <img alt="image" width="1496" src="https://user-images.githubusercontent.com/25219906/258967641-dae4921c-3b0d-4a46-be9a-f86df6ae5d05.png">我也是一直报着个错，基座和微应用，全部都是vite4 + vue3，怎么解决
> 
> 子应用不能是开发模式，我之前也遇到这个问题，你把子应用打包，然后npm run preview再看看

我本来也是这个问题
![image](https://github.com/micro-zoe/micro-app/assets/70535483/cb250067-82b8-40f9-8bd2-28b83f850b77)

按照你的说法用 preview 后是如下问题
![image](https://github.com/micro-zoe/micro-app/assets/70535483/995fbe13-5382-4803-91ee-226aa7b6c7ff)
跨域了，我觉得是我在 prod 的环境下，url 写的有问题，但是不知道如何去解决这个问题（我的意思是在开发的模式下，我要用 preview 去调试吗，或者说开发模式下的跨域我应该如何解决）

**Comment by scottMan1001** [comment]
子应用没取消跨域。。但你解决这个问题后还会遇见其他问题。。比如你子应用的初始路由界面不展示



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年9月7日(周四) 晚上6:11
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [micro-zoe/micro-app] vue3 vite3 ts 编译后作为micro-app的子应用报错 (Issue #626)




   
我也是一直报着个错，基座和微应用，全部都是vite4 + vue3，怎么解决
  
子应用不能是开发模式，我之前也遇到这个问题，你把子应用打包，然后npm run preview再看看
  
我本来也是这个问题
 
 
按照你的说法用 preview 后是如下问题
 
 跨域了，我觉得是我在 prod 的环境下，url 写的有问题，但是不知道如何去解决这个问题
