### ISSUE TITLE
keep-alive 可以部分应用不进行保持吗

### ISSUE THREAD

**Issue by lyydhy** [jd-opensource/micro-app#628]
## 背景
> 描述您希望改进的问题。
设置keep-alive后 会缓存所有的子应用  导致子应用原有的 生命周期都不会被执行 销毁之类的，但是有些应用 正常走销毁会更方便 

## 期望的效果
在可选的情况下  可不可以添加一个过滤之类的  部分应用不进行keep-alive  其余的如设置了keep-alive  正常缓存

**Comment by bailicangdu** [comment]
keep-alive可以针对子应用单独设置

**Comment by bailicangdu** [comment]
`<micro-app name='xx' url='xx' keep-alive></micro-app>`

**Comment by dz269375933** [comment]
想请教一下子应用中单个组件的缓存怎么设置呢

**Comment by dz269375933** [comment]
“如果想要缓存具体的页面或组件，需要使用子应用框架的能力，如：vue的keep-alive。”子应用中会用keep-alive，但由于子应用是由同一个组件渲染出来的，组件的name是固定的，子应用中不同页面组件的name值都是同一个值，怎么处理比较好呢

**Comment by Albert-cord** [comment]
> “如果想要缓存具体的页面或组件，需要使用子应用框架的能力，如：vue的keep-alive。”子应用中会用keep-alive，但由于子应用是由同一个组件渲染出来的，组件的name是固定的，子应用中不同页面组件的name值都是同一个值，怎么处理比较好呢

不同页面肯定有些不一样的，例如path，或者有个唯一的id，通过appName跟path或者id组成一个唯一的主键，可以通过一些摘要算法，例如简单的hash得到
