### ISSUE TITLE
1.0 alpha 版本，主应用vue3  路由history模式，子应用 vue2 hash模式。关闭虚拟路由后，如果子应用路由携带参数，刷新浏览器，无法找到对应路由，加载子应用失败

### ISSUE THREAD

**Issue by islittlezhou** [jd-opensource/micro-app#629]
如果 你认为没有这个BUG， 请给我一个 准确答复 --- 让我确信是我自己的问题。 谢谢

**Comment by islittlezhou** [comment]
### 问题描述
>1.0 alpha 版本 0.8 版本，主应用vue3 路由history模式，子应用 vue2 hash模式。关闭虚拟路由后，如果子应用路由携带参数，刷新浏览器，无法找到对应路由，加载子应用失败

### 复现步骤
1、下载我给的 demo，安装依赖，然后分别启动 主应用 和 子应用， 启动后， 主应用地址是  http://localhost:9999 ，子应用地址是  http://localhost:9998
2、在浏览器中 打开 地址  http://localhost:9999 
3、点击页面  按钮  档案管理首页  跳入 子应用
2、在 页面 点击 按钮， 携带参数进入b路由，页面路劲是 http://localhost:9999/dagl#/b?t=3， 然后刷新浏览器，发现 无法匹配到路由

### 复现仓库
> 
[子应用携带参数刷新后无法找到路由.zip](https://github.com/micro-zoe/micro-app/files/9856899/default.zip)


### 环境信息
- micro-app   1.0@aplha、0.8
-  主应用 vue3  vue-router@4.0
- 子应用  vue3 vue-router@4.0




这个是 最小复现 demo， 主 和 子 应用 都是 vue3 ， 主应用是 history 子应用是 hash

**Comment by bailicangdu** [comment]
测试demo复现步骤，没有问题

**Comment by islittlezhou** [comment]
> 测试demo复现步骤，没有问题
有问题 
![image](https://user-images.githubusercontent.com/24935959/197692939-2be22bea-659d-44b9-aa47-9203c0259e6a.png)

**Comment by islittlezhou** [comment]
本人已找到问题， vue3 + vue-router@4.0.0 会出现上述问题。
我用 vue2 + vue-router@3.1.3 正常
vue3 + vue-router@4.1.6 正常

总之 把 vue-router@4.0.0 升级版本后 都正常了
