### ISSUE TITLE
页面切换，内存占用不释放

### ISSUE THREAD

**Issue by yang0942** [jd-opensource/micro-app#63]
## 问题描述
> 只启动了vue2的项目和基项目，在页面切换后内存占用不释放，会一直增加。只是使用的demo启动后观察到的问题。

## 上传截图
![image](https://user-images.githubusercontent.com/53600732/130915790-443d18a5-5d91-42d9-9224-77507d0d3fe3.png)

**Comment by jiaoguanwen** [comment]
一样遇到，太严重了，只是切换，内存就不停的增加
![image](https://user-images.githubusercontent.com/19830742/130924511-e09f5f90-c2d2-4a75-8cba-a9c914fff086.png)

**Comment by jiaoguanwen** [comment]
子模块卸载后，没有取消引用吧

**Comment by bailicangdu** [comment]
好的，我看一下

**Comment by bailicangdu** [comment]
已定位问题，近期会修复

**Comment by Leeero** [comment]
请问这个问题修复了吗？或者有确切的计划修复时间吗？

**Comment by bailicangdu** [comment]
v0.3.0 版本发布一种解决方案，参考 https://github.com/micro-zoe/micro-app/releases/tag/v0.3.0  https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/advanced?id=_3%e3%80%81%e5%86%85%e5%ad%98%e4%bc%98%e5%8c%96
