### ISSUE TITLE
子应用 iframe URL 被劫持

### ISSUE THREAD

**Issue by hlskysong** [jd-opensource/micro-app#630]
## 问题描述
子应用通过 cloudflare sdk 上传时, iframe 上传页URL被劫持到基座, 导致第三方页面打开失败

## 复现步骤
暂无

## 上传截图
暂无

## 复现仓库
暂无

## 环境信息
- micro-app版本：1.0.0-alpha.7
- 主应用前端框架&版本：vue2
- 子应用前端框架&版本：umi4 & react 18
- 构建工具&版本：webpack5

**Comment by bailicangdu** [comment]
这种情况只能手动补全iframe地址

**Comment by hlskysong** [comment]
已经确认是该 SDK 在 shadow tree 下 document.currentScript 取值异常造成的

https://html.spec.whatwg.org/multipage/dom.html#dom-document-currentscript
