### ISSUE TITLE
配置应用的keepalive或者vue的keepalive 多页签切换子应用缓存都不生效

### ISSUE THREAD

**Issue by wenqd** [jd-opensource/micro-app#631]
## 问题描述
> 问题的具体描述
主子应用都是基于Vue2 的vue-element-admin，配置应用的keepalive或者vue的keepalive 多页签切换子应用缓存都不生效。希望能协助分析下问题 ,issue里相关问题挺多，应该属于公共问题，能否出一个成功的demo？

## 复现步骤
1. demo地址：https://github.com/wenqd/microapp_demo.git
2.具体说明已在readme.md里

## 上传截图
> # 新问题：升级micro-app 1.0后 切换子应用路由 都是跳转到子应用的根目录

# microapp_demo
# 问题：开启keepalive属性后 切换子应用路由 页面组件不跟着切换
# 主应用下挂载页面路径，可根据子应用启动的端口动态调整
main-vue-element-admin/src/views/microapp/app.vue
<img width="1124" alt="image" src="https://user-images.githubusercontent.com/39663153/197712220-234dc059-c1b2-4dd0-a8eb-5a08769d7e16.png">
# 路由
## 可以访问菜单Excel下的子菜单，已配好，
![image](https://user-images.githubusercontent.com/39663153/197712766-b76a8a0c-55a1-4350-b623-14d921d83a74.png)
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/39663153/197712914-585154c3-f618-4577-b5ce-fba05bbd8e1d.png">

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。
demo地址：https://github.com/wenqd/microapp_demo.git
## 环境信息
- micro-app版本：1.0
- 主应用前端框架&版本：vue-element-admin   vue2.6
- 子应用前端框架&版本：vue-element-admin   vue2.6
- 构建工具&版本：webpack

**Comment by bailicangdu** [comment]
本基座控制子应用跳转方式参考：https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/jump, 如果使用了1.0的虚拟路由系统，参考：https://micro-zoe.com/docs/1.x/#/zh-cn/router?id=%e5%af%bc%e8%88%aa

**Comment by bailicangdu** [comment]
因为keep-alive相当于简单的隐藏和显示，不会响应基座的跳转

**Comment by hlwen** [comment]
需要判单断一下是否是隐藏状态，如果是就需要切换基座的路由getActiveApps({excludeHiddenApp:true})

`if (!getActiveApps({excludeHiddenApp:true}).includes(appName)) {
            console.log(1)
            // child-vite 和 child-react17子应用为hash路由，这里拼接一下hash值
            hash && (path += `/#${hash}`)
            // 主应用跳转
            this.$router.push(path)
          } else {
            console.log(2)
            let childPath = null
            // child-vite 和 child-react17子应用是hash路由，hash值就是它的页面地址，这里单独处理
            if (hash) {
              console.log(3)
              childPath = hash
            } else {
              console.log(4)
              // path的值形式如：/app-vue2/page2，这里/app-vue2是子应用的基础路由，/page2才是页面地址，所以我们需要将/app-vue2部分删除
              childPath = path.replace(/^\/app-[^/]+/, '')
              !childPath && (childPath = '/') // 防止地址为空
            }
            // 主应用通过下发data数据控制子应用跳转
            microApp.setData(appName, { path: childPath })
          }`
