### ISSUE TITLE
资源过滤无效

### ISSUE THREAD

**Issue by llm9131142671** [jd-opensource/micro-app#632]
## 问题描述
主应用增加全局静态资源，单个子应用增加资源文件过滤，希望子应用不加载，实际子应用仍然加载了

## 复现步骤
主应用增加
globalAssets: {
        js: ['https://unpkg.com/element-ui@2.15.10/lib/index.js'],
        css: ['https://unpkg.com/element-ui@2.15.10/lib/theme-chalk/index.css'],
    },

子应用增加
     <script src="https://cdn.jsdelivr.net/npm/ant-design-vue@1.7.8/dist/antd.min.js" exclude></script>
     <link href=https://cdn.jsdelivr.net/npm/ant-design-vue@1.7.8/dist/antd.min.css" rel="stylesheet" type="text/css" exclude />

实际效果：子应用仍然会加载js,css文件

## 环境信息
- micro-app版本：0.8.1
- 主应用前端框架&版本：react 17.0.2
- 子应用前端框架&版本：vue2
- 构建工具&版本：
- 主应用 @reskript/cli": "5.2.0"

**Comment by bailicangdu** [comment]
是否有其他子应用加载了相同的文件？network截图看一下呢

**Comment by llm9131142671** [comment]
只启动了一个子应用
