### ISSUE TITLE
资源共享-共享组件库，只能写js，css文件地址，这样不能按需加载，有其他方式吗

### ISSUE THREAD

**Issue by llm9131142671** [jd-opensource/micro-app#634]
资源共享-共享组件库，只能写js，css文件地址，这样不能按需加载，有其他方式吗，比如一个平台有好几个组件库，有的常用，有的按需加载，怎么做

**Comment by bailicangdu** [comment]
参考 https://github.com/micro-zoe/micro-app/releases

**Comment by fantasticsoul** [comment]
推荐了解hel-micro https://github.com/tnfe/hel，一个工具链无关的运行时模块联邦sdk
