### ISSUE TITLE
使用vuecli uniapp模板创建的h5项目做为子应用集成后无效

### ISSUE THREAD

**Issue by jimwjl666** [jd-opensource/micro-app#638]
## 问题描述
> 问题的具体描述

## 复现步骤
1.使用 vue create -p dcloudio/uni-preset-vue mall-test 初始化一个uniapp 项目
2.使用 npm run serve 启动项目，并修改manifest.json 入下图
3.路由使用hash模式
4.主应用加载后再控制台已经可以看到子应用的js、css，但是无法渲染micoApp组件，也没有任何报错信息。
5.尝试vue-cli生成的普通vue项目没问题

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。

![image](https://user-images.githubusercontent.com/19330023/198261217-6c7cdd2d-b531-4357-8f12-091ecda7e056.png)

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。

## 环境信息
- micro-app版本：最新版
- 主应用前端框架&版本：react
- 子应用前端框架&版本：vue create -p dcloudio/uni-preset-vue 新建的uniapp项目
- 构建工具&版本：

**Comment by qian153087222** [comment]
请问解决了吗

**Comment by ThatDays** [comment]
没有，换成正常的vue了



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年12月07日 15:58 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [micro-zoe/micro-app] 使用vuecli uniapp模板创建的h5项目做为子应用集成后无效 (Issue #638) |

请问解决了吗
