### ISSUE TITLE
Failed to resolve component: micro-app

### ISSUE THREAD

**Issue by Nikkolast88** [jd-opensource/micro-app#64]
## 问题描述
> 问题的具体描述

## 复现步骤
1.
2.

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。
https://github.com/DengRiGuang/micro-frontend.git
## 环境信息
- micro-app版本：0.2.5
- 基座应用的前端框架和版本：3.2.6
- 子应用的前端框架和版本：3.2.6
- 构建工具&版本：vite

**Comment by bailicangdu** [comment]
vite内嵌vite吗，因为沙箱关闭了，页面同时引入两套vue3+vite，产生冲突不好解决

**Comment by Nikkolast88** [comment]
想上3.0和vite的话，基座和子应用，怎么一个配置呢

**Comment by zqaq520** [comment]
我觉得跟vite没有关系，而是vue3报的找不到《micro-app》这个自定义标签。PS：我基座和子应用都使用vue3+webpack都报这个

**Comment by bailicangdu** [comment]
参考 https://github.com/vuejs/vue-next/issues/1414

**Comment by zhoufanglu** [comment]
> 想上3.0和vite的话，基座和子应用，怎么一个配置呢

最后有配置成功吗？想参考下

**Comment by Nikkolast88** [comment]
> > 想上3.0和vite的话，基座和子应用，怎么一个配置呢
> 
> 最后有配置成功吗？想参考下

没有，上乾坤了

**Comment by zhoufanglu** [comment]
> > > 想上3.0和vite的话，基座和子应用，怎么一个配置呢
> > 
> > 
> > 最后有配置成功吗？想参考下
> 
> 没有，上乾坤了

昨天经过作者的回答，配置成功了。。

**Comment by Ranylx** [comment]
> > > > 想上3.0和vite的话，基座和子应用，怎么一个配置呢
> > > 
> > > 
> > > 最后有配置成功吗？想参考下
> > 
> > 
> > 没有，上乾坤了
> 
> 昨天经过作者的回答，配置成功了。。

想问下老哥咋解决的

**Comment by JoestarJian** [comment]
> > > > 想上3.0和vite的话，基座和子应用，怎么一个配置呢
> > > 
> > > 
> > > 最后有配置成功吗？想参考下
> > 
> > 
> > 没有，上乾坤了
> 
> 昨天经过作者的回答，配置成功了。。

**Comment by JoestarJian** [comment]
> > > > 想上3.0和vite的话，基础和子应用，怎么一个配置呢
> > > 
> > > 
> > > 最后有配置成功吗？想参考下
> > 
> > 
> > 没有，上乾坤了
> 
> 昨天经过作者的回答，配置成功了。。

怎么配置，求助
