### ISSUE TITLE
二次进入子应用，提示TypeError: Cannot read properties of undefined (reading 'getPrefixCls')，开发环境切换正常。

### ISSUE THREAD

**Issue by happyGloria** [jd-opensource/micro-app#640]
## 问题描述
> 问题的具体描述

- 生产环境：二次进入子应用，提示TypeError: Cannot read properties of undefined (reading 'getPrefixCls')；
- 开发环境：切换正常；

## 复现步骤
1. 基座应用： vue2.x, ant-design-vue@1.7.8，history模式
2. 子应用： vite+vue3, ant-design-vue@3.2.13，hash模式
3. 打包部署到nginx, 应用第一次进入正常，切换到基座应用的其它菜单，或者切换到其它子应用，二次进入应用后报错；

## 上传截图
![image](https://user-images.githubusercontent.com/18031601/198563164-aee74cb3-b765-4db1-8629-60957e6d6e4c.png)

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。
[gitee仓库地址](https://gitee.com/happyGloria/micro-app-issue)
## 环境信息
- micro-app版本：0.6.2
- 主应用前端框架&版本：vue@2.6.14、 vue-router@3.5.3、ant-design-vue@1.7.8
- 子应用前端框架&版本：vue@3.2.41、vue-router@4.1.6、ant-design-vue@3.2.13
- 构建工具&版本：pnpm@7.8.0, yarn，cnpm
- 部署环境： nginx

**Comment by gehaiyi** [comment]
解决了吗 我也出现相同的问题了

**Comment by happyGloria** [comment]
> 解决了吗 我也出现相同的问题了

没有解决，换成了webpack了。

**Comment by gehaiyi** [comment]
> > 解决了 我也出现了相同的问题了
> 
> 没有解决，换成了webpack了。

踩了两周的坑了，正在切换webpack￣□￣｜｜
