### ISSUE TITLE
同名应用不允许有多个,不太友好

### ISSUE THREAD

**Issue by chinaSoftMobile** [jd-opensource/micro-app#641]
## 背景
> 描述您希望改进的问题。

![image](https://user-images.githubusercontent.com/81662974/198569968-1c1eb633-0c87-45c2-b55f-1983c653fa6f.png)
在H5中存在一个页面有多个应用情况

## 期望的效果
支持同名应用,url支持多级页面。

**Comment by bailicangdu** [comment]
同名是指name相同吗，name是唯一标识，不可重复，url支持多级页面在1.0中开启虚拟路由系统可以做到。1.0文档 https://micro-zoe.com/docs/1.x/#/zh-cn/start

**Comment by chinaSoftMobile** [comment]
图片中Link 是同一个应用,这样的需求目前是满足不了的吧。

**Comment by bailicangdu** [comment]
同名确实是不可以的



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: chinaSoftMobile ***@***.***&gt;
发送时间: 2022年10月31日 15:23
收件人: micro-zoe/micro-app ***@***.***&gt;
抄送: cangdu ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [micro-zoe/micro-app] 同名应用不允许有多个,不太友好 (Issue #641)





 
图片中Link 是同一个应用,这样的需求目前是满足不了的吧。

**Comment by zenjustin** [comment]
请问如何去支持多Tab页的应用（如两个tab页内容是同一个子应用的不同路由页面），在子应用name不让重复的情况下。

**Comment by bailicangdu** [comment]
> 请问如何去支持多Tab页的应用（如两个tab页内容是同一个子应用的不同路由页面），在子应用name不让重复的情况下。

name不可重复是指不能同时渲染两个同名的子应用，像tab这种切换子应用是可以的

**Comment by zhou-tao** [comment]
> > 请问如何去支持多Tab页的应用（如两个tab页内容是同一个子应用的不同路由页面），在子应用name不让重复的情况下。
> 
> name不可重复是指不能同时渲染两个同名的子应用，像tab这种切换子应用是可以的

请问多个tab打开同个子应用(不同路由)，可以使用keep-alive保证各个同名子应用间互不干扰么
