### ISSUE TITLE
引入官方demo vue3，shadowDOM报错 TypeError: Illegal invocation

### ISSUE THREAD

**Issue by Niefee** [jd-opensource/micro-app#643]
## 问题描述
> 问题的具体描述

新建主应用，引入官方demo vue3，添加shadowDOM属性，报 TypeError: Illegal invocation

```html5
<micro-app
    name="sub-app-vue3"
    :url="url"
    baseroute="/main-app/sub-app-vue3"
    :data="microAppData"
    disable-memory-router
    keep-alive
    @created="handleCreate"
    @beforemount="handleBeforeMount"
    @mounted="handleMount"
    @unmount="handleUnmount"
    @error="handleError"
    @datachange="handleDataChange"></micro-app>
```
```shell
[micro-app from runScript] app sub-app-vue3:  TypeError: Illegal invocation
    at CreateApp.querySelector (create_app.ts:673:4)
    at HTMLDocument.querySelector (patch.ts:446:4)
    at addStyle (addStylesClient.js?499e:120:1)
    at addStylesToDom (addStylesClient.js?499e:104:1)
    at addStylesClient (addStylesClient.js?499e:58:1)
    at Object.eval (App.vue?7c0e:10:1)
    at ./node_modules/vue-style-loader/index.js?!./node_modules/css-loader/dist/cjs.js?!./node_modules/vue-loader-v16/dist/stylePostLoader.js!./node_modules/postcss-loader/src/index.js?!./node_modules/sass-loader/dist/cjs.js?!./node_modules/cache-loader/dist/cjs.js?!./node_modules/vue-loader-v16/dist/index.js?!./src/App.vue?vue&type=style&index=0&id=7ba5bd90&lang=scss (app.js:1102:1)
    at __webpack_require__ (app.js:856:30)
    at fn (app.js:153:20)
    at Object.eval (App.vue?236d:1:1) http://localhost.abc.com:4010/child/vue3/js/app.js
```

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。

## 环境信息
- micro-app版本：
  - "@micro-zoe/micro-app": "1.0.0-alpha.10",
- 主应用前端框架&版本：
  - "vite": "^2.9.2",
- 子应用前端框架&版本：
  -   "vue": "^3.0.0",
      "vue-router": "^4.0.0"
- 构建工具&版本：
  - "@vue/cli-plugin-babel": "^4.5.0",
    "@vue/cli-plugin-eslint": "^4.5.13",
    "@vue/cli-plugin-router": "^4.5.0",
    "@vue/cli-plugin-typescript": "^4.5.0",
    "@vue/cli-service": "4.5.10",
    "@vue/compiler-sfc": "^3.0.0",
    "@vue/eslint-config-standard": "^5.1.2",
    "@vue/eslint-config-typescript": "^7.0.0",

**Comment by Niefee** [comment]
试验了一下官方[demo](https://github.com/micro-zoe/micro-app-demo) , child-vite添加shadowDOM属性，demo主应用vite无法渲染

**Comment by bailicangdu** [comment]
感谢反馈，我们会尽快排查和修复

**Comment by hsqzyswoai** [comment]
1.0.0 alpha.10碰到了这个问题

**Comment by brooke1220** [comment]
+1

**Comment by agileago** [comment]
+1

**Comment by peony0519** [comment]
子应用vue2 碰到了这个问题

**Comment by hmilin** [comment]
报错原因是：shadowRoot的querySelector和querySelectorAll继承自DocumentFragment而非Document

**Comment by xingbaoliang** [comment]
还没修复吗

**Comment by xingbaoliang** [comment]
> 感谢反馈，我们会尽快排查和修复

有没有解决办法

**Comment by ohgod1992** [comment]
最新版本也遇见了

**Comment by LiuZiqi-dual** [comment]
最新版本，依然存在这个问题

**Comment by wizardpisces** [comment]
最新版依然存在，有进度了么？咋被关闭了

**Comment by burakakca** [comment]
same problem

**Comment by l246804** [comment]
+1

**Comment by l246804** [comment]
暂时给源码 `CreateApp` 类的这两个方法打个补丁解决了，还是官方处理比较合适。

```ts
    querySelector(selectors) {
            const fn = this.container instanceof globalEnv.rawDocumentFragment ? globalEnv.rawDocumentFragment.prototype.querySelector : globalEnv.rawElementQuerySelector
            return this.container ? fn.call(this.container, selectors) : null;
        }
    querySelectorAll(selectors) {
        const fn = this.container instanceof globalEnv.rawDocumentFragment ? globalEnv.rawDocumentFragment.prototype.querySelectorAll : globalEnv.rawElementQuerySelectorAll
        return this.container ? fn.call(this.container, selectors) : [];
    }
```

**Comment by hhbbeijing** [comment]
三年过去了，都2025年了，还没解决。。。。。。不靠谱

**Comment by hhbbeijing** [comment]
> 暂时给源码 `CreateApp` 类的这两个方法打个补丁解决了，还是官方处理比较合适。
> 
>     querySelector(selectors) {
>             const fn = this.container instanceof globalEnv.rawDocumentFragment ? globalEnv.rawDocumentFragment.prototype.querySelector : globalEnv.rawElementQuerySelector
>             return this.container ? fn.call(this.container, selectors) : null;
>         }
>     querySelectorAll(selectors) {
>         const fn = this.container instanceof globalEnv.rawDocumentFragment ? globalEnv.rawDocumentFragment.prototype.querySelectorAll : globalEnv.rawElementQuerySelectorAll
>         return this.container ? fn.call(this.container, selectors) : [];
>     }

怎么给源码打补丁啊？

**Comment by l246804** [comment]
> > 暂时给源码 `CreateApp` 类的这两个方法打个补丁解决了，还是官方处理比较合适。
> > ```
> > querySelector(selectors) {
> >         const fn = this.container instanceof globalEnv.rawDocumentFragment ? globalEnv.rawDocumentFragment.prototype.querySelector : globalEnv.rawElementQuerySelector
> >         return this.container ? fn.call(this.container, selectors) : null;
> >     }
> > querySelectorAll(selectors) {
> >     const fn = this.container instanceof globalEnv.rawDocumentFragment ? globalEnv.rawDocumentFragment.prototype.querySelectorAll : globalEnv.rawElementQuerySelectorAll
> >     return this.container ? fn.call(this.container, selectors) : [];
> > }
> > ```
> 
> 怎么给源码打补丁啊？

给源码打补丁我用的 `pnpm patch`，npm 的话有个包叫 `patch-package` 可以试试，不过目前发现开启 `shadowDom` 后会导致子应用事件拦截失效，比如子应用的 ElementPlus 的 TreeSelect 组件会在点击树节点立即关闭下拉面板，关闭 `shadowDom` 后就正常了，不介意的话倒是可以用用看。

**Comment by zepang** [comment]
> 暂时给源码 `CreateApp` 类的这两个方法打个补丁解决了，还是官方处理比较合适。
> 
>     querySelector(selectors) {
>             const fn = this.container instanceof globalEnv.rawDocumentFragment ? globalEnv.rawDocumentFragment.prototype.querySelector : globalEnv.rawElementQuerySelector
>             return this.container ? fn.call(this.container, selectors) : null;
>         }
>     querySelectorAll(selectors) {
>         const fn = this.container instanceof globalEnv.rawDocumentFragment ? globalEnv.rawDocumentFragment.prototype.querySelectorAll : globalEnv.rawElementQuerySelectorAll
>         return this.container ? fn.call(this.container, selectors) : [];
>     }

虽然这个修复可以避免错误，但是，之后出现了css自定义变量提示未定义的问题，shadowDOM貌似开不起来

**Comment by l246804** [comment]
> > 暂时给源码 `CreateApp` 类的这两个方法打个补丁解决了，还是官方处理比较合适。
> > ```
> > querySelector(selectors) {
> >         const fn = this.container instanceof globalEnv.rawDocumentFragment ? globalEnv.rawDocumentFragment.prototype.querySelector : globalEnv.rawElementQuerySelector
> >         return this.container ? fn.call(this.container, selectors) : null;
> >     }
> > querySelectorAll(selectors) {
> >     const fn = this.container instanceof globalEnv.rawDocumentFragment ? globalEnv.rawDocumentFragment.prototype.querySelectorAll : globalEnv.rawElementQuerySelectorAll
> >     return this.container ? fn.call(this.container, selectors) : [];
> > }
> > ```
> 
> 虽然这个修复可以避免错误，但是，之后出现了css自定义变量提示未定义的问题，shadowDOM貌似开不起来

这个倒是没注意，如果你的 css 变量定义在根元素的话可能需要替换 `:root` 为 `:host` 试下？其次开 shadowDom 的目的应该是为了能够隔离主子应用之间的样式问题，所以得看使用场景吧，我这边要不是遇到点击事件穿透问题可能会一直开，目前已经关了
