### ISSUE TITLE
启用虚拟路由后，子应用无法使用 window.open 打开页面

### ISSUE THREAD

**Issue by Otto-J** [jd-opensource/micro-app#647]
## 问题描述
> 问题的具体描述

## 复现步骤
1. 克隆仓库，安装依赖，运行项目
2. 子应用 8082 的 about 页面有个按钮，会 window.open 打开新页面
3. 子应用 8080 打开页面，点击按钮，新开的页面路径不正确

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。
https://github.com/Otto-J/micro-app-handle-window-open

## 环境信息
- micro-app版本：1.0.10
- 主应用前端框架&版本：vue3+ cli + router
- 子应用前端框架&版本：vue3+ cli + router
- 构建工具&版本：vue-cli

**Comment by Otto-J** [comment]
补充：如果在基座 main.ts 中关闭虚拟路由，功能就是正常的

**Comment by bailicangdu** [comment]
window.open无法被拦截，建议手动调整跳转路径，如果无法解决只能关闭虚拟路由了

**Comment by Otto-J** [comment]
是的，但关闭了虚拟路由，子应用跳转路由，基座就不知道，无法正确映射高亮的菜单了。比如子应用在 a页面点击按钮跳转到了b页面，关闭虚拟路由的话，基座不能正确展示高亮

**Comment by Otto-J** [comment]
昨天的评估方案：
- 开启虚拟路由，子应用封装 window.open 的 hook 逻辑，如果是微前端环境，自行拼好url，保证可以直接打开
- 关闭虚拟路由，子应用在 router.beforeEach 里告诉基座当前路由，这样是为了基座知道路由变化

**Comment by Otto-J** [comment]
same https://github.com/micro-zoe/micro-app/issues/630#issue-1421723310
