### ISSUE TITLE
自定义元素名，不硬编码 micro-app 前缀

### ISSUE THREAD

**Issue by maogongzi** [jd-opensource/micro-app#648]
## 背景

您好！十分感谢贵司开源的微前端框架，设计很精巧，已计划使用，目前有一个小疑问，就是代码逻辑里面针对 `tagName` 硬编码了一段自定义元素名的识别逻辑，貌似只能以 `micro-app` 开头，不是很理解这样的用意，但是好像后缀又可以随便改，请问这个逻辑未来可以放开吗，让用户自行定义元素名，只要不和已有元素冲突就可以

## 期望的效果

可以使用非 `micro-app` 开头的元素名称，例如 `ui-micro-app`

```
<ui-micro-app></ui-micro-app>
```

**Comment by bailicangdu** [comment]
micro-app开头主要是为了兼容react的polyfill，如果不考虑react，是可以自定义的
