### ISSUE TITLE
vue子应用进入路由时获取的from to为基座应用

### ISSUE THREAD

**Issue by caojunior** [jd-opensource/micro-app#65]
子应用在router.beforeEach中获取的from和to是基座应用的路由，导致渲染404

**Comment by caojunior** [comment]
使用history路由才有的问题，hash正常

**Comment by lovelyJason** [comment]
俺也遇到了这个问题

**Comment by lovelyJason** [comment]
> 使用history路由才有的问题，hash正常

你把这个issue close了，你怎么解决的，仁兄
