### ISSUE TITLE
报出的异常[micro-app] app microApps: An error occurred while parsing CSS:  Error: Declaration missing '{'

### ISSUE THREAD

**Issue by WJYman** [jd-opensource/micro-app#653]
## 问题描述
> 问题的具体描述
子应用是主应用拆分出去的项目，报出的异常[micro-app] app microApps: An error occurred while parsing CSS:
 Error: Declaration missing '{'
跟问题#232 类似，
但是我这边是"{",
他的问题是"}"
页面出来了，但是就是在控制台报错
## 复现步骤
1. 使用步骤都是按照你们官方的步骤一步一步来的
2.

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。
主应用
<img width="579" alt="image" src="https://user-images.githubusercontent.com/26448051/199642933-a59d243f-19f7-4ff1-945b-a1871d749e8c.png">
子应用和你们提供的demo 写法方式一致
<img width="613" alt="image" src="https://user-images.githubusercontent.com/26448051/199643074-85492cb8-46b0-4bf2-9dfc-0621be2ae862.png">

<img width="477" alt="image" src="https://user-images.githubusercontent.com/26448051/199642992-08860547-d24b-43da-9f1f-1bce117751ee.png">

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。

## 环境信息
- micro-app版本："@micro-zoe/micro-app": "^0.8.10",
- 主应用前端框架&版本："vue": "2.6.10",
- 子应用前端框架&版本："vue": "2.6.10",
- 构建工具&版本："@vue/cli-service": "4.4.6",

**Comment by WJYman** [comment]
目前都是在本地运行，出的报错

**Comment by WJYman** [comment]
https://github.com/WJYman/microAppProblem.git 
麻烦帮忙看看，谢谢

**Comment by WJYman** [comment]
@bailicangdu 麻烦了

**Comment by bailicangdu** [comment]
升级到1.0版本试一下，升级方式：https://micro-zoe.com/docs/1.x/#/zh-cn/transfer

**Comment by WJYman** [comment]
<img width="481" alt="image" src="https://user-images.githubusercontent.com/26448051/199680687-fa852d91-1f48-49a0-814e-60c612ba9eb1.png">
项目升级完后，报的错误 @bailicangdu

**Comment by WJYman** [comment]
<img width="441" alt="image" src="https://user-images.githubusercontent.com/26448051/199681080-c6c7c6d1-f59e-46e7-9e46-5f4f71aba80f.png">

import microApp from '@micro-zoe/micro-app'
microApp.start({
  'disable-memory-router': true, // 关闭虚拟路由系统
  'disable-patch-request': true // 关闭对子应用请求的拦截
})

**Comment by bailicangdu** [comment]
提供的案例无法运行，子应用使用了vue的scoped，可以关掉样式隔离  https://micro-zoe.com/docs/1.x/#/zh-cn/configure?id=disable-scopecss

**Comment by WJYman** [comment]
非常感谢，设置disable-scopecss 之后不报错了。

**Comment by ErnestWangZuNian** [comment]
新版的antd-pro很多用了where选择器编译 

:where(.css-dev-only-do-not-override-4sxmcs)%{transform:rotate(0deg);}25:where(.css-dev-only-do-not-override-4sxmcs)%{transform:rotate(90deg);}50:where(.css-dev-only-do-not-override-4sxmcs)%{transform:rotate(180deg);}75:where(.css-dev-only-do-not-override-4sxmcs)%{transform:rotate(270deg);}100:where(.css-dev-only-do-not-override-4sxmcs)%{transform:rotate(360deg);}}@media (max-width: 480){:where(.css-dev-only-do-not-override-4sxmcs).ant-pro-table .ant-table{width:100%;overflow-x:auto;}:where(.css-dev-only-do-not-override-4sxmcs).ant-pro-table .ant-table-thead>tr >th,:where(.css-dev-only-do-not-override-4sxmcs).ant-pro-table .ant-table-tbody>tr >th,:where(.css-dev-only-do-not-override-4sxmcs).ant-pro-table .ant-table-thead>tr >td,:where(.css-dev-only-do-not-override-4sxmcs).ant-pro-table .ant-table-tbody>tr >td{white-space:pre;}:where(.css-dev-only-do-not-override-4sxmcs).ant-pro-table .ant-table-thead>tr >th >span,:where(.css-dev-only-do-not-override-4sxmcs).ant-pro-table .ant-table-tbody>tr >th >span,:where(.css-dev-only-do-not-override-4sxmcs).ant-pro-table .ant-table-thead>tr >td >span,:where(.css-dev-only-do-not-override-4sxmcs).ant-pro-table .ant-table-tbody>tr >td >span{display:block;}}@media (max-width: 575px){:where(.css-dev-only-do-not-override-4sxmcs).ant-pro-table-toolbar{flex-direction:column;align-items:flex-start;justify-content:flex-start;height:auto;margin-block-end:16px;margin-inline-start:16px;padding-block:8px;padding-inline:8px;padding-block-start:16px;line-height:normal;}:where(.css-dev-only-do-not-override-4sxmcs).ant-pro-table-toolbar-title{margin-block-end:16px;}:where(.css-dev-only-do-not-override-4sxmcs).ant-pro-table-toolbar-option{display:flex;justify-content:space-between;width:100%;}:where(.css-dev-only-do-not-override-4sxmcs).ant-pro-table-toolbar-default-option{display:flex;flex:1;align-items:center;justify-content:flex-end;}} null this.cssText
然后有这种情况 然后这个(/^{\s*/正则满足不了 官方后续是否能考虑这种情况 就会抛出这个错误

**Comment by bailicangdu** [comment]
@ErnestWangZuNian 感谢反馈

**Comment by ErnestWangZuNian** [comment]
您好，我已收到邮件，我会尽快处理的。。。

**Comment by qiuzixu** [comment]
> 非常感谢，设置disable-scopecss 之后不报错了。

不报错了，但是子应用能正常运行吗，我这边出现这个报错的原因是子应用引用了uno.css，如果子应用删除这个引用就不会报错，但是样式丢失了。如果不删除这个引用，那么就报跟你一样的错误，加上这个样式隔离的属性之后，不报错，但是子应用也加载不出来。

**Comment by ErnestWangZuNian** [comment]
您好，我已收到邮件，我会尽快处理的。。。
