### ISSUE TITLE
sentry日志监控到 document.createElement is not a function，是从utils.ts/libs中的pureCreateElement报出来的

### ISSUE THREAD

**Issue by Ben07** [jd-opensource/micro-app#655]
## 问题描述
> 问题的具体描述

线上sentry经常会遇到`document.createElement is not a function`的错误日志。查看日志后发现错误来自micro-app  
暂时没有头绪，先提一个issue看看别人是否也遇到这类情况

## 复现步骤
我复现不了，参照下面的截图吧

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。
![image](https://user-images.githubusercontent.com/8055139/199877749-bed4ee86-8b06-43ac-a518-b7ccae8f474e.png)

sentry错误日志截图。 
![image](https://user-images.githubusercontent.com/8055139/199875526-bd865283-2f7b-4e5b-a142-0a08ef7a57b5.png)
相关js对应位置。 
![image](https://user-images.githubusercontent.com/8055139/199875759-0abe6ce8-7db2-4340-8e27-fb887d6ed8af.png)
按照关键信息去micro-app查找到的代码。 
<img width="1199" alt="image" src="https://user-images.githubusercontent.com/8055139/199875902-747f780e-2fda-41fe-86c9-80d6f4c9323c.png">

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。

## 环境信息
- micro-app版本：0.8.2
- 主应用前端框架&版本：react@16.14.0，react-dom@16.14.0
- 子应用前端框架&版本：react@16.14.26，react-dom@16.14.0
- 构建工具&版本：webpack@5.74.0

**Comment by Ben07** [comment]
排查了一下，是我们在基座里面对document有改动影响到了。

**Comment by whhlulu** [comment]
大佬你们的子应用怎么用sentry采集错误的？
我这子应用不能sentry.init，初始化之后错误就采集不到了，不初始化错误全部被基座采集去了，source-map又不好看了

**Comment by Ben07** [comment]
> 又

1. 主，子应用初始化Sentry
2. 加载子应用的时候，手动给子应用的资源内容拼一个#sourcemap进去。`microApp.start`里面的plugins。具体看文档
3. 子应用sentry上报加一个beforeSend。如果判断是主应用的js资源里的报错。用主应用的Sentry上报。主应用的Sentry可以通过window或别的方式传给子应用

你子应用初始化之后，错误采集不到是什么原因？有定位过吗？

**Comment by Ben07** [comment]
@whhlulu 
1. 主应用初始化Sentry
2. 子应用加载的时候对主应用的Sentry进行Proxy，改初始化逻辑，把sentry信息传给主应用。生成新的client
3. 加载子应用的时候，手动给子应用的资源内容拼一个#sourcemap进去。`microApp.start`里面的plugins。具体看文档
4. 子应用sentry上报加一个beforeSend。如果判断是主应用的js资源里的报错。用主应用的Sentry上报。主应用的Sentry可以通过window或别的方式传给子应用
5. 子应用加载或切换时，要更新Sentry的client。对应的api `Sentry.getCurrentHub().bindClient`

大概流程就这样
