### ISSUE TITLE
el-popover、el-tooltip无法卸载

### ISSUE THREAD

**Issue by zhangdf1989** [jd-opensource/micro-app#656]
## 问题描述
> 问题的具体描述
el-popover、el-tooltip无法卸载，切换页面时第一次会销毁，第二次下拉会出现在页面左上角
## 复现步骤
1.点开popover下拉
2.点击页面跳转

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。
![image](https://user-images.githubusercontent.com/38598656/199913231-a786e7d9-cc70-4301-8fdb-f0be20b5949a.png)

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。

## 环境信息
- micro-app版本：latest
- 主应用前端框架&版本：element-ui 2.15.9
- 子应用前端框架&版本：element-ui  2.15.7
- 构建工具&版本：webpack 4.0.0

**Comment by zhangdf1989** [comment]
仓库地址：https://gitee.com/zhangdanfeng1989/micro-app-demo.git
复现步骤：
![image](https://user-images.githubusercontent.com/38598656/200243796-9b75435b-d053-4985-a910-c448d80729d0.png)
点击click按钮，然后FirstChildAbout菜单->在点击FirstChildHome菜单->click按钮->FirstChildAbout菜单
![image](https://user-images.githubusercontent.com/38598656/200243960-127e9fc0-c4ce-48eb-af8f-fdda6d1d0b4a.png)
popover就无法销毁了

**Comment by bailicangdu** [comment]
升级到1.0版本可以解决，参考 https://micro-zoe.com/docs/1.x/#/zh-cn/transfer
