### ISSUE TITLE
子路由跳转影响父应用history，相关issue：155

### ISSUE THREAD

**Issue by BelenLuo-tech** [jd-opensource/micro-app#657]
对照 issue：[155]修改后发现并没有解决这个问题。
对照官网找了很久，没有找到对应issue，后面发现 beforeEach 和 afereach拿到的结果不一致。
猜想：是beforeEach中的重定向导致，这样改就解决了这个问题。

if (window.__MICRO_APP_ENVIRONMENT__) {
  const realBaseRoute = window.__MICRO_APP_BASE_ROUTE__

  let currentPath = null

  router.beforeEach(() => {
    if (typeof window.history.state?.current === 'string') {
      currentPath = window.history.state.current = window.history.state.current.replace(new RegExp(realBaseRoute, 'g'), '')
    }
  })

  router.afterEach(() => {
    if (typeof window.history.state === 'object') {
      window.history.state.current = currentPath
    }
  })
}

**Comment by bailicangdu** [comment]
micro-app版本是多少？

**Comment by bailicangdu** [comment]
主、子都是vue3，需要升级micro-app到1.0，开启虚拟路由可以解决上述问题 https://micro-zoe.com/docs/1.x/#/zh-cn/start
