### ISSUE TITLE
0.8.4版本microAddDataListener方法会执行两次

### ISSUE THREAD

**Issue by Lzy328** [jd-opensource/micro-app#661]
## 问题描述
> 问题的具体描述

## 复现步骤
1.0.8.4版本microAddDataListener方法会执行两次
2.第一次进入子应用通信的时候这里的打印会执行两次，

## 上传截图
> 
![image](https://user-images.githubusercontent.com/51940708/200453136-f67a68eb-fd62-4051-a7dc-f20dbf1b75fb.png)

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。

## 环境信息
- micro-app版本：
- 主应用前端框架&版本：
- 子应用前端框架&版本：
- 构建工具&版本：

**Comment by Lzy328** [comment]
重新修改截图

**Comment by bailicangdu** [comment]
基座发送数据的时候才会触发，检查一下是不是发送了2次数据
