### ISSUE TITLE
【生产环境报错】 [micro-app from runScript] app xxx:  TypeError: Cannot read properties of undefined (reading 'use')

### ISSUE THREAD

**Issue by zhou-tao** [jd-opensource/micro-app#662]
## 问题描述
开发环境一切正常，打包部署后打开到包括子应用页面时出现以下micro-app代码报错：
[micro-app from runScript] app xxx:  TypeError: Cannot read properties of undefined (reading 'use')

本应用右下角内容区为子应用区域

## 上传截图
- 生产环境截图：

![bb5ef996c83935d9ed7840fb5a9ffcd](https://user-images.githubusercontent.com/36221207/200511753-bb4ac7cf-3ff3-42cf-9ef2-ebdeca30710b.jpg)

- 相同代码开发环境正常截图：

![52bb8c75275ef7b4f472bfd4fbf8033](https://user-images.githubusercontent.com/36221207/200511953-4f95bb76-122d-4bec-abc6-9cc854ea01dc.jpg)

## 环境信息
- micro-app版本：0.8.10
- 主应用前端框架&版本：vue@2.6.14
- 子应用前端框架&版本：vue@2.6.14
- 构建工具&版本：webpack （vue-cli）

**Comment by zhou-tao** [comment]
@bailicangdu 报错问题解决了，现在定位到子应用可以正常加载但是子应用内的router-view未渲染，是路由配置问题吗？

**Comment by bailicangdu** [comment]
> @bailicangdu 报错问题解决了，现在定位到子应用可以正常加载但是子应用内的router-view未渲染，是路由配置问题吗？

大概率是路由问题

**Comment by liujuntao123** [comment]
@zhou-tao 请问是如何解决的呢，我也遇到了这个问题

**Comment by liujuntao123** [comment]
@bailicangdu 您好，是否可以贴一下解决方案呢？

**Comment by zhou-tao** [comment]
> @zhou-tao 请问是如何解决的呢，我也遇到了这个问题

我这边是之前老项目的vue.config.js内webpack配置问题。本质问题还是子项目内的报错，建议单开子应用查看是否有报错。
