### ISSUE TITLE
首次加载子应用白屏问题

### ISSUE THREAD

**Issue by llm9131142671** [jd-opensource/micro-app#663]
为什么通过左侧菜单切换，首次加载子应用的时候会出现白屏，后续再切换子应用就不会白屏，但有时会闪一下

**Comment by bailicangdu** [comment]
因为子应用需要加载资源、解析、执行，这些都需要时间的

**Comment by bailicangdu** [comment]
可以使用预加载提升首屏渲染时间

**Comment by llm9131142671** [comment]
左侧菜单是在主应用上的，首次切换子应用，左侧菜单也会白屏吗

**Comment by bailicangdu** [comment]
这种情况在子应用是nextjs遇到过，主要是因为开发工具在应用渲染时会重置一次文档，也只在开发环境出现

**Comment by happy760690** [comment]
我只要切换应用或者应用内跳转就会出现白色闪屏，整个页面重新渲染，然后再重新出现页面。

**Comment by LuGuojing** [comment]
这个问题解决了吗，我也有这个问题，为什么被关了
