### ISSUE TITLE
vite子应用样式前缀问题

### ISSUE THREAD

**Issue by hdhsyyyyy** [jd-opensource/micro-app#665]
官网vite应用demo如图, 子应用样式会带micro-app[name=vite]前缀, 
<img width="1511" alt="image" src="https://user-images.githubusercontent.com/16219970/201032893-a2df2cf3-1111-4efc-bef3-90d67bece2ca.png">

但是micro-app-demo里, 子应用样式就不会带前缀，这是什么原因
<img width="1488" alt="image" src="https://user-images.githubusercontent.com/16219970/201033365-f8826ec1-4d09-4482-944c-3552128d7d0a.png">

**Comment by raoenhui** [comment]
可以看下这个文档，https://micro-zoe.com/docs/1.x/#/zh-cn/scopecss
