### ISSUE TITLE
micro-app 创建后，子应用资源加载失败，不会mount，也不会触发 error，无法知道这个错误

### ISSUE THREAD

**Issue by smallalso** [jd-opensource/micro-app#667]
## 背景
> micro-app 创建后，子应用资源加载失败，不会mount，也不会触发 error，无法知道这个错误

## 期望的效果

能有方法，通知 某个 micro-app 创建失败了

**Comment by raoenhui** [comment]
https://micro-zoe.com/docs/1.x/#/zh-cn/life-cycles?id=_5-error  这个生命周期可以监听到吗？

**Comment by surele** [comment]
同样，子应用无法加载，未报错，可以监听到unmount, 其他的都监听不到

**Comment by bailicangdu** [comment]
> 同样，子应用无法加载，未报错，可以监听到unmount, 其他的都监听不到

能提供一个简易的demo帮助复现吗
