### ISSUE TITLE
子应用被多个基座应用嵌入时。生产环境切换基座应用会出现应用中访问 子应用的请求跨域

### ISSUE THREAD

**Issue by yahoolcj** [jd-opensource/micro-app#668]
## 问题描述
> 问题的具体描述
micro-app子应用被多个基座应用嵌入时。生产环境切换基座应用会出现应用中访问 子应用的请求跨域。 例如 A B基座都嵌入了C子应用， A访问C后 B访问C ，在B应用中会出现子应用跨域A的报错 
## 复现步骤
1.
2.

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。
![image](https://user-images.githubusercontent.com/47837279/201308813-aa127eb9-ae0e-4a8f-90b8-ac51cb24edbd.png)

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。

## 环境信息
- micro-app版本：
- 主应用前端框架&版本：
- 子应用前端框架&版本：
- 构建工具&版本：

**Comment by raoenhui** [comment]
多个基座应用之前新开页面跳转呢？

**Comment by yahoolcj** [comment]
> 多个基座应用之前新开页面跳转呢？

单独开启某个基座应用访问没问题，但是当多个基座都在浏览器打开后，并且他们访问的都是同一个子应用地址，就会出现如上情况。网关已经配置了允许跨域，为了防止浏览器缓存我在访问子应用的url地址后面加上了时间戳

**Comment by bailicangdu** [comment]
没遇到这种情况，有没有什么方式帮助我们复现？

**Comment by yahoolcj** [comment]
> 没遇到这种情况，有没有什么方式帮助我们复现？

**Comment by yahoolcj** [comment]
> 没遇到这种情况，有没有什么方式帮助我们复现？

知道是什么原因了，是资源被浏览器缓存，导致origin错误。  A基座访问了子应用之后 加载了资源 origin来自A基座地址，资源被缓存在磁盘。 B基座再访问时 资源从浏览器缓存中被读取，但是，origin还是A基座的地址，所以浏览器提示我资源跨域来自不同host的origin。这个问题其实可以在官网层做允许全域跨域访问的设置，不过我们的网关设置必须同host。 目前在前端代码上的解决办法是在micro-app的fetch方法中 对资源的访问url加上基座表标识，这样能保证不同基座读取的资源文件地址不同 同基座也能保持缓存

**Comment by AYWK** [comment]
资源响应头加下：Vary: Origin 试试呢

**Comment by liulovegame** [comment]
> > 没遇到这种情况，有没有什么方式帮助我们复现？
> 
> 知道是什么原因了，是资源被浏览器缓存，导致origin错误。 A基座访问了子应用之后 加载了资源 origin来自A基座地址，资源被缓存在磁盘。 B基座再访问时 资源从浏览器缓存中被读取，但是，origin还是A基座的地址，所以浏览器提示我资源跨域来自不同host的origin。这个问题其实可以在官网层做允许全域跨域访问的设置，不过我们的网关设置必须同host。 目前在前端代码上的解决办法是在micro-app的fetch方法中 对资源的访问url加上基座表标识，这样能保证不同基座读取的资源文件地址不同 同基座也能保持缓存

单独访问了子应用后，在访问主应用就跨域了，因为origin原因我也遇到了，想问下你这边怎么解决的，重配置主应用这个fetch吗？

**Comment by yahoolcj** [comment]
> > > 没遇到这种情况，有没有什么方式帮助我们复现？
> > 
> > 
> > 知道是什么原因了，是资源被浏览器缓存，导致origin错误。 A基座访问了子应用之后 加载了资源 origin来自A基座地址，资源被缓存在磁盘。 B基座再访问时 资源从浏览器缓存中被读取，但是，origin还是A基座的地址，所以浏览器提示我资源跨域来自不同host的origin。这个问题其实可以在官网层做允许全域跨域访问的设置，不过我们的网关设置必须同host。 目前在前端代码上的解决办法是在micro-app的fetch方法中 对资源的访问url加上基座表标识，这样能保证不同基座读取的资源文件地址不同 同基座也能保持缓存
> 
> 单独访问了子应用后，在访问主应用就跨域了，因为origin原因我也遇到了，想问下你这边怎么解决的，重配置主应用这个fetch吗？

是的，通过给fetch拦截中的资源地址添加基座的标识。

**Comment by zedwone** [comment]
> > > > 没遇到这种情况，有没有什么方式帮助我们复现？
> > > 
> > > 
> > > 知道是什么原因了，是资源被浏览器缓存，导致origin错误。 A基座访问了子应用之后 加载了资源 origin来自A基座地址，资源被缓存在磁盘。 B基座再访问时 资源从浏览器缓存中被读取，但是，origin还是A基座的地址，所以浏览器提示我资源跨域来自不同host的origin。这个问题其实可以在官网层做允许全域跨域访问的设置，不过我们的网关设置必须同host。 目前在前端代码上的解决办法是在micro-app的fetch方法中 对资源的访问url加上基座表标识，这样能保证不同基座读取的资源文件地址不同 同基座也能保持缓存
> > 
> > 
> > 单独访问了子应用后，在访问主应用就跨域了，因为origin原因我也遇到了，想问下你这边怎么解决的，重配置主应用这个fetch吗？
> 
> 是的，通过给fetch拦截中的资源地址添加基座的标识。

请问如何添加基座的标识呢
