### ISSUE TITLE
JS 沙箱咱是不 也能借鉴一下 这个库的 Iframe 方式？

### ISSUE THREAD

**Issue by LengYXin** [jd-opensource/micro-app#670]
## 背景
> 描述您希望改进的问题。

## 期望的效果

https://github.com/Tencent/wujie

**Comment by jardenliu** [comment]
也有一些奇怪的问题  例如我遇到的这个
https://github.com/Tencent/wujie/issues/256

**Comment by LengYXin** [comment]
> 也有一些奇怪的问题 例如我遇到的这个 [Tencent/wujie#256](https://github.com/Tencent/wujie/issues/256)

确实是。直接 instanceof HTMLElement  应该是当前 iframe window 里面的？然后创建的又是 window.top 顶层的？
