### ISSUE TITLE
createDocumentFragment 会有元素逃逸现象

### ISSUE THREAD

**Issue by ylji1990** [jd-opensource/micro-app#672]
## 问题描述
> 问题的具体描述

子应用通过 以下方式插入元素 造成元素逃逸

var fragment = document.createDocumentFragment();
var link = document.createElement("link");
link.href ="xxxxxx.css";
fragment.appendChild(link);
var script = document.createElement("script");
script.src ="xxxxx.js";
fragment.appendChild(script);
document.head.appendChild(fragment)

后续改造成如下代码防止逃逸
var headEle = document.head;
var link = document.createElement("link");
link.href ="xxxxxx.css";
headEle.appendChild(link);
var script = document.createElement("script");
script.src ="xxxxx.js";
headEle.appendChild(script);

## 复现步骤
1.
2.

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。

改造前

![image](https://user-images.githubusercontent.com/38064469/202075620-bab6feaa-944d-4f9e-9545-a00820992c41.png)

![image](https://user-images.githubusercontent.com/38064469/202076726-58fe638a-2c96-497a-857a-c0f0cad346fb.png)

改造后

![image](https://user-images.githubusercontent.com/38064469/202078370-c6107d08-96f0-4570-97ff-63e1233bdfcc.png)

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。

## 环境信息
- micro-app版本：
1.0.0-alpha.10
- 主应用前端框架&版本：
react17.0.2
- 子应用前端框架&版本：
react17.0.2
- 构建工具&版本：
webpack 5

**Comment by bailicangdu** [comment]
感谢反馈
