### ISSUE TITLE
父子都是hash模式，加载资源错误

### ISSUE THREAD

**Issue by ssx1477651687** [jd-opensource/micro-app#674]
父子都是hash模式，父子应用在同一页面，当点击父应用路由跳转时，先请求子服务的资源，再去卸载子服务，导致主服务页面加载报错

**Comment by ssx1477651687** [comment]
![image](https://user-images.githubusercontent.com/49713232/202188849-1dc04a9e-1dbc-452c-9820-5290d2db6e02.png)
主服务8001 子服务8002
在同一个页面里，点击主服务模块 进行路由跳转，请求的确实8002域名的资源

**Comment by ssx1477651687** [comment]
主 react16  子 vue3

**Comment by zhou-tao** [comment]
> 父子都是hash模式，父子应用在同一页面，当点击父应用路由跳转时，先请求子服务的资源，再去卸载子服务，导致主服务页面加载报错

父子都使用hash，是不是无法部在同一端口内？因为子应用 nginx 若映射为/child 则无法满足父应用hash规则。
