### ISSUE TITLE
请问是否可以支持开发环境子应用调试？比如 vue-devtools

### ISSUE THREAD

**Issue by zhou-tao** [jd-opensource/micro-app#676]

**Comment by sailve68** [comment]
如果父应用是Vue的话，可以尝试这个方法 https://github.com/vuejs/devtools/issues/64#issuecomment-238025184

**Comment by qq1066536** [comment]
### `Mirco-App` 中启用子应用的`vue-devtools`
> Mirco-app框架中，加载子应用后，`vue-devtools` 无法解析子应用对应的UI 组件和属性，不利于开发调试

#### 处理办法
- 基座中添加生命周期
```javascript
MircoApp.start({
  ...,
  lifeCycles:{
    mounted(e) {
      //window.__MICRO_APP_SUB_APP_VM__ 定义子应用中的$VM
     // $vm 为基座实例
      /*
      * 由于需要实时刷新组件，此方法判断process.env.NODE_ENV，只使用于开发环境
      * 
      * */
      if(window.__MICRO_APP_SUB_APP_VM__&&process.env.NODE_ENV==='develop'){
        //判断$vm.$children长度，默认为1，决定子应用插入方法
        if(window.GLOBAL.$vm.$children.length===1)
          $vm.$children.push(window.__MICRO_APP_SUB_APP_VM__)
        else $vm.$children.splice(1,1,window.__MICRO_APP_SUB_APP_VM__)
      }
    }
  }
})
```
- 子应用`main.js`添加`window.rawWindow.__MICRO_APP_SUB_APP_VM__`,用于基座中的调用

```javascript

window.rawWindow.__MICRO_APP_SUB_APP_VM__=new Vue({
  ...,
})
```
[参考链接](https://juejin.cn/post/6850418121052946440)

**Comment by zhou-tao** [comment]
> 

参照这种做法，打印出来子应用实例是添加进父应用的children了，但是 vue-devtool 中还是无法显示子应用。

**Comment by zhou-tao** [comment]
> ### `Mirco-App` 中启用子应用的`vue-devtools`
> > Mirco-app框架中，加载子应用后，`vue-devtools` 无法解析子应用对应的UI 组件和属性，不利于开发调试
> 
> #### 处理办法
> * 基座中添加生命周期
> 
> ```js
> MircoApp.start({
>   ...,
>   lifeCycles:{
>     mounted(e) {
>       //window.__MICRO_APP_SUB_APP_VM__ 定义子应用中的$VM
>      // $vm 为基座实例
>       /*
>       * 由于需要实时刷新组件，此方法判断process.env.NODE_ENV，只使用于开发环境
>       * 
>       * */
>       if(window.__MICRO_APP_SUB_APP_VM__&&process.env.NODE_ENV==='develop'){
>         //判断$vm.$children长度，默认为1，决定子应用插入方法
>         if(window.GLOBAL.$vm.$children.length===1)
>           $vm.$children.push(window.__MICRO_APP_SUB_APP_VM__)
>         else $vm.$children.splice(1,1,window.__MICRO_APP_SUB_APP_VM__)
>       }
>     }
>   }
> })
> ```
> 
> * 子应用`main.js`添加`window.rawWindow.__MICRO_APP_SUB_APP_VM__`,用于基座中的调用
> 
> ```js
> window.rawWindow.__MICRO_APP_SUB_APP_VM__=new Vue({
>   ...,
> })
> ```
> 
> [参考链接](https://juejin.cn/post/6850418121052946440)

参照这种做法，打印出来子应用实例是添加进父应用的children了，但是 vue-devtool 中还是无法显示子应用。
