### ISSUE TITLE
主应用vue2 + webpack ,vue3 + vite的子应用图片地址的前缀是主应用的前缀地址 404 

### ISSUE THREAD

**Issue by skyLoveSnap** [jd-opensource/micro-app#677]
子应用 vue3  + vite  : 
host: http://localhost:4007
    <img alt="Vue logo" class="logo" :src="logoPath" width="125" height="125" />
const logoPath = new URL("../src/assets/logo.svg", import.meta.url).href;

主应用 vue2  webpack
host: http://localhost:3000
报错： 用的是主应用前缀 所以404 
![企业微信截图_93076ad8-1a35-408e-b683-3a61a38f0ed7](https://user-images.githubusercontent.com/40157361/202961785-00929f61-926f-413a-b47d-8f1f3d6e438d.png)

**Comment by message163** [comment]
我也是这个问题

**Comment by message163** [comment]
解决了vite 降级3.0.0 好使了

**Comment by HarperGG** [comment]
我也遇到了这个问题，目前v4使用 import.meta.url 方式导入静态文件，也会有这个问题。
