### ISSUE TITLE
百度地图接入成功了吗？

### ISSUE THREAD

**Issue by X-J-C** [jd-opensource/micro-app#679]
## 问题描述
> 直接引用百度地图会报跨域，所以普通街道的用"vue-baidu-map",基本功能都能实现，但是现在突然加了一个需要，要增加3D。想引入“vue-bmap-gl”，发现又报跨域。项目用的是vue2

## 复现步骤
1.npm install vue-bmap-gl --save
2.在main.js引用就报跨域

## 上传截图
>
![image](https://user-images.githubusercontent.com/48943037/203491151-4f4f973c-e258-4bfe-acbf-7da40bd289f2.png)

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。

## 环境信息
- micro-app版本：1.0.0-alpha.9
- 主应用前端框架&版本：vue2+element-ui
- 子应用前端框架&版本：vue2+element-ui
- 构建工具&版本：Visual Studio Code

**Comment by raoenhui** [comment]
下载到本地引入，避开跨域问题

**Comment by iYogic2** [comment]
按此操作 do like this:  https://github.com/micro-zoe/micro-app/issues/1009
