### ISSUE TITLE
子应用在SSR时，能否通过变量知道其所处环境？

### ISSUE THREAD

**Issue by qianqian05723** [jd-opensource/micro-app#68]
![image](https://user-images.githubusercontent.com/17306867/130952335-2bcfc262-14e2-491d-8362-bafa39a7067c.png)
目前根据文档已知的是在CSR是可以判断的，目前我用了nuxt做子应用，需要在nuxt插件执行时判断所处环境...不知道有没有其他变量可以判断?

**Comment by bailicangdu** [comment]
不可以，目前只能在浏览器环境下执行

**Comment by qianqian05723** [comment]
可以了，我的nuxt子应用的是koa做服务，然后主应用改写fetch在请求headers中传参，子应用能获取到参数，谢谢！
