### ISSUE TITLE
Uncaught SyntaxError: Cannot use import statement outside a module.问题

### ISSUE THREAD

**Issue by skyLoveSnap** [jd-opensource/micro-app#680]
## 问题描述
> 问题的具体描述
Uncaught SyntaxError: Cannot use import statement outside a module.
## 复现步骤
1.基座应用vue2 
2.子应用vue3 + vite

## 上传截图
Uncaught SyntaxError: Cannot use import statement outside a module

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。

## 环境信息
- micro-app版本：
- 主应用前端框架&版本：
- 子应用前端框架&版本：
- 构建工具&版本：

**Comment by trry-hub** [comment]
问题解决了么
