### ISSUE TITLE
mathjs 引起的卡死

### ISSUE THREAD

**Issue by ringgoyao** [jd-opensource/micro-app#682]
## 问题描述
> 问题的具体描述
子应用引入mathjs后卡死，移除后正常，不知道什么原因，微信群里有人碰到同样的问题

mirco版本  0.8.2

**Comment by raoenhui** [comment]
可检查mathjs里面是否有重写原生浏览器方法

**Comment by Constaline** [comment]
可以换用 [decimal.js](https://github.com/MikeMcl/decimal.js) 处理
