### ISSUE TITLE
【缺陷】父子应用均为hash路由时，无法实现同端口下部署父子应用

### ISSUE THREAD

**Issue by zhou-tao** [jd-opensource/micro-app#683]
## 问题描述
父子应用均使用hash路由

统一端口 80 下
父应用部署路径为： /
子应用部署为：/child

此时，父应用无论如何设置url，均无法满足即加载到子应用资源还能满足子应用hash路由（因为子应用为/child开头则不满足父应用根路由hash规则）

该问题比较棘手且场景较多，希望得到解决方案。

## 环境信息
- micro-app版本：0.8.10
- 主应用前端框架&版本：vue^2.7.10
- 子应用前端框架&版本：vue^2.6.10
- 构建工具&版本：webpack^5

**Comment by ZoeyZhong** [comment]
我也面临同样的问题

环境信息：
主应用前端框架&版本：angular^12.2.0
子应用前端框架&版本：angular^12.2.0
