### ISSUE TITLE
unmountApp手动卸载子应用后，再次跳转子应用不加载子应用

### ISSUE THREAD

**Issue by Luolei1992** [jd-opensource/micro-app#684]

**Comment by Luolei1992** [comment]
正常是这样
![13](https://user-images.githubusercontent.com/23149226/205211406-b5c8b197-9626-4407-961c-419864e26c05.png)

手动卸载后再次进入子应用，micro-app标签都没有了
![14](https://user-images.githubusercontent.com/23149226/205211733-5cb5318f-d412-4ff6-a34d-2e38ddc9f445.png)

**Comment by justCharlesLeft** [comment]
我也遇到这个问题咯

**Comment by raoenhui** [comment]
用reload试试呢，https://micro-zoe.com/docs/1.x/#/zh-cn/api?id=reload

**Comment by zhou-tao** [comment]
> 用reload试试呢，https://micro-zoe.com/docs/1.x/#/zh-cn/api?id=reload

reload 也无效, unmountApp(‘app’) 后不仅是app这个子应用无法加载，其他的都加载不了。。

**Comment by zhou-tao** [comment]
> > 用reload试试呢，https://micro-zoe.com/docs/1.x/#/zh-cn/api?id=reload
> 
> reload 也无效, unmountApp(‘app’) 后不仅是app这个子应用无法加载，其他的都加载不了。。

补充一波: 好像是在unmountApp当前激活的子应用时会发生这个问题，切到其他子应用再来卸载这个app子应用则正常。

**Comment by k-maikou** [comment]
> 我也遇到这个问题咯

后面有解决好这个问题吗

**Comment by LeYi713** [comment]
遇到同一个问题，有解决了的吗？

**Comment by zhou-tao** [comment]
> 遇到同一个问题，有解决了的吗？

可以使用延迟卸载解决的，子应用关闭后再卸载。

**Comment by LeYi713** [comment]
> > 遇到同一个问题，有解决了的吗？
> 
> 可以使用延迟卸载解决的，子应用关闭后再卸载。

这个问题已经使用这种方式解决了。还有个新问题，当前主应用只有一个子应用时，进行卸载，在切回该子应用或其他子应用都无法加载，同样的micro-app标签都没有了。这个问题大佬有遇到不
