### ISSUE TITLE
uniapp支持

### ISSUE THREAD

**Issue by qian153087222** [jd-opensource/micro-app#685]
## uniapp的H5为子应用的时候 返回的是 Please enable JavaScript to continue.
> 希望能增加uniapp的H5支持。

**Comment by qian153087222** [comment]
<img width="609" alt="image" src="https://user-images.githubusercontent.com/36727433/205251311-085a7680-131f-4b99-88cf-b74dba2dce9b.png">

**Comment by raoenhui** [comment]
uniapp打包后的文件是否为esmodule？如果为esmodule则会有问题，可以看看uniapp中是否能关闭esmodule打包
