### ISSUE TITLE
 __MICRO_APP_PUBLIC_PATH__ 每次都是进来的第一个子应用

### ISSUE THREAD

**Issue by lizesheng0313** [jd-opensource/micro-app#689]
## 问题描述
> 问题的具体描述
   不同的子应用取得的环境变量 __MICRO_APP_PUBLIC_PATH__ 每次都是进来的第一个子应用，在切换子应用后，当前的__MICRO_APP_PUBLIC_PATH__  还是上一个子应用的值  请问是不是   不同的端口识别不了

## 复现步骤
1.        <micro-app name='ptp-base' path='/ptp-base' url='http://172.20.1.90:7000' baseroute='ptp-base' />
          <micro-app name='ptp-sbl' path='/ptp-sbl' url='http://172.20.1.90:7001' baseroute='ptp-sbl' />
          <micro-app name='ptp-portal' path='/ptp-portal' url='http://172.20.1.90:7002' baseroute='ptp-portal' />
2.

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。

## 环境信息
- micro-app版本：
- 主应用前端框架&版本：
- 子应用前端框架&版本：
- 构建工具&版本：

**Comment by raoenhui** [comment]
请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。
