### ISSUE TITLE
Any way to use createWebHistory in vite sub app?

### ISSUE THREAD

**Issue by byoungd** [jd-opensource/micro-app#69]
As mentioned in [`document`](https://cangdu.org/micro-app/docs.html#/zh-cn/advanced?id=_2%e3%80%81%e9%80%82%e9%85%8dvite), supporting `Vite` is **expensive** and for now micro-app official doc recommends using `createWebHashHistory` as work around but `hash router` is not `elegant`.

`Vite` is growing fast and more popular in modern web development.It's possible to use Vue3, TypeScript to create enterprise-level development environments. As far as application grows larger, The slow feedback from local dev envrionment  can greatly affect developers' productivity and happiness. So we really want `micro-app` can porvide optimized support fo vite.

Thanks for reply!

**Comment by bailicangdu** [comment]
I will add a demo for this
