### ISSUE TITLE
添加预加载控制台报错

### ISSUE THREAD

**Issue by daughterRui** [jd-opensource/micro-app#690]
## 问题描述
 添加预加载后报错
报错信息如下：
@micro-zoe-00601836.js:1 [micro-app] app sub-app-mcsp: element does not exist in lifecycle error
@micro-zoe-00601836.js:1 [micro-app] app sub-app-mcsp: element body is missing

用的方式三
microApp.start({
  preFetchApps: [
    { name: 'my-app', url: 'xxx' }
  ],
})

## 环境信息
- micro-app版本：1.0.0-alpha.10
- 主应用前端框架&版本：vite2.0，vue3
- 子应用前端框架&版本：vue2

**Comment by raoenhui** [comment]
vite要等1.0.0正式版本出来后，再支持

**Comment by daughterRui** [comment]
vite 沙箱 大概什么时候能发布

**Comment by lovelyJason** [comment]
preFetchApps怎么加了感觉没什么太大效果
```js
  microApp.start({
    'disable-memory-router': true,
    // 'router-mode': 'native-scope',
    preFetchApps: [
      {
        name: 'childPower',
        url: 'http://localhost:8080/child/power/',
        level: 1,
        iframe: true,
      },
    ],
```
