### ISSUE TITLE
H5加上padding兼容主应用就无法显示

### ISSUE THREAD

**Issue by qian153087222** [jd-opensource/micro-app#691]
## 问题描述
> H5加上padding兼容主应用就无法正常显示

## 复现步骤
 var coverSupport = 'CSS' in window && typeof CSS.supports === 'function' && (CSS.supports('top: env(a)') ||
                CSS.supports('top: constant(a)'))

## 上传截图
<img width="1176" alt="image" src="https://user-images.githubusercontent.com/36727433/206381378-3dceb1e0-7b14-49ab-a547-4a940f3bcd14.png">
<img width="1396" alt="image" src="https://user-images.githubusercontent.com/36727433/206381532-bd139bb9-8a81-4e9d-be6b-0664b9ce6398.png">

## 版本
"micro-app": "^1.0.2",

**Comment by raoenhui** [comment]
子应用要往window上加变量，需先获取外部真实window，可以看https://micro-zoe.com/docs/1.x/#/zh-cn/questions?id=_6%e3%80%81%e5%ad%90%e5%ba%94%e7%94%a8%e5%9c%a8%e6%b2%99%e7%ae%b1%e7%8e%af%e5%a2%83%e4%b8%ad%e5%a6%82%e4%bd%95%e8%8e%b7%e5%8f%96%e5%88%b0%e5%a4%96%e9%83%a8%e7%9c%9f%e5%ae%9ewindow%ef%bc%9f
