### ISSUE TITLE
基座应用使用windows传递一个页面组件到子应用，但是子应用没办法使用这个页面组件

### ISSUE THREAD

**Issue by haoayou4211** [jd-opensource/micro-app#692]
并报错：
 $listeners is readonly.
 $attrs is readonly

子应用及基座应用的vue版本号是不一致的。请问一下这个有什么好的解决方案嘛？
可以 将基座应用的组件，挂载到 windows上供子应用使用嘛？

**Comment by raoenhui** [comment]
该页面组件提成公共包，两边都可以使用
