### ISSUE TITLE
同时用了vue-smooth-dnd 插件  页面报错  

### ISSUE THREAD

**Issue by hzfvictory** [jd-opensource/micro-app#695]
## 复现步骤
1.  import { Container, Draggable } from "vue-smooth-dnd";
2. 直接引用就报错了  

## 上传截图
> ![image](https://user-images.githubusercontent.com/38562125/208419274-23bbfa1c-a7f0-4a22-9da3-d0ba8ff28010.png)

## 环境信息
- micro-app版本：0.81.10
- 主应用前端框架&版本：vue2
- 子应用前端框架&版本：vue2
- 构建工具&版本：webpack

**Comment by bailicangdu** [comment]
能提供个demo看一下吗

**Comment by hzfvictory** [comment]
> 能提供个demo看一下吗

https://github.com/hzfvictory/micro-test-smooth-dnd    这个地址你克隆下

**Comment by hzfvictory** [comment]
咋样  用提供的插件是不是能解决

**Comment by tong822218** [comment]
你好请问解决了吗 我也遇到了同样的问题

**Comment by oYangMr** [comment]
请问解决了吗，我也是父子应用 同时用了vue-smooth-dnd 插件 页面报错

**Comment by tong822218** [comment]
这个问题我已经解决，有个大神为了解决这个问题另开了一个仓库，vue-dndrop   你只需要把vue-smooth-dnd 包删除，换成vue-dndrop包即可，两个包用法完全一样。希望能帮到你
