### ISSUE TITLE
子应用中的JS 被自动注释了

### ISSUE THREAD

**Issue by lizesheng0313** [jd-opensource/micro-app#698]
## 问题描述
> 问题的具体描述

## 复现步骤
1. 
2.

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。
<img width="886" alt="image" src="https://user-images.githubusercontent.com/23352222/209457723-fc706684-ae8c-4063-9b77-90c5e486cbe6.png">

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。

## 环境信息
- micro-app版本：
- 主应用前端框架&版本：
- 子应用前端框架&版本：
- 构建工具&版本：

**Comment by raoenhui** [comment]
inline script extract by micro-app，内联js微前端已经提取了

**Comment by maorunjie-2019** [comment]
> 

提取到哪里了呢

**Comment by bailicangdu** [comment]
> > 
> 
> 提取到哪里了呢

提取到后台以Function形式运行
