### ISSUE TITLE
子应用样式加载问题

### ISSUE THREAD

**Issue by UltramanWeiLai** [jd-opensource/micro-app#699]
我这边碰到了一个问题，我子应用有个来自于 第三方集合的 css 文件，大概有 600kb（直接查看构建后产物的文件大小） 左右，开发的时候很正常，但是部署到服务器上后样式总是丢失，经过调试后发现，micro-app-head 中的 style 中的内容被截取了，只剩下 10kb（在控制台中通过获取元素节点查看 innerHTML 控制台提示的内容大小） 的内容了，请问一下这种情况具体发生的原因和如何处理？

**Comment by bailicangdu** [comment]
可能是样式隔离的问题，关闭样式隔离试一下

**Comment by CoolBoyCaoBo** [comment]
@bailicangdu 你好，我们在实际使用过程中也出现了这样的问题，按照您的这个方案，我们针对发生问题的子应用关闭了样式隔离问题可以解决，但是子应用的样式影响到基座的样式了。目前还有其他的办法解决样式丢失的问题哇？

**Comment by bailicangdu** [comment]
> @bailicangdu 你好，我们在实际使用过程中也出现了这样的问题，按照您的这个方案，我们针对发生问题的子应用关闭了样式隔离问题可以解决，但是子应用的样式影响到基座的样式了。目前还有其他的办法解决样式丢失的问题哇？

可以提供出问题的css文件帮助复现问题吗？
