### ISSUE TITLE
不同子应用的子路由之间无法跳转

### ISSUE THREAD

**Issue by caojunior** [jd-opensource/micro-app#70]
## 问题描述
> 问题的具体描述
子应用的子路由与其他子应用的子路由跳转报404，使用history.pushState window.dispatchEvent(new PopStateEvent('popstate', { state: null }))在子应用不同路由跳转正常，两个子应用之间也正常，只有两个子应用的子路由下无法跳转
## 复现步骤
1.进入localhost:3000/router1#/databoard/a
2.切换到localhost:3000/router2#/sys/user

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。

## 环境信息
- micro-app版本：0.2.5
- 基座应用的前端框架和版本：vue2 2.6.10
- 子应用的前端框架和版本：vue2 2.6.10
- 构建工具&版本：

**Comment by bailicangdu** [comment]
因为当前子应用也会接受到popstate事件并匹配路由，当前路由不匹配时会如果设置了404，可能会兜底到404，所以路由设置要注意

**Comment by caojunior** [comment]
@bailicangdu 已经去掉404了，还是一样有问题，最后通过 this.$router.push({ path: '/' }).then(() => {})这样解决了

**Comment by caojunior** [comment]
@bailicangdu 能再请教个问题吗，现在我们需要支持携带cookie，自定义了fetch，设置credentials: 'include'，发现chrome高版本是支持的，但chrome65还是有问题，我看fetch应该是48以上就该支持的

**Comment by bailicangdu** [comment]
> @bailicangdu 能再请教个问题吗，现在我们需要支持携带cookie，自定义了fetch，设置credentials: 'include'，发现chrome高版本是支持的，但chrome65还是有问题，我看fetch应该是48以上就该支持的

可以用axios或ajax代替fetch

**Comment by caojunior** [comment]
@bailicangdu localhost:3000/router1#/a 跳到localhost:3000/router2#/a 使用this.$router.push({ path: '/' }).then(() => {history.replaceState window.dispatchEvent })这样是可以的，如果是/router/router1#/a 跳/router/router2#/a就有问题，对这块跳转还是不太懂，还有什么方法是清除state来实现跳转的，现在就剩这个问题卡了我两天。。

**Comment by bailicangdu** [comment]
有可复现的代码吗

**Comment by caojunior** [comment]
好像是keep-alive的问题，去掉就可以了。
