### ISSUE TITLE
子应用使用百度地图嵌入主应用后无法正常使用(跨域)

### ISSUE THREAD

**Issue by wang0713** [jd-opensource/micro-app#700]
**项目版本**
micro-app: ^0.8.10
主应用: vue  ^2.6.14
子应用: react: 17.x, umi: ^3.5.33

**复现步骤**
vue 主应用引入百度地图(子应用引入百度地图不生效)
 <script type="text/javascript" src="https://api.map.baidu.com/api?v=2.0&ak=key值"></script>
子应用打开地图可以显示但是无法正常使用
<img width="1308" alt="WeChat680c8af325a19d7c4b4da81f9ec854d2" src="https://user-images.githubusercontent.com/105999835/210134526-e92a6194-6d2d-4d46-9485-31defd2379ef.png">
<img width="1041" alt="WeChat35a2d5dcc92f75bc4addbe9ba05230f5" src="https://user-images.githubusercontent.com/105999835/210134591-a31f2f62-bbaa-4b3f-9c27-a201f9998026.png">
![1672135588204](https://user-images.githubusercontent.com/105999835/210134603-f0416445-42e8-4240-ac15-ff5e691ac5e7.jpg)

**Comment by JE-lee** [comment]
要本地化

**Comment by DCdafan** [comment]
可以放在父容器引入～

**Comment by iYogic2** [comment]
按此操作 do like this:  https://github.com/micro-zoe/micro-app/issues/1009
