### ISSUE TITLE
在主应用上使用 document.body.appendChild 和 document.body.append 插入元素，导致元素被插入到子应用内

### ISSUE THREAD

**Issue by kelvin-lemon** [jd-opensource/micro-app#702]
## 问题描述
在主应用上使用 document.body.appendChild 和 document.body.append 插入元素，导致元素被插入到子应用内。

## 目标
希望在主应用内执行 document.body.appendChild 和 document.body.append 元素插入到主应用上。

## 复现步骤
在主应用上使用 document.body.appendChild 和 document.body.append 插入元素。

## 环境信息
- micro-app版本：[v1.0.0-alpha.10](https://github.com/micro-zoe/micro-app/releases/tag/v1.0.0-alpha.10)
- 主应用前端框架&版本：vu3
- 子应用前端框架&版本：vu3
- 构建工具&版本：webpack

**Comment by kelvin-lemon** [comment]
补充：
子应用内加载使用 document.currentScript 的 script 标签后，子应用操作元素时会绑定元素作用域被强制绑定到子应用内，且不会解绑

**Comment by bailicangdu** [comment]
参考 https://micro-zoe.com/docs/1.x/#/zh-cn/dom-scope?id=%e8%a7%a3%e9%99%a4%e5%85%83%e7%b4%a0%e7%bb%91%e5%ae%9a

**Comment by kelvin-lemon** [comment]
> 参考 https://micro-zoe.com/docs/1.x/#/zh-cn/dom-scope?id=%e8%a7%a3%e9%99%a4%e5%85%83%e7%b4%a0%e7%bb%91%e5%ae%9a

在主应用通过重置作用域 removeDomScope() 也不行，主要是 newChild.__MICRO_APP_NAME__ 这个地方一直被设置为子应用

https://github.dev/micro-zoe/micro-app/blob/a62a9fec645a7f58316aff2bdccdb2f3765e27df/src/source/patch.ts#L235-L236

**Comment by bailicangdu** [comment]
能提供个demo看一下吗

**Comment by bailicangdu** [comment]
> > 参考 https://micro-zoe.com/docs/1.x/#/zh-cn/dom-scope?id=%e8%a7%a3%e9%99%a4%e5%85%83%e7%b4%a0%e7%bb%91%e5%ae%9a
> 
> 在主应用通过重置作用域 removeDomScope() 也不行，主要是 newChild.**MICRO_APP_NAME** 这个地方一直被设置为子应用
> 
> https://github.dev/micro-zoe/micro-app/blob/a62a9fec645a7f58316aff2bdccdb2f3765e27df/src/source/patch.ts#L235-L236

删除元素上的`__MICRO_APP_NAME__`属性可以达到一样的效果

**Comment by kelvin-lemon** [comment]
> 

找到原因了，是因为子应用内引入了一个监控的库，该库也代理了 window.document.createElement 方法，导致子应用加载时该库在沙盒内执行，导致全局的 window.document.createElement 被代理到了沙盒内的创建方法。
![image](https://user-images.githubusercontent.com/49432472/210547157-c8f24f75-3646-4440-9f2f-a6b85ae9d1cb.png)

这种情况 。。。

**Comment by kelvin-lemon** [comment]
> > > 参考 https://micro-zoe.com/docs/1.x/#/zh-cn/dom-scope?id=%e8%a7%a3%e9%99%a4%e5%85%83%e7%b4%a0%e7%bb%91%e5%ae%9a
> > 
> > 
> > 在主应用通过重置作用域 removeDomScope() 也不行，主要是 newChild.**MICRO_APP_NAME** 这个地方一直被设置为子应用
> > https://github.dev/micro-zoe/micro-app/blob/a62a9fec645a7f58316aff2bdccdb2f3765e27df/src/source/patch.ts#L235-L236
> 
> 删除元素上的`__MICRO_APP_NAME__`属性可以达到一样的效果

删除的话解决不了 script 内资源动态加载的问题，我是远程加载一个 包，这个包内内通过 webpcack 切割出去的有其他资源这些都会被代理，要该 webpack 的构建逻辑了，这不太方便

**Comment by bailicangdu** [comment]
监控的库可以放在基座中吗

**Comment by kelvin-lemon** [comment]
> 监控的库可以放在基座中吗

好的，我这边先修改一下那个监控库
