### ISSUE TITLE
子应用的环境的接口地址被基座的环境重置了

### ISSUE THREAD

**Issue by WJYman** [jd-opensource/micro-app#704]
## 问题描述
> 问题的具体描述
基座的环境 http://172.29.xxx:30497/
子应用的环境 http://172.29.xxx:30496/
发现基座里的子应用接口请求地址是 基座环境的http://172.29.xxx:30497/，而不是子应用的

## 复现步骤
1.
2.

## 上传截图
> 
<img width="491" alt="image" src="https://user-images.githubusercontent.com/26448051/210737866-9934ca92-775f-4e7b-be7f-6590ad56e420.png">
<img width="545" alt="image" src="https://user-images.githubusercontent.com/26448051/210738972-c2dfab81-7afb-4e9b-9221-0e23d1895eac.png">
<img width="661" alt="image" src="https://user-images.githubusercontent.com/26448051/210739118-ed0f0ea8-9f6c-4e91-a10b-cd77bdddead1.png">

## 复现仓库
希望子应用请求接口不被基座给替换调
## 环境信息
- micro-app版本：^1.0.0-alpha.10
- 主应用前端框架&版本："vue": "2.6.10"
- 子应用前端框架&版本："vue": "2.6.10"
- 构建工具&版本：webpack

**Comment by bailicangdu** [comment]
这种情况一般解决方式是 手动写死地址
