### ISSUE TITLE
子应用不加载，会触发vue内部的生命周期，但是microapp的生命周期一个也触发不了

### ISSUE THREAD

**Issue by justCharlesLeft** [jd-opensource/micro-app#707]
这个现象只出现在线上环境，本地一切正常，发布到线上之后，子应用有时候会出现不加载的问题，microapp的生命周期一律没有触发，但是vue的mounted是触发了的，没有任何报错。

**Comment by bailicangdu** [comment]
有复现的demo吗，方便定位问题

**Comment by 173163** [comment]
我也遇到了相同的问题

**Comment by franose371** [comment]
> 我也遇到了相同的问题

@173163  你的子应用也是使用的相对路径吗？
