### ISSUE TITLE
微信群满了，能再建一个吗

### ISSUE THREAD

**Issue by LingJinT** [jd-opensource/micro-app#710]

**Comment by raoenhui** [comment]
需要企业认证才能新建不过期的微信群码，正在查找方案，好了后新建一个

**Comment by raoenhui** [comment]
已新建
![image](https://user-images.githubusercontent.com/14011130/218035889-5f75a3db-989f-41ef-9a75-f5673b61a8dd.png)

**Comment by LingJinT** [comment]
👍

**Comment by raoenhui** [comment]
微信群二维码由于微信限制会7天过期，如果哪位大佬知道怎么建不过期的微信群二维码，欢迎告诉我们

**Comment by zhoufanglu** [comment]
为何不在qq群里讨论，方便多了

**Comment by zdhzhongtao** [comment]
我也觉得留QQ联系方式很好。不过个人微信群过期问题好像没法解决，只能使用企业微信
------
不过我也想加微信群，还有没有渠道？

**Comment by minifangit** [comment]
你好，还能加交流群吗？

**Comment by mzcc666GtHb** [comment]
你好，还能加交流群吗？
