### ISSUE TITLE
子应用是登入后从后台动态获取生成的路由,请问主应用能直接配这些子应用的来路由访问吗?

### ISSUE THREAD

**Issue by lxhtiamo** [jd-opensource/micro-app#711]
子应用是登入后从后台动态获取生成的路由,  请问主应用能直接配子应用的来路由访问吗?
 我现在能访问子应用中本来就配好的静态路由的主页页面. 但是我想进一步直接在主应用访问那些需要后台返回路径才能访问的子应用的菜单项.在主应用直接配这些子应用动态的路由路径访问后就直接404. 根本原因就是主应用访问这些子应用的动态路径的时候后台还未返回数据,路由也未生成. 请问能怎么解决?

**Comment by raoenhui** [comment]
点击路由菜单时，基座发通信给通知子应用，子应用加载好动态路由后，在通过事件跳转对应路由

**Comment by lxhtiamo** [comment]
> 点击路由菜单时，基座发通信给通知子应用，子应用加载好动态路由后，在通过事件跳转对应路由

子应用是必须是有用户登入之后才能获取动态路由 ,我在主应用配的子应用动态路由中的路径, 直接点菜单.就算通知子应用,但是没有用户也无法调用接口.

**Comment by raoenhui** [comment]
子应用没登录的话先跳登录页，登录完后再通过通信通知子应用路由跳转
