### ISSUE TITLE
多页面应用接入问题

### ISSUE THREAD

**Issue by ghost** [jd-opensource/micro-app#712]
``` vue
 <micro-app
    :url="url"
  ></micro-app>


<script>
  const url = ref('');
  url.value = URL + route.path;
</script>
```

如果强行实现多页面应用接入的话，有什么办法吗？

核心实现就是动态改变url，并且在nginx conf上进行rewrite，例如：https://www.xx.com/a 会最终加载 https://www.xx.com/a.html

但是现在有一个问题，url会自动补全，即：https://www.xx.com/a 会被补全成 https://www.xx.com/a/

这种办法应该如何结解决

**Comment by bailicangdu** [comment]
无解，rewrite需要浏览器配合，微前端不是浏览器，无法通过nginx改变url的值

**Comment by bailicangdu** [comment]
url的改变只能在前端实现

**Comment by ghost** [comment]
> 无解，rewrite需要浏览器配合，微前端不是浏览器，无法通过nginx改变url的值

并不是让nginx来改变url的意思，目前是程序里在改变url，但是因为< micro-app> 的 props url 会补全，有什么办法不补全吗

**Comment by ghost** [comment]
> 无解，rewrite需要浏览器配合，微前端不是浏览器，无法通过nginx改变url的值

现在用法是用nginx rewrite实现了一个类似路由的效果，即访问domin/a，实际访问的是domin/a.html。

为什么要实现这个效果呢，是因为如果我直接在<micro-app>的url传入 :url='DOMIN/a.html'的话，程序会报错，如下：

![image](https://user-images.githubusercontent.com/16110230/218394871-1814d913-6d50-4520-a118-a5c4d48a57ed.png)


并且来回点击的话，会指数型增加

**Comment by bailicangdu** [comment]
这个报错是子应用js内部的报错，子应用加载了，但是报错

**Comment by ghost** [comment]
> 这个报错是子应用js内部的报错，子应用加载了，但是报错

和 micro-app 没关系吗？那是不是可以理解成这种方式来实现多页面的子应用接入没问题？

**Comment by bailicangdu** [comment]
多页面接入最大的问题是页面之间的跳转，因为一个micro-app元素只能绑定一个html

**Comment by maorunjie-2019** [comment]
所以micro-app不支持多页面应用的接入吗？

**Comment by maorunjie-2019** [comment]
> > 无解，rewrite需要浏览器配合，微前端不是浏览器，无法通过nginx改变url的值
> 
> 现在用法是用nginx rewrite实现了一个类似路由的效果，即访问domin/a，实际访问的是domin/a.html。
> 
> 为什么要实现这个效果呢，是因为如果我直接在的url传入 :url='DOMIN/a.html'的话，程序会报错，如下：
> 
> ![image](https://user-images.githubusercontent.com/16110230/218394871-1814d913-6d50-4520-a118-a5c4d48a57ed.png)
> 
> 并且来回点击的话，会指数型增加

所以micro-app不支持多页面应用的接入吗？

**Comment by maorunjie-2019** [comment]
> micro-app元素



> 多页面接入最大的问题是页面之间的跳转，因为一个micro-app元素只能绑定一个html

所以micro-app目前是不支持多页面应用的接入的，对吗

**Comment by bailicangdu** [comment]
如果是多个html地址，不建议接入
