### ISSUE TITLE
setTimeout 在子应用中如果没及时clearTimeout，在和其他子应来回切换时会重复调用，次数会叠加

### ISSUE THREAD

**Issue by hlwen** [jd-opensource/micro-app#713]
## 问题描述
> 问题的具体描述
setTimeout 在子应用中如果没及时clearTimeout，在和其他子应来回切换时会重复调用，次数会叠加
## 复现步骤
1.打开一个子应用在页面调用setTimeout，执行完不使用clearTimeout清除
2.在不同子应用切换再回来setTimeout会再次执行，反复这个过程再次执行次数会叠加

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。

## 环境信息
- micro-app版本：1.0.0-alpha.10
- 主应用前端框架&版本：vue 2.7.14
- 子应用前端框架&版本：vue 2.7.14
- 构建工具&版本：vue/cli 4

**Comment by bailicangdu** [comment]
umd模式吗

**Comment by kelvin-lemon** [comment]
<img width="893" alt="image" src="https://user-images.githubusercontent.com/49432472/236595059-e5d71c03-353a-4d81-98ef-aaf68a609ca9.png">
通过这样修改尝试对 time handler 在重复绑定时移除之前 map 的引用，看看是否能合入主干？ @bailicangdu
