### ISSUE TITLE
子应用使用 keep-alive，回退后变空白页

### ISSUE THREAD

**Issue by ziqiya** [jd-opensource/micro-app#714]
## 问题描述
> 问题的具体描述
有子应用A和B，子应用都使用 keep-alive 属性，先打开子应用A，再打开子应用B，调用 history.back() 后，返回子应用A，但是此时子应用A为空白

## 复现步骤
1.有子应用A和B，子应用都使用 keep-alive 属性，先打开子应用A，加载页面
2.再打开子应用B，加载完成后，点击浏览器左上角回退（或者 调用 history.back() ）
3.回到子应用A以后，发现子应用为空白

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。
![image](https://user-images.githubusercontent.com/39564114/218687321-b955c4c4-9020-4e7d-9970-52e14c54e842.png)

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。
[git@github.com:ziqiya/micro-app-demo.git](https://github.com/ziqiya/micro-app-demo)

## 环境信息
- micro-app版本：0.8.7
- 主应用前端框架&版本：react17.0.1
- 子应用前端框架&版本：react17.0.1
- 构建工具&版本：@umijs/max:4.0.0

**Comment by bailicangdu** [comment]
能提供个demo看一下吗

**Comment by ziqiya** [comment]
> 能提供个demo看一下吗

已经补充了，这个 demo 的 react17 就有点像那个问题，一直是空的

**Comment by ziqiya** [comment]
已经解决了，micro-app版本更新到 1.0.0-alpha.10 以后就没有这个问题了，但是不知道会不会对现有项目有影响

**Comment by zey28** [comment]
应该是 回退事件,被2个子应用都捕捉了,然后都进行了路由回退渲染找不到子应用中对应的组件,产生了空白页面,这个怎么解决的,未激活的子应用是否可以屏蔽回退事件
