### ISSUE TITLE
支持vite微前端，是否可参考无界实现方式？

### ISSUE THREAD

**Issue by agileago** [jd-opensource/micro-app#719]
## 背景

公司前端脚手架全部迁移至vite了，急需支持vite微前端，感觉无界不错，但是他父子路由不一致，用户体验不好，micro-app是否可参考无界的隔离实现方式支持vite应用，vite现在势头汹汹

## 期望的效果

支持vite子应用

**Comment by bailicangdu** [comment]
'父子路由不一致' 是指什么？

**Comment by agileago** [comment]
无界使用的query来同步子路由的

**Comment by agileago** [comment]
![image](https://user-images.githubusercontent.com/11799110/219931947-fb278231-be47-40d9-a0e2-6b615a067e49.png)

**Comment by agileago** [comment]
https://wujie-micro.github.io/doc/guide/sync.html

**Comment by agileago** [comment]
我想他主要是为了能同时加载多个子应用才这样设计的

**Comment by bailicangdu** [comment]
了解

**Comment by xiaozhanghui** [comment]
micro 1.0也是这个虚拟路由的设计

**Comment by agileago** [comment]
@bailicangdu 真的假的，能出一个页面上只存在一个子应用，并且路由同步的功能么？路由同步这个很重要，因为很多人都是右键打开新的链接

**Comment by bailicangdu** [comment]
micro-app的虚拟路由支持两种模式，可以选择将子应用路由信息添加到search上(类似于wujie)或者是pathname上

**Comment by agileago** [comment]
现在可用1.0么， 我看已经发布alpha版了

**Comment by agileago** [comment]
@bailicangdu  貌似最新版的baseroute不生效了？

**Comment by peony0519** [comment]
默认情况下，baseroute的功能是被禁止的，若要开启需先关闭memory-router

**Comment by peony0519** [comment]
> @bailicangdu 貌似最新版的baseroute不生效了？

默认情况下，baseroute的功能是被禁止的，若要开启需先关闭memory-router
