### ISSUE TITLE
子应用的Head内的script标签加载的js代码，无法获取到currentScript

### ISSUE THREAD

**Issue by darknessjs** [jd-opensource/micro-app#720]
## 问题描述
> 问题的具体描述

## 复现步骤
1.子应用使用了
<head><script
      crossorigin="anonymous"
      src="https://uipaas-assets.com/prod/npm/@alilc/lowcode-engine/1.1.1/dist/js/engine-core.js"
    ></script></head>
2.enginc-core里面会读取document.currentScript加载另一个文件(react-simulator-renderer.js)

期待地址是：https://uipaas-assets.com/prod/npm/@alilc/lowcode-engine/1.1.1/dist/js/react-simulator-renderer.js
实际地址是：http://localhost:xxxx/react-simulator-renderer.js

获取origin地址的代码是
const publicPath = (document.currentScript as HTMLScriptElement)?.src.replace(/^(.*\/)[^/]+$/, '$1');

export function getPublicPath(): string {
  return publicPath || '';
}

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。

## 环境信息
- micro-app版本：1.0.0-alpha.10

**Comment by bailicangdu** [comment]
确实有这个问题，感谢反馈

**Comment by BARMPlus** [comment]
这个问题依然存在

**Comment by ZuPerfect** [comment]
这个问题现在有解决方案吗？

**Comment by viccsen** [comment]
确实还没解决...
