### ISSUE TITLE
子应用的生命周期

### ISSUE THREAD

**Issue by smysmile** [jd-opensource/micro-app#723]
vue  环境下 子应用的生命周期函数 beforeDestroy是不是无法生效？请问有什么方法可替代此方法吗？

**Comment by bailicangdu** [comment]
可以正常触发

**Comment by smysmile** [comment]
> 可以正常触发

为啥我的不能触发

**Comment by bailicangdu** [comment]
我本地试是正常的，实在不行提供个demo看一下吧

**Comment by Cmingqiu** [comment]
楼主解决了吗，我也是vue3 onBeforeUnmount 不触发

**Comment by raoenhui** [comment]
我这边demo测试，生命周期是触发的
![image](https://github.com/micro-zoe/micro-app/assets/14011130/2f5bba66-c2da-4b21-bd75-ab8e25082ce5)
<img width="1310" alt="image" src="https://github.com/micro-zoe/micro-app/assets/14011130/274b1866-b177-4ac2-bc65-e97aae4dd3a6">
