### ISSUE TITLE
子服务不渲染，也没触发生命周期，实例也没创建，试过常见问题的router和webpack配置jsonFunction也无法解决

### ISSUE THREAD

**Issue by justCharlesLeft** [jd-opensource/micro-app#724]
此为主项目路由配置：
const routes: Array<RouteRecordRaw> = [
  {
    path: "/",
    component: layout,
    children: [
      {
        path: "/index",
        name: 'home',
        redirect: '/',
        component: () => import(/* webpackChunkName: "vue3" */ "@/views/home.vue"),
      }
    ],
  },
  {
    path: '/plat/:page*',
    name: 'app-plat',
    component: layout,
    children: [
      {
        path: "/plat/:page*",
        name: 'plat',
        component: () => import(/* webpackChunkName: "vue3" */ "@/views/plat.vue"),
      },
    ],
  },
  {
    path: '/system/:page*',
    name: 'app-system',
    component: layout,
    children: [
      {
        path: "/system/:page*",
        name: 'system',
        component: () => import(/* webpackChunkName: "vue3" */ "@/views/plat.vue"),
      },
    ],
  },
  {
    path: '/call/:page*',
    name: 'app-call',
    component: layout,
    children: [
      {
        path: "/call/:page*",
        name: 'call',
        component: () => import(/* webpackChunkName: "vue3" */ "@/views/call.vue"),
      },
    ],
  }
]
此为主项目中引用子项目的页面:
<template>
  <div style="height: 100%" v-loading="state.isLoading">
    <micro-app
      name="call"
      :url="state.url"
      :data="state.microAppData"
      @created="handleCreate"
      @beforemount="handleBeforeMount"
      @mounted="handleMount"
      @unmount="handleUnmount"
      @error="handleError"
      @datachange="handleDataChange"
    ></micro-app>
  </div>
</template>

子项目路由
import Vue from 'vue'
import Router from 'vue-router'

Vue.use(Router)

/* Layout */
import Layout from "@/layout"
// 公共路由
export const constantRoutes = [
  {
    path: window.__MICRO_APP_BASE_ROUTE__ || '/',
    component: Layout,
    children: [
      {
        path: '/setting/blackList',
        component: () => import('@/views/callingCloudPlatform/settingCenter/blackLists/index.vue'),
        name: 'blackList'
      },
      {
        path: '/setting/holiday',
        component: () => import('@/views/callingCloudPlatform/settingCenter/holidays/index.vue'),
        name: 'holiday'
      },
      {
        path: '/setting/script',
        component: () => import('@/views/callingCloudPlatform/settingCenter/callScripts/index.vue'),
        name: 'script'
      },
      {
        path: '/setting/templates',
        component: () => import('@/views/callingCloudPlatform/settingCenter/templates/index.vue'),
        name: 'templates'
      },
      {
        path: '/task/autoDialing',
        name: 'autoDialing',
        component: () => import('@/views/callingCloudPlatform/taskCenter/autoDialing/index.vue')
      },
      {
        path: '/task/monitor',
        name: 'monitor',
        component: () => import('@/views/callingCloudPlatform/taskCenter/monitor/index.vue')
      },
      {
        path: '/task/taskRunDetail',
        name: 'taskRunDetail',
        component: () => import('@/views/callingCloudPlatform/taskCenter/autoDialing/taskRunDetail.vue')
      },
      {
        path: '/task/serves',
        component: () => import('@/views/callingCloudPlatform/taskCenter/serves/index.vue'),
        name: 'serves',
      },
      {
        path: '/task/callingDetail',
        name: 'callingDetail',
        component: () => import('@/views/callingCloudPlatform/taskCenter/autoDialing/callingDetail.vue')
      },
      {
        path: '/setting/relationTask',
        name: 'relationTask',
        component: () => import('@/views/callingCloudPlatform/settingCenter/blackLists/relationTask.vue')
      },
      {
        path: '/setting/blackListDetail',
        name: 'blackListDetail',
        component: () => import('@/views/callingCloudPlatform/settingCenter/blackLists/blackListDetail.vue')
      },
      {
        path: '/setting/editBackLists',
        name: 'editBackLists',
        component: () => import('@/views/callingCloudPlatform/settingCenter/blackLists/editBackLists.vue')
      },
      {
        path: '/setting/relationScenceDetail',
        name: 'relationScenceDetail',
        component: () => import('@/views/callingCloudPlatform/settingCenter/templates/relationScenceDetail.vue')
      },
      {
        name: 'newRule',
        path: '/task/newRule',
        component: () => import('@/views/callingCloudPlatform/taskCenter/serves/newRule.vue')
      },
      {
        path: '/task/editRule',
        name: 'editRule',
        component: () => import('@/views/callingCloudPlatform/taskCenter/serves/editRule.vue')
      },
      {
        path: '/reportForm/reportFormManage',
        name: 'reportFormManage',
        component: () => import('@/views/callingCloudPlatform/reportForm/reportFormManage')
      },
      {
        path: '/reportForm/callingoutDetail',
        name: 'callingoutDetail',
        component: () => import('@/views/callingCloudPlatform/reportForm/reportFormManage/callingoutDetail.vue')
      },
      //2.0
      {
        path: '/task/tryTask',
        name: 'tryTask',
        component: () => import('@/views/callingCloudPlatform/taskCenter/tryTask/index.vue')
      },
      {
        path: '/task/tryTask/taskDetail',
        name: 'taskDetail',
        component: () => import('@/views/callingCloudPlatform/taskCenter/tryTask/taskDetail.vue')
      },
      // todo
      {
        path: '/task/tryTask/callDetail',
        name: 'callDetail',
        component: () => import('@/views/callingCloudPlatform/taskCenter/tryTask/callDetail.vue')
      },
      {
        path: '/setting/limit',
        name: 'limit',
        component: () => import('@/views/callingCloudPlatform/settingCenter/limit/index.vue')
      },
      {
        path: '/setting/messageConfig',
        name: 'messageConfig',
        component: () => import('@/views/callingCloudPlatform/settingCenter/messageConfig/index.vue')
      },
      {
        path: '/setting/flowChart',
        name: 'flowChart',
        component: () => import('@/views/callingCloudPlatform/settingCenter/flowChart/index.vue')
      },
      {
        path: '/setting/flowMap',
        name: 'flowMap',
        component: () => import('@/views/callingCloudPlatform/settingCenter/flowChart/flowMap/index.vue')
      },
      {
        path: '/setting/api',
        name: 'api',
        component: () => import('@/views/callingCloudPlatform/settingCenter/apis/index.vue')
      },
      {
        path: '/setting/numberManage',
        name: 'numberManage',
        component: () => import('@/views/callingCloudPlatform/settingCenter/numberManage/index.vue')
      }
    ]
  }
]
// 动态路由，基于用户权限动态去加载
export const dynamicRoutes = []

// 防止连续点击多次路由报错
let routerPush = Router.prototype.push
Router.prototype.push = function push(location) {
  return routerPush.call(this, location).catch((err) => err)
}

export default new Router({
  // base: window.__MICRO_APP_BASE_ROUTE__ || process.env.BASE_URL,
  mode: 'hash', // 去掉url中的#
  // scrollBehavior: () => ({ y: 0 }),
  routes: constantRoutes
})
子项目main.js
import Vue from 'vue'
import Cookies from 'js-cookie'

import Element from 'element-ui'
import '@/rem.ts'
import echarts from './echarts'
import './assets/styles/element-variables.scss'

import '@/assets/styles/index.scss' // global css
import '@/assets/styles/aicc.scss' // aicc css
import '@/assets/styles/base.scss'
import App from './App.vue'
import store from './store'
import router from './router'
import directive from './directive' // directive
import plugins from './plugins' // plugins
import { download } from '@/utils/request'
import './public-path'
import './assets/icons' // icon
import './permission' // permission control
import { getDicts } from '@/api/system/dict/data'
import { getConfigKey, updateConfigByKey } from '@/api/system/config'
import { parseTime, resetForm, addDateRange, selectDictLabel, selectDictLabels, handleTree } from '@/utils/aicc'
// 分页组件
import Pagination from '@/components/Pagination/index.vue'
// 自定义表格工具组件
import RightToolbar from '@/components/RightToolbar/index.vue'
// 富文本组件
import Editor from '@/components/Editor/index.vue'
// 文件上传组件
import FileUpload from '@/components/FileUpload/index.vue'
// 图片上传组件
import ImageUpload from '@/components/ImageUpload/index.vue'
// 图片预览组件
import ImagePreview from '@/components/ImagePreview/index.vue'
// 字典标签组件
import DictTag from '@/components/DictTag/index.vue'
// 头部标签组件
import VueMeta from 'vue-meta'
// 字典数据组件
import DictData from '@/components/DictData'

// 全局方法挂载
Vue.prototype.getDicts = getDicts
Vue.prototype.getConfigKey = getConfigKey
Vue.prototype.updateConfigByKey = updateConfigByKey
Vue.prototype.parseTime = parseTime
Vue.prototype.resetForm = resetForm
Vue.prototype.addDateRange = addDateRange
Vue.prototype.selectDictLabel = selectDictLabel
Vue.prototype.selectDictLabels = selectDictLabels
Vue.prototype.download = download
Vue.prototype.handleTree = handleTree
Vue.prototype.$echarts = echarts

// 全局组件挂载
Vue.component('DictTag', DictTag)
Vue.component('Pagination', Pagination)
Vue.component('RightToolbar', RightToolbar)
Vue.component('Editor', Editor)
Vue.component('FileUpload', FileUpload)
Vue.component('ImageUpload', ImageUpload)
Vue.component('ImagePreview', ImagePreview)

Vue.use(directive)
Vue.use(plugins)
Vue.use(VueMeta)
DictData.install()

/**
 * If you don't want to use mock-server
 * you want to use MockJs for mock api
 * you can execute: mockXHR()
 *
 * Currently MockJs will be used in the production environment,
 * please remove it before going online! ! !
 */

// 修改 el-dialog 默认点击遮照为不关闭
// Element.Dialog.props.closeOnClickModal.default = false

Vue.use(Element, {
  size: Cookies.get('size') || 'medium' // set element-ui default size
})

Vue.config.productionTip = false

function handleMicroData () {
  // 是否是微前端环境
  if ((<any>window).__MICRO_APP_ENVIRONMENT__) {
    // 主动获取基座下发的数据
    // 监听基座下发的数据变化
    (<any>window).microApp.addDataListener((data: any) => {
      const newData = JSON.parse(JSON.stringify(data))
      if (newData.permissions) {
        (<any>store).commit('SET_PERMISSIONS', newData.permissions)
      }
      // 当基座下发path时进行跳转
      if (newData.path && newData.path !== router.currentRoute.path) {
        router.push(newData.path)
      }
    })
  }
}
// ----------分割线---默认模式------两种模式任选其一-----放开注释即可运行------- //
// const app = new Vue({
//   router,
//   store,
//   render: h => h(App),
// }).$mount('#app-cc-web')

// console.log('微应用cc-web渲染了')

// handleMicroData()

// // 监听卸载操作
// window.addEventListener('unmount', function () {
//   app.$destroy()
//   console.log('微应用cc-web卸载了')
// })
let app: any = null
// 将渲染操作放入 mount 函数
function mount () {
  app = new Vue({
    el: '#app-cc-web',
    router,
    store,
    render: h => h(App)
  })

  console.log('微应用cc-web渲染了')

  handleMicroData()
}

// 将卸载操作放入 unmount 函数
function unmount () {
  app.$destroy()
  app.$el.innerHTML = ''
  app = null
  console.log('微应用cc-web卸载了')
}

// 微前端环境下，注册mount和unmount方法
if ((<any>window).__MICRO_APP_ENVIRONMENT__) {
  (<any>window)[`micro-app-${(<any>window).__MICRO_APP_NAME__}`] = { mount, unmount }
} else {
  // 非微前端环境直接渲染
  mount()
}
 

本地加载毫无问题，打包线上就子服务不加载，偶尔可以加载出来，但是大多数时间都无法加载，也不触发子服务内部生命周期

**Comment by bailicangdu** [comment]
大概率是nginx配置问题，有线上地址吗

**Comment by weihuifeng** [comment]
你好，碰到了同样的问题，也没有任何报错，请问是怎么解决的
`
<micro-app-body><div id="app"></div></micro-app-body>
`
线上环境的src都被注释掉了，所以没有渲染？毫无头绪。。从主应用进或者直接url进子应用也没有任何报错，开发环境正常
