### ISSUE TITLE
vue 子应用之间的页面互相跳转

### ISSUE THREAD

**Issue by smysmile** [jd-opensource/micro-app#725]
vue 子应用之间的页面互相跳转时，页面会加载两次 但是路由只有一次，页面的生命周期都执行了两次

**Comment by bailicangdu** [comment]
通过基座做中转跳转，还是其它方式跳转？

**Comment by JackShijt** [comment]
解决了吗？我现在子应用跳转，点后退需要点两次才能退回上一个子应用
