### ISSUE TITLE
nuxt下data和setData()使用问题

### ISSUE THREAD

**Issue by qianqian05723** [jd-opensource/micro-app#73]
## Describe the bug
> 标签data属性和setData()在nuxt下使用遇到问题：
1. 主应用通过data传值，在子应用始终无法接收到；
2. 主应用使用setData()主动传值，子应用可以接收到值；不过使用setData()传值时，页面刷新会报window相关错误。
如下主应用和子应用code:
主应用：
![image](https://user-images.githubusercontent.com/17306867/131280853-8d4368ed-16cd-46b7-a920-f3688e8b009d.png)
子应用：
![image](https://user-images.githubusercontent.com/17306867/131280899-74c0352b-5dee-4b66-a752-ee3d5675fab7.png)

## To Reproduce
1.页面初始化
![image](https://user-images.githubusercontent.com/17306867/131281013-eff5b641-fbf9-4573-bcef-9ea4ac0397d5.png)

2.改变属性和值
![image](https://user-images.githubusercontent.com/17306867/131281100-f8f41c45-5947-43e9-9478-2c4001a3a414.png)

3.使用setData()方法
![image](https://user-images.githubusercontent.com/17306867/131281564-6552e0e2-2f9f-4d93-8040-cec75e208357.png)

4. 使用setData()回车刷新页面报错
![image](https://user-images.githubusercontent.com/17306867/131281724-76488512-5a3f-431e-8ebd-9136f18baa0a.png)

## Screenshots
> If possible, please upload screenshots of the code, console, terminal, etc. to help us understand your problem.

## Reproduce repository
> Please provide a condensed code repository and upload it to your own github to help us reproduce your problem.

## Environment
- micro-app version: 0.2.5
- framework of base app & version: nuxt-koa 最新nuxt版本
- framework of sub app & version: nuxt-koa 最新nuxt版本
- Build tools & version: webpack

**Comment by bailicangdu** [comment]
好的，我看一下
