### ISSUE TITLE
VUE使用ElementUi 中的 Dropdown 下拉菜单定位偏移问题

### ISSUE THREAD

**Issue by webSupre** [jd-opensource/micro-app#730]
## 问题描述
在vue框架内使用elementui的组件el-dropdown，位置偏移

## 复现步骤
1.在vue框架内引入elementui的组件el-dropdown
2.在表格内使用，当表格数据量过多时，下面的el-dropdown菜单就会偏移

## 上传截图
1.数据量较少正常
![image](https://user-images.githubusercontent.com/66408413/224255285-69415c68-e1a8-4631-8162-86aceca3cf35.png)
2.当数据量过多，产生偏移，红框位置是鼠标放的位置
![image](https://user-images.githubusercontent.com/66408413/224255751-10f8f6ea-5587-4dd7-ab3c-8b1c015453a8.png)
3.我单独打开子应用的时候，是显示正常的，集成在框架里面来就产生了问题

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。

## 环境信息
- micro-app版本：1.0.0-alpha.10
- 主应用前端框架&版本："vue": "^2.6.14",
- 子应用前端框架&版本："vue": "^2.6.12",
- 构建工具&版本：webpack

**Comment by bailicangdu** [comment]
主应用也是用了ElementUi吗，可能是基座影响到子应用了

**Comment by webSupre** [comment]
主应用也是ElementUi，影响到了怎么解决呢

**Comment by njzzzz** [comment]
> 主应用也是ElementUi，影响到了怎么解决呢
兄die～最后怎么解决的

**Comment by njzzzz** [comment]
> > 主应用也是ElementUi，影响到了怎么解决呢
> > 兄die～最后怎么解决的

![image](https://user-images.githubusercontent.com/41502851/234453304-bbd352f8-3082-42a9-a775-67e2170f08de.png)
暂时这么解决了一下

**Comment by webSupre** [comment]
> > > 主应用也是ElementUi，影响到了怎么解决呢
> > > 兄die～最后怎么解决的
> 
> ![image](https://user-images.githubusercontent.com/41502851/234453304-bbd352f8-3082-42a9-a775-67e2170f08de.png) 暂时这么解决了一下

有用吗

**Comment by webSupre** [comment]
> > > > 主应用也是ElementUi，影响到了怎么解决呢
> > > > 兄die～最后怎么解决的
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/41502851/234453304-bbd352f8-3082-42a9-a775-67e2170f08de.png) 暂时这么解决了一下
> 
> 有用吗
 老哥  你这个是写在哪儿的呢

**Comment by njzzzz** [comment]
> > > > 主应用也是ElementUi，影响到了怎么解决呢
> > > > 兄die～最后怎么解决的
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/41502851/234453304-bbd352f8-3082-42a9-a775-67e2170f08de.png) 暂时这么解决了一下
> 
> 有用吗

有用，写在drop-down组件的visible-change 事件里面

**Comment by Reda011** [comment]
> > > 主应用也是ElementUi，影响到了怎么解决呢
> > > 兄die～最后怎么解决的
> 
> ![image](https://user-images.githubusercontent.com/41502851/234453304-bbd352f8-3082-42a9-a775-67e2170f08de.png) 暂时这么解决了一下

感谢大佬提供的方案。

我在处理的时候，除了这样监听visible-change 事件，还需要给 micro-app-body 加个“position: relative”。

希望能帮到大家
