### ISSUE TITLE
元素点击事件onclick="submit()"这种写法，报错submit is not define

### ISSUE THREAD

**Issue by ufiudi** [jd-opensource/micro-app#731]
## 问题描述
> 问题的具体描述

## 复现步骤
1.
2.

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。

## 环境信息
- micro-app版本：
- 主应用前端框架&版本：
- 子应用前端框架&版本：
- 构建工具&版本：

**Comment by bailicangdu** [comment]
这种形式无法支持，会向基座查询submit方法
