### ISSUE TITLE
git clone后yarn install && yarn build 编译失败

### ISSUE THREAD

**Issue by happysearch** [jd-opensource/micro-app#732]
## 问题描述
> git clone代码后什么都不做，执行yarn install后再yarn build报错
master和dev分支报不同的错：
**master分支报错：**
![image](https://user-images.githubusercontent.com/7447527/224649461-f6f12ce3-fefb-4bf2-b362-b49266a444a6.png)

**Dev分支:**
![image](https://user-images.githubusercontent.com/7447527/224649209-75c8f659-7c6c-490e-a303-db98f692a02b.png)

**Comment by raoenhui** [comment]
用 yarn bootstrap 安装

**Comment by happysearch** [comment]
不是这个原因，_**rollup -c**_  后 _**lib/index.d.ts**_ 根本没打包出来所以导致后继执行_**npm run createtype**_出错，感觉是打包时提示的的 _**“(!) Circular dependencies”**_ 导致的  
![image](https://user-images.githubusercontent.com/7447527/233532349-0c1afd4a-65d0-498e-8a00-fa8eb1acd76e.png)
