### ISSUE TITLE
1.x版本是否可以和0.x版本兼容

### ISSUE THREAD

**Issue by HadiChen** [jd-opensource/micro-app#734]
如基座升级为1.x版本，部分子应用保持0.8.X版本是否可行

**Comment by bailicangdu** [comment]
版本不同可能会导致不可预料的问题，不建议这样做

**Comment by mursumomo** [comment]
我这边也遇到了这样的情况。其他部门的项目也是用micro-app。用的是0.8。现在要接入到我这边的主应用下。还不能改动他们的版本。就会存在1.0套0.8这样的。

**Comment by keuby** [comment]
我们目前是 0.x 和 1.x 的应用同时运行在一起的。我们的做法是封装了一个用于通讯的包 @knx/micro-app，基座操作子应用，子应用和基座的通讯都基于这个包暴露的接口方法。这包里面的逻辑根据一些环境变量来判断当前环境，通过一些兼容代码抹平了 0.x 和 1.x 的功能差异

**Comment by JackShijt** [comment]
子应用不用安装microapp吧？
