### ISSUE TITLE
发布之后，报 DOMException: Blocked a frame with origin "xxx" from accessing a cross-origin frame 的错误，本地开发环境没问题

### ISSUE THREAD

**Issue by jiaozhiye** [jd-opensource/micro-app#736]
## 问题描述
编译发布之后，报 DOMException: Blocked a frame with origin "xxx" from accessing a cross-origin frame 的错误，本地开发环境没问题

## 上传截图
![Dingtalk_20230319134539](https://user-images.githubusercontent.com/22720488/226254067-a8445c12-46a8-47a4-8446-05bbfd45d34d.jpg)
![Dingtalk_20230319134413](https://user-images.githubusercontent.com/22720488/226254082-5e7d713d-ae4c-47e3-b13e-6fec620c6062.jpg)

## 环境信息
- micro-app版本：1.0.0-beta.0
- 主应用前端框架&版本：Reactv17.0.2 + webpack5.75.0
- 子应用前端框架&版本：Reactv17.0.2 + webpack5.75.0
- 构建工具&版本： webpack5.75.0

**Comment by bailicangdu** [comment]
iframe沙箱的src为主应用的host，检查一下nginx是否将这个地址重定向了?

**Comment by jiaozhiye** [comment]
> iframe沙箱的src为主应用的host，检查一下nginx是否将这个地址重定向了?

就是最简单的一些配置，并没有对主应用host做重定向
location / {
    root html;
    # 用于配合 browserHistory 使用
    try_files $uri $uri/ /index.html;
    add_header Access-Control-Allow-Origin *;
}

**Comment by bailicangdu** [comment]
能提供一个demo吗

**Comment by jiaozhiye** [comment]
> 能提供一个demo吗

现在都是在我们现有的工程上做的验证，找时间我抽离一个最小demo

**Comment by jiaozhiye** [comment]
> 能提供一个demo吗

我找到问题了，我主应用设置了 document.domain 导致了以上的错误；我想咨询一下，如果项目里有这种需求，需要设置 document.domain，在 micro-app 底层能做兼容处理吗？不报这个错误

**Comment by bailicangdu** [comment]
能截图相关的代码看一下吗

**Comment by jiaozhiye** [comment]
> 能截图相关的代码看一下吗

![image](https://user-images.githubusercontent.com/22720488/226852163-a93ba7f2-c2c8-4a94-b420-997cec76ebc8.png)

**Comment by bailicangdu** [comment]
好的，感谢反馈，我们会尝试修复这个问题，预计在明天发布的1.0.0-beta.1版本中带上

**Comment by jiaozhiye** [comment]
> 好的，感谢反馈，我们会尝试修复这个问题，预计在明天发布的1.0.0-beta.1版本中带上

感谢，如果可以的话，烦请给React技术栈使用antd的drawer组件无法渲染的问题提供一个适配方案吧，我们就可以整体升级大版本了！

**Comment by bailicangdu** [comment]
drawer组件的问题也会在明天的新版本中带上

**Comment by Jay214** [comment]
> 好的，感谢反馈，我们会尝试修复这个问题，预计在明天发布的1.0.0-beta.1版本中带上

今天也遇到了同样的问题，什么时候能解决呢

**Comment by bailicangdu** [comment]
已修复，更新到最新版即可，参考 https://github.com/micro-zoe/micro-app/releases/tag/v1.0.0-beta.1
