### ISSUE TITLE
IE11 兼容

### ISSUE THREAD

**Issue by SxxGDZB** [jd-opensource/micro-app#737]
能不能出一个兼容IE11版本的解决方案啊

**Comment by bailicangdu** [comment]
由于我们强依赖于proxy和customElements，所以无法兼容IE

**Comment by a572251465** [comment]
是否考虑过降级方案呢  一般proxy可以做降级，使用快照沙箱可以满足，就是性能上，呵呵呵..  但是custom Element 做降级代价有大了
