### ISSUE TITLE
使用当前最新版1.0.0-beta.0，子应用antd的drawer组件无法渲染，0.8版本正常

### ISSUE THREAD

**Issue by ZXYforce** [jd-opensource/micro-app#739]
## 问题描述
> 最新版的1.0.0-beta.0没法渲染drawer组件，0.8版本正常

## 复现仓库
>https://github.com/sogud/micro-app

## 环境信息
- micro-app版本：1.0.0-beta.0
- 主应用前端框架&版本：vue2
- 子应用前端框架&版本：react17
- 构建工具&版本：官方仓库

**Comment by bailicangdu** [comment]
感谢反馈，我们会在下个版本增加一个适配方案

**Comment by jiaozhiye** [comment]
> 

感谢，我们也需要这个功能，要不我们一直无法升级到新版，只能用 0.8.10 的

**Comment by jiaozhiye** [comment]
> 感谢反馈，我们会在下个版本增加一个适配方案

感谢，我们也需要这个功能，要不我们一直无法升级到新版，只能用 0.8.10 的

**Comment by bailicangdu** [comment]
已修复，更新到最新版即可，参考 https://github.com/micro-zoe/micro-app/releases/tag/v1.0.0-beta.1
