### ISSUE TITLE
是否可以将vite沙箱的形式，以额外插件或者扩展的形式独立出来。向0.8版本提供兼容。

### ISSUE THREAD

**Issue by mursumomo** [jd-opensource/micro-app#742]
最近在尝试了1.0版本后发现。新版本改动确实很大。 并且部分功能在升级后，使用老版本的应用会出现很多不可预知的问题。
当前遇到的最大问题就是vite的沙箱机制。但目前vite沙箱是高度融合在1.0版本的。

期望的是，在不升级老版本的同时，又能使用vite的沙箱机制。

能否把vite沙箱这一块，以插件或者扩展sdk的形式。单独独立出来，方便灵活兼容使用

**Comment by bailicangdu** [comment]
沙箱是高度耦合的，很难分离出来

**Comment by bailicangdu** [comment]
在后续可能会推出单独的沙箱版本的npm包，需要哪种沙箱就引入哪种沙箱的包

**Comment by mursumomo** [comment]
期待大佬新功能的不断迭代
