### ISSUE TITLE
patch.ts:337 Uncaught TypeError: Failed to execute 'removeChild' on 'Node'

### ISSUE THREAD

**Issue by skyLoveSnap** [jd-opensource/micro-app#743]
## 问题描述
<img width="540" alt="image" src="https://user-images.githubusercontent.com/40157361/227866334-4be35283-28b6-4842-83b0-aec9aaca6628.png">

## 上传截图
<img width="1046" alt="image" src="https://user-images.githubusercontent.com/40157361/227865955-e70bce29-400b-4fa8-abdb-e94962c488a7.png">

## 环境信息
- micro-app版本：1.0.0-alpha.10
- 主应用前端框架&版本：vue3 + vite
- 子应用前端框架&版本：vue2

**Comment by skyLoveSnap** [comment]
问题定位出来了： 
  Element.prototype.removeChild = function removeChild<T extends Node> (oldChild: T): T {
    if (oldChild?.__MICRO_APP_NAME__) {
      const app = appInstanceMap.get(oldChild.__MICRO_APP_NAME__)
      if (app?.container) {
        return invokePrototypeMethod(
          app,
          globalEnv.rawRemoveChild,
          this,
          getMappingNode(oldChild),
        )
      }
      try {
        return globalEnv.rawRemoveChild.call(this, oldChild) as T
      } catch {
        return (oldChild?.parentNode && globalEnv.rawRemoveChild.call(oldChild.parentNode, oldChild)) as T
      }
    }

    return globalEnv.rawRemoveChild.call(this, oldChild) as T
  }

 return globalEnv.rawRemoveChild.call(this, oldChild) as T 的时候    oldChild 是undefine,  这样的话 就报错了 ，应该对oldChild断空一下就可以了，我怎么解决呢

**Comment by skyLoveSnap** [comment]
重现实例暂时无法提供  ，报错就是那个oldChild是undefined 导致的。。。。

**Comment by bailicangdu** [comment]
定位一下为什么oldChild是空？

**Comment by skyLoveSnap** [comment]
主应用切子应用的时候，(没有用keep-live)

**Comment by bailicangdu** [comment]
> 主应用切子应用的时候，(没有用keep-live)

这个太笼统了，没有代码调试很难定位问题

**Comment by xinglu68** [comment]
你好哦  请问这个问题解决了嘛，是怎么解决的呢

**Comment by qinbinhua601** [comment]
想问一下怎么复现这个问题啊？有没有复现步骤？
