### ISSUE TITLE
请问有计划把文档翻译英文吗，可以在空闲时间帮忙翻译（btw 自己英语也不好，就是单纯想帮忙）

### ISSUE THREAD

**Issue by maogongzi** [jd-opensource/micro-app#744]
## 背景
> 描述您希望改进的问题。

目前主站英文文档是 coming soon 状态

## 期望的效果

主站有中英切换，有英文文档供参考

## 流程

期望官方给出具体可操作的翻译流程

**Comment by bailicangdu** [comment]
我们在推出1.0后才考虑出英文文档，到时候欢迎加入

**Comment by Relaxe111** [comment]
I can help out as well. Not to say that i am super profesional either. But i think i can contribute with some English translation at least.

**Comment by paper-play** [comment]
> 

请问1.0正式版本什么时候会发布
