### ISSUE TITLE
https://zeroing.jd.com/docs.html#/zh-cn/deploy 文档链接错误❌

### ISSUE THREAD

**Issue by zhu-hongwei** [jd-opensource/micro-app#745]
这个 https://zeroing.jd.com/docs.html#/zh-cn/deploy

最底部，这两个 

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/61079864/227901084-d138107a-f7c3-4698-8299-1244d871ce26.png">

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/61079864/227901183-3b91ffe1-49dd-47b4-870e-f463e3957172.png">

**Comment by bailicangdu** [comment]
感谢反馈，最新文档请参考 https://micro-zoe.github.io/micro-app/
