### ISSUE TITLE
[micro-app from runScript] app appName:  SyntaxError: Cannot use 'import.meta' outside a module (at main.ts?t=1680052288517:3:405)

### ISSUE THREAD

**Issue by dean16930** [jd-opensource/micro-app#746]
请教下，容器和子应用都是Vite+vue3的情况下，子应用单独运行是正常的，在容器里访问为什么会报这种错误？
![1680055834978](https://user-images.githubusercontent.com/48011106/228408346-54271707-2317-4e66-a8da-71ab6559b6f2.png)

**Comment by 113655509** [comment]
同问，也碰到了同样问题，请问楼主解决了吗？

**Comment by betsylotus** [comment]
同问，也碰到了同样问题，请问楼主解决了吗？

**Comment by betsylotus** [comment]
> 请教下，容器和子应用都是Vite+vue3的情况下，子应用单独运行是正常的，在容器里访问为什么会报这种错误？ ![1680055834978](https://user-images.githubusercontent.com/48011106/228408346-54271707-2317-4e66-a8da-71ab6559b6f2.png)

https://micro-zoe.com/docs/1.x/#/zh-cn/framework/vite?id=%e4%bd%9c%e4%b8%ba%e5%ad%90%e5%ba%94%e7%94%a8

**Comment by lecheng-lc** [comment]
https://zeroing.jd.com/micro-app/docs.html#/zh-cn/framework/vite  

> > 请教下，容器和子应用都是Vite+vue3的情况下，子应用单独运行是正常的，在容器里访问为什么会报这种错误？ ![1680055834978](https://user-images.githubusercontent.com/48011106/228408346-54271707-2317-4e66-a8da-71ab6559b6f2.png)
> 
> https://micro-zoe.com/docs/1.x/#/zh-cn/framework/vite?id=%e4%bd%9c%e4%b8%ba%e5%ad%90%e5%ba%94%e7%94%a8

**Comment by lecheng-lc** [comment]
> 同问，也碰到了同样问题，请问楼主解决了吗？
https://zeroing.jd.com/micro-app/docs.html#/zh-cn/framework/vite

**Comment by lance631** [comment]
这个是怎么解决的，遇到同样问题

**Comment by salmanLee** [comment]
主：vite+vue3
子：vite+react
遇到同样问题

**Comment by ffzhen** [comment]
![image](https://github.com/micro-zoe/micro-app/assets/31466455/372826a1-89bb-4186-b369-8a7e7c589b75)在基座上启用iframe就可以了

**Comment by ghost** [comment]
子应用是vite，需开启 iframe沙箱
<img width="469" alt="image" src="https://github.com/micro-zoe/micro-app/assets/58690804/033445b9-97ac-47b3-abcb-0331d9652776">


https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/framework/vite?id=%e4%bd%9c%e4%b8%ba%e5%ad%90%e5%ba%94%e7%94%a8

**Comment by CooperSuperLiu** [comment]
主应用改成这样就好了
microApp.start({
    iframe: true,
})

**Comment by CooperSuperLiu** [comment]
主应用改成这样就好了
microApp.start({
    iframe: true,
})
