### ISSUE TITLE
angular15为子应用，单独访问没问题，放到<micro-app>标签里面页面不显示

### ISSUE THREAD

**Issue by xiao-zhang-923** [jd-opensource/micro-app#747]
## 问题描述
> 问题的具体描述

## 复现步骤
1.
2.

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。

## 环境信息
- micro-app版本：1.0.0-beta.1
- 主应用前端框架&版本：react16
- 子应用前端框架&版本：angular 15
- 构建工具&版本：

**Comment by xiao-zhang-923** [comment]
![Uploading 1680140726173.jpg…]()

**Comment by xiao-zhang-923** [comment]
可以了，但是有一个问题，我angular应用里面有一个declare let tinycolor: any;单独启动没问题，放到micro-app里面就报inycolor is not defined

**Comment by xiao-zhang-923** [comment]
这个问题我也解决了，现在是一个问题，子应用放到micro-app里面有页面了，但是未能正确执行
Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.

**Comment by xiao-zhang-923** [comment]
ChunkLoadError: Loading chunk xxx failed.

**Comment by lionzhong** [comment]
这个复现特别简单，只需要把子应用升级官方示例至15+，懒加载模块一定出现类似：
app-routing.module.ts:10  ERROR Error: Uncaught (in promise): ChunkLoadError: Loading chunk src_app_lazy_lazy_module_ts failed.
(error: http://localhost:4200/src_app_lazy_lazy_module_ts.js)
ChunkLoadError: Loading chunk src_app_lazy_lazy_module_ts failed.
