### ISSUE TITLE
在开启iframe模式时，关闭虚拟路由系统并未生效

### ISSUE THREAD

**Issue by jiaozhiye** [jd-opensource/micro-app#748]
## 问题描述
在开启iframe模式时，关闭虚拟路由系统并未生效

## 上传截图
![image](https://user-images.githubusercontent.com/22720488/228705483-011254fa-0418-435c-bab7-feb55f78cd03.png)
![image](https://user-images.githubusercontent.com/22720488/228706052-e7991b1d-d6d6-42ee-8734-25b13e0692fb.png)

## 环境信息
- micro-app版本：1.0.0-beta.1
- 主应用前端框架&版本：react
- 子应用前端框架&版本：react
- 构建工具&版本：webpack5.75.0

**Comment by bailicangdu** [comment]
iframe模式暂时无法关闭虚拟路由

**Comment by daughterRui** [comment]
强烈建议iframe模式下可以控制是否关闭虚拟路由

**Comment by hmilin** [comment]
同求，希望iframe模式可以支持关闭虚拟路由，否则使用vite作为子应用时，对子应用侵入性太大

**Comment by bailicangdu** [comment]
已发布最新版1.0.0-beta.4，iframe沙箱支持关闭虚拟路由，详情参考：https://github.com/micro-zoe/micro-app/releases/tag/v1.0.0-beta.4

**Comment by bailicangdu** [comment]
已发布最新版1.0.0-beta.4，iframe沙箱支持关闭虚拟路由，详情参考：https://github.com/micro-zoe/micro-app/releases/tag/v1.0.0-beta.4
