### ISSUE TITLE
如何获取全局globalData数据

### ISSUE THREAD

**Issue by liugangtaotie** [jd-opensource/micro-app#75]
## Describe the bug
> 目前，搭建了一个基于mobile的微前端，基座是vite，子应用也是vite，基座是可以设置globalData，但是子应用想获取globalData，没有对应的api

站点项目：https://github.com/liugangtaotie/micro-app-mobile-code

## To Reproduce
1. 需要提供 getGlobalData，已便获取globalData

## Screenshots
> If possible, please upload screenshots of the code, console, terminal, etc. to help us understand your problem.

## Reproduce repository
> Please provide a condensed code repository and upload it to your own github to help us reproduce your problem.

## Environment
- micro-app version:0.2.5
- framework of base app & version: 
- framework of sub app & version:
- Build tools & version:

**Comment by bailicangdu** [comment]
你可以在网上找一套发布订阅系统挂在window上，也能达到同样的效果

**Comment by liugangtaotie** [comment]
> 你可以在网上找一套发布订阅系统挂在window上，也能达到同样的效果

还有个问题，👆上面搭建的微前端（基座为vite、子应用为vite）,子应用与子应用，子应用与基座都没有办法进行跳转，如果可以，看一下上面项目的跳转逻辑，谢谢了

```shell
 // 跳转sub-first
  gotoMainHome() {
    history.pushState(null, null, "main-home");

    console.info("1111111", window);

    // 主动触发一次popstate事件
    window.dispatchEvent(new PopStateEvent("popstate", { state: null }));
  }

  // 跳转 sub-second
  gotoSubSecond() {
    history.pushState(null, null, "sub-second");
    // 主动触发一次popstate事件
    window.dispatchEvent(new PopStateEvent("popstate", { state: null }));
  }
```

**Comment by qianqian05723** [comment]
我有个想法，子应用都通过路由守卫拦截即将跳转的URL，然后通过全局通信上报到基座应用，基座应用在分发跳转对应的子应用，这个不知道行不行？

**Comment by liugangtaotie** [comment]
> 我有个想法，子应用都通过路由守卫拦截即将跳转的URL，然后通过全局通信上报到基座应用，基座应用在分发跳转对应的子应用，这个不知道行不行？

**Comment by liugangtaotie** [comment]
> 我有个想法，子应用都通过路由守卫拦截即将跳转的URL，然后通过全局通信上报到基座应用，基座应用在分发跳转对应的子应用，这个不知道行不行？

> 尝试一下，看一下能不能实现

**Comment by liugangtaotie** [comment]
> > 我有个想法，子应用都通过路由守卫拦截即将跳转的URL，然后通过全局通信上报到基座应用，基座应用在分发跳转对应的子应用，这个不知道行不行？
> 
> > 尝试一下，看一下能不能实现

已经解决！
```shell
 // 跳转sub-first
  gotoMainHome() {
    history.pushState(null, null, "main-home");

    // 主动触发一次popstate事件
    window.dispatchEvent(new PopStateEvent("popstate", { state: null }));

    setTimeout(() => {
      location.reload();
    }, 100);
  }

```
