### ISSUE TITLE
静态json文件怎么加载

### ISSUE THREAD

**Issue by xiao-zhang-923** [jd-opensource/micro-app#750]
## 背景
> 描述您希望改进的问题。
静态json文件怎么加载呢，现在angular作为一个子应用，因为加载这句话报错
## 期望的效果

这个怎么加载。。。。
export class WebpackTranslateLoader implements TranslateLoader {
  getTranslation(lang: string): Observable<any> {
    console.log(from(import(`../assets/i18n/${lang}.json`)))
    return from(import(`../assets/i18n/${lang}.json`));
  }
}

**Comment by bailicangdu** [comment]
地址404，还是加载成功后报错？

**Comment by xiao-zhang-923** [comment]
请求是304，请求地址不对，我的子应用端口是4200，但是它给我请求的端口是3000，返回结果是js 禁用

**Comment by xiao-zhang-923** [comment]
不是我不提交git，是我的子应用还得请求后台，后台你还得用docker部署，不然子应用启动不了
改到服务器上就跨域啦

**Comment by bailicangdu** [comment]
使用绝对地址请求呢

**Comment by xiao-zhang-923** [comment]
一样的错误，还有我angular路由loadChildren这个方法不是使用的懒加载，放到micro-app里面也报错

**Comment by bailicangdu** [comment]
有没有复现的方式或案例？

**Comment by xiao-zhang-923** [comment]
帮我解决这个问题吧，Can't bind to 'flexibleDimensions' since it isn't a known property of 'ng-template'
` <ng-template
        cdkConnectedOverlay
        [cdkConnectedOverlayOrigin]="accounttrigger"
        [flexibleDimensions]="true"
        [lockPosition]="true"
        [cdkConnectedOverlayOffsetY]="10"
        [cdkConnectedOverlayHasBackdrop]="true"
        [cdkConnectedOverlayPositions]="accountCardPositions"
        cdkConnectedOverlayBackdropClass="transparent-backdrop"
        [cdkConnectedOverlayOpen]="showAccount"
        (backdropClick)="showAccount = false"
        (detach)="showAccount = false"
      >
        <cnsl-accounts-card
          @accounts
          class="a_card"
          *ngIf="showAccount"
          (closedCard)="showAccount = false"
          [user]="user"
          [iamuser]="['iam.write$'] | hasRole | async"
        >
        </cnsl-accounts-card>
      </ng-template>`
我这个项目自己启动就没事，但是用micro-app框架启动就报这个错

**Comment by Huansheng1** [comment]
我是通过window的环境变量来判断是否是微前端环境，给它加上子应用的绝对路径来做的
