### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'dynamicChildren')

### ISSUE THREAD

**Issue by xuxu-1997** [jd-opensource/micro-app#752]
子app偶尔跳转出现这个问题导致不能跳转。基座和子app都是vue3
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'dynamicChildren')

**Comment by bailicangdu** [comment]
能提供复现的demo吗

**Comment by xuxu-1997** [comment]
> 能提供复现的demo吗
触发机制是偶尔的，目前没有测试出具体触发的条件，但是跳转频繁的时候好像就会出现。

**Comment by bailicangdu** [comment]
没遇到这样的问题，也没人反馈过类似的问题，没有复现的方式无法定位和解决😂

**Comment by xuxu-1997** [comment]
> 能提供复现的demo吗

目前测试出触发的场景是子app A页面 => B页面，触发router.back()回到A页面，再跳转B页面,再触发router.back()的时候会百分百触发，我再去单独创建一个demo测试一下看是不是所有都会出现这个问题，大概触发逻辑就是这样子，谢谢

**Comment by xuxu-1997** [comment]
已解决，vue3的teleport挂载位置不合适会出现这个错误
