### ISSUE TITLE
1.0里中通信跟0.8通信的结果不一致导致的问题

### ISSUE THREAD

**Issue by yahoolcj** [jd-opensource/micro-app#753]
## 背景
> 描述您希望改进的问题。
在0.8.x版本里 我可以在基座应用里调用多次setData并且是同一个结构，让子应用根据启用某个字段的值判断需要的操作，也就是定义了通信参数规范，但是在1.0里。当我调用了次setData之后，被框架将参数合并层了一个对象，导致我每次发送的参数都会被下次参数覆盖（因为发送的参数内 字段名称一样，只有值不一样）。
例如父基座是这样发送的。
```js
this.$micro.setData('monitoring', {
        action: 'getHeader',
        payload: {aa"},
      })
      this.$micro.setData('monitoring', {
        action: 'getData',
        payload: [],
      })
```
子应用接受：
```js
window.microApp.addDataListener(res => {
       
        // 获取header
        if (res.action == 'getHeader') {
          this.$store.dispatch('setHeader', res.payload)
        }
        // 获取权限
        if (res.action == 'getPermissions') {
          this.$store.dispatch('setPermissions', res.payload)
        }
      })
```
在0.8版本时 每次setData事件都是独立的，可以让我准确碰撞到子应用里监听的代码块。但是升到1.0之后 2个setData事件被合并成了一个，并且参数也因为同键名原因被覆盖。。。没办法进入对应的判断里

但是由于需要keep-alive的原因必须升到1.0。 
## 期望的效果
给一个合理的解决方案

**Comment by bailicangdu** [comment]
你的意思是旧数据产生影响？可以在每次基座发送数据前清空一下数据
<img width="694" alt="image" src="https://user-images.githubusercontent.com/20297227/229097568-f050e19e-1a3b-4ada-bbf1-b2cf84ce87cf.png">

**Comment by yahoolcj** [comment]
不是  在0.8中 按照图一的代码 我在子应用的监听函数中会触发2次，每次都是对应的setData事件传过来的参数，这样我就可以在一个函数里根据action判断setData要做的事情，但是1.0中文档说会把这两次setData合并到下个帧执行 ，就变成实际到子应用的监听函数中只触发了一次。并且拿到的只是最后一次setData的参数。导致我子应用监听函数内部的前面那些if判断根本进不去

**Comment by bailicangdu** [comment]
那就只能等到一次数据发送结束后再发送新的数据 
<img width="673" alt="image" src="https://user-images.githubusercontent.com/20297227/229122499-042fb5e7-cdda-463c-b69f-87f6024b3ca5.png">

**Comment by yahoolcj** [comment]
请问间隔多久内的setData会被合并为一帧，我想使用setTimeout或者requestAnimationFrame将每个setData的执行延迟，保证每次setData可以独立触发一次子应用的监听事件

**Comment by bailicangdu** [comment]
> 请问间隔多久内的setData会被合并为一帧，我想使用setTimeout或者requestAnimationFrame将每个setData的执行延迟，保证每次setData可以独立触发一次子应用的监听事件

可以，setData是promise异步

**Comment by yahoolcj** [comment]
还是想知道为什么在0.8版本中开启了KeepAlive之后 页面打不开，子应用在app.vue中添加的监听事件监听不到基座在onMountd时发送的数据

**Comment by hulksqj** [comment]
我也是 子应用在main.js中添加的监听事件 无法监听 主应用的 microApp.setData(appName, { path: childPath })

**Comment by yahoolcj** [comment]
> 我也是 子应用在main.js中添加的监听事件监听 microApp.setData(appName, { path: childPath })

我已经不使用官方的通信方式，自己写了一套替换多个产品线，更稳定可控点

**Comment by hulksqj** [comment]
> > 我也是 子应用在main.js中添加的监听事件监听 microApp.setData(appName, { path: childPath })
> 
> 我已经不使用官方的通信方式，自己写了一套替换多个产品线，更稳定可控点

大佬，能提供下思路参考下吗

**Comment by yahoolcj** [comment]
> > > 我也是 子应用在main.js中添加的监听事件监听 microApp.setData(appName, { path: childPath })
> > 
> > 
> > 我已经不使用官方的通信方式，自己写了一套替换多个产品线，更稳定可控点
> 
> 大佬，能提供下思路参考下吗

利用window，暴露函数互相调用

**Comment by wangling404** [comment]
> 



> 不是 在0.8中 按照图一的代码 我在子应用的监听函数中会触发2次，每次都是对应的setData事件传过来的参数，这样我就可以在一个函数里根据action判断setData要做的事情，但是1.0中文档说会把这两次setData合并到下个帧执行 ，就变成实际到子应用的监听函数中只触发了一次。并且拿到的只是最后一次setData的参数。导致我子应用监听函数内部的前面那些if判断根本进不去

同样遇到这个问题，有没有官方解决下呀？

**Comment by raoenhui** [comment]
> [setData第三个参数为回调函数，它会在数据发送结束后执行](https://micro-zoe.com/docs/1.x/#/zh-cn/data?id=setdata%e7%ac%ac%e4%b8%89%e4%b8%aa%e5%8f%82%e6%95%b0%e4%b8%ba%e5%9b%9e%e8%b0%83%e5%87%bd%e6%95%b0%ef%bc%8c%e5%ae%83%e4%bc%9a%e5%9c%a8%e6%95%b0%e6%8d%ae%e5%8f%91%e9%80%81%e7%bb%93%e6%9d%9f%e5%90%8e%e6%89%a7%e8%a1%8c)
可以在回调函数里面发送下一次数据

**Comment by wen-gang** [comment]
一样的问题，主应用发送的数据，子应用监听的时候合并成一个了。本来考key的名字不同来触发不同的函数，现在每次都传过来所有数据，每次都执行，很傻缺的设计。。。

**Comment by refinist** [comment]
我个人感觉这块设计主要是处理数据，而目前的大部分业务比较倾向“事件”，很多情况都会利用对象的 type 来进行判断，然后触发不用的逻辑，如：
```
window.microApp.addDataListener(({ type, payload }) => {
    if (type === 'xxx') {}
    else if (type === 'xxx') {}
    else if (type === 'xxx') {}
  });
```
基座推送的话，子应用所有的 `window.microApp.addDataListener` 代码块都会被执行。

建议：是否可以仍然保留这块逻辑，然后再新增一块“真正的事件总线"逻辑，类似 mitt。

我有看过作者大大的文章有说到：”发布订阅系统很灵活，但太过于灵活可能会导致数据传输的混乱，必须定义一套清晰的数据流“，但是我个人认为既然要开发微应用，基座和各个子应用之间团队都是拿捏好的，没必要处理得那么严格（就有点不好用了），举个不恰当例子，好比 vue 中的规定的单向数据流，然后 props 可以是一个对象，子组件也可以更改这个 prop，违反了规则但是可运行且方便！只要编程者保持清醒这块没有必要那么严格。

目前我的临时解决方案：在基座 window 上挂 mitt，然后就可以随意通信了

**Comment by bailicangdu** [comment]
> 我个人感觉这块设计主要是处理数据，而目前的大部分业务比较倾向“事件”，很多情况都会利用对象的 type 来进行判断，然后触发不用的逻辑，如：
> 
> ```
> window.microApp.addDataListener(({ type, payload }) => {
>     if (type === 'xxx') {}
>     else if (type === 'xxx') {}
>     else if (type === 'xxx') {}
>   });
> ```
> 
> 基座推送的话，子应用所有的 `window.microApp.addDataListener` 代码块都会被执行。
> 
> 建议：是否可以仍然保留这块逻辑，然后再新增一块“真正的事件总线"逻辑，类似 mitt。
> 
> 我有看过作者大大的文章有说到：”发布订阅系统很灵活，但太过于灵活可能会导致数据传输的混乱，必须定义一套清晰的数据流“，但是我个人认为既然要开发微应用，基座和各个子应用之间团队都是拿捏好的，没必要处理得那么严格（就有点不好用了），举个不恰当例子，好比 vue 中的规定的单向数据流，然后 props 可以是一个对象，子组件也可以更改这个 prop，违反了规则但是可运行且方便！只要编程者保持清醒这块没有必要那么严格。
> 
> 目前我的临时解决方案：在基座 window 上挂 mitt，然后就可以随意通信了

关键就是在易用性和安全性之间做出取舍，我们会考虑一下的，谢谢反馈

**Comment by refinist** [comment]
> > 我个人感觉这块设计主要是处理数据，而目前的大部分业务比较倾向“事件”，很多情况都会利用对象的 type 来进行判断，然后触发不用的逻辑，如：
> > ```
> > window.microApp.addDataListener(({ type, payload }) => {
> >     if (type === 'xxx') {}
> >     else if (type === 'xxx') {}
> >     else if (type === 'xxx') {}
> >   });
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 基座推送的话，子应用所有的 `window.microApp.addDataListener` 代码块都会被执行。
> > 建议：是否可以仍然保留这块逻辑，然后再新增一块“真正的事件总线"逻辑，类似 mitt。
> > 我有看过作者大大的文章有说到：”发布订阅系统很灵活，但太过于灵活可能会导致数据传输的混乱，必须定义一套清晰的数据流“，但是我个人认为既然要开发微应用，基座和各个子应用之间团队都是拿捏好的，没必要处理得那么严格（就有点不好用了），举个不恰当例子，好比 vue 中的规定的单向数据流，然后 props 可以是一个对象，子组件也可以更改这个 prop，违反了规则但是可运行且方便！只要编程者保持清醒这块没有必要那么严格。
> > 目前我的临时解决方案：在基座 window 上挂 mitt，然后就可以随意通信了
> 
> 关键就是在易用性和安全性之间做出取舍，我们会考虑一下的，谢谢反馈

😃 期待有更好的解决方案，很棒的库，👍🏻👍🏻👍🏻

**Comment by refinist** [comment]
我又来了😃，最近看了 wujie 的通信方案，发现这种方案才是易用的，https://wujie-micro.github.io/doc/guide/communication.html#eventbus-%E9%80%9A%E4%BF%A1。以事件为驱动，才更贴近业务。
我也看了 qiankun 的方案，感觉比 micro-app 更难使用，都是以传递”数据“设计，而没有考虑”事件“。
其实这个功能对于 micro-app 易如反掌，只能说设计理念不一样吧。
wujie 我估计也是站在巨人（micro-app）的肩膀上 🙊

**Comment by kuoruan** [comment]
+1，希望在当前数据通讯的基础上，再提供一个全局的事件通讯机制
