### ISSUE TITLE
子通信父跳转父的页面，父的页面replace回子页面，再次返回丢失基础路由。

### ISSUE THREAD

**Issue by xuxu-1997** [jd-opensource/micro-app#754]
## 问题描述
> 进入子APP => 进入A页面 => A页面发送消息通知基座跳转到基座about页面 => 基座about页面replace回子app的A页面 => 子APP的A页面的返回(router.back)丢失了基础路由。

## 复现步骤
1.进入子APP
2.进入A页面
3. A页面发送消息通知基座跳转到基座about页面
4.  基座about页面replace回子app的A页面
5.  子APP的A页面的返回(router.back)丢失了基础路由

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。

## 复现仓库
https://github.com/xuxu-1997/MicroDemo.git

## 环境信息
- micro-app版本：0.8.10
- 主应用前端框架&版本：Vue3
- 子应用前端框架&版本：Vue3
- 构建工具&版本：主应用Vite 子应用Webpack

**Comment by bailicangdu** [comment]
在0.8版本中主、子都是vue3，路由冲突无法解决，需要升级到1.0并开启虚拟路由才可以，但1.0仍处在测试阶段，请根据自己的情况选择 https://micro-zoe.com/docs/1.x/#/zh-cn/start

**Comment by xuxu-1997** [comment]
> 在0.8版本中主、子都是vue3，路由冲突无法解决，需要升级到1.0并开启虚拟路由才可以，但1.0仍处在测试阶段，请根据自己的情况选择 https://micro-zoe.com/docs/1.x/#/zh-cn/start

你好想問下，升級1.0後，會對之前的其他功能有影響嗎？

**Comment by hlwen** [comment]
> 在0.8版本中主、子都是vue3，路由冲突无法解决，需要升级到1.0并开启虚拟路由才可以，但1.0仍处在测试阶段，请根据自己的情况选择 https://micro-zoe.com/docs/1.x/#/zh-cn/start

虚拟路由能否不在地址栏显示，而且虚拟路由变化后真是路由也能及时变化

**Comment by bailicangdu** [comment]
> > 在0.8版本中主、子都是vue3，路由冲突无法解决，需要升级到1.0并开启虚拟路由才可以，但1.0仍处在测试阶段，请根据自己的情况选择 https://micro-zoe.com/docs/1.x/#/zh-cn/start
> 
> 虚拟路由能否不在地址栏显示，而且虚拟路由变化后真是路由也能及时变化

不可以，否则刷新浏览器路由信息会丢失
