### ISSUE TITLE
关闭虚拟路由，偶发的会在地址栏出现虚拟路由的search参数

### ISSUE THREAD

**Issue by jiaozhiye** [jd-opensource/micro-app#755]
## 问题描述
关闭虚拟路由，偶发的会在地址栏出现虚拟路由的search参数，但是没发现规律，感觉像是资源初次加载，打开子应用那一刻并未关闭虚拟路由。

## 环境信息
- micro-app版本：1.0.0-beta.1
- 主应用前端框架&版本：react
- 子应用前端框架&版本：react
- 构建工具&版本：webpack5.75.0

**Comment by bailicangdu** [comment]
设置了iframe沙箱吗

**Comment by jiaozhiye** [comment]
> 设置了iframe沙箱吗

没开启iframe沙箱

**Comment by bailicangdu** [comment]
有复现的方式吗

**Comment by jiaozhiye** [comment]
> 有复现的方式吗

偶发的，也没发现规律，感觉每次发版之后出现的机率大一些，所以感觉重新拉取资源时，在渲染子应用的那一刻就会出现虚拟路由的search参数

**Comment by bailicangdu** [comment]
使用了预加载吗

**Comment by jiaozhiye** [comment]
> 使用了预加载吗

没有使用预加载
