### ISSUE TITLE
子应用使用element-plus会抛出Invalid event arguments: event validation failed for event "click"警告

### ISSUE THREAD

**Issue by SepVeneto** [jd-opensource/micro-app#756]
## 问题描述
子应用使用`vite`和`element-plus`，在基座中使用的时候会抛出`Invalid event arguments: event validation failed for event "click"`。

由于子应用开启了`iframe`，有没有可能是js环境的完全隔离，导致在基座环境下触发的`MouseEvent`无法通过子应用中element-plus的emit校验。
```js
{
  click: (evt) => evt instanceof MouseEvent
}
```

## 复现步骤
1. 子应用安装element-plus
2. 添加如下代码
```html
<template>
  <ElButton @click="handleClick">click me</ElButton>
</template>
<script setup>
function handleClick(evt) {
  console.log(evt instanceof MouseEvent, evt instanceof PointerEvent)
}
</script>
```
3. 在基座中引入该子应用，并点击按钮，会看到控制台抛出`Invalid event arguments: event validation failed for event "click".`

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。
![image](https://user-images.githubusercontent.com/20925980/229444856-0b8e10fd-d816-4a75-aaea-0032f09ce85b.png)

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。

## 环境信息
- micro-app版本：v1.0.0-beta.1
- 主应用前端框架&版本：vue3.2.47
- 子应用前端框架&版本：vue3.2.47
- 构建工具&版本：主应用 vite4.1.2; 子应用 vite4.2.1

`element-plus`导致的警告是小问题，但是如果子应用开启iframe使用了其它第三方库，其中有依赖`instanceof`的逻辑就比较麻烦了。

有没有什么处理的方法

**Comment by SepVeneto** [comment]
试过`escapeProperties: ['MouseEvent']`，但是没有效果。

想不到什么更好的方法，暂时是通过vite插件将`evt => evt instanceof MouseEvent`改为`evt => evt instanceof window.rawWindow.MosueEvent`

```ts
function patchRawWindow(): Plugin {
  return {
    name: 'patchRawWindow',
    transform(code, id) {
      if (id.includes('/.vite/deps/chunk')) {
        let isFind = false
        const _code = code.replace(
          /instanceof (([A-Z]{1}[a-zA-Z]+)?Event)/g,
          (_, $1) => {
            isFind = true
            return `instanceof (patchRawWindow('${$1}') || ${$1})`
          },
        )
        const fn = `function patchRawWindow(key) {
          if (window.__MICRO_APP_ENVIRONMENT__ && window[key]) {
            return window.rawWindow[key]
          } else {
            return false
          }
        }\n`
        return isFind ? fn + _code : _code
      }
      return code
    },
  }
}
```

**Comment by zyf540860996** [comment]
能不能贴下完整的解决代码

**Comment by SepVeneto** [comment]
> 能不能贴下完整的解决代码

 @zyf540860996 
这个其实就是写了一个vite插件，在编译阶段修改了所有校验的逻辑

```ts
import { URL, fileURLToPath } from 'node:url'

import { type Plugin, defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import vueJsx from '@vitejs/plugin-vue-jsx'

function patchRawWindow() {...}

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [vue(), vueJsx(), patchRawWindow()],
  resolve: {
    alias: {
      '@': fileURLToPath(new URL('./src', import.meta.url)),
    },
  },
})

```
这个是vite的，如果子应用是其它打包工具的话，得自己实现了。
如果有需要，我也可以写一个通用的插件。

**Comment by zyf540860996** [comment]
> > 能不能贴下完整的解决代码
> 
> @zyf540860996 这个其实就是写了一个vite插件，在编译阶段修改了所有校验的逻辑
> 
> ```ts
> import { URL, fileURLToPath } from 'node:url'
> 
> import { type Plugin, defineConfig } from 'vite'
> import vue from '@vitejs/plugin-vue'
> import vueJsx from '@vitejs/plugin-vue-jsx'
> 
> function patchRawWindow() {...}
> 
> // https://vitejs.dev/config/
> export default defineConfig({
>   plugins: [vue(), vueJsx(), patchRawWindow()],
>   resolve: {
>     alias: {
>       '@': fileURLToPath(new URL('./src', import.meta.url)),
>     },
>   },
> })
> ```
> 
> 这个是vite的，如果子应用是其它打包工具的话，得自己实现了。 如果有需要，我也可以写一个通用的插件。

感谢，已解决

**Comment by ycx0303** [comment]
没有生效

**Comment by shen-lan** [comment]
patchRawWindow 配置子应用还是基座应用？两边都试了似乎不生效....😭
