### ISSUE TITLE
主应用可以给子应用共享安装的插件吗？

### ISSUE THREAD

**Issue by elarbor** [jd-opensource/micro-app#757]
比如主应用安装了elementUI，子应用也需要，可以分享给子应用吗？
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/43592730/229668776-b49d6589-6a88-4b05-908f-301d3ce8300f.png">

**Comment by bailicangdu** [comment]
如果是全量引入，可以将elmentUI这个变量发送给子应用注册
