### ISSUE TITLE
keep-alive潜藏的问题讨论

### ISSUE THREAD

**Issue by Albert-cord** [jd-opensource/micro-app#761]
## 背景
由于keep-alive的实现是通过在内存里记录一个傀儡div作为临时节点来实现，然后由挂载节点时判断appInstanceMap是否记录了实例，且其keepAlive是否为true来决定隐藏、激活时应用上述傀儡div，将shadowRoot与之拷贝或者粘贴
>希望改进的问题：

根据上述的实现，那么在子应用A(keep-alive)切换到子应用B(也keep-alive)时存在一个问题，假如子应用B的加载稍慢的情况下，交互比较快的情况下，即交互过程：子应用A->子应用B->子应用A，然而子应用B还没加载到script或者加载到了，但是Dom渲染（依赖某些异步逻辑），此时的shadowRoot还是空的，那么内存里的傀儡div实际储存的是空的shadowRoot，之后再由子应用A->子应用B时，那么shadowRoot也会是空的
## 期望的效果：
（全keep-alive）子应用A->子应用B->子应用A->子应用B的链路不必考虑子应用的加载情况
>可以讨论的想法跟建议

考虑通过display: none的方式进行应用的切换，然后我看window隔离的功能已经通过sandbox实现了，document隔离的功能alpha版本也支持了，不知道会不会有影响？然后还有对虚拟路由的影响？
希望作者指出其中不足，跟当时为什么采用内存切换的方式实现

**Comment by bailicangdu** [comment]
确实存在所述问题。不使用display: none是因为micro-app元素从文档中删除后才会触发隐藏操作，再次渲染时micro-app元素会重建，所以需要一个临时容器记录dom

**Comment by Albert-cord** [comment]
> 确实存在所述问题。不使用display: none是因为micro-app元素从文档中删除后才会触发隐藏操作，再次渲染时micro-app元素会重建，所以需要一个临时容器记录dom

了解。
那么可以考虑不做这个keep-alive功能？
将keep-alive的功能交由业务层user-land去管控，例如采用tab组件去维护一组micro-app，然后这样再向外暴露appManager的API来维护所有micro-app实例跟其之间的事件通信 
而且我看现在的事件已经支持了所有micro-app实例的通信，内部appInstanceMap、一些全局的状态、事件管控跟MicroAppElementInstance实例的通信都是采用appName的命名空间来管理，综上这个keep-alive功能是不是有些多余？

**Comment by Albert-cord** [comment]
如果还要保留keep-alive，建议是内部实现一个简易的tab组件来管控，作者认为如何？有其他一些我没考虑到的问题吗？

**Comment by bailicangdu** [comment]
> > 确实存在所述问题。不使用display: none是因为micro-app元素从文档中删除后才会触发隐藏操作，再次渲染时micro-app元素会重建，所以需要一个临时容器记录dom
> 
> 了解。 那么可以考虑不做这个keep-alive功能？ 将keep-alive的功能交由业务层user-land去管控，例如采用tab组件去维护一组micro-app，然后这样再向外暴露appManager的API来维护所有micro-app实例跟其之间的事件通信 而且我看现在的事件已经支持了所有micro-app实例的通信，内部appInstanceMap、一些全局的状态、事件管控跟MicroAppElementInstance实例的通信都是采用appName的命名空间来管理，综上这个keep-alive功能是不是有些多余？

keep-alive用于缓存元素状态，你说的是通过数据维护元素状态？当然也可以做到，但成本更高

**Comment by bailicangdu** [comment]
keep-alive在加载前卸载导致二次渲染失败的问题会在下个版本中修复

**Comment by Albert-cord** [comment]
> > > 确实存在所述问题。不使用display: none是因为micro-app元素从文档中删除后才会触发隐藏操作，再次渲染时micro-app元素会重建，所以需要一个临时容器记录dom
> > 
> > 
> > 了解。 那么可以考虑不做这个keep-alive功能？ 将keep-alive的功能交由业务层user-land去管控，例如采用tab组件去维护一组micro-app，然后这样再向外暴露appManager的API来维护所有micro-app实例跟其之间的事件通信 而且我看现在的事件已经支持了所有micro-app实例的通信，内部appInstanceMap、一些全局的状态、事件管控跟MicroAppElementInstance实例的通信都是采用appName的命名空间来管理，综上这个keep-alive功能是不是有些多余？
> 
> keep-alive用于缓存元素状态，你说的是通过数据维护元素状态？当然也可以做到，但成本更高

不是，我的意思是考虑删掉keep-alive的功能，然后交给用户自己去解决，或者就是我后面回复的，内部实现一个简易tab组件，不太明白你说的`通过数据维护元素状态`，是第三种方式吗？（我理解你说的`通过数据维护元素状态`就是现在当下使用的实现方式）  

因为现在的实现的隐藏问题是不知道当前的elementInstance的shadowRoot的状态是否允许被操作（即被cloneContainer到一个临时div上），我想的是两种方式解决：    

1. 是在新版本去掉keep-alive的功能，这种功能交由用户层自行去解决，一个微前端库为什么需要实现这种功能？    

2. 就是实现一个简易tab了，就外面套一个micro-app[-libraryName]，里面渲染多个micro-app-appName，然后哪个keep-alive就使得哪个显示

**Comment by bailicangdu** [comment]
用户可以选择自己实现，但成本太高了，即便是维护一个tab，那么功能和实现方式也和现在的keep-alive差不多

**Comment by bailicangdu** [comment]
另外你说的`不知道当前的elementInstance的shadowRoot的状态是否允许被操作（即被cloneContainer到一个临时div上）`，这个临时的div也是可有可无的，后续可能会去掉

**Comment by hlwen** [comment]
不知道开启keep-alive后，基座向已经隐藏的子应用发送事件能否成功执行，有时候子应用切换到后台后有些清理功能能否异步操作

**Comment by Albert-cord** [comment]
> 确实存在所述问题。不使用display: none是因为micro-app元素从文档中删除后才会触发隐藏操作，再次渲染时micro-app元素会重建，所以需要一个临时容器记录dom

其实回头看，这个问题应该不是问题吧，因为这只是当下的逻辑
我觉得使用display: none反倒是直观的，因为实际上js逻辑在keep-alive-hidden是也会继续跑的

**Comment by Albert-cord** [comment]
> 不知道开启keep-alive后，基座向已经隐藏的子应用发送事件能否成功执行，有时候子应用切换到后台后有些清理功能能否异步操作

这个可能要具体看下hidden状态下的事件分发逻辑，但我估计没做处理；如果没做处理，那么是可以成功执行的，因为js逻辑还是存在的。

**Comment by bailicangdu** [comment]
问题已修复，参考 https://github.com/micro-zoe/micro-app/releases/tag/v1.0.0-beta.3

**Comment by xionglongxiang** [comment]
> 问题已修复，参考 https://github.com/micro-zoe/micro-app/releases/tag/v1.0.0-beta.3

实测，被标记为keep-alive 的应用A。从A应用跳转到其他应用B后，就无法跳回A了。页面是卡在B应用的。且B应用不会被卸载。
