### ISSUE TITLE
基座应用切换路由时，新路由动态创建的 link 标签被待销毁的老路由组件的 <micro-app> 拦截，但并未创建导致基座样式丢失

### ISSUE THREAD

**Issue by hoperyy** [jd-opensource/micro-app#763]
## 问题描述
> 问题的具体描述

## 复现步骤
1. 基座应用 A 路由的内容区域使用 micro-app，然后切换到 B 路由（没用 micro-app）
2. B 路由页面的第一个样式丢失，页面样式混乱
3. B 路由页面的其他静态资源标签正常被创建和插入 DOM

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。

## 环境信息
- micro-app版本：0.8.5~1.0.0.alpha.x 都试过了
- 主应用前端框架&版本：umi3 + react
- 子应用前端框架&版本：umi4 + react
- 构建工具&版本：

**Comment by hoperyy** [comment]
因为 A 路由中的 micro-app 会被销毁，怀疑是 B 路由的 dynamic script / link 通过 appendChild 创建的，而 micro-app 拦截了 appendChild 做 fetch 操作。

随着 A 路由的组件被销毁，micro-app 随即被销毁，后面 B 路由的其他静态资源就没有被拦截了

**Comment by bailicangdu** [comment]
在跳转前清空元素作用域，参考 https://micro-zoe.com/docs/1.x/#/zh-cn/dom-scope?id=%e8%a7%a3%e9%99%a4%e5%85%83%e7%b4%a0%e7%bb%91%e5%ae%9a

**Comment by hoperyy** [comment]
是不是可以理解为，切换路由的时候，等老路由的组件渲染被销毁后，再发出新路由组件的 dynamic 资源？

**Comment by bailicangdu** [comment]
是的

**Comment by prettyboyweiwei** [comment]
@bailicangdu 从子页面切换到基座页面，基座 js /css 会被拦截 fetch，这个在我们的其他数个 micro 项目均未出现，官方的示例也不存在。这有可能是哪方面原因呢？

**Comment by bailicangdu** [comment]
要看具体的代码，比如子应用控制基座跳转

**Comment by prettyboyweiwei** [comment]
跳转是基座的菜单在跳转

**Comment by prettyboyweiwei** [comment]
@bailicangdu 另外有个方案也能使页面样式正常，就是在基座应用 microApp.start() 之前加入如下代码。请帮忙评估下这样是否可行？
```typescript
(() => {
    const rawAppendChild = Element.prototype.appendChild
    Object.defineProperty(HTMLLinkElement.prototype, 'href', {
        set: function (href) {
            // 根据 path 判断为主应用的 link 自行全局加载，禁掉被子应用加载，子应用的 link 则不做处理
            let add = false
            // 判断为主应用的 link，假设子应用是其他端口
            if (isFatherStatic(location)) {
                // 禁掉被子应用加载
                this.setAttribute('exclude', 'true')
                add = true
            }
            this.setAttribute('href', href)
            // 加载，插入到真正的 head 里
            if (add) rawAppendChild.call(new Function('return window.document.head')(), this)
        },
    })
})()

microApp.start()
```

**Comment by prettyboyweiwei** [comment]
主要是想这能导致跳转的原因有很多，需要做很多处理来加重置作用域或添加延迟。且这样的话代码只用写在基座应用里

**Comment by hoperyy** [comment]
![image](https://user-images.githubusercontent.com/5757051/231089267-e94b6623-d8f9-4739-b0f5-b6cb54fad018.png)

**Comment by bailicangdu** [comment]
> @bailicangdu 另外有个方案也能使页面样式正常，就是在基座应用 microApp.start() 之前加入如下代码。请帮忙评估下这样是否可行？
> 
> ```ts
> (() => {
>     const rawAppendChild = Element.prototype.appendChild
>     Object.defineProperty(HTMLLinkElement.prototype, 'href', {
>         set: function (href) {
>             // 根据 path 判断为主应用的 link 自行全局加载，禁掉被子应用加载，子应用的 link 则不做处理
>             let add = false
>             // 判断为主应用的 link，假设子应用是其他端口
>             if (isFatherStatic(location)) {
>                 // 禁掉被子应用加载
>                 this.setAttribute('exclude', 'true')
>                 add = true
>             }
>             this.setAttribute('href', href)
>             // 加载，插入到真正的 head 里
>             if (add) rawAppendChild.call(new Function('return window.document.head')(), this)
>         },
>     })
> })()
> 
> microApp.start()
> ```

可以，只要能判断地址的来源

**Comment by hoperyy** [comment]
> 

有可能是这个没问题的基座应用没有外链的 <link> 标签，因为我这边异常表现是只有 link 标签被待销毁的 micro-app 拦截并 fetch 了，而 script 标签没有

**Comment by ourfeel** [comment]
同遇到这个问题。  在B子应用 上 直接调用基座的history 进行切换基座页面的时候。 样式表被拦截调整为fetch请求。 原因是创建的时候  还携带_microappname 属性。

**Comment by ourfeel** [comment]
> 同遇到这个问题。 在B子应用 上 直接调用基座的history 进行切换基座页面的时候。 样式表被拦截调整为fetch请求。 原因是创建的时候 还携带_microappname 属性。

发现执行完一堆清空微前端的操作后 销毁生命周期执行removedomscope 未触发前。 已经有资源被拦截进入fetch。
