### ISSUE TITLE
iframe 模式下无法关闭虚拟路由

### ISSUE THREAD

**Issue by daughterRui** [jd-opensource/micro-app#768]
## 背景
> 描述您希望改进的问题。
之前老版本没有用虚拟路由，因为子应用现在是vite，导致需要升级micro-app，升级后设置关闭虚拟路由，但不起有作用，自动开启虚拟路由了,体验很不友好。
## 期望的效果
iframe 模式下 能控制虚拟路由是否开启，给用户一个选择

**Comment by mistyrain-jiangnan** [comment]
我这边也遇到了这个问题

**Comment by byc233518** [comment]
me too
