### ISSUE TITLE
可以只将某个Dom元素泄漏给子应用吗？

### ISSUE THREAD

**Issue by axis0093** [jd-opensource/micro-app#769]
## 问题描述

在子应用中调用微信的jssdk的方法，如扫码，返回主应用后，在主应用中再次调用扫码方法无效。

该问题在1.0.0 beta0-beta3可以复现，降级到1.0.0 alpha.10版本又好了。

从微信公众平台申请了一个测试App来编写复现用例，编写完成后发现竟然无法复现😂。我们使用的是政务微信，已经更新到了最新版本，推测可能是由于jsbrige和互联网版本微信不一致，实现方式不一样。

## 复现步骤
1.主应用初始化微信jssdk，然后通过wx.scanQRCode，启动摄像头扫码，可以正常扫码并得到结果。
2.打开子应用，通过window.rawWindow.wx.scanQRCode，启动摄像头扫码，可以正常扫码并得到扫码结果。（通过scopeProperties、escapeProperties插件也试过）
3.关闭子应用（keep-alive状态），通过unmountApp卸载，`window._microApp.unmountApp(this.appName, { clearAliveState: true })`后切换回主应用，再调用wx.scanQRCode扫码，无效，无法再打开摄像头。

## 原因分析
分析了一下微信jssdk，它通过创建iframe来传递消js调用原生代码的消息通知，会创建__WeixinJSBridgeIframe和__WeixinJSBridgeIframe_SetResult这两个元素，发起调用或者接收结果时，这两个元素的src会发生改变。而互联网版本的微信通过window.__wx对象来传递消息。

创建iframe的代码如下，这段代码应该是由微信建立jsbridge时通过android webview动态注入进来的，无法通过loader修改。

```  
  function _createQueueReadyIframe(doc) {
    if (!doc.getElementById("__WeixinJSBridgeIframe_SetResult")) {
      // _setResultIframe 的初始化
      _setResultIframe = doc.createElement("iframe");
      _setResultIframe.id = "__WeixinJSBridgeIframe_SetResult";
      _setResultIframe.style.display = "none";
      doc.documentElement.appendChild(_setResultIframe);
    }

    if (!doc.getElementById("__WeixinJSBridgeIframe")) {
      _readyMessageIframe = doc.createElement("iframe");
      _readyMessageIframe.id = "__WeixinJSBridgeIframe";
      _readyMessageIframe.style.display = "none";
      doc.documentElement.appendChild(_readyMessageIframe);
    }
  }
```
alpha.10版本中，子应用创建的iframe会创建在主应用的html下。
![alpha10](https://user-images.githubusercontent.com/6679227/232369301-70695885-f7e3-41f4-a57b-8f95c8e29629.png)

更新成beta.x版本后，该元素会被创建到micro-app下。
![betax](https://user-images.githubusercontent.com/6679227/232369494-0ad6f669-1dd4-430d-b874-24d7f9a6dba9.png)

关闭子应用后，子应用下的__WeixinJSBridgeIframe和__WeixinJSBridgeIframe_SetResult元素随着micro-app元素的移除被移除掉了。然后，在主应用中调用微信jssdk时，主应用中__WeixinJSBridgeIframe_SetResult和__WeixinJSBridgeIframe_SetResult元素仍然存在，这会导致主应用中的这两个iframe未被因为`doc.getElementById("__WeixinJSBridgeIframe_SetResult")`存在而未重建，_setResultIframe、_readyMessageIframe 引用的又是被删掉的对象。

## 临时解决方法

子应用关闭时，在主应用的dom中查找__WeixinJSBridgeIframe、__WeixinJSBridgeIframe_SetResult这两个iframe并删掉，这样下次调用时又会被_createQueueReadyIframe方法重建。

或者在子应用打开前，通过global中的processHtml对html进行处理，在html标签前面加上这两个iframe，这样子应用打开后不会重新创建iframe，引用仍然指向主应用的iframe。

尝试将js沙箱切换到iframe隔离方式，可以解决这个问题。但我们已有的几个应用作为子应用集成时又会出现问题。

请问有没有什么别的解决方法或者建议？

**Comment by bailicangdu** [comment]
可否提供一个demo帮助复现？

**Comment by axis0093** [comment]
> 可否提供一个demo帮助复现？

很抱歉，目前无法提供demo。

我尝试在微信公众平台申请了个测试应用编写复现用例，但是用互联网版本的微信无法复现这个问，因为互联网版本的微信的jsbridge使用的是__wx对象来传递消息的。

目前看来只能在我们使用的那个内部版本的政务微信能够复现，但是在互联网上又无法正常使用。

问题就是alpha版本和beta版本创建iframe的位置不一样，我觉得beta版本的创建的位置也什么问题（可能是修复了alpha版本的bug？），子应用本身元素就应该创建在micro-app标签内部。

主要是想问问能不能在把主应用的__WeixinJSBridgeIframe_SetResult和__WeixinJSBridgeIframe这两个对象泄漏出来，这样子应用通过doc.getElementById("__WeixinJSBridgeIframe_SetResult")就可以找到主应用中的对象，不重新创建，引用的对象也不会发生改变，从而规避这个问题。

**Comment by bailicangdu** [comment]
子应用只能查询到自己内部的元素，即便有其他方式也和你现在的处理方式差不多
