### ISSUE TITLE
iframe 模式下能否支持关闭虚拟路由系统

### ISSUE THREAD

**Issue by mistyrain-jiangnan** [jd-opensource/micro-app#771]
## 背景
> 描述您希望改进的问题。
iframe 模式下能否支持关闭虚拟路由系统
## 期望的效果
iframe 模式下支持关闭虚拟路由系统

**Comment by bailicangdu** [comment]
已发布最新版1.0.0-beta.4，iframe沙箱支持关闭虚拟路由，详情参考：https://github.com/micro-zoe/micro-app/releases/tag/v1.0.0-beta.4
