### ISSUE TITLE
子应用开启 keep-alive 会导致基座页面静态资源（js/css）执行顺序混乱而报错

### ISSUE THREAD

**Issue by hoperyy** [jd-opensource/micro-app#773]
## 问题描述
> 问题的具体描述

子应用开启 keep-alive 会导致基座页面报错

## 复现步骤
@micro-zoe/micro-app 以下版本均有此问题：0.8.5、0.8.10、1.0.0-alpha.10、1.0.0-beta.2、1.0.0-beta.3

<micro-app> 开启 keep-alive，基座应用刷新页面直接访问携带 <micro-app> 的页面后，通过菜单栏切换 history 路由，回退到基座应用页面。

是否开启 keep-alive 会影响基座应用页面的 js/css 加载顺序，导致页面报错（个别有特定逻辑的页面）。

1. 开启 keep-alive，基座应用的 js/css 通过 webpack:///node_modules/@micro-zoe/micro-app/lib/index.esm.js 创建 script/link，此时产生错误的加载顺序，会导致基座页面报错
2. 不开启，基座应用的 js/css 通过 webpack:///webpack/runtime/load script 和 webpack:///webpack/runtime/css loading 创建 script/link，此时加载顺序正常，基座页面正常运行

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。
数据安全不便于截图。

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。

```tsx
<micro-app keep-alive name="xxx" baseRoute="yyy" url="zzz" />
```

## 环境信息
- micro-app版本：均有此问题：0.8.5、0.8.10、1.0.0-alpha.10、1.0.0-beta.2、1.0.0-beta.3
- 主应用前端框架&版本：umi3 + react@16
- 子应用前端框架&版本：umi4 + react@18.2.0
- 构建工具&版本：

**Comment by hoperyy** [comment]
感觉 keep-alive 后 micro-app 拦截基座的 js / css 没啥问题，但：

1. 请求发出顺序正常
2. 请求返回顺序可能是乱的，我 debug 出来 micro-app 在资源返回就立即处理了，可能是这个原因

需要保证返回的处理顺序和请求顺序一致

**Comment by hoperyy** [comment]
@bailicangdu 烦请看下是否是上面猜测的原因，有没有解决方案

**Comment by bailicangdu** [comment]
能提供一个demo吗，我本地无法复现

**Comment by hoperyy** [comment]
@bailicangdu 比较麻烦，我尝试下。

具体到思路的话，我感觉可能是：

1. webpack 通过 script/link 标签发出请求，执行顺序肯定是和请求顺序一致的，不会有问题

  > 比如，请求顺序是 1 2 3 4 5，虽然返回是乱序的，但执行顺序肯定是 1 2 3 4 5

2. micro-app 是通过 fetch 拿到 js/css 返回值并在回调执行的，只要资源内容返回了，就立刻执行，可能会和请求的顺序不一致

  > 比如，请求顺序是 1 2 3 4 5，返回是乱序的，在 micro-app fetch 回调里的执行顺序可能是 1 3 4 2 5
