### ISSUE TITLE
子应用html标签样式隔离失效

### ISSUE THREAD

**Issue by jeane-zz** [jd-opensource/micro-app#777]
## 问题描述
> 问题的具体描述
1. 子应用中对html标签设置的height：auto。
2. 样式隔离正常打开。
3. 打包后的代码，子应用设置的html标签样式影响到了主应用，导致样式异常。

## 复现步骤
1.
4.

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。
样式引用
![image](https://user-images.githubusercontent.com/21193997/234461802-f7aa6a54-c3ef-4d82-8baf-7a2a03b67b03.png)
打包后台HTML标签的样式
![image](https://user-images.githubusercontent.com/21193997/234462115-b5050f3e-530a-4219-9816-a2786d1b03cd.png)

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。

## 环境信息
- micro-app版本：V0.8.10
- 主应用前端框架&版本：react V16.14.0
- 子应用前端框架&版本：vue V3.2.37
- 构建工具&版本：webpack V4.31.0

**Comment by bailicangdu** [comment]
因为全局只有一个html，所以子应用的html样式会对外层html有影响。
