### ISSUE TITLE
基座应用的router-view使用keep-alive时，子应用第二次渲染空白

### ISSUE THREAD

**Issue by tiancantudousi** [jd-opensource/micro-app#778]
## 问题描述
> 问题的具体描述

## 复现步骤
1.基座应用为vue2，顶层router-view外层包裹keep-alive标签时，跳转子应用第一次渲染正常，切换到基座应用其它页面，再点击跳转子应用时，页面渲染空白。
2.去掉router-view的keep-alive时，子应用第二次渲染能正常，所以这个bug是router-view的keep-alive导致的。
3.通过代码调试（基座router-view使用keep-alive时），第二次进子应用时，<micro-app @created="created">标签上 created函数中日志 'micro-app元素被创建'打印两次。使用debugger同样会断点两次，卡在created第二次打印前时，页面正常渲染，结束第二次debugger时页面空白。
4.后面使用源码调试发现connectedCallback函数执行两次导致这个问题，自己改成防抖这种形式，页面能正常渲染。

## 上传截图
> 
![image](https://user-images.githubusercontent.com/30852480/234493665-7b338085-0975-466f-a7b9-95764534c098.png)
![image](https://user-images.githubusercontent.com/30852480/234494322-07ffd047-02ad-4f3c-9dd7-f9dcd78950c8.png)

## 复现仓库
> 基座应用
https://github.com/tiancantudousi/VUE2.git
子应用
https://github.com/tiancantudousi/childVite.git

## 环境信息
- micro-app版本：0.8.10
- 主应用前端框架&版本：vue 2.7.8
- 子应用前端框架&版本：vue3
- 构建工具&版本：

**Comment by bailicangdu** [comment]
感谢反馈，这个问题在1.0版本中已经修复，既然你已经解决了这个问题，可以不用升级
