### ISSUE TITLE
虚拟路由怎么实现打开新页签功能（主应用和子应用）

### ISSUE THREAD

**Issue by Smilewangjing** [jd-opensource/micro-app#780]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by bailicangdu** [comment]
表述的不是很清楚，问的是打开的方式还是地址？

**Comment by Smilewangjing** [comment]
> 表述的不是很清楚，问的是打开的方式还是地址？

主应用和子应用，window.open这种用虚拟路由分别怎么实现

**Comment by Smilewangjing** [comment]
关闭

**Comment by keuby** [comment]
window.rawWindow.open(url, '_blank')
