### ISSUE TITLE
子应用错误监控问题

### ISSUE THREAD

**Issue by xiaozhanghui** [jd-opensource/micro-app#784]
拿到的stack信息只能定位到是基座microapp源码new Function(code)的地方，有没有办法拿到子应用运行时真正的错误stack

**Comment by raoenhui** [comment]
子应用需要用inline-source-map打包模式，才能在浏览器中进行调试查看实际位置。
https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/questions?id=_19%e3%80%81%e7%94%a8webpack%e6%89%93%e5%8c%85%e7%9a%84%e5%ad%90%e5%ba%94%e7%94%a8%ef%bc%8c%e5%a6%82%e4%bd%95%e9%80%9a%e8%bf%87source-map%e8%bf%9b%e8%a1%8c%e6%ba%90%e7%a0%81%e8%b0%83%e8%af%95%ef%bc%9f

**Comment by xiaozhanghui** [comment]
@raoenhui 你这个是开发模式下的，代码调试吧！我要的是线上发布的版本，通过监控记录浏览器报错信息，拿到错误堆栈信息，然后通过工具解析到源代码具体位置。

**Comment by raoenhui** [comment]
被打乱压缩的文件无法解析到源代码具体位置。所以子应用需要用inline-source-map打包模式
