### ISSUE TITLE
子应用Keep-alive后，切换其他应用后再回到Keep-alive的应用时，渲染异常

### ISSUE THREAD

**Issue by zyf540860996** [jd-opensource/micro-app#785]
## 问题描述
> 子应用Keep-alive后，切换其他应用后再回到Keep-alive的应用时，渲染异常

## 复现步骤
1.子应用1设置Keep-alive
2.打开子应用1中A页面后，切换到其他应用，然后再打开子应用1中B页面，实际渲染的还是子应用1中A页面，
3.子应用配置Keep-alive后，离开当前子应用后再打开，默认渲染的是子应用最后一次打开的页面，但是实际需求中，可能通过链接跳转到子应用的其他页面

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。

## 环境信息
- micro-app版本：1.0.0-beta.4
- 主应用前端框架&版本：vite2 + Vue3
- 子应用前端框架&版本：vite2 + Vue3
- 构建工具&版本：vite2

**Comment by bailicangdu** [comment]
keep-alive只是让应用隐藏和展示，再次渲染时不会根据url地址自动跳转，需要手动控制跳转

**Comment by zyf540860996** [comment]
怎么手动控制跳转了，怎么拿到实际要跳转的路径。
disableMemoryRouter:true 时，window.rawWindow.location 获得 hash 是实际要跳转的地址
disableMemoryRouter:false 时，window.rawWindow.location 获得是缓存的路由信息，怎么获取实际跳转的地址

**Comment by raoenhui** [comment]
用虚拟路由后，可以用 router.decode(path: string) 来解码获取实际跳转的地址，https://micro-zoe.com/docs/1.x/#/zh-cn/router?id=%e7%bc%96%e8%a7%a3%e7%a0%81

**Comment by hulksqj** [comment]
> keep-alive只是让应用隐藏和展示，再次渲染时不会根据url地址自动跳转，需要手动控制跳转

这样相当于跳了两次页面， 用户会看到这两次跳转，有没有好的优化方式，或者说 手动控制跳转的时机是什么时候我现在在
子应用beforeshow的时候加上了这段跳转逻辑，但是实际效果还是跳转了两次

**Comment by 1160916065aabbc** [comment]
> > keep-alive只是让应用隐藏和展示，再次渲染时不会根据url地址自动跳转，需要手动控制跳转
> 
> 这样相当于跳了两次页面， 用户会看到这两次跳转，有没有好的优化方式，或者说 手动控制跳转的时机是什么时候我现在在 子应用beforeshow的时候加上了这段跳转逻辑，但是实际效果还是跳转了两次

并没有 还是会出现这样的问题

**Comment by CreateAnything** [comment]
解决了吗兄弟我也遇到这个问题
