### ISSUE TITLE
子应用资源加载问题

### ISSUE THREAD

**Issue by xuxu-1997** [jd-opensource/micro-app#788]
子应用加载第三方js，(google map.js，如图红色框)，然后这个第三方js文件里会再去加载两个js文件(如图蓝色框)，这两个js会出现跨域错误。请问如何解决?（单独打开子应用可以加载成功，从主应用打开子应用则会加载失败）
![企业微信截图_16836865491960](https://github.com/micro-zoe/micro-app/assets/59275406/de6ef0d4-1a73-49c8-9e9e-1ccf6376ab77)

**Comment by bailicangdu** [comment]
将js文件放在基座中引入
