### ISSUE TITLE
react子应用动态fetch json文件，获取的是基座的路径

### ISSUE THREAD

**Issue by Lizhihua1988** [jd-opensource/micro-app#789]
micro app 0.81 

基座地址：localhost:3000
子应用地址：localhost:3001
react子应用动态fetch json文件，获取的是基座的路径，404

在子应用中调用以下语句
await fetch(require('../assets/config.json'));

network是：localhost:3000/config.json

麻烦帮忙是否有解决的方法

**Comment by Kryzeno** [comment]
这边也是 上线的项目突然变成了这样 原来好好的

**Comment by frankcloudy** [comment]
我们今天下午也是遇到这个问题了，看技术交流群晚上7点40左右的时候有人反馈好了。及其诡异，求解

**Comment by Kryzeno** [comment]
实测版本0.8.4 0.8.5 很怪异这个  下午开始 子应用静态资源的域名 全部变成基应用的域名去了 到了7点多又好了 这样搞谁敢用哦

**Comment by ludetao** [comment]
今天下午，突然整个应用中心的子应用全部白屏。子应用部分静态资源域名变成基应用的域名了。
然后子应用使用了（自动补全publicPath）引发了新报错
版本为0.8.5

**Comment by Melon0527** [comment]
同样的问题，下午4点出现问题，7点多自动恢复。
猜测可能是某个第三方CDN发布新版本把`window.fetch`方法重写了。

**Comment by bailicangdu** [comment]
使用绝对路径请求，相对路由会兜底到基座
