### ISSUE TITLE
子应用使用element-plus会抛出Invalid event arguments: event validation failed for event 警告

### ISSUE THREAD

**Issue by zyf540860996** [jd-opensource/micro-app#792]
![image](https://github.com/micro-zoe/micro-app/assets/10524382/72edf034-3477-4ad1-8c9b-a069bbaaabc0)

micro-app版本：v1.0.0-beta.4
主应用前端框架&版本：vue3.2.47
子应用前端框架&版本：vue3.2.47
构建工具&版本：主应用 vite4.3.4; 子应用 vite4.3.4

**Comment by summer-rain** [comment]
碰到相同的问题了，不知道有没有人解决呀

**Comment by SepVeneto** [comment]
[https://github.com/micro-zoe/micro-app/issues/756](https://github.com/micro-zoe/micro-app/issues/756)
这个问题我之前反馈过，但是官方没人回复

**Comment by Smilewangjing** [comment]
遇到相同的问题

**Comment by bailicangdu** [comment]
会抛出警告，但功能不受影响，后续会进行处理

**Comment by LIshuas** [comment]
> ![image](https://user-images.githubusercontent.com/10524382/237634029-72edf034-3477-4ad1-8c9b-a069bbaaabc0.png)
> 
> micro-app版本：v1.0.0-beta.4 主应用前端框架&版本：vue3.2.47 子应用前端框架&版本：vue3.2.47 构建工具&版本：主应用 vite4.3.4; 子应用 vite4.3.4

哥们，你子应用使用el-select组件开启远程搜索功能后会报错吗，我本地调试没问题，一上线就会报这个组件的错误。如图
![error](https://github.com/micro-zoe/micro-app/assets/50450058/544c2e37-e682-4fb5-8ad2-972e57450ce3)
