### ISSUE TITLE
主应用是vue2+webpack+element，子应用是vue3+webpack+element-plus，drawer打开时动画有问题

### ISSUE THREAD

**Issue by changEveryDay** [jd-opensource/micro-app#793]
## 问题描述
主应用是vue2+webpack+element，子应用是vue3+webpack+element-plus，drawer打开时动画有问题，正常打开前有一个打开后关闭的闪动

## 复现步骤
1.
2.

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。

主应用地址：https://github.com/changEveryDay/vueprojecto.git
子应用地址：https://github.com/changEveryDay/childrenApp.git
分别启动这两个项目，项目很简单，只有一个点击打开drawer的效果，主应用里改一下子应用的地址，即可复现

急等回复

## 环境信息
- micro-app版本：
- 主应用前端框架&版本：
- 子应用前端框架&版本：
- 构建工具&版本：

**Comment by changEveryDay** [comment]
主应用地址：https://github.com/changEveryDay/vueprojecto.git
子应用地址：https://github.com/changEveryDay/childrenApp.git
麻烦帮忙看下

**Comment by bailicangdu** [comment]
element-ui样式冲突了，给子应用设置一个样式前缀，避免冲突，参考 https://element-plus.gitee.io/zh-CN/guide/namespace.html

**Comment by changEveryDay** [comment]
了解了，多谢
