### ISSUE TITLE
环境变量__MICRO_APP_BASE_APPLICATION__为undefined

### ISSUE THREAD

**Issue by Smilewangjing** [jd-opensource/micro-app#795]
## 问题描述
> 问题的具体描述

## 复现步骤
1.启动主应用
2.
![image](https://github.com/micro-zoe/micro-app/assets/22747717/37d55cba-97b8-47a0-997d-139c2650002c)

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。
![image](https://github.com/micro-zoe/micro-app/assets/22747717/ebfae1d9-dbe7-4c9d-a3b1-60eeed954279)

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。

## 环境信息
- micro-app版本：1.0.0-beta.4
- 主应用前端框架&版本：
- 子应用前端框架&版本：
- 构建工具&版本：

**Comment by bailicangdu** [comment]
感谢反馈，下个版本会进行修复

**Comment by daughterRui** [comment]
+1，下个版本什么时间发布了

**Comment by bailicangdu** [comment]
问题已修复，升级到1.0.0-beta.5即可
