### ISSUE TITLE
为什么 createTextNode 方法的 patch 移除掉了？

### ISSUE THREAD

**Issue by keuby** [jd-opensource/micro-app#797]
https://github.com/micro-zoe/micro-app/blob/1e8bc118810afd8c44aab59e42f1378eaf514aaa/src/source/patch.ts#L583-L586

我看源码在 1.x 版本中移除了 createTextNode 的处理，是什么原因呢？

**Comment by bailicangdu** [comment]
只需要处理到element，text级别不需要处理，节省性能
