### ISSUE TITLE
容器加了iframe后，子应用注册的点击事件全都执行了两次

### ISSUE THREAD

**Issue by k-maikou** [jd-opensource/micro-app#798]
有遇到过这种问题的兄弟不，所有点击事件全都触发两次，子应用是react16.x的版本，micro-app版本：1.0.0-beta.4
接入前的项目可以正常执行
![image](https://github.com/micro-zoe/micro-app/assets/55917074/fcc23aff-8b8e-461a-94f3-d519c003daab)
接入到子应用后点击会触发两次：
![image](https://github.com/micro-zoe/micro-app/assets/55917074/ceed285e-34b3-444c-b180-a27752af41d3)

**Comment by bailicangdu** [comment]
能提供一个demo看一下吗
