### ISSUE TITLE
子应用的window的部分api会使用父应用的作用域

### ISSUE THREAD

**Issue by hyq2019** [jd-opensource/micro-app#799]
## 问题描述
在子应用上写切换url等相关的操作方法 使用到window的时候 有的情况下会使用父window的作用域的操作 没有隔离开

子应用：
1:如 window.location.reload() _**>>>>**_ 结果则会把整个父应用都给刷新
2:如 vue2 hash子应用 只要是`./# `的路由地址 
    const previewUrl = `./#/subappurl`;
    window.open(previewUrl);
_**>>>>**_ 结果则会用父应用的host去拼接子应用写的url去打开新页面

可能还有别的问题 暂时还没遇见 只是子应用写全地址能规避掉 
代码和代码仓就不贴了 外包仔的保密工作 不给贴
控制台没有看到错误/警告信息抛出 网络部分对应子应用数据配置也正常获取
## 环境信息
- micro-app版本：1.0.0beta4
- 主应用前端框架&版本：vue2 hash
- 子应用前端框架&版本：vue2 hash
- 构建工具&版本：node10.23.0 webpack 4.44.2 打包和node应该不影响

**Comment by bailicangdu** [comment]
这几个API都是全局的，包括a标签跳转、popstateEvent

**Comment by hyq2019** [comment]
收到 十分感谢
