### ISSUE TITLE
子应用页面切换时重复实例化？

### ISSUE THREAD

**Issue by qianqian05723** [jd-opensource/micro-app#80]
## 背景
> 如下图场景下，有疑问：
![c24b99981279552997ae5113c85043d](https://user-images.githubusercontent.com/17306867/131619699-a15303c1-c37e-422f-8a3e-7fd3a4842530.png)

1. 操作1路由跳转的时候，子应用创建生成了实例；
2. 操作2路由跳转时，子应用先卸载又重新生成实例？

## 
操作2路由跳转时，直接匹配路由不重新生成实例

**Comment by bailicangdu** [comment]
路径切换的时候micro-app标签被删除和重写渲染才会导致这样的问题

**Comment by qianqian05723** [comment]
> 路径切换的时候micro-app标签被删除和重写渲染才会导致这样的问题

嗯，在基座应用使用router.push进行跳转都会重新渲染页面导致这个问题，那遇到相同前缀的路由传值到子应用，在子应用中进行跳转，这样应该能解决这个问题...

**Comment by trytocatchyou** [comment]
> 路径切换的时候micro-app标签被删除和重写渲染才会导致这样的问题
当主应用使用一个router-view来动态渲染不同的微应用时，会出现这样的问题，退出该router-view后view内的micro-app组件会自动卸载，当再次进入该view时若应用名一致，基座就会报错已存在already exist
这个问题可以在进入微应用页面时使用不同的micro-app name 来规避 比如给名称后面加一个随机key
