### ISSUE TITLE
主应用加载子应用为vite+react的项目报错

### ISSUE THREAD

**Issue by Smilewangjing** [jd-opensource/micro-app#805]
## 问题描述
> 问题的具体描述

## 复现步骤
1.
2.

## 上传截图
> 
![image](https://github.com/micro-zoe/micro-app/assets/22747717/97d2d0ef-0950-42bd-b2f2-7121d60e380f)

## 复现仓库
> https://github.com/Smilewangjing/micro-app-demo.git

## 环境信息
- micro-app版本：
- 主应用前端框架&版本：
- 子应用前端框架&版本：
- 构建工具&版本：

**Comment by bobfw** [comment]
同样遇到这个问题，我把vite 改成rspack了，开发体验差了好多

**Comment by bailicangdu** [comment]
问题已修复，升级到1.0.0-beta.5即可
