### ISSUE TITLE
不同子项目要求不同node怎么处理

### ISSUE THREAD

**Issue by UmbraCi** [jd-opensource/micro-app#806]
应用中把微前端项目做成monorepo，实际安装依赖的时候，一些老旧项目因为node-sass版本兼容问题，不得不得使用NODE V14的版本，有些新的子项目又是用umijs最新版构建的又需要nodeV16版本，这种情况怎么办，node-sass升级就要升级loader，又会牵涉到webpack的大版本更新，breakchange非常多，实在不想动原有的业务代码。

**Comment by JerryWangTdcy** [comment]
> 应用中把微前端项目做成monorepo，实际安装依赖的时候，一些老旧项目因为node-sass版本兼容问题，不得不得使用NODE V14的版本，有些新的子项目又是用umijs最新版构建的又需要nodeV16版本，这种情况怎么办，node-sass升级就要升级loader，又会牵涉到webpack的大版本更新，breakchange非常多，实在不想动原有的业务代码。

如果我没记错的话，monorepo下你的项目package.json固定死了依赖版本，他不会给你安装新的吧。

**Comment by UmbraCi** [comment]
> > 应用中把微前端项目做成monorepo，实际安装依赖的时候，一些老旧项目因为node-sass版本兼容问题，不得不得使用NODE V14的版本，有些新的子项目又是用umijs最新版构建的又需要nodeV16版本，这种情况怎么办，node-sass升级就要升级loader，又会牵涉到webpack的大版本更新，breakchange非常多，实在不想动原有的业务代码。
> 
> 如果我没记错的话，monorepo下你的项目package.json固定死了依赖版本，他不会给你安装新的吧。

A/B两个子应用需求的node版本不同如何解决呢
