### ISSUE TITLE
micro-app1.0 keep-alive不生效的问题

### ISSUE THREAD

**Issue by LAMMUpro** [jd-opensource/micro-app#807]
## 问题描述
使用的micro-app是1.0版本, 父应用和子应用都是用的vite4+vue3, 禁用了虚拟路由(因为项目的路由结构比较简单)
路由格式是 /:baseRoute/:path*, 类似下面这种
/appA/a
/appA/b
/appB/a
/appB/b
不加keep-alive, 正常使用, 加上keep-alive后, 第一次访问子应用可以正常访问, 但是第二次访问, micro-app没有被渲染出来

## 复现步骤
1. 运行父应用和一个子应用, 访问父应用http://localhost:2666/
2. 打开父应用的代码, 打开src/Content.vue, 在micro-app组件加上keep-alive属性
3. 点击侧边的跳到/appA/b
4. 点击侧边的跳到/appB/a
5. 再点击侧边的跳到/appA/b (页面空白, 没有办法恢复之前的数据)
6. (去掉micro-app组件的keep-alive), 使用正常只是没有缓存功能
7. 我怀疑是micro-app里面的baseroute、name、url使用的是动态的参数, 所以我在主应用的fearture-mutiple拆分了, 切换为fearture-mutiple分支, 重新运行, 发现keep-alive还是不管用

## 上传截图
<img width="1393" alt="image" src="https://github.com/micro-zoe/micro-app/assets/38106851/9a10ef40-404e-41f5-bf02-2767a42d3e2b">

## 复现仓库
父应用master分支: https://gitee.com/LAMMUpro/microapp-vite-admin
子应用master分支: https://gitee.com/LAMMUpro/microapp-vite-app-a

## 环境信息
- micro-app版本：1.0.0-beta.4
- 主应用前端框架&版本：vite4+vue3(node16.15.0)
- 子应用前端框架&版本：vite4+vue3(node16.15.0)
- 构建工具&版本：vite4

**Comment by bailicangdu** [comment]
问题已修复，升级到1.0.0-beta.5即可

**Comment by xionglongxiang** [comment]
实测 1.0.0-beta.5 依旧存在这个问题。

**Comment by CassenChan** [comment]
实测 1.0.0-rc.4 依旧存在这个问题。
@bailicangdu @xionglongxiang @LAMMUpro @tinymins @WLyKan

**Comment by CassenChan** [comment]
> 实测 1.0.0-rc.4 依旧存在这个问题。 @bailicangdu @xionglongxiang @LAMMUpro @tinymins @WLyKan

我是"vite": "^5.1.0"和"react": "^18.2.0",
