### ISSUE TITLE
子应用的接口偶尔报跨域，

### ISSUE THREAD

**Issue by changEveryDay** [jd-opensource/micro-app#811]
子应用和主应用分开部署的，域名不同，nginx也设置了跨域，大部分时间里都没有问题，但是偶尔会有接口报跨域，请问大佬如何解决，急
![切片](https://github.com/micro-zoe/micro-app/assets/111346814/b52620b8-126c-49b3-b0ea-a38c28c1e456)

**Comment by bailicangdu** [comment]
接口请求报跨域，应该是服务端到问题

**Comment by changEveryDay** [comment]
是的，已经解决，是服务器的问题

**Comment by wangfpp** [comment]
@changEveryDay 大哥 是啥问题啊 怎么解决的   有没有遇到本地开发的时候跨域
