### ISSUE TITLE
全局只有基座的html生效，如何在子应用中，修改页面标签的favicon

### ISSUE THREAD

**Issue by sunxd-lab** [jd-opensource/micro-app#812]
## 问题描述
全局只有基座的html生效，如何在子应用中，修改页面标签的favicon

## 复现步骤
1. 希望在子应用中 通过设置 
```
document.querySelector('link[rel="icon"]').setAttribute('href', ICON_URL) 来配置页面标签的favicon，会报错找不到标签
```

## 上传截图
![image](https://github.com/micro-zoe/micro-app/assets/58944410/3ef4e6f3-7699-4dfa-aa13-eaae47ff12c2)

**Comment by bailicangdu** [comment]
icon link在子应用中被禁止，document.querySelector 只能查找子应用内部的元素，解决方式：`window.rawDocument.querySelector('link[rel="icon"]').setAttribute('href', ICON_URL)`

**Comment by sunxd-lab** [comment]
使用window.rawDocument.querySelector('link[rel="icon"]')获取到的是null，没有找到对应标签
最小复现demo如下：

基座应用： https://github.com/sunxd-lab/demo-micro-home
子应用：https://github.com/sunxd-lab/demo-micro-eam

![img_v2_c664f161-b818-4029-9371-85a2cc11bb0g](https://github.com/micro-zoe/micro-app/assets/58944410/e26c78b1-45cb-43ff-b192-020f0202eee8)

window.rawDocument.querySelector('link[rel="icon"]') 在子应用的my-page.js里

**Comment by bailicangdu** [comment]
临时解决方案：
<img width="1024" alt="image" src="https://github.com/micro-zoe/micro-app/assets/20297227/a0010ddb-2664-4d40-8025-3b79d44a638c">
```js
// my-page.js
export function MyPage() {
  const rawDocument = window.rawDocument
  window.microApp.removeDomScope()
  rawDocument.querySelector('link[rel="icon"]').setAttribute('href', 'https://ahooks.js.org/simple-logo.svg')

  return <div>eeam</div>;
}

```

**Comment by bailicangdu** [comment]
不过这确实是一个设计缺陷，后续会进行优化
