### ISSUE TITLE
路由缓存

### ISSUE THREAD

**Issue by yjs-yang** [jd-opensource/micro-app#813]
基座应用提供统一的菜单和页签。点击不同的菜单会打开不同的页签，多个个页签可能来自同一个子应用。点击页签后可以进行内容的切换。
https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/jump 必须要用这种跳转对吗？
keep-alive 也是没用的对吗？
"react-router-dom": "^6.4.3" 
[
  {
    name: "test",
    url: "http://test.com",
    path: "/test/*",
    baseroute: "/test",
    label: "test",
  },
]

**Comment by bailicangdu** [comment]
最好是通过基座下发通知控制子应用跳转。当然也可以在每次点击基座侧边栏都卸载子应用重新渲染，但这种方式效率不高

**Comment by yjs-yang** [comment]
基座下发通知控制子应用跳转 这种如果多页签的形式，keep-alive也是无效的对吗
keep-alive 只是缓存的应用状态，和路由缓存不同对吧

**Comment by bailicangdu** [comment]
keep-alive只能保存同一个子应用的当前活动页

**Comment by bailicangdu** [comment]
你说的路由缓存是指每个页面都缓存吗，那么就要每个tab都对应一个micro-app元素，设置keep-alive，且name不能相同

**Comment by 160905** [comment]
> 你说的路由缓存是指每个页面都缓存吗，那么就要每个tab都对应一个micro-app元素，设置keep-alive，且name不能相同
我们改造了子应用，通过向子应用注册的 name,在同一个站点导出不同的内容。但是多次使用 micro-app 标签 依然会加载多次资源 html 和 js，能做到相同的 url 微服务资源加载一次，还可以多次使用 micro-app 标签。
![image](https://github.com/micro-zoe/micro-app/assets/22002759/83931b3c-d880-494a-b4af-7151c8842dd7)
![image](https://github.com/micro-zoe/micro-app/assets/22002759/83c1a3f8-eeca-40bb-b027-cd44695505e5)

**Comment by raoenhui** [comment]
楼上的情况可以用下资源共享
https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/static-source?id=%e8%b5%84%e6%ba%90%e5%85%b1%e4%ba%ab
