### ISSUE TITLE
使用中的一些问题

### ISSUE THREAD

**Issue by Ttou** [jd-opensource/micro-app#814]
### 子应用调用 `window.microApp.router.push({ name: 'vue2', path: '/' })` 无法跳转，报警告：

![image](https://github.com/micro-zoe/micro-app/assets/4298437/a19ffad3-4f1f-4d4e-b17e-41414ba6890e)

### 项目启动后，vite 子应用报错：

![image](https://github.com/micro-zoe/micro-app/assets/4298437/86993d1e-d2e6-41c9-b266-6ac3bf9461f1)

### element-plus 在 vite 子应用中弹出层位置偏移

![image](https://github.com/micro-zoe/micro-app/assets/4298437/e6a7da16-77b0-41c4-bd69-a23dde8fe810)

## 复现步骤
1. `pnpm i`
2. `pnpm dev`

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。

https://gitee.com/jh_shot/microapp-template.git

## 环境信息
- micro-app版本：1.0.0-beta.5
- 主应用前端框架&版本：vue2.7.14
- 子应用前端框架&版本：vue2.7.14 & vue3.3.4
- 构建工具&版本：vite4 & vue-cli5

**Comment by Ttou** [comment]
启动报错的原因找到了，预加载的vite子应用也要设置 iframe
https://micro-zoe.com/docs/1.x/#/zh-cn/prefetch?id=vite%e5%ba%94%e7%94%a8

**Comment by Ttou** [comment]
@bailicangdu 
vite子应用内弹出层偏移的问题是由主应用的样式引起的，基于 vue-cli 的项目正常
![image](https://github.com/micro-zoe/micro-app/assets/4298437/2e5fea92-c956-4dfa-a20a-edb510a9b56f)

**Comment by bailicangdu** [comment]
iframe沙箱下才出现问题？

**Comment by Ttou** [comment]
@bailicangdu 是的，基于vue-cli 的子应用加上 iframe 属性后，也出现这个问题

**Comment by bailicangdu** [comment]
> @bailicangdu 是的，基于vue-cli 的子应用加上 iframe 属性后，也出现这个问题

好的，我们会尽快排查和修复

**Comment by Ttou** [comment]
@bailicangdu 我在子应用的 #app 上设了 `position: relative;`，去掉之后定位就正确了

**Comment by Ttou** [comment]
执行以下命令：

```sh
pnpm stage
pnpm serve
```

访问 `http://localhost:3000` 浏览器不停的打印错误:

![image](https://github.com/micro-zoe/micro-app/assets/4298437/07f2a1db-ee7d-41ea-9f5d-3b9a482fadb2)

**Comment by Ttou** [comment]
主应用迁移到 vite 后，打包后不再报错

**Comment by Ttou** [comment]
如果 vite 子应用使用了按需加载插件，如`unplugin-element-plus`，进入子应用渲染不正确，刷新后正常

![iShot_2023-06-06_09 47 52](https://github.com/micro-zoe/micro-app/assets/4298437/b72fb765-9e4e-4d2c-a89d-98138b95f007)

**Comment by Ttou** [comment]
通过将预加载的级别设为3可以缓解上一个问题；通过 baseRouter 无法跳转到子路由的指定页面：

![iShot_2023-06-09_16 45 46](https://github.com/micro-zoe/micro-app/assets/4298437/78492271-5c6d-45b5-955a-d9a1b2fa9ba7)

**Comment by Ttou** [comment]
通过将预加载的级别设为3可以缓解上一个问题；通过 baseRouter 无法跳转到子路由的指定页面
