### ISSUE TITLE
主应用 vite3-vue3,报错Expected a JavaScript module script but the server responded with a MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.

### ISSUE THREAD

**Issue by hecongyuan** [jd-opensource/micro-app#816]
## 问题描述
主应用 vite3-vue3,报错
Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.

**Comment by hecongyuan** [comment]
vue3不能用setup写组件吗，我改成defineComponent写组件就好了

**Comment by hecongyuan** [comment]
> Hello @hecongyuan. In order to facilitate location and troubleshooting, we need you to provide a realistic GitHub repository. 您好 @hecongyuan, 为了方便定位和排查问题，我们需要您提供一个重现实例，请提供一个尽可能精简的 GitHub 仓库地址。

vue3不能用setup写组件吗，我改成defineComponent写组件就好了

**Comment by hecongyuan** [comment]
> Hello @hecongyuan. In order to facilitate location and troubleshooting, we need you to provide a realistic GitHub repository. 您好 @hecongyuan, 为了方便定位和排查问题，我们需要您提供一个重现实例，请提供一个尽可能精简的 GitHub 仓库地址。

vit3+vue3不能用setup写组件吗，我改成defineComponent写组件就好了,应该就是这个导致的问题

**Comment by hecongyuan** [comment]
已解决，package中新增type:'module'

**Comment by shijiashuai123** [comment]
在react 17 中，package里面添加了type: "module" 还是会有这问题！
