### ISSUE TITLE
本仓库 demo 改了配置后报错

### ISSUE THREAD

**Issue by liuyib** [jd-opensource/micro-app#817]
## 问题描述
> 问题的具体描述

页面报错：

![image](https://github.com/micro-zoe/micro-app/assets/38221479/57096a08-216f-449b-871a-56a824521375)

## 复现步骤

1. 本仓库里的 demo，react16基座，vite2子应用。修改配置：https://github.com/micro-zoe/micro-app/blob/dev/dev/main-react16/src/pages/vite2/vite2.js#L103-L105, 把 `inline, disableSandbox` 配置启用，关闭 `iframe` 配置:

> 之所以这样改配置，是因为[文档](https://zeroing.jd.com/docs.html#/zh-cn/framework/vite?id=%e4%bd%9c%e4%b8%ba%e5%ad%90%e5%ba%94%e7%94%a8)里写的：
> ![image](https://github.com/micro-zoe/micro-app/assets/38221479/ed974f88-88d0-4144-a72d-aa7648fa1329)

<img width="700" alt="image" src="https://github.com/micro-zoe/micro-app/assets/38221479/a76dd54f-95cf-4d52-82af-3577de5903fd">

2. 访问 vite2应用 页面后，再访问任意其他页面报错

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。

## 环境信息
- micro-app版本：1.0.0-beta.5
- 主应用前端框架&版本：react 16.13.0
- 子应用前端框架&版本：vue^3.1.4
- 构建工具&版本：vite^2.6.13

**Comment by bailicangdu** [comment]
这是旧版本的写法，1.0版本参考 https://micro-zoe.com/docs/1.x/#/zh-cn/start

**Comment by liuyib** [comment]
> 这是旧版本的写法，1.0版本参考 https://micro-zoe.com/docs/1.x/#/zh-cn/start

好的感谢。提个小建议，文档默认进去应该对应最新版的，旧版的放到顶部菜单中更好些吧。

---

我发现问题出在哪了，https://zeroing.jd.com/ 这个网址的文档是旧的，首页都看不到 1.x 文档的入口：

![image](https://github.com/micro-zoe/micro-app/assets/38221479/f8c1d638-a6fe-476a-8d0d-5a19651597cd)

建议停掉不能同步更新的文档网址，或者重定向到最新的网址
