### ISSUE TITLE
子应用加载有明显的空白时间，用了预加载后主应用明显被拖慢

### ISSUE THREAD

**Issue by changEveryDay** [jd-opensource/micro-app#818]
import microApp from '@micro-zoe/micro-app'
microApp.start()
microApp.preFetch([
    { name: 'xxx', level: 1, url: 'xxx, 'default-page': 'xx' } // 加载资源并解析
], 5000)

**Comment by changEveryDay** [comment]
试了一下，加上了预加载，都是在主应用加载之前加载子应用的文件，不是在浏览器空闲时间执行的，主应用加载明显受影响

**Comment by bailicangdu** [comment]
micro-app版本是多少？

**Comment by changEveryDay** [comment]
版本是 0.8.10

**Comment by bailicangdu** [comment]
> 版本是 0.8.10

用定时器包裹一下会好一点

**Comment by JackShijt** [comment]
预加载逻辑别放入口文件里
