### ISSUE TITLE
warming: navigation failed, app does not exist or is inactive

### ISSUE THREAD

**Issue by hecongyuan** [jd-opensource/micro-app#820]
## 问题描述
> 路由跳转报错

## 代码
import microApp from '@micro-zoe/micro-app'
microApp.router.push({ name: 'appneme-vue2', path: '/index })

## 环境信息
- micro-app版本： "^1.0.0-beta.5",
- 主应用前端框架&版本：vue3-vite官方demo
- 子应用前端框架&版本：vue2 官方demo
- 构建工具&版本：vite4

**Comment by bailicangdu** [comment]
`app does not exist or is inactive` 子应用不存在，子应用渲染完成后才能跳转

**Comment by Ttou** [comment]
要跳转的子应用被过滤掉了，不知道有没有其他办法

![image](https://github.com/micro-zoe/micro-app/assets/4298437/2cbaf3d6-623b-4221-a766-d7f920db84f7)

**Comment by bailicangdu** [comment]
keep-alive应用吗

**Comment by Ttou** [comment]
设置了

**Comment by bailicangdu** [comment]
keep-alive应用隐藏后不支持跳转

**Comment by Ttou** [comment]
![iShot_2023-06-13_18 06 46](https://github.com/micro-zoe/micro-app/assets/4298437/a63c1efd-6ffc-413d-8f16-a0403a693cd2)

**Comment by Ttou** [comment]
想要在一个子应用里跳转到另一个子应用的某一页面，怎么做

**Comment by bailicangdu** [comment]
基座先跳转，再控制子应用跳转

**Comment by Ttou** [comment]
怎么判断基座已经跳转了

![image](https://github.com/micro-zoe/micro-app/assets/4298437/d5c5844c-b3b8-4129-9d07-81837972b08d)

**Comment by hsiangleev** [comment]
请问你那边解决了吗，最后是怎么判断基座已经跳转的

**Comment by yuxuan-ctrl** [comment]
> 想要在一个子应用里跳转到另一个子应用的某一页面，怎么做

目前我是这样处理的，基座应用暴露一个方法给子应用，基座应用先跳转过去对应的子应用页面(router.push('/基座应用注册的路由'))

**Comment by yuxuan-ctrl** [comment]
> > 想要在一个子应用里跳转到另一个子应用的某一页面，怎么做
> 
> 目前我是这样处理的，基座应用暴露一个方法给子应用，基座应用先跳转过去对应的子应用页面(router.push('/基座应用注册的路由'))

然后在通过setData通知子应用跳转到子应用的页面。microApp.setData(appName, { path: fullPath })，子应用就监听Data，用自己的路由进行跳转

**Comment by BennyCxb** [comment]
我是主应用跳子应用报这个错误，有兄弟们指导一下怎么解决吗？版本为：1.0.0-rc.0

**Comment by BenjaminCCG** [comment]
> > > 想要在一个子应用里跳转到另一个子应用的某一页面，怎么做
> > 
> > 
> > 目前我是这样处理的，基座应用暴露一个方法给子应用，基座应用先跳转过去对应的子应用页面(router.push('/基座应用注册的路由'))
> 
> 然后在通过setData通知子应用跳转到子应用的页面。microApp.setData(appName, { path: fullPath })，子应用就监听Data，用自己的路由进行跳转

老哥有仓库学习下吗
