### ISSUE TITLE
子应用使用wangeditor，启动正常使用，嵌入到主应用后报错

### ISSUE THREAD

**Issue by Smilewangjing** [jd-opensource/micro-app#823]
## 问题描述
> 问题的具体描述

## 复现步骤
1.
![image](https://github.com/micro-zoe/micro-app/assets/22747717/556bd567-d3a9-4c14-b754-b1bacac55c80)

2.

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。

## 复现仓库
> https://github.com/Smilewangjing/micro-app-demo.git

## 环境信息
- micro-app版本：1.0.0-beta.5
- 主应用前端框架&版本：vue3+vite
- 子应用前端框架&版本：vue3+viite
- 构建工具&版本：vite

**Comment by Smilewangjing** [comment]
这个还会解决吗

**Comment by JackShijt** [comment]
你确定一下是不是富文本编辑器有些配置文件路径出现问题了

**Comment by houliang999** [comment]
我也遇到了同样的问题，因为时vite项目，启用了iframe沙箱。0.x版本的时候是正常的

**Comment by fei-king** [comment]
同样问题，firefox下，功能基本全军覆膜

**Comment by beef-or-noodles** [comment]
同样问题，现在有其它解决办法没，或者换个editer，还是其它什么方法

**Comment by raoenhui** [comment]
关闭沙箱试试，https://micro-zoe.com/docs/1.x/#/zh-cn/configure?id=disable-sandbox

**Comment by fei-king** [comment]
该邮箱已经转发至阿里去邮
