### ISSUE TITLE
主应用和子应用都部署到 ali oss 上，无法加载子应用

### ISSUE THREAD

**Issue by liuyib** [jd-opensource/micro-app#824]
## 问题描述
> 问题的具体描述

vite 子应用，开启 iframe 沙箱后，我观察到主应用加载子应用时，micro-app 会在 dom 中插入 `<iframe>`（应该是用来做跨域请求的）：

![image](https://github.com/micro-zoe/micro-app/assets/38221479/196fb68c-116e-4bb7-990a-3953f0df711a)

其中 `<iframe>` 的 `src` 是主应用的根地址，但是直接访问 aliyun oss 的根地址会返回 403 页面：

![image](https://github.com/micro-zoe/micro-app/assets/38221479/011fa41d-479f-4a87-8396-4347156b318c)

于是 `<iframe>` 就加载失败了，导致子应用无法正常加载。

请教下如何解决呢？如果还需要其他信息，我可以再提供。另外，感谢作者开源这么好用的框架 ❤️ 。

## 复现步骤
1.
2.

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。

## 环境信息
- micro-app版本：1.0.0-beta.5
- 主应用前端框架&版本：react^17.0.1
- 子应用前端框架&版本：react^17.0.0
- 构建工具&版本：主应用 webpack^4.44.2, 子应用 vite^2.1.5

**Comment by bailicangdu** [comment]
根路径错误，在nginx中设置一下，确保直接访问基座域名不会报错

**Comment by liuyib** [comment]
~~问了公司里的运维，说这个域名其实是配的 CNAME，直接到 ali oss 的 IP，中间没有 nginx，貌似也没法配 nginx。~~

~~我想的是，micro-app 插入这个 `<iframe>` 时，`src` 是不是应该直接用 用户传的 `url` 参数？这样根路径永远不会错了，毕竟主应用也不一定是部署在域名的根路径下。~~

~~比如：~~
~~有个地址：http://example.com/~~
~~主应用部署在：http://example.com/main/ 下（甚至还可能没法配 nginx，需要这样访问：[http://example.com/main/index.html](http://example.com/main/index.html)）~~
~~这种情况下，micro-app 应该这样生成 `<iframe>` 吧：`<iframe src="http://example.com/main/" />` 而不是目前的行为（把子路径去掉了）：`<iframe src="http://example.com/" />`~~

~~@bailicangdu  我的这个想法合理吗？~~

又看了看，应该不是这个原因

**Comment by liuyib** [comment]
发现这个问题有报错：

![image](https://github.com/micro-zoe/micro-app/assets/38221479/9a8b28b5-933d-40ba-9c54-139dc15d6771)

对应 micro-app 这里的代码：

![image](https://github.com/micro-zoe/micro-app/assets/38221479/1b0e7d2e-b820-4b55-a6be-9832688631e1)

看了下 micro-app 插入的 `<iframe>` 元素，里面没有 `<base>` 元素（其他正常的有 `<base>`）：

![image](https://github.com/micro-zoe/micro-app/assets/38221479/7ea3b05c-7b63-48f0-9748-65dacbe49114)

然后我把 micro-app 源码下载到本地，加上 log，部署到线上测试环境：

<img width="1269" alt="image" src="https://github.com/micro-zoe/micro-app/assets/38221479/953af0c0-6713-4076-a0f8-b1a042da6581">

![image](https://github.com/micro-zoe/micro-app/assets/38221479/f2c6f204-a851-4bc4-a459-8533beedee30)

源码里这个 `this.microHead = microDocument.head` 被赋值了 `null`。

辛苦作者大大再看下 @bailicangdu

**Comment by bailicangdu** [comment]
这种情况没遇到过，线上环境才有问题的吗

**Comment by liuyib** [comment]
是的，目前只发现线上有这个问题，本地启动开发服务器测试，或者 build 出来测试都没复现。回头我再试试本地能不能复现吧，一旦复现了第一时间反馈在这里。

**Comment by bin115885** [comment]
我也遇到了同样的问题，大佬有解决方案吗

**Comment by bin115885** [comment]
@bailicangdu 请问您解决了吗
