### ISSUE TITLE
有一个需求，不知道合理不，url参数能不能像iframe的src属性那样，传一个具体的页面地址，不依赖路由系统就能直接打开

### ISSUE THREAD

**Issue by jiaozhiye** [jd-opensource/micro-app#825]
有一个需求，不知道合理不？
url参数能不能像iframe的src属性那样，传一个具体的页面地址，不依赖路由系统就能直接打开。

**Comment by jiaozhiye** [comment]
有些场景是，页面中有多个 <micro-app> 节点，需要加载不同的页面，还不想开启虚拟路由，因为地址栏会多出很多参数，因此想能都像iframe的src那样，直接给url参数一个具体的页面地址。

**Comment by bailicangdu** [comment]
这样刷新会导致路由状态丢失，回到初始页面

**Comment by bailicangdu** [comment]
可以做到像iframe那样，但也会存在iframe同样的问题

**Comment by jiaozhiye** [comment]
> 可以做到像iframe那样，但也会存在iframe同样的问题

![image](https://github.com/micro-zoe/micro-app/assets/22720488/3d64e558-cae4-4cab-838a-9995fa1db6ef)
比方说工作台首页，就有很多小组件，是通过咱们 micro-app 加载的，还有工作流调度的表单页面，也是这么做的，还有其他的一些场景，如果能支持类似于iframe的src这种特性，就会很方便处理这些场景。

**Comment by jiaozhiye** [comment]
> 可以做到像iframe那样，但也会存在iframe同样的问题
我感觉只要是弹窗能够实现铺满整个窗口，cookie和localStorage等能够和现在一样，其他的问题应该无所谓，本质上就是想通过现有的加载器，在不依赖路由系统的前提下，能够独立渲染具体的页面。比如 https://xxx.cn/list/arc001 对应SPA应用一个具体页面，通过微前端加载器能够直接渲染。

**Comment by ZXYforce** [comment]
> 有些场景是，页面中有多个 节点，需要加载不同的页面，还不想开启虚拟路由，因为地址栏会多出很多参数，因此想能都像iframe的src那样，直接给url参数一个具体的页面地址。

我项目也有这样的需求，应该怎么处理呢？希望官方能支持一下！

**Comment by R1ngYang** [comment]
我们也有此类需求，使用虚拟路由可以实现，但是地址栏参数真的很不方便

**Comment by zhuqiaoyue** [comment]
我们也有此类需求！

**Comment by ghost** [comment]
我们也有此类需求！

**Comment by busy-dog** [comment]
我们也有此类需求

**Comment by codeh2o** [comment]
> 这样刷新会导致路由状态丢失，回到初始页面

那也应该支持配置用哪种方式啊 现在这样子更奇怪

**Comment by raoenhui** [comment]
可以把虚拟路由关闭，用这个方式https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/route

**Comment by jiaozhiye** [comment]
> 可以把虚拟路由关闭，用这个方式https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/route

关闭虚拟路由也实现不了一个页面中多个微组件的这种需求，页面中多个micro-app容器而浏览器路由地址是一个，因此micro-app没办法加载不同的子页面。其实这个就是社区一直讨论的**微组件**的需求，希望官方能够考虑一下，需求场景确实挺多的。
