### ISSUE TITLE
vite最新版本+vue3多层嵌套报错

### ISSUE THREAD

**Issue by R1ngYang** [jd-opensource/micro-app#826]
## 问题描述
> vite最新版本+vue3多层嵌套报错

## 复现步骤
1. 根据文档完全使用vite进行错层嵌套配置，报错
2. 下载复现仓库，安装启动，访问3000端口则能复现

## 上传截图
> 现在  child1 镶嵌child2 正常
![image](https://github.com/micro-zoe/micro-app/assets/43800994/6531921d-9c49-4870-98e0-331053c09264)
main 再镶嵌child1  就会报错
<img width="1392" alt="image" src="https://github.com/micro-zoe/micro-app/assets/43800994/dee6135f-b76d-4710-a76c-5857dbebfaa1">

## 复现仓库
> [https://github.com/R1ngYang/micro-app-multiple](https://github.com/R1ngYang/micro-app-multiple)

## 环境信息
- micro-app版本： "@micro-zoe/micro-app": "1.0.0-beta.5"
- 主应用前端框架&版本："vite": "^4.3.9", "vue": "^3.2.47"
- 子应用前端框架&版本："vite": "^4.3.9", "vue": "^3.2.47"
- 构建工具&版本：pnpm 7.18.2 ,  node 18.16.0

**Comment by alexwjj** [comment]
https://github.com/micro-zoe/micro-app/issues/874   一样的问题，暂时无解
