### ISSUE TITLE
patchWindowEffect中的timeoutMap是否应该改为WeakMap?

### ISSUE THREAD

**Issue by karl-barkmann** [jd-opensource/micro-app#828]
## 背景
如题，沙箱window对所有setTimeout 做了拦截。我在项目内存泄漏排查中，发现类似element-ui、throttle-debounce这类库在使用setTimeout后没有对应的clearTimeout，在某些场景下比如用了el-dropdown、el-select 组件在el-tab内，tab反复切换时就会因为 timeoutIdMap 对setTimeout回调函数的直接引用导致内存泄漏。
```
export function patchWindowEffect (
  appName: string,
  microAppWindow: microAppWindowType,
): CommonEffectHook {
  const eventListenerMap = new Map<string, Set<MicroEventListener>>()
  const sstEventListenerMap = new Map<string, Set<MicroEventListener>>()
  const intervalIdMap = new Map<number, timeInfo>()
  const timeoutIdMap = new Map<number, timeInfo>()
  const {
    rawWindow,
    rawAddEventListener,
    rawRemoveEventListener,
    rawSetInterval,
    rawSetTimeout,
    rawClearInterval,
    rawClearTimeout,
  } = globalEnv
  microAppWindow.setTimeout = function (
    handler: TimerHandler,
    timeout?: number,
    ...args: any[]
  ): number {
    const timeoutId = rawSetTimeout.call(rawWindow, handler, timeout, ...args)
    timeoutIdMap.set(timeoutId, { handler, timeout, args })
    return timeoutId
  }
```
可以看下图
![image](https://github.com/micro-zoe/micro-app/assets/5437253/d7994067-962b-40c4-99f7-34d13c4dbb07)

## 期望的效果
把Map改为WeakMap避免组件相关内存无法释放。

**Comment by karl-barkmann** [comment]
throttle-debounce 类库对 debounce 函数的封装实现，实际上调用者根本无法 clearTimeout 到它内部的timeout，所以我也不太确定是否是microapp框架的实现问题，还是 throttle-debounce 的问题，目前我倾向于是 timeoutIdMap 的强引用所致。
如图：
![image](https://github.com/micro-zoe/micro-app/assets/5437253/ab2e7521-d305-4049-aaed-d09df3195deb)

**Comment by raoenhui** [comment]
Map 可以被遍历， WeakMap 不能被遍历，我们需要foreach

**Comment by karl-barkmann** [comment]
> Map 可以被遍历， WeakMap 不能被遍历，我们需要foreach

重点是**内存无法回收**。

**Comment by qinbinhua601** [comment]
> throttle-debounce 类库对 debounce 函数的封装实现，实际上调用者根本无法 clearTimeout 到它内部的timeout，所以我也不太确定是否是microapp框架的实现问题，还是 throttle-debounce 的问题，目前我倾向于是 timeoutIdMap 的强引用所致。 如图： ![image](https://private-user-images.githubusercontent.com/5437253/247501153-ab2e7521-d305-4049-aaed-d09df3195deb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4NDMyODgsIm5iZiI6MTcxOTg0Mjk4OCwicGF0aCI6Ii81NDM3MjUzLzI0NzUwMTE1My1hYjJlNzUyMS1kMzA1LTQwNDktYWFlZC1kMDlkZjMxOTVkZWIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDFUMTQwOTQ4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWYzNjQ2YjY0Nzc2MWRhM2IwODBjNDgxNmJkMmNkM2Q3MzZhZjE5MDdjNmYxMDU2ZjYxZjg1YzJmNzU0MTA3MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ElCiIVn_2MiGgr6H4Rh3zIPyMFgk_JHzrQNJwCJxSs0)

throttle-debounce感觉可以直接cancel就可以了。
![2024-07-01 at 22 10](https://github.com/micro-zoe/micro-app/assets/3437641/1fd9eda3-94e3-4d53-bb03-db7fea6d5a6c)
