### ISSUE TITLE
支持保留子应用中@container开头的container query相关的css

### ISSUE THREAD

**Issue by ZhengRui** [jd-opensource/micro-app#829]
## 背景
> 描述您希望改进的问题。

我的子应用中使用了tailwind css比较新的支持container query的一些tags，发现渲染后以@container开头的样式就丢失了。我看到这一段可能是保留@media开头的media query相关的样式，是不是可以也去支持@container开头的container query相关的样式？

## 期望的效果
子应用中container query相关的样式渲染后得到保留

**Comment by raoenhui** [comment]
帮忙提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。

**Comment by raoenhui** [comment]
https://github.com/micro-zoe/micro-app/pull/860 已经提了PR解决

**Comment by ZhengRui** [comment]
谢谢 这样就可以保留container query的样式了
