### ISSUE TITLE
当访问子应用A时，通过主应用页面的链接跳转子应用B时，浏览器历史记录多了一条错误的记录

### ISSUE THREAD

**Issue by zyf540860996** [jd-opensource/micro-app#833]
## 问题描述
> 问题的具体描述

## 复现步骤
1.当访问子应用A时，通过主应用页面的链接跳转子应用B时
2.浏览器历史记录多了一条错误的记录
3.然后点击浏览器返回按钮，页面并不是显示上次访问的子应用A页面了

关闭了虚拟路由，disable-memory-router:true

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。
![image](https://github.com/micro-zoe/micro-app/assets/10524382/6a14f212-4e69-4486-8df0-200a0c6a3f09)

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。

## 环境信息
- micro-app版本：1.0.0-beta.5
- 主应用前端框架&版本：vue3
- 子应用前端框架&版本：vue3
- 构建工具&版本：vite

**Comment by zyf540860996** [comment]
简单的浏览器后退，请作者测试下，关闭虚拟路由后，非常容易复现

**Comment by zyf540860996** [comment]
目前通过这样的方式解决了，但是不知道有没有更好的办法
const appName = 'sub1'
const activeApp = getActiveApps({ excludeHiddenApp: true, excludePreRender: true })
if (activeApp.includes(appName)) {
  microApp.router.push({ name: appName, path: path })
  return
}
window.history.pushState(null, null, route.path)
router.replace(path)

**Comment by zyf540860996** [comment]
子应用激活后，如果子应用内部路由首次跳转时，路由带有query参数时，跳转后再浏览器返回，路由会错乱。

操作步骤
1、打开主应用
2、在主应用中打开子应用A的某个页面，假如是pageA页面，地址栏:http://localhost/sub-a/pageA
3、子应用A的pageA页面中，通过router-link标签跳转到 /pageB?a=1 ，这里务必带query参数
4、通过浏览器返回按钮返回到 pageA 页面，路由出错显示为 http://localhost/sub-a/sub-a/pageA

不知道什么原因，造成了多加一层 /sub-a，如果跳转不带query参数，则没有这问题

主应用和子应用都是Vue3，路由都是histroy模式，关闭了虚拟路由配置

希望官方给下解决方案！

**Comment by minbaoer111** [comment]
请问你的应用是vue-router4吗？这个问题可以参考下这里。https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/framework/vue?id=_2%e3%80%81%e5%bd%93%e5%9f%ba%e5%ba%a7%e5%92%8c%e5%ad%90%e5%ba%94%e7%94%a8%e9%83%bd%e6%98%afvue-router4%ef%bc%8c%e7%82%b9%e5%87%bb%e6%b5%8f%e8%a7%88%e5%99%a8%e8%bf%94%e5%9b%9e%e6%8c%89%e9%92%ae%e9%a1%b5%e9%9d%a2%e4%b8%a2%e5%a4%b1
