### ISSUE TITLE
A域名跟B域名同时引入某个微应用，后访问的域名加载微应用的资源时，提示跨域

### ISSUE THREAD

**Issue by pengmaoxing** [jd-opensource/micro-app#835]
## 问题描述
> 问题的具体描述

## 复现步骤
1.有2个不同的域名同时引入了相同的微应用
2.先访问A域名，能正常访问，再访问B域名，由于浏览器缓存了A应用的微应用资源，导致访问B域名的时候，直接读取本地的缓存数据，但是由于A跟B的域名不一致，B应用就会提示加载这些资源时，报如下错误

## 上传截图

![1687917959926](https://github.com/micro-zoe/micro-app/assets/26033956/e8572f9f-6528-4f04-8741-73181d2528a9)

## 复现仓库
> 暂无

## 环境信息
- micro-app版本：0.8.11
- 主应用前端框架&版本：VUE 3.2.45
- 子应用前端框架&版本：VUE 3.2.45
- 构建工具&版本：webpack

**Comment by raoenhui** [comment]
子应用一定要支持跨域，配置可参考 https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/questions?id=_2%e3%80%81%e5%ad%90%e5%ba%94%e7%94%a8%e4%b8%80%e5%ae%9a%e8%a6%81%e6%94%af%e6%8c%81%e8%b7%a8%e5%9f%9f%e5%90%97%ef%bc%9f
