### ISSUE TITLE
子应用中element-plus下拉选择框样式会错乱，单独访问子应用是正常的，主应用中访问就会出现错乱

### ISSUE THREAD

**Issue by LIshuas** [jd-opensource/micro-app#837]
## 问题描述
> 子应用单独访问下拉选择框样式正常，主应用访问就会出现样式不一致的问题

## 上传截图
> 
![1688000126044](https://github.com/micro-zoe/micro-app/assets/50450058/f3d8e094-e3f4-407a-9d50-61de88d3efed)

## 环境信息
- micro-app版本：1.0.0-beta.4
- 主应用前端框架&版本：vue  2.6.10
- 子应用前端框架&版本：vue  3.3.1
- 构建工具&版本：vite4.3.5

**Comment by raoenhui** [comment]
切到iframe沙箱试试，https://micro-zoe.com/docs/1.x/#/zh-cn/framework/vite?id=%e4%bd%9c%e4%b8%ba%e5%ad%90%e5%ba%94%e7%94%a8

**Comment by HE77XTL** [comment]
解决了吗， 今天简单试了下， 发现同样的问题

**Comment by LIshuas** [comment]
> 解决了吗， 今天简单试了下， 发现同样的问题
解决了，最终使用el-plus自带的命名空间解决样式问题

**Comment by Jennylx** [comment]
@请问下有遇到主应用的样式被子应用污染的问题吗？是怎么解决的？
@LIshuas

**Comment by LIshuas** [comment]
> @请问下有遇到主应用的样式被子应用污染的问题吗？是怎么解决的？ @LIshuas

没遇到过，有相关的截图提供看看嘛

**Comment by Jennylx** [comment]
![image](https://github.com/micro-zoe/micro-app/assets/35032877/7db4fa92-ff5a-449c-b124-bf781821207f)
大概是这样的。我加了 iframe和disable-scopecss。
