### ISSUE TITLE
接入microapp后网页的内存占用平均增加了35%，基本是microapp在全局注入的对象占用的

### ISSUE THREAD

**Issue by JackShijt** [jd-opensource/micro-app#839]
怎么能优化一下内存占用情况？

**Comment by OldDream** [comment]
还有一个现象，微前端项目卸载后，内存占用未释放👻

**Comment by raoenhui** [comment]
> 

子应用被卸载时会接受到一个名为unmount的事件，开发者可以在此进行卸载相关操作。
https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/life-cycles?id=%e5%ad%90%e5%ba%94%e7%94%a8%e5%8d%b8%e8%bd%bd

**Comment by OldDream** [comment]
> > 
> 
> 子应用被卸载时会接受到一个名为unmount的事件，开发者可以在此进行卸载相关操作。 https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/life-cycles?id=%e5%ad%90%e5%ba%94%e7%94%a8%e5%8d%b8%e8%bd%bd


在框架层面，这部分是否有优化空间？这部分并没随着子应用卸载而回收。似乎有着某种引用。
![image](https://github.com/micro-zoe/micro-app/assets/18358438/f4fc7c8f-edb0-4e4b-a4ad-0a3357db7bdf)

**Comment by raoenhui** [comment]
这个可以加下https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/configure?id=destroy
