### ISSUE TITLE
做一个大型企业系统(micro-app)，子应用为vite-vue,host(域名、ip..)不确定,需要相对路径,替换全url方式可能不实用

### ISSUE THREAD

**Issue by cheng990629** [jd-opensource/micro-app#84]
## 问题描述
> 问题的具体描述
做一个大型企业系统(micro-app)，子应用为vite-vue,host(域名、ip..)不确定,需要相对路径,替换全url方式可能不实用
## 复现步骤
1. 文档的方式，baseUrl必须http://{hostname}/{path}..
2. 多家客户，大型企业系统，这个方式可能不适用

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。
![image](https://user-images.githubusercontent.com/40415260/131643619-ddf4f013-76a6-4298-8b1e-171eea965179.png)

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。

## 环境信息
- micro-app版本：
- 基座应用的前端框架和版本：
- 子应用的前端框架和版本：
- 构建工具&版本：

**Comment by bailicangdu** [comment]
确实不好搞，只能用插件系统改js吧

**Comment by JACK-YUNS** [comment]
> 确实不好搞，只能用插件系统改js吧

能说下具体的想法吗
