### ISSUE TITLE
升级1.0.0后，生产环境动态路由的子应用vue没有挂载到body上，页面空白，js逻辑还执行了

### ISSUE THREAD

**Issue by JackShijt** [jd-opensource/micro-app#841]
## 问题描述
> 升级1.0.0后，生产环境动态路由的子应用vue没有挂载到body上，页面空白，子应用的js逻辑还执行了，控制台有打印，network有接口调用，就是页面空白，降回0.8又恢复正常

## 复现步骤
1.按文档升级1.0.0
2.子应用路由是通过基座传来的数据动态生成的

## 上传截图
> 
![image](https://github.com/micro-zoe/micro-app/assets/56808243/7195d853-087b-4802-a4fa-38f86ad4bea0)
<img width="489" alt="image" src="https://github.com/micro-zoe/micro-app/assets/56808243/cf00525f-5814-4bef-826a-3648872b3646">
这个div竟然都没有了，在开发环境就没问题

## 复现仓库
> 

## 环境信息
- micro-app版本：1.0.0-beta.5
- 主应用前端框架&版本：vue2.6.14
- 子应用前端框架&版本：2.6.14
- 构建工具&版本：webpack@5.75.0

**Comment by shanyu1988** [comment]
我用的也是1.0.0-beta.5,在生产环境下发生了同样的问题，页面空白 <div  id="app"></div> 标签丢失，无法渲染。
经测试将动态路由相关的代码去掉后是可以正常渲染，这里的动态路由指的是vue-router动态添加route 路径。
但是在开发环境下没有此问题，页面正常显示。
因这种情况只会发生在生产环境，并且需要动态路由相关的业务代码，所以无法将具体情况复现，我是直接使用的1.0.0-beta.5版本，并没有使用0.8版本，所以无法确定是否是升级导致的问题。
现在的问题是没有报错，无法定位问题，只能自己排查。
想要看看大家是否有类似的问题，最后如何解决的。

**Comment by shanyu1988** [comment]
> 我用的也是1.0.0-beta.5,在生产环境下发生了同样的问题，页面空白
> 
> 标签丢失，无法渲染。
> 经测试将动态路由相关的代码去掉后是可以正常渲染，这里的动态路由指的是vue-router动态添加route 路径。
> 但是在开发环境下没有此问题，页面正常显示。
> 因这种情况只会发生在生产环境，并且需要动态路由相关的业务代码，所以无法将具体情况复现，我是直接使用的1.0.0-beta.5版本，并没有使用0.8版本，所以无法确定是否是升级导致的问题。
> 现在的问题是没有报错，无法定位问题，只能自己排查。
> 想要看看大家是否有类似的问题，最后如何解决的。

经测试降级到 0.8.11 恢复正常，感觉还是因为vue-router导致的页面无法正常跳转，不知道感觉对不对。

**Comment by JackShijt** [comment]
> 

确实是动态路由的问题，所有静态注册的路由都是好用的，但是我的项目涉及到权限必须用动态路由，本来还想用vite弄子应用，现在搞不了了

**Comment by minbaoer111** [comment]
可以提供一个精简版的demo方便复现和排查问题吗？建议严格按照https://micro-zoe.com/docs/1.x/#/zh-cn/framework/vue里的步骤试试。

**Comment by T0205** [comment]
我也是这种情况, 并且子应用无法使用document.querySelector , 使用就报错
