### ISSUE TITLE
一个微服务地址根据使用标签时的 name 导出不同的内容

### ISSUE THREAD

**Issue by 160905** [jd-opensource/micro-app#842]
## 背景
> 描述您希望改进的问题。
目前有一个需求就是根据使用微服务的标签 name 属性，在同一个 url 中 render 不同的内容。现在能做到，但是同一个 url 的微服务在使用时对资源的加载还是叠加的，所以期望能做到 相同的 url 不同的 name，在使用时只 load 一次 source。

## 期望的效果
``` javascript
<Divider>omni-layout-app</Divider>
<micro-app name='layout-app' url='http://localhost:8003' />

<Divider>Siderbar</Divider>
<micro-app name='siderbar' url='http://localhost:8003' data={{ component: "siderbar" }} />

<Divider>header</Divider>
<micro-app name='omni-header' url='http://localhost:8003' data={{ component: "omni-header" }} />
```
![image](https://github.com/micro-zoe/micro-app/assets/22002759/3210d593-b176-4dac-8bf3-742f20cb353f)

**期望 network 中的资源请求是一次**

**Comment by JackShijt** [comment]
不同的name本来指的就是不同的包，肯定要都加载

**Comment by 160905** [comment]
> 不同的name本来指的就是不同的包，肯定要都加载

但是都是相同的 url ，不可以减少资源请求么

**Comment by raoenhui** [comment]
预加载，https://micro-zoe.com/docs/1.x/#/zh-cn/prefetch
