### ISSUE TITLE
Angular 16 workspaces sub-apps can be opened independently, but cannot get when embedded

### ISSUE THREAD

**Issue by Alfxjx** [jd-opensource/micro-app#845]
reproduction: https://github.com/Alfxjx/webcomponent-demo-app
need help

Angular 16 workspaces 子应用可以独立打开，但是嵌入时显示 cannot get 
可以帮忙看看是什么问题吗

**Comment by raoenhui** [comment]
If applicable, add screenshots to help explain your problem.What is the console error message？
