### ISSUE TITLE
两个子应用快速切换，偶尔会出现加载页面的错乱

### ISSUE THREAD

**Issue by jiaozhiye** [jd-opensource/micro-app#847]
## 问题描述
1. 主应用下挂载了两个子应用，使用两个 micro-app 容器渲染，页面展示是通过控制 micro-app 标签的 display 属性完成的。
2. 快速点击两个子应用，或者快速来回切换着点击，会出现加载子应用页面错乱的情况，比如两个子应用加载的页面一样。
3. 使用的是 beta.4 版本，主子应用都是 react17 技术栈。
4. 感觉是在 *快速* 切换时，前一个页面资源没加载完，这时候加载下一个页面资源导致的。

## 上传截图
![image](https://github.com/micro-zoe/micro-app/assets/22720488/63ea674e-edcd-4a11-835c-3cbe0aaa2c44)

## 环境信息
- micro-app版本：1.0.0-beta.4，1.0.0-beta.5
- 主应用前端框架&版本：react17
- 子应用前端框架&版本：react17
- 构建工具&版本：webpack5.88.0

**Comment by CrystalAngelLee** [comment]
尝试一下 umd 模式呢 https://zeroing.jd.com/docs.html#/zh-cn/advanced?id=_2%e3%80%81%e6%80%a7%e8%83%bdamp%e5%86%85%e5%ad%98%e4%bc%98%e5%8c%96

**Comment by jiaozhiye** [comment]
> 尝试一下 umd 模式呢 https://zeroing.jd.com/docs.html#/zh-cn/advanced?id=_2%e3%80%81%e6%80%a7%e8%83%bdamp%e5%86%85%e5%ad%98%e4%bc%98%e5%8c%96

现在用的就是umd格式，问题就出现在快速切换，上一个页面资源没加载完的时候

**Comment by CrystalAngelLee** [comment]
辛苦提交一个精简版的复现仓库，我们会尽快排查和修复

**Comment by jiaozhiye** [comment]
> 辛苦提交一个精简版的复现仓库，我们会尽快排查和修复

https://github.com/micro-zoe/micro-app/issues/825
这需求咱们官方能否支持一下呢？看好多团队也有这个需求，感谢！
