### ISSUE TITLE
预加载失败及其相应处理

### ISSUE THREAD

**Issue by heD0ng** [jd-opensource/micro-app#848]
## 问题描述
> 问题的具体描述
基座需要接入子应用预加载功能，但是官网文档中未曾提到预加载失败及其相应处理的方案。目前，需要调研几个问题：
1、基座如果预加载子应用失败，是否会影响后续子应用的加载与渲染；
2、如果预加载失败会影响子应用的加载与渲染，如何确保子应用可以正常访问；

## 环境信息
- micro-app版本：0.8.7
- 主应用前端框架&版本：vue: 2.6.14
- 子应用前端框架&版本：vue: 2.6.14
- 构建工具&版本：webpack: 4.X

**Comment by JackShijt** [comment]
您好，这个问题有解决吗？
