### ISSUE TITLE
主应用前进后退，需要回退 2 次才能正确加载子应用的页面

### ISSUE THREAD

**Issue by niefz** [jd-opensource/micro-app#849]
## Describe the bug
主应用使用浏览器的前进后退功能时，需要点击2次才能正确加载子应用的页面

## Reproduce repository
 主应用：https://github.com/niefz/base-app
 子应用：https://github.com/niefz/sub-app

## Environment
- node version: 18.16.1
- micro-app version: 1.0.0-beta.5
- framework of base app & version: vue~3.3.4 + pinia~2.1.4 + pinia-plugin-persistedstate~3.1.0
- framework of sub app & version: vue~3.3.4 + pinia~2.1.4 + pinia-plugin-persistedstate~3.1.0
- Build tools & version: base app - vite~4.3.9、sub app - webpack~5.87.0

**Comment by CrystalAngelLee** [comment]
仓库权限辛苦开放一下

**Comment by niefz** [comment]
> 仓库权限辛苦开放一下

已私聊

**Comment by JackShijt** [comment]
我也遇到了，怎么解决呢？

**Comment by niefz** [comment]
> 我也遇到了，怎么解决呢？

官方还没给方案呢

**Comment by CrystalAngelLee** [comment]
**问题原因**

路由回退的时候，多进行了一次路由跳转（跳转到了当前页面），导致出现了需要回退两次的问题

关键问题点

```js
function handleMicroData(router) {
  // 是否是微前端环境
  if (window.MICRO_APP_ENVIRONMENT) {
    // 监听基座下发的数据变化
    addDataListener((data) => {
      // 当基座下发 path 时进行跳转
      if (data.path && data.path !== router.currentRoute.value.path) {
        router.push(data.path);
      }
    });
  }
}
```

**问题处理建议**
- **方案一**
修改问题处（即子应用 main.js）路由切换，查询合适时机改为 `router.replace`

- **方案二**
不在主应用手动 router.push 处理，修改主应用菜单路由处使用，改为在子应用监听事件并做重定向操作，参考：https://zeroing.jd.com/docs.html#/zh-cn/data

**Comment by CrystalAngelLee** [comment]
问题原因：

主应用在进行了路由跳转之后，子应用接收到父应用发送的data数据：路由改变，然后子应用进行路由重定向，当前windows路由本身已经跳转了一次，子应用接收到消息后，类似重新执行了一次 window.history.push() 导致当前路由存储了两次，所以在回退/前进的时候需要操作两次。

问题处理：

在以最小力度兼容的前提下，将主应用挂载子应用处 name 绑定为各自路由，相当于给每个路由增加一个微应用，这样的话使用框架本身路由定向完成页面加载。

或者选择在子应用响应路由切换的时候做好判断，什么时候用replace 什么时候用push

附：
当前这种处理方式会增加资源消耗，毕竟会多加载子应用资源。否则主应用处留一处进入子应用入口，其他事情交给子应用自行处理即可。

**Comment by minbaoer111** [comment]
请问你的应用是vue-router4吗？这个问题可以参考下这里。https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/framework/vue?id=_2%e3%80%81%e5%bd%93%e5%9f%ba%e5%ba%a7%e5%92%8c%e5%ad%90%e5%ba%94%e7%94%a8%e9%83%bd%e6%98%afvue-router4%ef%bc%8c%e7%82%b9%e5%87%bb%e6%b5%8f%e8%a7%88%e5%99%a8%e8%bf%94%e5%9b%9e%e6%8c%89%e9%92%ae%e9%a1%b5%e9%9d%a2%e4%b8%a2%e5%a4%b1
