### ISSUE TITLE
子应用富文本编辑器，内容会在子应用micro-body添加一份标签

### ISSUE THREAD

**Issue by mursumomo** [jd-opensource/micro-app#85]
![image](https://user-images.githubusercontent.com/43238460/131956306-f4e44494-020d-4ee1-8560-005c155bf58d.png)
![image](https://user-images.githubusercontent.com/43238460/131956371-6f8850c0-db64-4df9-a4bc-78256b686def.png)

富文本的内容，在micor-body内对出来了一份。
这个怎么解决

**Comment by mursumomo** [comment]
多出来的标签，切换同一个子应用其他路由，也不会消除

**Comment by bailicangdu** [comment]
可以提供一个复现的仓库吗

**Comment by mursumomo** [comment]
git@github.com:ice-musru/micro-editor-bug.git

这个仓库，我用的富文本编辑器是tinymac

**Comment by bailicangdu** [comment]
> [git@github.com](mailto:git@github.com):ice-musru/micro-editor-bug.git
> 
> 这个仓库，我用的富文本编辑器是tinymac

好的，我看一下

**Comment by bailicangdu** [comment]
@ice-musru 已经找到问题并进行修复，下周发版会带上，谢谢指出

**Comment by mursumomo** [comment]
感谢大佬！期待！

**Comment by bailicangdu** [comment]
问题已修复，最新版本v0.3.0：https://github.com/micro-zoe/micro-app/releases/tag/v0.3.0 @ice-musru
