### ISSUE TITLE
改变基座路由，子应用不生效，在线等...

### ISSUE THREAD

**Issue by guangmang** [jd-opensource/micro-app#850]
## 问题描述
目前在路由http://localhost:8000/app1#/test2，假设子应用的默认路由是test1。基座路由是通过React Router实现。这时候
通过useNavigate导航到http://localhost:8000/app1#/test1，地址栏会变，但是页面不会跳转。

请问如果实现这个功能？

## 环境信息
- micro-app版本：0.81
- 主应用前端框架&版本：React18
- 子应用前端框架&版本：React18
- 构建工具&版本：Webpack5

**Comment by niefz** [comment]
需要通知子应用跳转，参考 https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/jump

**Comment by guangmang** [comment]
> 需要通知子应用跳转，参考 https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/jump

**Comment by guangmang** [comment]
> 需要通知子应用跳转，参考 https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/jump

太麻烦了。我现在是多层嵌套。baseroute 是配置子应用的默认页面吗？
