### ISSUE TITLE
基座嵌套子应用A和B，子应用A有两个菜单，分别导航到B的/test1和/test2路由

### ISSUE THREAD

**Issue by guangmang** [jd-opensource/micro-app#852]
## 问题描述
基座嵌套子应用A和B，子应用A有两个菜单，打开的时候B的/test1和/test2路由
A的index.tsx初始化代码如下
function mount() {
	if (window.__MICRO_APP_ENVIRONMENT__) {
		const data= window.microApp.getData();
		console.warn('data', data);
	}
	const root = document.getElementById('root');
	if (root) {
		createRoot(root).render(
			<HashRouter>
				<Routes />
			</HashRouter>
		);
		microApp.start({
			tagName: 'micro-app-xxx',
		});
	}
}

micro-app是在index.tsx中初始化的，不能使用useNavigate，
请问如何实现点击A的菜单导航到B的/test1。

## 环境信息
- micro-app版本：0.81
- 主应用前端框架&版本：react18
- 子应用前端框架&版本：react18
- 构建工具&版本：webpack5

**Comment by CrystalAngelLee** [comment]
参考：https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/jump

**Comment by Kingshaohui** [comment]
请问您在卸载react18版本子应用的时候会报一个错误吗？
<img width="586" alt="image" src="https://github.com/micro-zoe/micro-app/assets/45385359/8f7d0e2d-9663-48f1-9cb3-1824706b5e43">
