### ISSUE TITLE
线上环境访问子应用会报el-select组件的相关错误导致页面显示出bug

### ISSUE THREAD

**Issue by LIshuas** [jd-opensource/micro-app#853]
![图1](https://github.com/micro-zoe/micro-app/assets/50450058/38c6ed67-eb48-4934-8829-42495d4decef)
图一中el-select组件开启远程搜索后就会报错，开发环境正常，上线就是这个错，不知道是哪里的问题。
![图2](https://github.com/micro-zoe/micro-app/assets/50450058/77316176-ec43-4225-862d-c6c5d20a0b88)

**Comment by CrystalAngelLee** [comment]
参考：https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/sandbox?id=_2%e3%80%81%e5%ad%90%e5%ba%94%e7%94%a8%e6%8a%9b%e5%87%ba%e9%94%99%e8%af%af%e4%bf%a1%e6%81%af%ef%bc%9axxx-%e6%9c%aa%e5%ae%9a%e4%b9%89

**Comment by LIshuas** [comment]
> 参考：https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/sandbox?id=_2%e3%80%81%e5%ad%90%e5%ba%94%e7%94%a8%e6%8a%9b%e5%87%ba%e9%94%99%e8%af%af%e4%bf%a1%e6%81%af%ef%bc%9axxx-%e6%9c%aa%e5%ae%9a%e4%b9%89

这应该不是js沙箱的问题吧，vite应用启用iframe沙箱后开启js沙箱会报错，micro-app stop rendering TypeError: Cannot read properties of null (reading 'sandboxReady')
