### ISSUE TITLE
部分antd样式没被隔离，也就是没加上前缀

### ISSUE THREAD

**Issue by Dreamvsforward** [jd-opensource/micro-app#854]
## 问题描述
> 问题的具体描述

## 复现步骤
1.
2.

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。
![image](https://github.com/micro-zoe/micro-app/assets/18736580/e624c752-a71b-4a02-906a-e754fd3f771d)

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。

## 环境信息
- micro-app版本：1.0.0-beta.5
- 主应用前端框架&版本：vue
- 子应用前端框架&版本：umi"antd": "^5.4.0",  "@umijs/max": "^4.0.72",
- 构建工具&版本：

**Comment by raoenhui** [comment]
这块antd有什么特殊的吗，是哪个antd组件？

**Comment by Dreamvsforward** [comment]
> 这块antd有什么特殊的吗，是哪个antd组件？

没特殊，antd": "^5.4.0"

**Comment by raoenhui** [comment]
:where这种伪类建议子应用自己加css权重，覆盖父应用样式

**Comment by powerfulyang** [comment]
把 umijs 的 antd 插件去掉，就不会引入 reset.css 了。算是一个解决办法吧

**Comment by MorningK** [comment]
> :where这种伪类建议子应用自己加css权重，覆盖父应用样式

感觉可能是因为现有的样式隔离没有处理css-in-js的情况，只处理了打包引入css，比如reset.css，这样在开启了样式隔离的情况下，反而导致了reset的样式的优先级高于了:where的实际样式？

**Comment by raoenhui** [comment]
是的。帮忙可以提供一个精简的代码仓库，然后上传到自己的 github。我后面看看把这块兼容下

**Comment by favorite58** [comment]
这个问题现在的版本有解决吗？我升级到了最新版也会出现reset.scss样式权重高于element plus样式的问题
