### ISSUE TITLE
从子应用跳转到其他子应用的时候microApp.setData 传递的数据，第一次监听不到

### ISSUE THREAD

**Issue by holdwl2016** [jd-opensource/micro-app#855]
## 背景
> 描述您希望改进的问题。
目前在主应用中microApp.setData 只能在同一个子应用中使用，比如切换路由时，主应用传递 path 在子应用中进行子应用页面跳转
比如： 左侧动态菜单在主应用中使用，点击到 app1 子应用页面1，使用 microApp.setData 可以切换到当前子应用的其他路由(window.microApp.addDataListener 可以接收到数据)，但是切换到其他子应用app2 的路由的时候，window.microApp.addDataListener 第一次监听不到数据，导致跳转的子应用页面路由不是预期的。

代码如下
`
// 点击主应用左侧菜单路由跳转
// data格式：{ id: '1-2', path: '/home', name: 'app1 home page', app: 'app1', fullPath: '/app1#/home' }
const handle = (data: MenuItem) => {
  router.push(data.fullPath!) // 跳转主应用的路由
  activeIndex.value = data.id
  if(data.app && ['app1', 'app2'].includes(data.app)) {
    microApp.setData(data.app, { path: data.path }) // 跳转子应用的路由
  }
  currentRoute.value = data
}
`

子应用
window.microApp.addDataListener((data: any) => {
  if (data.path) {
    router.push(data.path)
  }
})

**Comment by holdwl2016** [comment]
上面第一次代码看不清
![image](https://github.com/micro-zoe/micro-app/assets/24886797/5054d677-4e5f-426b-9f98-8a88166dd197)

**Comment by holdwl2016** [comment]
环境是 "@micro-zoe/micro-app": "1.0.0-beta.5" 和 vite最新版

**Comment by niefz** [comment]
addDataListener 第二个参数设置为 true 试试

**Comment by holdwl2016** [comment]
好奇怪我刚加了第二个这个参数，结果连路由都不能切换了，现在不知道怎么就可以了。谢大佬
