### ISSUE TITLE
关于子应用中使用`frameElement`带来的问题

### ISSUE THREAD

**Issue by Saber-Kurama** [jd-opensource/micro-app#856]
## 问题描述
> 问题的具体描述
npm 包中 `compute-scroll-into-view` 有使用 `el.ownerDocument.defaultView.frameElement` 这样的代码

在子应用中 `el.ownerDocument.defaultView.frameElement` 会得到 `iframe` Element ，应该为`rawWindow`的`frameElement` 

## 复现步骤
1.
2.

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。

## 环境信息
- micro-app版本：1.0.0-beta.5
- 主应用前端框架&版本：vue3
- 子应用前端框架&版本：vue3
- 构建工具&版本：vite4

**Comment by raoenhui** [comment]
目前有3种方式在子应用中获取外部真实window，试试这几种

1、new Function("return window")() 或 Function("return window")()
2、(0, eval)('window')
3、window.rawWindow

**Comment by Saber-Kurama** [comment]
可能是我描述的不清楚，子应用中如果使用 `window. frameElement` 会得到 `iframe`的Element，但其实应该是真实`window`的`frameElement`。所以我认为应该这个属性应该代理到外部的`window`

**Comment by bailicangdu** [comment]
子应用确实被嵌入了iframe中运行，返回iframe理论上没有问题。
<img width="777" alt="image" src="https://github.com/micro-zoe/micro-app/assets/20297227/d3a4ca2c-f177-4f17-8c14-be22abc268ef">
