### ISSUE TITLE
快速切换两个用例，在关闭虚拟路由的情况下，浏览器地址栏偶发出现虚拟路由参数

### ISSUE THREAD

**Issue by jiaozhiye** [jd-opensource/micro-app#858]
## 问题描述
快速切换两个用例，在关闭虚拟路由的情况下，浏览器地址栏偶发出现虚拟路由参数

## 上传截图
![image](https://github.com/micro-zoe/micro-app/assets/22720488/53c72a1f-f837-480d-8bd9-ca6b1689b080)

## 环境信息
- micro-app版本：1.0.0-beta.4
- 主应用前端框架&版本：react17
- 子应用前端框架&版本：react17
- 构建工具&版本：webpack5.88.0

**Comment by jiaozhiye** [comment]
上述问题的复现仓库地址：https://github.com/jiaozhiye/micro-app-repo.git

![image](https://github.com/micro-zoe/micro-app/assets/22720488/d5ed3cf7-e3e7-4e5f-a81f-0a56527e4d1d)
还有一个问题，在快速切换用例时，没能加载上页面内容。

总结：
1. 快速切换两个用例，在关闭虚拟路由的情况下，浏览器地址栏偶发出现虚拟路由参数。
2. 快速切换两个用例，偶发没能加载上页面内容。

**Comment by raoenhui** [comment]
关闭虚拟路由方法为 disable-memory-router ，用这个试试，详情可看https://micro-zoe.com/docs/1.x/#/zh-cn/configure?id=disable-memory-router

**Comment by jiaozhiye** [comment]
> 关闭虚拟路由方法为 disable-memory-router ，用这个试试，详情可看https://micro-zoe.com/docs/1.x/#/zh-cn/configure?id=disable-memory-router

这个已经设置了，正常操作没问题，出问题是在快速切换时。

**Comment by raoenhui** [comment]
这里的方法试试，https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/jump

**Comment by jiaozhiye** [comment]
> 这里的方法试试，https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/jump

文档中这些都试过了，上边提供了最小复现demo，这个问题挺棘手的，麻烦官方能够看一下。奇怪的是正常点击切换用例没问题，就是快速的来回点击切换，会偶发出现上述两个问题。

**Comment by minbaoer111** [comment]
我这里下载了你的demo看了下，由于我这边没有复现，但根据微前端源码，你上述路由中出现的虚拟路由偶现肯定是走进了虚拟路由函数代码里，建议你确保是否关闭所有子应用的虚拟路由功能，因为快速来回切换有可能导致加载时并没有走到识别关闭虚拟路由的代码，偶现出该类似的bug，或者建议你降级到微前端0.8版本。

**Comment by jiaozhiye** [comment]
> 我这里下载了你的demo看了下，由于我这边没有复现，但根据微前端源码，你上述路由中出现的虚拟路由偶现肯定是走进了虚拟路由函数代码里，建议你确保是否关闭所有子应用的虚拟路由功能，因为快速来回切换有可能导致加载时并没有走到识别关闭虚拟路由的代码，偶现出该类似的bug，或者建议你降级到微前端0.8版本。

这个可以在下一个版本修复一下吗？我们的项目肯定想持续使用咱们的新版本，不能一直停留在0.8的版本，要不以后新的特性或问题的修复，我们都无法升级到新版。

**Comment by tjyuanpeng** [comment]
同样的问题，偶现设置disable-memory-router后，地址栏出现虚拟路由queryString

**Comment by bailicangdu** [comment]
根据案例没有复现。但是在开发模式下，开启热更新，有几率出现所述问题，生产模式下表现正常。

**Comment by tjyuanpeng** [comment]
是的，热更新下会出现
