### ISSUE TITLE
在使用webgl为子应用时，为基座节点绑定了事件

### ISSUE THREAD

**Issue by xwj-r** [jd-opensource/micro-app#859]
## 问题描述
> 问题的具体描述

## 复现步骤
1.
2.

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。
![image](https://github.com/micro-zoe/micro-app/assets/57882107/2cba5e7c-827d-442c-a331-f5885bab5c4b)

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。
https://github.com/xwj-r/wbglmirror.git

## 环境信息
- micro-app版本：^0.8.11
- 主应用前端框架&版本： angular: 13.3.0
- 子应用前端框架&版本：html 
- 构建工具&版本：

**Comment by raoenhui** [comment]
怎么绑节点的代码可以发下吗？绑节点时选到子应用上的节点。
