### ISSUE TITLE
window变量隔离有问题、start options传递时机有误

### ISSUE THREAD

**Issue by Yubiao-Li** [jd-opensource/micro-app#86]
## 问题描述
> 问题的具体描述
父应用使用cdn引入vue，子应用使用node_modules引入vue，然后在子应用打印window.vue发现能够打印出来，预期应该是找不到vue的

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。
![image](https://user-images.githubusercontent.com/39786286/132310123-f74a35fd-e645-4283-adb8-588181b0c5ca.png)

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。
https://github.com/Yubiao-Li/micio-app-test/tree/window

## 环境信息
- micro-app版本：
- 基座应用的前端框架和版本：
- 子应用的前端框架和版本：
- 构建工具&版本：

**Comment by bailicangdu** [comment]
确实是有这个问题，沙箱中找不到的全局变量会兜底到外部window上查找，主要为了兼容 console, eval 等全局方法

**Comment by bailicangdu** [comment]
可以设置scopeProperties强制某些变量不兜底到外层window
![image](https://user-images.githubusercontent.com/20297227/132320734-43434457-c579-4591-a78c-d8987979b9f4.png)

**Comment by Yubiao-Li** [comment]
ok

**Comment by Yubiao-Li** [comment]
我发现在源码实现中有一个问题
![image](https://user-images.githubusercontent.com/39786286/132342324-8abdf6f4-8161-4fb5-bc2a-9731bc04a914.png)
如果在defineElement执行前dom元素已经被插入html（如ssr场景），connectedCallback会马上被触发，此时start传入的options不会被应用

**Comment by bailicangdu** [comment]
👍，这个问题我明天验证一下

**Comment by bailicangdu** [comment]
问题已修复，会在0.3.1版本中发布

**Comment by Yubiao-Li** [comment]
可以了，辛苦辛苦
