### ISSUE TITLE
基座vite 子应用vite 为什么只有第一次渲染micro-app组件会渲染子应用

### ISSUE THREAD

**Issue by zhanghan-cdns** [jd-opensource/micro-app#862]
只有第一次渲染会跳转子应用，基座再用vue-router跳转都无效，手动f5刷新就又可以刷新子应用了，请问是什么原因造成的
![image](https://github.com/micro-zoe/micro-app/assets/62645261/828bd129-f257-4c45-a0f3-da60dc551aef)

**Comment by zhanghan-cdns** [comment]
基座和子应用都是vue3+vite3，microapp版本为0.8.11

**Comment by zhanghan-cdns** [comment]
https://github.com/micro-zoe/micro-app/assets/62645261/38461836-4279-4c0d-b4d7-4d5bffe4dafd

**Comment by raoenhui** [comment]
0.8.11，版本还不支持iframe模式，vite打包的应用会有问题

**Comment by ThatDays** [comment]
我也是这种情况，基座应用vue3.0 ,子应用vite2.9+vue3.0，micro-app v0.6.11 ，打包后的文件也是这种情况，开发调试没有问题

第二个页面第一次打开[
![image](https://github.com/micro-zoe/micro-app/assets/38598889/31fe19da-cbed-4ff9-b84e-46d958a22461)
](url)
![image](https://github.com/micro-zoe/micro-app/assets/38598889/23e30355-036e-4205-b978-c966d72d836e)
刷新后打开
![image](https://github.com/micro-zoe/micro-app/assets/38598889/256343c2-718d-4229-bf92-727acfdde04b)
![image](https://github.com/micro-zoe/micro-app/assets/38598889/4954dfcf-0400-4a7c-9aba-bfd18685826a)

**Comment by Rain20199** [comment]
碰到同样的问题  有解决吗？

**Comment by ThatDays** [comment]
micro-app升级到1.0使用新增iframe属性可以结局



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年10月15日 14:58 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [micro-zoe/micro-app] 基座vite 子应用vite 为什么只有第一次渲染micro-app组件会渲染子应用 (Issue #862) |

碰到同样的问题 有解决吗？

**Comment by ThatDays** [comment]
第二次加载页面是加载到了，但是里面的内容没有解析渲染，不确定是不是这样



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年10月15日 14:58 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [micro-zoe/micro-app] 基座vite 子应用vite 为什么只有第一次渲染micro-app组件会渲染子应用 (Issue #862) |

碰到同样的问题 有解决吗？
