### ISSUE TITLE
我在基座应用中 打开子应用，有时候会出现子应用样式加载不出来的问题，这个是什么原因呢

### ISSUE THREAD

**Issue by leex92** [jd-opensource/micro-app#864]
## 问题描述
> 问题的具体描述

## 复现步骤
1.
2.

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。

## 环境信息
- micro-app版本：  "@micro-zoe/micro-app": "^0.8.10",
- 主应用前端框架&版本：最新creact-react-app 搭建
- 子应用前端框架&版本：最新creact-react-app 搭建
- 构建工具&版本：

**Comment by raoenhui** [comment]
有报什么错吗？每个子应用的css加载不出来，还是部分css加载不出来？

**Comment by leex92** [comment]
> 有报什么错吗？每个子应用的css加载不出来，还是部分css加载不出来？

没有任何报错信息，就是css样式出不来，js功能这些都是正常的，这个问题很奇怪，这个对我很重要，项目快上线了，麻烦帮忙看看啥问题

**Comment by leex92** [comment]
低频率，项目组每个人都遇到过，有时候刚打开会出现，或者是放置久了刷新会出现。有没有可能是样式隔离里面的bug（整个子应用css都没加载进去，js的交互又是正常的），拜托优先帮忙看看这个问题


。忽尔今夏
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "micro-zoe/micro-app"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月1日(星期二) 下午3:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [micro-zoe/micro-app] 我在基座应用中 打开子应用，有时候会出现子应用样式加载不出来的问题，这个是什么原因呢 (Issue #864)





 
有报什么错吗？每个子应用的css加载不出来，还是部分css加载不出来？

**Comment by JackShijt** [comment]
我也遇到过，整个子应用都加载不出来，没有报错，一刷新页面又好了

**Comment by raoenhui** [comment]
网络问题，导致某个文件下载失败

**Comment by leex92** [comment]
> 网络问题，导致某个文件下载失败

直接没发起相应的请求？网络失败在请求列表里面应该能看到把

**Comment by leex92** [comment]
> 网络问题，导致某个文件下载失败

我发现了 <micro-app name='-ed2a-4140-a62e-6e76a30d4808'></micro-app> 
<micro-app name='cb51c5c-f060-4eae-b945-a46e2163b2e3'></micro-app> 异常的如上，传入uuid生成过后前面有一段消失了，第一个是异常显示，第二个是正常显示

**Comment by leex92** [comment]
`<micro-app name='-ed2a-4140-a62e-6e76a30d4808'></micro-app> <micro-app name='cb51c5c-f060-4eae-b945-a46e2163b2e3'></micro-app>`

**Comment by raoenhui** [comment]
name不能重复哈

**Comment by Kingwv** [comment]
> name不能重复哈

他的name没有重复啊，怎么问题就关闭了。后来怎么解决的，我也遇到了同样的问题

**Comment by html9527** [comment]
> > name不能重复哈
> 
> 他的name没有重复啊，怎么问题就关闭了。后来怎么解决的，我也遇到了同样的问题

你好,请问你的问题解决了吗?我也遇到了相同问题

**Comment by shonentropy3** [comment]
> > > name不能重复哈
> > 
> > 
> > 他的name没有重复啊，怎么问题就关闭了。后来怎么解决的，我也遇到了同样的问题
> 
> 你好,请问你的问题解决了吗?我也遇到了相同问题

解决了，文档里面对name做了限制，你可以仔细看下

**Comment by html9527** [comment]
> 我也遇到过，整个子应用都加载不出来，没有报错，一刷新页面又好了

你好,请问你的问题解决了吗?我也遇到了相同问题

**Comment by html9527** [comment]
> > > > name不能重复哈
> > > 
> > > 
> > > 他的name没有重复啊，怎么问题就关闭了。后来怎么解决的，我也遇到了同样的问题
> > 
> > 
> > 你好,请问你的问题解决了吗?我也遇到了相同问题
> 
> 解决了，文档里面对name做了限制，你可以仔细看下

具体是因为 name 值多个微前端应用重复了 是吗 您导致的原因?

**Comment by shonentropy3** [comment]
> > > > > name不能重复哈
> > > > 
> > > > 
> > > > 他的name没有重复啊，怎么问题就关闭了。后来怎么解决的，我也遇到了同样的问题
> > > 
> > > 
> > > 你好,请问你的问题解决了吗?我也遇到了相同问题
> > 
> > 
> > 解决了，文档里面对name做了限制，你可以仔细看下
> 
> 具体是因为 name 值多个微前端应用重复了 是吗 您导致的原因?

不是哈，是因为name不符合规则，你得name是啥 要不你加我给你说  421498437

**Comment by html9527** [comment]
> > > > > > name不能重复哈
> > > > > 
> > > > > 
> > > > > 他的name没有重复啊，怎么问题就关闭了。后来怎么解决的，我也遇到了同样的问题
> > > > 
> > > > 
> > > > 你好,请问你的问题解决了吗?我也遇到了相同问题
> > > 
> > > 
> > > 解决了，文档里面对name做了限制，你可以仔细看下
> > 
> > 
> > 具体是因为 name 值多个微前端应用重复了 是吗 您导致的原因?
> 
> 不是哈，是因为name不符合规则，你得name是啥 要不你加我给你说 421498437

谢谢朋友 是 wx 还是 qq 呢?
