### ISSUE TITLE
生产环境报require is not defined

### ISSUE THREAD

**Issue by houliang999** [jd-opensource/micro-app#867]
## 问题描述
引用第三方插件内部使用了require,开发环境下正常，生产环境require is not defined

## 复现步骤
1.
2.

## 环境信息
- micro-app版本：1.0.0-beta.5
- 主应用前端框架&版本：vite vue3
- 子应用前端框架&版本：vite vue3
- 构建工具&版本：vite 4.3.3

**Comment by raoenhui** [comment]
https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/sandbox?id=_2%e3%80%81%e5%ad%90%e5%ba%94%e7%94%a8%e6%8a%9b%e5%87%ba%e9%94%99%e8%af%af%e4%bf%a1%e6%81%af%ef%bc%9axxx-%e6%9c%aa%e5%ae%9a%e4%b9%89

**Comment by houliang999** [comment]
抱歉，这个是我的问题，vite对于require的语法不兼容
