### ISSUE TITLE
CSS Nesting support

### ISSUE THREAD

**Issue by Lionad-Morotar** [jd-opensource/micro-app#868]
## 问题描述

希望能支持原生 CSS 嵌套语法，鉴于现代浏览器已经开始支持 CSS 嵌套语法，见 [Can I Use](https://caniuse.com/?search=CSS%20Nesting)。

## 上传截图

当前版本的 micro-app 在解析 CSS Nesting 时会中断执行，见下图：
![image](https://github.com/micro-zoe/micro-app/assets/26913795/85fe8201-ffde-45b6-be44-06a79c24908e)

如果没有显式报错或在文档中说明，容易造成不易排查的线上问题。

## 环境信息

- micro-app版本：1.0.0-alpha.5

**Comment by CrystalAngelLee** [comment]
在项目中正常使用CSS Nesting是可以正常解析的哈

**Comment by CrystalAngelLee** [comment]
收到，我们会逐步支持

**Comment by Lionad-Morotar** [comment]
> 收到，我们会逐步支持

你好，请问一下预计是在什么版本会支持这个功能鸭

**Comment by Lionad-Morotar** [comment]
@bailicangdu Hello，增加了一个简单的实现及用例，能否帮忙 Review 一下代码
