### ISSUE TITLE
error事件抛出来这个错误： {"isTrusted":false} 是什么意思呢？

### ISSUE THREAD

**Issue by WadeZhu** [jd-opensource/micro-app#869]
## 问题描述
上线后查日志发现error事件时不时会被触发，但是error信息是 {"isTrusted":false} ，看不出来是因为什么原因导致了渲染失败。请问这是什么情况下才会出这个错呢？

**Comment by WadeZhu** [comment]
您好，你的邮件我已经收到。我将会仔细阅读，并尽快给您回复。

**Comment by raoenhui** [comment]
可以先截图下network报错信息
