### ISSUE TITLE
vite4  + vue3 作为子应用时，控制台报错The URL 'ws://:/child/vite/' is invalid.

### ISSUE THREAD

**Issue by w1687021088** [jd-opensource/micro-app#871]
## 问题描述
> 问题的具体描述
vite4  + vue3 作为子应用时，控制台报错The URL 'ws://:/child/vite/' is invalid.
## 复现步骤
1.
基座设置Next.js

```tsx
// _app.tsx
import type { AppProps } from 'next/app'
import microApp from '@micro-zoe/micro-app'
import { useEffect, useRef } from 'react'
import appStyle from '../style/home.module.css'
import '../style/globals.css'
import Sidebar from 'components/sidebar'
import config from '@/lib/config'

const App = ({ Component, pageProps }: AppProps) => {
  const init = useRef(true)
  useEffect(() => {
    if (init.current) {
      init.current = false
      // 初始化micro-app
      microApp.start({
        plugins: {
          modules: {
            'appname-vite': [
              {
                loader(code: string) {
                  if (process.env.NODE_ENV === 'development') {
                    // 这里 /basename/ 需要和子应用vite.config.js中base的配置保持一致
                    code = code.replace(/(from|import)(\s*['"])(\/child\/vite\/)/g, all => {
                      return all.replace('/child/vite/', config.vite_vue3_02)
                    })
                  }

                  return code
                }
              }
            ]
          }
        }
      })
    }
  }, [])
  return (
    <>
      <div id="router-container" className={appStyle.box1}>
        <Sidebar />
        <section>
          <Component {...pageProps} />
        </section>
      </div>
    </>
  )
}

export default App

```

配置 vite3 项目路由
```tsx
// /pages/vite_vue3/[[...]].tsx

/** @jsxRuntime classic */
/** @jsx jsxCustomEvent */
import jsxCustomEvent from '@micro-zoe/micro-app/polyfill/jsx-custom-event'

import React from 'react'
import { EventCenterForMicroApp } from '@micro-zoe/micro-app'
import config from '@/lib/config'

function Vue3() {
  const [microAppData, changeMicroAppData] = React.useState({ msg: '来自基座的数据' })
  const [show, changeShow] = React.useState(false)

  function handleCreate(): void {
    console.log('++++ handleCreate ++++ 创建了11111')
  }

  function handleBeforeMount(): void {
    console.log('++++ handleBeforeMount ++++ 即将被渲染')
  }

  function handleMount(): void {
    console.log('++++ handleMount ++++ 已经渲染完成')

    setTimeout(() => {
      changeMicroAppData({ msg: '来自基座的新数据' })
    }, 2000)
  }

  function handleUnmount(): void {
    console.log('child-vite 卸载了')
  }

  function handleError(): void {
    console.log('child-vite 加载出错了')
  }

  function handleDataChange(e: CustomEvent): void {
    console.log('来自子应用 child-vite 的数据:', e.detail.data)
  }

  React.useEffect(() => {
    // @ts-ignore
    if (!window.eventCenterForAppNameVite) {
      // @ts-ignore 因为vite子应用关闭了沙箱，我们需要为子应用appname-vite创建EventCenterForMicroApp对象来实现数据通信

      window.eventCenterForAppNameVite = new EventCenterForMicroApp('appname-vite')
    }

    changeShow(true)
  }, [])

  return (
    <>
      <div>
        {show && (
          <micro-app
            name="appname-vite"
            url={config.vite_vue3_02}
            inline={true}
            disablesandbox={true}
            data={microAppData}
            onCreated={handleCreate}
            onBeforemount={handleBeforeMount}
            onMounted={handleMount}
            onUnmount={handleUnmount}
            onError={handleError}
            onDataChange={handleDataChange}
          />
        )}
      </div>
    </>
  )
}

export default Vue3
```

2.
子应用
```ts

import './assets/main.css'

import { createApp } from 'vue'
import App from './App.vue'
import router from './router'

declare global {
  interface Window {
    eventCenterForAppNameVite: any
    __MICRO_APP_NAME__: string
    __MICRO_APP_ENVIRONMENT__: string
    __MICRO_APP_BASE_APPLICATION__: string
  }
}

function mount() {
  const app = createApp(App)

  app.use(router)

  app.mount('#vite-vue3')

  console.log('vite-vue3 子应用启动')

// 监听卸载操作
  window.addEventListener('unmount', function () {
    app.unmount()
    // 卸载所有数据监听函数
    window.eventCenterForAppNameVite?.clearDataListener()
    console.log('微应用child-vite卸载了')
  })
}

mount()
```

vite配置

```ts
import { fileURLToPath, URL } from 'node:url'
import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import { join } from 'path'
import { writeFileSync } from 'fs'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    vue(),
    (function () {
      let basePath = ''
      return {
        name: "vite:micro-app",
        apply: 'build',
        configResolved(config: any) {
          basePath = `${config.base}${config.build.assetsDir}/`
        },
        // writeBundle 钩子可以拿到完整处理后的文件，但已经无法修改
        writeBundle (options: any, bundle: any) {
          for (const chunkName in bundle) {
            if (Object.prototype.hasOwnProperty.call(bundle, chunkName)) {
              const chunk = bundle[chunkName]
              if (chunk.fileName && chunk.fileName.endsWith('.js')) {
                chunk.code = chunk.code.replace(/(from|import\()(\s*['"])(\.\.?\/)/g, (all: any, $1: any, $2: any, $3: any) => {
                  return all.replace($3, new URL($3, basePath))
                })
                const fullPath = join(options.dir, chunk.fileName)
                writeFileSync(fullPath, chunk.code)
              }
            }
          }
        },
      }
    })() as any,
  ],
  resolve: {
    alias: {
      '@': fileURLToPath(new URL('./src', import.meta.url))
    }
  },
  server: {
    port: 5008
  },
  base: `${process.env.NODE_ENV === 'production' ? 'http://www.xxx-sit.com' : ''}/child/vite/`,
  build: {
    outDir: 'vite',
  },
})

```

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。
<img width="402" alt="image" src="https://github.com/micro-zoe/micro-app/assets/38272529/1a123ed8-ae99-4799-845f-14d16ddcd396">

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。

## 环境信息
- micro-app版本：
- latest
- 主应用前端框架&版本：
- next.js12.2.3
- 子应用前端框架&版本：
- vite4.4.6
- 构建工具&版本：

**Comment by listener-dong** [comment]
同样的错误，vite版本高了，图片也获取不到，但是vite2.8.6没问题，很是头大

**Comment by ssx1477651687** [comment]
+1，vite3.0  css里面的图片加载的还是主服务
ts里面的图片，放到public下面可以拿到

**Comment by bolawen** [comment]
子应用  vite.config.ts


import { defineConfig } from 'vite';
import vue from '@vitejs/plugin-vue';
import { join } from 'path';
import { writeFileSync } from 'fs';

export default defineConfig({
  server: {
    port: 4007,
    headers: {
      'Access-Control-Allow-Origin': '*'
    }
  },
  base: `${
    process.env.NODE_ENV === 'production' ? 'https://bolawen.com' : ''
  }/vite-vue3-micro/`,
  build: {
    outDir: 'vite'
  },
  plugins: [
    vue(),
    (function () {
      let basePath = '';
      return {
        name: 'vite:micro-app',
        apply: 'build',
        configResolved(config) {
          basePath = `${config.base}${config.build.assetsDir}/`;
        },
        writeBundle(options, bundle) {
          for (const chunkName in bundle) {
            if (Object.prototype.hasOwnProperty.call(bundle, chunkName)) {
              const chunk = bundle[chunkName];
              if (chunk.fileName && chunk.fileName.endsWith('.js')) {
                chunk.code = chunk.code.replace(
                  /(from|import\()(\s*['"])(\.\.?\/)/g,
                  (all, $1, $2, $3) => {
                    return all.replace($3, new URL($3, basePath));
                  }
                );
                const fullPath = join(options.dir, chunk.fileName);
                writeFileSync(fullPath, chunk.code);
              }
            }
          }
        }
      };
    })() as any
  ]
});


子应用 main.ts


import { createApp, App as AppInstance } from 'vue';
import {
  createRouter,
  createWebHashHistory,
  RouterHistory,
  Router
} from 'vue-router';
import App from './App.vue';
import routes from './router';

declare global {
  interface Window {
    eventCenterForAppNameVite: any;
    __MICRO_APP_NAME__: string;
    __MICRO_APP_ENVIRONMENT__: string;
    __MICRO_APP_BASE_APPLICATION__: string;
  }
}

let app: AppInstance | null = null;
let router: Router | null = null;
let history: RouterHistory | null = null;
// 将渲染操作放入 mount 函数
function mount() {
  history = createWebHashHistory();
  router = createRouter({
    history,
    routes
  });

  app = createApp(App);
  app.use(router);
  app.mount('#vite-vue3-micro');

  console.log('微应用child-vite渲染了');
}

// 将卸载操作放入 unmount 函数
function unmount() {
  app?.unmount();
  history?.destroy();
  // 卸载所有数据监听函数
  window.eventCenterForAppNameVite?.clearDataListener();
  app = null;
  router = null;
  history = null;
  console.log('微应用child-vite卸载了');
}

// 微前端环境下，注册mount和unmount方法
if (window.__MICRO_APP_BASE_APPLICATION__) {
  // @ts-ignore
  window['vite-vue3-micro'] = { mount, unmount };
} else {
  // 非微前端环境直接渲染
  mount();
}


子应用 package.json

{
  "name": "vite-vue3",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "vue-tsc && vite build",
    "preview": "vite preview"
  },
  "dependencies": {
    "vue": "^3.3.4",
    "vue-router": "^4.0.13"
  },
  "devDependencies": {
    "@vitejs/plugin-vue": "^4.2.3",
    "typescript": "^5.0.2",
    "vite": "^4.4.5",
    "vue-tsc": "^1.8.5"
  }
}

**Comment by bolawen** [comment]
![image](https://github.com/micro-zoe/micro-app/assets/57985761/0455dcb6-9407-431e-ac48-385310439086)

**Comment by ssx1477651687** [comment]
+1 vite3同样问题，有这个报错

ts引用图片可以放入public里面
但是css里面的图片没办法，加载的还是主服务域名

**Comment by ufxelv80** [comment]
官方是不是不打算维护了，怎么就只兼容官方给出的demo版本，对高版本都不做支持，我基座是vue3.3版本，脚手架是vue-cli，然后子应用直接把官方给出的vite的demo接入之后页面能加载出来，但是一直在自己刷新页面，基座的代码也是和官方的demo一样，只是版vue的版本不同

**Comment by raoenhui** [comment]
> ![image](https://user-images.githubusercontent.com/57985761/260745826-0455dcb6-9407-431e-ac48-385310439086.png)

这个是不是热更新导致的，线上链接有这个报错吗

**Comment by raoenhui** [comment]
> +1 vite3同样问题，有这个报错
> 
> ts引用图片可以放入public里面 但是css里面的图片没办法，加载的还是主服务域名

css里面的图片用下绝对地址
