### ISSUE TITLE
[micro-app from runScript] app ****: TypeError: Illegal invocation

### ISSUE THREAD

**Issue by zzc369** [jd-opensource/micro-app#872]
## 背景
> 描述您希望改进的问题。
在使用 @tinymce/tinymce-vue 富文本编辑器时，只要一加载编辑器就报这个错，这个报错信息不够具体，无法定位到具体问题是什么

## 期望的效果
希望能有更具体的报错信息帮助定位

**Comment by raoenhui** [comment]
TS报错，可以单独打开子应用链接，看看是不是也有报错，来排查

**Comment by zzc369** [comment]
如果是TS报错的话，应该是不会阻塞渲染的，但是这个报错会阻塞渲染，子应用并没有这个报错，可以正常渲染，只有连接到主应用后会出现这个报错，下图是部署后的报错
<img width="1734" alt="image" src="https://github.com/micro-zoe/micro-app/assets/48020066/62a9485b-90eb-4ecd-8c30-b27c7737eb1e">

**Comment by zzc369** [comment]
> TS报错，可以单独打开子应用链接，看看是不是也有报错，来排查

如果是TS报错的话，应该是不会阻塞渲染的，但是这个报错会阻塞渲染，子应用并没有这个报错，可以正常渲染，只有连接到主应用后会出现这个报错，下图是部署后的报错
<img width="1734" alt="image" src="https://github.com/micro-zoe/micro-app/assets/48020066/62a9485b-90eb-4ecd-8c30-b27c7737eb1e">

**Comment by zzc369** [comment]
<img width="619" alt="image" src="https://github.com/micro-zoe/micro-app/assets/48020066/c2173c83-d025-4f30-a436-db016c393ec0">
这种问题有办法隔离上下文吗，或者其他的解决方式

**Comment by raoenhui** [comment]
@tinymce/tinymce-vue里面有没有改写原生方法，如改写了 Document.prototype.createElement之类的

**Comment by zzc369** [comment]
> @tinymce/tinymce-vue里面有没有改写原生方法，如改写了 Document.prototype.createElement之类的

这个不太清楚，可能是有的，这个应该怎么解决呢

**Comment by swing-t** [comment]
这个问题有解决方案了吗
