### ISSUE TITLE
基座：vite+react，子应用：vite+react，第一次进入页面成功，第二次进入就失败没渲染

### ISSUE THREAD

**Issue by zouyi741599086** [jd-opensource/micro-app#873]
只是测试下微应用，主应用跟子应用都是用同一个项目改造测试而已，主应用子应用路由都是hash模式
就算是第一次成功渲染了子应用也有报错，但是子应用能运行：
![image](https://github.com/micro-zoe/micro-app/assets/14175254/04340b65-a826-4d5b-a034-8ec15dab5c26)

![image](https://github.com/micro-zoe/micro-app/assets/14175254/33ee9dea-0a7d-4ba9-9719-2b3017e27677)
第二次第三次再次进入子应用，报错信息一样，但是没渲染子应用

![image](https://github.com/micro-zoe/micro-app/assets/14175254/7bd74c0a-f424-4f19-9c66-c87b62f11d64)

另外感觉microApp比qiankun、umi、无界都好用，最近研究微应用把几个主流的都测试了，坑都太多，microApp按照文档来一下就成功了，其它的微前端起码搞半天一天一上，就算搞起了也有很多问题，microApp目前只发现上面一个问题。

**Comment by raoenhui** [comment]
第二次进入是怎么进入的，
试下这几个方案：1、每次进入 name换成不同的  2、加destory，https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/configure?id=destroy

**Comment by zouyi741599086** [comment]
> 第二次进入是怎么进入的,试下这几个方案:1、每次进入名字换成不同的 2、加毁灭，[https://micro-Zoe . github . io/micro-app/docs . html #/zh-cn/configure？id =销毁](https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/configure?id=destroy)

正常进入呀，比如说有AB两个页面，A页面里面里面装的子应用，第一次进入A页面能正常渲染子应用，切换到B页面后在此回到A页面就无法渲染子应用了，你说的两个两个方法都试过了还是不行，并且在micro-app组件上新增key属性每次进入key的值不一样都还是不得行
