### ISSUE TITLE
子项目使用vite4版本，静态资源获取失败

### ISSUE THREAD

**Issue by listener-dong** [jd-opensource/micro-app#876]
## 问题描述
主应用与子应用都是vite+vue的项目
子应用获取图片地址的时候用了基座的域名地址
在vite版本是2.8.6上使用时是正常显示图片
![image](https://github.com/micro-zoe/micro-app/assets/52540616/e41b6f24-1620-4fc5-9edc-dbb33152b0e2)

vite版本：4版本
micro版本：0.8.11

**Comment by raoenhui** [comment]
方案一：上传到服务器中，用绝对地址
方案二：https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/static-source?id=publicpath

**Comment by listener-dong** [comment]
> 方案一：上传到服务器中，用绝对地址 方案二：https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/static-source?id=publicpath

<img width="1051" alt="image" src="https://github.com/micro-zoe/micro-app/assets/52540616/2283b773-acf7-4cc3-9750-6ccb5d29bc2c">
用方案二，vite4下拿不到其他Micro-app的其他参数

**Comment by wangling404** [comment]
> 

方案2说的不是webpack构建的项目才能使用吗，上面说的不是vite4么，不适用吧？

**Comment by wangling404** [comment]
> 方案一：上传到服务器中，用绝对地址 方案二：https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/static-source?id=publicpath
方案2说的不是webpack构建的项目才能使用吗，上面说的不是vite4么，不适用吧？

**Comment by raoenhui** [comment]
方案二是不行。只能用方案一了

**Comment by ufxelv80** [comment]
vite4要区分开发环境和生产环境
![image](https://github.com/micro-zoe/micro-app/assets/120778315/5d4ba0af-b917-48d7-a47d-fd822c2246d1)

**Comment by listener-dong** [comment]
> vite4要区分开发环境和生产环境 ![image](https://user-images.githubusercontent.com/120778315/261789773-5d4ba0af-b917-48d7-a47d-fd822c2246d1.png)

如何使用呢？大佬

**Comment by ufxelv80** [comment]
> > vite4要区分开发环境和生产环境![图像](https://user-images.githubusercontent.com/120778315/261789773-5d4ba0af-b917-48d7-a47d-fd822c2246d1.png)
> 
> 怎么用呢？大佬

所有图片头存放在 assets 目录下，然后调用这个方法的时候直接传图片的名称，assets 目录在src目录下，这个方法的路径是 src > utils > index.ts

**Comment by yirelia** [comment]
> > > vite4要区分开发环境和生产环境![图像](https://user-images.githubusercontent.com/120778315/261789773-5d4ba0af-b917-48d7-a47d-fd822c2246d1.png)
> > 
> > 
> > 怎么用呢？大佬
> 
> 所有图片头存放在 assets 目录下，然后调用这个方法的时候直接传图片的名称，assets 目录在src目录下，这个方法的路径是 src > utils > index.ts

0.8.1 版本下子应用 建议可以是用下社区库 [vite-plugin-dynamic-base](https://www.npmjs.com/package/vite-plugin-dynamic-base)，
在子应用plugin  改下下应用前缀 
```
dynamicBase({
  // dynamic public path var string, default window.__dynamic_base__
  publicPath: 'window.__dynamic_base__',
  // dynamic load resources on index.html, default false. maybe change default true
  transformIndexHtml:  false
})
```
| 这个插件在打包后 被在子应用的html 注入一段script ，来改写静态文件地址


可以在基座应用上提前初始化 属性
window.__dynamic_base__ = 'xxxxxxx'

子应用的window 被代理了，所以 可以在子应用html 上重新初始化下 __dynamic_base__ 
```
<html>
<scirpt>
(function() {
window.__dynamic_base__  = window.rawWindow.__dynamic_base__  
})()
</script>
.....
</html>
```
可以看下是否可以解决你的问题
