### ISSUE TITLE
一定要通过浏览器网址才能确定子应用的路由吗?

### ISSUE THREAD

**Issue by codeh2o** [jd-opensource/micro-app#878]
如果我有两个vue页面:
http://test.com/a
http://test.com/b

a,b都是路由
我该怎么把http://test.com/a,http://test.com/b同时放到基座里?

**Comment by JackShijt** [comment]
基座baseroute="/a",子应用里"/"注册路由

**Comment by codeh2o** [comment]
为什么基座发送跳转指令让2个http://test.com分别跳转到
http://test.com/a
http://test.com/b
分别跳转后 会随机显示一个路由在浏览器里?有什么办法不显示路由再浏览器里吗?

**Comment by raoenhui** [comment]
两个vue页面是要放在同一个基座页面中吗？还是基座的不同页面中？

**Comment by ghost** [comment]
有同样的问题，能否在框架内隐藏子应用路由处理，不在浏览器url里显示
