### ISSUE TITLE
unocss引入问题

### ISSUE THREAD

**Issue by wangling404** [jd-opensource/micro-app#881]
## 问题描述
> vue3 + vite + ts  子应用 main.ts中引入 uno.css之后，生命周期都不执行，注释掉引用后就可以

## 复现步骤
1.
2.

## 上传截图
> <img width="702" alt="image" src="https://github.com/micro-zoe/micro-app/assets/25219906/aa529d94-b41e-4f65-96db-d6570a426b13">

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。

## 环境信息
- micro-app版本：1.0.5
- 主应用前端框架&版本：vue3 + vite4
- 子应用前端框架&版本：vue3 + vite4(vite2)
- 构建工具&版本：vite4/ vite2

**Comment by raoenhui** [comment]
查看下uno.css里面有什么特殊css写法吗？

**Comment by HLzhongxiao** [comment]
兄弟，问题解决了吗？我也遇到了这个问题

**Comment by aibayanyu20** [comment]
可以用vue-scoped模式来解决

**Comment by trry-hub** [comment]
> vue-scoped

怎么用，可以指点下么

**Comment by trry-hub** [comment]
> 兄弟，问题解决了吗？我也遇到了这个问题

解决了么
