### ISSUE TITLE
切换应用之后，React Dnd失效

### ISSUE THREAD

**Issue by guangmang** [jd-opensource/micro-app#882]
## 问题描述
> 有多个子应用存在时，当切换子应用再回来后，React dnd变成不可拖拽了。

- micro-app版本：0.81
- 主应用前端框架&版本：react 18
- 子应用前端框架&版本：react 18
- 构建工具&版本：webpack 5

**Comment by raoenhui** [comment]
当切换子应用再回来后,其他子应用有卸载吗？

**Comment by guangmang** [comment]
> 



> 当切换子应用再回来后,其他子应用有卸载吗？

没有，需要卸载其他子应用吗？

**Comment by raoenhui** [comment]
切换到其他子应用，含有DND的子应用有被完全卸载掉吗？然后把这个加上试试，https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/configure?id=destroy
