### ISSUE TITLE
子应用vue3不会触发onBeforeUnmount、onUnmount生命周期

### ISSUE THREAD

**Issue by Cmingqiu** [jd-opensource/micro-app#883]
"@micro-zoe/micro-app": "^0.8.11"
基座vue2 ，子应用vue3，在基座跳转路由的时候不会触发子应用的生命周期函数

**Comment by raoenhui** [comment]
我这边demo测试，生命周期是触发的
![image](https://github.com/micro-zoe/micro-app/assets/14011130/2f5bba66-c2da-4b21-bd75-ab8e25082ce5)
<img width="1310" alt="image" src="https://github.com/micro-zoe/micro-app/assets/14011130/274b1866-b177-4ac2-bc65-e97aae4dd3a6">

**Comment by yuanyongjie1995** [comment]
是组件卸载的生命两个周期 onBeforeUnmount、onUnmount
我这里项目里也是进不去这两个生命周期
