### ISSUE TITLE
子应用之间的路由跳转

### ISSUE THREAD

**Issue by ufxelv80** [jd-opensource/micro-app#884]
子应用如果一个是 vue 另外一个是 React 使用官方给出的方式跳转不了吗？
window.history.pushState(null, '', 'page2')

// 主动触发一次popstate事件
window.dispatchEvent(new PopStateEvent('popstate', { state: null }))

**Comment by raoenhui** [comment]
[通过数据通信控制跳转](https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/jump?id=%e6%96%b9%e5%bc%8f%e4%b8%80%e3%80%81%e9%80%9a%e8%bf%87%e6%95%b0%e6%8d%ae%e9%80%9a%e4%bf%a1%e6%8e%a7%e5%88%b6%e8%b7%b3%e8%bd%ac)

**Comment by ufxelv80** [comment]
> [通过数据通信控制跳转](https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/jump?id=%e6%96%b9%e5%bc%8f%e4%b8%80%e3%80%81%e9%80%9a%e8%bf%87%e6%95%b0%e6%8d%ae%e9%80%9a%e4%bf%a1%e6%8e%a7%e5%88%b6%e8%b7%b3%e8%bd%a

> [通过数据通信控制跳转](https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/jump?id=%e6%96%b9%e5%bc%8f%e4%b8%80%e3%80%81%e9%80%9a%e8%bf%87%e6%95%b0%e6%8d%ae%e9%80%9a%e4%bf%a1%e6%8e%a7%e5%88%b6%e8%b7%b3%e8%bd%ac)

好的，谢谢！！！
