### ISSUE TITLE
 应用keep-alive下，A子应用重复切换到B子应用的同一个页面，第二次无法触发路由监听

### ISSUE THREAD

**Issue by jianmu297** [jd-opensource/micro-app#887]
## 问题描述
> 应用keep-alive下，A子应用重复push到B子应用的同一个页面，第二次无法触发路由监听

## 复现步骤
1.A应用切换到B应用b1页面，b1创建渲染正常
2.b1切回A应用
3.A应用再次切换到B应用b1页面，由于B应用路由未发生变化，未发生路由跳转，所以也监听不到路由变化

## 期望实现
正常在单页面应用中，跳转新页面总会切换路由栈。但是微前端下，跳转到新页面会出现切换子应用，但子应用由于是keep-alive，加上当前页正是要跳转的页面，导致只是切换应用，没有触发路由跳转。。。该业务场景该如何处理

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。

## 环境信息
- micro-app版本：1,0.5 beta
- 主应用前端框架&版本：vue2
- 子应用前端框架&版本：vue2
- 构建工具&版本：webpack

**Comment by hsiangleev** [comment]
遇到同样的问题了

**Comment by tjyuanpeng** [comment]
A应用切到应用B的路由时，B应用router.replace重新触发一下路由跳转
或者还有一种方案
B应用响应路由的变化，无论是A应用的路径还有B应用的，这样也能响应到路由变化

可能的原因除了你说的
还有可能是页面内调用history.pushstate，不会触发popstate事件，导致应用间路由不同步
