### ISSUE TITLE
当我在子程序中，使用fetch请求接口时报错 TypeError: Failed to execute 'fetch' on 'Window': Illegal invocation

### ISSUE THREAD

**Issue by Ian-potter** [jd-opensource/micro-app#889]
"next": "13.4.16",
  "@micro-zoe/micro-app": "0.8.11",
当我在子应用中，使用fetch请求接口时报错
![image](https://github.com/micro-zoe/micro-app/assets/120541625/cc066787-9dcc-4fab-b319-b19493eb6ac1)

     ` <Button onClick={() => {
              window.fetch('https://aelf-node-sidechain-test1.aelf.io/api/blockChain/transactionResult?transactionId=d7e7b38d71617cb147845d2058d2a599f778d0eb28b7e83424644d5893b80985').then(res => res.json()).then(result => {
                console.log(result, 'url=====result===')
              })
                .catch(error => {
                  console.error(error, 'url=====result===error')
                })
            }}>button</Button>
`

 **请问我应该怎么做，才能在子应用中使用fetch**

**Comment by raoenhui** [comment]
试试这个 https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/questions?id=_11%e3%80%81%e5%ad%90%e5%ba%94%e7%94%a8%e5%9c%a8%e6%b2%99%e7%ae%b1%e7%8e%af%e5%a2%83%e4%b8%ad%e5%a6%82%e4%bd%95%e8%8e%b7%e5%8f%96%e5%88%b0%e5%a4%96%e9%83%a8%e7%9c%9f%e5%ae%9ewindow%ef%bc%9f

**Comment by Ian-potter** [comment]
> 试试这个 https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/questions?id=_11%e3%80%81%e5%ad%90%e5%ba%94%e7%94%a8%e5%9c%a8%e6%b2%99%e7%ae%b1%e7%8e%af%e5%a2%83%e4%b8%ad%e5%a6%82%e4%bd%95%e8%8e%b7%e5%8f%96%e5%88%b0%e5%a4%96%e9%83%a8%e7%9c%9f%e5%ae%9ewindow%ef%bc%9f

这样确实是可以拿到的， 我想确认一下，我能将window下的fetch替换成这种方式么？因为我应用及及第三方依赖应用都是使用fetch请求？ 感谢

**Comment by raoenhui** [comment]
可以用这个试试 https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/advanced?id=_1%e3%80%81%e8%87%aa%e5%ae%9a%e4%b9%89fetch
