### ISSUE TITLE
开发环境未报错，打包生产环境报错TypeError: Cannot destructure property 'row' of 'undefined' as it is undefined.

### ISSUE THREAD

**Issue by 520Qiuyu** [jd-opensource/micro-app#890]
## 问题描述
> 问题的具体描述
开发过程中没有啥问题，但是打包部署后，会出现TypeError: Cannot destructure property 'row' of 'undefined' as it is undefined.、336b742c-f189-4b60-9918-423c996d0674:4 TypeError: Cannot read properties of undefined (reading '$index')等问题，在基座引用中，能触发子应用的生命周期，子应用也接受得到基座的数据，但是就是界面不显示，报错，请求也没有发送，他就开始渲染table

## 复现步骤
1.
2.

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。
生产环境
![image](https://github.com/micro-zoe/micro-app/assets/71555151/705d7ae3-bfd1-4a1c-b157-10d093fd99bd)
开发环境
![image](https://github.com/micro-zoe/micro-app/assets/71555151/cc5b949b-b5b1-4ea1-a6b3-5efe1eb92919)

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。

## 环境信息
- micro-app版本：^0.8.6
- 主应用前端框架&版本：Vue3 + vite2.9.5
- 子应用前端框架&版本：vue3+vite2.9.9
- 构建工具&版本：

**Comment by T0205** [comment]
这个issues 怎么关闭了?  解决的方法我看不到在哪啊 ?

**Comment by 520Qiuyu** [comment]
> 这个issues 怎么关闭了?  解决的方法我看不到在哪啊 ? 

注意一下执行顺序 我的问题是发送消息给子应用是同步的  加载子应用是异步的，在加载之前就发送了消息，导致出现异常
