### ISSUE TITLE
【子应用接入问题】子应用为多页面jQuery老项目

### ISSUE THREAD

**Issue by ghost** [jd-opensource/micro-app#891]
部分nginx配置如图：
![image](https://github.com/micro-zoe/micro-app/assets/73871391/24cf41dc-ae94-46a7-9122-dd8c3a519745)
基座应用使用方式：
![image](https://github.com/micro-zoe/micro-app/assets/73871391/253166e8-e597-460a-b3f5-c53a29d13882)
报错信息：
![image](https://github.com/micro-zoe/micro-app/assets/73871391/4cc4962e-7768-4057-8726-e76c8ad8a3be)

**Comment by raoenhui** [comment]
这个是跨域问题，需要静态资源支持跨域，https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/questions?id=_2%e3%80%81%e5%ad%90%e5%ba%94%e7%94%a8%e4%b8%80%e5%ae%9a%e8%a6%81%e6%94%af%e6%8c%81%e8%b7%a8%e5%9f%9f%e5%90%97%ef%bc%9f
