### ISSUE TITLE
升级到1.x后子应用加载报错

### ISSUE THREAD

**Issue by involker** [jd-opensource/micro-app#892]
## 问题描述
> 问题的具体描述
升级到最新版本的micro-app后，子应用使用了vuedraggable库加载报错

## 上传截图
> 
<img width="748" alt="image" src="https://github.com/micro-zoe/micro-app/assets/23690689/ea6da60b-9214-4fa9-a01e-08720195d68d">
<img width="860" alt="image" src="https://github.com/micro-zoe/micro-app/assets/23690689/47addf3a-18a8-47ab-ae08-9f8cd7cebfec">

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。

## 环境信息
- micro-app版本：1.0.0-beta.5
- 主应用前端框架&版本：vue@2.6.14
- 子应用前端框架&版本：vue@2.5.17、vuedraggable@2.23.2
- 构建工具&版本：

**Comment by Luolei1992** [comment]
降到0.8就好了

**Comment by devbian** [comment]
1.0不知道啥时候可以稳定。

**Comment by involker** [comment]
> 降到0.8就好了

想用1.x的虚拟路由功能来着😂😂

**Comment by raoenhui** [comment]
开启了iframe模式吗？

**Comment by involker** [comment]
> 开启了iframe模式吗？

没有
