### ISSUE TITLE
micro-app使用iframe模式不兼容Monaco-editor，点击子应用的代码输入框时，失去焦点选中

### ISSUE THREAD

**Issue by yuxuan-ctrl** [jd-opensource/micro-app#893]
## 问题描述
> 问题的具体描述

在子应用引入了monaco-editor，在子应用本身跑起来可以正常使用，获取到代码编辑器的焦点。可是在使用主应用访问时，代码编辑器失去焦点，不能点击。已经找到原因，会提一个PR，请审核处理~
## 复现步骤
1.子应用引入Monaco-editor
2.主应用访问并点击

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。

预期: 
![动画1](https://github.com/micro-zoe/micro-app/assets/83435945/22d5d4db-e16c-460d-a14a-b697b273df1f)
结果：
![success](https://github.com/micro-zoe/micro-app/assets/83435945/6eaf4b79-a468-450c-859a-5cdc26563f4a)

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。

## 环境信息
- micro-app版本：1.0.0-beta.5
- 主应用前端框架&版本：vue3
- 子应用前端框架&版本：vue3
- 构建工具&版本：vite4.2.2

**Comment by ghost** [comment]
@raoenhui @bailicangdu 
#895 此修复很有必要,会救了老命,大佬合并下吧

**Comment by raoenhui** [comment]
有没有精简的仓库，方便我测试下

**Comment by bailicangdu** [comment]
已合并，谢谢反馈

**Comment by raoenhui** [comment]
> @raoenhui @bailicangdu #895 此修复很有必要,会救了老命,大佬合并下吧

有没有精简的仓库，方便我测试下
