### ISSUE TITLE
按1.x文档修改配置，点击浏览器返回地址有误

### ISSUE THREAD

**Issue by Luolei1992** [jd-opensource/micro-app#899]
## 问题描述
> micro0.8改成到1.x版本后，主子应用多次切换后，点击浏览器返回会出现空白页，地址栏路由也不对

## 复现步骤
1. 主应用切换到子应用后，多次切换子应用路由home和test
2. 点击浏览器返回，多点几次就会出现
3. 只需启动main-app和child-app1即可复现

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。
![image](https://github.com/micro-zoe/micro-app/assets/23149226/e36b8001-2338-496f-8c2b-9242a3cdce35)

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。
[https://gitee.com/byll/microapp-vite-vue3-demo.git](url)

## 环境信息
- micro-app版本：v1.0.0-beta.5
- 主应用前端框架&版本：vue@3.2.37         vue-router@4.2.4
- 子应用前端框架&版本：vue@3.2.37         vue-router@4.2.4
- 构建工具&版本：vite@4.1.4

**Comment by zyf540860996** [comment]
强烈建议，主应用和子应用不要都使用vue3，路由各种问题

**Comment by zyf3166** [comment]
> 
因噎废食？

**Comment by Luolei1992** [comment]
是vue3的问题吗，还是vite的问题？官方有人解答下吗

**Comment by bailicangdu** [comment]
配置问题，vite升级参考 https://micro-zoe.com/docs/1.x/#/zh-cn/transfer 
<img width="804" alt="image" src="https://github.com/micro-zoe/micro-app/assets/20297227/a728e8d3-767b-4759-a2be-b86f21d51aed">

**Comment by Luolei1992** [comment]
![image](https://github.com/micro-zoe/micro-app/assets/23149226/6c440eeb-f077-42c8-bf2c-d48bb5333f50)
这个改了之后会出现新的问题

**Comment by bailicangdu** [comment]
描述的不是很清楚，点击test会重定向到home页？

**Comment by bailicangdu** [comment]
最新的代码同步一下

**Comment by Luolei1992** [comment]
![image](https://github.com/micro-zoe/micro-app/assets/23149226/a3fcdba3-c293-428f-8900-09abee077d24)
代码已同步

**Comment by bailicangdu** [comment]
因为在渲染子应用时没有指定地址，所以默认是首页，需要指定默认页面，写法如下：
<img width="860" alt="image" src="https://github.com/micro-zoe/micro-app/assets/20297227/35f27b85-9353-4c63-b4b6-9dcaccbe7174">

**Comment by Luolei1992** [comment]
多谢跳转的问题解决，还有两个新的疑问。
第一个，监听路由变化会执行两次
<img width="970" alt="image" src="https://github.com/micro-zoe/micro-app/assets/23149226/f7dc322a-53ec-44fe-8bd2-36bc20cd5cdb">

第二个，路由传参问题
<img width="1077" alt="image" src="https://github.com/micro-zoe/micro-app/assets/23149226/52c9802d-0646-46ed-8907-186816c1daa5">

**Comment by bailicangdu** [comment]
代码写的有问题吧，仔细检查一下吧

**Comment by XiaoDan12202** [comment]
我也有差不多的问题，切换另一个子应用B的时候，会把上一个子应用A的路由参数带到B上，导致路由乱了，能不把子应用的路由加到url上吗

**Comment by frankzhu0925** [comment]
> 强烈建议，主应用和子应用不要都使用vue3，路由各种问题
确实，天天踩屎坑

**Comment by world56** [comment]
同vue3有问题 = =！

**Comment by tiancantudousi** [comment]
子应用vite+vue3,也遇到了同样的问题

**Comment by bailicangdu** [comment]
vue3的冲突问题可以升级到最新版本解决 @tiancantudousi
