### ISSUE TITLE
个人优化意见

### ISSUE THREAD

**Issue by canyuegongzi** [jd-opensource/micro-app#9]
建议能够增加自定义子应用挂载的钩子函数，类似于 qiankun中的 getActiveRule。

**Comment by bailicangdu** [comment]
实现方式不同，暂时没有支持，不过这个思路可以借鉴一下

**Comment by canyuegongzi** [comment]
> 实现方式不同，暂时没有支持，不过这个思路可以借鉴一下

嗯嗯，感觉采用 getActiveRule 钩子函数的话，主应用能更好的把握子应用的挂载、卸载时机。
