### ISSUE TITLE
基座和子应用都是Vue项目的情况下，如何使用Vue.js devtools调试子应用呢

### ISSUE THREAD

**Issue by dai-yi-heng** [jd-opensource/micro-app#900]

**Comment by CrystalAngelLee** [comment]
可以尝试这个方法 https://github.com/vuejs/devtools/issues/64#issuecomment-238025184

**Comment by dai-yi-heng** [comment]
> 可以尝试这个方法 [vuejs/devtools#64 (comment)](https://github.com/vuejs/devtools/issues/64#issuecomment-238025184)

你有成功吗，能给我看下你的示例代码吗
