### ISSUE TITLE
线上子项目加载资源地址不正确

### ISSUE THREAD

**Issue by oydiligent** [jd-opensource/micro-app#901]
## 问题描述
> 问题的具体描述
壳项目vue3 + vite 3，子项目vue2.0 cli5.0 , 目前子项目加载不出来，控制台无报错，js资源type="module"

![image](https://github.com/micro-zoe/micro-app/assets/19690319/ca971af4-3661-45d5-aabc-b651b41db29a)

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。

## 环境信息
- micro-app版本：
- 主应用前端框架&版本：
- 子应用前端框架&版本：
- 构建工具&版本：

**Comment by raoenhui** [comment]
cli打包模式换成 no-moudle 模式试试

**Comment by oydiligent** [comment]
换了no-moudle就好了
