### ISSUE TITLE
有没有0.8.11的tag的包?

### ISSUE THREAD

**Issue by Plortinus** [jd-opensource/micro-app#903]
现在npm上的包是0.8.11的但是没有tag

**Comment by msojocs** [comment]
![image](https://github.com/micro-zoe/micro-app/assets/20937135/bebdd699-8c38-4270-abf2-d96116be1c12)

**Comment by raoenhui** [comment]
tag已打：https://github.com/micro-zoe/micro-app/tree/v0.8.11
