### ISSUE TITLE
主应用vue2  当子应用为vite时候，控制台加载异常会递归出大量的iframe 标签

### ISSUE THREAD

**Issue by hzfvictory** [jd-opensource/micro-app#904]
## 问题描述
> 问题的具体描述

主应用vue2  当子应用为vite时候，控制台加载异常会递归出大量的iframe 标签

## 复现步骤
1.
2.

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。
![image](https://github.com/micro-zoe/micro-app/assets/38562125/366a4b1c-446b-4ecf-936f-c7b6de61b38c)

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。

## 环境信息
- micro-app版本：1.0.5 beta 
- 主应用前端框架&版本：vue2
- 子应用前端框架&版本：vue3+vite 
- 构建工具&版本：webpack

**Comment by hzfvictory** [comment]
> Hello @hzfvictory. In order to facilitate location and troubleshooting, we need you to provide a realistic GitHub repository. 您好 @hzfvictory, 为了方便定位和排查问题，我们需要您提供一个重现实例，请提供一个尽可能精简的 GitHub 仓库地址。

配置项大致如下  子应用都是vite加vue3  ,子应用的域名跟主应用公用的一个  
```js
{
        path: '/content-app/*',
        name: 'ContentApp',
        component: 'ViteTemplate',
        meta: {
          title: '内容运营',
          micro: {
            name: 'content-app',
            baseroute: '/content-app/',
            url: 'https://xxx.com/content-app/',
            preFetch: true,
            iframe: true,
          },
        },
      },
      {
        path: '/activity-app',
        name: 'ActivityApp',
        component: 'HomeApp',
        meta: {
          title: '活动运营',
        },
      },
      {
        path: '/project-app/*',
        name: 'ProjectApp',
        component: 'ViteTemplate',
        meta: {
          title: '项目运营',
          micro: {
            name: 'project-app',
            baseroute: '/project-app/',
            url: 'https://xxxx.com/project-app/',
            preFetch: true,
            iframe: true,
          },
        },
      },
      {
        path: '/strategy-app/*',
        name: 'StrategyApp',
        component: 'ViteTemplate',
        meta: {
          title: '策略中心',
          micro: {
            name: 'strategy-app',
            baseroute: '/strategy-app/',
            url: 'https://xxx.com/strategy-app/',
            preFetch: true,
            iframe: true,
          },
        },
      },
```

**Comment by bailicangdu** [comment]
基座和子应用域名相同，地址相同，基座的路由优先级高，相当于基座潜入基座，死循环了

**Comment by bailicangdu** [comment]
子应用的baseroute换一个值，不要和基座相同，否则部署到线上也会出问题
<img width="747" alt="image" src="https://github.com/micro-zoe/micro-app/assets/20297227/894da666-c48c-46d7-bbcf-d463c0016df3">

**Comment by hzfvictory** [comment]
> 基座和子应用域名相同，地址相同，基座的路由优先级高，相当于基座潜入基座，死循环了

对于这种情况 我改下 baseroute 就解决了吗 ；
还有我本地主子域名肯定不一样的  也出现死循环那种情况了

**Comment by hzfvictory** [comment]
> 基座和子应用域名相同，地址相同，基座的路由优先级高，相当于基座潜入基座，死循环了

![image](https://github.com/micro-zoe/micro-app/assets/38562125/63a1decd-7925-4a88-86b6-e90810c6348a)
这是本地的死循环 ， 我改了baseroute ,  还有主子也不是同域   还是有那个问题  

```
{
        path: '/content-app/*',
        name: 'ContentApp',
        component: 'ViteTemplate',
        meta: {
          title: '内容运营',
          micro: {
            name: 'content-app',
            baseroute: '/content-app/',
            url:'http://127.0.0.1:8836',
            preFetch: true,
            iframe: true,
          },
        },
      },
      {
        path: '/project-app/*',
        name: 'ProjectApp',
        component: 'ViteTemplate',
        meta: {
          title: '项目运营',
          micro: {
            name: 'project-app',
            baseroute: '/project-app/',
            url: 'http://127.0.0.1:8838',
            preFetch: true,
            iframe: true,
          },
        },
      },
      {
        path: '/strategy-app/*',
        name: 'StrategyApp',
        component: 'ViteTemplate',
        meta: {
          title: '策略中心',
          micro: {
            name: 'strategy-app',
            baseroute: '/strategy-app/',
            url: 'http://127.0.0.1:8839',
            preFetch: true,
            iframe: true,
          },
        },
      },
  {
        path: '/template-app/*',
        name: 'TemplateApp',
        component: 'ViteTemplate',
        meta: {
          title: '模板中心',
          micro: {
            name: 'template-app11111111',
            baseroute: '/template/',
            url: 'http://127.0.0.1:8839',
            preFetch: true,
            iframe: true,
          },
        },
      },
```

**Comment by bailicangdu** [comment]
死循环肯定循环嵌套，路由配置有问题导致的

**Comment by hzfvictory** [comment]
> 死循环肯定循环嵌套，路由配置有问题导致的

本地就剩这一个子应用了  ；  这个配置路由、域名 、 baseroute都不一样 也还是死循环

 {
        path: '/template-app/*',
        name: 'TemplateApp',
        component: 'ViteTemplate',
        meta: {
          title: '模板中心',
          micro: {
            name: 'ttttttemplate-app11111111',
            baseroute: '/template/',
            url: 'http://127.0.0.1:8839',
            preFetch: true,
            iframe: true,
          },
        },
      },

**Comment by bailicangdu** [comment]
能提供一个复现的demo吗

**Comment by hzfvictory** [comment]
> 能提供一个复现的demo吗

公司代码不好弄  我把vite的预渲染关闭就正常，但是性能太拉胯了

**Comment by hzfvictory** [comment]
> 基座和子应用域名相同，地址相同，基座的路由优先级高，相当于基座潜入基座，死循环了

<script>if(window.parent !== window) {window.stop()}</script>

看到其他issues 有提到加一行这个代码  加上后我这死循环也得到了解决。   这个是阻止iframe加载资源吗 ，或者说添加后会不会导致预加载失败

**Comment by bailicangdu** [comment]
> > 基座和子应用域名相同，地址相同，基座的路由优先级高，相当于基座潜入基座，死循环了
> 
> <script>if(window.parent !== window) {window.stop()}</script>
> 看到其他issues 有提到加一行这个代码 加上后我这死循环也得到了解决。 这个是阻止iframe加载资源吗 ，或者说添加后会不会导致预加载失败

阻止加载主应用资源的
