### ISSUE TITLE
Cannot read properties of undefined (reading 'location')

### ISSUE THREAD

**Issue by LvZhenXiang** [jd-opensource/micro-app#908]
## 问题描述
> 问题的具体描述
Cannot read properties of undefined (reading 'location')
## 复现步骤
1.在子应用加载完成之前主应用调用了replace

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。
![image](https://github.com/micro-zoe/micro-app/assets/86390786/877dbdda-0bc6-41e9-8c89-3fbac0ba4693)

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。

## 环境信息
- micro-app版本：1.0.0-alpha.10
- 主应用前端框架&版本：react ^18.2.0
- 子应用前端框架&版本：react ^18.2.0
- 构建工具&版本：

**Comment by bailicangdu** [comment]
新版本中已修复，详情参考 https://github.com/micro-zoe/micro-app/releases/tag/v1.0.0-beta.7
