### ISSUE TITLE
使用renderApp方法调用报错

### ISSUE THREAD

**Issue by hsiangleev** [jd-opensource/micro-app#909]
## 问题描述
> 直接使用renderApp方法调用会报错`SyntaxError: Cannot use import statement outside a module`

## 上传截图
> ![img](https://images.hsianglee.cn/ps1/3a01bc3f616f671504029b7b75fbf627.png)

## 环境信息
- micro-app版本："^1.0.0-beta.6",
- 主应用前端框架&版本：vue3-vite
- 子应用前端框架&版本：vue3-vite
- 构建工具&版本：vite4

**Comment by bailicangdu** [comment]
vite应用要切换iframe沙箱
<img width="479" alt="image" src="https://github.com/micro-zoe/micro-app/assets/20297227/b7eceadf-175a-499a-9f64-1cda9443be27">

**Comment by frankdou** [comment]
> vite应用要切换iframe沙箱 <img alt="image" width="479" src="https://user-images.githubusercontent.com/20297227/269280318-b7eceadf-175a-499a-9f64-1cda9443be27.png">

一样不起效的
