### ISSUE TITLE
使用renderApp渲染子应用的时候，keepAlive没效果

### ISSUE THREAD

**Issue by hsiangleev** [jd-opensource/micro-app#911]
## 问题描述
> 使用renderApp渲染子应用的时候，keepAlive没效果，但是使用标签的时候是可以的

## 上传截图
> ![20230923112557.png](https://images.hsianglee.cn/ps1/20230923112557.png)

## 环境信息
- micro-app版本："^1.0.0-beta.6",
- 主应用前端框架&版本：vue3-vite
- 子应用前端框架&版本：vue3-vite
- 构建工具&版本：vite4

**Comment by bailicangdu** [comment]
写法有问题，keepAlive --> keep-alive
<img width="772" alt="image" src="https://github.com/micro-zoe/micro-app/assets/20297227/05bd6956-b4f9-47f4-8a32-63b98fdaf0d2">
