### ISSUE TITLE
Firefox 子应用Antd 5 Select下拉选项和Tooltip无法展现到正确位置

### ISSUE THREAD

**Issue by bobfw** [jd-opensource/micro-app#913]
## 问题描述
> 问题的具体描述
子应用使用Vite + Antd 5，在Firefox就会出现Select和Tooltip 无法正确展示的bug，在chorme都是正常的
## 复现步骤
1. 使用组件即可

## 复现仓库
https://github.com/faner11/micro-app-demo
## 环境信息
- micro-app版本：v1.0.0-rc.0
- 主应用前端框架&版本：react 都是最新
- 子应用前端框架&版本：react antd都是最新
- 构建工具&版本：vite 4.49最新

**Comment by xuwei0930** [comment]
好久了，这个问题修不了啦？
