### ISSUE TITLE
为什么关闭disable-memory-router的情况下pathname后面会多了条“/”

### ISSUE THREAD

**Issue by LvZhenXiang** [jd-opensource/micro-app#918]
![image](https://github.com/micro-zoe/micro-app/assets/86390786/8adb18d9-c405-4166-bb8c-69ca1f1a75b5)

下面那个pathname是传给<micro-app />url的pathname 上面那个无论是在子应用中log出来的pathname或者是浏览器url栏中复制出来decodeURIComponent的后面都有“/” 是在第一次初始化后会出现这样的情况

micro-app版本：^1.0.0-beta.7
主应用前端框架&版本：react ^18.2.0
子应用前端框架&版本：react ^18.2.0

**Comment by bailicangdu** [comment]
有可能是前端框架加上的，效果是一样的
