### ISSUE TITLE
子应用是Vite+React，无法正常展示，@react-refresh报错

### ISSUE THREAD

**Issue by thesadboy** [jd-opensource/micro-app#920]
## 子应用是Vite+React，无法正常展示
> 报错：GET http://localhost:8000/@react-refresh net::ERR_ABORTED 404 (Not Found)
App.tsx:11 Uncaught Error: @vitejs/plugin-react can't detect preamble. Something is wrong. See https://github.com/vitejs/vite-plugin-react/pull/11#discussion_r430879201
    at App.tsx:11:5

## 复现步骤
1.主应用Vite4+Vue3
2.子应用Vite4+React18

## 上传截图
> 
![iShot_2023-09-28_17 41 44](https://github.com/micro-zoe/micro-app/assets/3643274/4e0a4726-10f9-4edf-8555-2508a9091046)

## 环境信息
- micro-app版本：1.0.0-rc.0
- 主应用前端框架&版本：vue@3.3.4
- 子应用前端框架&版本：react@18.2.0
- 构建工具&版本：vite@4.4.9

**Comment by thesadboy** [comment]
按照vite官方示例直接生成两个项目分别为vue和react，按照1.0版本完成基座应用和子应用的配置，Vue为基座引用，React为子应用即可复现。

**Comment by thesadboy** [comment]
只有关掉子应用的hmr才能正常

**Comment by bailicangdu** [comment]
开启iframe沙箱了吗

**Comment by thesadboy** [comment]
> 开启iframe沙箱了吗

开启了

**Comment by thesadboy** [comment]
尴尬了，是因为不小心开启了 disable-patch-request，请忽视。。。

**Comment by thesadboy** [comment]
尴尬了，是因为不小心开启了 disable-patch-request，请忽视。。。
