### ISSUE TITLE
主应用和子应用同时引用bootstrap，一些组件无法正常操作

### ISSUE THREAD

**Issue by futugyou** [jd-opensource/micro-app#921]
## 问题描述
> 问题的具体描述

## 复现步骤
1. 主应用react+vite， install react-bootstrap bootstrap
2. 子应用vue3+vite, install bootstrap
3. 两个应用均添加Dropdowns,paging之类需要js控制的组件
4. 当两个应用均import 'bootstrap'时，主应用正常，子应用无法操作
5. 主应用import，子应用不import时，主应用正常，子应用无法操作
6. 主应用不import，子应用import时，主应用无法操作，子应用正常

 
## 环境信息
- micro-app版本： ^1.0.0-rc.0
- 主应用前端框架&版本："react": "^18.2.0" "vite": "^4.4.9"
- 子应用前端框架&版本："vue": "^3.3.4", "vite": "^4.4.9",

**Comment by CrystalAngelLee** [comment]
可以提供一个复现仓库吗？我这边没有复现你这个问题

**Comment by futugyou** [comment]
> 可以提供一个复现仓库吗？我这边没有复现你这个问题

不能提供，不然我在提issues的时候就提供了
