### ISSUE TITLE
主应用会重复请求静态资源并取消

### ISSUE THREAD

**Issue by listener-dong** [jd-opensource/micro-app#922]
## 问题描述
主应用会重复请求静态资源并取消

## 复现步骤
1. 运行vite项目
2.

## 上传截图
<img width="1061" alt="image" src="https://github.com/micro-zoe/micro-app/assets/52540616/fbd9d410-2370-4ccb-98df-7321b472020b">

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。

## 环境信息
- micro-app版本：1.0正式版
- 主应用前端框架&版本：vite4+vue3
- 子应用前端框架&版本：vite4+vue3
- 构建工具&版本：

**Comment by bailicangdu** [comment]
没有复现，可以提供一个demo吗
