### ISSUE TITLE
主应用跟子应用引用相同文件（js/css）问题

### ISSUE THREAD

**Issue by Yowi** [jd-opensource/micro-app#925]
### 当前环境
```js
"vue": "^2.7.14",
"ant-design-vue": "^1.7.8",
"@micro-zoe/micro-app": "^0.8.4",
```

### 主应用配置
```js
microApp.start({
  plugins: {
    global: [
      {
        loader(code, url, options, info) {
          if ((url || "").indexOf("/xxx/antd.min.js") >= 0) {
            return `window.antd = antd;`;
          }
          return code;
        },
      },
    ],
  },
});
```

### 子应用配置
```js
// vue.config.js
  externals: {
    vue: "Vue",
    "vue-router": "VueRouter",
    vuex: "Vuex",
    moment: "moment",
    axios: "axios",
    "ant-design-vue": "antd"
  },

// index.html
<script type="text/javascript" src="/xxx/antd.min.js"></script>
```

### 问题
![image](https://github.com/micro-zoe/micro-app/assets/8690749/87e3dee6-00a1-49dc-8918-3f9f44ca49d2)

## 期望的效果

希望当主应用跟子应用都用相同文件时，可以正常使用插件`loader` 进行设置，例如：
```js
microApp.start({
  plugins: {
    global: [
      {
        loader(code, url, options, info) {
          if ((url || "").indexOf("/xxx/vue2-extra.js") >= 0) {
            return `
                window.Vue = Vue;
                window.Vuex = Vuex;
                window.axios = axios;
                window.antd = antd;
                ....
            `;
          }
          return code;
        },
      },
    ],
  },
});
```
但实际那么使用时，`axios` 跟 `antd` 均都会报错，是否我这种思路有什么问题？或者是否有更佳的方案提供？谢谢！

**Comment by bailicangdu** [comment]
vue、vuex都是挂在主应用window上的吗

**Comment by bailicangdu** [comment]
思路没问题，改成这样试试
<img width="768" alt="image" src="https://github.com/micro-zoe/micro-app/assets/20297227/46caa0da-a6af-4152-8ec2-47fcc6cac3cf">

**Comment by Yowi** [comment]
> vue、vuex都是挂在主应用window上的吗

是的，而且不止 vue、vuex，还有 vue-router, aixos, antd, 等都挂到主应用 window 上（我的主应用跟十几个子应用加载的js/css很多一样的），我之所以有这样设置是因为我设置了 `keep-alive` 属性+页签的方式之后，**内存得不到释放**。

![image](https://github.com/micro-zoe/micro-app/assets/8690749/6f7ec90c-bd38-4a24-9e68-f64254ae2314)

不知道是不是我姿势问题，所以我做了以下尝试与部分代码：

一、**关闭页签时销毁**：调用 `unmountApp` 事件。（没明显区别）
![image](https://github.com/micro-zoe/micro-app/assets/8690749/214abb62-f965-42ab-b0f9-342492b85ac0)

```js
import { unmountApp, getActiveApps } from "@micro-zoe/micro-app";

const removeTab = (appName) => {
   unmountApp(appName, { clearAliveState: true }); // <-- 这里是否需要改成 `destroy: true` ？
}
```

二、**设置公共文件**：设置 `globalAssets` 、`global` 属性。（毫无感觉）
```js
microApp.start({
  globalAssets: {
    js: ['js地址1', 'js地址2', ...],
  }
})
``` 

三、**子应用添加销毁事件**：关闭页签时，触发对应子应用添加销毁事件。（没啥用）
```js
    const unmount = () => {
      console.log("卸载微应用", window.__MICRO_APP_NAME__);
      if (app) {
        app.$destroy();
        app.$el.innerHTML = "";
        app = null;
      }
    };

    window.microApp.addDataListener((data) => {
      if (data?.key === "unmountApp") {
        unmount();
      }
    });
```

四、其他问题

1.  unmountApp(appName, { clearAliveState: true }); // <-- 这里是否需要改成 `destroy: true` ？有频繁切换加载子应用需求。
2. 有什么其他方式释放内存？
3. `keep-alive` 属性+页签的方式，是每一个页签tab，microApp 的 name 属性都不一样吗？（两个页签tab是同一个子应用情况）
4. 我这种情况下，需要关闭页签时调用子应用销毁事件吗？（unmount、app.$destroy();）

**Comment by bailicangdu** [comment]
1、keep-alive应用一直处于活动状态，不会释放内存，除非彻底销毁 2、多个tab对应的name最好保持一致 3、像你这种情况，不需要unmount应用，只需要在切换tab时控制子应用跳转就行，不需要频繁的卸载

**Comment by Yowi** [comment]
> 1、keep-alive应用一直处于活动状态，不会释放内存，除非彻底销毁 2、多个tab对应的name最好保持一致 3、像你这种情况，不需要unmount应用，只需要在切换tab时控制子应用跳转就行，不需要频繁的卸载

1、现在我每一个页签tab都是不同的 microApp name，因为我要 keep-alive 每一个页面，微前端的 name 随路由变化而变化。
2、「keep-alive应用一直处于活动状态，不会释放内存，除非彻底销毁」，我点击页签关闭时主应用调用 `unmountApp(appName, { clearAliveState: true });` 子应用调用 `app.$destroy();` unmount应用，但内存依然销毁不明显。
3、切换tab时我只是激活tab上的页面并不会卸载，点击页签上关闭按钮时才要卸载。

**Comment by bailicangdu** [comment]
内存问题参考 https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/framework/vue?id=_1%e3%80%81%e5%bc%80%e5%90%afumd%e6%a8%a1%e5%bc%8f%ef%bc%8c%e4%bc%98%e5%8c%96%e5%86%85%e5%ad%98%e5%92%8c%e6%80%a7%e8%83%bd
