### ISSUE TITLE
子应用页面不渲染

### ISSUE THREAD

**Issue by Rain20199** [jd-opensource/micro-app#927]
1.micro-app 的生命周期已执行,子应用单独也是可以访问的 
2.页面空白  没有渲染任何内容
3.基座是 vue3+webpack （vue-cli）创建的

<img width="796" alt="image" src="https://github.com/micro-zoe/micro-app/assets/56431955/7d27a223-48c9-4606-8251-246ea5416134">
<img width="803" alt="image" src="https://github.com/micro-zoe/micro-app/assets/56431955/e6ff7604-6445-4cc5-9c2e-3071d352b728">
<img width="646" alt="image" src="https://github.com/micro-zoe/micro-app/assets/56431955/4094f08a-7585-4a4c-a6f5-9501b624a173">
<img width="1428" alt="image" src="https://github.com/micro-zoe/micro-app/assets/56431955/d10a81e4-4164-4697-9368-38f0e20f4482">

**Comment by Rain20199** [comment]
好像找到原因了   1.0rc 版本的问题  回退到 0.8.11 版本 此问题消失

**Comment by bailicangdu** [comment]
0.8迁移到1.0需要修改相关配置 https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/transfer
