### ISSUE TITLE
关于主子应用都是vue3+vite时开发环境request代理跨域问题求解

### ISSUE THREAD

**Issue by xh-shen** [jd-opensource/micro-app#934]
子应用发送的ajax请求，出现跨域问题，请问有这方面的示例吗，主子应用怎么开发环境怎么配置ajax代理
<img width="766" alt="image" src="https://github.com/micro-zoe/micro-app/assets/68724515/b45bb0e2-2392-445a-91fa-94446af9ef53">

**Comment by xh-shen** [comment]
"@micro-zoe/micro-app": "1.0.0-rc.1"

**Comment by bailicangdu** [comment]
因为跨域请求带了cookie，那么Access-Control-Allow-Origin不能设置为*，必须指定域名，同时设置Access-Control-Allow-Credentials: true
