### ISSUE TITLE
关于部署后子应用资源加载的问题

### ISSUE THREAD

**Issue by KeyToLove** [jd-opensource/micro-app#936]
```tsx
export function App () {
  return (
    <div>
      <h1>子应用👇</h1>
      // name：应用名称, url：应用地址
      <micro-app name='vue-app' url='http://localhost:3000/'></micro-app>
      <micro-app name='react-app' url='http://localhost:8000/'></micro-app>
    </div>
  )
}
```
按照文档通过如上配置在本地环境下，使用React 作为主应用接入两个子应用vue-app(基于vue)、react-app（基于react）是ok的；

想请教一下在部署后主应用是如何加载子应用页面及其静态资源的？因为子应用配置的url都是固定的 `http://localhost:port`格式（这块url是否需要区分本地开发和构建进行动态调整?），文档nginx这一层配置上也没看到针对这类请求做转发处理，那么主应用是如何准确加载各子应用对应的资源的呢，希望有大佬解惑一下🙏

**Comment by bailicangdu** [comment]
开发环境一般用端口号区分，生产环境通常用域名，如果域名相同，则用path区分，需要配置nginx

**Comment by KeyToLove** [comment]
> 开发环境一般用端口号区分，生产环境通常用域名，如果域名相同，则用path区分，需要配置nginx

感谢答疑 😄 

我刚又仔细看了下文档中 【部署】章节的内容。 Nginx这一侧的配置没啥问题，基本就是做一个资源映射处理和给子应用添加允许跨域的请求头；

我的疑问在该章节示例仓库中对应部分代码里找到了答案
![image](https://github.com/micro-zoe/micro-app/assets/54970106/de6f44d2-9ab8-4cd8-9a4b-3341246db9cb)
示例地址：https://github.com/micro-zoe/micro-app-demo/tree/master

![image](https://github.com/micro-zoe/micro-app/assets/54970106/ff13cd39-f896-44f7-9953-b475005c95c9)
![image](https://github.com/micro-zoe/micro-app/assets/54970106/ff95fa68-0882-4e83-be37-2899df32b7ec)

- url是需要根据本地开发环境、部署环境做动态处理的
- 本地开发时指向子应用启动服务所在`ip:port`，部署时指向子应用静态资源真实部署的路径或经 nginx 侧处理

觉得url这块可以在部署章节多提一嘴补充一下；一开始我以为 `micro-app` 内部会自动根据所属环境结合 `name` `url` 等属性做处理 🤣
