### ISSUE TITLE
升级到 1.0.0-rc.1 后，子应用的 location 也被代理了，导致存量逻辑使用 location.origin、href 的地方都出问题了

### ISSUE THREAD

**Issue by kelvin-lemon** [jd-opensource/micro-app#937]
## 背景
升级到 1.0.0-rc.1 后，子应用的 location 也被代理了，导致存量逻辑使用 location.origin、href 的地方都出问题了

## 期望的效果
是否有配置还原 loaction

**Comment by bailicangdu** [comment]
vite应用吗

**Comment by kelvin-lemon** [comment]
> vite应用吗

不是 vite 应用，存量基于 webpack vue2 vue3，代码内之前有取 location.origin href 做上报以及跳转的逻辑，

升级到 1.0.0-rc.1 之前用的是 1.0.0-alpha.10 是正常的，

并且也禁用的虚拟路由：    'disable-memory-router': true, // 关闭虚拟路由系统；    'disable-patch-request': true, // 关闭对子应用请求的拦截

**Comment by jiaozhiye** [comment]
> > vite应用吗
> 
> 不是 vite 应用，存量基于 webpack vue2 vue3，代码内之前有取 location.origin href 做上报以及跳转的逻辑，
> 
> 升级到 1.0.0-rc.1 之前用的是 1.0.0-alpha.10 是正常的，
> 
> 并且也禁用的虚拟路由： 'disable-memory-router': true, // 关闭虚拟路由系统； 'disable-patch-request': true, // 关闭对子应用请求的拦截

我们这边也发现这个问题了，被代理的属性和之前不一样了，多了好多！

**Comment by bailicangdu** [comment]
@kelvin-lemon @jiaozhiye 能贴一下 location.origin href 相关代码吗，方便我们定位和解决问题

**Comment by kelvin-lemon** [comment]
> @kelvin-lemon @jiaozhiye 能贴一下 location.origin href 相关代码吗，方便我们定位和解决问题

![image](https://github.com/micro-zoe/micro-app/assets/49432472/8c3a8896-76b1-460f-a0f5-c9fbf27eac55)

最新的 micro app 版本，默认配置就可以复现。可以看这个demo代码：
[micro-demo.zip](https://github.com/micro-zoe/micro-app/files/13164265/micro-demo.zip)
@bailicangdu

**Comment by kelvin-lemon** [comment]
![image](https://github.com/micro-zoe/micro-app/assets/49432472/f886edee-f86d-400b-a782-becea4ef2d75)
看了下现在创建沙盒的逻辑里，createMicroLocation 是必须的步骤，根据子应用的 URL 创建了 location，在子应用内获取和之前就不一样了，实际还是希望获取到主应用的 location，否则存量逻辑就要全部检查一遍了

@bailicangdu

**Comment by bailicangdu** [comment]
了解你的意思，目前我们是完全模拟子应用单独运行的环境，但像你这样的location指向主应用的场景也存在，两种方式各有优缺点，我们会考虑一下最终选择那种方案

**Comment by kelvin-lemon** [comment]
> 了解你的意思，目前我们是完全模拟子应用单独运行的环境，但像你这样的location指向主应用的场景也存在，两种方式各有优缺点，我们会考虑一下最终选择那种方案

或者可以支持配置，现在这个逻辑下子应用内的逻辑还可以适配一下，如果有些外部依赖库例如上报这些 也有使用 location 的场景 就不太好适配

**Comment by bailicangdu** [comment]
> > 了解你的意思，目前我们是完全模拟子应用单独运行的环境，但像你这样的location指向主应用的场景也存在，两种方式各有优缺点，我们会考虑一下最终选择那种方案
> 
> 或者可以支持配置，现在这个逻辑下子应用内的逻辑还可以适配一下，如果有些外部依赖库例如上报这些 也有使用 location 的场景 就不太好适配

了解，我们会考虑一下

**Comment by jiaozhiye** [comment]
> > > 了解你的意思，目前我们是完全模拟子应用单独运行的环境，但像你这样的location指向主应用的场景也存在，两种方式各有优缺点，我们会考虑一下最终选择那种方案
> > 
> > 
> > 或者可以支持配置，现在这个逻辑下子应用内的逻辑还可以适配一下，如果有些外部依赖库例如上报这些 也有使用 location 的场景 就不太好适配
> 
> 了解，我们会考虑一下

子应用 location 被代理，给我们各项目组确实造成很大影响，都得去改动代码，咱官方能在下个版本修复一下吗，感谢！

**Comment by matinary** [comment]
感觉子应用location 默认指向子应用是合理的，但是也存在location指向主应用的场景，可以去添加配置或者其他对象来处理这种场景

**Comment by chenlong-io** [comment]
我觉得这种改变应该默认向下兼容，且给出配置，后面大点的版本更新再破坏，然后在版本升级文档上体现。

**Comment by bailicangdu** [comment]
问题已修复，升级到1.0.0-rc.4版本即可
