### ISSUE TITLE
由主模块跳转 子系统内存得不到释放

### ISSUE THREAD

**Issue by huoshanxue** [jd-opensource/micro-app#945]
子系统由主系统跳转后，页面内存得不到释放，操作后内存只增不减少，子系统单独单独访问内存能够及时释放。
版本由 0.8.4 升级到 1.0.0-rc.2 依旧是同样的问题。
这是什么问题，有没有遇到类似问题，目前有没有解决方案？

**Comment by xiangxinji** [comment]
解决了吗?

**Comment by bayuango** [comment]
同求
