### ISSUE TITLE
可否提供一下next.js的接入demo。。。

### ISSUE THREAD

**Issue by apf1111111** [jd-opensource/micro-app#96]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by bailicangdu** [comment]
基座还是子应用

**Comment by lileilei** [comment]
> 基座还是子应用

子应用吧，基座其实真不行再搞一个，应用基本上很难改造了

**Comment by youngjunning** [comment]
next.js 作为基座项目如何引入呢？

**Comment by bailicangdu** [comment]
参考文档 https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/framework/nextjs

**Comment by xiasiyong1** [comment]
@bailicangdu 

这个demo(https://github.com/micro-zoe/micro-app-demo)里面都是dev模式的呀,nextjs在prod模式下面还是有很多问题
