### ISSUE TITLE
如何在 angular16 的基座应用中通过路由加载子应用？

### ISSUE THREAD

**Issue by vanswang** [jd-opensource/micro-app#962]
github 仓库：https://github.com/vanswang/micro-app-angular-module

基础：基座应用和子应用都是 angular16 创建的。

问题：如何在 angular16 的基座应用中通过路由加载子应用？具体可看 github 仓库中的 angular16\host-ng16\src\app\app-routing.module.ts 文件内的 TODO

**Comment by bailicangdu** [comment]
默认情况下，将micro-app元素插入到html中就可以渲染了，不需要特殊配置

**Comment by vanswang** [comment]
> 默认情况下，将micro-app元素插入到html中就可以渲染了，不需要特殊配置

大佬是这样的，我是想在 html 里面不写 micro app 标签。然后在路由里面配置好之后通过点击菜单然后在 router outlet 里加载子应用，不知这样能否实现呢？

**Comment by bailicangdu** [comment]
这两者没有关系，micro-app并不依赖路由

**Comment by vanswang** [comment]
> 这两者没有关系，micro-app并不依赖路由

有点没太看懂，可能是我没解释清楚。是这样的，angular 的 routing 里面不是可以写一个 path 对应一个懒加载的 module 嘛，我想让第三方应用以这种形式加载。有个例子就是 module federation 里面有个 loadRemoteModule 的方式可以把第三方应用直接加载到主应用里面去。不知咱们 micro app 能有办法实现这个功能嘛？感谢大佬解答～

**Comment by bailicangdu** [comment]
在micro-app1.0版本中已经不依赖于路由进行渲染，你可以把它当作iframe标签使用，甚至当成div标签，这些标签怎么写micro-app就怎么写

**Comment by vanswang** [comment]
> 在micro-app1.0版本中已经不依赖于路由进行渲染，你可以把它当作iframe标签使用，甚至当成div标签，这些标签怎么写micro-app就怎么写

好嘞，大概理解了，感谢大佬解答～
