### ISSUE TITLE
如何在 angular16 的基座应用中弹窗打开子应用特定页面？

### ISSUE THREAD

**Issue by vanswang** [jd-opensource/micro-app#963]
如题，看到有个 issue [489](https://github.com/micro-zoe/micro-app/issues/489) 里面咱们有说支持这种形式，想问下咱们有示例代码嘛？

**Comment by bailicangdu** [comment]
如果没有关闭虚拟路由，可以通过default-page设置默认页面，https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/router?id=%e8%ae%be%e7%bd%ae%e9%bb%98%e8%ae%a4%e9%a1%b5%e9%9d%a2

**Comment by vanswang** [comment]
> 如果没有关闭虚拟路由，可以通过default-page设置默认页面，https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/router?id=%e8%ae%be%e7%bd%ae%e9%bb%98%e8%ae%a4%e9%a1%b5%e9%9d%a2

好嘞，感谢解答，我看一下文档尝试下～

**Comment by 260178** [comment]
设置default-page怎么才能离开的时候全部卸载，进入时重新初始化，现在进入一次离开后再次进入显示空白，页面上有警告element micro-app is already defined

**Comment by 260178** [comment]
@bailicangdu

**Comment by 260178** [comment]
试了destroy和cleardata没有用，还是会有警告
