### ISSUE TITLE
子应用里window上自定义属性读取的问题

### ISSUE THREAD

**Issue by mursumomo** [jd-opensource/micro-app#97]
子应用在index.html里面给window上赋值了很多属性，接入到父应用后，window上新增的属性都找不到，怎么解决？

![image](https://user-images.githubusercontent.com/43238460/133883444-8d0478d9-5ef1-46bb-9990-f048ab608473.png)
父应用里
![image](https://user-images.githubusercontent.com/43238460/133883460-c4407569-93b8-40be-b4b7-82dd2910c797.png)

**Comment by bailicangdu** [comment]
定义全局变量的方式是什么

**Comment by bailicangdu** [comment]
子应用的全局变量父应用无法获取

**Comment by bailicangdu** [comment]
可以通过插件系统解决
```js
microApp.start({
  plugins: {
    global: [{ escapeProperties: ['renderTime'] }]
  }
})
```

**Comment by mursumomo** [comment]
好的！感谢大佬，我试试
