### ISSUE TITLE
tinymce资源加载问题

### ISSUE THREAD

**Issue by zkch** [jd-opensource/micro-app#972]
1. 基座开启端口为5170，子应用开启端口为5180
2. 子应用部分富文本页面用到tinymce时，import了部分插件
<img width="420" alt="image" src="https://github.com/micro-zoe/micro-app/assets/20108479/eb03f0b4-b91a-4889-a701-4606a4689442">

3. 到路由到子应用的富文本页面时，会报以下错误：
<img width="900" alt="image" src="https://github.com/micro-zoe/micro-app/assets/20108479/1053f824-f5cc-472c-a6fc-62085aa1517c">
要如何修改才能让资源正确加载？

**Comment by gaojiangtao-git** [comment]
建议复现一个小demo出来，这样的话作者好排查问题

**Comment by hezhengliang** [comment]
目前本地vite开发环境应该可以解决：
- window.__MICRO_APP_ENVIRONMENT__来判断是否为微应用环境
- window.__MICRO_APP_PUBLIC_PATH__获取子应用的静态资源前缀
将skins相关css放到public文件夹下，本地开发环境在tinyMce初始化配置：

```js
const distUrl = window.__MICRO_APP_PUBLIC_PATH__.replace(/\/$/, '')
// tinymce options
{
   language_url: `${distUrl}/tinymce/langs/xxx.js`,
   content_css: `${distUrl}/tinymce/skins/content/default/content.min.css`,
   skin: 'oxide',
   skin_url: `${distUrl}/tinymce/skins/ui/oxide`,
   ...
}
```

**Comment by bailicangdu** [comment]
micro-app版本是多少？

**Comment by zkch** [comment]
> micro-app版本是多少？

1.0.0 rc1 跟 rc2 都试过一样的效果 @bailicangdu

**Comment by tinymins** [comment]
请问有 demo 吗，尝试复现了两天但是都很正常

**Comment by zkch** [comment]
由于子应用的tinymce加载静态资源时，会走基座应用的域名，所以把截图的静态资源文件也放一份到基座应用里面，并在子应用的tinymce配置 **skin_url** 指定绝对路径，所以暂时解决这个问题。
