### ISSUE TITLE
[Vue warn]: Invalid event arguments: event validation failed for event "mouseenter".

### ISSUE THREAD

**Issue by enmotion** [jd-opensource/micro-app#975]
主应用 vue3+vite
子应用 vue3+vite

为什么我嵌入后，在主应用中对按钮，输入框，交互时，浏览器会警告
[Vue warn]: Invalid event arguments: event validation failed for event "mouseenter". 类似这样的信息

是什么地方配置错误了吗？

**Comment by bailicangdu** [comment]
这是已知问题，对功能无影响，会在后续版本中修复

**Comment by Leovenn** [comment]
有同样的问题

**Comment by theores** [comment]
同样的问题。

**Comment by NNTYM** [comment]
同样的问题

**Comment by trry-hub** [comment]
同样的问题

**Comment by ahlzq** [comment]
还没修复

**Comment by Plutossy** [comment]
修复了吗？有洁癖
