### ISSUE TITLE
子应用的 window.__MICRO_APP_BASE_ROUTE__ 为 undefined

### ISSUE THREAD

**Issue by LouisGo** [jd-opensource/micro-app#98]
## 问题描述
> 使用 micro-app 传递了`baseroute` 结果子应用中 window.__MICRO_APP_BASE_ROUTE__ 为 undefined。虽然可以成功加载~

## 复现步骤
1. 
![image](https://user-images.githubusercontent.com/25026983/133883773-2d570837-46b7-4882-be60-30a341b862c2.png)
![image](https://user-images.githubusercontent.com/25026983/133883879-bfff782c-8886-4fa6-a70a-534f13808dda.png)
![image](https://user-images.githubusercontent.com/25026983/133883911-65cb9587-97e5-44de-b30f-7522aafebcf1.png)

2.

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。

## 环境信息
- micro-app版本：0.1.0
- 基座应用的前端框架和版本：react17 history模式
- 子应用的前端框架和版本：react17 history模式
- 构建工具&版本：create-react-app

**Comment by bailicangdu** [comment]
升级到micro-app最新版本

**Comment by LouisGo** [comment]
> 升级到micro-app最新版本

谢谢，刚在升级日志里找到关键词了~不过类似这种 BREAKING CHANGE 建议还是能在文档里注明一下会更好:)

**Comment by bailicangdu** [comment]
👍

**Comment by Planck-Ho** [comment]
> 升级到micro-app最新版本

v0.8.8还是存在

**Comment by bailicangdu** [comment]
> > 升级到micro-app最新版本
> 
> v0.8.8还是存在

vue-cli 5 ?

**Comment by decadef20** [comment]
> > > 升级到micro-app最新版本
> > 
> > 
> > v0.8.8还是存在
> 
> vue-cli 5 ?

vue cli 5.0.8  依旧有这个问题 @bailicangdu

**Comment by bailicangdu** [comment]
@decadef20 参考 https://cli.vuejs.org/zh/guide/browser-compatibility.html#%E7%8E%B0%E4%BB%A3%E6%A8%A1%E5%BC%8F

**Comment by jiangkaifree** [comment]
v0.8.10 还是存在获取不到，只能在 `start()` 后 获取到 `__MICRO_APP_BASE_APPLICATION__` , 我打印 了一下全局的 `window`, 也只发现了这个属性 `__MICRO_APP_BASE_APPLICATION__`,  不过我子应用是 `vite`
