### ISSUE TITLE
建议使用文档官网能完善下

### ISSUE THREAD

**Issue by mursumomo** [jd-opensource/micro-app#99]
## 背景
> 发现文档目前有三个地址

https://micro-zoe.github.io/micro-app

https://zeroing.jd.com/micro-app

https://cangdu.org/micro-app/

三个文档地址中，第一个文档相对来说较新
例如：高级功能中，内存优化的文档，其余两个地址的文档中没有提现

还有问题就是，三个文档地址，有时打开很快，有时打不开，也有可能跟网络有关

## 期望的效果

能有个真正的官网地址，而且文档更新及时，细节全面

**Comment by bailicangdu** [comment]
嗯，我们会尽量同步更新的

**Comment by mursumomo** [comment]
希望能做大做好，不然也不敢把这玩意用到项目中，会被老板怼的

**Comment by bailicangdu** [comment]
最近在忙着功能完善和问题修复，节后会对文档进一步完善的

**Comment by hanshu0513** [comment]
您好，请问这个示例是对的嘛？快速开始-> 3、分配一个路由给子应用 react部分有两个export default并且并未声明routes。比较疑惑，可以出个react的比较完整的demo吗？

**Comment by hanshu0513** [comment]
你好，请问这个示例是对的吗？快速开始> 3、有两个路由-给子响应部分导出默认的演示路由。比较疑惑，可以出个react的比较完整的演示吗？

**Comment by bailicangdu** [comment]
这里文档错误了，第二个export default 应该去掉，react的独立文档最近会补充，案例可以先参考这个：基座应用 https://github.com/micro-zoe/micro-app-demo/tree/master/main_apps/react16  子应用：https://github.com/micro-zoe/micro-app-demo/tree/master/child_apps/child-react16
