### ISSUE TITLE
【咨询】如何使用本地的静态资源注册子应用

### ISSUE THREAD

**Issue by huangrenfang** [jd-opensource/micro-app#994]
背景：
最近公司打算做一个PC客户端，客户端里的内容为微前端展示的TO B系统；
为了优化子应用的打开速度，打算注册的子应用url不放在远端，而是直接读取本地的静态资源以降低请求和加载的时间

诉求：
想了解micro app是否支持直接读本地资源（不是子应用起localhost服务的形式）打开子应用以及如何使用

**Comment by bailicangdu** [comment]
不支持，子应用必须有一个url地址
