### ISSUE TITLE
document.querySelector方法在removeDomScope之后未重置为基座的document

### ISSUE THREAD

**Issue by adntian** [jd-opensource/micro-app#995]
## 问题描述
> 问题的具体描述
子应用加载后，会重写document.querySelector方法，如果基座应用路由切换后，调用document.querySelector方法应该调用基座的document，此时主动解除元素document绑定：removeDomScope()

https://github.com/micro-zoe/micro-app/blob/e970ad1fe730a22ae9078a9fd048f3f560bdb382/src/libs/utils.ts#L405-L408

但是初始化documentProxy时，方法是这样的：
https://github.com/micro-zoe/micro-app/blob/e970ad1fe730a22ae9078a9fd048f3f560bdb382/src/sandbox/with/document.ts#L207-L233

先执行了       throttleDeferForSetAppName(appName) 方法，**而这个appName是在初始化时传入的，后续不会更新此变量**

https://github.com/micro-zoe/micro-app/blob/e970ad1fe730a22ae9078a9fd048f3f560bdb382/src/libs/utils.ts#L391-L398

那么在执行document.querySelector时，就会执行throttleDeferForSetAppName方法，此方法会设置setCurrentAppName

综合来说就是我调用removeDomScope时，setCurrentAppName为空值，但是我调用document.querySelector时，又重新设置了setCurrentAppName，执行下面代码的时候就无法进入return globalEnv.rawQuerySelector.call(_this, selectors) 代码段了
https://github.com/micro-zoe/micro-app/blob/e970ad1fe730a22ae9078a9fd048f3f560bdb382/src/source/patch.ts#L605-L620

## 复现步骤
1.全局配置：
```
{
        'disable-memory-router': true, // 关闭虚拟路由系统
        'disable-patch-request': true, // 关闭对子应用请求的拦截
}
```
2.子应用引入
```
    <micro-app :data="appData" name='subApp' :url='url' @afterhidden="afterHidden" @aftershow="afterShow" baseroute="/example/" keep-alive />
```

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。

## 环境信息
- micro-app版本：
- 主应用前端框架&版本：vue2.6.11
- 子应用前端框架&版本：vue2.6.11
- 构建工具&版本：

**Comment by adntian** [comment]
是否可以给removeDomScope提供一个参数等解决方法
```
// force: 为true时强制释放子应用对docuent的占用
removeDomScope( force = false ) {
    // ......
}
```
当然如果有副作用，在keep-alive变为show之前需要重置

**Comment by bailicangdu** [comment]
removeDomScope是给基座使用的方法，如果在执行后子应用立即调用document，会重新绑定作用域，你说的这种现象确实存在，是由于优先级不同造成的，通过参数来解决确实是一个好办法

**Comment by adntian** [comment]
> removeDomScope是给基座使用的方法，如果在执行后子应用立即调用document，会重新绑定作用域，你说的这种现象确实存在，是由于优先级不同造成的，通过参数来解决确实是一个好办法

我在使用的时候，是基座应用调用document的时候遇到的问题，removeDomScope也是基座调用的，由于使用了keep-alive，这时基座的document在mounted的时候就获取了，所以读取到的document就是错的，removeDomScope这种场景其实是不需要再访问子应用的情况下使用的

**Comment by bailicangdu** [comment]
新版本1.0.0-rc.4已支持，使用方式：

```js
import { removeDomScope } from '@micro-zoe/micro-app'

// 解除元素绑定，并且一定时间内阻止再次绑定
removeDomScope(true)
```

详情参考：https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/api?id=removedomscope
